import {Router,type Request} from 'express';
import type {PoolConnection,ResultSetHeader,RowDataPacket} from 'mysql2/promise';
import {query,transaction} from '../../config/database.js';
import {asyncHandler} from '../../middleware/error-handler.js';
import {requirePermission} from '../../middleware/require-permission.js';
import {HttpError} from '../../shared/http-error.js';
import {assertPermission,can,rbac,type PermissionScope} from '../rbac/rbac.service.js';

export const hrRouter=Router();
type Input=Record<string,unknown>;
const id=(v:unknown)=>{const x=String(v??'');if(!/^\d+$/.test(x)||x==='0')throw new HttpError(400,'Identifiant invalide.');return x};
const text=(v:unknown,label:string,required=false,max=190)=>{const x=typeof v==='string'?v.trim():'';if(required&&!x)throw new HttpError(400,`${label} obligatoire.`);if(x.length>max)throw new HttpError(400,`${label} trop long.`);return x||null};
const date=(v:unknown,label:string)=>{const x=String(v??'');if(!/^\d{4}-\d{2}-\d{2}$/.test(x)||Number.isNaN(Date.parse(`${x}T00:00:00Z`)))throw new HttpError(400,`${label} invalide.`);return x};
const positive=(v:unknown,label:string,scale=2)=>{const raw=String(v??'').trim();if(!/^\d+(?:\.\d+)?$/.test(raw))throw new HttpError(400,`${label} invalide.`);const n=Number(raw);if(!Number.isFinite(n)||n<=0)throw new HttpError(400,`${label} doit être supérieur à zéro.`);return n.toFixed(scale)};
const nonNegative=(v:unknown,label:string,scale=3)=>{const raw=String(v??'').trim();if(!/^\d+(?:\.\d+)?$/.test(raw))throw new HttpError(400,`${label} invalide.`);const n=Number(raw);if(!Number.isFinite(n)||n<0)throw new HttpError(400,`${label} ne peut pas être négatif.`);return n.toFixed(scale)};
const categoryCode=(v:unknown)=>{const value=String(v??'').trim().toUpperCase().replace(/[\s-]+/g,'_');if(!/^[A-Z0-9_]{1,50}$/.test(value))throw new HttpError(400,'Code catégorie invalide.');return value};
const pagination=(q:Input)=>{const page=Math.max(1,Math.min(100000,Number(q.page)||1)),pageSize=Math.max(1,Math.min(100,Number(q.pageSize)||20));return{page,pageSize,offset:(page-1)*pageSize}};
const scopeFor=async(r:Request,permission:string)=>r.rbac?.isSuperAdmin?'GLOBAL':await assertPermission(r,permission);
function agencyPredicate(r:Request,scope:PermissionScope|null,agencyAlias='a',userAlias?:string){
  if(scope==='GLOBAL')return{sql:'1=1',params:[]as any[]};
  if(scope==='CONCESSION')return{sql:`${agencyAlias}.concession_id=(SELECT concession_id FROM agencies WHERE id=?)`,params:[r.user!.agencyId]};
  if(scope==='AGENCY')return{sql:`${agencyAlias}.id=?`,params:[r.user!.agencyId]};
  if(scope==='OWN'&&userAlias)return{sql:`${userAlias}.id=?`,params:[r.user!.sub]};
  throw new HttpError(403,'Le scope OWN ne s’applique pas à cette opération collective.');
}
function budgetPredicate(r:Request,scope:PermissionScope|null){
  if(scope==='GLOBAL')return{sql:'1=1',params:[]as any[]};
  if(scope==='CONCESSION')return{sql:'COALESCE(b.concession_id,ba.concession_id)=(SELECT concession_id FROM agencies WHERE id=?)',params:[r.user!.agencyId]};
  if(scope==='AGENCY')return{sql:'b.scope_type=\'agency\' AND b.agency_id=?',params:[r.user!.agencyId]};
  throw new HttpError(403,'Le scope OWN ne s’applique pas aux budgets.');
}
async function audit(c:PoolConnection,r:Request,type:string,entityId:string,action:string,value:unknown){await c.execute(`INSERT INTO audit_logs(user_id,module,entity_type,entity_id,action,new_values,ip_address,user_agent) VALUES(?,'hr',?,?,?,?,?,?)`,[r.user!.sub,type,entityId,action,JSON.stringify(value),r.ip??null,r.get('user-agent')??null])}
async function assertAgencyTarget(r:Request,permission:string,agencyId:string){const scope=await scopeFor(r,permission);const p=agencyPredicate(r,scope,'a');const rows=await query<RowDataPacket[]>(`SELECT a.id FROM agencies a WHERE a.id=? AND a.is_active=TRUE AND ${p.sql}`,[agencyId,...p.params]);if(!rows[0])throw new HttpError(403,'Agence hors périmètre.');return rows[0]}
async function actorConcession(r:Request){const[rows]=await query<RowDataPacket[]>('SELECT concession_id FROM agencies WHERE id=?',[r.user!.agencyId]);if(!rows)throw new HttpError(403,'Agence de rattachement invalide.');return String(rows.concession_id)}
async function categoryManagementConcession(r:Request,requested?:unknown){const scope=await scopeFor(r,'hr.stock.manage');if(scope==='OWN'||scope==='AGENCY')throw new HttpError(403,'La gestion des catégories exige un scope CONCESSION ou GLOBAL.');if(scope==='CONCESSION')return actorConcession(r);return id(requested)}
async function employee(r:Request,permission:string,employeeId:string,lock?:PoolConnection){const scope=await scopeFor(r,permission),p=agencyPredicate(r,scope,'a','u'),sql=`SELECT ep.*,u.agency_id,a.concession_id FROM employee_profiles ep JOIN users u ON u.id=ep.user_id JOIN agencies a ON a.id=u.agency_id WHERE ep.id=? AND ${p.sql}${lock?' FOR UPDATE':''}`;const rows=lock?(await lock.execute<RowDataPacket[]>(sql,[employeeId,...p.params]))[0]:await query<RowDataPacket[]>(sql,[employeeId,...p.params]);if(!rows[0])throw new HttpError(404,'Employé introuvable dans votre périmètre.');return rows[0]}
async function stockItem(r:Request,permission:string,itemId:string,c?:PoolConnection,activeOnly=false){const scope=await scopeFor(r,permission),p=agencyPredicate(r,scope,'a'),sql=`SELECT i.* FROM internal_stock_items i JOIN agencies a ON a.id=i.agency_id WHERE i.id=?${activeOnly?' AND i.is_active=TRUE':''} AND ${p.sql}${c?' FOR UPDATE':''}`;const rows=c?(await c.execute<RowDataPacket[]>(sql,[itemId,...p.params]))[0]:await query<RowDataPacket[]>(sql,[itemId,...p.params]);if(!rows[0])throw new HttpError(404,activeOnly?'Article actif introuvable dans votre périmètre.':'Article introuvable dans votre périmètre.');return rows[0]}
async function budget(r:Request,permission:string,budgetId:string,c?:PoolConnection){const scope=await scopeFor(r,permission),p=budgetPredicate(r,scope),sql=`SELECT b.* FROM budgets b LEFT JOIN agencies ba ON ba.id=b.agency_id WHERE b.id=? AND ${p.sql}${c?' FOR UPDATE':''}`;const rows=c?(await c.execute<RowDataPacket[]>(sql,[budgetId,...p.params]))[0]:await query<RowDataPacket[]>(sql,[budgetId,...p.params]);if(!rows[0])throw new HttpError(404,'Budget introuvable dans votre périmètre.');return rows[0]}

hrRouter.get('/hr/employees',requirePermission('hr.employees.view'),asyncHandler(async(r,res)=>{
  const scope=await scopeFor(r,'hr.employees.view'),p=agencyPredicate(r,scope,'a','u'),{page,pageSize,offset}=pagination(r.query),params=[...p.params] as any[];let where=p.sql;
  if(r.query.status){const s=String(r.query.status);if(!['active','inactive','departed'].includes(s))throw new HttpError(400,'Statut invalide.');where+=' AND ep.employment_status=?';params.push(s)}
  if(r.query.agencyId){await assertAgencyTarget(r,'hr.employees.view',id(r.query.agencyId));where+=' AND u.agency_id=?';params.push(r.query.agencyId)}
  if(r.query.search){const q=`%${String(r.query.search).trim().slice(0,120)}%`;where+=' AND (CONCAT_WS(\' \',u.first_name,u.last_name) LIKE ? OR ep.employee_number LIKE ? OR ep.position_title LIKE ?)';params.push(q,q,q)}
  const context=await rbac(r),salaryAllowed=can(context,'hr.salary.view'),salaryScope=context.isSuperAdmin?'GLOBAL':context.permissions.get('hr.salary.view'),salaryVisibility=salaryAllowed?agencyPredicate(r,salaryScope??null,'a','u'):null;
  const salarySelection=salaryVisibility?`, CASE WHEN ${salaryVisibility.sql} THEN (SELECT sh.amount FROM salary_history sh WHERE sh.employee_profile_id=ep.id AND sh.effective_date<=CURDATE() ORDER BY sh.effective_date DESC,sh.id DESC LIMIT 1) ELSE NULL END current_salary`:'';
  const [countRows,rows]=await Promise.all([query<RowDataPacket[]>(`SELECT COUNT(*) total FROM employee_profiles ep JOIN users u ON u.id=ep.user_id JOIN agencies a ON a.id=u.agency_id WHERE ${where}`,params),query<RowDataPacket[]>(`SELECT ep.id,ep.employee_number,ep.position_title,ep.hire_date,ep.employment_status,ep.created_at,ep.updated_at,u.id user_id,u.first_name,u.last_name,u.email,u.phone,u.is_active account_active,a.id agency_id,a.name agency_name${salarySelection} FROM employee_profiles ep JOIN users u ON u.id=ep.user_id JOIN agencies a ON a.id=u.agency_id WHERE ${where} ORDER BY u.last_name,u.first_name LIMIT ? OFFSET ?`,[...(salaryVisibility?.params??[]),...params,pageSize,offset])]);
  res.json({items:rows.map(x=>({...x,id:String(x.id),user_id:String(x.user_id),agency_id:String(x.agency_id),current_salary:salaryAllowed&&x.current_salary!=null?Number(x.current_salary):undefined})),total:Number(countRows[0]?.total??0),page,pageSize});
}));

hrRouter.patch('/hr/employees/:id',requirePermission('hr.employees.manage'),asyncHandler(async(r,res)=>{
  const employeeId=id(r.params.id),body=r.body as Input,status=body.status==null?null:String(body.status);if(status&&!['active','inactive','departed'].includes(status))throw new HttpError(400,'Statut RH invalide.');
  await transaction(async c=>{const current=await employee(r,'hr.employees.manage',employeeId,c),sets:string[]=[],values:any[]=[];if(Object.hasOwn(body,'employeeNumber')){sets.push('employee_number=?');values.push(text(body.employeeNumber,'Matricule',true,50))}if(Object.hasOwn(body,'positionTitle')){sets.push('position_title=?');values.push(text(body.positionTitle,'Fonction',false,120))}if(Object.hasOwn(body,'hireDate')){sets.push('hire_date=?');values.push(date(body.hireDate,'Date d’embauche'))}if(status){sets.push('employment_status=?');values.push(status)}if(!sets.length)throw new HttpError(400,'Aucune modification valide.');sets.push('updated_by=?');values.push(r.user!.sub);await c.execute(`UPDATE employee_profiles SET ${sets.join(',')} WHERE id=?`,[...values,employeeId]);await audit(c,r,'employee',employeeId,'employee.updated',{before:{status:current.employment_status},status})});
  res.json({success:true});
}));

hrRouter.get('/hr/employees/:id/salaries',requirePermission('hr.salary.view'),asyncHandler(async(r,res)=>{const employeeId=id(r.params.id);await employee(r,'hr.salary.view',employeeId);const rows=await query<RowDataPacket[]>(`SELECT sh.id,sh.amount,sh.effective_date,sh.created_at,CONCAT_WS(' ',u.first_name,u.last_name) author_name FROM salary_history sh LEFT JOIN users u ON u.id=sh.created_by WHERE sh.employee_profile_id=? ORDER BY sh.effective_date DESC,sh.id DESC`,[employeeId]);res.json(rows.map(x=>({...x,id:String(x.id),amount:Number(x.amount)})))}));
hrRouter.post('/hr/employees/:id/salaries',requirePermission('hr.salary.manage'),asyncHandler(async(r,res)=>{const employeeId=id(r.params.id),amount=positive(r.body.amount,'Montant'),effectiveDate=date(r.body.effectiveDate,'Date d’effet');const salaryId=await transaction(async c=>{await employee(r,'hr.salary.manage',employeeId,c);try{const[result]=await c.execute<ResultSetHeader>('INSERT INTO salary_history(employee_profile_id,amount,effective_date,created_by) VALUES(?,?,?,?)',[employeeId,amount,effectiveDate,r.user!.sub]);await audit(c,r,'salary',String(result.insertId),'salary.created',{employeeId,amount,effectiveDate});return String(result.insertId)}catch(error:any){if(error?.code==='ER_DUP_ENTRY')throw new HttpError(409,'Un salaire existe déjà à cette date d’effet.');throw error}});res.status(201).json({id:salaryId,amount:Number(amount),effectiveDate})}));

hrRouter.get('/hr/stock-agencies',requirePermission('hr.stock.manage'),asyncHandler(async(r,res)=>{const scope=await scopeFor(r,'hr.stock.manage'),p=agencyPredicate(r,scope,'a'),rows=await query<RowDataPacket[]>(`SELECT a.id,a.name,a.code FROM agencies a WHERE a.is_active=TRUE AND ${p.sql} ORDER BY a.name`,p.params);res.json(rows.map(x=>({id:String(x.id),name:String(x.name),code:String(x.code)})))}));
hrRouter.get('/hr/internal-stock-categories',asyncHandler(async(r,res)=>{const context=await rbac(r),permission=can(context,'hr.stock.manage')?'hr.stock.manage':'hr.stock.view',scope=await scopeFor(r,permission);if(scope==='OWN')throw new HttpError(403,'Le scope OWN ne permet pas de consulter ce référentiel collectif.');const params:unknown[]=[];let where='1=1';if(scope!=='GLOBAL'){where='c.concession_id=(SELECT concession_id FROM agencies WHERE id=?)';params.push(r.user!.agencyId)}if(r.query.active==='true')where+=' AND c.is_active=TRUE';const rows=await query<RowDataPacket[]>(`SELECT c.id,c.concession_id,c.code,c.name,c.is_active,c.created_at,c.updated_at FROM internal_stock_categories c WHERE ${where} ORDER BY c.name,c.id`,params);res.json(rows.map(x=>({...x,id:String(x.id),concession_id:String(x.concession_id),is_active:Boolean(x.is_active)})))}));
hrRouter.post('/hr/internal-stock-categories',requirePermission('hr.stock.manage'),asyncHandler(async(r,res)=>{const b=r.body as Input,concessionId=await categoryManagementConcession(r,b.concessionId),name=text(b.name,'Nom catégorie',true,100)!,code=categoryCode(b.code);const categoryId=await transaction(async c=>{try{const[result]=await c.execute<ResultSetHeader>('INSERT INTO internal_stock_categories(concession_id,code,name,is_active) SELECT ?,?,?,TRUE FROM concessions WHERE id=? AND is_active=TRUE',[concessionId,code,name,concessionId]);if(!result.affectedRows)throw new HttpError(400,'Concession inexistante ou inactive.');await audit(c,r,'internal_stock_category',String(result.insertId),'stock.category.created',{concessionId,code,name});return String(result.insertId)}catch(error:any){if(error?.code==='ER_DUP_ENTRY')throw new HttpError(409,'Ce code catégorie existe déjà dans cette concession.');throw error}});res.status(201).json({id:categoryId})}));
hrRouter.patch('/hr/internal-stock-categories/:id',requirePermission('hr.stock.manage'),asyncHandler(async(r,res)=>{const categoryId=id(r.params.id),scope=await scopeFor(r,'hr.stock.manage');if(scope==='OWN'||scope==='AGENCY')throw new HttpError(403,'La gestion des catégories exige un scope CONCESSION ou GLOBAL.');const concessionId=scope==='CONCESSION'?await actorConcession(r):null,b=r.body as Input,name=text(b.name,'Nom catégorie',true,100)!,code=categoryCode(b.code);if(typeof b.isActive!=='boolean')throw new HttpError(400,'Statut catégorie invalide.');const isActive=b.isActive;await transaction(async c=>{const[rows]=await c.execute<RowDataPacket[]>(`SELECT id,concession_id,code,name,is_active FROM internal_stock_categories WHERE id=?${concessionId?' AND concession_id=?':''} FOR UPDATE`,[categoryId,...(concessionId?[concessionId]:[])]),current=rows[0];if(!current)throw new HttpError(404,'Catégorie introuvable dans votre périmètre.');try{await c.execute('UPDATE internal_stock_categories SET code=?,name=?,is_active=? WHERE id=?',[code,name,isActive,categoryId])}catch(error:any){if(error?.code==='ER_DUP_ENTRY')throw new HttpError(409,'Ce code catégorie existe déjà dans cette concession.');throw error}await audit(c,r,'internal_stock_category',categoryId,'stock.category.updated',{before:{code:current.code,name:current.name,isActive:Boolean(current.is_active)},after:{code,name,isActive}})});res.json({success:true})}));
hrRouter.get('/hr/internal-stock',requirePermission('hr.stock.view'),asyncHandler(async(r,res)=>{const scope=await scopeFor(r,'hr.stock.view'),p=agencyPredicate(r,scope,'a'),params=[...p.params] as unknown[];let where=p.sql;if(r.query.includeInactive!=='true')where+=' AND i.is_active=TRUE';if(r.query.agencyId){await assertAgencyTarget(r,'hr.stock.view',id(r.query.agencyId));where+=' AND i.agency_id=?';params.push(r.query.agencyId)}if(r.query.search){where+=' AND CONCAT_WS(\' \',i.designation,i.reference,c.name,i.category) LIKE ?';params.push(`%${String(r.query.search).trim().slice(0,120)}%`)}const rows=await query<RowDataPacket[]>(`SELECT i.*,COALESCE(c.name,i.category) category,c.code category_code,a.name agency_name,(i.current_quantity<=i.minimum_quantity) below_minimum FROM internal_stock_items i JOIN agencies a ON a.id=i.agency_id LEFT JOIN internal_stock_categories c ON c.id=i.category_id WHERE ${where} ORDER BY i.designation`,params);res.json(rows.map(x=>({...x,id:String(x.id),agency_id:String(x.agency_id),category_id:x.category_id==null?null:String(x.category_id),current_quantity:Number(x.current_quantity),minimum_quantity:Number(x.minimum_quantity),below_minimum:Boolean(x.below_minimum),is_active:Boolean(x.is_active)})))}));
hrRouter.post('/hr/internal-stock',requirePermission('hr.stock.manage'),asyncHandler(async(r,res)=>{const b=r.body as Input,agencyId=id(b.agencyId),categoryId=id(b.categoryId);await assertAgencyTarget(r,'hr.stock.manage',agencyId);const designation=text(b.designation,'Désignation',true)!,unit=text(b.unit,'Unité',true,40)!,minimum=nonNegative(b.minimumQuantity??0,'Stock minimum');const itemId=await transaction(async c=>{const[categories]=await c.execute<RowDataPacket[]>('SELECT c.id,c.name FROM internal_stock_categories c JOIN agencies a ON a.concession_id=c.concession_id WHERE c.id=? AND c.is_active=TRUE AND a.id=? FOR UPDATE',[categoryId,agencyId]),category=categories[0];if(!category)throw new HttpError(400,'Catégorie inactive, inexistante ou étrangère à la concession de l’agence.');const[result]=await c.execute<ResultSetHeader>('INSERT INTO internal_stock_items(agency_id,designation,reference,category,category_id,unit,minimum_quantity,created_by,updated_by) VALUES(?,?,?,?,?,?,?,?,?)',[agencyId,designation,text(b.reference,'Référence',false,100),category.name,categoryId,unit,minimum,r.user!.sub,r.user!.sub]);await audit(c,r,'internal_stock_item',String(result.insertId),'stock.item.created',{agencyId,categoryId,designation});return String(result.insertId)});res.status(201).json({id:itemId})}));
hrRouter.patch('/hr/internal-stock/:id/status',requirePermission('hr.stock.manage'),asyncHandler(async(r,res)=>{const itemId=id(r.params.id),value=r.body.isActive;if(typeof value!=='boolean')throw new HttpError(400,'Statut article invalide.');await transaction(async c=>{const current=await stockItem(r,'hr.stock.manage',itemId,c);await c.execute('UPDATE internal_stock_items SET is_active=?,updated_by=? WHERE id=?',[value,r.user!.sub,itemId]);await audit(c,r,'internal_stock_item',itemId,'stock.item.status.updated',{before:{isActive:Boolean(current.is_active)},after:{isActive:value}})});res.json({success:true,isActive:value})}));
hrRouter.get('/hr/internal-stock/:id/movements',requirePermission('hr.stock.view'),asyncHandler(async(r,res)=>{const itemId=id(r.params.id);await stockItem(r,'hr.stock.view',itemId);const rows=await query<RowDataPacket[]>(`SELECT m.*,CONCAT_WS(' ',u.first_name,u.last_name) author_name FROM internal_stock_movements m LEFT JOIN users u ON u.id=m.performed_by WHERE m.item_id=? ORDER BY m.movement_date DESC,m.id DESC`,[itemId]);res.json(rows.map(x=>({...x,id:String(x.id),item_id:String(x.item_id),agency_id:String(x.agency_id),quantity:Number(x.quantity),quantity_before:Number(x.quantity_before),quantity_after:Number(x.quantity_after)})))}));
hrRouter.post('/hr/internal-stock/:id/movements',asyncHandler(async(r,res)=>{const itemId=id(r.params.id),type=String(r.body.type??'');if(!['entry','exit'].includes(type))throw new HttpError(400,'Type de mouvement invalide.');const permission=type==='entry'?'hr.stock.entry':'hr.stock.exit';await assertPermission(r,permission);const quantity=positive(r.body.quantity,'Quantité',3),movementId=await transaction(async c=>{const item=await stockItem(r,permission,itemId,c,true),before=Number(item.current_quantity),after=type==='entry'?before+Number(quantity):before-Number(quantity);if(after<0)throw new HttpError(409,'Stock insuffisant pour cette sortie.');await c.execute('UPDATE internal_stock_items SET current_quantity=?,updated_by=? WHERE id=?',[after.toFixed(3),r.user!.sub,itemId]);const[result]=await c.execute<ResultSetHeader>('INSERT INTO internal_stock_movements(item_id,agency_id,movement_type,quantity,quantity_before,quantity_after,movement_date,reason,reference,performed_by) VALUES(?,?,?,?,?,?,COALESCE(?,NOW()),?,?,?)',[itemId,item.agency_id,type,quantity,before.toFixed(3),after.toFixed(3),r.body.movementDate?`${date(r.body.movementDate,'Date')} 00:00:00`:null,text(r.body.reason,'Motif',false,500),text(r.body.reference,'Référence',false,100),r.user!.sub]);await audit(c,r,'internal_stock_movement',String(result.insertId),`stock.${type}`,{itemId,quantity,before,after,agencyId:String(item.agency_id)});return String(result.insertId)});res.status(201).json({id:movementId})}));

hrRouter.get('/hr/budgets',requirePermission('hr.budget.view'),asyncHandler(async(r,res)=>{const scope=await scopeFor(r,'hr.budget.view'),p=budgetPredicate(r,scope);const rows=await query<RowDataPacket[]>(`SELECT b.*,a.name agency_name,c.name concession_name,COALESCE(SUM(e.amount),0) spent,b.initial_amount-COALESCE(SUM(e.amount),0) remaining FROM budgets b LEFT JOIN agencies ba ON ba.id=b.agency_id LEFT JOIN agencies a ON a.id=b.agency_id LEFT JOIN concessions c ON c.id=b.concession_id LEFT JOIN budget_expenses e ON e.budget_id=b.id WHERE ${p.sql} GROUP BY b.id ORDER BY b.start_date DESC,b.id DESC`,p.params);res.json(rows.map(x=>({...x,id:String(x.id),agency_id:x.agency_id==null?null:String(x.agency_id),concession_id:x.concession_id==null?null:String(x.concession_id),initial_amount:Number(x.initial_amount),spent:Number(x.spent),remaining:Number(x.remaining)})))}));
hrRouter.get('/hr/concessions',requirePermission('hr.budget.manage'),asyncHandler(async(r,res)=>{const scope=await scopeFor(r,'hr.budget.manage');if(scope==='OWN'||scope==='AGENCY')return res.json([]);const rows=await query<RowDataPacket[]>(`SELECT c.id,c.name FROM concessions c WHERE c.is_active=TRUE${scope==='CONCESSION'?' AND c.id=(SELECT concession_id FROM agencies WHERE id=?)':''} ORDER BY c.name`,scope==='CONCESSION'?[r.user!.agencyId]:[]);res.json(rows.map(x=>({id:String(x.id),name:String(x.name)})))}));
hrRouter.post('/hr/budgets',requirePermission('hr.budget.manage'),asyncHandler(async(r,res)=>{const b=r.body as Input,scopeType=String(b.scopeType??'');if(!['agency','concession'].includes(scopeType))throw new HttpError(400,'Portée budget invalide.');const scope=await scopeFor(r,'hr.budget.manage');let agencyId:string|null=null,concessionId:string|null=null;if(scopeType==='agency'){agencyId=id(b.agencyId);await assertAgencyTarget(r,'hr.budget.manage',agencyId)}else{concessionId=id(b.concessionId);if(scope==='OWN'||scope==='AGENCY')throw new HttpError(403,'Ce scope ne permet pas de créer un budget de concession.');const[allowed]=await query<RowDataPacket[]>(`SELECT c.id FROM concessions c WHERE c.id=? AND c.is_active=TRUE${scope==='CONCESSION'?' AND c.id=(SELECT concession_id FROM agencies WHERE id=?)':''}`,[concessionId,...(scope==='CONCESSION'?[r.user!.agencyId]:[])]);if(!allowed)throw new HttpError(403,'Concession hors périmètre.')}const start=date(b.startDate,'Date de début'),end=date(b.endDate,'Date de fin');if(start>end)throw new HttpError(400,'La date de fin doit suivre la date de début.');const amount=positive(b.initialAmount,'Montant initial'),label=text(b.label,'Libellé',true)!;const budgetId=await transaction(async c=>{const[result]=await c.execute<ResultSetHeader>('INSERT INTO budgets(scope_type,agency_id,concession_id,label,initial_amount,start_date,end_date,category,status,created_by,updated_by) VALUES(?,?,?,?,?,?,?,?,?,?,?)',[scopeType,agencyId,concessionId,label,amount,start,end,text(b.category,'Catégorie',false,100),'active',r.user!.sub,r.user!.sub]);await audit(c,r,'budget',String(result.insertId),'budget.created',{scopeType,agencyId,concessionId,amount});return String(result.insertId)});res.status(201).json({id:budgetId})}));
hrRouter.get('/hr/budgets/:id/expenses',requirePermission('hr.expense.view'),asyncHandler(async(r,res)=>{const budgetId=id(r.params.id);await budget(r,'hr.expense.view',budgetId);const rows=await query<RowDataPacket[]>(`SELECT e.*,CONCAT_WS(' ',u.first_name,u.last_name) author_name FROM budget_expenses e LEFT JOIN users u ON u.id=e.created_by WHERE e.budget_id=? ORDER BY e.expense_date DESC,e.id DESC`,[budgetId]);res.json(rows.map(x=>({...x,id:String(x.id),budget_id:String(x.budget_id),amount:Number(x.amount)})))}));
hrRouter.post('/hr/budgets/:id/expenses',requirePermission('hr.expense.create'),asyncHandler(async(r,res)=>{const budgetId=id(r.params.id),amount=positive(r.body.amount,'Montant'),expenseDate=date(r.body.expenseDate,'Date de dépense'),label=text(r.body.label,'Libellé',true)!;const expenseId=await transaction(async c=>{const b=await budget(r,'hr.expense.create',budgetId,c);if(String(b.status)!=='active')throw new HttpError(409,'Le budget n’est pas actif.');if(expenseDate<String(b.start_date)||expenseDate>String(b.end_date))throw new HttpError(409,'La dépense est hors de la période du budget.');const[spent]=await c.execute<RowDataPacket[]>('SELECT COALESCE(SUM(amount),0) total FROM budget_expenses WHERE budget_id=?',[budgetId]);const remaining=Number(b.initial_amount)-Number(spent[0]?.total??0);if(Number(amount)>remaining)throw new HttpError(409,'Montant supérieur au budget disponible.');const[result]=await c.execute<ResultSetHeader>('INSERT INTO budget_expenses(budget_id,label,amount,expense_date,category,reference,created_by) VALUES(?,?,?,?,?,?,?)',[budgetId,label,amount,expenseDate,text(r.body.category,'Catégorie',false,100),text(r.body.reference,'Référence',false,100),r.user!.sub]);await audit(c,r,'budget_expense',String(result.insertId),'expense.created',{budgetId,amount,remainingBefore:remaining});return String(result.insertId)});res.status(201).json({id:expenseId})}));

hrRouter.get('/hr/overview',requirePermission('hr.view'),asyncHandler(async(r,res)=>{const context=await rbac(r),result:Input={};if(can(context,'hr.employees.view')){const p=agencyPredicate(r,context.isSuperAdmin?'GLOBAL':context.permissions.get('hr.employees.view')??null,'a','u');const[row]=await query<RowDataPacket[]>(`SELECT COUNT(*) total FROM employee_profiles ep JOIN users u ON u.id=ep.user_id JOIN agencies a ON a.id=u.agency_id WHERE ep.employment_status='active' AND ${p.sql}`,p.params);result.activeEmployees=Number(row?.total??0)}if(can(context,'hr.salary.view')){const p=agencyPredicate(r,context.isSuperAdmin?'GLOBAL':context.permissions.get('hr.salary.view')??null,'a','u');const[row]=await query<RowDataPacket[]>(`SELECT COALESCE(SUM(sh.amount),0) total FROM employee_profiles ep JOIN users u ON u.id=ep.user_id JOIN agencies a ON a.id=u.agency_id JOIN salary_history sh ON sh.id=(SELECT x.id FROM salary_history x WHERE x.employee_profile_id=ep.id AND x.effective_date<=CURDATE() ORDER BY x.effective_date DESC,x.id DESC LIMIT 1) WHERE ep.employment_status='active' AND ${p.sql}`,p.params);result.payroll=Number(row?.total??0)}if(can(context,'hr.stock.view')){const p=agencyPredicate(r,context.isSuperAdmin?'GLOBAL':context.permissions.get('hr.stock.view')??null,'a');const[row]=await query<RowDataPacket[]>(`SELECT COUNT(*) items,SUM(i.current_quantity<=i.minimum_quantity) low FROM internal_stock_items i JOIN agencies a ON a.id=i.agency_id WHERE i.is_active=TRUE AND ${p.sql}`,p.params);result.stockItems=Number(row?.items??0);result.lowStockItems=Number(row?.low??0)}if(can(context,'hr.budget.view')){const p=budgetPredicate(r,context.isSuperAdmin?'GLOBAL':context.permissions.get('hr.budget.view')??null);const[row]=await query<RowDataPacket[]>(`SELECT COALESCE(SUM(b.initial_amount),0) total,COALESCE(SUM((SELECT COALESCE(SUM(e.amount),0) FROM budget_expenses e WHERE e.budget_id=b.id)),0) spent FROM budgets b LEFT JOIN agencies ba ON ba.id=b.agency_id WHERE b.status='active' AND ${p.sql}`,p.params);result.activeBudget=Number(row?.total??0);result.expenses=Number(row?.spent??0);result.remainingBudget=Number(row?.total??0)-Number(row?.spent??0)}res.json(result)}));

hrRouter.get('/hr/reporting',requirePermission('hr.reporting.view'),asyncHandler(async(r,res)=>{
  const context=await rbac(r),out:Input={};
  if(can(context,'hr.employees.view')){const p=agencyPredicate(r,context.isSuperAdmin?'GLOBAL':context.permissions.get('hr.employees.view')??null,'a','u');out.headcount=await query<RowDataPacket[]>(`SELECT a.id agency_id,a.name agency_name,COUNT(*) employees FROM employee_profiles ep JOIN users u ON u.id=ep.user_id JOIN agencies a ON a.id=u.agency_id WHERE ep.employment_status='active' AND ${p.sql} GROUP BY a.id,a.name ORDER BY a.name`,p.params)}
  if(can(context,'hr.salary.view')){const p=agencyPredicate(r,context.isSuperAdmin?'GLOBAL':context.permissions.get('hr.salary.view')??null,'a','u');out.payroll=await query<RowDataPacket[]>(`SELECT a.id agency_id,a.name agency_name,COALESCE(SUM(sh.amount),0) payroll FROM employee_profiles ep JOIN users u ON u.id=ep.user_id JOIN agencies a ON a.id=u.agency_id JOIN salary_history sh ON sh.id=(SELECT x.id FROM salary_history x WHERE x.employee_profile_id=ep.id AND x.effective_date<=CURDATE() ORDER BY x.effective_date DESC,x.id DESC LIMIT 1) WHERE ep.employment_status='active' AND ${p.sql} GROUP BY a.id,a.name ORDER BY a.name`,p.params)}
  if(can(context,'hr.stock.view')){const p=agencyPredicate(r,context.isSuperAdmin?'GLOBAL':context.permissions.get('hr.stock.view')??null,'a');out.stock=await query<RowDataPacket[]>(`SELECT a.id agency_id,a.name agency_name,COUNT(*) items,SUM(i.current_quantity<=i.minimum_quantity) low_items,COALESCE(SUM((SELECT COALESCE(SUM(m.quantity),0) FROM internal_stock_movements m WHERE m.item_id=i.id AND m.movement_type='entry')),0) entries,COALESCE(SUM((SELECT COALESCE(SUM(m.quantity),0) FROM internal_stock_movements m WHERE m.item_id=i.id AND m.movement_type='exit')),0) exits FROM internal_stock_items i JOIN agencies a ON a.id=i.agency_id WHERE ${p.sql} GROUP BY a.id,a.name`,p.params)}
  if(can(context,'hr.budget.view')){const p=budgetPredicate(r,context.isSuperAdmin?'GLOBAL':context.permissions.get('hr.budget.view')??null);out.budgets=await query<RowDataPacket[]>(`SELECT b.category,COALESCE(SUM(b.initial_amount),0) initial_amount,COALESCE(SUM((SELECT COALESCE(SUM(e.amount),0) FROM budget_expenses e WHERE e.budget_id=b.id)),0) spent FROM budgets b LEFT JOIN agencies ba ON ba.id=b.agency_id WHERE ${p.sql} GROUP BY b.category ORDER BY b.category`,p.params)}
  res.json(out);
}));

// Les montants et dates sont immuables en V1. Cette permission administre
// uniquement les métadonnées ; toute correction financière future devra être
// une annulation auditable plutôt qu'une réécriture de l'historique.
hrRouter.patch('/hr/expenses/:id',requirePermission('hr.expense.manage'),asyncHandler(async(r,res)=>{
  const expenseId=id(r.params.id),scope=await scopeFor(r,'hr.expense.manage'),p=budgetPredicate(r,scope),body=r.body as Input;
  await transaction(async c=>{const[rows]=await c.execute<RowDataPacket[]>(`SELECT e.id,e.budget_id,e.label,e.category,e.reference FROM budget_expenses e JOIN budgets b ON b.id=e.budget_id LEFT JOIN agencies ba ON ba.id=b.agency_id WHERE e.id=? AND ${p.sql} FOR UPDATE`,[expenseId,...p.params]),current=rows[0];if(!current)throw new HttpError(404,'Dépense introuvable dans votre périmètre.');const label=text(body.label,'Libellé',true)!,category=text(body.category,'Catégorie',false,100),reference=text(body.reference,'Référence',false,100);await c.execute('UPDATE budget_expenses SET label=?,category=?,reference=? WHERE id=?',[label,category,reference,expenseId]);await audit(c,r,'budget_expense',expenseId,'expense.metadata.updated',{before:{label:current.label,category:current.category,reference:current.reference},after:{label,category,reference}})});
  res.json({success:true});
}));
