import type {Request} from 'express';
import type {PoolConnection,ResultSetHeader,RowDataPacket} from 'mysql2/promise';
import {query,transaction} from '../../config/database.js';
import {HttpError} from '../../shared/http-error.js';
import {emitToAgenciesAndGlobals} from '../../realtime/socket.js';

export interface EffectiveLaborRate {id:string;baseRateId:string;code:string;label:string;hourlyRate:number;source:'concession'|'agency'}

const positiveId=(value:unknown,label='Identifiant')=>{const raw=String(value??'');if(!/^[1-9]\d*$/.test(raw))throw new HttpError(400,`${label} invalide`);return raw};
const code=(value:unknown)=>{const result=String(value??'').trim().toUpperCase();if(!/^[A-Z0-9][A-Z0-9._-]{0,49}$/.test(result))throw new HttpError(400,'Code barème invalide');return result};
const label=(value:unknown)=>{const result=String(value??'').trim();if(!result||result.length>150)throw new HttpError(400,'Libellé barème invalide');return result};
const amount=(value:unknown)=>{if(typeof value!=='number'||!Number.isFinite(value)||value<0)throw new HttpError(400,'Tarif horaire invalide');return value};
const order=(value:unknown)=>{const result=value==null?0:Number(value);if(!Number.isInteger(result)||result<0||result>1_000_000)throw new HttpError(400,"Ordre d'affichage invalide");return result};
const scope=(r:Request,permission:'settings.view'|'settings.update')=>r.rbac?.isSuperAdmin?'GLOBAL':r.rbac?.permissions.get(permission);
async function actorConcession(r:Request){const[row]=await query<RowDataPacket[]>('SELECT concession_id FROM agencies WHERE id=?',[r.user!.agencyId]);if(!row)throw new HttpError(400,'Agence de rattachement invalide');return String(row.concession_id)}
async function agencyContext(agencyId:string){const[row]=await query<RowDataPacket[]>('SELECT id,concession_id FROM agencies WHERE id=?',[agencyId]);if(!row)throw new HttpError(404,'Agence introuvable');return{id:String(row.id),concessionId:String(row.concession_id)}}
async function readableAgency(r:Request,value:unknown){const agencyId=positiveId(value??r.user!.agencyId,'Agence'),agency=await agencyContext(agencyId),permissionScope=scope(r,'settings.view'),ownConcession=await actorConcession(r);if(permissionScope==='OWN'||permissionScope==null)throw new HttpError(403,'Le scope OWN ne permet pas de consulter les barèmes collectifs');if(permissionScope==='AGENCY'&&agency.id!==String(r.user!.agencyId)||permissionScope==='CONCESSION'&&agency.concessionId!==ownConcession)throw new HttpError(403,'Agence hors du scope settings.view');return agency}
async function writableAgency(r:Request,value:unknown){const agencyId=positiveId(value??r.user!.agencyId,'Agence'),agency=await agencyContext(agencyId),permissionScope=scope(r,'settings.update'),ownConcession=await actorConcession(r);if(permissionScope==='OWN'||permissionScope==null)throw new HttpError(403,"Le scope OWN ne permet pas d'administrer les barèmes collectifs");if(permissionScope==='AGENCY'&&agency.id!==String(r.user!.agencyId)||permissionScope==='CONCESSION'&&agency.concessionId!==ownConcession)throw new HttpError(403,'Agence hors du scope settings.update');return agency}
async function writableConcession(r:Request,value?:unknown){const permissionScope=scope(r,'settings.update');if(permissionScope!=='CONCESSION'&&permissionScope!=='GLOBAL')throw new HttpError(403,'Le référentiel concession exige un scope CONCESSION ou GLOBAL');const own=await actorConcession(r),target=permissionScope==='GLOBAL'&&value!=null?positiveId(value,'Concession'):own;const[row]=await query<RowDataPacket[]>('SELECT id FROM concessions WHERE id=?',[target]);if(!row)throw new HttpError(404,'Concession introuvable');return target}
async function audit(c:PoolConnection,r:Request,entityId:string,action:string,oldValues:unknown,newValues:unknown){await c.execute('INSERT INTO audit_logs(user_id,module,entity_type,entity_id,action,old_values,new_values,ip_address,user_agent) VALUES(?,?,?,?,?,?,?,?,?)',[r.user!.sub,'settings','workshop_labor_rate',entityId,action,oldValues==null?null:JSON.stringify(oldValues),JSON.stringify(newValues),r.ip??null,r.get('user-agent')??null])}
async function emit(concessionId:string){const rows=await query<RowDataPacket[]>('SELECT id FROM agencies WHERE concession_id=?',[concessionId]);emitToAgenciesAndGlobals(rows.map(row=>String(row.id)),'settings:workshop-labor-rates-updated',{concessionId})}
const duplicate=(error:unknown)=>{if((error as {code?:string})?.code==='ER_DUP_ENTRY')throw new HttpError(409,'Ce code de barème existe déjà dans cette concession');throw error};

export async function effectiveLaborRates(agencyId:string,connection?:PoolConnection):Promise<EffectiveLaborRate[]>{
  const run=connection?async(sql:string,p:any[])=>(await connection.execute<RowDataPacket[]>(sql,p))[0]:query<RowDataPacket[]>;
  const rows=await run(`SELECT base.id base_id,base.code,base.label,base.hourly_rate concession_rate,override_rate.id override_id,override_rate.hourly_rate agency_rate,override_rate.is_active agency_active
    FROM agencies a JOIN workshop_labor_rates base ON base.concession_id=a.concession_id AND base.agency_id IS NULL
    LEFT JOIN workshop_labor_rates override_rate ON override_rate.parent_rate_id=base.id AND override_rate.agency_id=a.id AND override_rate.is_configured=TRUE
    WHERE a.id=? AND base.is_active=TRUE AND (override_rate.id IS NULL OR override_rate.is_active=TRUE)
    ORDER BY base.display_order,base.code`,[agencyId]);
  return rows.map(row=>({id:String(row.override_id??row.base_id),baseRateId:String(row.base_id),code:String(row.code),label:String(row.label),hourlyRate:Number(row.override_id?row.agency_rate:row.concession_rate),source:row.override_id?'agency':'concession'}));
}

export async function resolveEffectiveLaborRate(agencyId:string,laborRateId:unknown,connection?:PoolConnection){const id=positiveId(laborRateId,'Barème'),rates=await effectiveLaborRates(agencyId,connection),rate=rates.find(entry=>entry.id===id);if(!rate)throw new HttpError(400,"Barème inactif ou non applicable à l'agence de l'OR");return rate}
export async function resolveEffectiveLaborRateSelection(agencyId:string,selection:{laborRateId?:unknown;rateCode?:unknown},connection?:PoolConnection){const rates=await effectiveLaborRates(agencyId,connection);if(selection.laborRateId!=null){const id=positiveId(selection.laborRateId,'Barème'),rate=rates.find(entry=>entry.id===id);if(rate)return rate}else if(selection.rateCode!=null){const selectedCode=code(selection.rateCode),rate=rates.find(entry=>entry.code===selectedCode);if(rate)return rate}throw new HttpError(400,"Barème inactif ou non applicable à l'agence de l'OR")}

export async function listLaborRates(r:Request,agencyIdValue?:unknown){const agency=await readableAgency(r,agencyIdValue),rows=await query<RowDataPacket[]>(`SELECT base.id,base.code,base.label,base.hourly_rate,base.is_active,base.display_order,override_rate.id override_id,override_rate.hourly_rate override_hourly_rate,override_rate.is_active override_is_active
  FROM workshop_labor_rates base LEFT JOIN workshop_labor_rates override_rate ON override_rate.parent_rate_id=base.id AND override_rate.agency_id=? AND override_rate.is_configured=TRUE
  WHERE base.concession_id=? AND base.agency_id IS NULL ORDER BY base.display_order,base.code`,[agency.id,agency.concessionId]);return{agencyId:agency.id,rates:rows.map(row=>({id:String(row.id),code:row.code,label:row.label,concessionHourlyRate:Number(row.hourly_rate),isActive:Boolean(row.is_active),displayOrder:Number(row.display_order),agencyOverride:row.override_id?{id:String(row.override_id),hourlyRate:Number(row.override_hourly_rate),isActive:Boolean(row.override_is_active)}:null,effectiveHourlyRate:Number(row.override_id?row.override_hourly_rate:row.hourly_rate),effectiveIsActive:Boolean(row.is_active)&&(!row.override_id||Boolean(row.override_is_active)),source:row.override_id?'agency':'concession'}))}}

export async function createLaborRate(body:any,r:Request){const concessionId=await writableConcession(r,body?.concessionId),value={code:code(body?.code),label:label(body?.label),hourlyRate:amount(body?.hourlyRate),isActive:body?.isActive!==false,displayOrder:order(body?.displayOrder)};try{const id=await transaction(async c=>{const[result]=await c.execute<ResultSetHeader>('INSERT INTO workshop_labor_rates(concession_id,code,label,hourly_rate,is_active,display_order,created_by) VALUES(?,?,?,?,?,?,?)',[concessionId,value.code,value.label,value.hourlyRate,value.isActive,value.displayOrder,r.user!.sub]);await audit(c,r,String(result.insertId),'workshop_labor_rate.created',null,value);return String(result.insertId)});await emit(concessionId);return{id,...value}}catch(error){duplicate(error)}}

export async function updateLaborRate(rateIdValue:unknown,body:any,r:Request){const rateId=positiveId(rateIdValue,'Barème'),[existing]=await query<RowDataPacket[]>('SELECT * FROM workshop_labor_rates WHERE id=? AND agency_id IS NULL',[rateId]);if(!existing)throw new HttpError(404,'Barème concession introuvable');await writableConcession(r,existing.concession_id);const value={code:body?.code==null?String(existing.code):code(body.code),label:body?.label==null?String(existing.label):label(body.label),hourlyRate:body?.hourlyRate==null?Number(existing.hourly_rate):amount(body.hourlyRate),isActive:body?.isActive==null?Boolean(existing.is_active):Boolean(body.isActive),displayOrder:body?.displayOrder==null?Number(existing.display_order):order(body.displayOrder)};try{await transaction(async c=>{if(value.code!==existing.code){const[used]=await c.execute<RowDataPacket[]>('SELECT id FROM repair_order_estimate_items WHERE labor_rate_id=? UNION ALL SELECT id FROM repair_order_items WHERE labor_rate_id=? LIMIT 1',[rateId,rateId]);if(used[0])throw new HttpError(409,"Le code d'un barème déjà utilisé est immuable");await c.execute('UPDATE workshop_labor_rates SET code=? WHERE parent_rate_id=?',[value.code,rateId])}await c.execute('UPDATE workshop_labor_rates SET code=?,label=?,hourly_rate=?,is_active=?,display_order=? WHERE id=?',[value.code,value.label,value.hourlyRate,value.isActive,value.displayOrder,rateId]);await audit(c,r,rateId,'workshop_labor_rate.updated',existing,value)});await emit(String(existing.concession_id));return{id:rateId,...value}}catch(error){duplicate(error)}}

export async function setAgencyOverride(rateIdValue:unknown,body:any,r:Request){const rateId=positiveId(rateIdValue,'Barème'),agency=await writableAgency(r,body?.agencyId),[base]=await query<RowDataPacket[]>('SELECT * FROM workshop_labor_rates WHERE id=? AND agency_id IS NULL',[rateId]);if(!base)throw new HttpError(404,'Barème concession introuvable');if(String(base.concession_id)!==agency.concessionId)throw new HttpError(400,"Le barème n'appartient pas à la concession de l'agence");const value={hourlyRate:amount(body?.hourlyRate),isActive:body?.isActive!==false};const overrideId=await transaction(async c=>{const[old]=await c.execute<RowDataPacket[]>('SELECT * FROM workshop_labor_rates WHERE agency_id=? AND parent_rate_id=? FOR UPDATE',[agency.id,rateId]);await c.execute(`INSERT INTO workshop_labor_rates(concession_id,agency_id,parent_rate_id,code,label,hourly_rate,is_active,is_configured,display_order,created_by) VALUES(?,?,?,?,?,?,?,TRUE,?,?) ON DUPLICATE KEY UPDATE hourly_rate=VALUES(hourly_rate),is_active=VALUES(is_active),is_configured=TRUE,updated_at=CURRENT_TIMESTAMP`,[agency.concessionId,agency.id,rateId,base.code,base.label,value.hourlyRate,value.isActive,base.display_order,r.user!.sub]);const[current]=await c.execute<RowDataPacket[]>('SELECT id FROM workshop_labor_rates WHERE agency_id=? AND parent_rate_id=?',[agency.id,rateId]),saved=current[0];if(!saved)throw new HttpError(500,'Surcharge agence non persistée');await audit(c,r,String(saved.id),'workshop_labor_rate.override.updated',old[0]??null,{agencyId:agency.id,...value});return String(saved.id)});await emit(agency.concessionId);return{id:overrideId,agencyId:agency.id,...value}}

export async function clearAgencyOverride(rateIdValue:unknown,agencyIdValue:unknown,r:Request){const rateId=positiveId(rateIdValue,'Barème'),agency=await writableAgency(r,agencyIdValue),[base]=await query<RowDataPacket[]>('SELECT concession_id FROM workshop_labor_rates WHERE id=? AND agency_id IS NULL',[rateId]);if(!base||String(base.concession_id)!==agency.concessionId)throw new HttpError(404,'Barème concession introuvable');await transaction(async c=>{const[old]=await c.execute<RowDataPacket[]>('SELECT * FROM workshop_labor_rates WHERE agency_id=? AND parent_rate_id=? FOR UPDATE',[agency.id,rateId]);if(!old[0])return;await c.execute('UPDATE workshop_labor_rates SET is_configured=FALSE WHERE id=?',[old[0].id]);await audit(c,r,String(old[0].id),'workshop_labor_rate.override.cleared',old[0],{agencyId:agency.id,inherit:true})});await emit(agency.concessionId);return{rateId,agencyId:agency.id,inherited:true}}
