import type{Request}from'express';
import type{PoolConnection,ResultSetHeader,RowDataPacket}from'mysql2/promise';
import{query,transaction}from'../../config/database.js';
import{HttpError}from'../../shared/http-error.js';

const text=(value:unknown,label:string,max:number,required=false)=>{if(value==null||String(value).trim()===''){if(required)throw new HttpError(400,`${label} obligatoire`);return null}const result=String(value).trim();if(result.length>max)throw new HttpError(400,`${label} trop long`);return result};
const code=(value:unknown)=>{const result=text(value,'Code',50,true)!.toUpperCase();if(!/^[A-Z0-9][A-Z0-9_-]*$/.test(result))throw new HttpError(400,'Code constructeur invalide');return result};
const positive=(value:unknown,label:string,max:number)=>{if(value==null||value==='')return null;const number=Number(value);if(!Number.isInteger(number)||number<=0||number>max)throw new HttpError(400,`${label} invalide`);return number};
const ids=(value:unknown)=>{if(!Array.isArray(value))return[];const result=[...new Set(value.map(String))];if(result.some(id=>!/^[1-9]\d*$/.test(id)))throw new HttpError(400,'Marque invalide');return result};
const audit=(c:PoolConnection,r:Request,id:string,action:string,oldValue:unknown,newValue:unknown)=>c.execute("INSERT INTO audit_logs(user_id,module,entity_type,entity_id,action,old_values,new_values,ip_address,user_agent)VALUES(?,'settings','warranty_provider',?,?,?,?,?,?)",[r.user!.sub,id,action,oldValue==null?null:JSON.stringify(oldValue),JSON.stringify(newValue),r.ip??null,r.get('user-agent')??null]);
async function assignBrands(c:PoolConnection,providerId:string,brandIds:string[]){if(brandIds.length){const[rows]=await c.execute<RowDataPacket[]>(`SELECT id FROM brands WHERE id IN (${brandIds.map(()=>'?').join(',')}) FOR UPDATE`,brandIds);if(rows.length!==brandIds.length)throw new HttpError(400,'Une marque sélectionnée est introuvable')}await c.execute('UPDATE brands SET warranty_provider_id=NULL WHERE warranty_provider_id=?',[providerId]);if(brandIds.length)await c.execute(`UPDATE brands SET warranty_provider_id=? WHERE id IN (${brandIds.map(()=>'?').join(',')})`,[providerId,...brandIds]);}
export async function list(){const providers=await query<RowDataPacket[]>("SELECT p.*,GROUP_CONCAT(b.id ORDER BY b.name) brand_ids,GROUP_CONCAT(b.name ORDER BY b.name SEPARATOR ', ') brand_names FROM warranty_providers p LEFT JOIN brands b ON b.warranty_provider_id=p.id GROUP BY p.id ORDER BY p.name");const brands=await query<RowDataPacket[]>('SELECT id,name,code,warranty_provider_id FROM brands ORDER BY name');return{providers,brands}}
export async function create(body:any,r:Request){const name=text(body.name,'Nom',200,true)!,internalCode=code(body.code),months=positive(body.defaultWarrantyMonths,'Durée de garantie',240),mileage=positive(body.defaultMileageLimit,'Limite kilométrique',10000000),brandIds=ids(body.brandIds),available=Boolean(body.warrantyAvailable);return transaction(async c=>{try{const[x]=await c.execute<ResultSetHeader>('INSERT INTO warranty_providers(code,name,is_active,warranty_available,default_warranty_months,default_mileage_limit)VALUES(?,?,TRUE,?,?,?)',[internalCode,name,available,months,mileage]);const id=String(x.insertId);await assignBrands(c,id,brandIds);await audit(c,r,id,'manufacturer.created',null,{name,code:internalCode,available,months,mileage,brandIds});return{id}}catch(error:any){if(error?.code==='ER_DUP_ENTRY')throw new HttpError(409,'Ce code constructeur existe déjà');throw error}})}
export async function update(id:string,body:any,r:Request){const name=text(body.name,'Nom',200,true)!,internalCode=code(body.code),months=positive(body.defaultWarrantyMonths,'Durée de garantie',240),mileage=positive(body.defaultMileageLimit,'Limite kilométrique',10000000),brandIds=ids(body.brandIds),available=Boolean(body.warrantyAvailable);return transaction(async c=>{const[rows]=await c.execute<RowDataPacket[]>('SELECT * FROM warranty_providers WHERE id=? FOR UPDATE',[id]),before=rows[0];if(!before)throw new HttpError(404,'Constructeur introuvable');try{await c.execute('UPDATE warranty_providers SET code=?,name=?,warranty_available=?,default_warranty_months=?,default_mileage_limit=? WHERE id=?',[internalCode,name,available,months,mileage,id])}catch(error:any){if(error?.code==='ER_DUP_ENTRY')throw new HttpError(409,'Ce code constructeur existe déjà');throw error}await assignBrands(c,id,brandIds);await audit(c,r,id,'manufacturer.updated',before,{name,code:internalCode,available,months,mileage,brandIds});return{id}})}
export async function status(id:string,isActive:unknown,r:Request){if(typeof isActive!=='boolean')throw new HttpError(400,'Statut invalide');return transaction(async c=>{const[rows]=await c.execute<RowDataPacket[]>('SELECT * FROM warranty_providers WHERE id=? FOR UPDATE',[id]),before=rows[0];if(!before)throw new HttpError(404,'Constructeur introuvable');await c.execute('UPDATE warranty_providers SET is_active=? WHERE id=?',[isActive,id]);await audit(c,r,id,isActive?'manufacturer.reactivated':'manufacturer.disabled',before,{isActive});return{id,isActive}})}
