import React, { useEffect, useState } from 'react';
import type { Vehicle } from '../../types';
import { useUpdateVehicle, useVehicleReferencesQuery } from '../../api/erpHooks';
import { useAuthStore } from '../../stores/authStore';
import { useUiStore } from '../../stores/uiStore';
import { Modal } from '../../components/ui/Modal';
import { Button } from '../../components/ui/Button';
import { VehicleTransferModal } from './VehicleTransferModal';

interface Props { isOpen:boolean; onClose:()=>void; vehicle:Vehicle }
const typeToDb:Record<Vehicle['type'],'new'|'used'|'demo'|'courtesy'>={Neuf:'new',Occasion:'used','Démo':'demo','Véhicule de Courtoisie':'courtesy'};
const data=(vehicle:Vehicle)=>({vehicleType:typeToDb[vehicle.type],registrationNumber:vehicle.registrationNumber,bodyType:vehicle.bodyType,year:vehicle.year,firstRegistrationDate:vehicle.firstRegistrationDate?.slice(0,10)??'',color:vehicle.color,interiorColor:vehicle.interiorColor,fuelType:vehicle.fuel,engine:vehicle.engine??'',transmission:vehicle.transmission,fiscalPower:vehicle.fiscalPower,realPower:vehicle.realPower,co2Emissions:vehicle.co2Emissions,mileage:vehicle.mileage,supplierId:vehicle.supplierId??'',notes:vehicle.notes??'',purchasePrice:vehicle.purchasePriceHT,refurbishmentCost:vehicle.refurbishCostHT,transportCost:vehicle.transportCost??0,administrativeCost:vehicle.administrativeCost??0,additionalCosts:vehicle.additionalCosts??vehicle.otherCostsHT,catalogPrice:vehicle.catalogPriceHT,salePrice:vehicle.sellingPriceHT,minimumPrice:vehicle.minimumPriceHT,reason:''});

export const EditVehicleModal:React.FC<Props>=({isOpen,onClose,vehicle})=>{
  const [form,setForm]=useState(()=>data(vehicle)),[transferOpen,setTransferOpen]=useState(false),update=useUpdateVehicle(),references=useVehicleReferencesQuery(),toast=useUiStore(s=>s.addToast),canFinance=useAuthStore(s=>s.can('vehicles.financials.view')),canTransfer=useAuthStore(s=>s.can('vehicles.assign_agency'));
  useEffect(()=>{if(isOpen)setForm(data(vehicle))},[isOpen,vehicle]);
  const field=(name:keyof typeof form)=>(event:React.ChangeEvent<HTMLInputElement|HTMLSelectElement|HTMLTextAreaElement>)=>setForm(current=>({...current,[name]:event.target.type==='number'?Number(event.target.value):event.target.value}));
  const save=async(event:React.FormEvent)=>{event.preventDefault();try{const payload:Record<string,unknown>=canFinance?{...form}:Object.fromEntries(Object.entries(form).filter(([key])=>!['purchasePrice','refurbishmentCost','transportCost','administrativeCost','additionalCosts','catalogPrice','salePrice','minimumPrice','reason'].includes(key)));if(!['new','used'].includes(String(payload.vehicleType)))delete payload.vehicleType;await update.mutateAsync({id:vehicle.id,...payload});toast({type:'success',title:'Véhicule mis à jour',description:'Les caractéristiques ont été enregistrées.'});onClose()}catch(error){toast({type:'error',title:'Modification impossible',description:error instanceof Error?error.message:'Erreur API'})}};
  const fields:[keyof typeof form,string,string?][]=[['registrationNumber','Immatriculation'],['bodyType','Carrosserie'],['year','Année','number'],['firstRegistrationDate','Première mise en circulation','date'],['color','Couleur extérieure'],['interiorColor','Couleur intérieure'],['fuelType','Énergie'],['engine','Moteur'],['transmission','Transmission'],['fiscalPower','Puissance fiscale','number'],['realPower','Puissance réelle','number'],['co2Emissions','CO₂','number'],['mileage','Kilométrage','number']];
  const prices:[keyof typeof form,string][]=[['purchasePrice','Prix achat HT'],['refurbishmentCost','Remise en état HT'],['transportCost','Transport HT'],['administrativeCost','Frais administratifs HT'],['additionalCosts','Autres frais HT'],['catalogPrice','Prix catalogue HT'],['salePrice','Prix vente HT'],['minimumPrice','Prix minimum HT']];
  const legacyType=!['new','used'].includes(form.vehicleType);
  return <><Modal isOpen={isOpen} onClose={onClose} title="Modifier le véhicule" description={`VIN ${vehicle.vin} — l’affectation physique utilise le workflow de transfert.`} maxWidth="2xl"><form onSubmit={save} className="space-y-4"><section className="flex flex-wrap items-center justify-between gap-3 rounded-xl border bg-slate-50 p-4"><div><div className="text-xs font-semibold text-slate-500">Affectation actuelle</div><div className="font-semibold">{vehicle.location||'Non affecté'}{vehicle.locationType?` · ${vehicle.locationType==='PARC'?'Parc':'Showroom'}`:''}</div></div>{canTransfer&&<Button type="button" variant="outline" onClick={()=>setTransferOpen(true)}>{vehicle.locationId?'Transférer':'Affecter'}</Button>}</section><div className="grid gap-3 sm:grid-cols-3"><label className="text-xs font-semibold">Nature commerciale<select value={form.vehicleType} onChange={field('vehicleType')} className="mt-1 w-full rounded-lg border p-2.5">{legacyType&&<option value={form.vehicleType} disabled>Valeur historique : {vehicle.type}</option>}<option value="new">VN — Véhicule neuf</option><option value="used">VO — Véhicule d’occasion</option></select></label>{fields.map(([name,label,type])=><label key={name} className="text-xs font-semibold">{label}<input type={type??'text'} min={type==='number'?0:undefined} value={String(form[name]??'')} onChange={field(name)} className="mt-1 w-full rounded-lg border p-2.5"/></label>)}<label className="text-xs font-semibold">Fournisseur<select value={form.supplierId} onChange={field('supplierId')} className="mt-1 w-full rounded-lg border p-2.5"><option value="">Non renseigné</option>{references.data?.suppliers?.map((item:{id:string;name:string})=><option key={item.id} value={item.id}>{item.name}</option>)}</select></label></div>{canFinance&&<section className="grid gap-3 rounded-xl border bg-slate-50 p-4 sm:grid-cols-4">{prices.map(([name,label])=><label key={name} className="text-xs font-semibold">{label} ({vehicle.currencyCode})<input type="number" min="0" step="0.01" value={Number(form[name])} onChange={field(name)} className="mt-1 w-full rounded-lg border p-2"/></label>)}<label className="text-xs font-semibold sm:col-span-4">Motif du changement de prix<input value={form.reason} onChange={field('reason')} className="mt-1 w-full rounded-lg border p-2"/></label></section>}<label className="block text-xs font-semibold">Notes<textarea value={form.notes} onChange={field('notes')} className="mt-1 w-full rounded-lg border p-2.5"/></label><div className="flex justify-end gap-2 border-t pt-3"><Button type="button" variant="outline" onClick={onClose}>Annuler</Button><Button type="submit" loading={update.isPending}>Enregistrer</Button></div></form></Modal><VehicleTransferModal open={transferOpen} close={()=>setTransferOpen(false)} onTransferred={()=>{setTransferOpen(false);onClose()}} vehicle={vehicle}/></>;
};
