import {Router,type Request} from 'express';
import type {RowDataPacket} from 'mysql2/promise';
import {query} from '../../config/database.js';
import {asyncHandler} from '../../middleware/error-handler.js';
import {HttpError} from '../../shared/http-error.js';
import {assertPermission,type PermissionScope} from '../rbac/rbac.service.js';

export const extendedReportRouter=Router();
const rank:Record<PermissionScope,number>={OWN:1,AGENCY:2,CONCESSION:3,GLOBAL:4};
const date=(value:unknown,label:string)=>{const text=String(value??'').trim(),parsed=new Date(`${text}T00:00:00Z`);if(!/^\d{4}-\d{2}-\d{2}$/.test(text)||Number.isNaN(parsed.getTime())||parsed.toISOString().slice(0,10)!==text)throw new HttpError(400,`${label} invalide`);return text};
const period=(r:Request)=>{const from=date(r.query.from,'Date de début'),to=date(r.query.to,'Date de fin');if(from>to)throw new HttpError(400,'La date de début dépasse la date de fin');return{from,to}};
const numberRow=(row:Record<string,unknown>)=>Object.fromEntries(Object.entries(row).map(([key,value])=>[key,key==='module'?value:Number(value??0)]));
async function intersection(r:Request,permissions:string[],collective=false){let scope=await assertPermission(r,'reporting.view') as PermissionScope|null;for(const permission of permissions){const value=await assertPermission(r,permission) as PermissionScope|null;if(value&&(!scope||rank[value]<rank[scope]))scope=value}if(!scope)throw new HttpError(403,'Périmètre Reporting absent');if(collective&&scope==='OWN')throw new HttpError(403,'Le scope OWN ne s’applique pas à cet agrégat collectif');return scope}
function agencyScope(r:Request,scope:PermissionScope,alias:string,ownerColumn?:string){const agency=String(r.user?.agencyId??''),user=String(r.user!.sub);if(scope==='GLOBAL')return{sql:'1=1',params:[]as unknown[]};if(scope==='OWN'){if(!ownerColumn)throw new HttpError(403,'Le scope OWN ne s’applique pas à cet agrégat collectif');return{sql:`${alias}.${ownerColumn}=?`,params:[user]}}if(!agency)throw new HttpError(403,'Agence requise pour ce périmètre');if(scope==='AGENCY')return{sql:`${alias}.agency_id=?`,params:[agency]};return{sql:`${alias}.concession_id=(SELECT concession_id FROM agencies WHERE id=?)`,params:[agency]}}
function leadScope(r:Request,scope:PermissionScope){const agency=String(r.user?.agencyId??''),user=String(r.user!.sub);if(scope==='GLOBAL')return{sql:'1=1',params:[]as unknown[]};if(scope==='OWN')return{sql:'COALESCE(l.assigned_user_id,l.created_by)=?',params:[user]};if(!agency)throw new HttpError(403,'Agence requise pour ce périmètre');if(scope==='AGENCY')return{sql:'oa.id=?',params:[agency]};return{sql:'oa.concession_id=(SELECT concession_id FROM agencies WHERE id=?)',params:[agency]}}
function accountScope(r:Request,scope:PermissionScope){const agency=String(r.user?.agencyId??'');if(scope==='GLOBAL')return{sql:'1=1',params:[]as unknown[]};if(scope==='OWN')throw new HttpError(403,'Le scope OWN ne s’applique pas à la trésorerie collective');if(!agency)throw new HttpError(403,'Agence requise pour ce périmètre');if(scope==='AGENCY')return{sql:'ta.agency_id=?',params:[agency]};return{sql:'ta.concession_id=(SELECT concession_id FROM agencies WHERE id=?)',params:[agency]}}
function employeeScope(r:Request,scope:PermissionScope,alias='ep'){const agency=String(r.user?.agencyId??'');if(scope==='GLOBAL')return{sql:'1=1',params:[]as unknown[]};if(scope==='OWN')throw new HttpError(403,'Le scope OWN ne s’applique pas au reporting RH collectif');if(!agency)throw new HttpError(403,'Agence requise pour ce périmètre');if(scope==='AGENCY')return{sql:`${alias}.agency_id=?`,params:[agency]};return{sql:`${alias}.concession_id=(SELECT concession_id FROM agencies WHERE id=?)`,params:[agency]}}

extendedReportRouter.get('/reports/consolidated/commercial',asyncHandler(async(r,res)=>{const scope=await intersection(r,['crm.prospect.view','showroom.view','sales.view']),{from,to}=period(r),lead=leadScope(r,scope),drive=agencyScope(r,scope,'td','advisor_id'),sale=agencyScope(r,scope,'s','salesperson_id');const [prospects,trials,sales]=await Promise.all([
  query<RowDataPacket[]>(`SELECT COUNT(*) prospects_created,SUM(l.status='converted') prospects_currently_converted,SUM(l.status='lost') prospects_currently_lost FROM leads l JOIN users owner ON owner.id=COALESCE(l.assigned_user_id,l.created_by) JOIN agencies oa ON oa.id=owner.agency_id WHERE DATE(l.created_at) BETWEEN ? AND ? AND ${lead.sql}`,[from,to,...lead.params]),
  query<RowDataPacket[]>(`SELECT COUNT(*) trials,SUM(td.status='completed') completed_trials,SUM(td.status='cancelled') cancelled_trials FROM showroom_test_drives td JOIN agencies a ON a.id=td.agency_id WHERE DATE(td.created_at) BETWEEN ? AND ? AND ${drive.sql.replace(`${'td'}.concession_id`,'a.concession_id')}`,[from,to,...drive.params]),
  query<RowDataPacket[]>(`SELECT COUNT(*) sales,SUM(s.status='cancelled') cancelled_sales,COALESCE(SUM(CASE WHEN s.status<>'cancelled' THEN s.total ELSE 0 END),0) confirmed_sales_amount FROM sales s JOIN agencies a ON a.id=s.agency_id WHERE DATE(s.sold_at) BETWEEN ? AND ? AND ${sale.sql.replace('s.concession_id','a.concession_id')}`,[from,to,...sale.params])
]);const p=numberRow(prospects[0]??{}),out={...p,...numberRow(trials[0]??{}),...numberRow(sales[0]??{})};res.json({...out,conversionRate:Number(out.prospects_created)?Number(out.prospects_currently_converted)/Number(out.prospects_created)*100:0,conversionDefinition:'Prospects créés dans la période dont le statut courant est converted / prospects créés dans la période'})}));

extendedReportRouter.get('/reports/consolidated/treasury',asyncHandler(async(r,res)=>{const scope=await intersection(r,['treasury.view'],true),{from,to}=period(r),s=accountScope(r,scope),rows=await query<RowDataPacket[]>(`SELECT COALESCE(SUM(CASE WHEN tm.status='POSTED' AND tm.transfer_id IS NULL AND tm.direction='IN' THEN tm.amount ELSE 0 END),0) economic_entries,COALESCE(SUM(CASE WHEN tm.status='POSTED' AND tm.transfer_id IS NULL AND tm.direction='OUT' THEN tm.amount ELSE 0 END),0) economic_exits,COALESCE(SUM(CASE WHEN tm.status='POSTED' AND tm.direction='IN' THEN tm.amount ELSE -tm.amount END),0) period_balance,COALESCE(SUM(CASE WHEN tm.transfer_id IS NOT NULL AND tm.direction='OUT' THEN tm.amount ELSE 0 END),0) transfers,COALESCE(SUM(CASE WHEN tm.source_type IN('MANUAL_RECEIPT','MANUAL_DISBURSEMENT') THEN tm.amount ELSE 0 END),0) manual_operations FROM treasury_movements tm JOIN treasury_accounts ta ON ta.id=tm.account_id WHERE tm.value_date BETWEEN ? AND ? AND ${s.sql}`,[from,to,...s.params]);res.json(numberRow(rows[0]??{}))}));

extendedReportRouter.get('/reports/consolidated/budgets',asyncHandler(async(r,res)=>{const scope=await intersection(r,['hr.budget.view','hr.expense.view'],true),{from,to}=period(r),agency=String(r.user?.agencyId??'');if(scope!=='GLOBAL'&&!agency)throw new HttpError(403,'Agence requise pour ce périmètre');const scoped=scope==='GLOBAL'?'1=1':scope==='CONCESSION'?'COALESCE(b.concession_id,ba.concession_id)=(SELECT concession_id FROM agencies WHERE id=?)':"b.scope_type='agency' AND b.agency_id=?",sp=scope==='GLOBAL'?[]:[agency],rows=await query<RowDataPacket[]>(`SELECT COALESCE(SUM(b.initial_amount+COALESCE(f.amount,0)),0) allocated,COALESCE(SUM(COALESCE(e.amount,0)),0) consumed,COALESCE(SUM(b.initial_amount+COALESCE(f.amount,0)-COALESCE(e.amount,0)),0) remaining,COALESCE(SUM(COALESCE(d.amount,0)),0) disbursed FROM budgets b LEFT JOIN agencies ba ON ba.id=b.agency_id LEFT JOIN (SELECT budget_id,SUM(amount) amount FROM budget_fund_movements GROUP BY budget_id) f ON f.budget_id=b.id LEFT JOIN (SELECT budget_id,SUM(amount) amount FROM budget_expenses WHERE expense_date BETWEEN ? AND ? GROUP BY budget_id) e ON e.budget_id=b.id LEFT JOIN (SELECT be.budget_id,SUM(bed.amount) amount FROM budget_expense_disbursements bed JOIN budget_expenses be ON be.id=bed.budget_expense_id JOIN treasury_movements tm ON tm.source_type='BUDGET_EXPENSE_DISBURSEMENT' AND CAST(tm.source_id AS UNSIGNED)=bed.id AND tm.event_type='POSTED' LEFT JOIN treasury_movements reversal ON reversal.reversal_of_id=tm.id WHERE bed.value_date BETWEEN ? AND ? AND reversal.id IS NULL GROUP BY be.budget_id) d ON d.budget_id=b.id WHERE b.start_date<=? AND b.end_date>=? AND b.status<>'cancelled' AND ${scoped}`,[from,to,from,to,to,from,...sp]);res.json(numberRow(rows[0]??{}))}));

extendedReportRouter.get('/reports/consolidated/hr',asyncHandler(async(r,res)=>{const scope=await intersection(r,['hr.reporting.view','hr.employees.view','hr.salary.view','hr.contract.view','hr.leave.view','hr.bonus.view'],true),{from,to}=period(r),s=employeeScope(r,scope),params=s.params,[headcount,contracts,leaves,bonuses]=await Promise.all([
 query<RowDataPacket[]>(`SELECT COUNT(*) active_employees,SUM(ep.user_id IS NOT NULL) with_erp_account,SUM(ep.user_id IS NULL) without_erp_account,COALESCE(SUM((SELECT sh.amount FROM salary_history sh WHERE sh.employee_profile_id=ep.id AND sh.effective_date<=? ORDER BY sh.effective_date DESC,sh.id DESC LIMIT 1)),0) current_salary_mass FROM employee_profiles ep WHERE ep.employment_status='active' AND ${s.sql}`,[to,...params]),
 query<RowDataPacket[]>(`SELECT SUM(ec.status='ACTIVE' AND ec.start_date<=? AND COALESCE(ec.effective_end_date,ec.contractual_end_date,'9999-12-31')>=?) current_contracts,SUM(ec.status='ACTIVE' AND ec.start_date>? ) scheduled_contracts,SUM(ec.status='ACTIVE' AND COALESCE(ec.effective_end_date,ec.contractual_end_date) BETWEEN ? AND ?) contracts_expiring FROM employee_contracts ec JOIN employee_profiles ep ON ep.id=ec.employee_profile_id WHERE ${s.sql}`,[to,to,to,to,to,...params]),
 query<RowDataPacket[]>(`SELECT SUM(l.status='PENDING') pending_leaves,SUM(l.status='APPROVED' AND l.start_date<=? AND l.end_date>=?) approved_leaves_in_period FROM employee_leaves l JOIN employee_profiles ep ON ep.id=l.employee_profile_id WHERE l.end_date>=? AND l.start_date<=? AND ${s.sql}`,[to,from,from,to,...params]),
 query<RowDataPacket[]>(`SELECT COUNT(*) approved_bonuses,COALESCE(SUM(b.amount),0) approved_bonus_amount FROM employee_bonuses b JOIN employee_profiles ep ON ep.id=b.employee_profile_id WHERE b.status='APPROVED' AND b.reference_date BETWEEN ? AND ? AND ${s.sql}`,[from,to,...params])
]);res.json({...numberRow(headcount[0]??{}),...numberRow(contracts[0]??{}),...numberRow(leaves[0]??{}),...numberRow(bonuses[0]??{})})}));

extendedReportRouter.get('/reports/consolidated/activity',asyncHandler(async(r,res)=>{const scope=await intersection(r,['activity.view']),{from,to}=period(r),s=agencyScope(r,scope,'al','user_id'),rows=await query<RowDataPacket[]>(`SELECT COUNT(*) events,COUNT(DISTINCT al.user_id) active_users,COUNT(DISTINCT al.module) active_modules FROM audit_logs al WHERE al.created_at>=CONCAT(?,' 00:00:00') AND al.created_at<DATE_ADD(?,INTERVAL 1 DAY) AND ${s.sql}`,[from,to,...s.params]),byModule=await query<RowDataPacket[]>(`SELECT al.module,COUNT(*) events FROM audit_logs al WHERE al.created_at>=CONCAT(?,' 00:00:00') AND al.created_at<DATE_ADD(?,INTERVAL 1 DAY) AND ${s.sql} GROUP BY al.module ORDER BY events DESC,al.module LIMIT 12`,[from,to,...s.params]);res.json({...numberRow(rows[0]??{}),byModule:byModule.map(numberRow)})}));

extendedReportRouter.get('/reports/consolidated/returns',asyncHandler(async(r,res)=>{const scope=await intersection(r,['vehicle.return.view']),{from,to}=period(r),s=agencyScope(r,scope,'vr','requested_by'),rows=await query<RowDataPacket[]>(`SELECT COUNT(*) returns,SUM(vr.status='CLOSED') closed_returns,COALESCE(SUM(vr.credited_amount),0) credited_amount,COALESCE(SUM(vr.refunded_amount),0) refunded_amount,SUM(vr.stock_decision='RESTOCK_USED') returned_to_stock FROM post_delivery_vehicle_returns vr WHERE DATE(vr.requested_at) BETWEEN ? AND ? AND ${s.sql}`,[from,to,...s.params]);res.json(numberRow(rows[0]??{}))}));
