import{Router,type Request}from'express';
import type{PoolConnection,ResultSetHeader,RowDataPacket}from'mysql2/promise';
import{query,transaction}from'../../config/database.js';
import{asyncHandler}from'../../middleware/error-handler.js';
import{requirePermission}from'../../middleware/require-permission.js';
import{emitToAgency}from'../../realtime/socket.js';
import{HttpError}from'../../shared/http-error.js';

export const deliveryChecklistRouter=Router();
type ConfigPermission='delivery.checklist.config.view'|'delivery.checklist.config.manage';
const idOf=(value:unknown)=>{const id=String(value??'');if(!/^[1-9]\d*$/.test(id))throw new HttpError(400,'Identifiant invalide');return id};
const text=(value:unknown,label:string,max:number,required=false)=>{const result=String(value??'').trim();if(required&&!result)throw new HttpError(400,`${label} est requis`);if(result.length>max)throw new HttpError(400,`${label} est trop long`);return result||null};
const codeOf=(value:unknown)=>{const code=String(value??'').trim();if(!/^[A-Za-z0-9][A-Za-z0-9_-]{1,79}$/.test(code))throw new HttpError(400,'Code stable invalide');return code};
async function concession(request:Request,permission:ConfigPermission,requested?:unknown,connection?:PoolConnection){
  const permissionScope=request.rbac?.permissions.get(permission);
  if(permissionScope==='OWN'||permissionScope==='AGENCY')throw new HttpError(403,'La configuration collective refuse les périmètres OWN et AGENCY.');
  const actorAgency=request.user?.agencyId;if(!actorAgency)throw new HttpError(403,'Aucune agence associée');
  const sql='SELECT concession_id FROM agencies WHERE id=?',rows=connection?(await connection.execute<RowDataPacket[]>(sql,[actorAgency]))[0]:await query<RowDataPacket[]>(sql,[actorAgency]),actor=rows[0];
  if(!actor)throw new HttpError(403,'Concession introuvable');
  if(permissionScope==='GLOBAL'&&requested!=null&&requested!=='')return idOf(requested);
  if(permissionScope==='GLOBAL'||permissionScope==='CONCESSION')return String(actor.concession_id);
  throw new HttpError(403,'Périmètre Checklist insuffisant.');
}
async function audit(connection:PoolConnection,request:Request,entityType:string,entityId:string|number|bigint,action:string,oldValues:unknown,newValues:unknown){
  await connection.execute(`INSERT INTO audit_logs(user_id,module,entity_type,entity_id,action,old_values,new_values,ip_address,user_agent) VALUES(?,'deliveries',?,?,?,?,?,?,?)`,[request.user!.sub,entityType,entityId,action,oldValues==null?null:JSON.stringify(oldValues),newValues==null?null:JSON.stringify(newValues),request.ip??null,request.get('user-agent')??null]);
}
async function categoryInScope(connection:PoolConnection,request:Request,id:string){const permissionScope=request.rbac?.permissions.get('delivery.checklist.config.manage');if(permissionScope==='GLOBAL'){const[rows]=await connection.execute<RowDataPacket[]>('SELECT * FROM delivery_checklist_categories WHERE id=? FOR UPDATE',[id]);if(!rows[0])throw new HttpError(404,'Catégorie introuvable');return{row:rows[0],concessionId:String(rows[0].concession_id)}}const concessionId=await concession(request,'delivery.checklist.config.manage',undefined,connection),[rows]=await connection.execute<RowDataPacket[]>('SELECT * FROM delivery_checklist_categories WHERE id=? AND concession_id=? FOR UPDATE',[id,concessionId]);if(!rows[0])throw new HttpError(404,'Catégorie introuvable');return{row:rows[0],concessionId}}
async function itemInScope(connection:PoolConnection,request:Request,id:string){const permissionScope=request.rbac?.permissions.get('delivery.checklist.config.manage');if(permissionScope==='GLOBAL'){const[rows]=await connection.execute<RowDataPacket[]>('SELECT i.*,c.concession_id FROM delivery_checklist_items i JOIN delivery_checklist_categories c ON c.id=i.category_id WHERE i.id=? FOR UPDATE',[id]);if(!rows[0])throw new HttpError(404,'Élément introuvable');return{row:rows[0],concessionId:String(rows[0].concession_id)}}const concessionId=await concession(request,'delivery.checklist.config.manage',undefined,connection),[rows]=await connection.execute<RowDataPacket[]>('SELECT i.*,c.concession_id FROM delivery_checklist_items i JOIN delivery_checklist_categories c ON c.id=i.category_id WHERE i.id=? AND c.concession_id=? FOR UPDATE',[id,concessionId]);if(!rows[0])throw new HttpError(404,'Élément introuvable');return{row:rows[0],concessionId}}
const idsOf=(value:unknown)=>{if(!Array.isArray(value)||!value.length)throw new HttpError(400,'Ordre complet requis');const ids=value.map(idOf);if(new Set(ids).size!==ids.length)throw new HttpError(400,'Ordre dupliqué');return ids};
async function emitConfig(concessionId:string,payload:unknown){const agencies=await query<RowDataPacket[]>('SELECT id FROM agencies WHERE concession_id=?',[concessionId]);for(const agency of agencies)emitToAgency(String(agency.id),'delivery:checklist-config',payload)}

deliveryChecklistRouter.get('/delivery-checklist-config',requirePermission('delivery.checklist.config.view'),asyncHandler(async(request,response)=>{
  const concessionId=await concession(request,'delivery.checklist.config.view',request.query.concessionId);
  const categories=await query<RowDataPacket[]>('SELECT * FROM delivery_checklist_categories WHERE concession_id=? ORDER BY sort_order,id',[concessionId]);
  const items=categories.length?await query<RowDataPacket[]>(`SELECT i.* FROM delivery_checklist_items i JOIN delivery_checklist_categories c ON c.id=i.category_id WHERE c.concession_id=? ORDER BY c.sort_order,i.sort_order,i.id`,[concessionId]):[];
  response.json(categories.map(category=>({...category,items:items.filter(item=>String(item.category_id)===String(category.id))})));
}));

deliveryChecklistRouter.post('/delivery-checklist-config/categories',requirePermission('delivery.checklist.config.manage'),asyncHandler(async(request,response)=>{
  const result=await transaction(async connection=>{const concessionId=await concession(request,'delivery.checklist.config.manage',request.body.concessionId,connection);await connection.execute('SELECT id FROM delivery_checklist_categories WHERE concession_id=? FOR UPDATE',[concessionId]);const[orders]=await connection.execute<RowDataPacket[]>('SELECT COALESCE(MAX(sort_order),0)+10 next_order FROM delivery_checklist_categories WHERE concession_id=?',[concessionId]);const[result]=await connection.execute<ResultSetHeader>('INSERT INTO delivery_checklist_categories(concession_id,code,name,description,sort_order,is_active,created_by) VALUES(?,?,?,?,?,TRUE,?)',[concessionId,codeOf(request.body.code),text(request.body.name,'Nom',180,true),text(request.body.description,'Description',1000),Number(orders[0]!.next_order),request.user!.sub]);await audit(connection,request,'delivery_checklist_category',result.insertId,'delivery.checklist.category.created',null,{code:request.body.code});return{id:String(result.insertId),concessionId}});await emitConfig(result.concessionId,{type:'category',id:result.id});response.status(201).json({id:result.id});
}));

deliveryChecklistRouter.patch('/delivery-checklist-config/categories/:id',requirePermission('delivery.checklist.config.manage'),asyncHandler(async(request,response)=>{const id=idOf(request.params.id);const result=await transaction(async connection=>{const{row,concessionId}=await categoryInScope(connection,request,id),next={name:text(request.body.name,'Nom',180,true),description:text(request.body.description,'Description',1000)};if(row.name===next.name&&(row.description??null)===next.description)return{changed:false,concessionId};await connection.execute('UPDATE delivery_checklist_categories SET name=?,description=? WHERE id=?',[next.name,next.description,id]);await audit(connection,request,'delivery_checklist_category',id,'delivery.checklist.category.updated',{name:row.name,description:row.description},next);return{changed:true,concessionId}});if(result.changed)await emitConfig(result.concessionId,{type:'category',id});response.json({success:true})}));
deliveryChecklistRouter.patch('/delivery-checklist-config/categories/:id/status',requirePermission('delivery.checklist.config.manage'),asyncHandler(async(request,response)=>{const id=idOf(request.params.id),isActive=Boolean(request.body.isActive);const result=await transaction(async connection=>{const{row,concessionId}=await categoryInScope(connection,request,id);if(Boolean(row.is_active)===isActive)return{changed:false,concessionId};await connection.execute('UPDATE delivery_checklist_categories SET is_active=? WHERE id=?',[isActive,id]);await audit(connection,request,'delivery_checklist_category',id,isActive?'delivery.checklist.category.activated':'delivery.checklist.category.deactivated',{isActive:Boolean(row.is_active)},{isActive});return{changed:true,concessionId}});if(result.changed)await emitConfig(result.concessionId,{type:'category',id});response.json({success:true})}));

deliveryChecklistRouter.post('/delivery-checklist-config/categories/reorder',requirePermission('delivery.checklist.config.manage'),asyncHandler(async(request,response)=>{const ids=idsOf(request.body.ids);const result=await transaction(async connection=>{const concessionId=await concession(request,'delivery.checklist.config.manage',request.body.concessionId,connection),[rows]=await connection.execute<RowDataPacket[]>('SELECT id,sort_order FROM delivery_checklist_categories WHERE concession_id=? ORDER BY sort_order,id FOR UPDATE',[concessionId]);if(rows.length!==ids.length||rows.some(row=>!ids.includes(String(row.id))))throw new HttpError(409,'La liste doit contenir toutes les catégories de la concession');if(rows.every((row,index)=>String(row.id)===ids[index]))return{changed:false,concessionId};for(const[index,id]of ids.entries())await connection.execute('UPDATE delivery_checklist_categories SET sort_order=? WHERE id=?',[1_000_000+index,id]);for(const[index,id]of ids.entries())await connection.execute('UPDATE delivery_checklist_categories SET sort_order=? WHERE id=?',[(index+1)*10,id]);await audit(connection,request,'delivery_checklist_configuration',concessionId,'delivery.checklist.categories.reordered',null,{ids});return{changed:true,concessionId}});if(result.changed)await emitConfig(result.concessionId,{type:'categories-reordered'});response.json({success:true})}));

deliveryChecklistRouter.post('/delivery-checklist-config/categories/:categoryId/items',requirePermission('delivery.checklist.config.manage'),asyncHandler(async(request,response)=>{const categoryId=idOf(request.params.categoryId);const result=await transaction(async connection=>{const{concessionId}=await categoryInScope(connection,request,categoryId);await connection.execute('SELECT id FROM delivery_checklist_items WHERE category_id=? FOR UPDATE',[categoryId]);const[orders]=await connection.execute<RowDataPacket[]>('SELECT COALESCE(MAX(sort_order),0)+10 next_order FROM delivery_checklist_items WHERE category_id=?',[categoryId]);const[result]=await connection.execute<ResultSetHeader>('INSERT INTO delivery_checklist_items(category_id,code,name,description,is_mandatory,sort_order,is_active,created_by) VALUES(?,?,?,?,?,?,TRUE,?)',[categoryId,codeOf(request.body.code),text(request.body.name,'Libellé',200,true),text(request.body.description,'Description',1000),request.body.isMandatory!==false,Number(orders[0]!.next_order),request.user!.sub]);await audit(connection,request,'delivery_checklist_item',result.insertId,'delivery.checklist.item.created',null,{categoryId,code:request.body.code});return{id:String(result.insertId),concessionId}});await emitConfig(result.concessionId,{type:'item',id:result.id});response.status(201).json({id:result.id})}));
deliveryChecklistRouter.patch('/delivery-checklist-config/items/:id',requirePermission('delivery.checklist.config.manage'),asyncHandler(async(request,response)=>{const id=idOf(request.params.id);const result=await transaction(async connection=>{const{row,concessionId}=await itemInScope(connection,request,id),next={name:text(request.body.name,'Libellé',200,true),description:text(request.body.description,'Description',1000),isMandatory:request.body.isMandatory!==false};if(row.name===next.name&&(row.description??null)===next.description&&Boolean(row.is_mandatory)===next.isMandatory)return{changed:false,concessionId};await connection.execute('UPDATE delivery_checklist_items SET name=?,description=?,is_mandatory=? WHERE id=?',[next.name,next.description,next.isMandatory,id]);await audit(connection,request,'delivery_checklist_item',id,'delivery.checklist.item.updated',{name:row.name,description:row.description,isMandatory:Boolean(row.is_mandatory)},next);return{changed:true,concessionId}});if(result.changed)await emitConfig(result.concessionId,{type:'item',id});response.json({success:true})}));
deliveryChecklistRouter.patch('/delivery-checklist-config/items/:id/status',requirePermission('delivery.checklist.config.manage'),asyncHandler(async(request,response)=>{const id=idOf(request.params.id),isActive=Boolean(request.body.isActive);const result=await transaction(async connection=>{const{row,concessionId}=await itemInScope(connection,request,id);if(Boolean(row.is_active)===isActive)return{changed:false,concessionId};await connection.execute('UPDATE delivery_checklist_items SET is_active=? WHERE id=?',[isActive,id]);await audit(connection,request,'delivery_checklist_item',id,isActive?'delivery.checklist.item.activated':'delivery.checklist.item.deactivated',{isActive:Boolean(row.is_active)},{isActive});return{changed:true,concessionId}});if(result.changed)await emitConfig(result.concessionId,{type:'item',id});response.json({success:true})}));
deliveryChecklistRouter.post('/delivery-checklist-config/categories/:categoryId/items/reorder',requirePermission('delivery.checklist.config.manage'),asyncHandler(async(request,response)=>{const categoryId=idOf(request.params.categoryId),ids=idsOf(request.body.ids);const result=await transaction(async connection=>{const{concessionId}=await categoryInScope(connection,request,categoryId);const[rows]=await connection.execute<RowDataPacket[]>('SELECT id,sort_order FROM delivery_checklist_items WHERE category_id=? ORDER BY sort_order,id FOR UPDATE',[categoryId]);if(rows.length!==ids.length||rows.some(row=>!ids.includes(String(row.id))))throw new HttpError(409,'La liste doit contenir tous les éléments de la catégorie');if(rows.every((row,index)=>String(row.id)===ids[index]))return{changed:false,concessionId};for(const[index,id]of ids.entries())await connection.execute('UPDATE delivery_checklist_items SET sort_order=? WHERE id=?',[1_000_000+index,id]);for(const[index,id]of ids.entries())await connection.execute('UPDATE delivery_checklist_items SET sort_order=? WHERE id=?',[(index+1)*10,id]);await audit(connection,request,'delivery_checklist_category',categoryId,'delivery.checklist.items.reordered',null,{ids});return{changed:true,concessionId}});if(result.changed)await emitConfig(result.concessionId,{type:'items-reordered',categoryId});response.json({success:true})}));
