import type{Request}from'express';
import type{RowDataPacket}from'mysql2/promise';
import{query}from'../../config/database.js';
import{HttpError}from'../../shared/http-error.js';
import{assertPermission,type PermissionScope}from'../rbac/rbac.service.js';
import{coverage as treasuryCoverage}from'../treasury/treasury-coverage.service.js';

export type FinancialSection='treasury'|'customers'|'budgets'|'suppliers'|'remunerations'|'coverage';
export type FinancialFilters={from:string;to:string;asOf:string;currency:string|null;agencyId:string|null;actorAgencyId:string;scope:Exclude<PermissionScope,null>};
const permissions:Record<FinancialSection,string[]>={treasury:['treasury.view'],customers:['billing.view','billing.payment.view'],budgets:['hr.budget.view','hr.expense.view'],suppliers:['supplier.debt.view'],remunerations:['hr.remuneration.view','hr.salary.view'],coverage:['treasury.coverage.view']};
const rank:Record<Exclude<PermissionScope,null>,number>={OWN:0,AGENCY:1,CONCESSION:2,GLOBAL:3};
const text=(v:unknown)=>String(v??'').trim();
const date=(v:unknown,label:string)=>{const x=text(v),d=new Date(`${x}T00:00:00Z`);if(!/^\d{4}-\d{2}-\d{2}$/.test(x)||Number.isNaN(d.getTime())||d.toISOString().slice(0,10)!==x)throw new HttpError(400,`${label} invalide`);return x};
export async function financialFilters(r:Request,section:FinancialSection,exporting=false):Promise<FinancialFilters>{
 const from=date(r.query.from,'Date de début'),to=date(r.query.to,'Date de fin'),asOf=date(r.query.asOf??to,'Date de référence');if(from>to)throw new HttpError(400,'La date de début dépasse la date de fin');
 let scope=await assertPermission(r,'reporting.view') as PermissionScope|null;for(const permission of [...permissions[section],...(exporting?['reporting.export']:[])]){const granted=await assertPermission(r,permission) as PermissionScope|null;if(granted&&(!scope||rank[granted]<rank[scope]))scope=granted}
 if(!scope||scope==='OWN')throw new HttpError(403,'Le scope OWN ne s’applique pas aux agrégats financiers collectifs');const actorAgencyId=String(r.user?.agencyId??'');if(scope!=='GLOBAL'&&!actorAgencyId)throw new HttpError(403,'Agence requise pour ce périmètre');
 const raw=text(r.query.agencyId??r.query.reportAgencyId);if(raw&&!/^[1-9]\d*$/.test(raw))throw new HttpError(400,'Agence invalide');let agencyId=raw||null;if(scope==='AGENCY'){if(agencyId&&agencyId!==actorAgencyId)throw new HttpError(403,'Agence non autorisée');agencyId=actorAgencyId}else if(agencyId){const rows=await query<RowDataPacket[]>(scope==='CONCESSION'?'SELECT target.id FROM agencies target JOIN agencies actor ON actor.concession_id=target.concession_id WHERE actor.id=? AND target.id=? AND target.is_active=TRUE':'SELECT id FROM agencies WHERE id=? AND is_active=TRUE',scope==='CONCESSION'?[actorAgencyId,agencyId]:[agencyId]);if(!rows[0])throw new HttpError(403,'Agence non autorisée')}
 const currency=text(r.query.currency).toUpperCase()||null;if(currency&&!/^[A-Z]{3}$/.test(currency))throw new HttpError(400,'Devise invalide');return{from,to,asOf,currency,agencyId,actorAgencyId,scope};
}
const scope=(alias:string,f:FinancialFilters,column='agency_id')=>f.agencyId?{sql:`${alias}.${column}=?`,params:[f.agencyId]}:f.scope==='GLOBAL'?{sql:'TRUE',params:[]as unknown[]}:{sql:`${alias}.${column} IN(SELECT a.id FROM agencies a WHERE a.concession_id=(SELECT concession_id FROM agencies WHERE id=?))`,params:[f.actorAgencyId]};
const currency=(alias:string,f:FinancialFilters)=>f.currency?{sql:` AND ${alias}.currency_code=?`,params:[f.currency]}:{sql:'',params:[]as unknown[]};
const rows=async(sql:string,p:unknown[])=>(await query<RowDataPacket[]>(sql,p)).map(x=>Object.fromEntries(Object.entries(x).map(([k,v])=>[k,typeof v==='bigint'?Number(v):v])));

export async function treasuryReport(f:FinancialFilters){const s=scope('ta',f),c=currency('ta',f);return rows(`SELECT ta.currency_code currencyCode,
 COALESCE(SUM(CASE WHEN tm.status='POSTED' AND tm.value_date<? THEN IF(tm.direction='IN',tm.amount,-tm.amount) ELSE 0 END),0) openingBalance,
 COALESCE(SUM(CASE WHEN tm.status='POSTED' AND tm.value_date>=? AND tm.value_date<DATE_ADD(?,INTERVAL 1 DAY) AND tm.transfer_id IS NULL AND tm.direction='IN' THEN tm.amount ELSE 0 END),0) inflows,
 COALESCE(SUM(CASE WHEN tm.status='POSTED' AND tm.value_date>=? AND tm.value_date<DATE_ADD(?,INTERVAL 1 DAY) AND tm.transfer_id IS NULL AND tm.direction='OUT' THEN tm.amount ELSE 0 END),0) outflows,
 COALESCE(SUM(CASE WHEN tm.status='POSTED' AND tm.value_date>=? AND tm.value_date<DATE_ADD(?,INTERVAL 1 DAY) AND tm.transfer_id IS NOT NULL AND tm.direction='IN' THEN tm.amount ELSE 0 END),0) transferInflows,
 COALESCE(SUM(CASE WHEN tm.status='POSTED' AND tm.value_date>=? AND tm.value_date<DATE_ADD(?,INTERVAL 1 DAY) AND tm.transfer_id IS NOT NULL AND tm.direction='OUT' THEN tm.amount ELSE 0 END),0) transferOutflows,
 COALESCE(SUM(CASE WHEN tm.status='POSTED' AND tm.value_date>=? AND tm.value_date<DATE_ADD(?,INTERVAL 1 DAY) AND tm.reversal_of_id IS NOT NULL AND tm.direction='IN' THEN tm.amount ELSE 0 END),0) reversalInflows,
 COALESCE(SUM(CASE WHEN tm.status='POSTED' AND tm.value_date>=? AND tm.value_date<DATE_ADD(?,INTERVAL 1 DAY) AND tm.reversal_of_id IS NOT NULL AND tm.direction='OUT' THEN tm.amount ELSE 0 END),0) reversalOutflows,
 COALESCE(SUM(CASE WHEN tm.status='POSTED' AND tm.value_date<=? THEN IF(tm.direction='IN',tm.amount,-tm.amount) ELSE 0 END),0) closingBalance
 FROM treasury_accounts ta LEFT JOIN treasury_movements tm ON tm.account_id=ta.id WHERE ${s.sql}${c.sql} GROUP BY ta.currency_code ORDER BY ta.currency_code`,[f.from,f.from,f.to,f.from,f.to,f.from,f.to,f.from,f.to,f.from,f.to,f.from,f.to,f.asOf,...s.params,...c.params]);}

export async function customerReport(f:FinancialFilters){const s=scope('i',f),c=currency('i',f),base=[...s.params,...c.params];return rows(`SELECT i.currency_code currencyCode,
 COALESCE(SUM(CASE WHEN i.issue_date>=? AND i.issue_date<DATE_ADD(?,INTERVAL 1 DAY) AND i.status<>'draft' THEN i.total ELSE 0 END),0) issued,
 COALESCE(SUM(CASE WHEN i.cancelled_at>=CONCAT(?,' 00:00:00') AND i.cancelled_at<DATE_ADD(?,INTERVAL 1 DAY) THEN i.total ELSE 0 END),0) cancelled,
 COALESCE((SELECT SUM(cn.amount) FROM credit_notes cn JOIN invoices ci ON ci.id=cn.invoice_id WHERE cn.status IN('issued','applied') AND cn.issue_date>=? AND cn.issue_date<DATE_ADD(?,INTERVAL 1 DAY) AND ${scope('ci',f).sql}${currency('ci',f).sql}),0) credits,
 COALESCE((SELECT SUM(p.amount) FROM payments p JOIN invoices pi ON pi.id=p.invoice_id WHERE p.status IN('confirmed','refunded') AND p.payment_date>=CONCAT(?,' 00:00:00') AND p.payment_date<DATE_ADD(?,INTERVAL 1 DAY) AND ${scope('pi',f).sql}${currency('pi',f).sql}),0) collections,
 COALESCE((SELECT SUM(pr.amount) FROM payment_refunds pr JOIN invoices ri ON ri.id=pr.invoice_id WHERE pr.refunded_at>=CONCAT(?,' 00:00:00') AND pr.refunded_at<DATE_ADD(?,INTERVAL 1 DAY) AND ${scope('ri',f).sql}${currency('ri',f).sql}),0)+
 COALESCE((SELECT SUM(p.amount) FROM payments p JOIN invoices li ON li.id=p.invoice_id WHERE p.status='refunded' AND p.refunded_at>=CONCAT(?,' 00:00:00') AND p.refunded_at<DATE_ADD(?,INTERVAL 1 DAY) AND NOT EXISTS(SELECT 1 FROM payment_refunds pr WHERE pr.payment_id=p.id) AND ${scope('li',f).sql}${currency('li',f).sql}),0) refunds,
 COALESCE(SUM(CASE WHEN i.issue_date<=? AND i.status<>'draft' AND (i.cancelled_at IS NULL OR DATE(i.cancelled_at)>?) THEN i.total ELSE 0 END),0)
 -COALESCE((SELECT SUM(cn.amount) FROM credit_notes cn JOIN invoices ai ON ai.id=cn.invoice_id WHERE cn.status IN('issued','applied') AND cn.issue_date<=? AND ${scope('ai',f).sql}${currency('ai',f).sql}),0)
 -COALESCE((SELECT SUM(p.amount) FROM payments p JOIN invoices bi ON bi.id=p.invoice_id WHERE p.status IN('confirmed','refunded') AND DATE(p.payment_date)<=? AND ${scope('bi',f).sql}${currency('bi',f).sql}),0)
 +COALESCE((SELECT SUM(pr.amount) FROM payment_refunds pr JOIN invoices di ON di.id=pr.invoice_id WHERE DATE(pr.refunded_at)<=? AND ${scope('di',f).sql}${currency('di',f).sql}),0)
 +COALESCE((SELECT SUM(p.amount) FROM payments p JOIN invoices ei ON ei.id=p.invoice_id WHERE p.status='refunded' AND DATE(p.refunded_at)<=? AND NOT EXISTS(SELECT 1 FROM payment_refunds pr WHERE pr.payment_id=p.id) AND ${scope('ei',f).sql}${currency('ei',f).sql}),0) receivables
 FROM invoices i WHERE ${s.sql}${c.sql} GROUP BY i.currency_code ORDER BY i.currency_code`,[f.from,f.to,f.from,f.to,f.from,f.to,...base,f.from,f.to,...base,f.from,f.to,...base,f.from,f.to,...base,f.asOf,f.asOf,f.asOf,...base,f.asOf,...base,f.asOf,...base,f.asOf,...base,...base]);}

const paidAt=`SELECT COALESCE(SUM(CASE WHEN original.value_date<=? AND (reversal.id IS NULL OR reversal.value_date>?) THEN d.amount ELSE 0 END),0) FROM budget_expense_disbursements d JOIN treasury_movements original ON original.source_type='BUDGET_EXPENSE_DISBURSEMENT' AND CAST(original.source_id AS UNSIGNED)=d.id AND original.event_type='POSTED' LEFT JOIN treasury_movements reversal ON reversal.reversal_of_id=original.id WHERE d.budget_expense_id=e.id`;
export async function budgetReport(f:FinancialFilters){const s=scope('b',f),c=f.currency?{sql:' AND co.currency_code=?',params:[f.currency]}:{sql:'',params:[]as unknown[]};return rows(`SELECT co.currency_code currencyCode,COALESCE(SUM(b.initial_amount),0) initialEnvelope,COALESCE(SUM((SELECT SUM(bfm.amount) FROM budget_fund_movements bfm WHERE bfm.budget_id=b.id AND DATE(bfm.created_at)<=?)),0) additionalEnvelope,COALESCE(SUM((SELECT SUM(e.amount) FROM budget_expenses e WHERE e.budget_id=b.id AND e.approval_status='approved' AND DATE(e.decided_at)<=?)),0) commitments,COALESCE(SUM((SELECT SUM((${paidAt})) FROM budget_expenses e WHERE e.budget_id=b.id AND e.approval_status='approved' AND DATE(e.decided_at)<=?)),0) paid FROM budgets b LEFT JOIN agencies ba ON ba.id=b.agency_id JOIN concessions co ON co.id=COALESCE(b.concession_id,ba.concession_id) WHERE b.status IN('active','closed') AND b.decided_at IS NOT NULL AND DATE(b.decided_at)<=? AND b.start_date<=? AND ${s.sql}${c.sql} GROUP BY co.currency_code ORDER BY co.currency_code`,[f.asOf,f.asOf,f.asOf,f.asOf,f.asOf,f.asOf,f.asOf,...s.params,...c.params]);}

export async function supplierReport(f:FinancialFilters){const s=scope('si',f),c=currency('si',f),creditsPeriod="SELECT COALESCE(SUM(cn.amount),0) FROM supplier_credit_notes cn WHERE cn.supplier_invoice_id=si.id AND cn.status='VALIDATED' AND cn.credit_date>=? AND cn.credit_date<DATE_ADD(?,INTERVAL 1 DAY) AND DATE(cn.validated_at)<=?",creditsAt="SELECT COALESCE(SUM(cn.amount),0) FROM supplier_credit_notes cn WHERE cn.supplier_invoice_id=si.id AND cn.status='VALIDATED' AND cn.credit_date<=?",paymentsPeriod="SELECT COALESCE(SUM(CASE WHEN d.value_date>=? AND d.value_date<DATE_ADD(?,INTERVAL 1 DAY) AND (reversal.id IS NULL OR reversal.value_date>?) THEN d.amount ELSE 0 END),0) FROM budget_expense_disbursements d JOIN treasury_movements original ON original.source_type='BUDGET_EXPENSE_DISBURSEMENT' AND CAST(original.source_id AS UNSIGNED)=d.id AND original.event_type='POSTED' LEFT JOIN treasury_movements reversal ON reversal.reversal_of_id=original.id WHERE d.budget_expense_id=si.budget_expense_id",paymentsAt="SELECT COALESCE(SUM(CASE WHEN original.value_date<=? AND (reversal.id IS NULL OR reversal.value_date>?) THEN d.amount ELSE 0 END),0) FROM budget_expense_disbursements d JOIN treasury_movements original ON original.source_type='BUDGET_EXPENSE_DISBURSEMENT' AND CAST(original.source_id AS UNSIGNED)=d.id AND original.event_type='POSTED' LEFT JOIN treasury_movements reversal ON reversal.reversal_of_id=original.id WHERE d.budget_expense_id=si.budget_expense_id";return rows(`SELECT si.currency_code currencyCode,COALESCE(SUM(CASE WHEN si.invoice_date>=? AND si.invoice_date<DATE_ADD(?,INTERVAL 1 DAY) THEN si.total ELSE 0 END),0) invoices,COALESCE(SUM((${creditsPeriod})),0) credits,COALESCE(SUM((${paymentsPeriod})),0) payments,COALESCE(SUM(GREATEST(0,si.total-(${creditsAt})-(${paymentsAt}))),0) balance,COALESCE(SUM(CASE WHEN si.due_date<? THEN GREATEST(0,si.total-(${creditsAt})-(${paymentsAt})) ELSE 0 END),0) overdue,COALESCE(SUM(CASE WHEN si.due_date>=? AND si.due_date<=DATE_ADD(?,INTERVAL 30 DAY) THEN GREATEST(0,si.total-(${creditsAt})-(${paymentsAt})) ELSE 0 END),0) upcoming FROM supplier_invoices si WHERE si.status='VALIDATED' AND DATE(si.validated_at)<=? AND ${s.sql}${c.sql} GROUP BY si.currency_code ORDER BY si.currency_code`,[f.from,f.to,f.from,f.to,f.asOf,f.from,f.to,f.asOf,f.asOf,f.asOf,f.asOf,f.asOf,f.asOf,f.asOf,f.asOf,f.asOf,f.asOf,f.asOf,f.asOf,f.asOf,f.asOf,f.asOf,f.asOf,f.asOf,f.asOf,...s.params,...c.params]);}

export async function remunerationReport(f:FinancialFilters){const s=scope('rm',f),c=currency('rm',f);return rows(`SELECT rm.currency_code currencyCode,COALESCE(SUM(CASE WHEN rm.created_at>=CONCAT(?,' 00:00:00') AND rm.created_at<DATE_ADD(?,INTERVAL 1 DAY) THEN rm.payable_amount ELSE 0 END),0) prepared,COALESCE(SUM(CASE WHEN rm.validated_at>=CONCAT(?,' 00:00:00') AND rm.validated_at<DATE_ADD(?,INTERVAL 1 DAY) THEN rm.payable_amount ELSE 0 END),0) validated,COALESCE(SUM(CASE WHEN rm.validated_at<=CONCAT(?,' 23:59:59') THEN rm.bonus_amount ELSE 0 END),0) bonuses,COALESCE(SUM(CASE WHEN be.approval_status='approved' AND DATE(be.decided_at)<=? THEN rm.payable_amount ELSE 0 END),0) engaged,COALESCE(SUM(CASE WHEN original.value_date<=? AND (reversal.id IS NULL OR reversal.value_date>?) THEN d.amount ELSE 0 END),0) paid FROM hr_remunerations rm LEFT JOIN budget_expenses be ON be.id=rm.budget_expense_id LEFT JOIN budget_expense_disbursements d ON d.budget_expense_id=be.id LEFT JOIN treasury_movements original ON original.source_type='BUDGET_EXPENSE_DISBURSEMENT' AND CAST(original.source_id AS UNSIGNED)=d.id AND original.event_type='POSTED' LEFT JOIN treasury_movements reversal ON reversal.reversal_of_id=original.id WHERE rm.validation_status='VALIDATED' AND DATE(rm.validated_at)<=? AND ${s.sql}${c.sql} GROUP BY rm.currency_code ORDER BY rm.currency_code`,[f.from,f.to,f.from,f.to,f.asOf,f.asOf,f.asOf,f.asOf,f.asOf,...s.params,...c.params]);}

export async function financialReport(r:Request,section:FinancialSection,exporting=false){const f=await financialFilters(r,section,exporting);let data:Record<string,unknown>[];if(section==='treasury')data=await treasuryReport(f);else if(section==='customers')data=await customerReport(f);else if(section==='budgets')data=await budgetReport(f);else if(section==='suppliers')data=await supplierReport(f);else if(section==='remunerations')data=await remunerationReport(f);else data=(await treasuryCoverage(r)) as unknown as Record<string,unknown>[];return{meta:{section,from:f.from,to:f.to,asOf:f.asOf,scope:f.scope,agencyId:f.agencyId,currency:f.currency,periodConvention:'[from, to + 1 jour)',currenciesSeparated:true,historicalLimitations:section==='coverage'?['La couverture est un instantané courant; asOf n’est pas rejoué historiquement.']:['Un statut annulé après asOf ne peut être reconstitué si son historique ne porte pas l’ancien statut.']},rows:data.map(x=>{const out:Record<string,unknown>={};for(const[k,v]of Object.entries(x))out[k]=typeof v==='number'?v:Number.isFinite(Number(v))&&v!==''?Number(v):v;const initial=Number(out.initialEnvelope??0),additional=Number(out.additionalEnvelope??0),engaged=Number(out.commitments??out.engaged??0),paid=Number(out.paid??0);if(section==='budgets')Object.assign(out,{totalEnvelope:initial+additional,remainingToPay:Math.max(0,engaged-paid),availableForCommitments:Math.max(0,initial+additional-engaged)});if(section==='customers')Object.assign(out,{netBilling:Number(out.issued??0)-Number(out.cancelled??0)-Number(out.credits??0),netCollections:Number(out.collections??0)-Number(out.refunds??0)});if(section==='suppliers')Object.assign(out,{netInvoices:Number(out.invoices??0)-Number(out.credits??0)});if(section==='remunerations')Object.assign(out,{remaining:Math.max(0,engaged-paid)});return out})};}
