import React,{useEffect,useState}from'react';
import{useNavigate}from'react-router-dom';
import{Search,RefreshCw,UserRound,Car,Wrench}from'lucide-react';
import{useExternalWorkshopCustomerDetailQuery,useExternalWorkshopCustomersQuery,type ExternalWorkshopCustomer}from'../../api/erpHooks';
import{Button}from'../../components/ui/Button';
import{Card,CardHeader,CardTitle}from'../../components/ui/Card';
import{TableEmptyState}from'../../components/common/TableEmptyState';
import{StatusBadge}from'../../components/common/StatusBadge';
import{formatDate}from'../../lib/utils';

interface Props{canCreateOrder:boolean;canViewCustomer:boolean;onNewOrder:(customerId:string)=>void}
const customerName=(customer:Pick<ExternalWorkshopCustomer,'companyName'|'civility'|'firstName'|'lastName'>)=>customer.companyName||[customer.civility,customer.firstName,customer.lastName].filter(Boolean).join(' ');
const statusFromDb:Record<string,string>={planned:'PLANIFIE',received:'RECEPTIONNE',diagnosis:'DIAGNOSTIC',waiting_approval:'ATTENTE_VALIDATION',in_progress:'EN_COURS',quality_control:'CONTROLE_QUALITE',ready:'PRET',invoiced:'FACTURE',delivered:'LIVRE',closed:'CLOTURE',cancelled:'ANNULE'};

export const ExternalCustomersPanel:React.FC<Props>=({canCreateOrder,canViewCustomer,onNewOrder})=>{
 const navigate=useNavigate(),[search,setSearch]=useState(''),[debouncedSearch,setDebouncedSearch]=useState(''),[page,setPage]=useState(1),[selectedId,setSelectedId]=useState('');
 useEffect(()=>{const timer=window.setTimeout(()=>{setDebouncedSearch(search.trim());setPage(1)},350);return()=>window.clearTimeout(timer)},[search]);
 const listQuery=useExternalWorkshopCustomersQuery({search:debouncedSearch,page,pageSize:7}),detailQuery=useExternalWorkshopCustomerDetailQuery(selectedId,Boolean(selectedId));
 const data=listQuery.data,items=data?.items??[],detail=detailQuery.data;
 useEffect(()=>{if(data&&data.page!==page)setPage(data.page)},[data,page]);
 return <div className="space-y-4">
  <div className="flex flex-col sm:flex-row gap-3 rounded-xl border border-slate-200 bg-white p-3.5"><div className="relative flex-1 max-w-md"><Search className="absolute left-3 top-2.5 h-4 w-4 text-slate-400"/><input value={search} onChange={event=>setSearch(event.target.value)} placeholder="Nom, entreprise, téléphone ou code client…" className="w-full rounded-lg border border-slate-200 bg-slate-50 py-2 pl-9 pr-3 text-xs focus:bg-white focus:outline-none focus:ring-2 focus:ring-blue-500"/></div><Button type="button" size="sm" variant="outline" icon={<RefreshCw className="h-4 w-4"/>} disabled={listQuery.isFetching} onClick={()=>listQuery.refetch()}>Rafraîchir</Button></div>
  {listQuery.isError&&<div className="rounded-lg border border-red-200 bg-red-50 p-3 text-sm text-red-800">Chargement des clients extérieurs impossible : {listQuery.error.message}</div>}
  <Card padding="none"><div className="overflow-x-auto"><table className="w-full min-w-[760px] text-left text-xs"><thead className="border-b bg-slate-50 uppercase tracking-wider text-slate-500"><tr><th className="px-4 py-3">Client</th><th className="px-4 py-3">Code client</th><th className="px-4 py-3">Téléphone</th><th className="px-4 py-3">Véhicules extérieurs</th><th className="px-4 py-3">OR extérieurs</th><th className="px-4 py-3">Dernier passage</th><th className="px-4 py-3 text-right">Actions</th></tr></thead><tbody className="divide-y divide-slate-100">{listQuery.isLoading&&<TableEmptyState colSpan={7} message="Chargement des clients extérieurs…" isLoading/>}{!listQuery.isLoading&&!listQuery.isError&&!items.length&&<TableEmptyState colSpan={7} message="Aucun client extérieur trouvé."/>}{items.map(customer=><tr key={customer.id} className="hover:bg-blue-50/50"><td className="px-4 py-3"><b>{customerName(customer)}</b>{customer.email&&<div className="text-[10px] text-slate-500">{customer.email}</div>}</td><td className="px-4 py-3 font-mono">{customer.code}</td><td className="px-4 py-3">{customer.phone||'—'}</td><td className="px-4 py-3">{customer.externalVehicleCount}</td><td className="px-4 py-3">{customer.externalOrderCount}</td><td className="px-4 py-3">{formatDate(customer.lastExternalOrderAt)}</td><td className="px-4 py-3"><div className="flex justify-end gap-2"><Button size="xs" variant="outline" onClick={()=>setSelectedId(customer.id)}>Détail</Button>{canCreateOrder&&<Button size="xs" onClick={()=>onNewOrder(customer.id)}>Nouvel OR</Button>}</div></td></tr>)}</tbody></table></div><div className="flex items-center justify-between border-t p-4 text-xs"><span>{data?.total??0} client(s)</span><div className="flex gap-2"><Button size="xs" variant="outline" disabled={page<=1} onClick={()=>setPage(value=>value-1)}>Précédent</Button><span>Page {page}/{Math.max(1,data?.totalPages??1)}</span><Button size="xs" variant="outline" disabled={page>=(data?.totalPages??1)} onClick={()=>setPage(value=>value+1)}>Suivant</Button></div></div></Card>
  {selectedId&&<Card><CardHeader><div><CardTitle>Détail du client extérieur</CardTitle><p className="mt-1 text-xs text-slate-500">Historique Atelier fondé uniquement sur les snapshots OR extérieurs.</p></div><Button size="xs" variant="outline" onClick={()=>setSelectedId('')}>Fermer</Button></CardHeader>{detailQuery.isLoading?<p className="text-sm text-slate-500">Chargement du détail…</p>:detailQuery.isError?<p className="text-sm text-red-700">Détail inaccessible : {detailQuery.error.message}</p>:detail&&<div className="space-y-5"><div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><div className="flex gap-3"><div className="rounded-lg bg-blue-50 p-2 text-blue-700"><UserRound className="h-5 w-5"/></div><div className="text-xs"><b className="text-sm">{customerName(detail.customer)}</b><p>{detail.customer.code} · {detail.customer.phone||'Sans téléphone'} · {detail.customer.email||'Sans e-mail'}</p></div></div><div className="flex gap-2">{canViewCustomer&&<Button size="xs" variant="outline" onClick={()=>navigate(`/customers/${detail.customer.id}`)}>Voir la fiche Client 360</Button>}{canCreateOrder&&<Button size="xs" icon={<Wrench className="h-3.5 w-3.5"/>} onClick={()=>onNewOrder(detail.customer.id)}>Nouvel OR</Button>}</div></div>
   <section><h4 className="mb-2 text-xs font-bold uppercase text-slate-600">Véhicules extérieurs reçus à l’Atelier</h4><div className="grid gap-2 md:grid-cols-2">{detail.vehicles.map(vehicle=><div key={vehicle.id} className="flex gap-3 rounded-lg border border-slate-200 p-3 text-xs"><Car className="h-5 w-5 shrink-0 text-blue-700"/><div><b>{vehicle.brand} {vehicle.model} {vehicle.version}</b><p>{vehicle.registrationNumber||'Sans immatriculation'} · {vehicle.vin||'Sans VIN'}</p><p className="text-slate-500">{vehicle.externalOrderCount} OR · dernier passage {formatDate(vehicle.lastExternalOrderAt)}</p></div></div>)}</div></section>
   <section><h4 className="mb-2 text-xs font-bold uppercase text-slate-600">Historique des OR extérieurs</h4><div className="overflow-x-auto"><table className="w-full min-w-[680px] text-left text-xs"><thead className="bg-slate-50"><tr><th className="p-2">OR</th><th className="p-2">Véhicule</th><th className="p-2">Date</th><th className="p-2">Statut</th><th className="p-2">Motif</th><th className="p-2"></th></tr></thead><tbody>{detail.repairOrders.map(order=><tr key={order.id} className="border-t"><td className="p-2 font-bold">{order.orderNumber}</td><td className="p-2">{order.vehicle.brand} {order.vehicle.model} · {order.vehicle.registrationNumber||order.vehicle.vin||'—'}</td><td className="p-2">{formatDate(order.createdAt)}</td><td className="p-2"><StatusBadge type="or" status={statusFromDb[order.status]??order.status}/></td><td className="max-w-xs truncate p-2">{order.complaint||'—'}</td><td className="p-2 text-right"><Button size="xs" variant="outline" onClick={()=>navigate(`/service/repair-orders/${order.id}`)}>Voir l’OR</Button></td></tr>)}</tbody></table></div></section>
  </div>}</Card>}
 </div>
};
