import argon2 from 'argon2';
import type { Request } from 'express';
import type { PoolConnection, ResultSetHeader, RowDataPacket } from 'mysql2/promise';
import { execute, query, transaction } from '../../config/database.js';
import { HttpError } from '../../shared/http-error.js';
import { assertAssignableRoles, assertCanManage, targetRoles } from './user-access.js';

type Input=Record<string,unknown>;
const txt=(v:unknown,label:string,required=false,max=190)=>{const x=typeof v==='string'?v.trim():'';if(required&&!x)throw new HttpError(400,`${label} obligatoire.`);if(x.length>max)throw new HttpError(400,`${label} trop long.`);return x||null};
const mail=(v:unknown)=>{const x=String(txt(v,'Email',true,190)).toLowerCase();if(!/^\S+@\S+\.\S+$/.test(x))throw new HttpError(400,'Adresse email invalide.');return x};
const pass=(v:unknown)=>{const x=typeof v==='string'?v:'';if(x.length<8)throw new HttpError(400,'Le mot de passe doit contenir au moins 8 caractères.');return x};
const roleCodes=(b:Input)=>Array.from(new Set((Array.isArray(b.roles)?b.roles:[b.roleCode]).filter((v):v is string=>typeof v==='string'&&!!v.trim()).map(v=>v.trim())));
const SELECT=`SELECT u.id,u.first_name,u.last_name,u.email,u.phone,u.job_title,u.agency_id,a.name agency_name,a.code agency_code,u.avatar_path,u.is_active,u.created_at,u.updated_at,GROUP_CONCAT(DISTINCT r.code ORDER BY r.code) roles FROM users u JOIN agencies a ON a.id=u.agency_id LEFT JOIN user_roles ur ON ur.user_id=u.id LEFT JOIN roles r ON r.id=ur.role_id`;
const map=(r:RowDataPacket)=>({id:String(r.id),firstName:r.first_name,lastName:r.last_name,fullName:`${r.first_name} ${r.last_name}`.trim(),displayName:`${r.first_name} ${r.last_name}`.trim(),email:r.email,phone:r.phone,jobTitle:r.job_title,agencyId:String(r.agency_id),agency:{id:String(r.agency_id),name:r.agency_name,code:r.agency_code},agencyName:r.agency_name,roles:r.roles?String(r.roles).split(','):[],isActive:Boolean(r.is_active),avatar:r.avatar_path,createdAt:r.created_at,updatedAt:r.updated_at});
async function validAgency(c:PoolConnection,value:unknown){const id=txt(value,'Agence',true,30)!;const[rows]=await c.execute<RowDataPacket[]>('SELECT id,is_active FROM agencies WHERE id=?',[id]);if(!rows[0])throw new HttpError(400,'INVALID_AGENCY');if(!rows[0].is_active)throw new HttpError(400,'AGENCY_INACTIVE');return id}
async function validRoles(c:PoolConnection,codes:string[]){if(!codes.length)throw new HttpError(400,'INVALID_ROLE');const[rows]=await c.execute<RowDataPacket[]>(`SELECT id,code FROM roles WHERE code IN (${codes.map(()=>'?').join(',')})`,codes);if(rows.length!==codes.length)throw new HttpError(400,'INVALID_ROLE');return rows}
async function audit(c:PoolConnection,req:Request,id:string,action:string,oldValue:unknown=null,newValue:unknown=null){await c.execute(`INSERT INTO audit_logs(user_id,module,entity_type,entity_id,action,old_values,new_values,ip_address,user_agent) VALUES(?,'users','user',?,?,?,?,?,?)`,[req.user!.sub,id,action,oldValue==null?null:JSON.stringify(oldValue),newValue==null?null:JSON.stringify(newValue),req.ip??null,req.get('user-agent')??null])}

export async function one(id:string){const[row]=await query<RowDataPacket[]>(`${SELECT} WHERE u.id=? GROUP BY u.id`,[id]);if(!row)throw new HttpError(404,'USER_NOT_FOUND');return map(row)}
export async function list(f:Record<string,unknown>){const p:unknown[]=[];let w=' WHERE 1=1';if(f.active==='true'||f.active==='false'){w+=' AND u.is_active=?';p.push(f.active==='true')}if(f.agencyId){w+=' AND u.agency_id=?';p.push(f.agencyId)}if(f.role){w+=' AND EXISTS(SELECT 1 FROM user_roles ux JOIN roles rx ON rx.id=ux.role_id WHERE ux.user_id=u.id AND rx.code=?)';p.push(f.role)}if(f.search){w+=` AND (CONCAT_WS(' ',u.first_name,u.last_name) LIKE ? OR u.email LIKE ?)`;p.push(`%${f.search}%`,`%${f.search}%`)}return(await query<RowDataPacket[]>(`${SELECT}${w} GROUP BY u.id ORDER BY u.last_name,u.first_name`,p)).map(map)}
export async function directory(f:Record<string,unknown>,req:Request){const p:unknown[]=[];let w=f.activeOnly==='false'&&req.user!.roles.some(r=>['SUPER_ADMIN','DIRECTOR'].includes(r))?' WHERE 1=1':' WHERE u.is_active=TRUE';const agency=f.agencyId?String(f.agencyId):req.user!.agencyId;if(!req.user!.roles.some(r=>['SUPER_ADMIN','DIRECTOR'].includes(r))&&String(agency)!==String(req.user!.agencyId))throw new HttpError(403,'Cette agence est hors de votre périmètre.');if(agency){w+=' AND u.agency_id=?';p.push(agency)}if(f.role){w+=' AND EXISTS(SELECT 1 FROM user_roles ux JOIN roles rx ON rx.id=ux.role_id WHERE ux.user_id=u.id AND rx.code=?)';p.push(f.role)}return(await query<RowDataPacket[]>(`${SELECT}${w} GROUP BY u.id ORDER BY u.last_name,u.first_name`,p)).map(r=>{const x=map(r);return{id:x.id,displayName:x.displayName,roles:x.roles,agencyId:x.agencyId,avatar:x.avatar,isActive:x.isActive}})}
export async function create(b:Input,req:Request){const first=txt(b.firstName,'Prénom',true,100)!,last=txt(b.lastName,'Nom',true,100)!,email=mail(b.email),password=pass(b.password),codes=roleCodes(b);assertAssignableRoles(req,codes);const id=await transaction(async c=>{const agencyId=await validAgency(c,b.agencyId),roles=await validRoles(c,codes),[duplicate]=await c.execute<RowDataPacket[]>('SELECT id FROM users WHERE email=?',[email]);if(duplicate[0])throw new HttpError(409,'EMAIL_ALREADY_EXISTS');const[result]=await c.execute<ResultSetHeader>('INSERT INTO users(agency_id,first_name,last_name,email,phone,password_hash,job_title,is_active) VALUES(?,?,?,?,?,?,?,TRUE)',[agencyId,first,last,email,txt(b.phone,'Téléphone',false,50),await argon2.hash(password),txt(b.jobTitle,'Fonction',false,120)]);for(const role of roles)await c.execute('INSERT INTO user_roles(user_id,role_id) VALUES(?,?)',[result.insertId,role.id]);await audit(c,req,String(result.insertId),'user.created',null,{firstName:first,lastName:last,email,agencyId,roles:codes});return String(result.insertId)});return one(id)}
async function protectLastSuper(id:string){const roles=await targetRoles(id);if(!roles.includes('SUPER_ADMIN'))return;const[row]=await query<RowDataPacket[]>(`SELECT COUNT(DISTINCT u.id) total FROM users u JOIN user_roles ur ON ur.user_id=u.id JOIN roles r ON r.id=ur.role_id WHERE u.is_active=TRUE AND r.code='SUPER_ADMIN'`);if(Number(row?.total)<=1)throw new HttpError(409,'LAST_SUPER_ADMIN')}
export async function update(id:string,b:Input,req:Request){const before=await one(id),oldRoles=await assertCanManage(req,id),changesRoles=Object.hasOwn(b,'roles')||Object.hasOwn(b,'roleCode'),nextRoles=changesRoles?roleCodes(b):oldRoles;if(changesRoles){assertAssignableRoles(req,nextRoles);if(oldRoles.includes('SUPER_ADMIN')&&!nextRoles.includes('SUPER_ADMIN'))await protectLastSuper(id)}await transaction(async c=>{const sets:string[]=[],values:any[]=[];for(const[field,column,label,max]of[['firstName','first_name','Prénom',100],['lastName','last_name','Nom',100],['phone','phone','Téléphone',50],['jobTitle','job_title','Fonction',120]]as const)if(Object.hasOwn(b,field)){sets.push(`${column}=?`);values.push(txt(b[field],label,field==='firstName'||field==='lastName',max))}if(Object.hasOwn(b,'email')){const email=mail(b.email),[dupe]=await c.execute<RowDataPacket[]>('SELECT id FROM users WHERE email=? AND id<>?',[email,id]);if(dupe[0])throw new HttpError(409,'EMAIL_ALREADY_EXISTS');sets.push('email=?');values.push(email)}let agencyId=before.agencyId;if(Object.hasOwn(b,'agencyId')){agencyId=await validAgency(c,b.agencyId);if(agencyId!==before.agencyId){const[busy]=await c.execute<RowDataPacket[]>(`SELECT COUNT(*) total FROM technicians t JOIN work_sessions ws ON ws.technician_id=t.id AND ws.status='running' WHERE t.user_id=?`,[id]);if(Number(busy[0]?.total)>0)throw new HttpError(409,'Ce technicien possède une session atelier active.');sets.push('agency_id=?');values.push(agencyId);await c.execute('UPDATE technicians SET agency_id=? WHERE user_id=?',[agencyId,id])}}if(sets.length)await c.execute(`UPDATE users SET ${sets.join(',')} WHERE id=?`,[...values,id]);if(changesRoles){const roles=await validRoles(c,nextRoles);await c.execute('DELETE FROM user_roles WHERE user_id=?',[id]);for(const role of roles)await c.execute('INSERT INTO user_roles(user_id,role_id) VALUES(?,?)',[id,role.id]);await c.execute('UPDATE technicians SET is_active=? WHERE user_id=?',[nextRoles.includes('TECHNICIAN'),id])}const action=agencyId!==before.agencyId?'user.agency_changed':changesRoles?'user.role_changed':'user.updated';await audit(c,req,id,action,{agencyId:before.agencyId,roles:oldRoles},{agencyId,roles:nextRoles});if(Object.hasOwn(b,'email'))await c.execute('UPDATE refresh_tokens SET revoked_at=NOW() WHERE user_id=? AND revoked_at IS NULL',[id])});return one(id)}
export async function status(id:string,value:unknown,req:Request){if(typeof value!=='boolean')throw new HttpError(400,'Statut invalide.');if(id===req.user!.sub&&!value)throw new HttpError(409,'CANNOT_DISABLE_SELF');await assertCanManage(req,id);if(!value)await protectLastSuper(id);await transaction(async c=>{const[result]=await c.execute<ResultSetHeader>('UPDATE users SET is_active=? WHERE id=?',[value,id]);if(!result.affectedRows)throw new HttpError(404,'USER_NOT_FOUND');if(!value){await c.execute('UPDATE refresh_tokens SET revoked_at=NOW() WHERE user_id=? AND revoked_at IS NULL',[id]);await c.execute('UPDATE technicians SET is_active=FALSE WHERE user_id=?',[id])}else if((await targetRoles(id)).includes('TECHNICIAN'))await c.execute('UPDATE technicians SET is_active=TRUE WHERE user_id=?',[id]);await audit(c,req,id,value?'user.reactivated':'user.disabled',null,{isActive:value})});return one(id)}
export async function changeOwnPassword(b:Input,req:Request){const next=pass(b.newPassword),[row]=await query<RowDataPacket[]>('SELECT password_hash FROM users WHERE id=? AND is_active=TRUE',[req.user!.sub]);if(!row||typeof b.currentPassword!=='string'||!await argon2.verify(String(row.password_hash),b.currentPassword))throw new HttpError(400,'CURRENT_PASSWORD_INVALID');await transaction(async c=>{await c.execute('UPDATE users SET password_hash=? WHERE id=?',[await argon2.hash(next),req.user!.sub]);await c.execute('UPDATE refresh_tokens SET revoked_at=NOW() WHERE user_id=? AND revoked_at IS NULL',[req.user!.sub]);await audit(c,req,req.user!.sub,'user.password_changed')});return{success:true}}
export async function resetPassword(id:string,b:Input,req:Request){await assertCanManage(req,id);const next=pass(b.newPassword);await transaction(async c=>{const[result]=await c.execute<ResultSetHeader>('UPDATE users SET password_hash=? WHERE id=?',[await argon2.hash(next),id]);if(!result.affectedRows)throw new HttpError(404,'USER_NOT_FOUND');await c.execute('UPDATE refresh_tokens SET revoked_at=NOW() WHERE user_id=? AND revoked_at IS NULL',[id]);await audit(c,req,id,'user.password_reset')});return{success:true}}
export async function rolesList(){return query<RowDataPacket[]>('SELECT id,code,name,description,is_system FROM roles ORDER BY name')}
export async function rolePermissions(id:string){const[role]=await query<RowDataPacket[]>('SELECT id,code,name,description FROM roles WHERE id=?',[id]);if(!role)throw new HttpError(404,'Rôle introuvable.');const permissions=await query<RowDataPacket[]>('SELECT p.id,p.module,p.action,p.code,p.description FROM permissions p JOIN role_permissions rp ON rp.permission_id=p.id WHERE rp.role_id=? ORDER BY p.module,p.action',[id]);return{...role,permissions}}
export async function avatarChanged(id:string,avatar:string|null,req:Request){await transaction(async c=>{await c.execute('UPDATE users SET avatar_path=? WHERE id=?',[avatar,id]);await audit(c,req,id,'user.avatar_changed',null,{hasAvatar:Boolean(avatar)})});return one(id)}
