import {Router,type Request} from 'express';
import type {PoolConnection,ResultSetHeader,RowDataPacket} from 'mysql2/promise';
import {query,transaction} from '../../config/database.js';
import {requirePermission,requireAnyPermission} from '../../middleware/require-permission.js';
import {asyncHandler} from '../../middleware/error-handler.js';
import {HttpError} from '../../shared/http-error.js';
import {permissionScopePredicate,type ScopePredicate} from '../rbac/scope-intersection.js';
import {writeAudit} from '../activity/audit-writer.js';
import {normalizeWorkshopRegistration,normalizeWorkshopVin} from './workshop-vehicle-normalization.js';

export const workshopVehicleRouter=Router();
const relationTypes=['OWNER','DRIVER','RESPONSIBLE','FLEET'] as const;
const sourceTypes=['SALE','REPAIR_ORDER','MANUAL','IMPORT'] as const;
const id=(value:unknown,name='Identifiant')=>{const text=String(value??'');if(!/^[1-9]\d*$/.test(text))throw new HttpError(400,`${name} invalide`);return text};
const optional=(value:unknown,max:number)=>{if(value==null||value==='')return null;if(typeof value!=='string')throw new HttpError(400,'Valeur texte invalide');const text=value.trim();if(text.length>max)throw new HttpError(400,`Valeur trop longue (${max} caractères maximum)`);return text||null};
const unsigned=(value:unknown,name:string,max=4294967295)=>{if(value==null||value==='')return null;const parsed=Number(value);if(!Number.isInteger(parsed)||parsed<0||parsed>max)throw new HttpError(400,`${name} invalide`);return parsed};
const plateSql=(alias='v')=>`UPPER(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(${alias}.registration_number,' ',''),'-',''),'.',''),'/',''),'_',''),'–',''))`;
const relationScope=(request:Request,permission:string,alias='cv')=>permissionScopePredicate(request,permission,{agency:`${alias}.agency_id`,owner:`${alias}.created_by`});
const vehicleScope=(request:Request,permission:string,alias='v'):ScopePredicate|null=>{
  const direct=permissionScopePredicate(request,permission,{agency:`${alias}.agency_id`,owner:`${alias}.created_by`});
  if(!direct)return null;
  const scope=request.rbac?.permissions.get(permission);
  if(scope==='GLOBAL')return direct;
  const relation=relationScope(request,permission,'cv_scope');
  return{sql:`((${direct.sql}) OR EXISTS(SELECT 1 FROM customer_vehicles cv_scope WHERE cv_scope.vehicle_id=${alias}.id AND cv_scope.is_current=TRUE AND ${relation!.sql}))`,params:[...direct.params,...relation!.params]};
};
const requireScope=(scope:ScopePredicate|null,permission:string)=>{if(!scope)throw new HttpError(403,`Scope manquant pour ${permission}`);return scope};
const customerScope=(request:Request,alias='c')=>requireScope(permissionScopePredicate(request,'customers.view',{agency:`${alias}.agency_id`,owner:`${alias}.assigned_user_id`,ownRequiresAgency:false}),'customers.view');
const assertAgency=async(connection:PoolConnection,request:Request,permission:string,agencyId:string)=>{const scope=request.rbac?.permissions.get(permission),current=request.user?.agencyId;let predicate:ScopePredicate|null=null;if(scope==='GLOBAL')predicate={sql:'1=1',params:[]};else if(current&&(scope==='OWN'||scope==='AGENCY'))predicate={sql:'a.id=?',params:[current]};else if(current&&scope==='CONCESSION')predicate={sql:'a.concession_id=(SELECT concession_id FROM agencies WHERE id=?)',params:[current]};predicate=requireScope(predicate,permission);const[rows]=await connection.execute<RowDataPacket[]>(`SELECT a.id FROM agencies a WHERE a.id=? AND a.is_active=TRUE AND ${predicate.sql}`,[agencyId,...predicate.params] as any[]);if(!rows[0])throw new HttpError(403,'Agence hors périmètre ou inactive')};
const assertCustomer=async(connection:PoolConnection,request:Request,customerId:string)=>{const scope=customerScope(request);const[rows]=await connection.execute<RowDataPacket[]>(`SELECT c.id,c.agency_id FROM customers c WHERE c.id=? AND ${scope.sql} FOR UPDATE`,[customerId,...scope.params] as any[]);if(!rows[0])throw new HttpError(404,'Client introuvable');return rows[0]};
const mapVehicle=(row:RowDataPacket)=>({id:String(row.id),vin:row.vin??null,registrationNumber:row.registration_number??null,brand:row.brand??'',model:row.model??'',version:row.version??'',year:row.year==null?null:Number(row.year),agencyId:String(row.agency_id),commercialOrigin:row.commercial_origin,isCommercialStock:Boolean(row.is_commercial_stock)});
const vehicleSelect=`SELECT v.id,v.vin,v.registration_number,v.year,v.agency_id,v.commercial_origin,v.is_commercial_stock,COALESCE(b.name,v.identity_brand) brand,COALESCE(m.name,v.identity_model) model,COALESCE(ve.name,v.identity_version) version FROM vehicles v LEFT JOIN versions ve ON ve.id=v.version_id LEFT JOIN models m ON m.id=ve.model_id LEFT JOIN brands b ON b.id=m.brand_id`;
const conflictDetails=(code:string,matches:RowDataPacket[])=>({code,matches:matches.map(mapVehicle)});

workshopVehicleRouter.get('/workshop/vehicles/search',requirePermission('workshop.vehicles.view'),asyncHandler(async(request,response)=>{
  const scope=requireScope(vehicleScope(request,'workshop.vehicles.view'),'workshop.vehicles.view'),vin=normalizeWorkshopVin(request.query.vin),registration=normalizeWorkshopRegistration(request.query.registration),brand=optional(request.query.brand,120),model=optional(request.query.model,120),customerId=request.query.customerId==null?null:id(request.query.customerId,'Client');
  if(!vin&&!registration.search&&!brand&&!model&&!customerId)throw new HttpError(400,'Au moins un critère de recherche est requis');
  const clauses=[scope.sql,'v.archived_at IS NULL'],params:unknown[]=[...scope.params];
  if(vin){clauses.push('v.vin=?');params.push(vin)}if(registration.search){clauses.push(`${plateSql()}=?`);params.push(registration.search)}if(brand){clauses.push('COALESCE(b.name,v.identity_brand) LIKE ?');params.push(`%${brand}%`)}if(model){clauses.push('COALESCE(m.name,v.identity_model) LIKE ?');params.push(`%${model}%`)}if(customerId){clauses.push('EXISTS(SELECT 1 FROM customer_vehicles cv WHERE cv.vehicle_id=v.id AND cv.customer_id=? AND cv.is_current=TRUE)');params.push(customerId)}
  const rows=await query<RowDataPacket[]>(`${vehicleSelect} WHERE ${clauses.join(' AND ')} ORDER BY v.updated_at DESC,v.id DESC LIMIT 50`,params);response.json({items:rows.map(mapVehicle),ambiguous:rows.length>1});
}));

async function insertAssociation(connection:PoolConnection,request:Request,input:{customerId:string;vehicleId:string;agencyId:string;relationType:string;sourceType:string;sourceId:string|null;validFrom:string|null;notes:string|null}){
  if(!relationTypes.includes(input.relationType as never))throw new HttpError(400,'Type de relation invalide');if(!sourceTypes.includes(input.sourceType as never))throw new HttpError(400,'Source de relation invalide');
  await assertAgency(connection,request,'workshop.vehicle.associations.create',input.agencyId);await assertCustomer(connection,request,input.customerId);
  const[vehicles]=await connection.execute<RowDataPacket[]>('SELECT id FROM vehicles WHERE id=? AND archived_at IS NULL FOR UPDATE',[input.vehicleId]);if(!vehicles[0])throw new HttpError(404,'Véhicule introuvable');
  const access=requireScope(vehicleScope(request,'workshop.vehicles.view'),'workshop.vehicles.view');const[allowed]=await connection.execute<RowDataPacket[]>(`SELECT v.id FROM vehicles v WHERE v.id=? AND ${access.sql}`,[input.vehicleId,...access.params] as any[]);if(!allowed[0])throw new HttpError(404,'Véhicule introuvable');
  const[duplicate]=await connection.execute<RowDataPacket[]>('SELECT id FROM customer_vehicles WHERE customer_id=? AND vehicle_id=? AND relation_type=? AND is_current=TRUE FOR UPDATE',[input.customerId,input.vehicleId,input.relationType]);if(duplicate[0])throw new HttpError(409,'Cette relation courante existe déjà',{code:'RELATION_ALREADY_EXISTS'});
  if(input.relationType==='OWNER'){const[owner]=await connection.execute<RowDataPacket[]>('SELECT id FROM customer_vehicles WHERE vehicle_id=? AND relation_type=\'OWNER\' AND is_current=TRUE AND customer_id<>? FOR UPDATE',[input.vehicleId,input.customerId]);if(owner[0])throw new HttpError(409,'Ce véhicule possède déjà un propriétaire courant',{code:'CURRENT_OWNER_CONFLICT'})}
  try{const[result]=await connection.execute<ResultSetHeader>('INSERT INTO customer_vehicles(customer_id,vehicle_id,agency_id,relation_type,source_type,source_id,valid_from,notes,created_by) VALUES(?,?,?,?,?,?,COALESCE(?,CURRENT_TIMESTAMP),?,?)',[input.customerId,input.vehicleId,input.agencyId,input.relationType,input.sourceType,input.sourceId,input.validFrom,input.notes,request.user!.sub]);await writeAudit(connection,request,{module:'workshop',entityType:'customer_vehicle',entityId:String(result.insertId),action:'workshop.vehicle.association.created',newValues:{customerId:input.customerId,vehicleId:input.vehicleId,agencyId:input.agencyId,relationType:input.relationType,sourceType:input.sourceType}});return String(result.insertId)}catch(error:any){if(error?.code==='ER_DUP_ENTRY')throw new HttpError(409,'Cette relation courante existe déjà',{code:'RELATION_ALREADY_EXISTS'});throw error}
}

workshopVehicleRouter.post('/workshop/external-vehicles',requirePermission('workshop.external_vehicle.create'),requirePermission('workshop.vehicle.associations.create'),requirePermission('workshop.vehicles.view'),asyncHandler(async(request,response)=>{
  const body=request.body as Record<string,unknown>,customerId=id(body.customerId,'Client'),agencyId=id(body.agencyId??request.user?.agencyId,'Agence'),vin=normalizeWorkshopVin(body.vin),registration=normalizeWorkshopRegistration(body.registrationNumber),brand=optional(body.brand,120),model=optional(body.model,120),version=optional(body.version,150),versionId=body.versionId==null||body.versionId===''?null:id(body.versionId,'Version');
  if(!versionId&&(!brand||!model))throw new HttpError(400,'La marque et le modèle sont requis hors catalogue');
  const result=await transaction(async connection=>{await assertAgency(connection,request,'workshop.external_vehicle.create',agencyId);await assertCustomer(connection,request,customerId);
    if(vin){const[found]=await connection.execute<RowDataPacket[]>('SELECT id FROM vehicles WHERE vin=? LIMIT 1 FOR UPDATE',[vin]);if(found[0])throw new HttpError(409,'Un véhicule portant ce VIN existe déjà',conflictDetails('VIN_ALREADY_EXISTS',[]))}
    if(registration.search){const[found]=await connection.execute<RowDataPacket[]>(`SELECT v.id FROM vehicles v WHERE ${plateSql()}=? AND v.archived_at IS NULL FOR UPDATE`,[registration.search]);if(found.length&&!Boolean(body.confirmRegistrationAmbiguity)){const access=requireScope(vehicleScope(request,'workshop.vehicles.view'),'workshop.vehicles.view'),[visible]=await connection.execute<RowDataPacket[]>(`${vehicleSelect} WHERE ${plateSql()}=? AND v.archived_at IS NULL AND ${access.sql}`,[registration.search,...access.params] as any[]);throw new HttpError(409,'Une ou plusieurs immatriculations correspondent déjà',conflictDetails('REGISTRATION_AMBIGUOUS',visible))}}
    if(versionId){const[ref]=await connection.execute<RowDataPacket[]>('SELECT ve.id FROM versions ve WHERE ve.id=? AND ve.is_active=TRUE',[versionId]);if(!ref[0])throw new HttpError(400,'Version catalogue invalide ou inactive')}
    const vehicleType=optional(body.vehicleType,20)??'used';if(!['new','used','demo','courtesy'].includes(vehicleType))throw new HttpError(400,'Type de véhicule invalide');
    let vehicleId:string;try{const[created]=await connection.execute<ResultSetHeader>(`INSERT INTO vehicles(version_id,agency_id,commercial_origin,commercial_origin_source,is_commercial_stock,identity_brand,identity_model,identity_version,vehicle_type,vin,registration_number,body_type,year,first_registration_date,color,interior_color,fuel_type,engine,transmission,fiscal_power,real_power,co2_emissions,mileage,status,notes,created_by) VALUES(?,?,'EXTERNAL','WORKSHOP',FALSE,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,'received',?,?)`,[versionId,agencyId,versionId?null:brand,versionId?null:model,versionId?null:version,vehicleType,vin,registration.display,optional(body.bodyType,60),unsigned(body.year,'Année',2155),optional(body.firstRegistrationDate,10),optional(body.color,80),optional(body.interiorColor,80),optional(body.fuelType,50),optional(body.engine,120),optional(body.transmission,50),unsigned(body.fiscalPower,'Puissance fiscale',65535),unsigned(body.realPower,'Puissance réelle',65535),unsigned(body.co2Emissions,'Émissions CO2',65535),unsigned(body.mileage,'Kilométrage')??0,optional(body.notes,5000),request.user!.sub]);vehicleId=String(created.insertId)}catch(error:any){if(error?.code==='ER_DUP_ENTRY')throw new HttpError(409,'Un véhicule portant ce VIN existe déjà',{code:'VIN_ALREADY_EXISTS'});throw error}
    await writeAudit(connection,request,{module:'workshop',entityType:'vehicle',entityId:vehicleId,action:'workshop.external_vehicle.created',newValues:{agencyId,commercialOrigin:'EXTERNAL',commercialOriginSource:'WORKSHOP',isCommercialStock:false,vinProvided:Boolean(vin),registrationProvided:Boolean(registration.display)}});
    const associationId=await insertAssociation(connection,request,{customerId,vehicleId,agencyId,relationType:String(body.relationType??'OWNER'),sourceType:'MANUAL',sourceId:null,validFrom:optional(body.validFrom,25),notes:optional(body.associationNotes,500)});return{vehicleId,associationId};
  });response.status(201).json(result);
}));

workshopVehicleRouter.post('/workshop/vehicle-associations',requirePermission('workshop.vehicle.associations.create'),requirePermission('workshop.vehicles.view'),asyncHandler(async(request,response)=>{const body=request.body as Record<string,unknown>;const associationId=await transaction(connection=>insertAssociation(connection,request,{customerId:id(body.customerId,'Client'),vehicleId:id(body.vehicleId,'Véhicule'),agencyId:id(body.agencyId??request.user?.agencyId,'Agence'),relationType:String(body.relationType??'OWNER'),sourceType:'MANUAL',sourceId:null,validFrom:optional(body.validFrom,25),notes:optional(body.notes,500)}));response.status(201).json({associationId})}));

workshopVehicleRouter.get('/workshop/customers/:customerId/vehicle-associations',requireAnyPermission(['workshop.vehicle.associations.view','workshop.vehicle.associations.close']),asyncHandler(async(request,response)=>{
  const customerId=id(request.params.customerId,'Client'),permission=request.rbac!.permissions.has('workshop.vehicle.associations.view')?'workshop.vehicle.associations.view':'workshop.vehicle.associations.close',scope=requireScope(relationScope(request,permission),permission),customer=customerScope(request);
  const rows=await query<RowDataPacket[]>(`SELECT cv.*,v.vin,v.registration_number,COALESCE(b.name,v.identity_brand) brand,COALESCE(m.name,v.identity_model) model,COALESCE(ve.name,v.identity_version) version FROM customer_vehicles cv JOIN customers c ON c.id=cv.customer_id JOIN vehicles v ON v.id=cv.vehicle_id LEFT JOIN versions ve ON ve.id=v.version_id LEFT JOIN models m ON m.id=ve.model_id LEFT JOIN brands b ON b.id=m.brand_id WHERE cv.customer_id=? AND ${scope.sql} AND ${customer.sql} AND (?=TRUE OR cv.is_current=TRUE) ORDER BY cv.is_current DESC,cv.valid_from DESC,cv.id DESC`,[customerId,...scope.params,...customer.params,String(request.query.includeHistory)==='true']);
  response.json(rows.map(row=>({id:String(row.id),customerId:String(row.customer_id),vehicleId:String(row.vehicle_id),agencyId:String(row.agency_id),relationType:row.relation_type,sourceType:row.source_type,sourceId:row.source_id==null?null:String(row.source_id),isCurrent:Boolean(row.is_current),validFrom:row.valid_from,validTo:row.valid_to,notes:row.notes,vehicle:mapVehicle(row)})));
}));

workshopVehicleRouter.patch('/workshop/vehicle-associations/:id/close',requirePermission('workshop.vehicle.associations.close'),asyncHandler(async(request,response)=>{
  const associationId=id(request.params.id,'Relation'),closed=await transaction(async connection=>{
    const scope=requireScope(relationScope(request,'workshop.vehicle.associations.close'),'workshop.vehicle.associations.close');
    const[rows]=await connection.execute<RowDataPacket[]>(`SELECT cv.* FROM customer_vehicles cv WHERE cv.id=? AND ${scope.sql} FOR UPDATE`,[associationId,...scope.params] as any[]),row=rows[0];
    if(!row)throw new HttpError(404,'Relation introuvable');if(!row.is_current)throw new HttpError(409,'Cette relation est déjà clôturée');
    const validTo=optional(request.body?.validTo,25)??new Date().toISOString().slice(0,19).replace('T',' '),[result]=await connection.execute<ResultSetHeader>('UPDATE customer_vehicles SET is_current=FALSE,valid_to=? WHERE id=? AND is_current=TRUE AND ?>=valid_from',[validTo,associationId,validTo]);
    if(!result.affectedRows)throw new HttpError(400,'La date de fin doit être postérieure à la date de début');await writeAudit(connection,request,{module:'workshop',entityType:'customer_vehicle',entityId:associationId,action:'workshop.vehicle.association.closed',oldValues:{isCurrent:true},newValues:{isCurrent:false,validTo}});return validTo;
  });response.json({id:associationId,isCurrent:false,validTo:closed});
}));
