import assert from'node:assert/strict';
import{readFileSync}from'node:fs';
import{test}from'node:test';
const read=(path:string)=>readFileSync(new URL(path,import.meta.url),'utf8');

test('ESSAI-06/07/08 l’entrée CRM crée les lignes Showroom et persiste appointment vers test_drive',()=>{const route=read('../src/modules/showroom/showroom.routes.ts');assert.match(route,/post\('\/showroom\/crm\/leads\/:leadId\/test-drives'/);assert.match(route,/INSERT INTO showroom_visits/);assert.match(route,/INSERT INTO showroom_test_drives/);assert.match(route,/requireCrmAppointmentForTestDrive/);assert.match(route,/markCrmTestDriveStarted/)});
test('ESSAI-02 le backend garde le vrai rendez-vous comme prérequis autoritaire',()=>{const policy=read('../src/modules/showroom/showroom-test-drive.ts');assert.match(policy,/a\.type='appointment'/);assert.match(policy,/f\.status IN\('pending','completed'\)/);assert.match(policy,/opportunity\.stage!=='appointment'/);assert.match(policy,/Un rendez-vous doit être enregistré/)});
test('DEVIS-01/02/03/04 conserve tables, auteur technique et propriétaire commercial',()=>{const service=read('../src/modules/quotations/quotation.service.ts');assert.match(service,/INSERT INTO quotations\(quotation_number,customer_id,opportunity_id,agency_id,created_by/);assert.match(service,/INSERT INTO quotation_items/);assert.match(service,/request\.user!\.sub/);assert.match(service,/opportunity\.assigned_user_id/)});
test('DEVIS-05/06/07 protège prérequis, propriétaire et agence par erreurs métier',()=>{const service=read('../src/modules/quotations/quotation.service.ts');assert.match(service,/throw new HttpError\(409,'Un essai réel/);assert.match(service,/throw new HttpError\(403,'Ce devis appartient/);assert.match(service,/throw new HttpError\(403,'Opportunité rattachée/)});
test('DEVIS-08 utilise la transaction partagée et ne crée aucun client avec un enum classification invalide',()=>{const service=read('../src/modules/quotations/quotation.service.ts');assert.match(service,/transaction\(async connection/);assert.doesNotMatch(service,/classification\).*'prospect'/);assert.match(service,/INSERT INTO customers\(customer_code,customer_type,agency_id/)});
