import assert from'node:assert/strict';
import test from'node:test';
import mysql,{type RowDataPacket}from'mysql2/promise';
import{assertTestDriveStartAvailable}from'../src/modules/showroom/showroom-test-drive.js';
const enabled=process.env.CORR_ERP_02E_MYSQL==='1';
const pool=mysql.createPool({host:process.env.DB_HOST,port:Number(process.env.DB_PORT??3306),user:process.env.DB_USER,password:process.env.DB_PASSWORD,database:process.env.DB_NAME,connectionLimit:8});
const at=(minutes:number)=>new Date(Date.now()+minutes*60000);
async function reserve(vehicleId:string,advisorId:string,visitId:string,start:Date,duration=30){for(let attempt=1;;attempt++){const c=await pool.getConnection();try{await c.beginTransaction();await assertTestDriveStartAvailable(c,{vehicleId,advisorId,agencyId:'1',visitId,scheduledAt:start,durationMinutes:duration});await c.execute("INSERT INTO showroom_test_drives(visit_id,vehicle_id,agency_id,advisor_id,status,scheduled_at,duration_minutes) VALUES(?,?,1,?,'planned',?,?)",[visitId,vehicleId,advisorId,start,duration]);await c.commit();return'created'}catch(error:any){await c.rollback();if(error?.status===409)return'conflict';if(error?.code!=='ER_LOCK_DEADLOCK'||attempt>=3)throw error}finally{c.release()}}}
const clear=()=>pool.execute('DELETE FROM showroom_test_drives');
test('CORR-ERP-02E MySQL 8.4 sérialise les créneaux futurs et accepte les bornes adjacentes',{skip:!enabled},async()=>{const start=at(120);await clear();assert.deepEqual((await Promise.all([reserve('1','1','1',start),reserve('1','2','2',start)])).sort(),['conflict','created']);await clear();assert.deepEqual((await Promise.all([reserve('1','1','1',start),reserve('2','1','2',start)])).sort(),['conflict','created']);await clear();assert.equal(await reserve('1','1','1',start),'created');assert.equal(await reserve('1','1','2',new Date(start.getTime()+30*60000)),'created');await clear();assert.deepEqual((await Promise.all([reserve('1','1','1',start),reserve('2','2','2',start)])).sort(),['created','created']);const[rows]=await pool.query<RowDataPacket[]>("SELECT COUNT(*) total FROM showroom_test_drives WHERE status='planned'");assert.equal(Number(rows[0]!.total),2);await clear();await pool.end()});
