import assert from 'node:assert/strict';
import {after,before,beforeEach,test} from 'node:test';
import jwt from 'jsonwebtoken';
import request from 'supertest';
import {createApp} from '../src/app.js';
import {env} from '../src/config/env.js';
import {pool} from '../src/config/database.js';

const originalExecute=pool.execute.bind(pool),originalGetConnection=pool.getConnection.bind(pool);
let ownerId='100',target={id:'101',agency_id:'1',is_active:1,roles:'SALES_AGENT'},writes:{sql:string;params:unknown[]}[]=[];
const lead=()=>({lead_id:'10',opportunity_id:'20',customer_id:null,first_name:'Koffi',last_name:'Test',company_name:null,email:'koffi@test.local',phone:'+242060000001',source:'Web',lead_status:'qualified',priority:'medium',assigned_user_id:ownerId,created_by:'200',title:'SUV',stage:'qualified',expected_value:15000000,probability:60,expected_close_date:null,lost_reason:null,notes:null,assigned_user_name:ownerId==='101'?'Carlos':'Elion',created_by_name:'Malik',agency_id:'1',agency_name:'Agence principale',created_at:'2026-09-08',updated_at:'2026-09-08'});
const token=(role:string,id:string)=>jwt.sign({sub:id,email:`${id}@lca.cg`,roles:[role],agencyId:'1'},env.jwt.accessSecret,{expiresIn:'5m'});
before(()=>{(pool as any).execute=async(sql:string)=>{if(sql.includes('FROM leads l JOIN opportunities o'))return[[lead()],[]];if(sql.includes('FROM users u LEFT JOIN user_roles'))return[[target],[]];return[[],[]]};(pool as any).getConnection=async()=>({beginTransaction:async()=>{},commit:async()=>{},rollback:async()=>{},release:()=>{},execute:async(sql:string,params:unknown[]=[])=>{writes.push({sql,params});if(sql.startsWith('UPDATE leads SET')&&sql.includes('assigned_user_id'))ownerId=String(params[0]);return[{affectedRows:1},[]]}})});
after(()=>{(pool as any).execute=originalExecute;(pool as any).getConnection=originalGetConnection});beforeEach(()=>{ownerId='100';target={id:'101',agency_id:'1',is_active:1,roles:'SALES_AGENT'};writes=[]});
test('REASSIGN-01 un commercial ne peut pas transférer son prospect à Carlos',async()=>{const response=await request(createApp()).patch('/api/leads/10').set('Authorization',`Bearer ${token('SALES_AGENT','100')}`).send({assignedUserId:'101'});assert.equal(response.status,403);assert.equal(ownerId,'100');assert.equal(writes.length,0)});
test('REASSIGN-02/05 Malik réaffecte Elion vers Carlos avec historique',async()=>{const response=await request(createApp()).patch('/api/leads/10').set('Authorization',`Bearer ${token('SALES_MANAGER','200')}`).send({assignedUserId:'101'});assert.equal(response.status,200);assert.equal(response.body.assignedUserId,'101');assert.equal(response.body.createdById,'200');const history=writes.find(item=>item.sql.includes('INSERT INTO activities'));assert.ok(history);assert.ok(history.params.includes('Réaffectation commerciale'));assert.ok(history.params.some(value=>String(value).includes('100 → 101')))});
test('REASSIGN-03 Malik ne peut pas cibler un commercial d’une autre agence',async()=>{target={...target,agency_id:'2'};const response=await request(createApp()).patch('/api/leads/10').set('Authorization',`Bearer ${token('SALES_MANAGER','200')}`).send({assignedUserId:'101'});assert.equal(response.status,403);assert.equal(ownerId,'100')});
test('REASSIGN-04 Malik ne peut cibler ni utilisateur inactif ni rôle incompatible',async()=>{target={...target,is_active:0};let response=await request(createApp()).patch('/api/leads/10').set('Authorization',`Bearer ${token('SALES_MANAGER','200')}`).send({assignedUserId:'101'});assert.equal(response.status,400);assert.match(response.body.message,/inactif/);target={...target,is_active:1,roles:'TECHNICIAN'};response=await request(createApp()).patch('/api/leads/10').set('Authorization',`Bearer ${token('SALES_MANAGER','200')}`).send({assignedUserId:'101'});assert.equal(response.status,400);assert.match(response.body.message,/ne peut pas être affecté/);assert.equal(ownerId,'100')});
