import assert from'node:assert/strict';import{readFileSync}from'node:fs';import test from'node:test';import{dashboardComparison}from'../src/modules/dashboard/dashboard.routes.js';
const source=(p:string)=>readFileSync(new URL(`../${p}`,import.meta.url),'utf8'),runtime=source('src/modules/dashboard/dashboard.routes.ts');
test('DASH-01 endpoint exige dashboard.view',()=>assert.match(runtime,/dashboard\/overview',requirePermission\('dashboard\.view'\)/));
test('DASH-02 sections utilisent leurs permissions métier',()=>{for(const p of ['billing.view','sales.view','crm.prospect.view','vehicles.view','showroom.view','delivery.view','service.order.view'])assert.match(runtime,new RegExp(p.replace('.','\\.')))});
test('DASH-03 aucun rôle historique ne gouverne le runtime',()=>assert.doesNotMatch(runtime,/DIRECTOR|DIRECTION|ACCOUNTANT|MANAGER|RECEPTIONIST|roles\.includes|authorize\(/));
test('DASH-04 scopes AGENCY CONCESSION GLOBAL sont distincts',()=>{assert.match(runtime,/s==='GLOBAL'/);assert.match(runtime,/s==='CONCESSION'/);assert.match(runtime,/s==='AGENCY'/)});
test('DASH-05 OWN exige une vraie colonne owner',()=>{assert.match(runtime,/s==='OWN'&&owner/);assert.match(runtime,/salesperson_id/);assert.match(runtime,/assigned_user_id/);assert.match(runtime,/advisor_id/)});
test('DASH-06 delta zéro reste neutre',()=>{assert.equal(dashboardComparison(10,0).deltaPercent,null);assert.equal(dashboardComparison(0,0).deltaPercent,null);assert.equal(dashboardComparison(15,10).deltaPercent,50)});
test('DASH-07 montants ne sont pas multipliés par les avoirs',()=>assert.match(runtime,/LEFT JOIN\(SELECT invoice_id,SUM\(amount\).*GROUP BY invoice_id/));
test('DASH-08 marge exige la permission financière véhicule',()=>assert.match(runtime,/vehicles\.financials\.view/));
test('DASH-09 KPI sans données utilisent null ou zéro SQL',()=>{assert.match(runtime,/COALESCE\(SUM/);assert.match(runtime,/revenue:revenue\?/)});
test('DASH-10 aucun ancien KPI fictif',()=>assert.doesNotMatch(runtime,/\+14%|12[.,]5%|4 essais|8 actifs|20 véhicules|3 visiteurs|2 prévus|3 en cours/));
test('SEARCH-01 endpoint exige dashboard.view et longueur minimale',()=>{assert.match(runtime,/global-search',requirePermission\('dashboard\.view'\)/);assert.match(runtime,/q\.length<2/)});
test('SEARCH-02 chaque type utilise sa permission et son scope',()=>{for(const p of ['customers.view','vehicles.view','crm.prospect.view','sales.view','service.order.view','billing.view','parts.view'])assert.match(runtime,new RegExp(p.replace('.','\\.')))});
test('SEARCH-03 résultats sont minimaux et bornés',()=>{assert.match(runtime,/LIMIT 5/g);assert.doesNotMatch(runtime,/SELECT \*/)});
test('SEARCH-04 requêtes LIKE sont paramétrées et échappées',()=>{assert.match(runtime,/LIKE \? ESCAPE/);assert.match(runtime,/replace\(\/\[\\\\%_\]/);assert.doesNotMatch(runtime,/LIKE ['"]%\$\{/)});
test('SEARCH-05 filtres agency concession user client ne sont pas acceptés',()=>assert.doesNotMatch(runtime,/query\.(agencyId|concessionId|userId)/));
test('SEARCH-06 mixed scopes sont calculés permission par permission',()=>assert.equal((runtime.match(/scope\(r,'[^']+'/g)??[]).length>=14,true));
test('SEARCH-07 navigation cible des routes existantes',()=>{for(const route of ['/customers','/vehicles','/crm/leads','/sales','/billing','/service/repair-orders','/parts'])assert.match(runtime,new RegExp(route))});
test('SEARCH-08 faux Super Admin ne peut pas être créé dans ce module',()=>assert.doesNotMatch(runtime,/role\.code|SUPER_ADMIN/));
