import test from'node:test';import assert from'node:assert/strict';import{readFileSync}from'node:fs';import{resolve}from'node:path';import{lockActiveSaleInvoice,useDeliveryFinancialAuthorization}from'../src/modules/billing/sale-financial-gate.js';
const root=resolve(import.meta.dirname,'../..'),read=(path:string)=>readFileSync(resolve(root,path),'utf8'),migration=read('backend-node/database/migrations/060_delivery_financial_authorizations.sql'),baseline=read('backend-node/database/baseline/001_initial_schema.sql'),routes=read('backend-node/src/modules/deliveries/delivery.routes.ts'),seed=read('backend-node/database/seeds/001_system_seed.sql'),ged=read('backend-node/src/modules/documents/document-access.ts'),pdf=read('backend-node/src/modules/documents/commercial-document.ts');
const connection=(responses:any[][])=>({execute:async()=>[responses.shift()??[]]})as any;

test('DEL-FIN-01/02/03/04 politique normale soldée et impayé sans autorisation',async()=>{const paid=await lockActiveSaleInvoice(connection([[{id:1,status:'paid',total:100,amount_paid:100,balance_due:0,currency_code:'XAF'}]]),'1','delivery')as any;assert.equal(paid.financiallyCleared,true);await assert.rejects(()=>lockActiveSaleInvoice(connection([[{id:1,status:'partially_paid',total:100,amount_paid:60,balance_due:40,currency_code:'XAF'}],[]]),'1','delivery'),/intégralement réglée/);assert.match(routes,/i\.balance_due<=0\.001 OR EXISTS/);assert.match(routes,/await lockActiveSaleInvoice\(connection,saleId,'delivery'\)/)});
test('DEL-FIN-12/13/31/32/33 snapshot couvre une baisse mais pas une hausse',async()=>{const invoice={id:1,status:'partially_paid',total:100,amount_paid:70,balance_due:30,currency_code:'XAF'},authorization={id:8,status:'AUTHORIZED',balance_due_snapshot:40};const valid=await lockActiveSaleInvoice(connection([[invoice],[authorization]]),'1','delivery')as any;assert.equal(valid.coveredByAuthorization,true);await assert.rejects(()=>lockActiveSaleInvoice(connection([[{...invoice,balance_due:50}],[authorization]]),'1','delivery'),/insuffisante/)});
test('DEL-FIN-30 finalisation marque USED dans la transaction',async()=>{const calls:any[]=[];const c={execute:async(sql:string,params:any[])=>{calls.push([sql,params]);if(sql.startsWith('SELECT id,status'))return[[{id:1,status:'partially_paid',total:100,amount_paid:70,balance_due:30,currency_code:'XAF'}]];if(sql.startsWith('SELECT * FROM'))return[[{id:8,status:'AUTHORIZED',balance_due_snapshot:40}]];return[{}]}}as any;await useDeliveryFinancialAuthorization(c,'1','4','9');assert.ok(calls.some(([sql])=>sql.includes("SET status='USED'")))});
test('DEL-FIN-05..24 RBAC, idempotence, audit et neutralité financière',()=>{assert.match(migration,/delivery\.financial_override\.authorize/);assert.match(seed,/delivery\.financial_override\.authorize/);assert.match(migration,/UNIQUE KEY uq_delivery_fin_auth_request \(created_by,client_request_id\)/);assert.match(routes,/permissionScope\(request,'delivery\.financial_override\.authorize'\).*OWN/s);assert.match(routes,/delivery\.financial_authorization\.authorized/);assert.match(routes,/delivery\.financial_authorization\.revoked/);assert.doesNotMatch(migration,/treasury_movements|INSERT INTO payments|UPDATE invoices/i);assert.doesNotMatch(routes,/INSERT INTO payments|INSERT INTO treasury_movements|UPDATE invoices SET/)});
test('DEL-FIN-18/19/20/34/35/36/37 validations et historique',()=>{assert.match(routes,/Motif.*true/);assert.match(routes,/échéance du solde ne peut pas être passée/);assert.match(migration,/guarantee_type VARCHAR\(100\) NULL/);assert.match(migration,/ENUM\('AUTHORIZED','REVOKED','SUPERSEDED','USED'\)/);assert.match(routes,/status='SUPERSEDED'/);assert.match(routes,/déjà utilisée ne peut pas être révoquée/)});
test('DEL-FIN-21/43/44/45/46 GED et PV officiel réutilisés',()=>{assert.match(ged,/delivery_financial_authorization/);assert.match(pdf,/AUTORISATION FINANCIÈRE DE LIVRAISON/);assert.match(pdf,/used_delivery_id/);assert.match(pdf,/JSON_EXTRACT\(al\.new_values,'\$\.currentBalanceDue'\)/);assert.match(read('backend-node/src/modules/documents/business-document.service.ts'),/archiveDelivery/)});
test('DEL-FIN migration 060 et baseline convergent',()=>{for(const token of['CREATE TABLE delivery_financial_authorizations','balance_due_snapshot','uq_delivery_fin_auth_request','fk_delivery_fin_auth_delivery']){assert.match(migration,new RegExp(token));assert.match(baseline,new RegExp(token))}assert.match(migration,/delivery\.financial_override\.authorize/);assert.match(seed,/delivery\.financial_override\.authorize/);assert.match(baseline,/baseline_001_064/)});
