import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import test from 'node:test';
const read=(path:string)=>readFileSync(new URL(path,import.meta.url),'utf8');
const route=read('../src/modules/deliveries/delivery.routes.ts');
const financialGate=read('../src/modules/billing/sale-financial-gate.ts');
const migration=read('../database/legacy-migrations/023_dynamic_rbac.sql')+read('../database/legacy-migrations/029_delivery_cancel_permission.sql');

test('DEL-01/06/08/09/11/23/24/25/26/33 autorisations entièrement dynamiques',()=>{
  for(const code of ['delivery.view','delivery.schedule','delivery.prepare','delivery.checklist.manage','delivery.documents.view','delivery.signature.capture','delivery.complete','delivery.cancel']){assert.match(route,new RegExp("requirePermission\\('"+code.replaceAll('.','\\.')+"'\\)"));assert.match(migration,new RegExp(code.replaceAll('.','\\.')))}
  assert.doesNotMatch(route,/DELIVERY_MANAGER|DIRECTOR|SALES_MANAGER|SALES_AGENT|ACCOUNTANT|authorize\(|roles\.includes|roles\.some|hasRole/);
});
test('DEL-02/03/04/05 scopes AGENCY CONCESSION GLOBAL et OWN spécialiste réel',()=>{assert.match(route,/value==='AGENCY'.*agency_id=\?/s);assert.match(route,/value==='CONCESSION'.*concession_id/s);assert.match(route,/value==='GLOBAL'.*1=1/s);assert.match(route,/value==='OWN'&&alias==='d'.*delivery_specialist_id=\?/s);assert.match(route,/value==='OWN'.*1=0/s)});
test('DEL-07 planification et affectation sont bornées à la vente et à agence',()=>{assert.match(route,/scope\(request,'delivery\.schedule','s'\)/);assert.match(route,/lockedSale\.agency_id.*agencyId/s);assert.match(route,/u\.agency_id=\?/);assert.match(route,/p\.code='delivery\.prepare'/)});
test('DEL-CONC la planification valide la concession de la vente persistée sans élargir les autres scopes',()=>{const post=route.slice(route.indexOf('deliveryRouter.post(\n  "/deliveries"'),route.indexOf('deliveryRouter.patch(\n  "/deliveries/:id/status"'));assert.match(post,/permissionScope\(request,'delivery\.schedule'\)==='CONCESSION'\?scope\(request,'delivery\.schedule','s'\):null/);assert.match(post,/WHERE s\.id=\?\$\{concessionScope\?` AND \$\{concessionScope\.sql\}`:''\}/);assert.match(post,/concessionScope\?String\(sale\.agency_id\):agency\(request,'delivery\.schedule', sale\.agency_id\)/);assert.match(post,/lockedSale\.agency_id\)!==agencyId/)});
test('DEL-10/12/13/14/15/18/19/20/35 finalisation transactionnelle autoritaire',()=>{const sign=route.slice(route.indexOf('"/deliveries/:id/sign"'),route.indexOf('"/deliveries/:id/pdf"'));assert.match(sign,/SELECT d\.\*,s\.status sale_status.*FOR UPDATE/);assert.match(sign,/lockActiveSaleInvoice/);assert.match(financialGate,/SELECT id,status,amount_paid,balance_due FROM invoices.*FOR UPDATE/);assert.match(financialGate,/assertFinanciallySettled/);assert.match(sign,/is_required=TRUE AND is_completed=FALSE/);assert.match(sign,/is_required=TRUE AND received=FALSE/);assert.match(sign,/vehicle\.status!=='sold'/);assert.match(sign,/assertHandoverMileage/);assert.match(sign,/delivery\.status==='delivered'.*duplicate:true/s);assert.match(sign,/UPDATE deliveries SET status='delivered'/);assert.match(sign,/UPDATE vehicles SET status='delivered'/)});
test('DEL-16/17/21/31 Livraison ne mute aucun paiement et masque les détails financiers',()=>{assert.doesNotMatch(route,/INSERT INTO payments|UPDATE payments|DELETE FROM payments/);assert.match(route,/billing\.payment\.view/);assert.match(route,/financially_cleared/);assert.match(route,/balance_due:await canViewFinancials\(request,row\.agency_id\)/)});
test('DEL-22/32 exposition minimale sans pouvoir Client ou Vente implicite',()=>{assert.doesNotMatch(route,/requirePermission\('customers\.view'\)|requirePermission\('sales\.view'\)/);assert.doesNotMatch(route,/customer_360|payment_method|payment_number/)});
test('DEL-34 documents et PV appliquent permissions et scope',()=>{const pdf=route.slice(route.indexOf('"/deliveries/:id/pdf"'),route.indexOf('"/deliveries-planning/pdf"'));assert.match(pdf,/requirePermission\('delivery\.view'\)/);assert.match(pdf,/requirePermission\('delivery\.documents\.view'\)/);assert.match(pdf,/detail\(idOf\(request\.params\.id\), request,'delivery\.documents\.view'\)/)});
