import assert from'node:assert/strict';import{readFileSync}from'node:fs';import test from'node:test';
const read=(path:string)=>readFileSync(new URL(path,import.meta.url),'utf8'),migration=read('../database/migrations/062_configurable_delivery_checklists.sql'),baseline=read('../database/baseline/001_initial_schema.sql'),routes=read('../src/modules/deliveries/delivery-checklist.routes.ts'),delivery=read('../src/modules/deliveries/delivery.routes.ts'),service=read('../src/modules/deliveries/delivery-checklist.service.ts'),seed=read('../database/seeds/001_system_seed.sql'),pdf=read('../src/modules/documents/commercial-document.ts');

test('CHK-CONF-01..14 catégories, items, statut et ordre sont concession-scopés',()=>{for(const sql of[migration,baseline])for(const token of['delivery_checklist_categories','delivery_checklist_items','uq_delivery_checklist_category_order','uq_delivery_checklist_item_order','is_active','sort_order'])assert.match(sql,new RegExp(token));for(const route of['get','post','patch'])assert.match(routes,new RegExp(`deliveryChecklistRouter\\.${route}`));assert.match(routes,/categories\/reorder/);assert.match(routes,/items\/reorder/);assert.match(routes,/FOR UPDATE/);assert.match(routes,/1_000_000\+index/)});
test('CHK-CONF-15..20 RBAC configuration distinct et sans bypass',()=>{for(const code of['delivery.checklist.config.view','delivery.checklist.config.manage']){assert.match(migration,new RegExp(code.replaceAll('.','\\.')));assert.match(seed,new RegExp(code.replaceAll('.','\\.')));assert.match(routes,new RegExp(code.replaceAll('.','\\.')))}assert.match(routes,/permissionScope==='OWN'\|\|permissionScope==='AGENCY'/);assert.match(routes,/permissionScope==='GLOBAL'\|\|permissionScope==='CONCESSION'/);assert.doesNotMatch(routes,/SUPER_ADMIN|role\.code|roles\.includes/);assert.match(migration,/role\.code='SUPER_ADMIN' AND role\.is_system=TRUE/)});
test('CHK-RUN-01..09 snapshot relationnel, idempotent et immuable vis-à-vis du catalogue',()=>{for(const sql of[migration,baseline])for(const token of['delivery_checklist_category_instances','delivery_checklist_item_instances','code_snapshot','name_snapshot','description_snapshot','sort_order_snapshot','is_mandatory_snapshot'])assert.match(sql,new RegExp(token));assert.match(service,/SELECT id FROM delivery_checklist_category_instances WHERE delivery_id=\? LIMIT 1 FOR UPDATE/);assert.match(service,/if\(existing\[0\]\)return false/);assert.match(service,/FOR SHARE/);assert.match(delivery,/current\.status==='planned'&&status==='preparing'/);assert.match(delivery,/createDeliveryChecklistSnapshot/);const create=delivery.slice(delivery.indexOf('deliveryRouter.post(\n  "/deliveries",'),delivery.indexOf('deliveryRouter.patch(\n  "/deliveries/:id/status"'));assert.doesNotMatch(create,/delivery_checklist_category_instances|createDeliveryChecklistSnapshot/)});
test('CHK-RUN-10..20 mutations, progression et finalisation sont backend-authoritative',()=>{assert.match(delivery,/delivery_checklist_item_instances SET is_completed=\?,completed_by=\?,completed_at=IF\(\?,NOW\(\),NULL\)/);assert.match(delivery,/Boolean\(item\.is_completed\)===completed/);assert.match(service,/mandatory_completed/);assert.match(service,/status:completed===0\?'NOT_STARTED':completed===total\?'COMPLETED':'IN_PROGRESS'/);assert.match(service,/is_mandatory_snapshot.*is_completed/s);assert.match(delivery,/lockAndAssertDeliveryChecklistComplete/);assert.match(delivery,/\["delivered", "cancelled"\]\.includes/);assert.match(service,/éléments obligatoires de la checklist/)});
test('CHK-INT-01..10 financial gate, PV snapshot et Treasury indépendant',()=>{const sign=delivery.slice(delivery.indexOf('"/deliveries/:id/sign"'),delivery.indexOf('"/deliveries/:id/pdf"'));assert.ok(sign.indexOf('useDeliveryFinancialAuthorization')<sign.indexOf('lockAndAssertDeliveryChecklistComplete'));assert.match(pdf,/delivery_checklist_category_instances/);assert.match(pdf,/name_snapshot/);assert.doesNotMatch(service+routes,/treasury_movements|payments|invoices/);assert.match(delivery,/requireBusinessArchive/)});
test('migration 062 backfill uniquement depuis preuves historiques',()=>{assert.match(migration,/FROM delivery_checklists legacy/);assert.match(migration,/legacy\.is_completed,legacy\.completed_by,legacy\.completed_at/);assert.match(migration,/FROM delivery_documents document/);assert.match(migration,/document\.received,document\.received_by,document\.received_at/);assert.doesNotMatch(migration,/UPDATE delivery_checklists|UPDATE delivery_documents|DELETE FROM|DROP TABLE/)});
