import assert from'node:assert/strict';
import{readFileSync}from'node:fs';
import{test}from'node:test';
import{assertHandoverMileage,deliverySignatureHash}from'../src/modules/deliveries/delivery.domain.js';
const read=(path:string)=>readFileSync(new URL(path,import.meta.url),'utf8');

test('DEL-MILE-01..04 refuse inférieur et accepte égal ou supérieur avec message métier',()=>{assert.throws(()=>assertHandoverMileage(25,20),error=>Boolean(error&&typeof error==='object'&&'status'in error&&error.status===409&&'message'in error&&String(error.message).includes('25 km')));assert.equal(assertHandoverMileage(25,25),25);assert.equal(assertHandoverMileage(25,31),31)});
test('DEL-SIGN empreinte reproductible depuis un timestamp canonique',()=>{const input={deliveryId:'1',saleId:'2',vehicleId:'3',signer:'Client',mileage:31,signedAt:'2026-09-10T10:00:00.000Z',signature:'data:image/png;base64,abc'};assert.equal(deliverySignatureHash(input),deliverySignatureHash(input));assert.notEqual(deliverySignatureHash(input),deliverySignatureHash({...input,signedAt:'2026-09-10T10:00:01.000Z'}))});
test('DEL-CHK-01..06 catégories, phases, persistance et verrou post-livraison',()=>{const route=read('../src/modules/deliveries/delivery.routes.ts'),migration=read('../../backend/database/migrations/020_delivery_stabilization.sql');assert.match(route,/SELECT id,item_name,category,is_required,sort_order FROM delivery_checklist_templates/);assert.match(route,/INSERT INTO delivery_checklists\(delivery_id,template_id,item_name,category,is_required,sort_order\)/);assert.match(route,/completed_by=\?,completed_at=IF\(\?,NOW\(\),NULL\)/);assert.match(route,/requiredPhase=status==='quality_control'\?'preparation':status==='ready'\?'quality'/);assert.match(route,/PHASE_FOR_STATUS/);assert.match(route,/\["delivered", "cancelled"\]\.includes\(row\.status\)/);assert.match(migration,/ADD COLUMN IF NOT EXISTS category/)});
test('DEL-DOC-01..04 documents physiques uniques et immuables',()=>{const route=read('../src/modules/deliveries/delivery.routes.ts');assert.match(route,/item\.category==='documents'.*INSERT INTO delivery_documents/s);assert.doesNotMatch(route,/delivery_checklists.*category='documents'.*is_completed/s);assert.match(route,/received=Boolean\(request\.body\.received\)/);assert.match(route,/documents d’une livraison finalisée ne peuvent plus être modifiés/);assert.match(route,/documents obligatoires ne sont pas tous remis/)});
test('DEL-SIGN-01..06 et DEL-FINAL-01..06 transaction unique et autoritaire',()=>{const route=read('../src/modules/deliveries/delivery.routes.ts'),schema=read('../../backend/database/schema.sql');const sign=route.slice(route.indexOf('"/deliveries/:id/sign"'),route.indexOf('"/deliveries/:id/pdf"'));assert.match(route,/const OPERATE = \["SUPER_ADMIN", "DIRECTOR", "DELIVERY_MANAGER"\]/);assert.match(sign,/SELECT d\.\*,s\.status sale_status.*FOR UPDATE/);assert.match(sign,/SELECT id,balance_due,status FROM invoices.*FOR UPDATE/);assert.match(sign,/SELECT id,status,mileage FROM vehicles WHERE id=\? FOR UPDATE/);assert.match(sign,/delivery\.status==='delivered'.*duplicate:true/s);assert.match(sign,/INSERT INTO delivery_signatures/);assert.match(sign,/UPDATE deliveries SET status='delivered'/);assert.match(sign,/UPDATE sales SET status='delivered'/);assert.match(sign,/UPDATE vehicles SET status='delivered',mileage=\?/);assert.match(sign,/vehicle\.status.*'delivered'/);assert.match(schema,/UNIQUE KEY uk_delivery_signature_final \(delivery_id\)/)});
test('DEL-PDF contient opérateur, documents, kilométrage, empreinte et vraie image',()=>{const route=read('../src/modules/deliveries/delivery.routes.ts');const pdf=route.slice(route.indexOf('"/deliveries/:id/pdf"'),route.indexOf('"/deliveries-planning/pdf"'));assert.match(pdf,/Responsable livraison/);assert.match(pdf,/Documents remis/);assert.match(pdf,/Kilométrage/);assert.match(pdf,/Empreinte/);assert.match(pdf,/doc\.image\(Buffer\.from/)});
test('DEL-PLAN responsable obligatoire de même agence et commerciaux exclus',()=>{const route=read('../src/modules/deliveries/delivery.routes.ts');assert.match(route,/const CREATE = \["SUPER_ADMIN", "DIRECTOR", "DELIVERY_MANAGER"\]/);assert.match(route,/specialist = idOf/);assert.match(route,/r\.code='DELIVERY_MANAGER'/);assert.match(route,/u\.agency_id=\?/)});
