import assert from'node:assert/strict';
import test from'node:test';
import{readFileSync}from'node:fs';
import{resolveDocumentPath,verifiedPreviewMime}from'../src/modules/documents/document-storage.js';
import{requireBusinessArchive}from'../src/modules/documents/business-document.service.js';
import{HttpError}from'../src/shared/http-error.js';

const source=(value:string)=>readFileSync(new URL(`../${value}`,import.meta.url),'utf8');
const routes=source('src/modules/documents/document.routes.ts'),archive=source('src/modules/documents/business-document.service.ts');

test('DOC-01/02/03 preview inline et téléchargement attachment restent protégés',()=>{const preview=routes.slice(routes.indexOf("get('/documents/:id/preview'"),routes.indexOf("get('/documents/:id/download'")),download=routes.slice(routes.indexOf("get('/documents/:id/download'"));for(const section of[preview,download]){assert.match(section,/requirePermission\('ged.view'\)/);assert.ok(section.indexOf('getAccessibleDocument')<section.indexOf('readDocumentFile'));assert.match(section,/readDocumentFile\(doc\.file_url,doc\.file_hash\)/)}assert.match(preview,/contentHeaders\(res,'inline'/);assert.match(download,/contentHeaders\(res,'attachment'/);assert.match(routes,/X-Content-Type-Options/);assert.match(routes,/private, no-store/)});
test('DOC-04/05/06 les contrôles centralisés permission, scope et absence sont conservés',()=>{const access=source('src/modules/documents/document-access.ts');assert.match(access,/resolveDocumentEntity/);assert.match(access,/Ressource documentaire hors périmètre/);assert.match(access,/Document introuvable/)});
test('DOC-07/08 vérification de contenu PDF et images, refus des formats non supportés',()=>{const pdf=Buffer.from('%PDF-1.7 test'),png=Buffer.from([137,80,78,71,13,10,26,10,0]),bad=Buffer.from('not a pdf');assert.equal(verifiedPreviewMime(pdf,'application/pdf'),'application/pdf');assert.equal(verifiedPreviewMime(png,'image/png'),'image/png');assert.throws(()=>verifiedPreviewMime(bad,'application/pdf'),/Aperçu indisponible/)});
test('DOC-09 path traversal reste impossible',()=>{assert.throws(()=>resolveDocumentPath('ged:../../etc/passwd'));assert.throws(()=>resolveDocumentPath('/uploads/../../etc/passwd'))});
test('DOC-10..14 les pièces finalisées exigent archive officielle, hash et retry idempotent',()=>{for(const file of['src/modules/quotations/quotation.routes.ts','src/modules/core/core.routes.ts','src/modules/billing/billing.routes.ts','src/modules/deliveries/delivery.routes.ts'])assert.match(source(file),/requiredHistoricalBusinessPdf/);assert.match(archive,/source_key=\?/);assert.match(archive,/ER_DUP_ENTRY/);assert.match(archive,/requireBusinessArchive/);assert.match(archive,/throw new HttpError\(503/);assert.match(archive,/requiredHistoricalBusinessPdf/);assert.match(archive,/readDocumentFile\(String\(row\.file_url\),row\.file_hash\)/)});
test('DOC-16 seules les indisponibilités rejouables sont converties en 503',async()=>{const original=console.error;console.error=()=>undefined;try{await assert.rejects(()=>requireBusinessArchive('x',async()=>{throw new HttpError(409,'Archive corrompue')}),(error:unknown)=>error instanceof HttpError&&error.status===409);await assert.rejects(()=>requireBusinessArchive('x',async()=>{throw new Error('stockage indisponible')}),(error:unknown)=>error instanceof HttpError&&error.status===503&&/temporairement indisponible/.test(error.message))}finally{console.error=original}});
test('DOC-15 téléchargement historique demeure disponible',()=>assert.match(routes,/documents\/:id\/download/));
