import assert from'node:assert/strict';
import{randomUUID}from'node:crypto';
import{after,test}from'node:test';
import jwt from'jsonwebtoken';
import type{ResultSetHeader,RowDataPacket}from'mysql2/promise';
import supertest from'supertest';
import{createApp}from'../src/app.js';
import{pool,query}from'../src/config/database.js';
import{bootstrapDatabase}from'../src/scripts/database-bootstrap.js';

const enabled=process.env.FIN02_MYSQL_TEST==='1';if(enabled)after(()=>pool.end());
test('FIN-02 MySQL 8.4 workflows, quatre yeux et concurrence',{skip:!enabled,timeout:300000},async()=>{
 assert.equal((await bootstrapDatabase()).version,72);
 const add=async(sql:string,p:unknown[]=[])=>String((await pool.execute<ResultSetHeader>(sql,p))[0].insertId),suffix=randomUUID().slice(0,8),concession=await add('INSERT INTO concessions(name,code,currency_code) VALUES(?,?,?)',[`FIN02 ${suffix}`,`F2${suffix}`,'XAF']),agency=await add('INSERT INTO agencies(concession_id,name,code) VALUES(?,?,?)',[concession,'Agence FIN02',`F2A${suffix}`]);
 const permissionCodes=['hr.budget.manage','hr.budget.submit','hr.budget.approve','hr.budget.view','hr.expense.create','hr.expense.submit','hr.expense.approve','hr.expense.view'],permissions=await query<RowDataPacket[]>(`SELECT id,code FROM permissions WHERE code IN(${permissionCodes.map(()=>'?').join(',')})`,permissionCodes),role=async(name:string,codes:string[])=>{const roleId=await add('INSERT INTO roles(name,code) VALUES(?,?)',[name,`${name}_${suffix}`]);for(const code of codes){const permission=permissions.find(x=>x.code===code);assert.ok(permission,code);await pool.execute('INSERT INTO role_permissions(role_id,permission_id,scope) VALUES(?,?,\'AGENCY\')',[roleId,permission.id])}return roleId},requesterRole=await role('FIN02_DEMANDEUR',['hr.budget.manage','hr.budget.submit','hr.budget.view','hr.expense.create','hr.expense.submit','hr.expense.view']),approverRole=await role('FIN02_APPROBATEUR',['hr.budget.approve','hr.budget.view','hr.expense.approve','hr.expense.view']);
 const sessions=new Map<string,string>(),user=async(email:string,roleId:string)=>{const userId=await add('INSERT INTO users(agency_id,first_name,last_name,email,password_hash) VALUES(?,?,?,?,?)',[agency,'Test','FIN02',email,'unused']);await pool.execute('INSERT INTO user_roles(user_id,role_id) VALUES(?,?)',[userId,roleId]);const sid=randomUUID();sessions.set(userId,sid);await pool.execute('INSERT INTO refresh_tokens(id,user_id,token_hash,expires_at) VALUES(?,?,?,DATE_ADD(NOW(),INTERVAL 1 HOUR))',[sid,userId,randomUUID().replaceAll('-','').padEnd(64,'0')]);return userId},requester=await user(`fin02-r-${suffix}@test.local`,requesterRole),approver=await user(`fin02-a-${suffix}@test.local`,approverRole),token=(userId:string)=>jwt.sign({sub:userId,sid:sessions.get(userId),email:'fin02@test.local',roles:[],agencyId:agency},process.env.JWT_ACCESS_SECRET!,{expiresIn:'10m'}),api=supertest(createApp()),auth=(request:supertest.Test,userId:string)=>request.set('Authorization',`Bearer ${token(userId)}`);
 let response=await auth(api.post('/api/hr/budgets'),requester).send({scopeType:'agency',agencyId:agency,label:'Budget FIN02',initialAmount:1_000_000,startDate:'2026-01-01',endDate:'2026-12-31'});assert.equal(response.status,201,response.text);const budgetId=String(response.body.id);assert.equal((await query<RowDataPacket[]>('SELECT status FROM budgets WHERE id=?',[budgetId]))[0]?.status,'draft');
 assert.equal((await auth(api.post(`/api/hr/budgets/${budgetId}/submit`),requester).send({})).status,200);assert.equal((await auth(api.post(`/api/hr/budgets/${budgetId}/approve`),requester).send({})).status,403);assert.equal((await auth(api.post(`/api/hr/budgets/${budgetId}/approve`),approver).send({})).status,200);assert.equal(Number((await query<RowDataPacket[]>('SELECT COUNT(*) total FROM treasury_movements'))[0]?.total),0);
 const expense=async(label:string)=>{const created=await auth(api.post(`/api/hr/budgets/${budgetId}/expenses`),requester).send({label,amount:800_000,expenseDate:'2026-10-09'});assert.equal(created.status,201,created.text);const expenseId=String(created.body.id);assert.equal((await auth(api.post(`/api/hr/expenses/${expenseId}/submit`),requester).send({})).status,200);return expenseId},expenseA=await expense('Demande A'),expenseB=await expense('Demande B');
 const selfApproval=await auth(api.post(`/api/hr/expenses/${expenseA}/approve`),requester).send({});assert.equal(selfApproval.status,403);
 const approvals=await Promise.all([auth(api.post(`/api/hr/expenses/${expenseA}/approve`),approver).send({}),auth(api.post(`/api/hr/expenses/${expenseB}/approve`),approver).send({})]);assert.deepEqual(approvals.map(x=>x.status).sort(),[200,409]);const engaged=Number((await query<RowDataPacket[]>("SELECT COALESCE(SUM(amount),0) total FROM budget_expenses WHERE budget_id=? AND approval_status='approved'",[budgetId]))[0]?.total);assert.equal(engaged,800_000);assert.equal(Number((await query<RowDataPacket[]>('SELECT COUNT(*) total FROM treasury_movements'))[0]?.total),0);
 const history=await query<RowDataPacket[]>('SELECT action FROM budget_approval_history ORDER BY id');assert.ok(history.some(x=>x.action==='approved'));assert.ok(history.some(x=>x.action==='submitted'));
});
