import assert from'node:assert/strict';
import{randomUUID}from'node:crypto';
import{after,test}from'node:test';
import jwt from'jsonwebtoken';
import type{ResultSetHeader,RowDataPacket}from'mysql2/promise';
import supertest from'supertest';
import{createApp}from'../src/app.js';
import{pool,query}from'../src/config/database.js';
import{bootstrapDatabase}from'../src/scripts/database-bootstrap.js';

const enabled=process.env.FIN01_MYSQL_TEST==='1';if(enabled)after(()=>pool.end());
test('FIN-01 MySQL 8.4 export réel, remboursements et scopes',{skip:!enabled,timeout:300000},async()=>{
 assert.equal((await bootstrapDatabase()).version,71);
 const add=async(sql:string,p:unknown[]=[])=>String((await pool.execute<ResultSetHeader>(sql,p))[0].insertId),suffix=randomUUID().slice(0,8),concession=await add('INSERT INTO concessions(name,code,currency_code) VALUES(?,?,?)',[`FIN01 ${suffix}`,`F1${suffix}`,'XAF']),otherConcession=await add('INSERT INTO concessions(name,code,currency_code) VALUES(?,?,?)',[`FIN01 autre ${suffix}`,`F2${suffix}`,'XAF']),agencyA=await add('INSERT INTO agencies(concession_id,name,code) VALUES(?,?,?)',[concession,'Agence A',`F1A${suffix}`]),agencyB=await add('INSERT INTO agencies(concession_id,name,code) VALUES(?,?,?)',[concession,'Agence B',`F1B${suffix}`]),agencyC=await add('INSERT INTO agencies(concession_id,name,code) VALUES(?,?,?)',[otherConcession,'Agence C',`F1C${suffix}`]);
 const permission=(await query<RowDataPacket[]>("SELECT id FROM permissions WHERE code='billing.export'"))[0]!,role=async(code:string,scope:'AGENCY'|'CONCESSION')=>{const id=await add('INSERT INTO roles(name,code) VALUES(?,?)',[code,code]);await pool.execute('INSERT INTO role_permissions(role_id,permission_id,scope) VALUES(?,?,?)',[id,permission.id,scope]);return id},agencyRole=await role(`FIN01_AG_${suffix}`,'AGENCY'),concessionRole=await role(`FIN01_CO_${suffix}`,'CONCESSION');
 const sessions=new Map<string,string>(),user=async(agency:string,email:string,roleId?:string)=>{const id=await add('INSERT INTO users(agency_id,first_name,last_name,email,password_hash) VALUES(?,?,?,?,?)',[agency,'Test','FIN01',email,'not-used']);if(roleId)await pool.execute('INSERT INTO user_roles(user_id,role_id) VALUES(?,?)',[id,roleId]);const sid=randomUUID();sessions.set(id,sid);await pool.execute('INSERT INTO refresh_tokens(id,user_id,token_hash,expires_at) VALUES(?,?,?,DATE_ADD(NOW(),INTERVAL 1 HOUR))',[sid,id,randomUUID().replaceAll('-','').padEnd(64,'0')]);return id},agencyUser=await user(agencyA,`fin01-a-${suffix}@test.local`,agencyRole),concessionUser=await user(agencyA,`fin01-c-${suffix}@test.local`,concessionRole),deniedUser=await user(agencyA,`fin01-x-${suffix}@test.local`),token=(id:string,agencyId:string)=>jwt.sign({sub:id,sid:sessions.get(id),email:'fin01@test.local',roles:[],agencyId},process.env.JWT_ACCESS_SECRET!,{expiresIn:'10m'}),api=supertest(createApp()),get=(id:string,agencyId:string,target:string)=>api.get('/api/invoices/export/accounting').query({agencyId:target,from:'2026-10-01',to:'2026-10-31'}).set('Authorization',`Bearer ${token(id,agencyId)}`);
 const customer=async(agency:string,code:string,name:string)=>add('INSERT INTO customers(customer_code,agency_id,company_name,first_name,last_name) VALUES(?,?,?,?,?)',[code,agency,name,'Client','FIN01']),customerA=await customer(agencyA,`CA${suffix}`,'=1+1'),customerB=await customer(agencyB,`CB${suffix}`,'Client B'),method=String((await query<RowDataPacket[]>('SELECT id FROM payment_methods ORDER BY id LIMIT 1'))[0]!.id),invoice=async(agency:string,customerId:string,number:string,total:number)=>add("INSERT INTO invoices(invoice_number,customer_id,agency_id,invoice_type,status,issue_date,due_date,total,amount_paid,balance_due) VALUES(?,?,?,'manual','issued','2026-10-01','2026-10-31',?,0,?)",[number,customerId,agency,total,total]),invoiceA=await invoice(agencyA,customerA,`FAC-A-${suffix}`,25_000_000),invoiceB=await invoice(agencyB,customerB,`FAC-B-${suffix}`,8_000_000);
 const payment=async(invoiceId:string,customerId:string,number:string,amount:number,status='confirmed')=>add('INSERT INTO payments(payment_number,invoice_id,customer_id,payment_method_id,amount,payment_date,status,refunded_at) VALUES(?,?,?,?,?,\'2026-10-05\',?,IF(?=\'refunded\',\'2026-10-10\',NULL))',[number,invoiceId,customerId,method,amount,status,status]),confirmed=await payment(invoiceA,customerA,`REG-OK-${suffix}`,10_000_000),legacy=await payment(invoiceA,customerA,`REG-LEG-${suffix}`,2_000_000,'refunded'),modern=await payment(invoiceA,customerA,`REG-MOD-${suffix}`,3_000_000),coexist=await payment(invoiceA,customerA,`REG-BOTH-${suffix}`,4_000_000,'refunded');await payment(invoiceA,customerA,`REG-FAIL-${suffix}`,999_999,'rejected');await payment(invoiceB,customerB,`REG-B-${suffix}`,1_000_000);
 const credit=async(number:string,amount:number)=>add("INSERT INTO credit_notes(credit_note_number,invoice_id,customer_id,status,reason,amount,issue_date) VALUES(?,?,?,'applied','FIN01',?,'2026-10-08')",[number,invoiceA,customerA,amount]),creditOne=await credit(`AVO-1-${suffix}`,3_000_000),creditTwo=await credit(`AVO-2-${suffix}`,4_000_000),creditOnly=await credit(`AVO-SEUL-${suffix}`,500_000),refund=async(paymentId:string,creditId:string,amount:number,key:string)=>add("INSERT INTO payment_refunds(payment_id,invoice_id,credit_note_id,amount,reason,idempotency_key,refunded_at) VALUES(?,?,?,?,'FIN01',?,'2026-10-11')",[paymentId,invoiceA,creditId,amount,key]);await refund(modern,creditOne,1_000_000,`m1-${suffix}`);await refund(modern,creditOne,1_000_000,`m2-${suffix}`);await refund(coexist,creditTwo,4_000_000,`both-${suffix}`);void confirmed;void legacy;void creditOnly;
 const own=await get(agencyUser,agencyA,agencyA);assert.equal(own.status,200,own.text);assert.equal(own.headers['content-disposition'],'attachment; filename="operations-facturation.csv"');assert.match(own.text,/"'=1\+1"/);assert.match(own.text,new RegExp(`FAC-A-${suffix}`));assert.doesNotMatch(own.text,new RegExp(`FAC-B-${suffix}`));assert.doesNotMatch(own.text,new RegExp(`REG-FAIL-${suffix}`));assert.equal((own.text.match(new RegExp(`REM-REG-LEG-${suffix}`,'g'))??[]).length,1);assert.equal((own.text.match(/"Remboursement"/g)??[]).length,3);assert.equal((own.text.match(/"1000000";"0";"0"/g)??[]).length>=2,true);assert.match(own.text,new RegExp(`AVO-SEUL-${suffix}`));
 const concessionExport=await get(concessionUser,agencyA,agencyB);assert.equal(concessionExport.status,200);assert.match(concessionExport.text,new RegExp(`FAC-B-${suffix}`));assert.doesNotMatch(concessionExport.text,new RegExp(`FAC-A-${suffix}`));assert.equal((await get(concessionUser,agencyA,agencyC)).status,403);assert.equal((await get(deniedUser,agencyA,agencyA)).status,403);assert.equal((await get(agencyUser,agencyA,agencyB)).status,403);
});
