import assert from'node:assert/strict';
import{readFileSync}from'node:fs';
import test from'node:test';

const read=(path:string)=>readFileSync(new URL(path,import.meta.url),'utf8');
const routes=read('../src/modules/hr/hr.routes.ts'),employee=read('../src/modules/hr/hr-employee.service.ts'),users=read('../src/modules/users/user.service.ts'),baseline=read('../database/baseline/001_initial_schema.sql'),seed=read('../database/seeds/001_system_seed.sql'),stockMigration=read('../database/migrations/042_internal_stock_governance.sql'),budgetCategoryMigration=read('../database/migrations/043_budget_categories.sql'),budgetFundsMigration=read('../database/migrations/044_budget_fund_movements.sql');

test('HR-SCHEMA-01 le modèle RH conserve historique et précision exacte',()=>{for(const table of ['employee_profiles','salary_history','internal_stock_items','internal_stock_movements','budgets','budget_expenses'])assert.match(baseline,new RegExp(`CREATE TABLE ${table}`));assert.match(baseline,/amount DECIMAL\(18,2\)/);assert.match(baseline,/current_quantity DECIMAL\(14,3\)/);assert.match(baseline,/employment_status ENUM\('active','inactive','departed'\)/);assert.doesNotMatch(baseline,/FLOAT/)});
test('HR-RBAC-01 le catalogue est granulaire et SUPER_ADMIN reste générique',()=>{for(const code of ['hr.view','hr.employees.view','hr.employees.manage','hr.salary.view','hr.salary.manage','hr.stock.view','hr.stock.manage','hr.stock.entry','hr.stock.exit','hr.budget.view','hr.budget.manage','hr.expense.view','hr.expense.create','hr.expense.manage','hr.reporting.view'])assert.match(seed,new RegExp(`'${code.replaceAll('.','\\.')}'`));assert.match(seed,/r.code='SUPER_ADMIN' AND r.is_system=TRUE/);assert.doesNotMatch(seed,/HR_MANAGER|RESPONSABLE_RH|DRH/)});
test('HR-EMP-01 à 07 users et employés restent distincts et les départs sont conservés',()=>{assert.match(baseline,/user_id BIGINT UNSIGNED NOT NULL UNIQUE/);assert.match(employee,/if\(!body\.isEmployee\).*employment_status='departed'/);assert.match(users,/LEFT JOIN employee_profiles/);assert.match(routes,/employee_profiles ep JOIN users u/);for(const scope of ['OWN','AGENCY','CONCESSION','GLOBAL'])assert.match(routes,new RegExp(`scope==='${scope}'`))});
test('HR-SAL-01 à 07 les salaires sont historisés et isolés par permissions',()=>{assert.match(baseline,/UNIQUE KEY uk_salary_employee_effective/);assert.match(routes,/requirePermission\('hr.salary.view'\)/);assert.match(routes,/requirePermission\('hr.salary.manage'\)/);assert.match(routes,/salaryVisibility=salaryAllowed\?agencyPredicate\(r,salaryScope\?\?null,'a','u'\):null/);assert.match(routes,/CASE WHEN \$\{salaryVisibility\.sql\} THEN/);assert.match(routes,/ORDER BY sh.effective_date DESC/);assert.match(routes,/SUM\(sh.amount\)/)});
test('HR-STOCK-01 à 08 les mouvements verrouillent le stock et refusent un solde négatif',()=>{assert.match(routes,/stockItem\(r,permission,itemId,c,true\)/);assert.match(routes,/i\.is_active=TRUE/);assert.match(routes,/FOR UPDATE/);assert.match(routes,/if\(after<0\)throw new HttpError\(409,'Stock insuffisant/);assert.match(routes,/INSERT INTO internal_stock_movements/);assert.match(routes,/current_quantity<=i.minimum_quantity/)});
test('RH-FIX-03 gouverne catégories, agences et historique inactif',()=>{assert.match(stockMigration,/CREATE TABLE internal_stock_categories/);assert.match(stockMigration,/UNIQUE KEY uk_internal_stock_category_concession_code/);assert.match(stockMigration,/UNIQUE KEY uk_internal_stock_category_concession_name/);assert.match(stockMigration,/ADD COLUMN category_id/);assert.match(stockMigration,/SHA2\(UPPER\(TRIM\(i\.category\)\)/);assert.match(routes,/\/hr\/stock-agencies/);assert.match(routes,/\/hr\/stock-concessions/);assert.match(routes,/\/hr\/internal-stock-categories/);assert.match(routes,/stock\.category\.created/);assert.match(routes,/stock\.item\.status\.updated/);assert.match(routes,/includeInactive/)});
test('RH-FIX-05 modifie uniquement le seuil minimum sous verrou et audit',()=>{assert.match(routes,/\/hr\/internal-stock\/:id\/minimum-threshold/);assert.match(routes,/stockItem\(r,'hr\.stock\.manage',itemId,c,true\)/);assert.match(routes,/UPDATE internal_stock_items SET minimum_quantity=\?,updated_by=\?/);assert.match(routes,/stock\.item\.minimum\.updated/);assert.doesNotMatch(routes,/minimum-threshold[\s\S]{0,1000}SET current_quantity=/)});
test('HR-BUDGET-01 à 08 les dépenses verrouillent le budget avant le calcul du disponible',()=>{assert.match(routes,/budget\(r,'hr.expense.create',budgetId,c\)/);assert.match(routes,/SELECT COALESCE\(SUM\(amount\),0\) total FROM budget_expenses/);assert.match(routes,/if\(Number\(amount\)>remaining\)/);assert.match(routes,/INSERT INTO budget_expenses/);assert.match(baseline,/chk_budget_scope/)});
test('RH-BUDGET-AGENCY-01 expose des cibles dédiées et garde le backend autoritaire',()=>{assert.match(routes,/\/hr\/budget-targets.*requirePermission\('hr\.budget\.manage'\)/);assert.match(routes,/scope==='OWN'.*Le scope OWN ne s’applique pas aux budgets/);assert.match(routes,/Aucune agence n’est associée à votre compte/);assert.match(routes,/Votre agence de rattachement est inactive ou introuvable/);assert.match(routes,/scopeType==='agency'.*assertAgencyTarget\(r,'hr\.budget\.manage',agencyId\)/);assert.match(routes,/scope==='OWN'\|\|scope==='AGENCY'.*budget de concession/);assert.doesNotMatch(routes,/budget-targets.*settings\.view/)});
test('RH-BUDGET-CATEGORIES-02 prépare le référentiel, les FK et un backfill déterministe',()=>{assert.match(budgetCategoryMigration,/CREATE TABLE budget_categories/);assert.match(budgetCategoryMigration,/UNIQUE KEY uk_budget_category_concession_code/);assert.match(budgetCategoryMigration,/UNIQUE KEY uk_budget_category_concession_name/);assert.match(budgetCategoryMigration,/ALTER TABLE budgets[\s\S]*ADD COLUMN category_id/);assert.match(budgetCategoryMigration,/ALTER TABLE budget_expenses[\s\S]*ADD COLUMN category_id/);assert.match(budgetCategoryMigration,/COLLATE utf8mb4_bin/);assert.match(budgetCategoryMigration,/LEGACY_/);assert.match(budgetCategoryMigration,/hr\.budget\.category\.view/);assert.match(budgetCategoryMigration,/hr\.budget\.category\.manage/);assert.doesNotMatch(budgetCategoryMigration,/DROP COLUMN category/)});
test('RH-BUDGET-CATEGORIES-02 rend category_id autoritaire et conserve les snapshots',()=>{assert.match(routes,/\/hr\/budget-categories/);assert.match(routes,/lockedBudgetCategory/);assert.match(routes,/INSERT INTO budgets\([^)]*category,category_id/);assert.match(routes,/INSERT INTO budget_expenses\([^)]*category,category_id/);assert.match(routes,/Le code d’une catégorie déjà utilisée est immuable/);assert.match(routes,/budget\.category\.deactivated/);assert.match(routes,/GROUP BY b\.category_id/);assert.match(routes,/GROUP BY e\.category_id/);assert.doesNotMatch(routes,/hrRouter\.delete\('\/hr\/budget-categories/)});
test('RH-FIX-04 conserve le montant initial et journalise chaque rallonge',()=>{assert.match(budgetFundsMigration,/CREATE TABLE budget_fund_movements/);assert.match(budgetFundsMigration,/amount DECIMAL\(18,2\) NOT NULL/);assert.match(budgetFundsMigration,/CHECK \(amount > 0\)/);assert.match(budgetFundsMigration,/ON DELETE RESTRICT/);assert.doesNotMatch(budgetFundsMigration,/UPDATE budgets/);assert.match(routes,/\/hr\/budgets\/:id\/funds/);assert.match(routes,/requirePermission\('hr\.budget\.manage'\)/);assert.match(routes,/budget\(r,'hr\.budget\.manage',budgetId,c\)/);assert.match(routes,/budget\.fund\.added/);assert.match(routes,/initial_amount\+COALESCE/);assert.doesNotMatch(routes,/UPDATE budgets SET initial_amount/)});
test('HR-IDOR-01 les ressources existantes sont relues dans le scope persistant',()=>{for(const helper of ['employee','stockItem','budget'])assert.match(routes,new RegExp(`async function ${helper}`));assert.match(routes,/JOIN agencies a ON a.id=u.agency_id/);assert.match(routes,/JOIN agencies a ON a.id=i.agency_id/);assert.match(routes,/LEFT JOIN agencies ba ON ba.id=b.agency_id/)});
test('HR-GED-01 aucun second stockage documentaire n’est créé',()=>{assert.doesNotMatch(baseline,/expense_documents|hr_documents|salary_documents/);assert.doesNotMatch(routes,/multer|writeFile|express\.static/)});
