import assert from'node:assert/strict';
import{randomUUID}from'node:crypto';
import{after,test}from'node:test';
import jwt from'jsonwebtoken';
import supertest from'supertest';
import type{RowDataPacket}from'mysql2/promise';
import{createApp}from'../src/app.js';
import{execute,pool,query}from'../src/config/database.js';

const enabled=process.env.LCA_HR_BUDGET_FUNDS_DB_TEST==='1';
if(enabled)after(async()=>pool.end());

test('RH-FIX-04 MySQL 8.4 : rallonges immuables, scopes, audit et concurrence',{skip:!enabled},async()=>{
 const suffix=randomUUID().slice(0,8),api=supertest(createApp()),insert=async(sql:string,params:unknown[]=[])=>String((await execute(sql,params)).insertId);
 const concessionA=await insert('INSERT INTO concessions(name,code) VALUES(?,?)',[`Funds A ${suffix}`,`FA-${suffix}`]),concessionB=await insert('INSERT INTO concessions(name,code) VALUES(?,?)',[`Funds B ${suffix}`,`FB-${suffix}`]),agencyA1=await insert('INSERT INTO agencies(concession_id,name,code) VALUES(?,?,?)',[concessionA,'Funds A1',`FA1-${suffix}`]),agencyA2=await insert('INSERT INTO agencies(concession_id,name,code) VALUES(?,?,?)',[concessionA,'Funds A2',`FA2-${suffix}`]),agencyB=await insert('INSERT INTO agencies(concession_id,name,code) VALUES(?,?,?)',[concessionB,'Funds B1',`FB1-${suffix}`]);
 const actor=await insert('INSERT INTO users(agency_id,first_name,last_name,email,password_hash) VALUES(?,?,?,?,?)',[agencyA1,'Budget','Funds',`funds-${suffix}@test.local`,'test']),role=await insert('INSERT INTO roles(name,code,is_system,is_active) VALUES(?,?,FALSE,TRUE)',[`Funds ${suffix}`,`FUNDS_${suffix}`]);await execute('INSERT INTO user_roles(user_id,role_id) VALUES(?,?)',[actor,role]);
 const codes=['hr.budget.view','hr.budget.manage','hr.expense.view','hr.expense.create'],permissions=await query<RowDataPacket[]>(`SELECT id,code FROM permissions WHERE code IN(${codes.map(()=>'?').join(',')})`,codes),permissionId=(code:string)=>String(permissions.find(row=>row.code===code)!.id),configure=async(scope:'OWN'|'AGENCY'|'CONCESSION'|'GLOBAL',includeManage=true)=>{await execute('DELETE FROM role_permissions WHERE role_id=?',[role]);for(const code of codes.filter(x=>includeManage||x!=='hr.budget.manage'))await execute('INSERT INTO role_permissions(role_id,permission_id,scope) VALUES(?,?,?)',[role,permissionId(code),scope])};
 const token=jwt.sign({sub:actor,email:`funds-${suffix}@test.local`,roles:[],agencyId:agencyA1},process.env.JWT_ACCESS_SECRET!,{expiresIn:'10m'}),auth=(request:supertest.Test)=>request.set('Authorization',`Bearer ${token}`),createBudget=async(agencyId:string,amount=1_000_000)=>String((await execute("INSERT INTO budgets(scope_type,agency_id,label,initial_amount,start_date,end_date,status,created_by,updated_by) VALUES('agency',?,?,?,?,?,'active',?,?)",[agencyId,`Budget ${randomUUID()}`,amount,'2026-01-01','2026-12-31',actor,actor])).insertId),fund=(budgetId:string,amount:unknown,reason='Renforcement',reference='REF-1')=>auth(api.post(`/api/hr/budgets/${budgetId}/funds`)).send({amount,reason,reference}),expense=(budgetId:string,amount:number)=>auth(api.post(`/api/hr/budgets/${budgetId}/expenses`)).send({label:'Dépense test',amount,expenseDate:'2026-06-01'});
 await configure('AGENCY');const budgetA1=await createBudget(agencyA1),budgetA2=await createBudget(agencyA2),budgetB=await createBudget(agencyB);let response=await fund(budgetA1,500_000);assert.equal(response.status,201,JSON.stringify(response.body));assert.equal((await expense(budgetA1,800_000)).status,201);response=await auth(api.get('/api/hr/budgets'));const row=response.body.find((x:any)=>x.id===budgetA1);assert.deepEqual([row.initial_amount,row.additional_funds,row.total_allocated,row.spent,row.remaining],[1_000_000,500_000,1_500_000,800_000,700_000]);assert.equal((await fund(budgetA1,100_000,'Deuxième rallonge','REF-2')).status,201);
 response=await auth(api.get(`/api/hr/budgets/${budgetA1}/funds`));assert.equal(response.status,200);assert.equal(response.body.length,2);assert.equal(response.body[0].reason,'Deuxième rallonge');assert.equal(response.body[1].author_name,'Budget Funds');assert.equal((await fund(budgetA1,0)).status,400);assert.equal((await fund(budgetA1,-1)).status,400);assert.equal((await fund('999999999',10)).status,404);assert.equal((await fund(budgetA2,10)).status,404);assert.equal((await fund(budgetB,10)).status,404);
 await configure('AGENCY',false);assert.equal((await fund(budgetA1,10)).status,403);await configure('OWN');assert.equal((await fund(budgetA1,10)).status,403);await configure('CONCESSION');assert.equal((await fund(budgetA2,10)).status,201);assert.equal((await fund(budgetB,10)).status,404);await configure('GLOBAL');assert.equal((await fund(budgetB,10)).status,201);
 const concurrentBudget=await createBudget(agencyA1,1_000_000),funds=await Promise.all([fund(concurrentBudget,200_000,'Concurrence A'),fund(concurrentBudget,300_000,'Concurrence B')]);assert.deepEqual(funds.map(x=>x.status).sort(),[201,201]);response=await auth(api.get('/api/hr/budgets'));const concurrentRow=response.body.find((x:any)=>x.id===concurrentBudget);assert.equal(concurrentRow.total_allocated,1_500_000);
 const raceBudget=await createBudget(agencyA1,100),race=await Promise.all([fund(raceBudget,100,'Rallonge concurrente'),expense(raceBudget,150)]);assert.ok(race.some(x=>x.status===201));assert.ok(race.every(x=>[201,409].includes(x.status)));response=await auth(api.get('/api/hr/budgets'));const raceRow=response.body.find((x:any)=>x.id===raceBudget);assert.equal(raceRow.remaining,raceRow.total_allocated-raceRow.spent);assert.ok(raceRow.remaining>=0);
 const[auditRow]=await query<RowDataPacket[]>("SELECT user_id,action,JSON_UNQUOTE(JSON_EXTRACT(new_values,'$.budgetId')) budget_id FROM audit_logs WHERE entity_type='budget_fund_movement' AND action='budget.fund.added' AND user_id=? ORDER BY id LIMIT 1",[actor]);assert.equal(String(auditRow.user_id),actor);assert.equal(String(auditRow.budget_id),budgetA1);
 const fakeUser=await insert('INSERT INTO users(agency_id,first_name,last_name,email,password_hash) VALUES(?,?,?,?,?)',[agencyA1,'Faux','Super',`fake-funds-${suffix}@test.local`,'test']),fakeRole=await insert('INSERT INTO roles(name,code,is_system,is_active) VALUES(?,?,FALSE,TRUE)',[`Fake ${suffix}`,`SUPER_ADMIN_${suffix}`]);await execute('INSERT INTO user_roles(user_id,role_id) VALUES(?,?)',[fakeUser,fakeRole]);for(const code of['hr.budget.view','hr.budget.manage'])await execute('INSERT INTO role_permissions(role_id,permission_id,scope) VALUES(?,?,?)',[fakeRole,permissionId(code),'AGENCY']);const fakeToken=jwt.sign({sub:fakeUser,email:`fake-funds-${suffix}@test.local`,roles:['SUPER_ADMIN'],agencyId:agencyA1},process.env.JWT_ACCESS_SECRET!,{expiresIn:'10m'});assert.equal((await api.post(`/api/hr/budgets/${budgetB}/funds`).set('Authorization',`Bearer ${fakeToken}`).send({amount:10})).status,404);
 const trueUser=await insert('INSERT INTO users(agency_id,first_name,last_name,email,password_hash) VALUES(?,?,?,?,?)',[agencyA1,'Vrai','Super',`true-funds-${suffix}@test.local`,'test']),[systemRole]=await query<RowDataPacket[]>("SELECT id FROM roles WHERE code='SUPER_ADMIN' AND is_system=TRUE AND is_active=TRUE");await execute('INSERT INTO user_roles(user_id,role_id) VALUES(?,?)',[trueUser,systemRole.id]);const trueToken=jwt.sign({sub:trueUser,email:`true-funds-${suffix}@test.local`,roles:[],agencyId:agencyA1},process.env.JWT_ACCESS_SECRET!,{expiresIn:'10m'});assert.equal((await api.post(`/api/hr/budgets/${budgetB}/funds`).set('Authorization',`Bearer ${trueToken}`).send({amount:10})).status,201);
 const[count]=await query<RowDataPacket[]>('SELECT COUNT(*) total FROM budget_fund_movements WHERE budget_id=?',[budgetA1]);assert.equal(Number(count.total),2);
});
