import assert from'node:assert/strict';
import{readFileSync}from'node:fs';
import test from'node:test';
const read=(path:string)=>readFileSync(new URL(path,import.meta.url),'utf8');
const migration=read('../database/migrations/065_employee_contract_history.sql'),baseline=read('../database/baseline/001_initial_schema.sql'),routes=read('../src/modules/hr/hr-contract.routes.ts'),ged=read('../src/modules/documents/document-access.ts'),seed=read('../database/seeds/001_system_seed.sql');

test('HR11A-01..05 types configurables, désactivables et snapshots historiques',()=>{for(const sql of[migration,baseline]){assert.match(sql,/CREATE TABLE employee_contract_types/);assert.match(sql,/is_active BOOLEAN NOT NULL DEFAULT TRUE/);assert.match(sql,/type_code_snapshot/);assert.match(sql,/type_name_snapshot/);assert.match(sql,/fk_contract_type.+ON DELETE RESTRICT/)}assert.match(routes,/Type de contrat actif introuvable/);assert.match(routes,/Le code d’un type utilisé est immuable/)});
test('HR11A-06..23 contrats liés exclusivement à employee et historique immuable',()=>{for(const sql of[migration,baseline]){assert.match(sql,/employee_profile_id BIGINT UNSIGNED NOT NULL/);assert.match(sql,/previous_contract_id BIGINT UNSIGNED NULL/);assert.match(sql,/status ENUM\('DRAFT','ACTIVE','ENDED','CANCELLED'\)/);assert.match(sql,/uk_contract_previous/);assert.match(sql,/chk_contract_dates/)}assert.doesNotMatch(migration,/user_id|salary|amount/);assert.match(routes,/Seul un brouillon peut être modifié/);assert.match(routes,/contract\.renewed/);assert.match(routes,/La période chevauche un autre contrat applicable/);assert.doesNotMatch(routes,/UPDATE employee_contracts SET employee_profile_id/)});
test('HR11A-24..30 GED, audit, realtime et transitions dédiées',()=>{assert.match(ged,/employee_contract:\['hr\.contract\.view'\]/);assert.match(ged,/FROM employee_contracts ec JOIN employee_profiles/);for(const action of['contract.created','contract.activated','contract.ended','contract.cancelled','contract.renewed'])assert.match(routes,new RegExp(action.replaceAll('.','\\.')));assert.match(routes,/hr:contract-updated/);assert.match(routes,/\/activate/);assert.match(routes,/\/end/);assert.match(routes,/\/cancel/)});
test('HR11A-RBAC-01..12 permissions persistées sans bypass de rôle',()=>{for(const code of['hr.contract.view','hr.contract.manage','hr.contract.type.manage']){assert.match(migration,new RegExp(code.replaceAll('.','\\.')));assert.match(seed,new RegExp(code.replaceAll('.','\\.')))}assert.match(routes,/scope==='OWN'/);assert.match(routes,/scope==='AGENCY'/);assert.match(routes,/scope==='CONCESSION'/);assert.match(routes,/scope==='GLOBAL'/);assert.doesNotMatch(routes,/SUPER_ADMIN/)});
test('HR11A-MIG historique sans backfill et baseline 065 convergente',()=>{assert.doesNotMatch(migration,/INSERT INTO employee_contracts/);assert.match(baseline,/VALUES \(65,'baseline_001_065'/);assert.match(migration,/INSERT INTO permissions/);assert.match(migration,/role_permissions/)});
