import assert from'node:assert/strict';
import{randomUUID}from'node:crypto';
import{after,test}from'node:test';
import jwt from'jsonwebtoken';
import supertest from'supertest';
import type{RowDataPacket}from'mysql2/promise';
import{createApp}from'../src/app.js';
import{execute,pool,query}from'../src/config/database.js';

const enabled=process.env.LCA_HR_REPORTING_DB_TEST==='1';
if(enabled)after(async()=>pool.end());

test('RH-REPORTING-UI-01 MySQL 8.4 : agrégations réelles, périodes et scopes sources',{skip:!enabled},async()=>{
 const suffix=randomUUID().slice(0,8),api=supertest(createApp()),insert=async(sql:string,params:unknown[]=[])=>String((await execute(sql,params)).insertId);
 const concessionA=await insert('INSERT INTO concessions(name,code) VALUES(?,?)',[`Reporting A ${suffix}`,`RPA-${suffix}`]),concessionB=await insert('INSERT INTO concessions(name,code) VALUES(?,?)',[`Reporting B ${suffix}`,`RPB-${suffix}`]),agencyA1=await insert('INSERT INTO agencies(concession_id,name,code) VALUES(?,?,?)',[concessionA,'Agence A1',`RPA1-${suffix}`]),agencyA2=await insert('INSERT INTO agencies(concession_id,name,code) VALUES(?,?,?)',[concessionA,'Agence A2',`RPA2-${suffix}`]),agencyB=await insert('INSERT INTO agencies(concession_id,name,code) VALUES(?,?,?)',[concessionB,'Agence B',`RPB1-${suffix}`]);
 const role=await insert('INSERT INTO roles(name,code,is_system,is_active) VALUES(?,?,FALSE,TRUE)',[`Reporting ${suffix}`,`REPORTING_${suffix}`]),users:string[]=[],employees:string[]=[],amounts=[100,200,300,400,500,900],agencies=[agencyA1,agencyA1,agencyA1,agencyA2,agencyA2,agencyB];
 for(let index=0;index<agencies.length;index++){const user=await insert('INSERT INTO users(agency_id,first_name,last_name,email,password_hash) VALUES(?,?,?,?,?)',[agencies[index],`R${index+1}`,`Fixture${suffix}`,`report-${suffix}-${index}@test.local`,'test']);users.push(user);const employee=await insert('INSERT INTO employee_profiles(user_id,employee_number,hire_date,employment_status) VALUES(?,?,?,?)',[user,`RPE-${suffix}-${index}`,'2026-01-01','active']);employees.push(employee);await execute('INSERT INTO salary_history(employee_profile_id,amount,effective_date,created_by) VALUES(?,?,?,?)',[employee,amounts[index],'2026-01-01',user])}
 const actor=users[0]!;await execute('INSERT INTO user_roles(user_id,role_id) VALUES(?,?)',[actor,role]);
 const marketing=await insert('INSERT INTO budget_categories(concession_id,code,name,is_active,created_by,updated_by) VALUES(?,?,?,TRUE,?,?)',[concessionA,`MARKETING_${suffix}`,'Marketing',actor,actor]),it=await insert('INSERT INTO budget_categories(concession_id,code,name,is_active,created_by,updated_by) VALUES(?,?,?,TRUE,?,?)',[concessionA,`IT_${suffix}`,'IT',actor,actor]),budgetA1=await insert("INSERT INTO budgets(scope_type,agency_id,label,initial_amount,start_date,end_date,category,category_id,status,created_by,updated_by) VALUES('agency',?,?,?,?,?,?,?,'active',?,?)",[agencyA1,'Marketing A1',1000,'2026-01-01','2026-12-31','Marketing',marketing,actor,actor]),budgetA2=await insert("INSERT INTO budgets(scope_type,agency_id,label,initial_amount,start_date,end_date,category,category_id,status,created_by,updated_by) VALUES('agency',?,?,?,?,?,?,?,'active',?,?)",[agencyA2,'IT A2',500,'2026-01-01','2026-12-31','IT',it,actor,actor]);
 await execute('INSERT INTO budget_expenses(budget_id,label,amount,expense_date,category,category_id,created_by) VALUES(?,?,?,?,?,?,?)',[budgetA1,'Campagne',100,'2026-02-10','Marketing',marketing,actor]);await execute('INSERT INTO budget_expenses(budget_id,label,amount,expense_date,category,category_id,created_by) VALUES(?,?,?,?,?,?,?)',[budgetA2,'Matériel',200,'2026-03-10','IT',it,actor]);
 const stockCategory=await insert('INSERT INTO internal_stock_categories(concession_id,code,name,is_active) VALUES(?,?,?,TRUE)',[concessionA,`SUPPLIES_${suffix}`,'Fournitures']);await execute('INSERT INTO internal_stock_items(agency_id,designation,category,category_id,unit,current_quantity,minimum_quantity,is_active,created_by,updated_by) VALUES(?,?,?,?,?,?,?,?,?,?)',[agencyA1,'Papier','Fournitures',stockCategory,'rame',10,5,true,actor,actor]);await execute('INSERT INTO internal_stock_items(agency_id,designation,category,category_id,unit,current_quantity,minimum_quantity,is_active,created_by,updated_by) VALUES(?,?,?,?,?,?,?,?,?,?)',[agencyA1,'Encre','Fournitures',stockCategory,'unité',1,2,true,actor,actor]);await execute('INSERT INTO internal_stock_items(agency_id,designation,category,category_id,unit,current_quantity,minimum_quantity,is_active,created_by,updated_by) VALUES(?,?,?,?,?,?,?,?,?,?)',[agencyA2,'Classeurs','Fournitures',stockCategory,'unité',5,5,true,actor,actor]);
 const codes=['hr.reporting.view','hr.employees.view','hr.salary.view','hr.budget.view','hr.expense.view','hr.stock.view'],permissionRows=await query<RowDataPacket[]>(`SELECT id,code FROM permissions WHERE code IN(${codes.map(()=>'?').join(',')})`,codes),permissionId=(code:string)=>String(permissionRows.find(row=>row.code===code)!.id),configure=async(scopes:Partial<Record<string,'OWN'|'AGENCY'|'CONCESSION'|'GLOBAL'>>)=>{await execute('DELETE FROM role_permissions WHERE role_id=?',[role]);for(const[code,scope]of Object.entries(scopes))await execute('INSERT INTO role_permissions(role_id,permission_id,scope) VALUES(?,?,?)',[role,permissionId(code),scope])};
 const token=jwt.sign({sub:actor,email:`report-${suffix}-0@test.local`,roles:[],agencyId:agencyA1},process.env.JWT_ACCESS_SECRET!,{expiresIn:'10m'}),auth=(request:supertest.Test)=>request.set('Authorization',`Bearer ${token}`),get=()=>auth(api.get('/api/hr/reporting?from=2026-01-01&to=2026-12-31'));
 await configure(Object.fromEntries(codes.map(code=>[code,'CONCESSION'])));let response=await get();assert.equal(response.status,200,JSON.stringify(response.body));assert.deepEqual(response.body.headcount.map((x:any)=>[x.agency_name,x.employees]),[['Agence A1',3],['Agence A2',2]]);assert.equal(response.body.payroll.reduce((sum:number,x:any)=>sum+x.payroll,0),1500);assert.deepEqual(response.body.budgets.map((x:any)=>[x.category_name,x.initial_amount,x.spent,x.remaining]),[['IT',500,200,300],['Marketing',1000,100,900]]);assert.deepEqual(response.body.expenseCategories.map((x:any)=>[x.category_name,x.spent]),[['IT',200],['Marketing',100]]);assert.deepEqual(response.body.expenseTrend.map((x:any)=>[x.period,x.spent]),[['2026-02',100],['2026-03',200]]);assert.equal(response.body.stock.reduce((sum:number,x:any)=>sum+x.items,0),3);assert.equal(response.body.stock.reduce((sum:number,x:any)=>sum+x.low_items,0),2);for(const section of['payroll','budgets','expenseCategories','stock'])for(const row of response.body[section])for(const value of Object.values(row))if(typeof value==='number')assert.ok(Number.isFinite(value));
 await configure({'hr.reporting.view':'GLOBAL','hr.employees.view':'GLOBAL','hr.budget.view':'GLOBAL','hr.expense.view':'GLOBAL','hr.stock.view':'GLOBAL'});response=await get();assert.equal(response.status,200);assert.equal(response.body.payroll,undefined);assert.ok(!('payroll'in response.body));
 await configure({'hr.reporting.view':'GLOBAL','hr.salary.view':'OWN'});response=await get();assert.equal(response.status,200);assert.deepEqual(response.body.payroll.map((x:any)=>[x.agency_name,x.payroll]),[['Agence A1',100]]);
 await configure({'hr.reporting.view':'GLOBAL','hr.salary.view':'AGENCY'});response=await get();assert.equal(response.body.payroll.reduce((sum:number,x:any)=>sum+x.payroll,0),600);
 await configure({'hr.reporting.view':'GLOBAL','hr.budget.view':'AGENCY'});response=await get();assert.deepEqual(response.body.budgets.map((x:any)=>x.category_name),['Marketing']);
 await configure({'hr.reporting.view':'GLOBAL','hr.budget.view':'CONCESSION'});response=await get();assert.equal(response.body.budgets.length,2);
 await configure({'hr.reporting.view':'GLOBAL','hr.stock.view':'AGENCY'});response=await get();assert.equal(response.body.stock.length,1);assert.equal(response.body.stock[0].items,2);
 await configure({'hr.reporting.view':'GLOBAL','hr.employees.view':'GLOBAL'});response=await get();assert.equal(response.body.headcount.filter((x:any)=>[agencyA1,agencyA2,agencyB].includes(x.agency_id)).reduce((sum:number,x:any)=>sum+x.employees,0),6);
 const fakeRole=await insert('INSERT INTO roles(name,code,is_system,is_active) VALUES(?,?,FALSE,TRUE)',[`Faux Super ${suffix}`,`SUPER_ADMIN_${suffix}`]),fakeUser=await insert('INSERT INTO users(agency_id,first_name,last_name,email,password_hash) VALUES(?,?,?,?,?)',[agencyA1,'Faux','Super',`fake-report-${suffix}@test.local`,'test']);await execute('INSERT INTO user_roles(user_id,role_id) VALUES(?,?)',[fakeUser,fakeRole]);for(const code of['hr.reporting.view','hr.employees.view'])await execute('INSERT INTO role_permissions(role_id,permission_id,scope) VALUES(?,?,?)',[fakeRole,permissionId(code),'AGENCY']);const fakeToken=jwt.sign({sub:fakeUser,email:`fake-report-${suffix}@test.local`,roles:['SUPER_ADMIN'],agencyId:agencyA1},process.env.JWT_ACCESS_SECRET!,{expiresIn:'10m'}),fakeResponse=await api.get('/api/hr/reporting?from=2026-01-01&to=2026-12-31').set('Authorization',`Bearer ${fakeToken}`);assert.equal(fakeResponse.body.headcount.reduce((sum:number,x:any)=>sum+x.employees,0),3);
 const systemUser=await insert('INSERT INTO users(agency_id,first_name,last_name,email,password_hash) VALUES(?,?,?,?,?)',[agencyA1,'Vrai','Super',`true-report-${suffix}@test.local`,'test']),[systemRole]=await query<RowDataPacket[]>("SELECT id FROM roles WHERE code='SUPER_ADMIN' AND is_system=TRUE AND is_active=TRUE");await execute('INSERT INTO user_roles(user_id,role_id) VALUES(?,?)',[systemUser,systemRole.id]);const systemToken=jwt.sign({sub:systemUser,email:`true-report-${suffix}@test.local`,roles:[],agencyId:agencyA1},process.env.JWT_ACCESS_SECRET!,{expiresIn:'10m'}),systemResponse=await api.get('/api/hr/reporting?from=2026-01-01&to=2026-12-31').set('Authorization',`Bearer ${systemToken}`);assert.equal(systemResponse.body.headcount.filter((x:any)=>[agencyA1,agencyA2,agencyB].includes(x.agency_id)).reduce((sum:number,x:any)=>sum+x.employees,0),6);
});
