import assert from 'node:assert/strict';
import {after,test} from 'node:test';
import {randomUUID} from 'node:crypto';
import type {ResultSetHeader,RowDataPacket} from 'mysql2/promise';
import jwt from 'jsonwebtoken';
import supertest from 'supertest';
import {pool,query} from '../src/config/database.js';
import {createApp} from '../src/app.js';
import {aggregateWorkshopReport} from '../src/modules/reports/workshop-report.service.js';

const enabled=process.env.LCA_14C5B_DB_TEST==='1';
if(enabled)after(async()=>pool.end());

test('14C5B MySQL 8.4 : origines, dates financières, déduplication et réconciliation',{skip:!enabled},async()=>{
  const suffix=randomUUID().slice(0,8),insert=async(sql:string,values:unknown[]=[])=>String(((await pool.execute<ResultSetHeader>(sql,values))[0]).insertId);
  const group=await insert('INSERT INTO groups_company(name,code) VALUES(?,?)',[`14C5B ${suffix}`,`C5G${suffix}`]);
  const concession=await insert('INSERT INTO concessions(group_id,name,code) VALUES(?,?,?)',[group,`14C5B ${suffix}`,`C5C${suffix}`]);
  const agency=await insert('INSERT INTO agencies(concession_id,name,code) VALUES(?,?,?)',[concession,`Agence ${suffix}`,`C5A${suffix}`]);
  const otherAgency=await insert('INSERT INTO agencies(concession_id,name,code) VALUES(?,?,?)',[concession,`Autre ${suffix}`,`C5B${suffix}`]);
  const method=String((await query<RowDataPacket[]>('SELECT id FROM payment_methods LIMIT 1'))[0].id);
  const makeOrder=async(origin:'CONCESSION'|'EXTERNAL'|'UNKNOWN',status:string,closedAt:string|null,targetAgency=agency)=>{
    const customer=await insert('INSERT INTO customers(customer_code,agency_id,first_name,last_name) VALUES(?,?,?,?)',[`C5-${suffix}-${origin}-${randomUUID().slice(0,4)}`,targetAgency,'Client',origin]);
    const vehicle=await insert("INSERT INTO vehicles(agency_id,commercial_origin,commercial_origin_source,is_commercial_stock,identity_brand,identity_model,vin,status) VALUES(?,?,'MANUAL',FALSE,'Test','14C5B',?,'received')",[targetAgency,origin,`VIN${suffix}${randomUUID().slice(0,6)}`]);
    const repair=await insert("INSERT INTO repair_orders(order_number,customer_id,vehicle_id,vehicle_commercial_origin,vehicle_origin_source,agency_id,status,received_at,closed_at,created_at) VALUES(?,?,?,?, 'MANUAL',?,?,?,?,?)",[`OR-${suffix}-${randomUUID().slice(0,5)}`,customer,vehicle,origin,targetAgency,status,'2026-09-01 08:00:00',closedAt,'2026-09-01 08:00:00']);
    return{customer,vehicle,repair,targetAgency};
  };
  const external=await makeOrder('EXTERNAL','closed','2026-09-20 18:00:00');
  const concessionOrder=await makeOrder('CONCESSION','in_progress',null);
  const unknown=await makeOrder('UNKNOWN','closed','2026-09-22 18:00:00');
  const cancelled=await makeOrder('EXTERNAL','cancelled','2026-09-23 18:00:00');
  const abandoned=await makeOrder('EXTERNAL','abandoned','2026-09-24 18:00:00');
  await makeOrder('EXTERNAL','closed','2026-09-25 18:00:00',otherAgency);
  for(const order of [external,unknown,cancelled,abandoned])await pool.execute("INSERT INTO repair_order_items(repair_order_id,item_type,description,quantity,unit_price,tax_rate,line_total,status) VALUES(?,'labor','Travaux',1,500000,20,500000,'active')",[order.repair]);
  const invoice=await insert("INSERT INTO invoices(invoice_number,customer_id,agency_id,repair_order_id,invoice_type,status,issue_date,due_date,total,amount_paid,balance_due) VALUES(?,?,?,?,'workshop','partially_paid','2026-09-10','2026-10-10',1000000,700000,100000)",[ `INV-${suffix}`,external.customer,agency,external.repair]);
  await pool.execute("INSERT INTO invoices(invoice_number,customer_id,agency_id,repair_order_id,invoice_type,status,issue_date,total,balance_due) VALUES(?,?,?,?,'workshop','draft','2026-09-12',900000,900000)",[`DRAFT-${suffix}`,external.customer,agency,external.repair]);
  await pool.execute("INSERT INTO invoices(invoice_number,customer_id,agency_id,repair_order_id,invoice_type,status,issue_date,total,balance_due) VALUES(?,?,?,?,'workshop','cancelled','2026-09-12',800000,0)",[`CANCEL-${suffix}`,external.customer,agency,external.repair]);
  await pool.execute("INSERT INTO credit_notes(credit_note_number,invoice_id,customer_id,status,reason,amount,issue_date) VALUES(?,?,?,'applied','Avoir octobre',200000,'2026-10-05')",[`CN-${suffix}`,invoice,external.customer]);
  await pool.execute("INSERT INTO credit_notes(credit_note_number,invoice_id,customer_id,status,reason,amount,issue_date) VALUES(?,?,?,'cancelled','Annulé',700000,'2026-09-15')",[`CNC-${suffix}`,invoice,external.customer]);
  await pool.execute("INSERT INTO payments(payment_number,invoice_id,customer_id,payment_method_id,amount,payment_date,status) VALUES(?,?,?,?,400000,'2026-09-15 12:00:00','confirmed')",[`PAY1-${suffix}`,invoice,external.customer,method]);
  await pool.execute("INSERT INTO payments(payment_number,invoice_id,customer_id,payment_method_id,amount,payment_date,status) VALUES(?,?,?,?,300000,'2026-10-15 12:00:00','confirmed')",[`PAY2-${suffix}`,invoice,external.customer,method]);
  await pool.execute("INSERT INTO payments(payment_number,invoice_id,customer_id,payment_method_id,amount,payment_date,status) VALUES(?,?,?,?,999000,'2026-09-15 12:00:00','rejected')",[`PAYR-${suffix}`,invoice,external.customer,method]);
  const legacy=await insert("INSERT INTO payments(payment_number,invoice_id,customer_id,payment_method_id,amount,payment_date,status,refunded_at) VALUES(?,?,?,?,50000,'2026-09-16 12:00:00','refunded','2026-10-16 12:00:00')",[`PAYL-${suffix}`,invoice,external.customer,method]);
  const coexist=await insert("INSERT INTO payments(payment_number,invoice_id,customer_id,payment_method_id,amount,payment_date,status,refunded_at) VALUES(?,?,?,?,70000,'2026-09-17 12:00:00','refunded','2026-10-17 12:00:00')",[`PAYC-${suffix}`,invoice,external.customer,method]);
  const credit=await insert("INSERT INTO credit_notes(credit_note_number,invoice_id,customer_id,status,reason,amount,issue_date) VALUES(?,?,?,'applied','Coexistence',70000,'2026-10-17')",[`CNCX-${suffix}`,invoice,external.customer]);
  await pool.execute('INSERT INTO payment_refunds(payment_id,invoice_id,credit_note_id,amount,reason,idempotency_key,refunded_at) VALUES(?,?,?,?,?,?,?)',[coexist,invoice,credit,70000,'Moderne',randomUUID(),'2026-10-17 12:00:00']);
  assert.ok(legacy);
  const input={scopeSql:'ro.agency_id=?',scopeParams:[agency]};
  const september=await aggregateWorkshopReport({...input,from:'2026-09-01',to:'2026-09-30'}),october=await aggregateWorkshopReport({...input,from:'2026-10-01',to:'2026-10-31'});
  assert.equal(september.workshop_revenue,1_000_000);
  assert.equal(september.workshop_collected,520_000);
  assert.equal(october.workshop_revenue,-270_000);
  assert.equal(october.workshop_collected,180_000);
  assert.equal(september.byCommercialOrigin.find(row=>row.origin==='EXTERNAL')!.interventionAmount,600_000);
  assert.equal(september.interventionAmount,1_200_000);
  assert.deepEqual(september.byCommercialOrigin.map(row=>row.origin),['CONCESSION','EXTERNAL','UNKNOWN']);
  assert.equal(september.byCommercialOrigin.reduce((sum,row)=>sum+row.netInvoiced,0),september.workshop_revenue);
  assert.equal(september.byCommercialOrigin.reduce((sum,row)=>sum+row.netCollected,0),september.workshop_collected);
  assert.equal((await aggregateWorkshopReport({...input,from:'2026-09-01',to:'2026-09-30',origin:'EXTERNAL'})).repair_orders_count,3);
  assert.equal(september.repair_orders_count,5);
  assert.equal(september.byCommercialOrigin.find(row=>row.origin==='CONCESSION')!.activeOrders,1);
  const makeActor=async(label:string,codes:string[])=>{
    const role=await insert('INSERT INTO roles(name,code,is_active) VALUES(?,?,TRUE)',[`14C5B ${label} ${suffix}`,`C5_${label}_${suffix}`]);
    const user=await insert('INSERT INTO users(agency_id,first_name,last_name,email,password_hash) VALUES(?,?,?,?,?)',[agency,'Audit',label,`${label}-${suffix}@test.local`,'test']);
    await pool.execute('INSERT INTO user_roles(user_id,role_id) VALUES(?,?)',[user,role]);
    for(const code of codes){const permission=(await query<RowDataPacket[]>('SELECT id FROM permissions WHERE code=?',[code]))[0];assert.ok(permission,code);await pool.execute("INSERT INTO role_permissions(role_id,permission_id,scope) VALUES(?,?,'AGENCY')",[role,permission.id])}
    const sid=randomUUID();await pool.execute('INSERT INTO refresh_tokens(id,user_id,token_hash,expires_at) VALUES(?,?,?,DATE_ADD(NOW(),INTERVAL 1 DAY))',[sid,user,randomUUID().replaceAll('-','').padEnd(64,'0')]);
    return jwt.sign({sub:user,sid,email:`${label}-${suffix}@test.local`,roles:[],agencyId:agency},process.env.JWT_ACCESS_SECRET!,{algorithm:'HS256',expiresIn:'15m'});
  };
  const full=await makeActor('full',['reporting.view','reporting.export','workshop.productivity.view','billing.view','billing.payment.view']);
  const noPayment=await makeActor('nopayment',['reporting.view','reporting.export','workshop.productivity.view','billing.view']);
  const noReporting=await makeActor('noreport',['workshop.productivity.view','billing.view','billing.payment.view']);
  const api=supertest(createApp()),get=(path:string,token:string)=>api.get(`/api${path}`).set('Authorization',`Bearer ${token}`);
  const response=await get('/reports/workshop?from=2026-09-01&to=2026-09-30',full);
  assert.equal(response.status,200,JSON.stringify(response.body));assert.equal(response.body.workshop_revenue,1_000_000);assert.equal(response.body.byCommercialOrigin.length,3);
  assert.equal((await get('/reports/workshop?from=2026-09-01&to=2026-09-30&origin=EXTERNAL',full)).body.repair_orders_count,3);
  assert.equal((await get("/reports/workshop?from=2026-09-01&to=2026-09-30&origin=EXTERNAL%27%20OR%201%3D1",full)).status,400);
  assert.equal((await get('/reports/workshop?from=2026-09-01&to=2026-09-30',noPayment)).status,403);
  assert.equal((await get('/reports/workshop?from=2026-09-01&to=2026-09-30',noReporting)).status,403);
  const csv=await get('/reports/export?section=workshop&from=2026-09-01&to=2026-09-30',full);
  assert.equal(csv.status,200);assert.match(csv.text,/"Facturation atelier TTC";"1000000"/);assert.match(csv.text,/"Extérieur";"3"/);
});
