import assert from'node:assert/strict';
import{readFileSync}from'node:fs';
import test from'node:test';
import{commercialStockPredicate,vehicleOriginSnapshot}from'../src/modules/vehicles/vehicle-commercial.js';
const read=(path:string)=>readFileSync(new URL(`../${path}`,import.meta.url),'utf8');
const migration=read('database/migrations/070_vehicle_commercial_origin.sql');
const baseline=read('database/baseline/001_initial_schema.sql');
const workshop=read('src/modules/workshop/workshop.routes.ts');
const customers=read('src/modules/customers/customer.routes.ts');
const vehicles=read('src/modules/vehicles/vehicle.routes.ts');
const dashboard=read('src/modules/dashboard/dashboard.routes.ts');
const reports=read('src/modules/reports/report.routes.ts');
const sales=read('src/modules/sales/sale.service.ts');
const quotations=read('src/modules/quotations/quotation.service.ts');
const bootstrap=read('src/scripts/database-bootstrap.ts');

test('14C1-01 origine commerciale explicite et conservatrice',()=>{assert.match(migration,/ENUM\('CONCESSION','EXTERNAL','UNKNOWN'\).*DEFAULT 'UNKNOWN'/);assert.deepEqual(vehicleOriginSnapshot(null,null),{origin:'UNKNOWN',source:'LEGACY'})});
test('14C1-02 stock commercial est indépendant de l’origine',()=>assert.match(migration,/is_commercial_stock BOOLEAN NOT NULL DEFAULT TRUE/));
test('14C1-03 anciens véhicules restent visibles sans reclassification',()=>{assert.match(migration,/commercial_origin[^\n]+DEFAULT 'UNKNOWN'/);assert.doesNotMatch(migration,/UPDATE vehicles SET commercial_origin/)});
test('14C1-04 VIN nullable mais unicité réelle conservée',()=>{assert.match(migration,/MODIFY COLUMN vin VARCHAR\(50\) NULL/);assert.match(baseline,/vin VARCHAR\(50\) NULL UNIQUE/)});
test('14C1-05 création commerciale conserve VIN strict',()=>assert.match(vehicles,/VIN doit comporter exactement 17 caractères valides/));
test('14C1-06 catalogue optionnel avec identité minimale contrôlée',()=>{assert.match(migration,/MODIFY COLUMN version_id BIGINT UNSIGNED NULL/);assert.match(migration,/chk_vehicle_identity_description/)});
test('14C1-07 table de relations client véhicule présente',()=>assert.match(migration,/CREATE TABLE customer_vehicles/));
test('14C1-08 plusieurs types de relation métier',()=>assert.match(migration,/ENUM\('OWNER','DRIVER','RESPONSIBLE','FLEET'\)/));
test('14C1-09 source de relation obligatoire',()=>assert.match(migration,/source_type ENUM\('SALE','REPAIR_ORDER','MANUAL','IMPORT'\) NOT NULL/));
test('14C1-10 doublon courant identique interdit',()=>assert.match(migration,/UNIQUE KEY uq_customer_vehicle_current \(customer_id,vehicle_id,relation_type,current_relation_key\)/));
test('14C1-11 historique daté et cohérent',()=>assert.match(migration,/is_current=FALSE AND valid_to IS NOT NULL AND valid_to>=valid_from/));
test('14C1-12 plusieurs clients historiques restent possibles',()=>assert.doesNotMatch(migration,/UNIQUE KEY[^\n]+\(vehicle_id,current_relation_key\)/));
test('14C1-13 lectures Atelier conservent vente et ancien OR',()=>{assert.match(workshop,/EXISTS\(SELECT 1 FROM customer_vehicles/);assert.match(workshop,/EXISTS\(SELECT 1 FROM sale_items/);assert.match(workshop,/EXISTS\(SELECT 1 FROM repair_orders ro/)});
test('14C1-14 fiche 360 conserve transition à trois sources',()=>{assert.match(customers,/FROM customer_vehicles cv/);assert.match(customers,/FROM sale_items si/);assert.match(customers,/FROM repair_orders ro/)});
test('14C1-15 OR photographie origine et source',()=>{assert.match(migration,/vehicle_commercial_origin/);assert.match(workshop,/vehicleOriginSnapshot/);assert.match(workshop,/vehicle_commercial_origin,vehicle_origin_source/)});
test('14C1-16 stock, dashboard et export excluent le non commercial',()=>{assert.equal(commercialStockPredicate(),'v.is_commercial_stock=TRUE');assert.match(dashboard,/v\.is_commercial_stock=TRUE/);assert.equal((reports.match(/v\.is_commercial_stock=TRUE/g)??[]).length,3)});
test('14C1-17 ventes refusent véhicule Atelier',()=>{assert.match(sales,/Ce véhicule Atelier ne peut pas être vendu/);assert.match(sales,/is_commercial_stock=TRUE AND archived_at IS NULL/)});
test('14C1-18 devis refusent véhicule Atelier',()=>assert.match(quotations,/Ce véhicule Atelier ne peut pas être utilisé pour un nouveau devis/));
test('14C1-19 vente confirmée prouve seulement une origine inconnue',()=>assert.match(sales,/commercial_origin='UNKNOWN'/));
test('14C1-20 baseline fraîche absorbe 070',()=>{assert.match(bootstrap,/FRESH_BASELINE_VERSION=70/);for(const token of['commercial_origin','customer_vehicles','vehicle_commercial_origin'])assert.ok(baseline.includes(token),token)});
