import assert from'node:assert/strict';
import{randomUUID}from'node:crypto';
import{after,test}from'node:test';
import jwt from'jsonwebtoken';
import supertest from'supertest';
import type{ResultSetHeader,RowDataPacket}from'mysql2/promise';
import{createApp}from'../src/app.js';
import{env}from'../src/config/env.js';
import{pool,query}from'../src/config/database.js';

const enabled=process.env.LOT14C2_MYSQL_TEST==='1';
if(enabled)after(()=>pool.end());
const insert=async(sql:string,params:unknown[]=[])=>String(((await pool.execute<ResultSetHeader>(sql,params as any[]))[0]).insertId);
const rows=(sql:string,params:unknown[]=[])=>query<RowDataPacket[]>(sql,params as any[]);

test('Lot 14C.2 — API authentifiées et invariants réels MySQL 8.4',{skip:!enabled,timeout:180_000},async()=>{
  const suffix=randomUUID().replaceAll('-','').slice(0,10),api=supertest(createApp());
  const concession=await insert('INSERT INTO concessions(name,code) VALUES(?,?)',[`C ${suffix}`,`C${suffix}`]);
  const otherConcession=await insert('INSERT INTO concessions(name,code) VALUES(?,?)',[`X ${suffix}`,`X${suffix}`]);
  const agency=await insert('INSERT INTO agencies(concession_id,name,code) VALUES(?,?,?)',[concession,`A ${suffix}`,`A${suffix}`]);
  const sibling=await insert('INSERT INTO agencies(concession_id,name,code) VALUES(?,?,?)',[concession,`B ${suffix}`,`B${suffix}`]);
  const foreign=await insert('INSERT INTO agencies(concession_id,name,code) VALUES(?,?,?)',[otherConcession,`X ${suffix}`,`Z${suffix}`]);
  const role=await insert('INSERT INTO roles(name,code,is_system) VALUES(?,?,FALSE)',[`Lot14C2 ${suffix}`,`LOT14C2_${suffix}`]);
  const noPermissionRole=await insert('INSERT INTO roles(name,code,is_system) VALUES(?,?,FALSE)',[`Sans droits ${suffix}`,`NONE_${suffix}`]);
  const user=await insert('INSERT INTO users(agency_id,first_name,last_name,email,password_hash) VALUES(?,?,?,?,?)',[agency,'API','Test',`api-${suffix}@test.invalid`,'not-used']);
  const deniedUser=await insert('INSERT INTO users(agency_id,first_name,last_name,email,password_hash) VALUES(?,?,?,?,?)',[agency,'Sans','Droits',`none-${suffix}@test.invalid`,'not-used']);
  await pool.execute('INSERT INTO user_roles(user_id,role_id) VALUES(?,?),(?,?)',[user,role,deniedUser,noPermissionRole]);
  const permissions=['customers.view','customers.history.view','vehicles.view','workshop.vehicles.view','workshop.external_vehicle.create','workshop.vehicle.associations.create','workshop.vehicle.associations.view','workshop.vehicle.associations.close','service.order.create','service.order.view','service.order.receive'];
  await pool.execute(`INSERT INTO role_permissions(role_id,permission_id,scope) SELECT ?,id,'AGENCY' FROM permissions WHERE code IN (${permissions.map(()=>'?').join(',')})`,[role,...permissions]);
  const sid=randomUUID(),revokedSid=randomUUID();await pool.execute('INSERT INTO refresh_tokens(id,user_id,token_hash,expires_at) VALUES(?,?,?,DATE_ADD(NOW(),INTERVAL 1 DAY)),(?,?,?,DATE_ADD(NOW(),INTERVAL 1 DAY))',[sid,user,`${suffix}1`.padEnd(64,'1'),revokedSid,user,`${suffix}2`.padEnd(64,'2')]);await pool.execute('UPDATE refresh_tokens SET revoked_at=NOW() WHERE id=?',[revokedSid]);
  const token=(sub:string,session:string)=>jwt.sign({sub,sid:session},env.jwt.accessSecret,{algorithm:'HS256',expiresIn:'15m'}),auth=token(user,sid);
  const customer=await insert('INSERT INTO customers(customer_code,agency_id,first_name,last_name,email,assigned_user_id,created_by) VALUES(?,?,?,?,?,?,?)',[`CLI-${suffix}`,agency,'Ada','Atelier',`ada-${suffix}@test.invalid`,user,user]);
  const foreignCustomer=await insert('INSERT INTO customers(customer_code,agency_id,last_name,email) VALUES(?,?,?,?)',[`CLX-${suffix}`,foreign,'Hors scope',`x-${suffix}@test.invalid`]);
  const internal=await insert("INSERT INTO vehicles(agency_id,commercial_origin,commercial_origin_source,is_commercial_stock,identity_brand,identity_model,vehicle_type,vin,status,created_by) VALUES(?,'CONCESSION','SALE',TRUE,'LCA','Interne','used',?,'available',?)",[agency,`VF1${suffix.toUpperCase()}000001`.slice(0,17),user]);
  await pool.execute("INSERT INTO customer_vehicles(customer_id,vehicle_id,agency_id,relation_type,source_type,created_by) VALUES(?,?,?,'DRIVER','MANUAL',?)",[customer,internal,agency,user]);
  assert.equal((await api.get('/api/workshop/vehicles/search?brand=LCA')).status,401);
  assert.equal((await api.get('/api/workshop/vehicles/search?brand=LCA').set('Authorization','Bearer invalide')).status,401);
  assert.equal((await api.get('/api/workshop/vehicles/search?brand=LCA').set('Authorization',`Bearer ${token(user,randomUUID())}`)).status,401);
  assert.equal((await api.get('/api/workshop/vehicles/search?brand=LCA').set('Authorization',`Bearer ${token(user,revokedSid)}`)).status,401);
  const deniedSid=randomUUID();await pool.execute('INSERT INTO refresh_tokens(id,user_id,token_hash,expires_at) VALUES(?,?,?,DATE_ADD(NOW(),INTERVAL 1 DAY))',[deniedSid,deniedUser,`${suffix}3`.padEnd(64,'3')]);assert.equal((await api.get('/api/workshop/vehicles/search?brand=LCA').set('Authorization',`Bearer ${token(deniedUser,deniedSid)}`)).status,403);
  const clientSearch=await api.get('/api/customers?search=Ada').set('Authorization',`Bearer ${auth}`);assert.equal(clientSearch.status,200);assert.ok(clientSearch.body.some((x:any)=>x.id===customer));
  const search=await api.get('/api/workshop/vehicles/search?brand=LCA').set('Authorization',`Bearer ${auth}`);assert.equal(search.status,200);assert.equal(search.body.items.length,1);
  const invalid=await api.post('/api/workshop/external-vehicles').set('Authorization',`Bearer ${auth}`).send({customerId:customer,agencyId:agency,brand:'Libre',model:'Route',vin:'FAUX'});assert.equal(invalid.status,400);
  const create=await api.post('/api/workshop/external-vehicles').set('Authorization',`Bearer ${auth}`).send({customerId:customer,agencyId:agency,brand:'Libre',model:'Route',registrationNumber:`AB-${suffix}`,commercialOrigin:'CONCESSION',isCommercialStock:true});assert.equal(create.status,201,JSON.stringify(create.body));
  const vehicleId=String(create.body.vehicleId),associationId=String(create.body.associationId),[vehicle]=await rows('SELECT * FROM vehicles WHERE id=?',[vehicleId]);assert.equal(vehicle.commercial_origin,'EXTERNAL');assert.equal(vehicle.commercial_origin_source,'WORKSHOP');assert.equal(Number(vehicle.is_commercial_stock),0);assert.equal(vehicle.vin,null);assert.equal(vehicle.version_id,null);
  const duplicatePlate=await api.post('/api/workshop/external-vehicles').set('Authorization',`Bearer ${auth}`).send({customerId:customer,agencyId:agency,brand:'Libre',model:'Route 2',registrationNumber:`AB ${suffix}`});assert.equal(duplicatePlate.status,409);assert.equal(duplicatePlate.body.details.code,'REGISTRATION_AMBIGUOUS');
  const confirmed=await api.post('/api/workshop/external-vehicles').set('Authorization',`Bearer ${auth}`).send({customerId:customer,agencyId:agency,brand:'Libre',model:'Route 2',registrationNumber:`AB ${suffix}`,confirmRegistrationAmbiguity:true,relationType:'DRIVER'});assert.equal(confirmed.status,201,JSON.stringify(confirmed.body));
  const inaccessible=await api.post('/api/workshop/external-vehicles').set('Authorization',`Bearer ${auth}`).send({customerId:foreignCustomer,agencyId:agency,brand:'Non',model:'Autorisé'});assert.equal(inaccessible.status,404);
  const beforeRollback=Number((await rows("SELECT COUNT(*) total FROM vehicles WHERE identity_model='Rollback'"))[0]!.total);const rollback=await api.post('/api/workshop/external-vehicles').set('Authorization',`Bearer ${auth}`).send({customerId:customer,agencyId:agency,brand:'Test',model:'Rollback',relationType:'INVALIDE'});assert.equal(rollback.status,400);assert.equal(Number((await rows("SELECT COUNT(*) total FROM vehicles WHERE identity_model='Rollback'"))[0]!.total),beforeRollback);
  const vin=`VF1${suffix.toUpperCase()}RACE001`.slice(0,17),payload={customerId:customer,agencyId:agency,brand:'Race',model:'VIN',vin,relationType:'FLEET'};const race=await Promise.all([api.post('/api/workshop/external-vehicles').set('Authorization',`Bearer ${auth}`).send(payload),api.post('/api/workshop/external-vehicles').set('Authorization',`Bearer ${auth}`).send(payload)]);assert.deepEqual(race.map(x=>x.status).sort(),[201,409]);assert.equal(Number((await rows('SELECT COUNT(*) total FROM vehicles WHERE vin=?',[vin]))[0]!.total),1);
  const duplicateRelation=await api.post('/api/workshop/vehicle-associations').set('Authorization',`Bearer ${auth}`).send({customerId:customer,vehicleId,agencyId:agency,relationType:'OWNER'});assert.equal(duplicateRelation.status,409);assert.equal(duplicateRelation.body.details.code,'RELATION_ALREADY_EXISTS');
  const close=await api.patch(`/api/workshop/vehicle-associations/${associationId}/close`).set('Authorization',`Bearer ${auth}`).send({});assert.equal(close.status,200);
  const history=await api.get(`/api/workshop/customers/${customer}/vehicle-associations?includeHistory=true`).set('Authorization',`Bearer ${auth}`);assert.equal(history.status,200);assert.ok(history.body.some((x:any)=>x.id===associationId&&!x.isCurrent));
  const recreate=await api.post('/api/workshop/vehicle-associations').set('Authorization',`Bearer ${auth}`).send({customerId:customer,vehicleId,agencyId:agency,relationType:'OWNER'});assert.equal(recreate.status,201);
  const repair=await api.post('/api/repair-orders').set('Authorization',`Bearer ${auth}`).send({customerId:customer,vehicleId,agencyId:agency,advisorId:user,mileage:120,complaint:'Contrôle intégration'});assert.equal(repair.status,201,JSON.stringify(repair.body));const repairId=String(repair.body.id??repair.body.repairOrderId);const detail=await api.get(`/api/repair-orders/${repairId}`).set('Authorization',`Bearer ${auth}`);assert.equal(detail.status,200);const[repairSql]=await rows('SELECT vehicle_commercial_origin,vehicle_origin_source FROM repair_orders WHERE id=?',[repairId]);assert.equal(repairSql.vehicle_commercial_origin,'EXTERNAL');assert.equal(repairSql.vehicle_origin_source,'WORKSHOP');
  const customer360=await api.get(`/api/customers/${customer}/360`).set('Authorization',`Bearer ${auth}`);assert.equal(customer360.status,200);assert.ok(customer360.body.vehicles.some((x:any)=>x.id===vehicleId));assert.ok(customer360.body.vehicles.some((x:any)=>x.id===internal));
  const stock=await api.get('/api/vehicles?view=all').set('Authorization',`Bearer ${auth}`);assert.equal(stock.status,200);const stockItems=Array.isArray(stock.body)?stock.body:(stock.body.items??[]);assert.ok(!stockItems.some((x:any)=>x.id===vehicleId));
  const foreignAgency=await api.post('/api/workshop/external-vehicles').set('Authorization',`Bearer ${auth}`).send({customerId:customer,agencyId:sibling,brand:'Scope',model:'Refus'});assert.equal(foreignAgency.status,403);
  const audits=await rows("SELECT action,user_id,agency_id,concession_id,new_values FROM audit_logs WHERE entity_id IN (?,?) AND action LIKE 'workshop.%'",[vehicleId,associationId]);assert.ok(audits.some(x=>x.action==='workshop.external_vehicle.created'));assert.ok(audits.some(x=>x.action==='workshop.vehicle.association.created'));assert.ok(audits.some(x=>x.action==='workshop.vehicle.association.closed'));assert.ok(audits.every(x=>String(x.user_id)===user&&String(x.agency_id)===agency&&String(x.concession_id)===concession&&!String(x.new_values).includes('test.invalid')));
});
