import assert from 'node:assert/strict';
import {randomUUID} from 'node:crypto';
import {after,test} from 'node:test';
import supertest from 'supertest';
import type {Request} from 'express';
import {createApp} from '../src/app.js';
import {pool,query} from '../src/config/database.js';
import type {RowDataPacket} from 'mysql2/promise';
import {validateLeadAssignee} from '../src/modules/crm/crm-assignment.js';
import {directory} from '../src/modules/users/user.service.js';

const enabled=process.env.LCA_PREPROD_DB_TEST==='1';
if(enabled)after(async()=>{await pool.end()});

test('PREPROD-MYSQL: facture créée/idempotente et suppression transactionnelle de rôle', {skip:!enabled},async()=>{
  const api=supertest(createApp());
  const login=await api.post('/api/auth/login').send({email:process.env.ADMIN_EMAIL,password:process.env.ADMIN_PASSWORD});
  assert.equal(login.status,200,JSON.stringify(login.body));
  const token=login.body.accessToken as string;
  const actor=api;
  const auth=(request:supertest.Test)=>request.set('Authorization',`Bearer ${token}`);
  const[agency]=await query<RowDataPacket[]>('SELECT id FROM agencies WHERE code=?',['LCA-BZV']);
  assert.ok(agency);
  const suffix=randomUUID().slice(0,8).toUpperCase();
  const customerCode=`QA-${suffix}`;
  await pool.execute('INSERT INTO customers(customer_code,agency_id,first_name,last_name) VALUES(?,?,?,?)',[customerCode,agency.id,'Client','Facture']);
  const[customer]=await query<RowDataPacket[]>('SELECT id FROM customers WHERE customer_code=?',[customerCode]);
  assert.ok(customer);
  const payload={agencyId:String(agency.id),customerId:String(customer.id),invoiceType:'manual',issueDate:'2026-09-16',dueDate:'2026-10-16',idempotencyKey:`invoice-${suffix}`,items:[{description:'Test de facturation',quantity:1,unitPrice:100_000,discount:10_000}]};
  const invoice=await auth(actor.post('/api/invoices')).send(payload);
  assert.equal(invoice.status,201,JSON.stringify(invoice.body));
  const[row]=await query<RowDataPacket[]>('SELECT status,total,balance_due FROM invoices WHERE id=?',[invoice.body.id]);
  assert.equal(row?.status,'draft');
  assert.equal(Number(row?.balance_due),Number(row?.total));
  const replay=await auth(actor.post('/api/invoices')).send(payload);
  assert.equal(replay.status,200,JSON.stringify(replay.body));
  assert.equal(replay.body.id,invoice.body.id);
  const invoicePdf=await auth(actor.get(`/api/invoices/${invoice.body.id}/pdf`));
  assert.equal(invoicePdf.status,200);
  assert.match(String(invoicePdf.headers['content-type']),/application\/pdf/);
  assert.equal(invoicePdf.body.subarray(0,4).toString(),'%PDF');

  const system=await query<RowDataPacket[]>("SELECT id FROM roles WHERE code='SUPER_ADMIN' AND is_system=TRUE");
  assert.ok(system[0]);
  const forbidden=await auth(actor.delete(`/api/roles/${system[0].id}`)).send({});
  assert.equal(forbidden.status,403);
  const unusedRole=await auth(actor.post('/api/roles')).send({code:`QA_UNUSED_${suffix}`,name:`Rôle inutilisé ${suffix}`,permissions:[]});
  assert.equal(unusedRole.status,201,JSON.stringify(unusedRole.body));
  const unusedDeleted=await auth(actor.delete(`/api/roles/${unusedRole.body.id}`)).send({});
  assert.equal(unusedDeleted.status,200,JSON.stringify(unusedDeleted.body));
  const first=await auth(actor.post('/api/roles')).send({code:`QA_ROLE_${suffix}`,name:`Rôle recette ${suffix}`,permissions:[]});
  assert.equal(first.status,201,JSON.stringify(first.body));
  const replacement=await auth(actor.post('/api/roles')).send({code:`QA_REPLACE_${suffix}`,name:`Remplaçant recette ${suffix}`,permissions:[]});
  assert.equal(replacement.status,201,JSON.stringify(replacement.body));
  const roleId=String(first.body.id),replacementId=String(replacement.body.id);
  const user=await auth(actor.post('/api/users')).send({firstName:'Test',lastName:'Réaffectation',email:`qa-${suffix.toLowerCase()}@example.test`,password:'qa-user-password-123',agencyId:String(agency.id),roleCode:`QA_ROLE_${suffix}`});
  assert.equal(user.status,201,JSON.stringify(user.body));
  const requiresReplacement=await auth(actor.delete(`/api/roles/${roleId}`)).send({});
  assert.equal(requiresReplacement.status,409);
  const removed=await auth(actor.delete(`/api/roles/${roleId}`)).send({replacementRoleId:replacementId});
  assert.equal(removed.status,200,JSON.stringify(removed.body));
  const assignments=await query<RowDataPacket[]>('SELECT role_id FROM user_roles WHERE user_id=?',[user.body.id]);
  assert.deepEqual(assignments.map(value=>String(value.role_id)),[replacementId]);
  const preserved=await query<RowDataPacket[]>('SELECT id FROM users WHERE id=?',[user.body.id]);
  assert.equal(preserved.length,1);
  const unused=await auth(actor.delete(`/api/roles/${replacementId}`)).send({});
  assert.equal(unused.status,409);
  const[salesPermission]=await query<RowDataPacket[]>("SELECT id FROM permissions WHERE code='sales.create'");
  assert.ok(salesPermission);
  const fakeRole=await auth(actor.post('/api/roles')).send({code:`SUPER_ADMIN_FAKE_${suffix}`,name:`Faux super admin ${suffix}`,permissions:[{permissionId:String(salesPermission.id),scope:'AGENCY'}]});
  assert.equal(fakeRole.status,201,JSON.stringify(fakeRole.body));
  const fakeUser=await auth(actor.post('/api/users')).send({firstName:'Faux',lastName:'Administrateur',email:`fake-${suffix.toLowerCase()}@example.test`,password:'qa-fake-password-123',agencyId:String(agency.id),roleCode:`SUPER_ADMIN_FAKE_${suffix}`});
  assert.equal(fakeUser.status,201,JSON.stringify(fakeUser.body));
  const fakeLogin=await actor.post('/api/auth/login').send({email:`fake-${suffix.toLowerCase()}@example.test`,password:'qa-fake-password-123'});
  assert.equal(fakeLogin.status,200,JSON.stringify(fakeLogin.body));
  assert.equal(fakeLogin.body.user.role.isSystemSuperAdmin,false);
  const fakeUsers=await actor.get('/api/users').set('Authorization',`Bearer ${fakeLogin.body.accessToken}`);
  assert.equal(fakeUsers.status,403);
  const fakeDelete=await actor.delete(`/api/roles/${replacementId}`).set('Authorization',`Bearer ${fakeLogin.body.accessToken}`).send({});
  assert.equal(fakeDelete.status,403);
  const assignmentRequest={user:{sub:String(login.body.user.id),agencyId:String(agency.id)},rbac:{isSuperAdmin:true,permissions:new Map()}} as unknown as Request;
  await assert.rejects(()=>validateLeadAssignee(String(login.body.user.id),assignmentRequest),/introuvable/);
  const assignable=await validateLeadAssignee(String(fakeUser.body.id),assignmentRequest);
  assert.equal(assignable.assignedUserId,String(fakeUser.body.id));
  const candidates=await directory({},assignmentRequest);
  assert.equal(candidates.some(candidate=>candidate.id===String(login.body.user.id)),false);
  assert.equal(candidates.some(candidate=>candidate.id===String(fakeUser.body.id)),true);
  await pool.execute('INSERT INTO brands(name,code) VALUES(?,?)',[`QA marque ${suffix}`,`QA-B-${suffix}`]);
  const[brand]=await query<RowDataPacket[]>('SELECT id FROM brands WHERE code=?',[`QA-B-${suffix}`]);
  await pool.execute('INSERT INTO models(brand_id,name) VALUES(?,?)',[brand!.id,`Modèle ${suffix}`]);
  const[model]=await query<RowDataPacket[]>('SELECT id FROM models WHERE brand_id=?',[brand!.id]);
  await pool.execute('INSERT INTO versions(model_id,name) VALUES(?,?)',[model!.id,'Recette']);
  const[version]=await query<RowDataPacket[]>('SELECT id FROM versions WHERE model_id=?',[model!.id]);
  await pool.execute("INSERT INTO vehicles(version_id,agency_id,vin,stock_number,purchase_price,catalog_price,sale_price,status) VALUES(?,?,?,?,?,?,?,'available')",[version!.id,agency.id,`QA${suffix}123456789`,`QA-STK-${suffix}`,35_000_000,40_000_000,40_000_000]);
  const[vehicle]=await query<RowDataPacket[]>('SELECT id,status FROM vehicles WHERE stock_number=?',[`QA-STK-${suffix}`]);
  const salePayload={agencyId:String(agency.id),customerId:String(customer.id),vehicleId:String(vehicle!.id),salespersonId:String(fakeUser.body.id),depositAmount:0,notes:'Recette marge'};
  const loss=await auth(actor.post('/api/sales')).send({...salePayload,discount:5_000_001,idempotencyKey:`sale-loss-${suffix}`});
  assert.equal(loss.status,409,JSON.stringify(loss.body));
  const[afterLoss]=await query<RowDataPacket[]>('SELECT status FROM vehicles WHERE id=?',[vehicle!.id]);
  assert.equal(afterLoss?.status,'available');
  const forgedAdmin=await auth(actor.post('/api/sales')).send({...salePayload,salespersonId:String(login.body.user.id),discount:0,idempotencyKey:`sale-admin-${suffix}`});
  assert.equal(forgedAdmin.status,400,JSON.stringify(forgedAdmin.body));
  const breakEven=await auth(actor.post('/api/sales')).send({...salePayload,discount:5_000_000,idempotencyKey:`sale-equal-${suffix}`});
  assert.equal(breakEven.status,201,JSON.stringify(breakEven.body));
  const orderPdf=await auth(actor.get(`/api/documents/business/sale/${breakEven.body.id}/pdf`));
  assert.equal(orderPdf.status,200);
  assert.match(String(orderPdf.headers['content-disposition']),/bon-commande-/);
  assert.equal(orderPdf.body.subarray(0,4).toString(),'%PDF');
  const[afterSale]=await query<RowDataPacket[]>('SELECT status FROM vehicles WHERE id=?',[vehicle!.id]);
  assert.equal(afterSale?.status,'reserved');
});
