import assert from'node:assert/strict';
import{randomUUID}from'node:crypto';
import{after,test}from'node:test';
import jwt from'jsonwebtoken';
import supertest from'supertest';
import{createApp}from'../src/app.js';
import{execute,pool,query,transaction}from'../src/config/database.js';
import type{RowDataPacket}from'mysql2/promise';
import{cancelUnpaidInvoice}from'../src/modules/billing/invoice-cancellation.service.js';

const enabled=process.env.LCA_SALE_CANCEL_DB_TEST==='1';
if(enabled)after(async()=>pool.end());

test('VENTE-ANNULATION-02 MySQL 8.4 : atomicité, refus financiers et concurrences',{skip:!enabled},async()=>{
 const insert=async(sql:string,params:unknown[]=[])=>String((await execute(sql,params)).insertId),suffix=randomUUID().slice(0,8),api=supertest(createApp());
 const concession=await insert('INSERT INTO concessions(name,code) VALUES(?,?)',[`Annulation ${suffix}`,`CAN-${suffix}`]);
 const agency=await insert('INSERT INTO agencies(concession_id,name,code) VALUES(?,?,?)',[concession,'Agence annulation',`CANA-${suffix}`]);
 const user=await insert('INSERT INTO users(agency_id,first_name,last_name,email,password_hash) VALUES(?,?,?,?,?)',[agency,'Audit','Annulation',`cancel-${suffix}@test.local`,'test']);
 const[role]=await query<RowDataPacket[]>("SELECT id FROM roles WHERE code='SUPER_ADMIN' AND is_system=TRUE");assert.ok(role);
 await pool.execute('INSERT INTO user_roles(user_id,role_id) VALUES(?,?)',[user,role.id]);
 const token=jwt.sign({sub:user,email:`cancel-${suffix}@test.local`,roles:['SUPER_ADMIN'],agencyId:agency},process.env.JWT_ACCESS_SECRET!),auth=(request:supertest.Test)=>request.set('Authorization',`Bearer ${token}`);
 const customerA=await insert('INSERT INTO customers(customer_code,agency_id,first_name,last_name) VALUES(?,?,?,?)',[`CA-${suffix}`,agency,'Client','A']);
 const customerB=await insert('INSERT INTO customers(customer_code,agency_id,first_name,last_name) VALUES(?,?,?,?)',[`CB-${suffix}`,agency,'Client','B']);
 const brand=await insert('INSERT INTO brands(name,code) VALUES(?,?)',[`Marque ${suffix}`,`B-${suffix}`]),model=await insert('INSERT INTO models(brand_id,name) VALUES(?,?)',[brand,`Modèle ${suffix}`]),version=await insert('INSERT INTO versions(model_id,name) VALUES(?,?)',[model,'Version']);
 const make=async(invoiceStatus?:'draft'|'issued'|'overdue',paid=0)=>{const vehicle=await insert("INSERT INTO vehicles(version_id,agency_id,vin,stock_number,status,sale_price,catalog_price) VALUES(?,?,?,?,'reserved',20000000,20000000)",[version,agency,`VIN${randomUUID().replaceAll('-','').slice(0,14)}`,`STK-${randomUUID().slice(0,8)}`]),sale=await insert("INSERT INTO sales(sale_number,customer_id,agency_id,salesperson_id,status,total,balance_due) VALUES(?,?,?,?, 'reserved',20000000,?)",[`V-${randomUUID().slice(0,8)}`,customerA,agency,user,20_000_000-paid]);await pool.execute('INSERT INTO sale_items(sale_id,vehicle_id,description,quantity,line_total) VALUES(?,?,?,1,20000000)',[sale,vehicle,'Véhicule']);await pool.execute("INSERT INTO reservations(reservation_number,customer_id,vehicle_id,sale_id,created_by,status) VALUES(?,?,?,?,?,'confirmed')",[`R-${randomUUID().slice(0,8)}`,customerA,vehicle,sale,user]);let invoice:string|undefined;if(invoiceStatus)invoice=await insert('INSERT INTO invoices(invoice_number,customer_id,agency_id,sale_id,invoice_type,status,issue_date,due_date,total,amount_paid,balance_due) VALUES(?,?,?,?,?,?,?,?,?,?,?)',[`F-${randomUUID().slice(0,8)}`,customerA,agency,sale,'vehicle',invoiceStatus,'2026-09-01','2026-09-02',20_000_000,paid,20_000_000-paid]);return{vehicle,sale,invoice}};
 for(const status of[undefined,'draft','issued','overdue']as const){const fixture=await make(status),response=await auth(api.patch(`/api/sales/${fixture.sale}/status`)).send({status:'cancelled',reason:'Annulation test'});assert.equal(response.status,200,JSON.stringify(response.body));const[sale]=await query<RowDataPacket[]>('SELECT status FROM sales WHERE id=?',[fixture.sale]),[vehicle]=await query<RowDataPacket[]>('SELECT status FROM vehicles WHERE id=?',[fixture.vehicle]),[reservation]=await query<RowDataPacket[]>('SELECT status FROM reservations WHERE sale_id=?',[fixture.sale]);assert.equal(sale.status,'cancelled');assert.equal(vehicle.status,'available');assert.equal(reservation.status,'cancelled');if(fixture.invoice){const[invoice]=await query<RowDataPacket[]>('SELECT status,balance_due FROM invoices WHERE id=?',[fixture.invoice]);assert.equal(invoice.status,'cancelled');assert.equal(Number(invoice.balance_due),0)}}
 const paid=await make('issued',5_000_000),method=(await query<RowDataPacket[]>('SELECT id FROM payment_methods LIMIT 1'))[0];await pool.execute("INSERT INTO payments(payment_number,invoice_id,customer_id,payment_method_id,amount,status) VALUES(?,?,?,?,5000000,'confirmed')",[`P-${randomUUID().slice(0,8)}`,paid.invoice,customerA,method.id]);const rejected=await auth(api.patch(`/api/sales/${paid.sale}/status`)).send({status:'cancelled',reason:'Interdit'});assert.equal(rejected.status,409);const[paidSale]=await query<RowDataPacket[]>('SELECT status FROM sales WHERE id=?',[paid.sale]),[paidVehicle]=await query<RowDataPacket[]>('SELECT status FROM vehicles WHERE id=?',[paid.vehicle]);assert.equal(paidSale.status,'reserved');assert.equal(paidVehicle.status,'reserved');
 const cancelled=await make(),cancelledResponse=await auth(api.patch(`/api/sales/${cancelled.sale}/status`)).send({status:'cancelled',reason:'Avant facture'});assert.equal(cancelledResponse.status,200);const forbiddenInvoice=await auth(api.post('/api/invoices')).send({agencyId:agency,customerId:customerA,saleId:cancelled.sale,invoiceType:'vehicle',issueDate:'2026-09-21',dueDate:'2026-10-21',idempotencyKey:`cancelled-${suffix}`,items:[{description:'Véhicule',quantity:1,unitPrice:20_000_000,discount:0}]});assert.equal(forbiddenInvoice.status,409,JSON.stringify(forbiddenInvoice.body));
 const concurrentPayment=await make('issued'),paymentKey=`pay-${randomUUID()}`;await Promise.allSettled([auth(api.patch(`/api/sales/${concurrentPayment.sale}/status`)).send({status:'cancelled',reason:'Concurrence paiement'}),auth(api.post(`/api/invoices/${concurrentPayment.invoice}/payments`)).send({paymentMethodId:String(method.id),amount:1_000_000,idempotencyKey:paymentKey})]);const[cpSale]=await query<RowDataPacket[]>('SELECT status FROM sales WHERE id=?',[concurrentPayment.sale]),[cpPayments]=await query<RowDataPacket[]>('SELECT COUNT(*) count FROM payments WHERE invoice_id=? AND status="confirmed"',[concurrentPayment.invoice]);assert.equal(cpSale.status==='cancelled'&&Number(cpPayments.count)>0,false);
 const concurrentInvoice=await make();await Promise.allSettled([auth(api.patch(`/api/sales/${concurrentInvoice.sale}/status`)).send({status:'cancelled',reason:'Concurrence facture'}),auth(api.post('/api/invoices')).send({agencyId:agency,customerId:customerA,saleId:concurrentInvoice.sale,invoiceType:'vehicle',issueDate:'2026-09-21',dueDate:'2026-10-21',idempotencyKey:`concurrent-${suffix}`,items:[{description:'Véhicule',quantity:1,unitPrice:20_000_000,discount:0}]})]);const[ciSale]=await query<RowDataPacket[]>('SELECT status FROM sales WHERE id=?',[concurrentInvoice.sale]),[activeInvoices]=await query<RowDataPacket[]>("SELECT COUNT(*) count FROM invoices WHERE sale_id=? AND status<>'cancelled'",[concurrentInvoice.sale]);assert.equal(ciSale.status==='cancelled'&&Number(activeInvoices.count)>0,false);
 const rollback=await make('issued');await assert.rejects(()=>transaction(async connection=>{await cancelUnpaidInvoice(connection,rollback.invoice!,'Rollback attendu',{userId:user,ip:null,userAgent:null});throw new Error('échec intermédiaire simulé')}));const[rollbackSale]=await query<RowDataPacket[]>('SELECT status FROM sales WHERE id=?',[rollback.sale]),[rollbackVehicle]=await query<RowDataPacket[]>('SELECT status FROM vehicles WHERE id=?',[rollback.vehicle]),[rollbackInvoice]=await query<RowDataPacket[]>('SELECT status FROM invoices WHERE id=?',[rollback.invoice]);assert.equal(rollbackSale.status,'reserved');assert.equal(rollbackVehicle.status,'reserved');assert.equal(rollbackInvoice.status,'issued');
 const resale=await insert("INSERT INTO sales(sale_number,customer_id,agency_id,salesperson_id,status,total,balance_due) VALUES(?,?,?,?, 'reserved',20000000,20000000)",[`V-${randomUUID().slice(0,8)}`,customerB,agency,user]);await pool.execute('INSERT INTO sale_items(sale_id,vehicle_id,description,quantity,line_total) VALUES(?,?,?,1,20000000)',[resale,cancelled.vehicle,'Revente']);const[available]=await query<RowDataPacket[]>('SELECT status FROM vehicles WHERE id=?',[cancelled.vehicle]);assert.equal(available.status,'available');
});
