import test from'node:test';import assert from'node:assert/strict';import{readFileSync}from'node:fs';import{money}from'../src/modules/workshop/warranty.service.js';
const route=readFileSync(new URL('../src/modules/workshop/workshop.routes.ts',import.meta.url),'utf8'),warranty=readFileSync(new URL('../src/modules/workshop/warranty.routes.ts',import.meta.url),'utf8'),service=readFileSync(new URL('../src/modules/workshop/warranty.service.ts',import.meta.url),'utf8'),migration=readFileSync(new URL('../database/migrations/046_sav_warranty_v1.sql',import.meta.url),'utf8'),report=readFileSync(new URL('../src/modules/reports/report.routes.ts',import.meta.url),'utf8');
test('GAR-01 OR normal inchangé',()=>assert.match(route,/decision_status==='APPROVED'/));
test('GAR-02 garantie déclarée',()=>assert.match(route,/warrantyIntent==='STUDY'/));
test('GAR-03 PENDING bloque démarrage',()=>assert.match(service,/decision_status==='PENDING'.*encore en attente/s));
test('GAR-04 APPROVED autorise selon workflow',()=>assert.match(service,/assertWarrantyMayStart/));
test('GAR-05 REJECTED ne finance rien',()=>assert.match(warranty,/DELETE FROM repair_order_warranty_allocations/));
test('GAR-06 garantie totale',()=>assert.match(warranty,/garantie totale doit couvrir chaque ligne à 100/));
test('GAR-07 garantie partielle',()=>assert.match(migration,/ENUM\('FULL','PARTIAL'\)/));
test('GAR-08 couverture mixte pièces et main-d’œuvre',()=>assert.match(migration,/repair_order_item_id BIGINT UNSIGNED NOT NULL UNIQUE/));
test('GAR-09 allocation supérieure à la ligne refusée',()=>assert.match(warranty,/share>total\+\.001/));
test('GAR-10 réel non confirmé bloque QC',()=>assert.match(route,/Complétez et validez le réel facturable/));
test('GAR-11 ventilation non confirmée bloque QC',()=>assert.match(service,/allocation_status!=='CONFIRMED'/));
test('GAR-12 ventilation et réel confirmés autorisent QC',()=>assert.match(route,/assertWarrantyReadyForQuality\(c,id\)/));
test('GAR-13 modification après verrou refusée',()=>assert.match(warranty,/quality_control.*ready.*invoiced.*delivered.*closed/));
test('GAR-14 stock pièce inchangé fonctionnellement',()=>assert.match(route,/UPDATE part_stocks SET current_stock=current_stock-/));
test('GAR-15 heures réelles conservées',()=>assert.match(route,/repair_order_items.*item_type/s));
test('GAR-16 facture client égale reste client',()=>assert.match(route,/customerHt:money\(line-manufacturerHt\)/));
test('GAR-17 garantie totale donne client zéro',()=>assert.equal(money(500000-500000),0));
test('GAR-18 créance constructeur correcte',()=>assert.match(route,/INSERT INTO warranty_claims/));
test('GAR-19 règlement partiel',()=>assert.match(warranty,/partially_paid/));
test('GAR-20 règlement complet',()=>assert.match(warranty,/balance<=\.001\?'paid'/));
test('GAR-21 surpaiement refusé',()=>assert.match(warranty,/dépasse le solde constructeur/));
test('GAR-22 remise sans paiement constructeur',()=>assert.doesNotMatch(route,/assertFinanciallySettled\([^)]*warranty/));
test('GAR-23 dette client bloque toujours',()=>assert.match(route,/assertFinanciallySettled\(invoices\[0\]\.balance_due,'atelier'\)/));
test('GAR-24 clôture OR préservée',()=>assert.match(route,/delivered:\['closed'\]/));
test('GAR-25 historique legacy non converti automatiquement',()=>{assert.match(migration,/LEGACY_UNALLOCATED/);assert.doesNotMatch(migration,/manufacturer_share_ht[^;]*SELECT/s)});
test('GAR-26 audit',()=>assert.match(service,/INSERT INTO audit_logs/));
test('GAR-27 concurrence allocation',()=>{assert.match(warranty,/expectedVersion/);assert.match(warranty,/FOR UPDATE/)});
test('GAR-28 concurrence paiement',()=>{assert.match(migration,/uk_wcp_request/);assert.match(warranty,/warranty_claims[^`]*FOR UPDATE/);assert.match(warranty,/dépasse le solde constructeur/)});
test('GAR-29 toute modification ou annulation du réel invalide la ventilation',()=>assert.ok((route.match(/invalidateWarrantyAllocation\(c,id,r\.user!\.sub\)/g)??[]).length>=3));
test('REP-WAR KPI et détail proviennent des données transactionnelles',()=>{assert.match(report,/reports\/warranties/);assert.match(report,/repair_order_warranty_allocations/);assert.match(report,/warranty_claims/)});
test('RBAC garantie reste dynamique et scope-aware',()=>{assert.match(warranty,/service\.warranty\.manage/);assert.match(warranty,/service\.warranty\.approve/);assert.doesNotMatch(service,/SUPER_ADMIN|roleCode/);assert.match(service,/CONCESSION/)});
test('RBAC règlement constructeur charge explicitement agence et conseiller de l’OR',()=>assert.match(warranty,/SELECT c\.\*,ro\.agency_id,ro\.advisor_id FROM warranty_claims/));
