import assert from 'node:assert/strict';
import {randomUUID} from 'node:crypto';
import {after,test} from 'node:test';
import supertest from 'supertest';
import type {ResultSetHeader,RowDataPacket} from 'mysql2/promise';
import {createApp} from '../src/app.js';
import {pool,query} from '../src/config/database.js';

const enabled=process.env.LCA_TARGETED_DB_TEST==='1';
if(enabled)after(async()=>{await pool.end()});
const rows=(sql:string,params:unknown[]=[])=>query<RowDataPacket[]>(sql,params);
const insert=async(sql:string,params:unknown[]=[])=>String((await pool.execute<ResultSetHeader>(sql,params))[0].insertId);

test('PR-01, SAV-OR-01 et SAV-OR-02 sur MySQL isolé', {skip:!enabled},async()=>{
  const api=supertest(createApp());
  const login=await api.post('/api/auth/login').send({email:process.env.ADMIN_EMAIL,password:process.env.ADMIN_PASSWORD});
  assert.equal(login.status,200,JSON.stringify(login.body));
  const token=login.body.accessToken;
  const auth=(request:supertest.Test)=>request.set('Authorization',`Bearer ${token}`);
  const suffix=randomUUID().slice(0,8);
  const [agency]=await rows('SELECT id FROM agencies LIMIT 1');
  const agencyId=String(agency.id);
  const category=await auth(api.post('/api/part-categories')).send({name:`Freinage ${suffix}`,code:`FREIN_${suffix}`,description:'Recette ciblée'});
  assert.equal(category.status,201,JSON.stringify(category.body));
  const categories=await auth(api.get('/api/part-categories'));
  assert.equal(categories.status,200);
  assert.ok(categories.body.some((item:RowDataPacket)=>String(item.id)===category.body.id));
  const references=await auth(api.get('/api/part-references').query({agencyId}));
  assert.equal(references.status,200);
  assert.ok(references.body.categories.some((item:RowDataPacket)=>String(item.id)===category.body.id));
  const part=await auth(api.post('/api/parts')).send({agencyId,reference:`QA-${suffix}`,name:'Plaquettes recette',categoryId:category.body.id});
  assert.equal(part.status,201,JSON.stringify(part.body));
  const persistedPart=await auth(api.get(`/api/parts/${part.body.id}`).query({agencyId}));
  assert.equal(persistedPart.status,200);
  assert.equal(String(persistedPart.body.category_id),category.body.id);
  const [savedPart]=await rows('SELECT category_id FROM parts WHERE id=?',[part.body.id]);
  assert.equal(String(savedPart.category_id),category.body.id);
  const badCategory=await auth(api.post('/api/parts')).send({agencyId,reference:`BAD-${suffix}`,name:'Pièce invalide',categoryId:'999999999'});
  assert.equal(badCategory.status,400);
  await auth(api.patch(`/api/part-categories/${category.body.id}`)).send({name:`Freinage ${suffix}`,code:`FREIN_${suffix}`,description:'Recette ciblée',isActive:false});
  const inactive=await auth(api.get('/api/part-references').query({agencyId}));
  assert.ok(!inactive.body.categories.some((item:RowDataPacket)=>String(item.id)===category.body.id));
  const [historical]=await rows('SELECT category_id FROM parts WHERE id=?',[part.body.id]);
  assert.equal(String(historical.category_id),category.body.id);
  const badInactive=await auth(api.post('/api/parts')).send({agencyId,reference:`INACTIVE-${suffix}`,name:'Pièce invalide',categoryId:category.body.id});
  assert.equal(badInactive.status,400);

  const [permission]=await rows("SELECT id FROM permissions WHERE code='service.order.receive'");
  const role=await insert('INSERT INTO roles(code,name,is_active,is_system) VALUES(?,?,TRUE,FALSE)',[`QA_SAV_${suffix}`,`Polyvalent ${suffix}`]);
  await pool.execute('INSERT INTO role_permissions(role_id,permission_id,scope) VALUES(?,? ,?)',[role,permission.id,'AGENCY']);
  const [admin]=await rows('SELECT password_hash FROM users WHERE email=?',[process.env.ADMIN_EMAIL]);
  const advisor=await insert('INSERT INTO users(agency_id,first_name,last_name,email,password_hash,is_active) VALUES(?,?,?,?,?,TRUE)',[agencyId,'Recette','Polyvalent',`advisor-${suffix}@example.test`,admin.password_hash]);
  await pool.execute('INSERT INTO user_roles(user_id,role_id) VALUES(?,?)',[advisor,role]);
  const candidate=await auth(api.get('/api/repair-orders/advisor-candidates').query({agencyId}));
  assert.equal(candidate.status,200,JSON.stringify(candidate.body));
  assert.ok(candidate.body.some((item:{id:string})=>item.id===advisor));
  assert.ok(!candidate.body.some((item:{id:string})=>item.id===String(login.body.user.id)));

  const emptyRole=await insert('INSERT INTO roles(code,name,is_active,is_system) VALUES(?,?,TRUE,FALSE)',[`QA_EMPTY_${suffix}`,`Magasinier ${suffix}`]);
  const unprivileged=await insert('INSERT INTO users(agency_id,first_name,last_name,email,password_hash,is_active) VALUES(?,?,?,?,?,TRUE)',[agencyId,'Recette','Sans permission',`empty-${suffix}@example.test`,admin.password_hash]);
  await pool.execute('INSERT INTO user_roles(user_id,role_id) VALUES(?,?)',[unprivileged,emptyRole]);
  const emptyLogin=await api.post('/api/auth/login').send({email:`empty-${suffix}@example.test`,password:process.env.ADMIN_PASSWORD});
  assert.equal(emptyLogin.status,200);
  const deniedCategory=await api.post('/api/part-categories').set('Authorization',`Bearer ${emptyLogin.body.accessToken}`).send({name:'Interdit',code:`DENIED_${suffix}`});
  assert.equal(deniedCategory.status,403);
  const brand=await insert('INSERT INTO brands(name,code) VALUES(?,?)',[`Marque ${suffix}`,`B-${suffix}`]);
  const model=await insert('INSERT INTO models(brand_id,name) VALUES(?,?)',[brand,`Modèle ${suffix}`]);
  const version=await insert('INSERT INTO versions(model_id,name) VALUES(?,?)',[model,'Standard']);
  const customerA=await insert('INSERT INTO customers(customer_code,agency_id,first_name,last_name) VALUES(?,?,?,?)',[`QA-A-${suffix}`,agencyId,'Client','A']);
  const customerB=await insert('INSERT INTO customers(customer_code,agency_id,first_name,last_name) VALUES(?,?,?,?)',[`QA-B-${suffix}`,agencyId,'Client','B']);
  const vehicle=async(n:number)=>insert('INSERT INTO vehicles(version_id,agency_id,vin) VALUES(?,?,?)',[version,agencyId,`QA${suffix}${n}`]);
  const vehicleA1=await vehicle(1),vehicleA2=await vehicle(2),vehicleB=await vehicle(3);
  for(const [customer,vehicleId,n] of [[customerA,vehicleA1,1],[customerA,vehicleA2,2],[customerB,vehicleB,3]] as const){
    const sale=await insert('INSERT INTO sales(sale_number,customer_id,agency_id) VALUES(?,?,?)',[`QA-S-${suffix}-${n}`,customer,agencyId]);
    await pool.execute('INSERT INTO sale_items(sale_id,vehicle_id,description) VALUES(?,?,?)',[sale,vehicleId,'Véhicule recette']);
  }
  const vehiclesA=await auth(api.get('/api/repair-orders/customer-vehicles').query({customerId:customerA}));
  assert.deepEqual(vehiclesA.body.map((item:{id:string})=>item.id).sort(),[vehicleA1,vehicleA2].sort());
  const vehiclesB=await auth(api.get('/api/repair-orders/customer-vehicles').query({customerId:customerB}));
  assert.deepEqual(vehiclesB.body.map((item:{id:string})=>item.id),[vehicleB]);
  const body={agencyId,customerId:customerA,vehicleId:vehicleA2,advisorId:advisor,complaint:'Contrôle recette',mileage:123};
  const deniedAdvisor=await auth(api.post('/api/repair-orders')).send({...body,advisorId:unprivileged});
  assert.equal(deniedAdvisor.status,400,JSON.stringify(deniedAdvisor.body));
  const forged=await auth(api.post('/api/repair-orders')).send({...body,vehicleId:vehicleB});
  assert.equal(forged.status,400,JSON.stringify(forged.body));
  const created=await auth(api.post('/api/repair-orders')).send(body);
  assert.equal(created.status,201,JSON.stringify(created.body));
  const reloaded=await auth(api.get(`/api/repair-orders/${created.body.id}`));
  assert.equal(reloaded.status,200,JSON.stringify(reloaded.body));
  assert.equal(String(reloaded.body.vehicle_id),vehicleA2);
  const [order]=await rows('SELECT customer_id,vehicle_id,advisor_id FROM repair_orders WHERE id=?',[created.body.id]);
  assert.equal(String(order.customer_id),customerA);
  assert.equal(String(order.vehicle_id),vehicleA2);
  assert.equal(String(order.advisor_id),advisor);
  const [home]=await rows('SELECT concession_id FROM agencies WHERE id=?',[agencyId]);
  const sisterAgency=await insert('INSERT INTO agencies(concession_id,name,code) VALUES(?,?,?)',[home.concession_id,`Agence sœur ${suffix}`,`SISTER_${suffix}`]);
  const second=await auth(api.post('/api/repair-orders')).send({...body,customerId:customerB,vehicleId:vehicleB,complaint:'Deuxième OR recette'});
  assert.equal(second.status,201,JSON.stringify(second.body));
  const secondReloaded=await auth(api.get(`/api/repair-orders/${second.body.id}`));
  assert.equal(secondReloaded.status,200);
  assert.equal(String(secondReloaded.body.customer_id),customerB);
  assert.equal(String(secondReloaded.body.vehicle_id),vehicleB);
  await pool.execute('UPDATE users SET agency_id=? WHERE id=?',[sisterAgency,advisor]);
  const agencyOnly=await auth(api.get('/api/repair-orders/advisor-candidates').query({agencyId}));
  assert.ok(!agencyOnly.body.some((item:{id:string})=>item.id===advisor));
  await pool.execute("UPDATE role_permissions SET scope='CONCESSION' WHERE role_id=? AND permission_id=?",[role,permission.id]);
  const concessionCandidates=await auth(api.get('/api/repair-orders/advisor-candidates').query({agencyId}));
  assert.ok(concessionCandidates.body.some((item:{id:string})=>item.id===advisor));
  const [group]=await rows('SELECT id FROM groups_company LIMIT 1');
  const otherConcession=await insert('INSERT INTO concessions(group_id,name,code) VALUES(?,?,?)',[group.id,`Concession externe ${suffix}`,`EXT_${suffix}`]);
  const externalAgency=await insert('INSERT INTO agencies(concession_id,name,code) VALUES(?,?,?)',[otherConcession,`Agence externe ${suffix}`,`EXA_${suffix}`]);
  await pool.execute('UPDATE users SET agency_id=? WHERE id=?',[externalAgency,advisor]);
  const concessionDenied=await auth(api.get('/api/repair-orders/advisor-candidates').query({agencyId}));
  assert.ok(!concessionDenied.body.some((item:{id:string})=>item.id===advisor));
  await pool.execute("UPDATE role_permissions SET scope='GLOBAL' WHERE role_id=? AND permission_id=?",[role,permission.id]);
  const globalCandidates=await auth(api.get('/api/repair-orders/advisor-candidates').query({agencyId}));
  assert.ok(globalCandidates.body.some((item:{id:string})=>item.id===advisor));
  await pool.execute('UPDATE roles SET is_active=FALSE WHERE id=?',[role]);
  const inactiveRole=await auth(api.get('/api/repair-orders/advisor-candidates').query({agencyId}));
  assert.ok(!inactiveRole.body.some((item:{id:string})=>item.id===advisor));
  await pool.execute('UPDATE roles SET is_active=TRUE WHERE id=?',[role]);
  await pool.execute('UPDATE users SET is_active=FALSE WHERE id=?',[advisor]);
  const withoutInactive=await auth(api.get('/api/repair-orders/advisor-candidates').query({agencyId}));
  assert.ok(!withoutInactive.body.some((item:{id:string})=>item.id===advisor));
});
