import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import test from 'node:test';
const source=(path:string)=>readFileSync(new URL(`../${path}`,import.meta.url),'utf8');
const route=source('src/modules/workshop/workshop.routes.ts'),frontend=source('../frontend/src/modules/service/RepairOrderDetailPage.tsx'),quick=source('../frontend/src/components/layout/QuickActionModal.tsx'),app=source('../frontend/src/App.tsx'),migration=source('database/legacy-migrations/030_service_order_workflow_permissions.sql'),seed=source('database/seeds/001_system_seed.sql');
const status=route.slice(route.indexOf('"/repair-orders/:id/status"'),route.indexOf('"/repair-orders/:id/inspection"')),handover=route.slice(route.indexOf("'/repair-orders/:id/handover'"),route.indexOf("'/repair-orders/:id/advisor'")),detail=route.slice(route.indexOf('async function detail'),route.indexOf('async function notify')),parts=route.slice(route.indexOf('"/repair-orders/:id/items"'),route.indexOf('"/repair-orders/:id/invoice"'));
const cases:Array<[string,()=>void]>=[
['SAV-01 no view',()=>assert.match(route,/serviceAccess\('service\.order\.view'\)/)],['SAV-02 OWN',()=>assert.match(route,/advisor_id=\?/)],['SAV-03 AGENCY',()=>assert.match(route,/permission==='AGENCY'/)],['SAV-04 CONCESSION',()=>assert.match(route,/permission==='CONCESSION'/)],['SAV-05 GLOBAL',()=>assert.match(route,/permission==='GLOBAL'/)],['SAV-06 no create',()=>assert.match(route,/serviceAccess\('service\.order\.create'\)/)],['SAV-07 create out of scope',()=>assert.match(route,/Client et véhicule doivent appartenir à la même agence/)],['SAV-08 no update',()=>assert.match(route,/serviceAccess\('service\.order\.update'\)/)],
['SAV-09 update OWN other advisor',()=>assert.match(route,/Périmètre SAV insuffisant/)],['SAV-10 no assign advisor',()=>assert.match(route,/serviceAccess\('service\.order\.assign_advisor'\)/)],['SAV-11 invalid advisor',()=>assert.match(route,/Conseiller SAV inactif, hors (?:agence|périmètre) ou sans capacité fonctionnelle/)],['SAV-12 no receive',()=>assert.match(route,/'planned:received':'service\.order\.receive'/)],['SAV-13 invalid transition',()=>assert.match(status,/Transition .* interdite/)],['SAV-14 no diagnose',()=>assert.match(route,/'received:diagnosis':'service\.order\.diagnose'/)],['SAV-15 diagnosis != approval',()=>assert.notEqual(route.indexOf("serviceAccess('service.order.diagnose')"),route.indexOf("serviceAccess('service.order.approve')"))],['SAV-16 no approve',()=>assert.match(route,/'waiting_approval:in_progress':'service\.order\.approve'/)],
['SAV-17 intervention without approval',()=>assert.match(status,/Validation client obligatoire/)],['SAV-18 no quality',()=>assert.match(route,/'in_progress:quality_control':'service\.order\.quality_control'/)],['SAV-19 incomplete quality',()=>assert.match(route,/Toutes les vérifications obligatoires doivent être validées/)],['SAV-20 no Billing create bypass',()=>assert.match(route,/requirePermission\('billing\.invoice\.create'\)/)],['SAV-21 no payment collect bypass',()=>assert.doesNotMatch(route,/billing\.payment\.collect/)],['SAV-22 financial details hidden',()=>assert.match(detail,/mayViewPayments\?await query/)],['SAV-23 positive balance blocks handover',()=>assert.match(handover,/assertFinanciallySettled/)],['SAV-24 no handover permission',()=>assert.match(handover,/serviceAccess\('service\.order\.handover'\)/)],
['SAV-25 handover no commercial vehicle delivery',()=>assert.doesNotMatch(handover,/UPDATE vehicles/)],['SAV-26 no close',()=>assert.match(route,/'delivered:closed':'service\.order\.close'/)],['SAV-27 close before handover',()=>assert.match(route,/'delivered:closed'/)],['SAV-28 closed immutable',()=>assert.match(route,/closed.*cancelled.*modification interdite/)],['SAV-29 cancel terminal refused',()=>assert.match(status,/invoiced.*delivered.*closed.*cancelled/)],['SAV-30 DIRECTOR no bypass',()=>assert.doesNotMatch(route,/DIRECTOR/)],['SAV-31 SERVICE_MANAGER no bypass',()=>assert.doesNotMatch(route,/SERVICE_MANAGER/)],['SAV-32 SERVICE_ADVISOR no bypass',()=>assert.doesNotMatch(route,/SERVICE_ADVISOR/)],
['SAV-33 SUPER_ADMIN',()=>assert.match(route,/isSuperAdmin/)],['SAV-34 unknown dynamic role',()=>assert.doesNotMatch(route,/roles\.includes|role ===/)],['SAV-35 frontend hidden actions',()=>assert.match(frontend,/can\("service\.order\.receive"\)/)],['SAV-36 direct API no bypass',()=>assert.match(route,/await assertPermission\(r,permission\)/)],['SAV-37 PDF document scope',()=>assert.match(route,/serviceAccess\('service\.documents\.view'\)/)],['SAV-38 customer 360 separation',()=>assert.doesNotMatch(route,/customers\.view.*service\.order\.view/)],['SAV-39 payment details separation',()=>assert.match(detail,/billing\.payment\.view/)],['SAV-40 transition history',()=>assert.match(status,/repair_order_status_history/)],
['SAV-41 update cannot receive',()=>assert.doesNotMatch(status,/service\.order\.update/)],['SAV-42 update cannot handover',()=>assert.doesNotMatch(handover,/service\.order\.update/)],['SAV-43 update cannot close',()=>assert.match(route,/'delivered:closed':'service\.order\.close'/)],['SAV-44 update cannot cancel',()=>assert.match(route,/nextStatus==='cancelled'\?'service\.order\.cancel'/)],['SAV-45 create cannot handover',()=>assert.doesNotMatch(handover,/service\.order\.create/)],['SAV-46 assignments independent',()=>{assert.match(route,/service\.order\.assign_advisor/);assert.match(route,/service\.order\.assign_technician/)}],['SAV-47 view masks amounts',()=>{assert.match(detail,/financially_cleared/);assert.match(frontend,/financiallyCleared/)}],['SAV-48 stock movement requires Parts',()=>{assert.match(parts,/requirePartsStockAccess/);assert.match(route,/await assertPermission\(r,'parts\.stock\.adjust'\)/)}],
];
for(const [name,run] of cases)test(name,run);
test('migration 030 est additive, idempotente et bootstrapée',()=>{assert.match(migration,/ON DUPLICATE KEY UPDATE/);assert.doesNotMatch(migration,/DROP|DELETE|TRUNCATE/);assert.match(seed,/service\.order\.receive/)});
test('navigation et Quick Action sont dynamiques',()=>{assert.match(quick,/service\.order\.create/);assert.match(app,/service:'service\.order\.view'/);assert.doesNotMatch(quick,/service\.create/)});
