import assert from 'node:assert/strict';
import {after,before,beforeEach,test} from 'node:test';
import request from 'supertest';
import {createApp} from '../src/app.js';
import {pool} from '../src/config/database.js';
import {RbacTestSessionFixture,type TestPermission} from './support/rbac-test-session.js';

type Visit={id:string;agency_id:string;assigned_user_id:string|null;greeted_by:string;status:string;outcome:string;arrival_at:string;assigned_at:string|null;visitor_name:string;lead_id:null;customer_id:null;vehicle_id:null;queue_number:number;wait_minutes:number};
const originalExecute=pool.execute.bind(pool),auth=new RbacTestSessionFixture(),app=createApp(),today=new Date().toISOString().slice(0,10),yesterday=new Date(Date.now()-86_400_000).toISOString().slice(0,10),users=['101','102','201'],agencies=['11','12','21'];
let visits:Visit[]=[];

function reset(){visits=Array.from({length:247},(_,index)=>{const id=index+1,isOld=id>237,status=['waiting','assigned','in_progress','completed','cancelled'][index%5]!,assigned=status==='waiting'||status==='cancelled'?null:users[index%3]!,arrival=`${isOld?yesterday:today} 09:${String(index%60).padStart(2,'0')}:00`;return{id:String(id),agency_id:agencies[index%3]!,assigned_user_id:assigned,greeted_by:users[index%3]!,status,outcome:status==='completed'?(index%10===3?'quotation':index%10===8?'sale':'follow_up'):'pending',arrival_at:arrival,assigned_at:assigned?arrival.replace('09:','09:10:'):null,visitor_name:`Visiteur ${id}`,lead_id:null,customer_id:null,vehicle_id:null,queue_number:id,wait_minutes:10}})}
const concession=(agency:string)=>agency==='21'?'C2':'C1';
function roleRows(userId:string){const role=auth.roles.get(auth.userRoles.get(userId)??'');return role?[{id:role.id,code:role.code,is_system:0}]:[]}
function scopeParamCount(sql:string){return sql.includes('sv.agency_id=? AND (sv.assigned_user_id=?')?3:sql.includes('sv.agency_id=?')||sql.includes('scoped_agency.concession_id=')?1:0}
function filtered(sql:string,params:unknown[]){const scopeCount=scopeParamCount(sql),fromIndex=scopeCount,hasFrom=sql.includes('sv.arrival_at>=?'),hasTo=sql.includes('sv.arrival_at<DATE_ADD(?,INTERVAL 1 DAY)'),from=hasFrom?String(params[fromIndex]):null,to=hasTo?String(params[fromIndex+(hasFrom?1:0)]):null;return visits.filter(visit=>{
  if(sql.includes('sv.agency_id=? AND (sv.assigned_user_id=?')&&!(visit.agency_id===String(params[0])&&(visit.assigned_user_id===String(params[1])||visit.assigned_user_id===null&&visit.greeted_by===String(params[2]))))return false;
  if(!sql.includes('sv.agency_id=? AND (sv.assigned_user_id=?')&&sql.includes('sv.agency_id=?')&&visit.agency_id!==String(params[0]))return false;
  if(sql.includes('scoped_agency.concession_id=')&&concession(visit.agency_id)!==concession(String(params[0])))return false;
  const day=visit.arrival_at.slice(0,10);if(sql.includes('CURRENT_DATE')&&day!==today)return false;if(from&&day<from)return false;if(to&&day>to)return false;return true;
})}
function summary(rows:Visit[]){const count=(status:string)=>rows.filter(row=>row.status===status).length,completed=count('completed'),transformed=rows.filter(row=>row.status==='completed'&&['lead_created','quotation','sale'].includes(row.outcome)).length;return{total:rows.length,waiting:count('waiting'),assigned:count('assigned'),in_progress:count('in_progress'),completed,cancelled:count('cancelled'),average_wait_minutes:rows.some(row=>row.assigned_at)?10:null,active_advisors:new Set(rows.filter(row=>['assigned','in_progress'].includes(row.status)).map(row=>row.assigned_user_id).filter(Boolean)).size,transformed,quotations:rows.filter(row=>row.status==='completed'&&row.outcome==='quotation').length}}
function decorated(row:Visit){return{...row,origin:'showroom',phone:null,reason:'Recette',preferred_model:null,assigned_user_name:null,greeted_by_name:null,vehicle_label:null,active_test_drive_id:null,active_test_drive_mileage:null,can_start_test_drive:1}}

before(()=>{for(const [index,id] of agencies.entries())auth.addAgency({id,concessionId:index===2?'C2':'C1'});(pool as any).execute=async(sql:string,params:unknown[]=[])=>{
  if(sql.includes('JOIN refresh_tokens rt'))return[auth.authRows(params),[]];
  if(sql.includes('SELECT r.id,r.code,r.is_system FROM users u JOIN user_roles'))return[roleRows(String(params[0])),[]];
  if(sql.includes('SELECT p.code,rp.scope FROM role_permissions'))return[auth.roles.get(String(params[0]))?.permissions??[],[]];
  if(sql.includes('SELECT DISTINCT o.lead_id FROM opportunities o'))return[[],[]];
  if(sql.startsWith('SELECT COUNT(*) total')&&sql.includes('FROM showroom_visits sv'))return[[summary(filtered(sql,params))],[]];
  if(sql.includes('FROM showroom_visits sv')){const rows=filtered(sql,params).sort((a,b)=>['waiting','assigned','in_progress','completed','cancelled'].indexOf(a.status)-['waiting','assigned','in_progress','completed','cancelled'].indexOf(b.status)||a.arrival_at.localeCompare(b.arrival_at)||Number(a.id)-Number(b.id)),limit=Number(params.at(-2)),offset=Number(params.at(-1));return[rows.slice(offset,offset+limit).map(decorated),[]]}
  return[[],[]];
}});
after(()=>{(pool as any).execute=originalExecute});beforeEach(reset);
function bearer(scope:TestPermission['scope'],userId='101',agencyId='11'){return`Bearer ${auth.createRbacTestSession({user:{id:userId,agencyId},roleCode:`SHOWROOM_PAG_${scope}_${Date.now()}_${Math.random()}`,permissions:[{code:'showroom.view',scope}]}).accessToken}`}
const get=(query='',scope:TestPermission['scope']='GLOBAL')=>request(app).get(`/api/showroom${query}`).set('Authorization',bearer(scope));

test('PAG6-01 applique pageSize=6 par défaut et ne rend jamais plus de six visites',async()=>{const first=await get('');assert.deepEqual([first.status,first.body.page,first.body.pageSize,first.body.total,first.body.totalPages,first.body.items.length],[200,1,6,237,40,6]);assert.ok(first.body.items.length<=6)});
test('PAG6-02 répartit sept résultats en pages de six puis un',async()=>{visits=visits.filter(row=>row.arrival_at.startsWith(today)).slice(0,7);const first=await get(''),second=await get('?page=2');assert.deepEqual([first.body.total,first.body.totalPages,first.body.items.length,second.body.items.length],[7,2,6,1])});
test('PAG6-03 répartit quinze résultats sur trois pages',async()=>{visits=visits.filter(row=>row.arrival_at.startsWith(today)).slice(0,15);const last=await get('?page=3');assert.deepEqual([last.body.total,last.body.totalPages,last.body.items.length],[15,3,3])});
test('PAG-06/12/13 conserve un tri stable sans doublon ni omission',async()=>{const pages=await Promise.all(Array.from({length:40},(_,index)=>get(`?page=${index+1}`)));const ids=pages.flatMap(response=>response.body.items.map((item:{id:string})=>item.id));assert.equal(ids.length,237);assert.equal(new Set(ids).size,237);assert.deepEqual(ids.slice(0,3),['1','61','121'])});
test('PAG-07/08 valide strictement page et pageSize',async()=>{for(const query of['?page=0','?page=-1','?page=x','?page=1.5','?pageSize=0','?pageSize=-2','?pageSize=x','?pageSize=2.5'])assert.equal((await get(query)).status,400,query)});
test('PAG-09/10/11 borne pageSize, clamp une page hors plage et gère zéro résultat',async()=>{const max=await get('?all=true&pageSize=500'),clamped=await get('?page=999');assert.equal(max.body.pageSize,100);assert.equal(max.body.items.length,100);assert.equal(clamped.body.page,40);visits=[];const empty=await get('?all=true&page=8');assert.deepEqual([empty.body.page,empty.body.totalPages,empty.body.total,empty.body.items.length],[1,0,0,0])});
test('COUNT-01..06 et METRIC-01..05 restent globaux indépendamment de la page',async()=>{const response=await get('?pageSize=2'),expected=summary(visits.filter(row=>row.arrival_at.startsWith(today)));assert.deepEqual(response.body.counts,{waiting:expected.waiting,assigned:expected.assigned,inProgress:expected.in_progress,completed:expected.completed,cancelled:expected.cancelled});assert.deepEqual(response.body.metrics,{total:237,waiting:expected.waiting,inProgress:expected.assigned+expected.in_progress,completed:expected.completed,averageWaitMinutes:10,activeAdvisors:expected.active_advisors,conversionRate:Math.round(expected.transformed/expected.completed*100),quotations:expected.quotations})});
test('FILTER-01..06 recalcule items, total, counts et metrics pour aujourd’hui, all et from/to',async()=>{const current=await get(''),all=await get('?all=true'),old=await get(`?from=${yesterday}&to=${yesterday}`);assert.deepEqual([current.body.total,all.body.total,old.body.total],[237,247,10]);assert.equal(Object.values(old.body.counts).reduce((sum,value)=>sum+Number(value),0),10);assert.equal(old.body.metrics.total,10)});
test('SCOPE-01..07 applique le scope avant total, counts et pagination',async()=>{for(const scope of['OWN','AGENCY','CONCESSION','GLOBAL']as const){const response=await get('?all=true&pageSize=5',scope),sql=scope==='OWN'?'sv.agency_id=? AND (sv.assigned_user_id=?':scope==='AGENCY'?'sv.agency_id=?':scope==='CONCESSION'?'scoped_agency.concession_id=':'1=1',params=scope==='OWN'?['11','101','101']:scope==='GLOBAL'?[]:['11'],expected=filtered(sql,params);assert.equal(response.body.total,expected.length,scope);assert.equal(Object.values(response.body.counts).reduce((sum,value)=>sum+Number(value),0),expected.length,scope);assert.ok(response.body.items.every((item:{agencyId:string})=>scope==='GLOBAL'?true:scope==='CONCESSION'?item.agencyId!=='21':item.agencyId==='11'),scope)}});
