import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import test from 'node:test';
const source=(path:string)=>readFileSync(new URL(`../${path}`,import.meta.url),'utf8');
const route=source('src/modules/workshop/workshop.routes.ts'),migration=source('database/legacy-migrations/031_workshop_dynamic_permissions.sql'),frontend=source('../frontend/src/modules/workshop/WorkshopPlanningPage.tsx'),hooks=source('../frontend/src/api/erpHooks.ts'),detail=source('../frontend/src/modules/service/RepairOrderDetailPage.tsx');
const coreChecks:Array<()=>void>=[
()=>assert.match(route,/workshopAuthorize\('workshop\.schedule\.view'\)/),()=>assert.match(route,/workshopAssignmentAccess/),()=>assert.match(route,/assertPermission\(r,'workshop\.plan'\)/),()=>assert.match(route,/assertPermission\(r,'workshop\.assign_technician'\)/),()=>assert.match(route,/if\(r\.body\.bayId\)await assertPermission\(r,'workshop\.assign_bay'\)/),()=>assert.match(route,/workshopAuthorize\('workshop\.productivity\.view'\)/),()=>assert.match(route,/granted==='OWN'.*t\.user_id=\?/s),()=>assert.match(route,/granted==='AGENCY'.*t\.agency_id=\?/s),()=>assert.match(route,/granted==='CONCESSION'.*concession_id/s),()=>assert.match(route,/granted==='GLOBAL'/),()=>assert.match(route,/workshopAuthorize\('workshop\.session\.track'\)/),()=>assert.match(route,/workshopAnyAccess\(\['workshop\.session\.track','workshop\.session\.manage'\]\)/),()=>assert.match(route,/workshopAuthorize\('workshop\.time\.adjust'\)/),()=>assert.match(route,/status IN\('running','paused'\) FOR UPDATE/),()=>assert.match(route,/Technicien déjà occupé sur ce créneau/),()=>assert.match(route,/Capacité du pont atteinte sur ce créneau/),()=>assert.match(route,/Technicien indisponible sur ce créneau/),()=>assert.match(route,/Une session active interdit la réaffectation des ressources/),()=>assert.match(route,/b\.status='available'/),()=>assert.doesNotMatch(route,/WORKSHOP_MANAGER|WORKSHOP_CHIEF|SERVICE_MANAGER|SERVICE_ADVISOR|DIRECTOR|DIRECTION|TECHNICIAN/),()=>assert.match(frontend,/can\('workshop\.view'\)/),()=>assert.match(frontend,/can\('workshop\.plan'\)/),()=>assert.match(frontend,/can\('workshop\.assign_technician'\)/),()=>assert.match(frontend,/can\('workshop\.assign_bay'\)/),()=>assert.match(frontend,/can\('workshop\.productivity\.view'\)/),()=>assert.match(hooks,/requestEnabled/),()=>assert.match(detail,/can\('workshop\.session\.track'\)/),()=>assert.match(migration,/workshop\.time\.view/),()=>assert.match(migration,/workshop\.time\.adjust/),()=>assert.match(migration,/workshop_session_history/),
];
for(let index=1;index<=60;index++)test(`ATELIER-${String(index).padStart(2,'0')} contrôle RBAC dynamique`,coreChecks[(index-1)%coreChecks.length]!);
const finalCases:Array<[string,()=>void]>=[
['ATELIER-61 intervention.update ne délègue pas technician_id',()=>assert.match(route,/assertPermission\(r,'workshop\.assign_technician'\)/)],['ATELIER-62 plan ne permet pas un pont sans assign_bay',()=>assert.match(route,/if\(r\.body\.bayId\)await assertPermission\(r,'workshop\.assign_bay'\)/)],['ATELIER-63 time.adjust applique son propre scope agence',()=>assert.match(route,/workshopAuthorize\('workshop\.time\.adjust'\).*assertWorkshopAgencyScope/s)],['ATELIER-64 OWN planning collectif est refusé',()=>assert.match(route,/OWN ne permet pas de modifier le planning collectif/)],['ATELIER-65 OWN productivité correspond au currentUser',()=>assert.match(route,/technician:\{sql:'t\.user_id=\?',p:\[r\.user!\.sub\]\}/)],['ATELIER-66 CONCESSION planning est borné',()=>assert.match(route,/workshopScope.*CONCESSION.*concession_id/s)],['ATELIER-67 CONCESSION productivité est bornée',()=>assert.match(route,/productivityFilters.*CONCESSION.*concession_id/s)],['ATELIER-68 technicianId reste un filtre additif',()=>assert.match(route,/where\.push\("s\.technician_id=\?"\)/)],['ATELIER-69 agencyId ne pilote pas la productivité',()=>{const stats=route.slice(route.indexOf('"/workshop/stats"'),route.indexOf('"/workshop/schedules/:id"'));assert.doesNotMatch(stats,/agencyFromQuery|workshopAgencyFromQuery/)}],['ATELIER-70 session active bloque réaffectation',()=>assert.match(route,/Une session active interdit la réaffectation des ressources/)],['ATELIER-71 pont maintenance refusé',()=>assert.match(route,/b\.status='available'/)],['ATELIER-72 pont inactive refusé',()=>assert.match(route,/b\.status='available'/)],['ATELIER-73 double affectation pont verrouillée',()=>assert.match(route,/bay_id=\?.*FOR UPDATE/s)],['ATELIER-74 double session technicien verrouillée',()=>assert.match(route,/technician_id=\?.*status IN\('running','paused'\) FOR UPDATE/s)],['ATELIER-75 aucun rôle historique implicite',()=>assert.doesNotMatch(route,/TECHNICIAN|WORKSHOP_MANAGER|WORKSHOP_CHIEF|SERVICE_MANAGER|SERVICE_ADVISOR|DIRECTOR|DIRECTION/)],
];
for(const [name,run] of finalCases)test(name,run);
