import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {test} from 'node:test';
const read=(path:string)=>readFileSync(new URL(path,import.meta.url),'utf8');

test('COM-01 Perdu utilise une modale contrôlée et non window.prompt',()=>{const crm=read('../src/modules/crm/CrmPage.tsx');assert.doesNotMatch(crm,/window\.prompt/);assert.match(crm,/Marquer l’opportunité comme perdue/);assert.match(crm,/Le motif de perte est obligatoire/);assert.match(crm,/lostReason:lostReason\.trim\(\)/)});
test('COM-02 les étapes structurantes sont produites par des actions métier',()=>{const crm=read('../src/modules/crm/CrmPage.tsx'),creation=read('../src/modules/crm/NewLeadModal.tsx');assert.match(creation,/<select value=\{formData\.stage\} disabled/);assert.match(crm,/Planifier un RDV/);assert.match(crm,/Créer un devis/);assert.match(crm,/Entrer en négociation/);assert.doesNotMatch(crm,/stages\.map\(\(s\).*<option/s)});
test('COM-03/05 le devis précharge l’opportunité et la vente transmet les deux FK',()=>{const quote=read('../src/modules/crm/QuotationModal.tsx'),sale=read('../src/modules/sales/SaleWizardModal.tsx');assert.match(quote,/opportunityId:lead\.opportunityId/);assert.match(quote,/sellingPriceTTC/);assert.match(sale,/opportunityId:initialOpportunityId/);assert.match(sale,/quotationId:initialQuotationId/)});
test('COM-04 le SALES_AGENT ne voit pas le sélecteur et la liste exclut direction/admin',()=>{const sale=read('../src/modules/sales/SaleWizardModal.tsx');assert.match(sale,/!isSalesAgent&&<label[^>]*>Commercial actif/);assert.match(sale,/\['SALES_REP','SALES_MANAGER'\]/);assert.doesNotMatch(sale,/\['SALES_REP','SALES_MANAGER','DIRECTION'/)});
test('COM-06/07 la fiche permet l’édition et affiche la vraie timeline',()=>{const crm=read('../src/modules/crm/CrmPage.tsx');assert.match(crm,/Modifier le prospect/);assert.match(crm,/useUpdateLead/);assert.match(crm,/useLeadActivitiesQuery/);assert.match(crm,/activity\.assignedUserName/);assert.match(crm,/Notes initiales/)});
test('COM-10 les mutations importantes exposent chargement et anti double clic',()=>{const crm=read('../src/modules/crm/CrmPage.tsx'),quote=read('../src/modules/crm/QuotationModal.tsx'),sale=read('../src/modules/sales/SaleWizardModal.tsx');assert.match(crm,/activityMutation\.isPending/);assert.match(quote,/create\.isPending/);assert.match(sale,/createSale\.isPending/)});
test('COM-09 la GED filtre les entités et types documentaires avec une politique partagée',()=>{const page=read('../src/modules/documents/DocumentsGedPage.tsx'),policy=read('../src/modules/documents/documentPolicy.ts');assert.match(page,/documentEntitiesForRoles/);assert.match(page,/documentTypesForRoles/);assert.match(policy,/SALES_REP/);assert.match(policy,/type!==\'Facture fournisseur\'\|\|allowed\.has\(\'supplier\'\)/)});
test('le Showroom désactive un essai CRM sans rendez-vous et préserve les essais hors CRM',()=>{const page=read('../src/modules/showroom/ShowroomPage.tsx'),hooks=read('../src/api/erpHooks.ts');assert.match(page,/Boolean\(visit\.leadId\)&&!visit\.canStartTestDrive/);assert.match(page,/Planifiez d’abord un rendez-vous/);assert.match(hooks,/canStartTestDrive: Boolean\(r\.canStartTestDrive\)/)});
test('les vues devis distinguent le propriétaire commercial du créateur',()=>{const crm=read('../src/modules/crm/CrmPage.tsx'),customer=read('../src/modules/customers/CustomerDetailPage.tsx');for(const page of [crm,customer]){assert.match(page,/Commercial :/);assert.match(page,/Créé par :/)}});
