import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { test } from 'node:test';

const read=(path:string)=>readFileSync(new URL(path,import.meta.url),'utf8');

test('le formulaire CRM possède un état initial vierge et un reset explicite',()=>{const modal=read('../src/modules/crm/NewLeadModal.tsx');assert.match(modal,/INITIAL_LEAD_FORM/);assert.match(modal,/targetBudget:''/);assert.match(modal,/const resetForm=/);assert.match(modal,/if\(!isOpen\)resetForm/);assert.match(modal,/resetForm\(\);onClose\(\)/)});
test('le reset arrive seulement après le succès et une erreur conserve la saisie',()=>{const modal=read('../src/modules/crm/NewLeadModal.tsx'),success=modal.indexOf("type:'success'"),reset=modal.indexOf('resetForm();onClose()',success),failure=modal.indexOf('catch(error)');assert.ok(success>0&&reset>success&&failure>reset);assert.doesNotMatch(modal.slice(failure),/resetForm\(/)});
test('un nouveau prospect commence exclusivement à l’étape Nouveau et l’affectation reste facultative',()=>{const modal=read('../src/modules/crm/NewLeadModal.tsx');assert.match(modal,/opportunityStageToDb\[formData\.stage\]/);assert.match(modal,/assignedUserId:formData\.assignedUserId\|\|undefined/);assert.match(modal,/<option value="">À affecter<\/option>/);assert.match(modal,/eligibleShowroomSalesUsers/);assert.match(modal,/<select value=\{formData\.stage\} disabled/);assert.match(modal,/<option value="NOUVEAU">Nouveau<\/option>/);for(const stage of ['CONTACTE','QUALIFIE','RDV','ESSAI'])assert.doesNotMatch(modal,new RegExp(`value="${stage}"`))});
test('la validation contrôlée conserve téléphone et email avec messages français',()=>{const modal=read('../src/modules/crm/NewLeadModal.tsx');assert.match(modal,/<form noValidate/);assert.match(modal,/Le prénom est obligatoire/);assert.match(modal,/Le numéro de téléphone n’est pas valide/);assert.match(modal,/L’adresse e-mail n’est pas valide/);assert.match(modal,/value=\{formData\.phone\}/);assert.match(modal,/value=\{formData\.email\}/);assert.match(modal,/disabled=\{createLead\.isPending\}/)});
test('aucun budget ou score fictif n’est envoyé',()=>{const modal=read('../src/modules/crm/NewLeadModal.tsx');assert.doesNotMatch(modal,/35000/);assert.doesNotMatch(modal,/probability\s*:\s*75/);assert.match(modal,/expectedValue:formData\.targetBudget===''\?undefined/)});
test('la recherche reste contrôlée, temporisée et combinable à la priorité',()=>{const page=read('../src/modules/crm/CrmPage.tsx'),hooks=read('../src/api/erpHooks.ts');assert.match(page,/value=\{searchQuery\}/);assert.match(page,/setDebouncedSearch\(searchQuery\.trim\(\)\),350/);assert.match(page,/useLeadsQuery\(debouncedSearch, selectedPriority/);assert.match(hooks,/params\.set\("search", search\)/);assert.match(page,/Aucun prospect ne correspond à vos critères/)});
test('un prospect sans commercial possède un libellé métier explicite',()=>{const hooks=read('../src/api/erpHooks.ts');assert.match(hooks,/assignedToName: r\.assignedUserName\?\.trim\(\) \|\| "À affecter"/)});
