import assert from'node:assert/strict';
import{readFileSync}from'node:fs';
import{test}from'node:test';
const read=(path:string)=>readFileSync(new URL(path,import.meta.url),'utf8');

test('DEL-27..30 frontend piloté par permissions dynamiques',()=>{const files=read('../src/modules/deliveries/DeliveriesPage.tsx')+read('../src/modules/deliveries/DeliveryDetailPage.tsx')+read('../src/modules/deliveries/NewDeliveryModal.tsx');assert.doesNotMatch(files,/DELIVERY_MANAGER|DIRECTOR|SALES_MANAGER|SALES_REP|ACCOUNTANT|roles\.includes/);for(const code of ['delivery.view','delivery.schedule','delivery.prepare','delivery.checklist.manage','delivery.complete','delivery.cancel'])assert.match(files,new RegExp(code.replaceAll('.','\\.')))});
test('DEL-CAND le formulaire charge les responsables éligibles pour la vente et refuse une sélection périmée',()=>{const modal=read('../src/modules/deliveries/NewDeliveryModal.tsx'),hooks=read('../src/api/erpHooks.ts');assert.match(modal,/useDeliverySpecialistsQuery\(saleId/);assert.match(modal,/specialists\.find\(user=>user\.id===deliverySpecialistId\)/);assert.match(modal,/!selectedSpecialist/);assert.match(modal,/required value=\{deliverySpecialistId\}/);assert.doesNotMatch(modal,/auth\.currentAgency\?\.id/);assert.match(hooks,/deliveries\/candidates\/\$\{saleId\}\/specialists/)});
test('DEL checklist affiche et verrouille chaque phase',()=>{const page=read('../src/modules/deliveries/DeliveryDetailPage.tsx');assert.match(page,/preparation:'Préparation',quality:'Contrôle qualité',handover:'Remise client'/);assert.match(page,/activePhase\[delivery\.status\]!==category/);assert.match(page,/!canChecklist\|\|readOnly/);assert.match(page,/Checklist de contrôle qualité incomplète/)});
test('DEL signature exige capture et finalisation, bloque le double clic',()=>{const page=read('../src/modules/deliveries/DeliveryDetailPage.tsx');assert.match(page,/canSign&&canComplete/);assert.match(page,/signLock\.current/);assert.match(page,/loading=\{signMutation\.isPending\}/);assert.match(page,/disabled=\{signDisabled\|\|signMutation\.isPending\}/)});
test('DEL documents et finance respectent leurs permissions propres',()=>{const page=read('../src/modules/deliveries/DeliveryDetailPage.tsx');assert.match(page,/canDocumentsView=can\('delivery\.documents\.view'\)/);assert.match(page,/canViewPayments=can\('billing\.payment\.view'\)/);assert.match(page,/Règlement validé/);assert.match(page,/received:false/)});
test('DEL annulation utilise action et permission dédiées',()=>{const page=read('../src/modules/deliveries/DeliveryDetailPage.tsx'),hooks=read('../src/api/erpHooks.ts'),map=read('../src/services/mysqlStatusMap.ts');assert.match(page,/canCancel=can\('delivery\.cancel'\)/);assert.match(hooks,/deliveries\/\$\{deliveryId\}\/cancel/);assert.match(map,/cancelled: 'ANNULE'/)});
