import assert from'node:assert/strict';
import{readFileSync}from'node:fs';
import test from'node:test';
const source=(value:string)=>readFileSync(new URL(`../${value}`,import.meta.url),'utf8');
const component=source('src/modules/documents/DocumentPreview.tsx'),ged=source('src/modules/documents/DocumentsGedPage.tsx'),vehicle=source('src/modules/vehicles/VehicleDetailPage.tsx');
test('UI-DOC-01/02 Visionner ouvre le composant commun',()=>{assert.match(ged,/>Visionner</);assert.match(ged,/setPreview\(d\)/);assert.match(ged,/<DocumentPreview/)});
test('UI-DOC-03/04 PDF et images utilisent une source backend sécurisée',()=>{assert.match(component,/\/documents\/\$\{document.id\}\/preview/);assert.match(component,/<iframe/);assert.match(component,/<img/)});
test('UI-DOC-05/06 chargement, erreur et format non supporté sont explicites',()=>{assert.match(component,/Chargement de l’aperçu/);assert.match(component,/role="alert"/);assert.match(component,/Aperçu indisponible pour ce format/)});
test('UI-DOC-07 téléchargement et fermeture restent disponibles',()=>{assert.match(component,/>Télécharger</);assert.match(component,/>Fermer</);assert.match(ged,/\/documents\/\$\{d.id\}\/download/)});
test('UI-DOC-09/10 la visionneuse est une modal indépendante de la liste',()=>{assert.match(component,/onClose/);assert.match(component,/URL.revokeObjectURL/);assert.match(ged,/useDocumentsQuery/)});
test('UI-DOC-10 la fiche véhicule réutilise la visionneuse commune',()=>{assert.match(vehicle,/DocumentPreview/);assert.match(vehicle,/>Visionner</)});
