import assert from'node:assert/strict';import{readFileSync}from'node:fs';import test from'node:test';const read=(path:string)=>readFileSync(new URL(path,import.meta.url),'utf8'),section=read('../src/modules/hr/EmployeeLeavesSection.tsx'),record=read('../src/modules/hr/EmployeeRecordModal.tsx'),list=read('../src/modules/hr/LeavesAdministration.tsx'),types=read('../src/modules/hr/LeaveTypesManager.tsx'),hooks=read('../src/api/hrHooks.ts');
test('UI-HR11B-01..04 fiche, employé autonome ou lié et création',()=>{assert.match(record,/EmployeeLeavesSection/);assert.match(section,/Congés & absences/);assert.match(section,/employee\.id/);assert.doesNotMatch(section,/password|roleId/);assert.match(section,/actions\.createLeave/)});
test('UI-HR11B-05..08 types actifs, dates, motif et GED sensible',()=>{assert.match(section,/useLeaveTypesQuery[\s\S]*true/);assert.match(section,/startDate/);assert.match(section,/endDate/);assert.match(section,/reason/);assert.match(section,/employee_leave/);assert.match(section,/Justificatifs sensibles/)});
test('UI-HR11B-09..14 transitions, historique et type inactif',()=>{for(const value of['Soumettre','Approuver','Refuser','Annuler','type inactif historique'])assert.match(section,new RegExp(value,'i'));for(const path of['submit','approve','reject','cancel'])assert.match(hooks,new RegExp(`/hr/leaves/\\$\\{id\\}/${path}`))});
test('UI-HR11B-15..17 OWN, anti auto-approbation et permissions',()=>{assert.match(section,/hr\.leave\.request/);assert.match(section,/employee\.user_id!==currentUserId/);assert.match(section,/hr\.leave\.approve/);assert.match(section,/hr\.leave\.manage/)});
test('UI-HR11B-18..19 filtres, pagination et état vide',()=>{for(const value of['status','leaveTypeId','agencyId','from','to','pageSize'])assert.match(list,new RegExp(value));assert.match(list,/Précédent/);assert.match(list,/Suivant/);assert.match(list,/Aucune absence/);assert.match(hooks,/\/hr\/leaves\?/)});
test('UI-HR11B-20 aucun faux solde et durée strictement calendaire',()=>{assert.match(section,/durée affichée est calendaire/i);assert.match(list,/calendaires/);assert.doesNotMatch(`${section}\n${list}`,/solde restant|jours acquis|jours disponibles|jours consommés juridiquement/i)});
test('UI-HR11B-21..22 confidentialité et design ERP',()=>{assert.match(list,/ne sont pas exposés dans cette liste générale/);assert.doesNotMatch(list,/fileName|DocumentPreview|reason/);assert.match(section,/rounded-md border/);assert.match(types,/rounded border/)});
test('UI-HR11B types configurables et désactivation historique',()=>{assert.match(types,/Configurer les types de congé/);assert.match(types,/Désactiver/);assert.match(types,/Réactiver/);assert.match(types,/requiresDocument/);assert.match(types,/Aucun type configuré/)});
