import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { test } from 'node:test';

const read=(path:string)=>readFileSync(new URL(path,import.meta.url),'utf8');

test('le formulaire bloque VIN invalide, traitement image et double clic',()=>{const modal=read('../src/modules/vehicles/NewVehicleModal.tsx'),vin=read('../src/modules/vehicles/vehicleVin.ts');assert.match(vin,/\^\[A-HJ-NPR-Z0-9\]\{17\}\$/);assert.match(modal,/isProcessingImages/);assert.match(modal,/finally\{setIsProcessingImages\(false\)/);assert.match(modal,/createVehicle\.isPending/);assert.match(modal,/Le VIN doit comporter exactement 17 caractères valides/)});
test('VEH-STOCK-UX-01 limite aussi l’état VIN et le payload lors d’une saisie ou d’un collage long',async()=>{const {normalizeVinInput,VIN_PATTERN}=await import('../src/modules/vehicles/vehicleVin.ts');const valid='WBA12345678901234',typed=normalizeVinInput(`${valid}X`),pasted=normalizeVinInput(`  ${valid}XYZ  `);assert.equal(typed,valid);assert.equal(typed.length,17);assert.equal(pasted,valid);assert.equal(pasted.length,17);assert.equal(VIN_PATTERN.test(typed),true);const modal=read('../src/modules/vehicles/NewVehicleModal.tsx');assert.match(modal,/vin:normalizedVin/)});
test('la création annonce le statut Réceptionné et garde le doublon VIN dans le formulaire',()=>{const modal=read('../src/modules/vehicles/NewVehicleModal.tsx');assert.match(modal,/statut « Réceptionné »/);assert.doesNotMatch(modal,/disponible dans le catalogue/);assert.match(modal,/setVinError\(message\)/);assert.match(modal,/vinRef\.current\?\.focus/)});
test('les filtres couvrent Réceptionné et En transit et les KPI viennent du backend',()=>{const page=read('../src/modules/vehicles/VehiclesListPage.tsx');assert.match(page,/<option value="RECEPTIONNE">Réceptionné<\/option>/);assert.match(page,/<option value="EN_TRANSIT">En transit<\/option>/);assert.match(page,/useVehicleStatsQuery/);assert.doesNotMatch(page,/const availableCount = vehicles\.filter/);assert.match(page,/Aucun véhicule ne correspond à vos critères/);assert.match(page,/:\s*'Aucun véhicule'/)});
test('le détail expose une modification autorisée et les images ont un fallback',()=>{const detail=read('../src/modules/vehicles/VehicleDetailPage.tsx'),edit=read('../src/modules/vehicles/EditVehicleModal.tsx');assert.match(detail,/canEdit&&<Button/);assert.match(detail,/EditVehicleModal/);assert.match(detail,/onError=/);assert.match(edit,/le VIN reste non modifiable/);assert.match(edit,/useUpdateVehicle/);assert.match(edit,/vehicle\.mileage/)});
test('VEH-STOCK-UX-01 sélectionne une image en rouge et centralise les actions sur son identifiant',()=>{const detail=read('../src/modules/vehicles/VehicleDetailPage.tsx');assert.match(detail,/selectedImageId/);assert.match(detail,/border-\[#8f1722\] ring-2 ring-\[#8f1722\]\/20/);assert.doesNotMatch(detail,/selectedPhotoIndex === idx \? 'border-blue/);assert.equal((detail.match(/Définir comme principale/g)??[]).length,1);assert.equal((detail.match(/>Supprimer<\/Button>/g)??[]).length,1);assert.match(detail,/imageId:String\(selectedImage\.id\)/);assert.match(detail,/disabled=\{!selectedImage/);assert.match(detail,/image\.is_primary/)});
test('VEH-STOCK-UX-01 conserve des clés stables et le reset cohérent des filtres sans manipulation DOM',()=>{const page=read('../src/modules/vehicles/VehiclesListPage.tsx');assert.match(page,/key=\{brand\.id\}/);assert.match(page,/key=\{model\.id\}/);assert.match(page,/key=\{v\.id\}/);assert.match(page,/setSelectedBrand\(e\.target\.value\);setSelectedModel\('ALL'\)/);assert.match(page,/filteredTotal=vehiclesQuery\.data\?\.total/);assert.doesNotMatch(page,/removeChild|appendChild|createPortal/)});
test('les prix publics restent visibles et les marges dépendent de vehicles.financials.view',()=>{const page=read('../src/modules/vehicles/VehiclesListPage.tsx'),hooks=read('../src/api/erpHooks.ts'),mapper=hooks.slice(hooks.indexOf('const mapVehicle'),hooks.indexOf('const leadPriorityFromDb'));assert.match(page,/canViewFinancials=can\('vehicles\.financials\.view'\)/);assert.match(page,/canViewFinancials&&<div className="text-right">/);assert.match(page,/canViewFinancials&&<th[^>]*>Marge Cible HT<\/th>/);assert.match(page,/canViewFinancials&&<td[^>]*>\{v\.targetMarginHT/);assert.match(page,/Prix Vente TTC/);assert.match(mapper,/targetMarginHT:[\s\S]*\.every\(value=>value!=null\)/);assert.doesNotMatch(mapper,/purchasePriceHT: n\(/)});
test('la fiche détail protège tous les calculs internes par permission dynamique',()=>{const detail=read('../src/modules/vehicles/VehicleDetailPage.tsx');assert.match(detail,/canViewFinancials=can\('vehicles\.financials\.view'\)/);assert.match(detail,/canViewFinancials&&<div[^>]*>[\s\S]*Marge Brute Cible HT/);assert.match(detail,/canViewFinancials && activeTab === 'financials'/);assert.match(detail,/Prix d'Achat HT/);assert.match(detail,/Prix de Revient Total HT/)});
test('Nginx donne la priorité au proxy uploads sur la regex des images',()=>{const nginx=read('../nginx/default.conf');assert.match(nginx,/location \^~ \/uploads\//);assert.match(nginx,/proxy_pass http:\/\/lca_backend/)});
