import React,{useMemo,useState}from'react';
import{Camera,KeyRound,Plus,Search,UserCheck,UserX}from'lucide-react';
import{Navigate}from'react-router-dom';
import{useAgenciesQuery}from'../../api/erpHooks';
import{type AdminUser,type CreateUserPayload,useRolesQuery,useUserActions,useUsersAdminQuery}from'../../api/userHooks';
import{PageHeader}from'../../components/common/PageHeader';
import{Badge}from'../../components/ui/Badge';
import{Button}from'../../components/ui/Button';
import{Card}from'../../components/ui/Card';
import{Modal}from'../../components/ui/Modal';
import{assetUrl}from'../../services/apiClient';
import{useAuthStore}from'../../stores/authStore';
import{useUiStore}from'../../stores/uiStore';
import{RoleManagementPanel}from'./RoleManagementPanel';

const empty:CreateUserPayload={firstName:'',lastName:'',email:'',phone:'',jobTitle:'',agencyId:'',roles:[],password:'',isEmployee:false,employeeNumber:'',employeePosition:'',employeeHireDate:'',employeeStatus:'active'};
const input='w-full rounded-md border border-slate-300 bg-white px-3 py-2 text-xs';
export const UsersManagementPage:React.FC=()=>{
 const auth=useAuthStore(),toast=useUiStore(s=>s.addToast),allowed=auth.can('users.view'),canCreate=auth.can('users.create')&&auth.can('users.assign_role')&&auth.can('users.assign_agency'),canUpdate=auth.can('users.update'),canAssignRole=auth.can('users.assign_role'),canAssignAgency=auth.can('users.assign_agency'),canManageEmployees=auth.can('hr.employees.manage'),canDisable=auth.can('users.disable'),canReset=auth.can('users.reset_password'),canViewRoles=auth.can('roles.view');
 const[tab,setTab]=useState<'users'|'matrix'>('users'),[search,setSearch]=useState(''),[active,setActive]=useState<''|'true'|'false'>(''),[agencyId,setAgencyId]=useState(''),[role,setRole]=useState(''),[open,setOpen]=useState(false),[editing,setEditing]=useState<AdminUser|null>(null),[reset,setReset]=useState<AdminUser|null>(null),[form,setForm]=useState<CreateUserPayload>(empty);
 const users=useUsersAdminQuery({search,active,agencyId,role}),agencies=useAgenciesQuery(),roles=useRolesQuery(canViewRoles),actions=useUserActions();
 const availableRoles=useMemo(()=>roles.data?.filter(r=>r.is_active!==false)??[],[roles.data]);
 if(!allowed)return <Navigate to="/dashboard" replace/>;
 const show=(user?:AdminUser)=>{setEditing(user??null);setForm(user?{firstName:user.firstName,lastName:user.lastName,email:user.email,phone:user.phone??'',jobTitle:user.jobTitle??'',agencyId:user.agencyId,roles:user.roles[0]?[user.roles[0]]:[],password:'',isEmployee:user.isEmployee,employeeNumber:user.employeeNumber??'',employeePosition:user.employeePosition??user.jobTitle??'',employeeHireDate:user.employeeHireDate?.slice(0,10)??'',employeeStatus:user.employeeStatus??'active'}:{...empty,agencyId:agencies.data?.find(a=>a.isActive)?.id??'',roles:availableRoles[0]?[availableRoles[0].code]:[]});setOpen(true)};
 const submit=async(e:React.FormEvent)=>{e.preventDefault();try{if(editing){const body:Record<string,unknown>={firstName:form.firstName,lastName:form.lastName,email:form.email,phone:form.phone,jobTitle:form.jobTitle};if(canAssignAgency)body.agencyId=form.agencyId;if(canAssignRole)body.roles=form.roles;if(canManageEmployees)Object.assign(body,{isEmployee:form.isEmployee,employeeNumber:form.employeeNumber,employeePosition:form.employeePosition,employeeHireDate:form.employeeHireDate,employeeStatus:form.employeeStatus});await actions.update.mutateAsync({id:editing.id,body:body as never})}else await actions.create.mutateAsync(canManageEmployees?form:{...form,isEmployee:undefined,employeeNumber:undefined,employeePosition:undefined,employeeHireDate:undefined,employeeStatus:undefined});toast({type:'success',title:editing?'Collaborateur modifié':'Collaborateur créé',description:'Les informations ont été enregistrées.'});setOpen(false)}catch(error){toast({type:'error',title:'Action impossible',description:error instanceof Error?error.message:'Erreur API'})}};
 const toggle=async(u:AdminUser)=>{if(u.isActive&&!confirm(`Désactiver cet agent ?\n\nIl ne pourra plus se connecter ni recevoir de nouvelles affectations. Son historique restera conservé.`))return;try{await actions.status.mutateAsync({id:u.id,isActive:!u.isActive});toast({type:'success',title:u.isActive?'Agent désactivé':'Agent réactivé',description:u.fullName})}catch(e){toast({type:'error',title:'Changement impossible',description:e instanceof Error?e.message:'Erreur API'})}};
 const upload=async(u:AdminUser,file?:File)=>{if(!file)return;try{await actions.avatar.mutateAsync({id:u.id,file});toast({type:'success',title:'Photo mise à jour',description:u.fullName})}catch(e){toast({type:'error',title:'Photo refusée',description:e instanceof Error?e.message:'Erreur API'})}};
 return <div className="space-y-6"><PageHeader title="Utilisateurs & habilitations" subtitle="Comptes, agences, rôles et accès opérationnels." breadcrumbs={[{label:'Accueil',href:'/dashboard'},{label:'Administration'},{label:'Utilisateurs'}]} actions={canCreate?<Button size="sm" icon={<Plus className="w-4 h-4"/>} onClick={()=>show()}>Ajouter un collaborateur</Button>:undefined}/>
 <div className="flex gap-2 border-b"><button className={`px-4 py-2 text-xs font-bold ${tab==='users'?'border-b-2 border-[#8f1722]':''}`} onClick={()=>setTab('users')}>Collaborateurs</button>{canViewRoles&&<button className={`px-4 py-2 text-xs font-bold ${tab==='matrix'?'border-b-2 border-[#8f1722]':''}`} onClick={()=>setTab('matrix')}>Matrice RBAC</button>}</div>
 {tab==='users'?<><Card><div className="grid gap-3 md:grid-cols-4"><label className="relative"><Search className="absolute left-3 top-2.5 h-4 w-4 text-slate-400"/><input className={`${input} pl-9`} value={search} onChange={e=>setSearch(e.target.value)} placeholder="Nom ou e-mail"/></label><select className={input} value={active} onChange={e=>setActive(e.target.value as typeof active)}><option value="">Tous les statuts</option><option value="true">Actifs</option><option value="false">Inactifs</option></select><select className={input} value={agencyId} onChange={e=>setAgencyId(e.target.value)}><option value="">Toutes les agences</option>{agencies.data?.filter(a=>a.isActive).map(a=><option key={a.id} value={a.id}>{a.name}</option>)}</select><select className={input} value={role} onChange={e=>setRole(e.target.value)}><option value="">Tous les rôles</option>{roles.data?.map(r=><option key={r.id} value={r.code}>{r.name}</option>)}</select></div></Card>
 <Card padding="none"><div className="overflow-x-auto"><table className="w-full text-left text-xs"><thead className="border-b bg-slate-50 text-slate-500"><tr><th className="p-4">Collaborateur</th><th className="p-4">Rôles</th><th className="p-4">Agence</th><th className="p-4">Statut</th><th className="p-4 text-right">Actions</th></tr></thead><tbody>{users.data?.map(u=><tr key={u.id} className="border-b last:border-0"><td className="p-4"><div className="flex items-center gap-3">{u.avatar?<img src={assetUrl(u.avatar)} className="h-9 w-9 rounded-full object-cover"/>:<div className="flex h-9 w-9 items-center justify-center rounded-full bg-[#161618] font-bold text-white">{u.firstName[0]}{u.lastName[0]}</div>}<div><div className="font-bold">{u.fullName}</div><div className="text-slate-500">{u.email}{u.jobTitle?` · ${u.jobTitle}`:''}</div></div></div></td><td className="p-4"><div className="flex flex-wrap gap-1">{u.roles.map(r=><Badge key={r} size="sm">{r}</Badge>)}</div></td><td className="p-4">{u.agencyName}</td><td className="p-4"><Badge variant={u.isActive?'success':'default'}>{u.isActive?'Actif':'Inactif'}</Badge></td><td className="p-4"><div className="flex justify-end gap-1">{canUpdate&&<Button size="sm" variant="outline" onClick={()=>show(u)}>Modifier</Button>}{canUpdate&&<label className="cursor-pointer rounded-md border p-2" title="Photo"><Camera className="h-4 w-4"/><input hidden type="file" accept="image/jpeg,image/png,image/webp" onChange={e=>void upload(u,e.target.files?.[0])}/></label>}{canUpdate&&u.avatar&&<Button size="sm" variant="outline" onClick={async()=>{try{await actions.deleteAvatar.mutateAsync(u.id)}catch(e){toast({type:"error",title:"Suppression impossible",description:e instanceof Error?e.message:"Erreur API"})}}}>Retirer photo</Button>}{canReset&&<Button size="sm" variant="outline" icon={<KeyRound className="h-4 w-4"/>} onClick={()=>setReset(u)}>Mot de passe</Button>}{canDisable&&<Button size="sm" variant={u.isActive?'danger':'outline'} icon={u.isActive?<UserX className="h-4 w-4"/>:<UserCheck className="h-4 w-4"/>} disabled={u.id===auth.currentUser?.id&&u.isActive} onClick={()=>void toggle(u)}>{u.isActive?'Désactiver':'Réactiver'}</Button>}</div></td></tr>)}</tbody></table>{users.isLoading&&<p className="p-5 text-sm text-slate-500">Chargement…</p>}{users.error&&<p className="p-5 text-sm text-red-700">{users.error.message}</p>}</div></Card></>:<RoleManagementPanel/>}
 <Modal isOpen={open} onClose={()=>setOpen(false)} title={editing?'Modifier le collaborateur':'Créer un collaborateur'}>
  <form className="space-y-3" onSubmit={submit}>
   <div className="grid grid-cols-2 gap-3"><label className="text-xs">Prénom(s) *<input className={input} required value={form.firstName} onChange={e=>setForm({...form,firstName:e.target.value})}/></label><label className="text-xs">Nom *<input className={input} required value={form.lastName} onChange={e=>setForm({...form,lastName:e.target.value})}/></label></div>
   <label className="block text-xs">E-mail *<input className={input} type="email" required value={form.email} onChange={e=>setForm({...form,email:e.target.value})}/></label>
   <div className="grid grid-cols-2 gap-3"><label className="text-xs">Téléphone<input className={input} value={form.phone} onChange={e=>setForm({...form,phone:e.target.value})}/></label><label className="text-xs">Fonction<input className={input} value={form.jobTitle} onChange={e=>setForm({...form,jobTitle:e.target.value})}/></label></div>
   <label className="block text-xs">Agence *<select className={input} required value={form.agencyId} onChange={e=>setForm({...form,agencyId:e.target.value})}><option value="" disabled>Choisir une agence</option>{agencies.data?.filter(a=>a.isActive).map(a=><option key={a.id} value={a.id}>{a.name}</option>)}</select></label>
   <label className="block text-xs">Rôle principal *<select className={input} required value={form.roles[0]??''} onChange={e=>setForm({...form,roles:e.target.value?[e.target.value]:[]})}><option value="" disabled>Choisir un rôle</option>{availableRoles.map(r=><option key={r.id} value={r.code}>{r.name}</option>)}</select></label>
   {canManageEmployees&&<div className="rounded-md border border-slate-200 bg-slate-50 p-3"><div className="flex items-center justify-between"><div><div className="text-xs font-bold">Employé de l’entreprise</div><div className="text-[11px] text-slate-500">Crée un profil dans le module RH.</div></div><select aria-label="Employé de l’entreprise" className="rounded-md border bg-white px-3 py-2 text-xs" value={form.isEmployee?'yes':'no'} onChange={e=>setForm({...form,isEmployee:e.target.value==='yes'})}><option value="no">Non</option><option value="yes">Oui</option></select></div>{form.isEmployee&&<div className="mt-3 grid grid-cols-2 gap-3"><label className="text-xs">Matricule<input className={input} value={form.employeeNumber} onChange={e=>setForm({...form,employeeNumber:e.target.value})} placeholder="Généré si vide"/></label><label className="text-xs">Fonction RH<input className={input} value={form.employeePosition} onChange={e=>setForm({...form,employeePosition:e.target.value})}/></label><label className="text-xs">Date d’embauche<input className={input} type="date" value={form.employeeHireDate} onChange={e=>setForm({...form,employeeHireDate:e.target.value})}/></label><label className="text-xs">Statut<select className={input} value={form.employeeStatus} onChange={e=>setForm({...form,employeeStatus:e.target.value as CreateUserPayload['employeeStatus']})}><option value="active">Actif</option><option value="inactive">Inactif</option><option value="departed">Sorti</option></select></label></div>}</div>}
   {!editing&&<label className="block text-xs">Mot de passe initial *<input className={input} type="password" minLength={8} required value={form.password} onChange={e=>setForm({...form,password:e.target.value})}/></label>}
   <div className="flex justify-end gap-2"><Button type="button" variant="outline" onClick={()=>setOpen(false)}>Annuler</Button><Button type="submit" disabled={!form.roles.length}>Enregistrer</Button></div>
  </form>
 </Modal>
 <Modal isOpen={Boolean(reset)} onClose={()=>setReset(null)} title="Réinitialiser le mot de passe"><form className="space-y-4" onSubmit={async e=>{e.preventDefault();const value=String(new FormData(e.currentTarget).get('password'));try{await actions.resetPassword.mutateAsync({id:reset!.id,newPassword:value});toast({type:'success',title:'Mot de passe réinitialisé',description:'Toutes les sessions ont été révoquées.'});setReset(null)}catch(error){toast({type:'error',title:'Réinitialisation impossible',description:error instanceof Error?error.message:'Erreur API'})}}}><p className="text-xs text-slate-500">Compte : {reset?.fullName}</p><input className={input} name="password" type="password" minLength={8} required placeholder="Nouveau mot de passe"/><div className="flex justify-end gap-2"><Button type="button" variant="outline" onClick={()=>setReset(null)}>Annuler</Button><Button type="submit">Réinitialiser</Button></div></form></Modal></div>
}
