import {randomUUID} from 'node:crypto';
import type {Request} from 'express';
import type {PoolConnection,ResultSetHeader,RowDataPacket} from 'mysql2/promise';
import {query,transaction} from '../../config/database.js';
import {unrestricted} from '../../middleware/authorize.js';
import {emitToAgency} from '../../realtime/socket.js';
import {HttpError} from '../../shared/http-error.js';
import {notifyRoles} from '../notifications/notification.service.js';

const SELECT=`SELECT q.*,COALESCE(c.company_name,CONCAT_WS(' ',c.first_name,c.last_name)) customer_name,o.assigned_user_id commercial_owner_id,CONCAT_WS(' ',owner.first_name,owner.last_name) commercial_owner_name,CONCAT_WS(' ',creator.first_name,creator.last_name) created_by_name,qi.vehicle_id,qi.description,qi.quantity,qi.unit_price,qi.discount,qi.tax_rate,qi.line_total,CONCAT(b.name,' ',m.name,' ',ve.name) vehicle_label,v.stock_number FROM quotations q JOIN customers c ON c.id=q.customer_id LEFT JOIN opportunities o ON o.id=q.opportunity_id LEFT JOIN users owner ON owner.id=o.assigned_user_id LEFT JOIN users creator ON creator.id=q.created_by LEFT JOIN quotation_items qi ON qi.quotation_id=q.id LEFT JOIN vehicles v ON v.id=qi.vehicle_id LEFT JOIN versions ve ON ve.id=v.version_id LEFT JOIN models m ON m.id=ve.model_id LEFT JOIN brands b ON b.id=m.brand_id`;
const id=(value:unknown,label='Identifiant')=>{const result=String(value??'');if(!/^[1-9]\d*$/.test(result))throw new HttpError(400,`${label} invalide`);return result};
const amount=(value:unknown,label:string)=>{const result=Number(value??0);if(!Number.isFinite(result)||result<0)throw new HttpError(400,`${label} invalide`);return Math.round(result*100)/100};
const date=(value:unknown)=>{const result=String(value??'').trim();if(result&&!/^\d{4}-\d{2}-\d{2}$/.test(result))throw new HttpError(400,'Date de validité invalide');return result||null};
const scope=(request:Request,alias='q')=>unrestricted(request)?{sql:'1=1',params:[] as unknown[]}:{sql:`${alias}.agency_id=?`,params:[request.user!.agencyId]};
const isAgent=(request:Request)=>request.user!.roles.includes('SALES_AGENT');
const assertOwner=(row:RowDataPacket,request:Request)=>{if(isAgent(request)&&String(row.commercial_owner_id??row.assigned_user_id??'')!==request.user!.sub)throw new HttpError(403,'Ce devis appartient à un autre commercial')};
const map=(row:RowDataPacket)=>({id:String(row.id),quotationNumber:row.quotation_number,opportunityId:row.opportunity_id==null?null:String(row.opportunity_id),customerId:String(row.customer_id),customerName:row.customer_name,agencyId:String(row.agency_id),salespersonId:row.commercial_owner_id==null?null:String(row.commercial_owner_id),salespersonName:row.commercial_owner_name??'',createdById:row.created_by==null?null:String(row.created_by),createdByName:row.created_by_name??'',status:row.status,validUntil:row.valid_until,subtotal:Number(row.subtotal),discountTotal:Number(row.discount_total),taxTotal:Number(row.tax_total),total:Number(row.total),notes:row.notes??'',createdAt:row.created_at,vehicleId:row.vehicle_id==null?null:String(row.vehicle_id),vehicleLabel:row.vehicle_label??'',stockNumber:row.stock_number??'',items:row.vehicle_id==null?[]:[{vehicleId:String(row.vehicle_id),description:row.description,quantity:Number(row.quantity),unitPrice:Number(row.unit_price),discount:Number(row.discount),taxRate:Number(row.tax_rate),lineTotal:Number(row.line_total)}]});

export async function one(value:unknown,request:Request){const quotationId=id(value,'Devis');const[row]=await query<RowDataPacket[]>(`${SELECT} WHERE q.id=?`,[quotationId]);if(!row)throw new HttpError(404,'Devis introuvable');if(!unrestricted(request)&&String(row.agency_id)!==String(request.user!.agencyId))throw new HttpError(403,'Devis rattaché à une autre agence');assertOwner(row,request);return map(row)}
export async function list(filters:Record<string,unknown>,request:Request){const s=scope(request),where=[s.sql],params=[...s.params];if(isAgent(request)){where.push('o.assigned_user_id=?');params.push(request.user!.sub)}for(const[key,column]of[['opportunityId','q.opportunity_id'],['customerId','q.customer_id'],['status','q.status']]as const)if(filters[key]){where.push(`${column}=?`);params.push(String(filters[key]))}return(await query<RowDataPacket[]>(`${SELECT} WHERE ${where.join(' AND ')} ORDER BY q.created_at DESC`,params)).map(map)}

export async function validateCreatePrerequisite(body:unknown,request:Request){const opportunityId=id((body as Record<string,unknown>|null)?.opportunityId,'Opportunité');const[opportunity]=await query<RowDataPacket[]>(`SELECT o.stage,o.assigned_user_id,COALESCE(assignee.agency_id,creator.agency_id) agency_id FROM opportunities o JOIN leads l ON l.id=o.lead_id LEFT JOIN users assignee ON assignee.id=o.assigned_user_id LEFT JOIN users creator ON creator.id=l.created_by WHERE o.id=?`,[opportunityId]);if(!opportunity)throw new HttpError(404,'Opportunité introuvable');if(opportunity.stage!=='test_drive')throw new HttpError(409,'Un essai réel doit être enregistré avant de créer le devis');const agencyId=String(opportunity.agency_id??'');if(!agencyId||(!unrestricted(request)&&agencyId!==String(request.user!.agencyId)))throw new HttpError(403,'Opportunité rattachée à une autre agence');assertOwner(opportunity,request)}

async function ensureCustomer(connection:PoolConnection,opportunity:RowDataPacket,agencyId:string,userId:string){if(opportunity.customer_id)return String(opportunity.customer_id);const temporary=`TMP-${randomUUID()}`,[created]=await connection.execute<ResultSetHeader>(`INSERT INTO customers(customer_code,customer_type,agency_id,first_name,last_name,company_name,email,phone,source,classification,assigned_user_id,created_by) VALUES(?,'individual',?,?,?,?,?,?,'CRM','prospect',?,?)`,[temporary,agencyId,opportunity.first_name,opportunity.last_name||opportunity.company_name||'Prospect',opportunity.company_name,opportunity.email,opportunity.phone,opportunity.assigned_user_id,userId]);const customerId=String(created.insertId),code=`CLI-${customerId.padStart(6,'0')}`;await connection.execute('UPDATE customers SET customer_code=? WHERE id=?',[code,customerId]);await connection.execute('UPDATE leads SET customer_id=? WHERE id=?',[customerId,opportunity.lead_id]);await connection.execute('UPDATE opportunities SET customer_id=? WHERE id=?',[customerId,opportunity.id]);return customerId}

export async function create(body:unknown,request:Request){
  const b=(body??{})as Record<string,unknown>,opportunityId=id(b.opportunityId,'Opportunité'),vehicleId=id(b.vehicleId,'Véhicule'),discount=amount(b.discount,'Remise'),validUntil=date(b.validUntil),notes=String(b.notes??'').trim();if(notes.length>10000)throw new HttpError(400,'Notes trop longues');
  const result=await transaction(async connection=>{
    const[opportunities]=await connection.execute<RowDataPacket[]>(`SELECT o.*,l.first_name,l.last_name,l.company_name,l.email,l.phone,COALESCE(assignee.agency_id,creator.agency_id) agency_id FROM opportunities o JOIN leads l ON l.id=o.lead_id LEFT JOIN users assignee ON assignee.id=o.assigned_user_id LEFT JOIN users creator ON creator.id=l.created_by WHERE o.id=? FOR UPDATE`,[opportunityId]),opportunity=opportunities[0];if(!opportunity)throw new HttpError(404,'Opportunité introuvable');
    const agencyId=String(opportunity.agency_id??'');if(!agencyId||(!unrestricted(request)&&agencyId!==String(request.user!.agencyId)))throw new HttpError(403,'Opportunité rattachée à une autre agence');assertOwner(opportunity,request);if(opportunity.stage!=='test_drive')throw new HttpError(409,'Un essai réel doit être enregistré avant de créer le devis');if(!opportunity.assigned_user_id)throw new HttpError(409,'Un commercial responsable doit être affecté à l’opportunité');
    const[duplicate]=await connection.execute<RowDataPacket[]>(`SELECT id FROM quotations WHERE opportunity_id=? AND status NOT IN('rejected','expired','cancelled') FOR UPDATE`,[opportunityId]);if(duplicate[0])throw new HttpError(409,'Un devis actif existe déjà pour cette opportunité');
    const[vehicles]=await connection.execute<RowDataPacket[]>('SELECT id,agency_id,status,stock_number,sale_price FROM vehicles WHERE id=? FOR UPDATE',[vehicleId]),vehicle=vehicles[0];if(!vehicle)throw new HttpError(404,'Véhicule introuvable');if(String(vehicle.agency_id)!==agencyId)throw new HttpError(403,'Véhicule rattaché à une autre agence');if(!['available','reserved'].includes(vehicle.status))throw new HttpError(409,'Véhicule indisponible pour un devis');
    const customerId=await ensureCustomer(connection,opportunity,agencyId,request.user!.sub),subtotal=amount(vehicle.sale_price,'Prix public');if(discount>subtotal)throw new HttpError(400,'La remise dépasse le prix du véhicule');const total=subtotal-discount,quotationNumber=`DEV-${new Date().toISOString().slice(0,10).replaceAll('-','')}-${randomUUID().slice(0,8).toUpperCase()}`;
    const[quotation]=await connection.execute<ResultSetHeader>(`INSERT INTO quotations(quotation_number,customer_id,opportunity_id,agency_id,created_by,status,valid_until,subtotal,discount_total,tax_total,total,notes) VALUES(?,?,?,?,?,'draft',?,?,?,0,?,?)`,[quotationNumber,customerId,opportunityId,agencyId,request.user!.sub,validUntil,subtotal,discount,total,notes||null]);
    await connection.execute(`INSERT INTO quotation_items(quotation_id,vehicle_id,description,quantity,unit_price,discount,tax_rate,line_total) VALUES(?,?,?,1,?,?,0,?)`,[quotation.insertId,vehicleId,`Véhicule ${vehicle.stock_number}`,subtotal,discount,total]);await connection.execute("UPDATE opportunities SET stage='offer',expected_value=? WHERE id=?",[total,opportunityId]);await connection.execute(`INSERT INTO activities(customer_id,lead_id,opportunity_id,assigned_user_id,type,subject,description,status,completed_at) VALUES(?,?,?,?,?,'Devis créé',?,'completed',NOW())`,[customerId,opportunity.lead_id,opportunityId,opportunity.assigned_user_id,'note',`${quotationNumber} — ${total} XAF`]);return{id:String(quotation.insertId),agencyId,quotationNumber,leadId:String(opportunity.lead_id)};
  });
  emitToAgency(result.agencyId,'quotation:created',{id:result.id,opportunityId});await notifyRoles({agencyId:result.agencyId,roles:['SALES_MANAGER'],includeGlobalRoles:['DIRECTOR','SUPER_ADMIN'],excludeUserIds:[request.user!.sub],subject:'Nouveau devis commercial',message:`Le devis ${result.quotationNumber} a été créé.`,eventType:'quotation.created',referenceType:'lead',referenceId:result.leadId,eventKey:`quotation.created:${result.id}`});return one(result.id,request);
}

export async function update(value:unknown,body:unknown,request:Request){const quotationId=id(value,'Devis'),b=(body??{})as Record<string,unknown>;await transaction(async connection=>{const[rows]=await connection.execute<RowDataPacket[]>(`SELECT q.*,o.assigned_user_id commercial_owner_id,qi.vehicle_id,v.sale_price FROM quotations q JOIN opportunities o ON o.id=q.opportunity_id JOIN quotation_items qi ON qi.quotation_id=q.id JOIN vehicles v ON v.id=qi.vehicle_id WHERE q.id=? FOR UPDATE`,[quotationId]),quotation=rows[0];if(!quotation)throw new HttpError(404,'Devis introuvable');if(!unrestricted(request)&&String(quotation.agency_id)!==String(request.user!.agencyId))throw new HttpError(403,'Agence non autorisée');assertOwner(quotation,request);if(!['draft','sent','negotiation'].includes(quotation.status))throw new HttpError(409,'Ce devis n’est plus modifiable');const discount=Object.hasOwn(b,'discount')?amount(b.discount,'Remise'):Number(quotation.discount_total),subtotal=Number(quotation.sale_price);if(discount>subtotal)throw new HttpError(400,'La remise dépasse le prix du véhicule');const total=subtotal-discount,notes=Object.hasOwn(b,'notes')?String(b.notes??'').trim():quotation.notes,validUntil=Object.hasOwn(b,'validUntil')?date(b.validUntil):quotation.valid_until;if(String(notes??'').length>10000)throw new HttpError(400,'Notes trop longues');await connection.execute('UPDATE quotations SET valid_until=?,subtotal=?,discount_total=?,total=?,notes=? WHERE id=?',[validUntil,subtotal,discount,total,notes||null,quotationId]);await connection.execute('UPDATE quotation_items SET unit_price=?,discount=?,line_total=? WHERE quotation_id=?',[subtotal,discount,total,quotationId]);await connection.execute('UPDATE opportunities SET expected_value=? WHERE id=?',[total,quotation.opportunity_id])});return one(quotationId,request)}

export async function validate(value:unknown,request:Request){
  const quotationId=id(value,'Devis');
  await transaction(async connection=>{
    const[rows]=await connection.execute<RowDataPacket[]>(`SELECT q.*,o.lead_id,o.assigned_user_id commercial_owner_id FROM quotations q JOIN opportunities o ON o.id=q.opportunity_id WHERE q.id=? FOR UPDATE`,[quotationId]),quotation=rows[0];
    if(!quotation)throw new HttpError(404,'Devis introuvable');
    if(!unrestricted(request)&&String(quotation.agency_id)!==String(request.user!.agencyId))throw new HttpError(403,'Devis rattaché à une autre agence');
    assertOwner(quotation,request);
    if(quotation.status!=='draft')throw new HttpError(409,'Seul un devis brouillon peut être émis');
    await connection.execute("UPDATE quotations SET status='sent' WHERE id=?",[quotationId]);
    await connection.execute(`INSERT INTO activities(customer_id,lead_id,opportunity_id,assigned_user_id,type,subject,description,status,completed_at) VALUES(?,?,?,?,?,'Devis émis',?,'completed',NOW())`,[quotation.customer_id,quotation.lead_id,quotation.opportunity_id,request.user!.sub,'note',`Devis ${quotation.quotation_number} émis. Propriétaire commercial : ${quotation.commercial_owner_id}.`]);
    await connection.execute(`INSERT INTO audit_logs(user_id,module,entity_type,entity_id,action,old_values,new_values,ip_address,user_agent) VALUES(?,'quotations','quotation',?,'quotation.issued',?,?,?,?)`,[request.user!.sub,quotationId,JSON.stringify({status:'draft',commercialOwnerId:String(quotation.commercial_owner_id)}),JSON.stringify({status:'sent',issuedBy:request.user!.sub}),request.ip??null,request.get('user-agent')??null]);
  });
  return one(quotationId,request);
}
