import React,{useEffect,useMemo,useState}from'react';
import{useCreateQuotation,useVehiclesQuery}from'../../api/erpHooks';
import{Modal}from'../../components/ui/Modal';
import{Button}from'../../components/ui/Button';
import{formatCurrency}from'../../lib/utils';
import{useAuthStore}from'../../stores/authStore';
import{useUiStore}from'../../stores/uiStore';
import type{Lead,Quotation}from'../../types';

export const QuotationModal:React.FC<{lead:Lead|null;onClose:()=>void;onCreated:(quotation:Quotation)=>void}>=({lead,onClose,onCreated})=>{
 const agencyId=useAuthStore(s=>s.currentAgency?.id),vehiclesQuery=useVehiclesQuery({status:'available'}),create=useCreateQuotation(),toast=useUiStore(s=>s.addToast),vehicles=useMemo(()=>vehiclesQuery.data?.filter(v=>v.agencyId===agencyId&&v.status==='DISPONIBLE')??[],[vehiclesQuery.data,agencyId]);
 const[vehicleId,setVehicleId]=useState(''),[discount,setDiscount]=useState(0),[validUntil,setValidUntil]=useState(''),[notes,setNotes]=useState('');
 useEffect(()=>{if(lead){setVehicleId('');setDiscount(0);setValidUntil('');setNotes('')}},[lead]);const vehicle=vehicles.find(v=>v.id===vehicleId),total=Math.max(0,(vehicle?.sellingPriceTTC??0)-discount),valid=Boolean(vehicle&&lead?.opportunityId&&discount>=0&&discount<=vehicle.sellingPriceTTC);
 const submit=async()=>{if(!lead?.opportunityId||!valid)return;try{const quotation=await create.mutateAsync({opportunityId:lead.opportunityId,vehicleId,discount,validUntil:validUntil||undefined,notes:notes.trim()||undefined});toast({type:'success',title:'Devis créé',description:`${quotation.quotationNumber} a été enregistré dans MySQL.`});onCreated(quotation);onClose()}catch(error){toast({type:'error',title:'Création du devis impossible',description:error instanceof Error?error.message:'Erreur API'})}};
 return <Modal isOpen={Boolean(lead)} onClose={onClose} title="Créer un devis" description={lead?`Opportunité ${lead.opportunityId} — ${lead.firstName} ${lead.lastName}`:undefined} maxWidth="lg"><div className="space-y-4">{vehiclesQuery.isLoading&&<p className="text-sm text-slate-500">Chargement des véhicules…</p>}{vehiclesQuery.isError&&<p className="rounded border border-red-200 bg-red-50 p-3 text-sm text-red-700">{vehiclesQuery.error.message}</p>}<label className="block text-xs font-semibold">Véhicule disponible<select value={vehicleId} onChange={e=>setVehicleId(e.target.value)} className="mt-1 w-full rounded border p-2.5"><option value="">Sélectionner</option>{vehicles.map(v=><option key={v.id} value={v.id}>{v.brand} {v.model} — {v.stockNumber} — {formatCurrency(v.sellingPriceTTC)}</option>)}</select></label><div className="grid gap-3 sm:grid-cols-2"><label className="text-xs font-semibold">Remise XAF<input type="number" min="0" max={vehicle?.sellingPriceTTC??0} value={discount} onChange={e=>setDiscount(Number(e.target.value))} className="mt-1 w-full rounded border p-2.5"/></label><label className="text-xs font-semibold">Valide jusqu’au<input type="date" value={validUntil} onChange={e=>setValidUntil(e.target.value)} className="mt-1 w-full rounded border p-2.5"/></label></div>{vehicle&&<div className="rounded border bg-slate-50 p-3 text-xs"><div>Prix public : <b>{formatCurrency(vehicle.sellingPriceTTC)}</b></div><div>Remise : <b>-{formatCurrency(discount)}</b></div><div className="mt-1 text-sm">Total : <b>{formatCurrency(total)}</b></div></div>}<label className="block text-xs font-semibold">Notes<textarea value={notes} onChange={e=>setNotes(e.target.value)} className="mt-1 min-h-20 w-full rounded border p-2.5"/></label><div className="flex justify-end gap-2 border-t pt-3"><Button variant="outline" onClick={onClose}>Annuler</Button><Button loading={create.isPending} disabled={!valid} onClick={()=>void submit()}>{create.isPending?'Création du devis…':'Créer le devis'}</Button></div></div></Modal>
};
