import React,{useState}from'react';
import{useSearchParams}from'react-router-dom';
import{useActivityOptionsQuery,useActivityQuery,type ActivityItem}from'../../api/activityHooks';
import{PageHeader}from'../../components/common/PageHeader';
import{Badge}from'../../components/ui/Badge';
import{Button}from'../../components/ui/Button';
import{Card}from'../../components/ui/Card';
import{Modal}from'../../components/ui/Modal';

const input='w-full rounded-md border border-slate-300 bg-white px-3 py-2 text-xs';
const label:Record<string,string>={CREATE:'Création',UPDATE:'Modification',STATUS:'Statut / affectation',APPROVE:'Approbation',REJECT:'Refus',CANCEL:'Annulation',PAYMENT:'Encaissement',REFUND:'Remboursement',DOCUMENT:'Document',SECURITY:'Sécurité',OTHER:'Autre'};
export const ActivityPage:React.FC=()=>{
 const[searchParams,setSearchParams]=useSearchParams(),[page,setPage]=useState(1),[selected,setSelected]=useState<ActivityItem|null>(null);
 const filters={page,pageSize:25,userId:searchParams.get('userId')??'',agencyId:searchParams.get('agencyId')??'',module:searchParams.get('module')??'',category:searchParams.get('category')??'',from:searchParams.get('from')??'',to:searchParams.get('to')??'',search:searchParams.get('search')??''};
 const options=useActivityOptionsQuery(),activity=useActivityQuery(filters);
 const update=(key:string,value:string)=>{const next=new URLSearchParams(searchParams);value?next.set(key,value):next.delete(key);setSearchParams(next);setPage(1)};
 const reset=()=>{setSearchParams({});setPage(1)};
 return <div className="space-y-6"><PageHeader title="Activité utilisateurs" subtitle="Journal opérationnel des actions métier significatives, dans votre périmètre d’accès." breadcrumbs={[{label:'Accueil',href:'/dashboard'},{label:'Système'},{label:'Activité'}]}/>
 <Card><div className="grid gap-3 md:grid-cols-4"><input className={input} value={filters.search} onChange={e=>update('search',e.target.value)} placeholder="Action, module, ressource, acteur…"/><select className={input} value={filters.userId} onChange={e=>update('userId',e.target.value)}><option value="">Tous les utilisateurs</option>{options.data?.users.map(user=><option key={user.id} value={user.id}>{user.name}{user.isActive?'':' (inactif)'}</option>)}</select><select className={input} value={filters.module} onChange={e=>update('module',e.target.value)}><option value="">Tous les modules</option>{options.data?.modules.map(module=><option key={module}>{module}</option>)}</select><select className={input} value={filters.category} onChange={e=>update('category',e.target.value)}><option value="">Toutes les actions</option>{options.data?.categories.map(category=><option key={category} value={category}>{label[category]??category}</option>)}</select><select className={input} value={filters.agencyId} onChange={e=>update('agencyId',e.target.value)}><option value="">Toutes les agences autorisées</option>{options.data?.agencies.map(agency=><option key={agency.id} value={agency.id}>{agency.name}</option>)}</select><input aria-label="Date de début" className={input} type="date" value={filters.from} onChange={e=>update('from',e.target.value)}/><input aria-label="Date de fin" className={input} type="date" value={filters.to} onChange={e=>update('to',e.target.value)}/><Button variant="outline" onClick={reset}>Réinitialiser</Button></div></Card>
 <Card padding="none"><div className="overflow-x-auto"><table className="w-full text-left text-xs"><thead className="border-b bg-slate-50 text-slate-500"><tr><th className="p-4">Date</th><th className="p-4">Acteur</th><th className="p-4">Action</th><th className="p-4">Ressource</th><th className="p-4">Contexte</th><th className="p-4 text-right">Détail</th></tr></thead><tbody>{activity.data?.rows.map(item=><tr key={item.id} className="border-b last:border-0"><td className="p-4 whitespace-nowrap">{new Date(item.createdAt).toLocaleString('fr-FR')}</td><td className="p-4"><div className="font-semibold">{item.actor.name}</div>{!item.actor.isActive&&<span className="text-slate-500">Compte inactif</span>}</td><td className="p-4"><Badge>{label[item.category]??item.category}</Badge><div className="mt-1 text-slate-500">{item.action}</div></td><td className="p-4"><div className="font-semibold">{item.resource}</div><div className="text-slate-500">{item.module}</div></td><td className="p-4">{item.context.agencyName??item.context.concessionName??'Contexte non renseigné'}</td><td className="p-4 text-right"><Button size="sm" variant="outline" onClick={()=>setSelected(item)}>Voir</Button></td></tr>)}</tbody></table>{activity.isLoading&&<p className="p-5 text-sm text-slate-500">Chargement…</p>}{activity.error&&<p className="p-5 text-sm text-red-700">{activity.error.message}</p>}{activity.data&&!activity.data.rows.length&&<p className="p-8 text-center text-sm text-slate-500">Aucune activité ne correspond aux filtres.</p>}</div><div className="flex items-center justify-between border-t p-4 text-xs"><span>{activity.data?.pagination.total??0} événement(s) · scope {activity.data?.scope??options.data?.scope??'—'}</span><div className="flex items-center gap-2"><Button size="sm" variant="outline" disabled={page<=1} onClick={()=>setPage(value=>value-1)}>Précédent</Button><span>Page {page} / {Math.max(1,activity.data?.pagination.totalPages??1)}</span><Button size="sm" variant="outline" disabled={page>=(activity.data?.pagination.totalPages??1)} onClick={()=>setPage(value=>value+1)}>Suivant</Button></div></div></Card>
 <Modal isOpen={Boolean(selected)} onClose={()=>setSelected(null)} title="Détail de l’événement" maxWidth="xl">{selected&&<div className="space-y-4 text-sm"><div><strong>{selected.action}</strong> · {selected.resource}</div><div className="text-slate-500">{selected.actor.name} — {new Date(selected.createdAt).toLocaleString('fr-FR')} — {selected.context.agencyName??selected.context.concessionName??'contexte non renseigné'}</div>{selected.detailsRestricted?<div className="rounded-md bg-amber-50 p-4 text-amber-900">Le détail est masqué car cette ressource contient des données sensibles.</div>:<div className="grid gap-4 md:grid-cols-2"><div><h4 className="mb-2 font-bold">Avant</h4><pre className="max-h-80 overflow-auto rounded-md bg-slate-950 p-3 text-xs text-slate-100">{JSON.stringify(selected.oldValues,null,2)??'—'}</pre></div><div><h4 className="mb-2 font-bold">Après</h4><pre className="max-h-80 overflow-auto rounded-md bg-slate-950 p-3 text-xs text-slate-100">{JSON.stringify(selected.newValues,null,2)??'—'}</pre></div></div>}</div>}</Modal></div>
}
