import{useState}from'react';
import{type Employee,useEmployeeContractTypesQuery,useHrActions}from'../../api/hrHooks';
import{Button}from'../../components/ui/Button';
import{Modal}from'../../components/ui/Modal';
import{useAuthStore}from'../../stores/authStore';
import{useUiStore}from'../../stores/uiStore';

const field='w-full rounded-md border border-slate-300 bg-white px-3 py-2 text-xs';
export function ContractTypesManager({employee}:{employee:Employee}){const can=useAuthStore(s=>s.can),toast=useUiStore(s=>s.addToast),actions=useHrActions(),types=useEmployeeContractTypesQuery(employee.concession_id,can('hr.contract.type.manage')), [open,setOpen]=useState(false),[form,setForm]=useState({code:'',name:'',description:''});if(!can('hr.contract.type.manage'))return null;const run=async(promise:Promise<unknown>,title:string)=>{try{await promise;await types.refetch();toast({type:'success',title})}catch(error){toast({type:'error',title:'Action impossible',description:error instanceof Error?error.message:'Erreur API'})}};return <><div className="flex justify-end"><Button size="xs" variant="outline" onClick={()=>setOpen(true)}>Configurer les types de contrat</Button></div><Modal isOpen={open} onClose={()=>setOpen(false)} title="Types de contrat"><div className="space-y-3">{types.data?.map(type=><div key={type.id} className="flex items-center justify-between rounded border p-3 text-xs"><span><strong>{type.code} · {type.name}</strong><br/><small className="text-slate-500">{type.is_active?'Actif':'Inactif'}{type.is_used?' · déjà utilisé, code immuable':''}</small></span><Button size="xs" variant="outline" onClick={()=>void run(actions.contractType.mutateAsync({id:type.id,code:type.code,name:type.name,description:type.description??'',isActive:!type.is_active}),type.is_active?'Type désactivé':'Type réactivé')}>{type.is_active?'Désactiver':'Réactiver'}</Button></div>)}{types.isSuccess&&!types.data?.length&&<p className="rounded bg-slate-50 p-3 text-center text-xs text-slate-500">Aucun type configuré. Aucun type juridique n’est imposé par défaut.</p>}<div className="grid grid-cols-2 gap-2"><input aria-label="Code type contrat" className={field} placeholder="Code" value={form.code} onChange={e=>setForm({...form,code:e.target.value})}/><input aria-label="Nom type contrat" className={field} placeholder="Libellé" value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></div><textarea aria-label="Description type contrat" className={field} placeholder="Description" value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/><div className="flex justify-end"><Button disabled={!form.code||!form.name} onClick={()=>void run(actions.contractType.mutateAsync({...form,concessionId:employee.concession_id}),'Type créé').then(()=>setForm({code:'',name:'',description:''}))}>Ajouter</Button></div></div></Modal></>}
