import React,{useMemo,useState}from'react';
import{BarChart3,Boxes,Coins,Plus,Search,Users}from'lucide-react';
import{useAgenciesQuery}from'../../api/erpHooks';
import{type Budget,type Employee,type StockCategory,type StockItem,useBudgetsQuery,useEmployeesQuery,useExpensesQuery,useHrActions,useHrConcessionsQuery,useHrOverviewQuery,useHrReportingQuery,useSalariesQuery,useStockAgenciesQuery,useStockCategoriesQuery,useStockMovementsQuery,useStockQuery}from'../../api/hrHooks';
import{PageHeader}from'../../components/common/PageHeader';
import{Badge}from'../../components/ui/Badge';
import{Button}from'../../components/ui/Button';
import{Card}from'../../components/ui/Card';
import{Modal}from'../../components/ui/Modal';
import{useAuthStore}from'../../stores/authStore';
import{useUiStore}from'../../stores/uiStore';

type Tab='overview'|'employees'|'salaries'|'stock'|'budgets'|'reporting';
const input='w-full rounded-md border border-slate-300 bg-white px-3 py-2 text-xs';
const money=(v:number|undefined)=>new Intl.NumberFormat('fr-FR',{maximumFractionDigits:2}).format(v??0);
const dateLabel=(v:string)=>new Intl.DateTimeFormat('fr-FR').format(new Date(`${v.slice(0,10)}T00:00:00`));
const statusLabel:Record<string,string>={active:'Actif',inactive:'Inactif',departed:'Sorti',draft:'Brouillon',closed:'Clôturé',cancelled:'Annulé'};

export const HrAdministrationPage:React.FC=()=>{
 const{can,permissionScope}=useAuthStore(),toast=useUiStore(s=>s.addToast),actions=useHrActions();
 const tabs=useMemo(()=>[
  {id:'overview' as Tab,label:'Vue d’ensemble',show:true},{id:'employees' as Tab,label:'Personnel',show:can('hr.employees.view')},{id:'salaries' as Tab,label:'Salaires',show:can('hr.salary.view')},{id:'stock' as Tab,label:'Stocks internes',show:can('hr.stock.view')},{id:'budgets' as Tab,label:'Budgets & Dépenses',show:can('hr.budget.view')},{id:'reporting' as Tab,label:'Reporting',show:can('hr.reporting.view')},
 ].filter(x=>x.show),[can]);
 const[tab,setTab]=useState<Tab>('overview'),[search,setSearch]=useState(''),[status,setStatus]=useState(''),[agencyId,setAgencyId]=useState(''),[page,setPage]=useState(1),[includeInactive,setIncludeInactive]=useState(false);
 const[selectedEmployee,setSelectedEmployee]=useState<Employee>(),[selectedStock,setSelectedStock]=useState<StockItem>(),[selectedBudget,setSelectedBudget]=useState<Budget>(),[editingCategory,setEditingCategory]=useState<StockCategory>(),[modal,setModal]=useState<'salary'|'employee'|'item'|'movement'|'categories'|'budget'|'expense'|null>(null);
 const overview=useHrOverviewQuery(tab==='overview'),employees=useEmployeesQuery({search,status,agencyId,page,pageSize:20},(tab==='employees'||tab==='salaries')&&can('hr.employees.view')),stock=useStockQuery({search:tab==='stock'?search:'',agencyId,includeInactive:includeInactive?'true':''},tab==='stock'&&can('hr.stock.view')),budgets=useBudgetsQuery(tab==='budgets'&&can('hr.budget.view')),reporting=useHrReportingQuery(tab==='reporting'&&can('hr.reporting.view')),agencies=useAgenciesQuery(),concessions=useHrConcessionsQuery(can('hr.budget.manage'));
 const stockAgencies=useStockAgenciesQuery(modal==='item'&&can('hr.stock.manage')),stockCategories=useStockCategoriesQuery(tab==='stock'&&(can('hr.stock.view')||can('hr.stock.manage'))),canManageCategories=['CONCESSION','GLOBAL'].includes(permissionScope('hr.stock.manage')??'');
 const salaries=useSalariesQuery(selectedEmployee?.id,modal==='salary'&&can('hr.salary.view')),movements=useStockMovementsQuery(selectedStock?.id,modal==='movement'&&can('hr.stock.view')),expenses=useExpensesQuery(selectedBudget?.id,modal==='expense'&&can('hr.expense.view'));
 const notify=(promise:Promise<unknown>,success:string)=>promise.then(()=>{toast({type:'success',title:success,description:'Les données ont été actualisées.'});setModal(null)}).catch(e=>toast({type:'error',title:'Action impossible',description:e instanceof Error?e.message:'Erreur API'}));
 const form=(e:React.FormEvent<HTMLFormElement>)=>Object.fromEntries(new FormData(e.currentTarget).entries());
 const employeeRows=employees.data?.items??[];
 return <div className="space-y-6"><PageHeader title="RH & Administration" subtitle="Personnel, salaires, stocks internes et pilotage budgétaire." breadcrumbs={[{label:'Accueil',href:'/dashboard'},{label:'RH & Administration'}]}/>
 <div className="flex gap-1 overflow-x-auto border-b">{tabs.map(x=><button key={x.id} className={`whitespace-nowrap px-4 py-2.5 text-xs font-bold ${tab===x.id?'border-b-2 border-[#8f1722] text-[#8f1722]':'text-slate-500'}`} onClick={()=>{setTab(x.id);setSearch('');setAgencyId('')}}>{x.label}</button>)}</div>
 {tab==='overview'&&<Overview data={overview.data} loading={overview.isLoading}/>} 
 {(tab==='employees'||tab==='salaries')&&<><Filters search={search} setSearch={setSearch} status={status} setStatus={setStatus} agencyId={agencyId} setAgencyId={setAgencyId} agencies={agencies.data??[]}/><Card padding="none"><div className="overflow-x-auto"><table className="w-full text-left text-xs"><thead className="border-b bg-slate-50 text-slate-500"><tr><th className="p-4">Collaborateur</th><th className="p-4">Matricule</th><th className="p-4">Fonction</th><th className="p-4">Agence</th><th className="p-4">Statut</th>{tab==='salaries'&&<th className="p-4 text-right">Salaire actuel</th>}<th className="p-4 text-right">Actions</th></tr></thead><tbody>{employeeRows.map(x=><tr key={x.id} className="border-b last:border-0"><td className="p-4"><div className="font-bold">{x.first_name} {x.last_name}</div><div className="text-slate-500">{x.email}</div></td><td className="p-4 font-mono">{x.employee_number}</td><td className="p-4">{x.position_title??'—'}</td><td className="p-4">{x.agency_name}</td><td className="p-4"><Badge variant={x.employment_status==='active'?'success':x.employment_status==='departed'?'danger':'default'}>{statusLabel[x.employment_status]}</Badge></td>{tab==='salaries'&&<td className="p-4 text-right font-semibold">{x.current_salary==null?'—':money(x.current_salary)}</td>}<td className="p-4 text-right">{tab==='employees'&&can('hr.employees.manage')&&<Button size="sm" variant="outline" onClick={()=>{setSelectedEmployee(x);setModal('employee')}}>Modifier</Button>}{tab==='salaries'&&<Button size="sm" variant="outline" onClick={()=>{setSelectedEmployee(x);setModal('salary')}}>{can('hr.salary.manage')?'Historique / Ajouter':'Historique'}</Button>}</td></tr>)}</tbody></table>{employees.isLoading&&<Empty text="Chargement du personnel…"/>}{!employees.isLoading&&!employeeRows.length&&<Empty text="Aucun employé ne correspond aux critères."/>}</div><div className="flex items-center justify-between border-t p-3 text-xs text-slate-500"><span>{employees.data?.total??0} employé(s)</span><div className="flex gap-2"><Button size="xs" variant="outline" disabled={page<=1} onClick={()=>setPage(p=>p-1)}>Précédent</Button><Button size="xs" variant="outline" disabled={page*20>=(employees.data?.total??0)} onClick={()=>setPage(p=>p+1)}>Suivant</Button></div></div></Card></>}
 {tab==='stock'&&<><div className="flex flex-wrap items-center justify-between gap-3"><Filters search={search} setSearch={setSearch} agencyId={agencyId} setAgencyId={setAgencyId} agencies={agencies.data??[]}/><div className="flex flex-wrap gap-2"><Button size="sm" variant={includeInactive?'primary':'outline'} onClick={()=>setIncludeInactive(v=>!v)}>{includeInactive?'Masquer les inactifs':'Voir les inactifs'}</Button>{canManageCategories&&<Button size="sm" variant="outline" onClick={()=>{setEditingCategory(undefined);setModal('categories')}}>Catégories</Button>}{can('hr.stock.manage')&&<Button size="sm" icon={<Plus className="h-4 w-4"/>} onClick={()=>setModal('item')}>Nouvel article</Button>}</div></div><Card padding="none"><TableEmpty loading={stock.isLoading} empty={!stock.data?.length}><table className="w-full text-left text-xs"><thead className="border-b bg-slate-50 text-slate-500"><tr><th className="p-4">Article</th><th className="p-4">Catégorie</th><th className="p-4">Agence</th><th className="p-4 text-right">Stock</th><th className="p-4 text-right">Minimum</th><th className="p-4 text-right">Actions</th></tr></thead><tbody>{stock.data?.map(x=><tr key={x.id} className="border-b last:border-0"><td className="p-4"><div className="flex items-center gap-2 font-bold">{x.designation}{!x.is_active&&<Badge variant="default">Inactif</Badge>}</div><div className="font-mono text-slate-500">{x.reference??'Sans référence'}</div></td><td className="p-4">{x.category??'—'}</td><td className="p-4">{x.agency_name}</td><td className="p-4 text-right"><Badge variant={x.below_minimum?'warning':'success'}>{x.current_quantity} {x.unit}</Badge></td><td className="p-4 text-right">{x.minimum_quantity}</td><td className="p-4 text-right"><div className="flex justify-end gap-2"><Button size="sm" variant="outline" onClick={()=>{setSelectedStock(x);setModal('movement')}}>Historique</Button>{x.is_active&&(can('hr.stock.entry')||can('hr.stock.exit'))&&<Button size="sm" onClick={()=>{setSelectedStock(x);setModal('movement')}}>Mouvement</Button>}{can('hr.stock.manage')&&<Button size="sm" variant="outline" onClick={()=>void notify(actions.stockItemStatus.mutateAsync({id:x.id,isActive:!x.is_active}),x.is_active?'Article désactivé':'Article réactivé')}>{x.is_active?'Désactiver':'Réactiver'}</Button>}</div></td></tr>)}</tbody></table></TableEmpty></Card></>}
 {tab==='budgets'&&<><div className="flex justify-end">{can('hr.budget.manage')&&<Button size="sm" icon={<Plus className="h-4 w-4"/>} onClick={()=>setModal('budget')}>Nouveau budget</Button>}</div><div className="grid gap-4 lg:grid-cols-2">{budgets.data?.map(x=><Card key={x.id}><div className="flex items-start justify-between"><div><h3 className="font-bold">{x.label}</h3><p className="mt-1 text-xs text-slate-500">{x.agency_name??x.concession_name} · {dateLabel(x.start_date)} au {dateLabel(x.end_date)}</p></div><Badge variant={x.status==='active'?'success':'default'}>{statusLabel[x.status]??x.status}</Badge></div><div className="mt-5 grid grid-cols-3 gap-3 text-xs"><Metric label="Initial" value={money(x.initial_amount)}/><Metric label="Dépensé" value={money(x.spent)}/><Metric label="Disponible" value={money(x.remaining)} strong/></div>{can('hr.expense.view')&&<div className="mt-4 flex justify-end"><Button size="sm" variant="outline" onClick={()=>{setSelectedBudget(x);setModal('expense')}}>{can('hr.expense.create')?'Dépenses / Ajouter':'Voir les dépenses'}</Button></div>}</Card>)}</div>{!budgets.isLoading&&!budgets.data?.length&&<Card><Empty text="Aucun budget dans votre périmètre."/></Card>}</>}
 {tab==='reporting'&&<Reporting data={reporting.data}/>} 

 <Modal isOpen={modal==='employee'} onClose={()=>setModal(null)} title="Modifier le profil employé"><form className="space-y-3" onSubmit={e=>{e.preventDefault();const b=form(e);void notify(actions.updateEmployee.mutateAsync({id:selectedEmployee!.id,body:{employeeNumber:b.employeeNumber,positionTitle:b.positionTitle,hireDate:b.hireDate,status:b.status}}),'Profil employé modifié')}}><label className="block text-xs">Matricule<input name="employeeNumber" required className={input} defaultValue={selectedEmployee?.employee_number}/></label><label className="block text-xs">Fonction<input name="positionTitle" className={input} defaultValue={selectedEmployee?.position_title??''}/></label><label className="block text-xs">Date d’embauche<input name="hireDate" type="date" required className={input} defaultValue={selectedEmployee?.hire_date?.slice(0,10)}/></label><label className="block text-xs">Statut<select name="status" className={input} defaultValue={selectedEmployee?.employment_status}><option value="active">Actif</option><option value="inactive">Inactif</option><option value="departed">Sorti</option></select></label><Submit/></form></Modal>
 <Modal isOpen={modal==='salary'} onClose={()=>setModal(null)} title={`Salaires · ${selectedEmployee?.first_name??''} ${selectedEmployee?.last_name??''}`}><div className="space-y-4">{can('hr.salary.manage')&&<form className="grid gap-3 sm:grid-cols-3" onSubmit={e=>{e.preventDefault();const b=form(e);void notify(actions.salary.mutateAsync({employeeId:selectedEmployee!.id,amount:String(b.amount),effectiveDate:String(b.effectiveDate)}),'Salaire ajouté')}}><input name="amount" type="number" min="0.01" step="0.01" required className={input} placeholder="Montant"/><input name="effectiveDate" type="date" required className={input}/><Button type="submit">Ajouter</Button></form>}<div className="divide-y rounded-md border">{salaries.data?.map(x=><div key={x.id} className="flex justify-between p-3 text-xs"><span>{dateLabel(x.effective_date)}<small className="ml-2 text-slate-400">par {x.author_name??'système'}</small></span><strong>{money(x.amount)}</strong></div>)}{!salaries.data?.length&&<Empty text="Aucun historique salarial."/>}</div></div></Modal>
 <Modal isOpen={modal==='item'} onClose={()=>setModal(null)} title="Créer un article interne"><form className="space-y-3" onSubmit={e=>{e.preventDefault();void notify(actions.stockItem.mutateAsync(form(e)),'Article créé')}}><label className="block text-xs">Désignation<input name="designation" required className={input}/></label><div className="grid grid-cols-2 gap-3"><label className="text-xs">Référence<input name="reference" className={input}/></label><label className="text-xs">Catégorie<select name="categoryId" required className={input} disabled={stockCategories.isLoading||stockCategories.isError}><option value="">Sélectionner</option>{stockCategories.data?.filter(c=>c.is_active).map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label><label className="text-xs">Unité<input name="unit" required className={input} placeholder="pièce, ramette…"/></label><label className="text-xs">Stock minimum<input name="minimumQuantity" type="number" min="0" step="0.001" defaultValue="0" className={input}/></label></div><label className="block text-xs">Agence<select name="agencyId" required className={input} disabled={stockAgencies.isLoading||stockAgencies.isError}><option value="">Sélectionner</option>{stockAgencies.data?.map(a=><option key={a.id} value={a.id}>{a.name}</option>)}</select></label>{stockAgencies.isLoading&&<p className="text-xs text-slate-500">Chargement des agences autorisées…</p>}{stockAgencies.isError&&<p className="text-xs text-red-700">Chargement des agences impossible : {stockAgencies.error.message}</p>}{stockAgencies.isSuccess&&!stockAgencies.data.length&&<p className="text-xs text-amber-700">Aucune agence autorisée.</p>}{stockCategories.isLoading&&<p className="text-xs text-slate-500">Chargement des catégories…</p>}{stockCategories.isError&&<p className="text-xs text-red-700">Chargement des catégories impossible : {stockCategories.error.message}</p>}{stockCategories.isSuccess&&!stockCategories.data.some(c=>c.is_active)&&<p className="text-xs text-amber-700">Aucune catégorie active disponible.</p>}<Submit/></form></Modal>
 <Modal isOpen={modal==='categories'} onClose={()=>{setEditingCategory(undefined);setModal(null)}} title="Catégories d’articles internes"><div className="space-y-4">{stockCategories.isLoading&&<Empty text="Chargement des catégories…"/>}{stockCategories.isError&&<p className="text-xs text-red-700">Chargement impossible : {stockCategories.error.message}</p>}<div className="divide-y rounded-md border">{stockCategories.data?.map(c=><div key={c.id} className="flex items-center justify-between gap-3 p-3 text-xs"><span><strong>{c.name}</strong><small className="ml-2 font-mono text-slate-500">{c.code}</small>{!c.is_active&&<Badge variant="default">Inactive</Badge>}</span><div className="flex gap-2"><Button size="xs" variant="outline" onClick={()=>setEditingCategory(c)}>Modifier</Button><Button size="xs" variant="outline" onClick={()=>void notify(actions.stockCategory.mutateAsync({id:c.id,name:c.name,code:c.code,isActive:!c.is_active}),c.is_active?'Catégorie désactivée':'Catégorie réactivée')}>{c.is_active?'Désactiver':'Réactiver'}</Button></div></div>)}{stockCategories.isSuccess&&!stockCategories.data.length&&<Empty text="Aucune catégorie dans votre périmètre."/>}</div><form key={editingCategory?.id??'new'} className="grid gap-3 sm:grid-cols-2" onSubmit={e=>{e.preventDefault();const b=form(e);void notify(actions.stockCategory.mutateAsync({id:editingCategory?.id,name:String(b.name),code:String(b.code),concessionId:String(b.concessionId||''),isActive:editingCategory?.is_active??true}),editingCategory?'Catégorie modifiée':'Catégorie créée')}}><input name="name" required className={input} defaultValue={editingCategory?.name??''} placeholder="Nom"/><input name="code" required className={input} defaultValue={editingCategory?.code??''} placeholder="Code stable"/>{permissionScope('hr.stock.manage')==='GLOBAL'&&<input name="concessionId" required className={input} defaultValue={editingCategory?.concession_id??''} placeholder="Identifiant concession"/>}<div className="flex gap-2"><Button type="submit">{editingCategory?'Enregistrer':'Créer'}</Button>{editingCategory&&<Button type="button" variant="outline" onClick={()=>setEditingCategory(undefined)}>Annuler</Button>}</div></form></div></Modal>
 <Modal isOpen={modal==='movement'} onClose={()=>setModal(null)} title={`Mouvements · ${selectedStock?.designation??''}`}><div className="space-y-4">{selectedStock&&!selectedStock.is_active&&<p className="rounded-md bg-amber-50 p-3 text-xs text-amber-800">Article inactif : historique consultable, nouveaux mouvements interdits.</p>}{selectedStock?.is_active&&(can('hr.stock.entry')||can('hr.stock.exit'))&&<form className="grid gap-3 sm:grid-cols-2" onSubmit={e=>{e.preventDefault();const b=form(e);void notify(actions.stockMovement.mutateAsync({itemId:selectedStock!.id,body:b}),'Mouvement enregistré')}}><select name="type" className={input}>{can('hr.stock.entry')&&<option value="entry">Entrée</option>}{can('hr.stock.exit')&&<option value="exit">Sortie</option>}</select><input name="quantity" type="number" min="0.001" step="0.001" required className={input} placeholder="Quantité"/><input name="reason" className={input} placeholder="Motif"/><input name="reference" className={input} placeholder="Référence"/><Button type="submit">Enregistrer</Button></form>}<div className="divide-y rounded-md border">{movements.data?.map(x=><div key={x.id} className="flex justify-between p-3 text-xs"><span><Badge variant={x.movement_type==='entry'?'success':'warning'}>{x.movement_type==='entry'?'Entrée':'Sortie'}</Badge> <span className="ml-2">{x.reason??x.reference??'Sans motif'}</span></span><strong>{x.movement_type==='entry'?'+':'−'}{x.quantity} · solde {x.quantity_after}</strong></div>)}{!movements.data?.length&&<Empty text="Aucun mouvement."/>}</div></div></Modal>
 <Modal isOpen={modal==='budget'} onClose={()=>setModal(null)} title="Créer un budget"><form className="space-y-3" onSubmit={e=>{e.preventDefault();const b=form(e),body={...b,agencyId:b.scopeType==='agency'?b.targetId:undefined,concessionId:b.scopeType==='concession'?b.targetId:undefined};void notify(actions.budget.mutateAsync(body),'Budget créé')}}><label className="block text-xs">Libellé<input name="label" required className={input}/></label><div className="grid grid-cols-2 gap-3"><label className="text-xs">Portée<select name="scopeType" className={input}><option value="agency">Agence</option>{concessions.data?.length&&<option value="concession">Concession</option>}</select></label><label className="text-xs">Agence / concession<select name="targetId" required className={input}>{agencies.data?.filter(a=>a.isActive).map(a=><option key={`a${a.id}`} value={a.id}>Agence · {a.name}</option>)}{concessions.data?.map(c=><option key={`c${c.id}`} value={c.id}>Concession · {c.name}</option>)}</select></label><label className="text-xs">Montant initial<input name="initialAmount" type="number" min="0.01" step="0.01" required className={input}/></label><label className="text-xs">Catégorie<input name="category" className={input}/></label><label className="text-xs">Début<input name="startDate" type="date" required className={input}/></label><label className="text-xs">Fin<input name="endDate" type="date" required className={input}/></label></div><Submit/></form></Modal>
 <Modal isOpen={modal==='expense'} onClose={()=>setModal(null)} title={`Dépenses · ${selectedBudget?.label??''}`}><div className="space-y-4">{can('hr.expense.create')&&<form className="grid gap-3 sm:grid-cols-2" onSubmit={e=>{e.preventDefault();void notify(actions.expense.mutateAsync({budgetId:selectedBudget!.id,body:form(e)}),'Dépense enregistrée')}}><input name="label" required className={input} placeholder="Libellé"/><input name="amount" type="number" min="0.01" max={selectedBudget?.remaining} step="0.01" required className={input} placeholder="Montant"/><input name="expenseDate" type="date" required className={input}/><input name="category" className={input} placeholder="Catégorie"/><input name="reference" className={input} placeholder="Référence"/><Button type="submit">Enregistrer</Button></form>}<div className="divide-y rounded-md border">{expenses.data?.map(x=><div key={x.id} className="flex justify-between p-3 text-xs"><span>{dateLabel(x.expense_date)} · {x.label}</span><strong>{money(x.amount)}</strong></div>)}{!expenses.data?.length&&<Empty text="Aucune dépense."/>}</div></div></Modal>
 </div>
}

const Overview=({data,loading}:{data:ReturnType<typeof useHrOverviewQuery>['data'];loading:boolean})=><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{loading?<Card><Empty text="Chargement des indicateurs…"/></Card>:<>{data?.activeEmployees!==undefined&&<Kpi icon={<Users/>} label="Employés actifs" value={String(data.activeEmployees)}/>} {data?.payroll!==undefined&&<Kpi icon={<Coins/>} label="Masse salariale" value={money(data.payroll)}/>} {data?.activeBudget!==undefined&&<Kpi icon={<BarChart3/>} label="Budget actif" value={money(data.activeBudget)} detail={`${money(data.remainingBudget)} disponible`}/>} {data?.stockItems!==undefined&&<Kpi icon={<Boxes/>} label="Articles internes" value={String(data.stockItems)} detail={`${data.lowStockItems??0} sous le minimum`}/>}</>}</div>;
const Kpi=({icon,label,value,detail}:{icon:React.ReactNode;label:string;value:string;detail?:string})=><Card><div className="flex items-center gap-3 text-slate-500"><span className="h-5 w-5">{icon}</span><span className="text-xs font-semibold">{label}</span></div><div className="mt-3 text-2xl font-bold">{value}</div>{detail&&<p className="mt-1 text-xs text-slate-500">{detail}</p>}</Card>;
const Metric=({label,value,strong=false}:{label:string;value:string;strong?:boolean})=><div><div className="text-slate-500">{label}</div><div className={strong?'font-bold text-emerald-700':'font-bold'}>{value}</div></div>;
const Empty=({text}:{text:string})=><p className="p-5 text-center text-xs text-slate-500">{text}</p>;
const TableEmpty=({loading,empty,children}:{loading:boolean;empty:boolean;children:React.ReactNode})=><div className="overflow-x-auto">{children}{loading&&<Empty text="Chargement…"/>}{!loading&&empty&&<Empty text="Aucune donnée dans votre périmètre."/>}</div>;
const Submit=()=> <div className="flex justify-end"><Button type="submit">Enregistrer</Button></div>;
const Filters=({search,setSearch,status,setStatus,agencyId,setAgencyId,agencies}:{search:string;setSearch:(v:string)=>void;status?:string;setStatus?:(v:string)=>void;agencyId:string;setAgencyId:(v:string)=>void;agencies:{id:string;name:string;isActive:boolean}[]})=><Card className="flex-1"><div className="grid gap-3 md:grid-cols-3"><label className="relative"><Search className="absolute left-3 top-2.5 h-4 w-4 text-slate-400"/><input className={`${input} pl-9`} value={search} onChange={e=>setSearch(e.target.value)} placeholder="Rechercher"/></label>{setStatus&&<select className={input} value={status} onChange={e=>setStatus(e.target.value)}><option value="">Tous les statuts</option><option value="active">Actifs</option><option value="inactive">Inactifs</option><option value="departed">Sortis</option></select>}<select className={input} value={agencyId} onChange={e=>setAgencyId(e.target.value)}><option value="">Toutes les agences</option>{agencies.filter(a=>a.isActive).map(a=><option key={a.id} value={a.id}>{a.name}</option>)}</select></div></Card>;
const Reporting=({data}:{data:ReturnType<typeof useHrReportingQuery>['data']})=><div className="grid gap-4 lg:grid-cols-2">{Object.entries(data??{}).map(([section,rows])=><Card key={section}><h3 className="mb-3 text-sm font-bold">{{headcount:'Effectif par agence',payroll:'Masse salariale par agence',stock:'Stocks internes',budgets:'Consommation budgétaire'}[section]??section}</h3><div className="space-y-2">{(rows as Record<string,unknown>[]).map((row,i)=><div key={i} className="flex flex-wrap justify-between gap-2 border-b py-2 text-xs last:border-0">{Object.entries(row).filter(([k])=>!k.endsWith('_id')).map(([k,v])=><span key={k}><span className="text-slate-500">{k.replaceAll('_',' ')} : </span><strong>{typeof v==='number'?money(v):String(v??'—')}</strong></span>)}</div>)}</div></Card>)}</div>;
