import { ConflictException, Injectable, NotFoundException } from '@nestjs/common';
import { ResultSetHeader, RowDataPacket } from 'mysql2/promise';
import { DatabaseService } from '../../database/database.service';
import { RealtimeGateway } from '../../realtime/realtime.gateway';
import { CreateReservationDto, CreateSaleDto } from './sales.dto';

@Injectable()
export class SalesService {
  constructor(private readonly db: DatabaseService, private readonly realtime: RealtimeGateway) {}
  async findAll(agencyId?:string|null){return this.db.query<RowDataPacket[]>(`SELECT s.*,CONCAT_WS(' ',c.first_name,c.last_name) customer_name,si.vehicle_id,v.vin,CONCAT(b.name,' ',m.name,' ',ve.name) vehicle_label,CONCAT_WS(' ',u.first_name,u.last_name) salesperson_name FROM sales s JOIN customers c ON c.id=s.customer_id LEFT JOIN sale_items si ON si.sale_id=s.id AND si.vehicle_id IS NOT NULL LEFT JOIN vehicles v ON v.id=si.vehicle_id LEFT JOIN versions ve ON ve.id=v.version_id LEFT JOIN models m ON m.id=ve.model_id LEFT JOIN brands b ON b.id=m.brand_id LEFT JOIN users u ON u.id=s.salesperson_id WHERE (? IS NULL OR s.agency_id=?) ORDER BY s.created_at DESC`,[agencyId??null,agencyId??null]);}
  async findOne(id:string){const [row]=await this.db.query<RowDataPacket[]>(`SELECT s.*,CONCAT_WS(' ',c.first_name,c.last_name) customer_name,si.vehicle_id,v.vin,CONCAT(b.name,' ',m.name,' ',ve.name) vehicle_label,CONCAT_WS(' ',u.first_name,u.last_name) salesperson_name FROM sales s JOIN customers c ON c.id=s.customer_id LEFT JOIN sale_items si ON si.sale_id=s.id AND si.vehicle_id IS NOT NULL LEFT JOIN vehicles v ON v.id=si.vehicle_id LEFT JOIN versions ve ON ve.id=v.version_id LEFT JOIN models m ON m.id=ve.model_id LEFT JOIN brands b ON b.id=m.brand_id LEFT JOIN users u ON u.id=s.salesperson_id WHERE s.id=?`,[id]);if(!row)throw new NotFoundException('Vente introuvable');return row;}
  async create(dto:CreateSaleDto,userId:string){const saleNumber=`V-${Date.now()}`;const reservationNumber=`RES-${Date.now()}`;const total=dto.vehiclePrice-(dto.discount??0)+(dto.taxTotal??0);const id=await this.db.transaction(async c=>{const [vehicles]=await c.execute<RowDataPacket[]>('SELECT status FROM vehicles WHERE id=? AND agency_id=? FOR UPDATE',[dto.vehicleId,dto.agencyId]);if(!vehicles[0])throw new NotFoundException('Véhicule introuvable');if(vehicles[0].status!=='available')throw new ConflictException('Ce véhicule n’est pas disponible');const [active]=await c.execute<RowDataPacket[]>(`SELECT id FROM reservations WHERE vehicle_id=? AND status IN ('pending','confirmed') AND (expires_at IS NULL OR expires_at>NOW()) FOR UPDATE`,[dto.vehicleId]);if(active[0])throw new ConflictException('Ce véhicule possède déjà une réservation active');const [sale]=await c.execute<ResultSetHeader>(`INSERT INTO sales(sale_number,customer_id,opportunity_id,agency_id,salesperson_id,status,subtotal,discount_total,tax_total,total,deposit_amount,balance_due,notes) VALUES(?,?,?,?,?,'reserved',?,?,?,?,?,?,?)`,[saleNumber,dto.customerId,dto.opportunityId??null,dto.agencyId,dto.salespersonId??userId,dto.vehiclePrice,dto.discount??0,dto.taxTotal??0,total,dto.depositAmount??0,total-(dto.depositAmount??0),dto.notes??null]);await c.execute(`INSERT INTO sale_items(sale_id,vehicle_id,description,quantity,catalog_price,unit_price,discount,tax_rate,line_total) SELECT ?,id,CONCAT(vin,' - ',stock_number),1,catalog_price,?,?,0,? FROM vehicles WHERE id=?`,[sale.insertId,dto.vehiclePrice,dto.discount??0,total,dto.vehicleId]);await c.execute(`INSERT INTO reservations(reservation_number,customer_id,vehicle_id,sale_id,created_by,status,amount) VALUES(?,?,?,?,?,'confirmed',?)`,[reservationNumber,dto.customerId,dto.vehicleId,sale.insertId,userId,dto.depositAmount??0]);await c.execute(`UPDATE vehicles SET status='reserved' WHERE id=?`,[dto.vehicleId]);await c.execute(`INSERT INTO vehicle_status_history(vehicle_id,old_status,new_status,changed_by,reason) VALUES(?,'available','reserved',?,'Création vente')`,[dto.vehicleId,userId]);return String(sale.insertId);});this.realtime.emitAgency(dto.agencyId,'sales:created',{id,saleNumber,vehicleId:dto.vehicleId});return this.findOne(id);}
  async createReservation(dto:CreateReservationDto,userId:string){const number=`RES-${Date.now()}`;const result=await this.db.transaction(async c=>{const [v]=await c.execute<RowDataPacket[]>('SELECT agency_id,status FROM vehicles WHERE id=? FOR UPDATE',[dto.vehicleId]);if(!v[0])throw new NotFoundException('Véhicule introuvable');if(v[0].status!=='available')throw new ConflictException('Véhicule indisponible');const [r]=await c.execute<ResultSetHeader>(`INSERT INTO reservations(reservation_number,customer_id,vehicle_id,sale_id,created_by,status,reserved_at,expires_at,amount,notes) VALUES(?,?,?,?,?,'confirmed',NOW(),?,?,?)`,[number,dto.customerId,dto.vehicleId,dto.saleId??null,userId,dto.expiresAt??null,dto.amount??0,dto.notes??null]);await c.execute(`UPDATE vehicles SET status='reserved' WHERE id=?`,[dto.vehicleId]);return{id:String(r.insertId),agencyId:String(v[0].agency_id)};});this.realtime.emitAgency(result.agencyId,'reservations:created',{...result,reservationNumber:number,vehicleId:dto.vehicleId});return result;}
  async cancelReservation(id:string,userId:string){const data=await this.db.transaction(async c=>{const [rows]=await c.execute<RowDataPacket[]>('SELECT r.vehicle_id,v.agency_id,r.status FROM reservations r JOIN vehicles v ON v.id=r.vehicle_id WHERE r.id=? FOR UPDATE',[id]);if(!rows[0])throw new NotFoundException('Réservation introuvable');if(!['pending','confirmed'].includes(rows[0].status))throw new ConflictException('Réservation déjà clôturée');await c.execute(`UPDATE reservations SET status='cancelled' WHERE id=?`,[id]);await c.execute(`UPDATE vehicles SET status='available' WHERE id=? AND status='reserved'`,[rows[0].vehicle_id]);await c.execute(`INSERT INTO vehicle_status_history(vehicle_id,old_status,new_status,changed_by,reason) VALUES(?,'reserved','available',?,'Annulation réservation')`,[rows[0].vehicle_id,userId]);return{vehicleId:String(rows[0].vehicle_id),agencyId:String(rows[0].agency_id)};});this.realtime.emitAgency(data.agencyId,'reservations:cancelled',{id,...data});return{success:true};}
  async updateStatus(id:string,status:string,userId:string){const allowed:Record<string,string[]>={draft:['reserved','cancelled'],reserved:['ordered','cancelled'],ordered:['confirmed','cancelled'],confirmed:['preparation','cancelled'],preparation:['ready_for_delivery','cancelled'],ready_for_delivery:['delivered','cancelled'],delivered:[],cancelled:[]};const data=await this.db.transaction(async c=>{const [rows]=await c.execute<RowDataPacket[]>(`SELECT s.status,s.agency_id,si.vehicle_id,v.status vehicle_status FROM sales s LEFT JOIN sale_items si ON si.sale_id=s.id AND si.vehicle_id IS NOT NULL LEFT JOIN vehicles v ON v.id=si.vehicle_id WHERE s.id=? FOR UPDATE`,[id]);if(!rows[0])throw new NotFoundException('Vente introuvable');if(!allowed[rows[0].status]?.includes(status))throw new ConflictException(`Transition ${rows[0].status} → ${status} interdite`);await c.execute('UPDATE sales SET status=?,sold_at=IF(?="delivered",NOW(),sold_at) WHERE id=?',[status,status,id]);if(rows[0].vehicle_id&&['ordered','confirmed','preparation','ready_for_delivery'].includes(status)&&rows[0].vehicle_status!=='sold'){await c.execute(`UPDATE vehicles SET status='sold' WHERE id=?`,[rows[0].vehicle_id]);await c.execute(`INSERT INTO vehicle_status_history(vehicle_id,old_status,new_status,changed_by,reason) VALUES(?,?,'sold',?,'Progression vente')`,[rows[0].vehicle_id,rows[0].vehicle_status,userId]);}if(rows[0].vehicle_id&&status==='cancelled'){await c.execute(`UPDATE vehicles SET status='available' WHERE id=? AND status IN ('reserved','sold')`,[rows[0].vehicle_id]);await c.execute(`UPDATE reservations SET status='cancelled' WHERE sale_id=? AND status IN ('pending','confirmed')`,[id]);}return{agencyId:String(rows[0].agency_id)};});this.realtime.emitAgency(data.agencyId,'sales:status',{id,status});return this.findOne(id);}
}
