import React,{useState}from'react';
import{ArrowLeft,FileText}from'lucide-react';
import{useNavigate,useParams}from'react-router-dom';
import{useVehicleReturnActions,useVehicleReturnOptions,useVehicleReturnQuery}from'../../api/erpHooks';
import{PageHeader}from'../../components/common/PageHeader';
import{Badge}from'../../components/ui/Badge';
import{Button}from'../../components/ui/Button';
import{Card,CardHeader,CardTitle}from'../../components/ui/Card';
import{formatDate}from'../../lib/utils';
import{apiDownload}from'../../services/apiClient';
import{useAuthStore}from'../../stores/authStore';
import{useUiStore}from'../../stores/uiStore';

const input='w-full rounded-md border border-slate-300 p-2 text-sm';
export function VehicleReturnPage(){const{id}=useParams(),navigate=useNavigate(),can=useAuthStore(s=>s.can),toast=useUiStore(s=>s.addToast),q=useVehicleReturnQuery(id,can('vehicle.return.view')),options=useVehicleReturnOptions(id,can('vehicle.return.view')),actions=useVehicleReturnActions(),[form,setForm]=useState<Record<string,string>>({}),[selected,setSelected]=useState<string[]>([]),row=q.data;
 const set=(key:string,value:string)=>setForm(x=>({...x,[key]:value})),run=async(title:string,job:()=>Promise<unknown>)=>{try{await job();toast({type:'success',title,description:'Le dossier et sa piste d’audit ont été actualisés.'})}catch(error){toast({type:'error',title:'Action impossible',description:error instanceof Error?error.message:'Erreur API'})}};
 if(q.isLoading)return <p className="p-8 text-sm">Chargement…</p>;if(!row)return <p className="p-8 text-red-700">Dossier de retour introuvable.</p>;
 const financial=can('vehicle.return.financial.resolve'),stock=can('vehicle.return.stock.receive');
 const downloadPdf=async()=>{try{const blob=await apiDownload(`/vehicle-returns/${row.id}/pdf`),url=URL.createObjectURL(blob),anchor=document.createElement('a');anchor.href=url;anchor.download=`retour-${row.return_number}.pdf`;anchor.click();URL.revokeObjectURL(url)}catch(error){toast({type:'error',title:'Document indisponible',description:error instanceof Error?error.message:'Erreur API'})}};
 return <div className="space-y-5"><PageHeader title={`Retour ${row.return_number}`} subtitle={`${row.customer_name_snapshot} · ${row.vehicle_label_snapshot} · VIN ${row.vin_snapshot}`} breadcrumbs={[{label:'Livraisons',href:'/deliveries'},{label:row.delivery_number_snapshot,href:`/deliveries/${row.delivery_id}`},{label:row.return_number}]} actions={<div className="flex gap-2"><Button variant="outline" icon={<ArrowLeft className="h-4 w-4"/>} onClick={()=>navigate(`/deliveries/${row.delivery_id}`)}>Livraison</Button>{row.status==='CLOSED'&&<Button icon={<FileText className="h-4 w-4"/>} onClick={()=>void downloadPdf()}>PV officiel</Button>}</div>}/>
 <Card><div className="flex flex-wrap items-center gap-3"><Badge variant={row.status==='CLOSED'?'success':row.status==='REJECTED'?'danger':'warning'}>{row.status}</Badge><span className="text-sm">Vente {row.sale_number_snapshot} · livraison {row.delivery_number_snapshot}</span><span className="ml-auto text-xs text-slate-500">Demande du {formatDate(row.requested_at)}</span></div><p className="mt-3 text-sm">{row.request_description}</p></Card>
 {row.status==='REQUESTED'&&can('vehicle.return.inspect')&&<Card><CardHeader><CardTitle>Inspection contradictoire</CardTitle></CardHeader><div className="grid gap-3 md:grid-cols-2"><input className={input} type="number" placeholder="Kilométrage retour" value={form.mileage||''} onChange={e=>set('mileage',e.target.value)}/><input className={input} placeholder="État général" value={form.condition||''} onChange={e=>set('condition',e.target.value)}/><textarea className={input} placeholder="Dommages constatés" value={form.damages||''} onChange={e=>set('damages',e.target.value)}/><textarea className={input} placeholder="Éléments manquants / notes" value={form.notes||''} onChange={e=>set('notes',e.target.value)}/><Button onClick={()=>run('Inspection enregistrée',()=>actions.inspect.mutateAsync({returnId:id,mileage:Number(form.mileage),generalCondition:form.condition,damages:form.damages,notes:form.notes}))}>Valider l’inspection</Button></div></Card>}
 {row.status==='INSPECTED'&&can('vehicle.return.approve')&&<Card><CardHeader><CardTitle>Décision</CardTitle></CardHeader><textarea className={input} placeholder="Justification obligatoire" value={form.decision||''} onChange={e=>set('decision',e.target.value)}/><div className="mt-3 flex gap-2"><Button onClick={()=>run('Retour approuvé',()=>actions.approve.mutateAsync({returnId:id,comment:form.decision}))}>Approuver</Button><Button variant="danger" onClick={()=>run('Retour rejeté',()=>actions.reject.mutateAsync({returnId:id,comment:form.decision}))}>Rejeter</Button></div></Card>}
 {row.status==='APPROVED'&&financial&&<><Card><CardHeader><CardTitle>Retenues justifiées</CardTitle></CardHeader>{row.deductions?.map((x:any)=><p key={x.id} className="border-b py-2 text-sm"><b>{x.label}</b> — {Number(x.amount).toLocaleString('fr-FR')} {row.currency_code}<br/><span className="text-xs text-slate-500">{x.description}</span></p>)}<div className="mt-3 grid gap-2 md:grid-cols-4"><input className={input} placeholder="Catégorie" onChange={e=>set('category',e.target.value)}/><input className={input} placeholder="Libellé" onChange={e=>set('label',e.target.value)}/><input className={input} placeholder="Justification" onChange={e=>set('deductionDescription',e.target.value)}/><input className={input} type="number" min="1" placeholder="Montant" onChange={e=>set('deductionAmount',e.target.value)}/><Button onClick={()=>run('Retenue ajoutée',()=>actions.addDeduction.mutateAsync({returnId:id,category:form.category,label:form.label,description:form.deductionDescription,amount:Number(form.deductionAmount),requestId:crypto.randomUUID()}))}>Ajouter</Button></div></Card><Card><CardHeader><CardTitle>Résolution financière</CardTitle></CardHeader><p className="mb-3 text-xs text-slate-600">Choisissez explicitement les factures à créditer. Les services additionnels peuvent être conservés. Le remboursement ne dépassera ni l’avoir ni les encaissements, déduction faite des retenues.</p>{options.data?.invoices?.map((x:any)=><label key={x.id} className="mb-2 flex items-center gap-3 rounded border p-3 text-sm"><input type="checkbox" checked={selected.includes(String(x.id))} onChange={e=>setSelected(v=>e.target.checked?[...v,String(x.id)]:v.filter(i=>i!==String(x.id)))}/><span><b>{x.invoice_number}</b> · {x.invoice_type} · {Number(x.total).toLocaleString('fr-FR')} {x.currency_code} · déjà crédité {Number(x.credited).toLocaleString('fr-FR')}</span></label>)}<textarea className={input} placeholder="Justification de la résolution" value={form.rationale||''} onChange={e=>set('rationale',e.target.value)}/><Button className="mt-3" disabled={!selected.length} onClick={()=>run('Résolution financière enregistrée',()=>actions.resolve.mutateAsync({returnId:id,invoiceIds:selected,rationale:form.rationale}))}>Créer les avoirs et remboursements</Button></Card></>}
 {row.status==='FINANCIALLY_RESOLVED'&&stock&&<LocationCard title="Réception physique" locations={options.data?.locations??[]} form={form} set={set} actionLabel="Réceptionner" onAction={()=>run('Véhicule réceptionné',()=>actions.receive.mutateAsync({returnId:id,locationId:form.locationId,notes:form.stockNotes}))}/>}
 {row.status==='VEHICLE_RECEIVED'&&stock&&<LocationCard title="Décision de remise en stock" locations={options.data?.locations??[]} form={form} set={set} withDecision actionLabel="Valider la décision stock" onAction={()=>run('Décision stock enregistrée',()=>actions.stock.mutateAsync({returnId:id,locationId:form.locationId,decision:form.stockDecision,notes:form.stockNotes}))}/>}
 {row.status==='STOCK_DECIDED'&&stock&&<Card><CardHeader><CardTitle>Clôture</CardTitle></CardHeader><p className="mb-3 text-sm">La résolution financière et la décision stock sont terminées. La clôture génère le PV officiel immuable.</p><Button onClick={()=>run('Dossier clôturé',()=>actions.close.mutateAsync({returnId:id}))}>Clôturer et générer le PV</Button></Card>}
 {row.resolutionLines?.length>0&&<Card><CardHeader><CardTitle>Résolution et historique financier</CardTitle></CardHeader>{row.resolutionLines.map((x:any)=><p key={x.id} className="border-b py-2 text-sm">{x.invoice_number} · <b>{x.resolution_action}</b> · avoir {Number(x.credit_amount).toLocaleString('fr-FR')} · retenue {Number(x.retained_amount).toLocaleString('fr-FR')}</p>)}<p className="mt-3 text-sm">Total crédité : <b>{Number(row.credited_amount).toLocaleString('fr-FR')} {row.currency_code}</b> · remboursé : <b>{Number(row.refunded_amount).toLocaleString('fr-FR')} {row.currency_code}</b></p></Card>}
 <Card><CardHeader><CardTitle>Piste d’audit</CardTitle></CardHeader>{row.events?.map((x:any)=><p key={x.id} className="border-b py-2 text-xs"><b>{x.event_type}</b> · {formatDate(x.occurred_at)} · {x.performed_by_name}</p>)}</Card></div>}

function LocationCard({title,locations,form,set,withDecision=false,actionLabel,onAction}:{title:string;locations:any[];form:Record<string,string>;set:(k:string,v:string)=>void;withDecision?:boolean;actionLabel:string;onAction:()=>void}){return <Card><CardHeader><CardTitle>{title}</CardTitle></CardHeader><div className="grid gap-3 md:grid-cols-2">{withDecision&&<select className={input} value={form.stockDecision||''} onChange={e=>set('stockDecision',e.target.value)}><option value="">Décision…</option><option value="RESTOCK_USED">Remettre en vente comme occasion</option><option value="RECONDITION">Reconditionnement</option><option value="HOLD">Maintenir hors vente</option></select>}<select className={input} value={form.locationId||''} onChange={e=>set('locationId',e.target.value)}><option value="">Emplacement véhicule…</option>{locations.map(x=><option key={x.id} value={x.id}>{x.name} · {x.type}</option>)}</select><textarea className={input} placeholder="Notes" value={form.stockNotes||''} onChange={e=>set('stockNotes',e.target.value)}/><Button disabled={!form.locationId||(withDecision&&!form.stockDecision)} onClick={onAction}>{actionLabel}</Button></div></Card>}
