import { randomUUID } from 'node:crypto';
import type { Request } from 'express';
import type { PoolConnection, ResultSetHeader, RowDataPacket } from 'mysql2/promise';
import { query, transaction } from '../../config/database.js';
import { unrestricted } from '../../middleware/authorize.js';
import { emitToAgency } from '../../realtime/socket.js';
import { HttpError } from '../../shared/http-error.js';
import { notifyRoles } from '../notifications/notification.service.js';
import { assertFinanciallySettled } from '../billing/payment.domain.js';
import { assertSaleTransition, saleTotals, validateCreateSale } from './sale.domain.js';

export async function assertFinanciallySettledForFinalization(saleId:string,request:Request){await transaction(async c=>{const[rows]=await c.execute<RowDataPacket[]>(`SELECT s.agency_id,COALESCE((SELECT i.balance_due FROM invoices i WHERE i.sale_id=s.id AND i.status<>'cancelled' ORDER BY i.id DESC LIMIT 1),s.balance_due) financial_balance FROM sales s WHERE s.id=? FOR UPDATE`,[id(saleId)]),sale=rows[0];if(!sale)throw new HttpError(404,'Vente introuvable');if(!unrestricted(request)&&String(sale.agency_id)!==String(request.user!.agencyId))throw new HttpError(403,'Vente rattachée à une autre agence');assertFinanciallySettled(sale.financial_balance,'vente')})}

const SELECT=`SELECT s.*,a.name agency_name,COALESCE(c.company_name,CONCAT_WS(' ',c.first_name,c.last_name)) customer_name,si.vehicle_id,v.vin,v.stock_number,CONCAT(b.name,' ',m.name,' ',ve.name) vehicle_label,CONCAT_WS(' ',u.first_name,u.last_name) salesperson_name,f.financing_type,f.financier_name,f.financed_amount,f.monthly_payment,f.duration_months,ti.trade_in_value,CONCAT_WS(' ',ti.brand,ti.model,ti.version,ti.year) trade_in_vehicle_details,(SELECT MIN(d.scheduled_at) FROM deliveries d WHERE d.sale_id=s.id AND d.status<>'cancelled') expected_delivery_date,(SELECT i.id FROM invoices i WHERE i.sale_id=s.id AND i.status<>'cancelled' ORDER BY i.id DESC LIMIT 1) invoice_id,(SELECT i.amount_paid FROM invoices i WHERE i.sale_id=s.id AND i.status<>'cancelled' ORDER BY i.id DESC LIMIT 1) invoice_amount_paid,(SELECT i.balance_due FROM invoices i WHERE i.sale_id=s.id AND i.status<>'cancelled' ORDER BY i.id DESC LIMIT 1) invoice_balance_due,(SELECT i.status FROM invoices i WHERE i.sale_id=s.id AND i.status<>'cancelled' ORDER BY i.id DESC LIMIT 1) invoice_status FROM sales s JOIN agencies a ON a.id=s.agency_id JOIN customers c ON c.id=s.customer_id LEFT JOIN sale_items si ON si.sale_id=s.id AND si.vehicle_id IS NOT NULL LEFT JOIN vehicles v ON v.id=si.vehicle_id LEFT JOIN versions ve ON ve.id=v.version_id LEFT JOIN models m ON m.id=ve.model_id LEFT JOIN brands b ON b.id=m.brand_id LEFT JOIN users u ON u.id=s.salesperson_id LEFT JOIN financing f ON f.id=s.financing_id LEFT JOIN trade_ins ti ON ti.id=s.trade_in_id`;
const id=(value:unknown)=>{const result=String(value??'');if(!/^[1-9]\d*$/.test(result))throw new HttpError(400,'Identifiant invalide');return result};
const scope=(request:Request,alias='s')=>unrestricted(request)?{sql:'1=1',params:[] as unknown[]}:request.user!.roles.includes('SALES_AGENT')?{sql:`${alias}.agency_id=? AND ${alias}.salesperson_id=?`,params:[request.user!.agencyId,request.user!.sub]}:{sql:`${alias}.agency_id=?`,params:[request.user!.agencyId]};
const agency=(request:Request,requested?:string)=>{if(unrestricted(request)&&requested)return requested;if(!request.user!.agencyId)throw new HttpError(403,'Aucune agence associée');return request.user!.agencyId};
async function audit(c:PoolConnection,r:Request,saleId:string,action:string,oldValues:unknown,newValues:unknown){await c.execute(`INSERT INTO audit_logs(user_id,module,entity_type,entity_id,action,old_values,new_values,ip_address,user_agent) VALUES(?,'sales','sale',?,?,?,?,?,?)`,[r.user!.sub,saleId,action,oldValues==null?null:JSON.stringify(oldValues),newValues==null?null:JSON.stringify(newValues),r.ip??null,r.get('user-agent')??null])}
export async function one(saleId:string,request:Request){const s=scope(request);const[row]=await query<RowDataPacket[]>(`${SELECT} WHERE s.id=? AND ${s.sql}`,[id(saleId),...s.params]);if(!row)throw new HttpError(404,'Vente introuvable');return row}
export async function list(filters:Record<string,unknown>,request:Request){const s=scope(request),where=[s.sql],params=[...s.params];for(const[field,column]of[['status','s.status'],['customerId','s.customer_id'],['salespersonId','s.salesperson_id'],['agencyId','s.agency_id']]as const)if(filters[field]){where.push(`${column}=?`);params.push(String(filters[field]))}if(filters.from){where.push('DATE(s.created_at)>=?');params.push(String(filters.from))}if(filters.to){where.push('DATE(s.created_at)<=?');params.push(String(filters.to))}return query<RowDataPacket[]>(`${SELECT} WHERE ${where.join(' AND ')} ORDER BY s.created_at DESC`,params)}
async function validateSalesperson(c:PoolConnection,userId:string,agencyId:string){const[rows]=await c.execute<RowDataPacket[]>(`SELECT u.id FROM users u JOIN user_roles ur ON ur.user_id=u.id JOIN roles r ON r.id=ur.role_id WHERE u.id=? AND u.agency_id=? AND u.is_active=TRUE AND r.code IN('SALES_AGENT','SALES_MANAGER') LIMIT 1`,[userId,agencyId]);if(!rows[0])throw new HttpError(400,'Commercial inactif ou incompatible avec cette agence')}
export async function create(body:unknown,request:Request){
  const input=validateCreateSale(body),agencyId=agency(request,input.agencyId),isAgent=request.user!.roles.includes('SALES_AGENT');
  if(isAgent&&input.salespersonId&&input.salespersonId!==request.user!.sub)throw new HttpError(403,'Un commercial ne peut pas attribuer sa vente à un autre utilisateur');
  if(input.opportunityId&&!input.quotationId)throw new HttpError(400,'Un devis est obligatoire pour transformer une opportunité en vente');
  if(input.quotationId&&!input.opportunityId)throw new HttpError(400,'Le devis doit être lié à une opportunité');
  if(input.depositAmount>0)throw new HttpError(409,"L’acompte doit être enregistré comme un règlement distinct sur la facture de vente");
  const result=await transaction(async c=>{
    const[duplicate]=await c.execute<RowDataPacket[]>('SELECT id FROM sales WHERE idempotency_key=?',[input.idempotencyKey]);if(duplicate[0])return{saleId:String(duplicate[0].id),duplicate:true,agencyId};
    const[agencies]=await c.execute<RowDataPacket[]>('SELECT id FROM agencies WHERE id=? AND is_active=TRUE FOR UPDATE',[agencyId]);if(!agencies[0])throw new HttpError(400,'Agence inexistante ou inactive');
    const[customers]=await c.execute<RowDataPacket[]>('SELECT id,agency_id FROM customers WHERE id=? FOR UPDATE',[input.customerId]);if(!customers[0])throw new HttpError(404,'Client introuvable');if(String(customers[0].agency_id)!==agencyId)throw new HttpError(403,'Client rattaché à une autre agence');
    const[vehicles]=await c.execute<RowDataPacket[]>('SELECT id,agency_id,status,vin,stock_number,catalog_price,sale_price FROM vehicles WHERE id=? FOR UPDATE',[input.vehicleId]),vehicle=vehicles[0];if(!vehicle)throw new HttpError(404,'Véhicule introuvable');if(String(vehicle.agency_id)!==agencyId)throw new HttpError(403,'Véhicule rattaché à une autre agence');if(vehicle.status!=='available')throw new HttpError(409,'Ce véhicule n’est pas disponible');
    const[reservation]=await c.execute<RowDataPacket[]>(`SELECT id FROM reservations WHERE vehicle_id=? AND status IN('pending','confirmed') AND (expires_at IS NULL OR expires_at>NOW()) FOR UPDATE`,[input.vehicleId]);if(reservation[0])throw new HttpError(409,'Ce véhicule possède déjà une réservation active');
    let salespersonId=isAgent?request.user!.sub:(input.salespersonId??request.user!.sub);
    let opportunity:RowDataPacket|undefined,quotation:RowDataPacket|undefined;
    if(input.opportunityId){const[rows]=await c.execute<RowDataPacket[]>('SELECT id,lead_id,customer_id,assigned_user_id,stage FROM opportunities WHERE id=? FOR UPDATE',[input.opportunityId]);opportunity=rows[0];if(!opportunity||String(opportunity.customer_id)!==input.customerId)throw new HttpError(400,'Opportunité incompatible avec le client');if(opportunity.stage!=='negotiation'&&opportunity.stage!=='offer')throw new HttpError(409,'L’opportunité doit avoir un devis en offre ou négociation');if(!opportunity.assigned_user_id)throw new HttpError(409,'L’opportunité doit avoir un commercial responsable');const ownerId=String(opportunity.assigned_user_id);if(isAgent&&ownerId!==request.user!.sub)throw new HttpError(403,'Cette opportunité appartient à un autre commercial');salespersonId=ownerId;await validateSalesperson(c,salespersonId,agencyId);const[existing]=await c.execute<RowDataPacket[]>('SELECT id FROM sales WHERE opportunity_id=? FOR UPDATE',[input.opportunityId]);if(existing[0])throw new HttpError(409,'Cette opportunité a déjà été transformée en vente')}
    if(input.quotationId){const[rows]=await c.execute<RowDataPacket[]>(`SELECT q.*,qi.vehicle_id FROM quotations q JOIN quotation_items qi ON qi.quotation_id=q.id WHERE q.id=? FOR UPDATE`,[input.quotationId]);quotation=rows[0];if(!quotation||String(quotation.opportunity_id)!==input.opportunityId||String(quotation.customer_id)!==input.customerId||String(quotation.vehicle_id)!==input.vehicleId)throw new HttpError(400,'Devis incompatible avec la vente');if(!['draft','sent','negotiation','accepted'].includes(quotation.status))throw new HttpError(409,'Ce devis ne peut pas être transformé');const[existing]=await c.execute<RowDataPacket[]>('SELECT id FROM sales WHERE quotation_id=? FOR UPDATE',[input.quotationId]);if(existing[0])throw new HttpError(409,'Ce devis a déjà été transformé en vente')}
    await validateSalesperson(c,salespersonId,agencyId);
    const totals=saleTotals(vehicle.sale_price,input.discount,input.depositAmount),saleNumber=`V-${new Date().toISOString().slice(0,10).replaceAll('-','')}-${randomUUID().slice(0,8).toUpperCase()}`,[sale]=await c.execute<ResultSetHeader>(`INSERT INTO sales(sale_number,customer_id,opportunity_id,quotation_id,agency_id,salesperson_id,status,subtotal,discount_total,tax_total,total,deposit_amount,balance_due,notes,idempotency_key,created_by) VALUES(?,?,?,?,?,?,'reserved',?,?,0,?,?,?,?,?,?)`,[saleNumber,input.customerId,input.opportunityId??null,input.quotationId??null,agencyId,salespersonId,totals.subtotal,totals.discount,totals.total,totals.depositAmount,totals.balanceDue,input.notes,input.idempotencyKey,request.user!.sub]),saleId=String(sale.insertId);
    await c.execute(`INSERT INTO sale_items(sale_id,vehicle_id,description,quantity,catalog_price,unit_price,discount,tax_rate,line_total) VALUES(?,?,?,1,?,?,?,0,?)`,[saleId,input.vehicleId,`${vehicle.vin} - ${vehicle.stock_number}`,vehicle.catalog_price,totals.subtotal,totals.discount,totals.total]);
    const reservationNumber=`RES-${randomUUID().slice(0,12).toUpperCase()}`;await c.execute(`INSERT INTO reservations(reservation_number,customer_id,vehicle_id,sale_id,created_by,status,amount) VALUES(?,?,?,?,?,'confirmed',?)`,[reservationNumber,input.customerId,input.vehicleId,saleId,request.user!.sub,totals.depositAmount]);
    await c.execute("UPDATE vehicles SET status='reserved' WHERE id=?",[input.vehicleId]);await c.execute("INSERT INTO vehicle_status_history(vehicle_id,old_status,new_status,changed_by,reason) VALUES(?,'available','reserved',?,'Création vente')",[input.vehicleId,request.user!.sub]);
    if(opportunity&&quotation){await c.execute("UPDATE opportunities SET stage='won',won_at=NOW(),lost_reason=NULL,lost_at=NULL WHERE id=?",[opportunity.id]);await c.execute("UPDATE leads SET status='converted',converted_at=NOW() WHERE id=?",[opportunity.lead_id]);await c.execute("UPDATE quotations SET status='accepted' WHERE id=?",[quotation.id]);await c.execute(`INSERT INTO activities(customer_id,lead_id,opportunity_id,assigned_user_id,type,subject,description,status,completed_at) VALUES(?,?,?,?,?,'Transformation en vente',?,'completed',NOW())`,[input.customerId,opportunity.lead_id,opportunity.id,salespersonId,'note',`Vente ${saleNumber} créée depuis le devis`])}
    await audit(c,request,saleId,'sale.created',null,{saleNumber,agencyId,customerId:input.customerId,vehicleId:input.vehicleId,salespersonId,opportunityId:input.opportunityId,quotationId:input.quotationId,...totals});return{saleId,duplicate:false,agencyId,saleNumber};
  });
  if(!result.duplicate){emitToAgency(result.agencyId,'sales:created',{id:result.saleId,saleNumber:result.saleNumber,vehicleId:input.vehicleId});await notifyRoles({agencyId:result.agencyId,roles:['SALES_MANAGER','DELIVERY_MANAGER'],includeGlobalRoles:['DIRECTOR','SUPER_ADMIN'],excludeUserIds:[request.user!.sub],subject:'Nouvelle vente',message:`La vente ${result.saleNumber} a été créée.`,eventType:'sale.created',referenceType:'sale',referenceId:result.saleId,eventKey:`sale.created:${result.saleId}`})}return one(result.saleId,request)
}
export async function update(saleId:string,body:unknown,request:Request){const current=await one(saleId,request),b=(body??{})as Record<string,unknown>,sets:string[]=[],values:any[]=[],next:Record<string,unknown>={};if(Object.hasOwn(b,'notes')){const notes=String(b.notes??'').trim();if(notes.length>10000)throw new HttpError(400,'Notes trop longues');sets.push('notes=?');values.push(notes||null);next.notes=notes||null}if(Object.hasOwn(b,'salespersonId')){const salespersonId=id(b.salespersonId);if(request.user!.roles.includes('SALES_AGENT')&&salespersonId!==request.user!.sub)throw new HttpError(403,'Un commercial ne peut pas réattribuer sa vente');await transaction(async c=>validateSalesperson(c,salespersonId,String(current.agency_id)));sets.push('salesperson_id=?');values.push(salespersonId);next.salespersonId=salespersonId}if(!sets.length)throw new HttpError(400,'Aucun champ de vente modifiable fourni');await transaction(async c=>{await c.execute(`UPDATE sales SET ${sets.join(',')} WHERE id=?`,[...values,id(saleId)]);await audit(c,request,id(saleId),'sale.updated',{notes:current.notes,salespersonId:String(current.salesperson_id??'')},next)});emitToAgency(String(current.agency_id),'sales:updated',{id:saleId});return one(saleId,request)}
export async function updateStatus(saleId:string,value:unknown,reasonValue:unknown,request:Request){
  const reason=String(reasonValue??'').trim();
  const result=await transaction(async c=>{
    const[rows]=await c.execute<RowDataPacket[]>(`SELECT s.id,s.status,s.agency_id,si.vehicle_id,v.status vehicle_status FROM sales s LEFT JOIN sale_items si ON si.sale_id=s.id AND si.vehicle_id IS NOT NULL LEFT JOIN vehicles v ON v.id=si.vehicle_id WHERE s.id=? FOR UPDATE`,[id(saleId)]),sale=rows[0];
    if(!sale)throw new HttpError(404,'Vente introuvable');
    if(!unrestricted(request)&&String(sale.agency_id)!==String(request.user!.agencyId))throw new HttpError(403,'Vente rattachée à une autre agence');
    const status=assertSaleTransition(String(sale.status),value);
    const finalValidators=['SUPER_ADMIN','DIRECTOR','SALES_MANAGER'];
    if(status==='delivered')throw new HttpError(409,'La livraison effective doit être validée depuis le module Livraisons');
    if(status==='ready_for_delivery'){
      if(!request.user!.roles.some(role=>finalValidators.includes(role)))throw new HttpError(403,'Seul un responsable commercial peut donner la validation commerciale finale');
      const[invoices]=await c.execute<RowDataPacket[]>("SELECT id,balance_due FROM invoices WHERE sale_id=? AND status<>'cancelled' ORDER BY id DESC LIMIT 1 FOR UPDATE",[saleId]);
      if(!invoices[0])throw new HttpError(409,'Une facture active est requise avant la mise en livraison');
      if(Number(invoices[0].balance_due)>.001)throw new HttpError(409,'La vente doit être entièrement réglée avant de pouvoir être déclarée prête à livrer');
    }
    if(status==='cancelled'){
      if(!request.user!.roles.some(role=>finalValidators.includes(role)))throw new HttpError(403,"Vous n’êtes pas autorisé à annuler une vente");
      if(!reason)throw new HttpError(400,"Le motif d’annulation est obligatoire");
      if(['ready_for_delivery','delivered'].includes(String(sale.status)))throw new HttpError(409,'Une vente prête à livrer ou livrée ne peut plus être annulée');
      const[invoices]=await c.execute<RowDataPacket[]>("SELECT amount_paid FROM invoices WHERE sale_id=? AND status<>'cancelled' FOR UPDATE",[saleId]);
      if(invoices.reduce((sum,row)=>sum+Number(row.amount_paid??0),0)>.001)throw new HttpError(409,'Une vente ayant reçu un paiement ne peut plus être annulée');
      const[deliveries]=await c.execute<RowDataPacket[]>("SELECT id FROM deliveries WHERE sale_id=? AND status<>'cancelled' LIMIT 1 FOR UPDATE",[saleId]);
      if(deliveries[0])throw new HttpError(409,'Une vente dont la livraison est planifiée ne peut plus être annulée');
    }
    await c.execute('UPDATE sales SET status=?,sold_at=IF(?="delivered",NOW(),sold_at),cancellation_reason=IF(?="cancelled",?,cancellation_reason) WHERE id=?',[status,status,status,reason||null,saleId]);
    let nextVehicleStatus=String(sale.vehicle_status??'');
    if(sale.vehicle_id&&['ordered','confirmed','preparation','ready_for_delivery'].includes(status))nextVehicleStatus='sold';
    if(sale.vehicle_id&&status==='cancelled'&&['reserved','sold'].includes(String(sale.vehicle_status)))nextVehicleStatus='available';
    if(sale.vehicle_id&&nextVehicleStatus!==String(sale.vehicle_status)){
      await c.execute('UPDATE vehicles SET status=? WHERE id=?',[nextVehicleStatus,sale.vehicle_id]);
      await c.execute('INSERT INTO vehicle_status_history(vehicle_id,old_status,new_status,changed_by,reason) VALUES(?,?,?,?,?)',[sale.vehicle_id,sale.vehicle_status,nextVehicleStatus,request.user!.sub,status==='cancelled'?reason:'Progression vente']);
    }
    if(status==='cancelled')await c.execute("UPDATE reservations SET status='cancelled' WHERE sale_id=? AND status IN('pending','confirmed')",[saleId]);
    else if(status==='ordered')await c.execute("UPDATE reservations SET status='converted' WHERE sale_id=? AND status IN('pending','confirmed')",[saleId]);
    await audit(c,request,saleId,status==='cancelled'?'sale.cancelled':'sale.status_changed',{status:sale.status,vehicleStatus:sale.vehicle_status},{status,vehicleStatus:nextVehicleStatus,reason:reason||null});
    return{agencyId:String(sale.agency_id),status,vehicleId:sale.vehicle_id?String(sale.vehicle_id):null};
  });
  emitToAgency(result.agencyId,'sales:status',{id:saleId,status:result.status,vehicleId:result.vehicleId});
  if(['cancelled','ready_for_delivery'].includes(result.status))await notifyRoles({agencyId:result.agencyId,roles:result.status==='ready_for_delivery'?['DELIVERY_MANAGER']:['SALES_MANAGER'],includeGlobalRoles:['DIRECTOR','SUPER_ADMIN'],subject:result.status==='ready_for_delivery'?'Vente prête pour livraison':'Vente annulée',message:`La vente ${saleId} est au statut ${result.status}.`,eventType:`sale.${result.status}`,referenceType:'sale',referenceId:saleId,eventKey:`sale.status:${saleId}:${result.status}`});
  return one(saleId,request);
}
