import React,{useEffect,useState} from 'react';
import { AlertTriangle,Package,Plus,Search,ShoppingCart } from 'lucide-react';
import { useNavigate } from 'react-router-dom';
import { useCreatePart,useCreatePurchaseOrder,usePartReferencesQuery,usePartsQuery,usePurchaseOrdersQuery,usePurchaseOrderStatus,useReceivePurchaseOrder } from '../../api/erpHooks';
import { PageHeader } from '../../components/common/PageHeader';import { Button } from '../../components/ui/Button';import { Card } from '../../components/ui/Card';import { Modal } from '../../components/ui/Modal';
import { formatCurrency } from '../../lib/utils';import { useAuthStore } from '../../stores/authStore';import { useUiStore } from '../../stores/uiStore';

const empty={reference:'',oemReference:'',name:'',brand:'',description:'',categoryId:'',supplierId:'',locationId:'',initialQuantity:0,minStock:0,maxStock:0,purchasePrice:0,salePrice:0,obsolete:false,isActive:true};
export const SparePartsPage:React.FC=()=>{
 const agency=useAuthStore(s=>s.currentAgency),toast=useUiStore(s=>s.addToast),nav=useNavigate();const[search,setSearch]=useState(''),[debounced,setDebounced]=useState(''),[category,setCategory]=useState(''),[low,setLow]=useState(false),[createOpen,setCreateOpen]=useState(false),[orderOpen,setOrderOpen]=useState(false),[receiveId,setReceiveId]=useState(''),[form,setForm]=useState(empty),[order,setOrder]=useState({supplierId:'',partId:'',quantity:1,unitPrice:0,taxRate:0,expectedAt:'',notes:''}),[receipt,setReceipt]=useState({locationId:'',itemId:'',quantity:1});
 useEffect(()=>{const t=setTimeout(()=>setDebounced(search),300);return()=>clearTimeout(t)},[search]);
 const refs=usePartReferencesQuery(agency?.id),parts=usePartsQuery(agency?.id,{search:debounced,categoryId:category}),orders=usePurchaseOrdersQuery(agency?.id),create=useCreatePart(),createOrder=useCreatePurchaseOrder(),status=usePurchaseOrderStatus(),receive=useReceivePurchaseOrder();
 const all=parts.data??[],shown=low?all.filter(p=>p.availableStock<=p.minStockAlert):all,value=all.reduce((s,p)=>s+p.physicalStock*p.purchasePriceHT,0);
 const fail=(title:string,e:unknown)=>toast({type:'error',title,description:e instanceof Error?e.message:'Erreur API'}),ok=(title:string)=>toast({type:'success',title});
 async function savePart(e:React.FormEvent){e.preventDefault();try{await create.mutateAsync({...form,agencyId:agency?.id});ok('Référence créée');setCreateOpen(false);setForm(empty)}catch(x){fail('Création impossible',x)}}
 async function saveOrder(e:React.FormEvent){e.preventDefault();try{await createOrder.mutateAsync({agencyId:agency?.id,supplierId:order.supplierId,expectedAt:order.expectedAt||null,notes:order.notes,items:[{partId:order.partId,quantity:order.quantity,unitPrice:order.unitPrice,taxRate:order.taxRate}]});ok('Commande fournisseur créée');setOrderOpen(false)}catch(x){fail('Commande impossible',x)}}
 async function doReceive(e:React.FormEvent){e.preventDefault();const po:any=orders.data?.find((x:any)=>String(x.id)===receiveId);try{const detail=await fetchDetail(receiveId,agency?.id);const item=detail.items.find((x:any)=>String(x.id)===receipt.itemId);await receive.mutateAsync({id:receiveId,agencyId:agency?.id,locationId:receipt.locationId,idempotencyKey:crypto.randomUUID(),items:[{itemId:receipt.itemId,quantity:receipt.quantity}]});ok(`Réception ${po?.order_number??''} enregistrée`);setReceiveId('');if(item)setReceipt(v=>({...v,itemId:''}))}catch(x){fail('Réception impossible',x)}}
 return <div className="space-y-6"><PageHeader title="Magasin Pièces de Rechange (PR) & Stocks" subtitle="Catalogue, stock disponible, approvisionnements et traçabilité multi-emplacement." breadcrumbs={[{label:'Accueil',href:'/dashboard'},{label:'Pièces & Stocks'}]} actions={<div className="flex gap-2"><Button variant="outline" size="sm" icon={<ShoppingCart className="w-4 h-4"/>} onClick={()=>setOrderOpen(true)}>Commander</Button><Button size="sm" icon={<Plus className="w-4 h-4"/>} onClick={()=>setCreateOpen(true)}>Nouvelle référence</Button></div>}/>
 <div className="grid sm:grid-cols-2 lg:grid-cols-4 gap-4">{[['Références',all.length],['Valeur physique HT',formatCurrency(value)],['Sous seuil',all.filter(p=>p.availableStock<=p.minStockAlert).length],['En commande',all.reduce((s,p)=>s+p.pendingOrderQuantity,0)]].map(([l,v])=><Card key={String(l)}><p className="text-xs text-slate-500">{l}</p><p className="text-2xl font-bold mt-1">{v}</p></Card>)}</div>
 <div className="flex flex-wrap gap-2 bg-white border rounded-xl p-3"><div className="relative flex-1 min-w-64"><Search className="absolute left-3 top-2.5 w-4 h-4 text-slate-400"/><input className="w-full pl-9 p-2 text-xs border rounded-lg" value={search} onChange={e=>setSearch(e.target.value)} placeholder="Référence, OEM, désignation, marque ou fournisseur"/></div><select className="p-2 text-xs border rounded-lg" value={category} onChange={e=>setCategory(e.target.value)}><option value="">Toutes catégories</option>{refs.data?.categories?.map((x:any)=><option key={x.id} value={x.id}>{x.name}</option>)}</select><Button variant={low?'primary':'outline'} size="sm" icon={<AlertTriangle className="w-4 h-4"/>} onClick={()=>setLow(!low)}>Alertes</Button></div>
 {parts.isError?<ApiError error={parts.error}/>:<Card padding="none"><div className="overflow-x-auto"><table className="w-full text-xs"><thead className="bg-slate-50 text-left"><tr><th className="p-3">Référence / OEM</th><th>Pièce</th><th>Catégorie / Fournisseur</th><th>Emplacements</th><th>Physique</th><th>Réservé</th><th>Disponible</th><th>En commande</th><th>Prix vente HT</th><th></th></tr></thead><tbody>{shown.map(p=><tr key={p.id} className="border-t hover:bg-red-50/40 cursor-pointer" onClick={()=>nav(`/parts/${p.id}`)}><td className="p-3 font-mono font-bold">{p.reference}<small className="block text-slate-400">{p.oemReference||'OEM —'}</small></td><td><b>{p.name}</b><small className="block text-slate-500">{p.brand}</small></td><td>{p.category}<small className="block text-slate-500">{p.supplier}</small></td><td>{p.stocks?.length?p.stocks.length===1?p.stocks[0].locationName:`${p.stocks.length} emplacements`:'Non affecté'}</td><td>{p.physicalStock}</td><td>{p.reservedStock}</td><td className={p.availableStock<=p.minStockAlert?'font-bold text-red-700':'font-bold'}>{p.availableStock}</td><td>{p.pendingOrderQuantity}</td><td>{formatCurrency(p.sellingPriceHT)}</td><td><Button size="xs" variant="outline" onClick={e=>{e.stopPropagation();nav(`/parts/${p.id}`)}}>Détails</Button></td></tr>)}</tbody></table>{!shown.length&&<p className="p-8 text-center text-slate-500"><Package className="mx-auto mb-2"/>Aucune pièce trouvée</p>}</div></Card>}
 <Card><h2 className="font-bold mb-3">Commandes fournisseurs</h2><div className="overflow-x-auto"><table className="w-full text-xs"><thead><tr className="text-left"><th>Commande</th><th>Fournisseur</th><th>Statut</th><th>Reste à recevoir</th><th>Total</th><th>Actions</th></tr></thead><tbody>{orders.data?.map((o:any)=><tr key={o.id} className="border-t"><td className="py-2 font-mono">{o.order_number}</td><td>{o.supplier_name}</td><td>{o.status}</td><td>{Number(o.pending_quantity)}</td><td>{formatCurrency(Number(o.total))}</td><td className="space-x-1">{o.status==='draft'&&<Button size="xs" onClick={()=>status.mutate({id:String(o.id),agencyId:agency?.id,status:'sent'})}>Envoyer</Button>}{['sent','confirmed','partially_received'].includes(o.status)&&<Button size="xs" onClick={()=>setReceiveId(String(o.id))}>Réceptionner</Button>}</td></tr>)}</tbody></table></div></Card>
 <Modal isOpen={createOpen} onClose={()=>setCreateOpen(false)} title="Nouvelle référence PR" maxWidth="lg"><form onSubmit={savePart} className="grid sm:grid-cols-2 gap-3">{[['Référence interne','reference'],['Référence OEM','oemReference'],['Désignation','name'],['Marque','brand']].map(([l,k])=><Field key={k} label={l} value={(form as any)[k]} onChange={v=>setForm({...form,[k]:v})} required={k==='reference'||k==='name'}/>)}<Select label="Catégorie" value={form.categoryId} onChange={v=>setForm({...form,categoryId:v})} items={refs.data?.categories}/><Select label="Fournisseur principal" value={form.supplierId} onChange={v=>setForm({...form,supplierId:v})} items={refs.data?.suppliers}/><Select label="Emplacement initial" value={form.locationId} onChange={v=>setForm({...form,locationId:v})} items={refs.data?.locations}/>{[['Quantité initiale','initialQuantity'],['Stock minimum','minStock'],['Stock maximum','maxStock'],['Prix achat HT','purchasePrice'],['Prix vente HT','salePrice']].map(([l,k])=><NumberField key={k} label={l} value={(form as any)[k]} onChange={v=>setForm({...form,[k]:v})}/>)}<label className="sm:col-span-2 text-xs font-semibold">Description<textarea className="mt-1 w-full p-2 border rounded" value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/></label><div className="sm:col-span-2 flex justify-end gap-2"><Button variant="outline" type="button" onClick={()=>setCreateOpen(false)}>Annuler</Button><Button type="submit" disabled={create.isPending}>Enregistrer</Button></div></form></Modal>
 <Modal isOpen={orderOpen} onClose={()=>setOrderOpen(false)} title="Créer une commande fournisseur"><form onSubmit={saveOrder} className="space-y-3"><Select label="Fournisseur" value={order.supplierId} onChange={v=>setOrder({...order,supplierId:v})} items={refs.data?.suppliers} required/><Select label="Pièce" value={order.partId} onChange={v=>{const p=all.find(x=>x.id===v);setOrder({...order,partId:v,unitPrice:p?.purchasePriceHT??0})}} items={all} required/><NumberField label="Quantité" value={order.quantity} onChange={v=>setOrder({...order,quantity:v})}/><NumberField label="Prix achat unitaire" value={order.unitPrice} onChange={v=>setOrder({...order,unitPrice:v})}/><NumberField label="Taxe (%)" value={order.taxRate} onChange={v=>setOrder({...order,taxRate:v})}/><div className="flex justify-end"><Button type="submit">Créer le brouillon</Button></div></form></Modal>
 <ReceiveModal id={receiveId} agencyId={agency?.id} refs={refs.data} value={receipt} setValue={setReceipt} onClose={()=>setReceiveId('')} onSubmit={doReceive}/>
 </div>;
};
const Field=({label,value,onChange,required=false}:any)=><label className="text-xs font-semibold">{label}<input required={required} className="mt-1 w-full p-2 border rounded" value={value} onChange={e=>onChange(e.target.value)}/></label>;
const NumberField=({label,value,onChange}:any)=><label className="text-xs font-semibold">{label}<input type="number" min="0" step="0.01" className="mt-1 w-full p-2 border rounded" value={value} onChange={e=>onChange(Number(e.target.value))}/></label>;
const Select=({label,value,onChange,items=[],required=false}:any)=><label className="text-xs font-semibold">{label}<select required={required} className="mt-1 w-full p-2 border rounded" value={value} onChange={e=>onChange(e.target.value)}><option value="">Sélectionner</option>{items?.map((x:any)=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label>;
const ApiError=({error}:any)=><div className="p-4 bg-red-50 text-red-700 rounded-lg">{error instanceof Error?error.message:'Erreur API'}</div>;
const fetchDetail=async(id:string,agencyId?:string)=>{const token=localStorage.getItem('lca-access-token');const base=String(import.meta.env.VITE_API_URL||'/api').replace(/\/$/,'');const r=await fetch(`${base}/purchase-orders/${id}?agencyId=${agencyId}`,{headers:{Authorization:`Bearer ${token}`}});const j=await r.json();if(!r.ok)throw new Error(j.message??'Erreur API');return j};
const ReceiveModal=({id,agencyId,refs,value,setValue,onClose,onSubmit}:any)=>{const[detail,setDetail]=useState<any>(null);useEffect(()=>{if(id)fetchDetail(id,agencyId).then(setDetail).catch(()=>setDetail(null))},[id,agencyId]);return <Modal isOpen={Boolean(id)} onClose={onClose} title="Réception fournisseur"><form onSubmit={onSubmit} className="space-y-3"><Select label="Emplacement" value={value.locationId} onChange={(v:string)=>setValue({...value,locationId:v})} items={refs?.locations} required/><label className="text-xs font-semibold">Ligne<select required className="mt-1 w-full p-2 border rounded" value={value.itemId} onChange={e=>setValue({...value,itemId:e.target.value})}><option value="">Sélectionner</option>{detail?.items?.filter((x:any)=>Number(x.pending_quantity)>0).map((x:any)=><option key={x.id} value={x.id}>{x.reference} — reste {Number(x.pending_quantity)}</option>)}</select></label><NumberField label="Quantité reçue" value={value.quantity} onChange={(v:number)=>setValue({...value,quantity:v})}/><div className="flex justify-end"><Button type="submit">Valider la réception</Button></div></form></Modal>};
