import React,{useEffect,useState} from 'react';
import { AlertTriangle,Package,Plus,Search,ShoppingCart } from 'lucide-react';
import { useNavigate } from 'react-router-dom';
import { useCreatePart,usePartCategoriesQuery,useSavePartCategory,useCreatePurchaseOrder,usePartReferencesQuery,usePartsQuery,usePurchaseOrdersQuery,usePurchaseOrderStatus,useReceivePurchaseOrder } from '../../api/erpHooks';
import { PageHeader } from '../../components/common/PageHeader';import { Button } from '../../components/ui/Button';import { Card } from '../../components/ui/Card';import { Modal } from '../../components/ui/Modal';
import { formatCurrency } from '../../lib/utils';import { useAuthStore } from '../../stores/authStore';import { useUiStore } from '../../stores/uiStore';
import { generateUuid } from '../../lib/uuid';
import { PartLocationsPanel } from './PartLocationsPanel';

const emptyCategory={name:'',code:'',parentId:null as string|null,description:'',isActive:true};
const empty={reference:'',oemReference:'',name:'',brand:'',description:'',categoryId:'',supplierId:'',locationId:'',initialQuantity:0,minStock:0,maxStock:0,purchasePrice:0,salePrice:0,obsolete:false,isActive:true};
const requireInteger=(value:number,label='La quantité',allowZero=false)=>{if(!Number.isFinite(value)||!Number.isInteger(value)||value<0||!allowZero&&value===0)throw new Error(`${label} doit être un nombre entier${allowZero?' positif ou nul':' supérieur à zéro'}.`)};
export const SparePartsPage:React.FC=()=>{
 const agency=useAuthStore(s=>s.currentAgency),can=useAuthStore(s=>s.can),canViewCatalog=can('parts.catalog.view'),canViewStock=can('parts.stock.view'),canManageCatalog=can('parts.catalog.manage'),canViewOrders=can('parts.purchase_order.view'),canOrder=can('parts.purchase_order.create'),canApproveOrder=can('parts.purchase_order.approve'),canReceive=can('parts.purchase_order.receive'),canViewFinancials=can('parts.reporting.view'),toast=useUiStore(s=>s.addToast),nav=useNavigate();const[search,setSearch]=useState(''),[debounced,setDebounced]=useState(''),[category,setCategory]=useState(''),[low,setLow]=useState(false),[createOpen,setCreateOpen]=useState(false),[orderOpen,setOrderOpen]=useState(false),[receiveId,setReceiveId]=useState(''),[form,setForm]=useState(empty),[order,setOrder]=useState({supplierId:'',partId:'',quantity:1,unitPrice:0,taxRate:0,expectedAt:'',notes:''}),[receipt,setReceipt]=useState({locationId:'',itemId:'',quantity:1});
 useEffect(()=>{const t=setTimeout(()=>setDebounced(search),300);return()=>clearTimeout(t)},[search]);
 const [activeTab,setActiveTab]=useState<'catalog'|'categories'|'locations'>('catalog'),[categoryForm,setCategoryForm]=useState({...emptyCategory}),[editCategoryId,setEditCategoryId]=useState<string|undefined>();
 const categoriesQuery=usePartCategoriesQuery(canViewCatalog&&activeTab==='categories'),saveCategory=useSavePartCategory();
 async function submitCategory(e:React.FormEvent){e.preventDefault();try{await saveCategory.mutateAsync({id:editCategoryId,...categoryForm});ok(editCategoryId?'Catégorie modifiée':'Catégorie créée');setEditCategoryId(undefined);setCategoryForm({...emptyCategory})}catch(x){fail('Enregistrement impossible',x)}}
 const refs=usePartReferencesQuery(agency?.id,canViewCatalog),parts=usePartsQuery(agency?.id,{search:debounced,categoryId:category},canViewCatalog),orders=usePurchaseOrdersQuery(agency?.id,canViewOrders),create=useCreatePart(),createOrder=useCreatePurchaseOrder(),status=usePurchaseOrderStatus(),receive=useReceivePurchaseOrder();
 const all=parts.data??[],shown=low&&canViewStock?all.filter(p=>p.availableStock<=p.minStockAlert):all,value=all.reduce((s,p)=>s+p.physicalStock*p.purchasePriceHT,0);
 const fail=(title:string,e:unknown)=>toast({type:'error',title,description:e instanceof Error?e.message:'Erreur API'}),ok=(title:string)=>toast({type:'success',title});
 async function savePart(e:React.FormEvent){e.preventDefault();try{requireInteger(form.initialQuantity,'La quantité initiale',true);requireInteger(form.minStock,'Le stock minimum',true);requireInteger(form.maxStock,'Le stock maximum',true);await create.mutateAsync({...form,agencyId:agency?.id});ok('Référence créée');setCreateOpen(false);setForm(empty)}catch(x){fail('Création impossible',x)}}
 async function saveOrder(e:React.FormEvent){e.preventDefault();try{requireInteger(order.quantity);await createOrder.mutateAsync({agencyId:agency?.id,supplierId:order.supplierId,expectedAt:order.expectedAt||null,notes:order.notes,items:[{partId:order.partId,quantity:order.quantity,unitPrice:order.unitPrice,taxRate:order.taxRate}]});ok('Commande fournisseur créée');setOrderOpen(false)}catch(x){fail('Commande impossible',x)}}
 async function cancelOrder(item:any){const partial=item.status==='partially_received',message=partial?`Confirmer l'annulation du reliquat de ${item.order_number} ?\nLes quantités déjà réceptionnées seront conservées. Seul le reliquat non réceptionné sera annulé.`:`Confirmer l'annulation de la commande fournisseur ${item.order_number} ?${item.status==='sent'||item.status==='confirmed'?'\nCette commande a déjà été transmise au fournisseur.':''}`;if(!window.confirm(message))return;const reason=window.prompt("Motif d'annulation");if(!reason?.trim())return;try{await status.mutateAsync({id:String(item.id),agencyId:agency?.id,status:'cancelled',reason:reason.trim()});ok(partial?'Reliquat annulé':'Commande annulée')}catch(x){fail("Annulation impossible",x)}}
 async function doReceive(e:React.FormEvent){e.preventDefault();const po:any=orders.data?.find((x:any)=>String(x.id)===receiveId);try{requireInteger(receipt.quantity,'La quantité reçue');const detail=await fetchDetail(receiveId,agency?.id);const item=detail.items.find((x:any)=>String(x.id)===receipt.itemId);await receive.mutateAsync({id:receiveId,agencyId:agency?.id,locationId:receipt.locationId,idempotencyKey:generateUuid(),items:[{itemId:receipt.itemId,quantity:receipt.quantity}]});ok(`Réception ${po?.order_number??''} enregistrée`);setReceiveId('');if(item)setReceipt(v=>({...v,itemId:''}))}catch(x){fail('Réception impossible',x)}}
 return <div className="space-y-6"><PageHeader title="Magasin Pièces de Rechange (PR) & Stocks" subtitle="Catalogue, stock disponible, approvisionnements et traçabilité multi-emplacement." breadcrumbs={[{label:'Accueil',href:'/dashboard'},{label:'Pièces & Stocks'}]} actions={<div className="flex gap-2">{canOrder&&<Button variant="outline" size="sm" icon={<ShoppingCart className="w-4 h-4"/>} onClick={()=>setOrderOpen(true)}>Commander</Button>}{canManageCatalog&&<Button size="sm" icon={<Plus className="w-4 h-4"/>} onClick={()=>setCreateOpen(true)}>Nouvelle référence</Button>}</div>}/>
 {canViewCatalog&&<div className="flex flex-wrap gap-2"><Button variant={activeTab==='catalog'?'primary':'outline'} size="sm" onClick={()=>setActiveTab('catalog')}>Catalogue</Button><Button variant={activeTab==='categories'?'primary':'outline'} size="sm" onClick={()=>setActiveTab('categories')}>Catégories</Button><Button variant={activeTab==='locations'?'primary':'outline'} size="sm" onClick={()=>setActiveTab('locations')}>Emplacements</Button></div>}
 {activeTab==='categories'&&canViewCatalog&&<Card><div className="flex items-center justify-between mb-3"><h2 className="font-bold">Catégories de pièces</h2>{canManageCatalog&&<Button size="sm" onClick={()=>{setEditCategoryId(undefined);setCategoryForm({...emptyCategory})}}>Nouvelle catégorie</Button>}</div>{categoriesQuery.isError?<ApiError error={categoriesQuery.error}/>:<div className="overflow-x-auto"><table className="w-full text-xs"><thead><tr className="text-left"><th>Nom</th><th>Code</th><th>Parent</th><th>Statut</th><th></th></tr></thead><tbody>{categoriesQuery.data?.map(item=><tr key={item.id} className="border-t"><td className="py-2">{item.name}</td><td>{item.code}</td><td>{categoriesQuery.data?.find(x=>x.id===String(item.parent_id))?.name??'—'}</td><td>{item.is_active?'Active':'Inactive'}</td><td>{canManageCatalog&&<Button size="xs" variant="outline" onClick={()=>{setEditCategoryId(String(item.id));setCategoryForm({name:item.name,code:item.code,parentId:item.parent_id?String(item.parent_id):null,description:item.description??'',isActive:Boolean(item.is_active)})}}>Modifier</Button>}</td></tr>)}</tbody></table></div>}{canManageCatalog&&<form onSubmit={submitCategory} className="grid sm:grid-cols-2 gap-3 mt-4 border-t pt-4"><Field label="Nom *" required value={categoryForm.name} onChange={(v:string)=>setCategoryForm({...categoryForm,name:v})}/><Field label="Code *" required value={categoryForm.code} onChange={(v:string)=>setCategoryForm({...categoryForm,code:v})}/><Select label="Catégorie parente" value={categoryForm.parentId??''} onChange={(v:string)=>setCategoryForm({...categoryForm,parentId:v||null})} items={categoriesQuery.data?.filter(x=>x.is_active&&String(x.id)!==editCategoryId)}/><Field label="Description" value={categoryForm.description} onChange={(v:string)=>setCategoryForm({...categoryForm,description:v})}/><label className="text-xs font-semibold">Statut<select className="mt-1 w-full p-2 border rounded" value={categoryForm.isActive?'active':'inactive'} onChange={e=>setCategoryForm({...categoryForm,isActive:e.target.value==='active'})}><option value="active">Active</option><option value="inactive">Inactive</option></select></label><div className="flex items-end gap-2"><Button type="submit" disabled={saveCategory.isPending}>{editCategoryId?'Enregistrer':'Créer'}</Button>{editCategoryId&&<Button type="button" variant="outline" onClick={()=>{setEditCategoryId(undefined);setCategoryForm({...emptyCategory})}}>Annuler</Button>}</div></form>}</Card>}
 {activeTab==='locations'&&canViewCatalog&&<PartLocationsPanel agencyId={agency?.id} agencyName={agency?.name} canManage={canManageCatalog}/>}
 <div className="grid sm:grid-cols-2 lg:grid-cols-4 gap-4">{[['Références',all.length],...(canViewFinancials&&canViewStock?[['Valeur physique HT',formatCurrency(value)]]:[]),...(canViewStock?[['Sous seuil',all.filter(p=>p.availableStock<=p.minStockAlert).length]]:[]),...(canViewOrders?[['En commande',all.reduce((s,p)=>s+p.pendingOrderQuantity,0)]]:[])].map(([l,v])=><Card key={String(l)}><p className="text-xs text-slate-500">{l}</p><p className="text-2xl font-bold mt-1">{v}</p></Card>)}</div>
 <div className="flex flex-wrap gap-2 bg-white border rounded-xl p-3"><div className="relative flex-1 min-w-64"><Search className="absolute left-3 top-2.5 w-4 h-4 text-slate-400"/><input className="w-full pl-9 p-2 text-xs border rounded-lg" value={search} onChange={e=>setSearch(e.target.value)} placeholder="Référence, OEM, désignation, marque ou fournisseur"/></div><select className="p-2 text-xs border rounded-lg" value={category} onChange={e=>setCategory(e.target.value)}><option value="">Toutes catégories</option>{refs.data?.categories?.map((x:any)=><option key={x.id} value={x.id}>{x.name}</option>)}</select><Button variant={low?'primary':'outline'} size="sm" icon={<AlertTriangle className="w-4 h-4"/>} onClick={()=>setLow(!low)}>Alertes</Button></div>
 {parts.isError?<ApiError error={parts.error}/>:<Card padding="none"><div className="overflow-x-auto"><table className="w-full text-xs"><thead className="bg-slate-50 text-left"><tr><th className="p-3">Référence / OEM</th><th>Pièce</th><th>Catégorie / Fournisseur</th><th>Emplacements</th><th>Physique</th><th>Réservé</th><th>Disponible</th><th>En commande</th><th>Prix vente HT</th><th></th></tr></thead><tbody>{shown.map(p=><tr key={p.id} className="border-t hover:bg-red-50/40 cursor-pointer" onClick={()=>nav(`/parts/${p.id}`)}><td className="p-3 font-mono font-bold">{p.reference}<small className="block text-slate-400">{p.oemReference||'OEM —'}</small></td><td><b>{p.name}</b><small className="block text-slate-500">{p.brand}</small></td><td>{p.category}<small className="block text-slate-500">{p.supplier}</small></td><td>{p.stocks?.length?p.stocks.length===1?p.stocks[0].locationName:`${p.stocks.length} emplacements`:'Non affecté'}</td><td>{p.physicalStock}</td><td>{p.reservedStock}</td><td className={p.availableStock<=p.minStockAlert?'font-bold text-red-700':'font-bold'}>{p.availableStock}</td><td>{p.pendingOrderQuantity}</td><td>{formatCurrency(p.sellingPriceHT)}</td><td><Button size="xs" variant="outline" onClick={e=>{e.stopPropagation();nav(`/parts/${p.id}`)}}>Détails</Button></td></tr>)}</tbody></table>{!shown.length&&<p className="p-8 text-center text-slate-500"><Package className="mx-auto mb-2"/>Aucune pièce trouvée</p>}</div></Card>}
 {canViewOrders&&<Card><h2 className="font-bold mb-3">Commandes fournisseurs</h2><div className="overflow-x-auto"><table className="w-full text-xs"><thead><tr className="text-left"><th>Commande</th><th>Fournisseur</th><th>Statut</th><th>Reste à recevoir</th>{canViewFinancials&&<th>Total</th>}<th>Actions</th></tr></thead><tbody>{orders.data?.map((o:any)=><tr key={o.id} className="border-t"><td className="py-2 font-mono">{o.order_number}</td><td>{o.supplier_name}</td><td>{o.status}</td><td>{Number(o.pending_quantity)}</td>{canViewFinancials&&<td>{formatCurrency(Number(o.total))}</td>}<td className="space-x-1">{canApproveOrder&&o.status==='draft'&&<Button size="xs" onClick={()=>status.mutate({id:String(o.id),agencyId:agency?.id,status:'sent'})}>Envoyer</Button>}{canReceive&&['sent','confirmed','partially_received'].includes(o.status)&&<Button size="xs" onClick={()=>setReceiveId(String(o.id))}>Réceptionner</Button>}{canApproveOrder&&['draft','sent','confirmed','partially_received'].includes(o.status)&&<Button size="xs" variant="danger" onClick={()=>void cancelOrder(o)}>{o.status==='partially_received'?'Annuler le reliquat':'Annuler la commande'}</Button>}</td></tr>)}</tbody></table></div></Card>}
 <Modal isOpen={createOpen} onClose={()=>setCreateOpen(false)} title="Nouvelle référence PR" maxWidth="lg"><form onSubmit={savePart} className="grid sm:grid-cols-2 gap-3">{[['Référence interne','reference'],['Référence OEM','oemReference'],['Désignation','name'],['Marque','brand']].map(([l,k])=><Field key={k} label={l} value={(form as any)[k]} onChange={v=>setForm({...form,[k]:v})} required={k==='reference'||k==='name'}/>)}<Select label="Catégorie" value={form.categoryId} onChange={v=>setForm({...form,categoryId:v})} items={refs.data?.categories}/><Select label="Fournisseur principal" value={form.supplierId} onChange={v=>setForm({...form,supplierId:v})} items={refs.data?.suppliers}/><Select label="Emplacement initial" value={form.locationId} onChange={v=>setForm({...form,locationId:v})} items={refs.data?.locations}/>{refs.isSuccess&&!refs.data?.locations?.length&&<p className="sm:col-span-2 text-xs text-amber-700">Aucun emplacement actif pour cette agence.</p>}{refs.isError&&<p className="sm:col-span-2 text-xs text-red-700">Chargement des emplacements impossible : {refs.error.message}</p>}{[['Quantité initiale','initialQuantity'],['Stock minimum','minStock'],['Stock maximum','maxStock'],['Prix achat HT','purchasePrice'],['Prix vente HT','salePrice']].map(([l,k])=><NumberField key={k} label={l} value={(form as any)[k]} onChange={v=>setForm({...form,[k]:v})}/>)}<label className="sm:col-span-2 text-xs font-semibold">Description<textarea className="mt-1 w-full p-2 border rounded" value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/></label><div className="sm:col-span-2 flex justify-end gap-2"><Button variant="outline" type="button" onClick={()=>setCreateOpen(false)}>Annuler</Button><Button type="submit" disabled={create.isPending}>Enregistrer</Button></div></form></Modal>
 <Modal isOpen={orderOpen} onClose={()=>setOrderOpen(false)} title="Créer une commande fournisseur"><form onSubmit={saveOrder} className="space-y-3"><Select label="Fournisseur" value={order.supplierId} onChange={v=>setOrder({...order,supplierId:v})} items={refs.data?.suppliers} required/><Select label="Pièce" value={order.partId} onChange={v=>{const p=all.find(x=>x.id===v);setOrder({...order,partId:v,unitPrice:p?.purchasePriceHT??0})}} items={all} required/><NumberField label="Quantité" value={order.quantity} onChange={v=>setOrder({...order,quantity:v})}/><NumberField label="Prix achat unitaire" value={order.unitPrice} onChange={v=>setOrder({...order,unitPrice:v})}/><NumberField label="Taxe (%)" value={order.taxRate} onChange={v=>setOrder({...order,taxRate:v})}/><div className="flex justify-end"><Button type="submit">Créer le brouillon</Button></div></form></Modal>
 <ReceiveModal id={receiveId} agencyId={agency?.id} refs={refs.data} value={receipt} setValue={setReceipt} onClose={()=>setReceiveId('')} onSubmit={doReceive}/>
 </div>;
};
const Field=({label,value,onChange,required=false}:any)=><label className="text-xs font-semibold">{label}<input required={required} className="mt-1 w-full p-2 border rounded" value={value} onChange={e=>onChange(e.target.value)}/></label>;
const NumberField=({label,value,onChange}:any)=>{const whole=/Quantité|Stock/.test(label);return <label className="text-xs font-semibold">{label}<input type="number" min="0" step={whole?'1':'0.01'} className="mt-1 w-full p-2 border rounded" value={value} onChange={e=>onChange(Number(e.target.value))}/></label>};
const Select=({label,value,onChange,items=[],required=false}:any)=><label className="text-xs font-semibold">{label}<select required={required} className="mt-1 w-full p-2 border rounded" value={value} onChange={e=>onChange(e.target.value)}><option value="">Sélectionner</option>{items?.map((x:any)=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label>;
const ApiError=({error}:any)=><div className="p-4 bg-red-50 text-red-700 rounded-lg">{error instanceof Error?error.message:'Erreur API'}</div>;
const fetchDetail=async(id:string,agencyId?:string)=>{const token=localStorage.getItem('lca-access-token');const base=String(import.meta.env.VITE_API_URL||'/api').replace(/\/$/,'');const r=await fetch(`${base}/purchase-orders/${id}?agencyId=${agencyId}`,{headers:{Authorization:`Bearer ${token}`}});const j=await r.json();if(!r.ok)throw new Error(j.message??'Erreur API');return j};
const ReceiveModal=({id,agencyId,refs,value,setValue,onClose,onSubmit}:any)=>{const[detail,setDetail]=useState<any>(null);useEffect(()=>{if(id)fetchDetail(id,agencyId).then(setDetail).catch(()=>setDetail(null))},[id,agencyId]);return <Modal isOpen={Boolean(id)} onClose={onClose} title="Réception fournisseur"><form onSubmit={onSubmit} className="space-y-3"><Select label="Emplacement" value={value.locationId} onChange={(v:string)=>setValue({...value,locationId:v})} items={refs?.locations} required/><label className="text-xs font-semibold">Ligne<select required className="mt-1 w-full p-2 border rounded" value={value.itemId} onChange={e=>setValue({...value,itemId:e.target.value})}><option value="">Sélectionner</option>{detail?.items?.filter((x:any)=>Number(x.pending_quantity)>0).map((x:any)=><option key={x.id} value={x.id}>{x.reference} — reste {Number(x.pending_quantity)}</option>)}</select></label><NumberField label="Quantité reçue" value={value.quantity} onChange={(v:number)=>setValue({...value,quantity:v})}/><div className="flex justify-end"><Button type="submit">Valider la réception</Button></div></form></Modal>};
