import { Router, type Request } from 'express';
import type { ResultSetHeader, RowDataPacket } from 'mysql2/promise';
import { execute, query, transaction } from '../../config/database.js';
import { requireAnyPermission, requirePermission } from '../../middleware/require-permission.js';
import { assertPermission } from '../rbac/rbac.service.js';
import { asyncHandler } from '../../middleware/error-handler.js';
import { HttpError } from '../../shared/http-error.js';
import { notifyCrm } from './crm.notifications.js';
import { resolveLeadAssignee, validateLeadAssignee } from './crm-assignment.js';

export const crmRouter=Router();

const stages=['new','contacted','qualified','appointment','test_drive','offer','negotiation','won','lost'] as const;
const activityTypes=['call','email','task','appointment','test_drive','note','other'] as const;
const activityStatuses=['planned','completed','cancelled'] as const;
const leadSources=['Passage Showroom','Web','Téléphone','LeBonCoin','Parrainage','Campagne Marketing'] as const;
const priorities=['low','medium','high','urgent'] as const;

interface LeadRow extends RowDataPacket { lead_id:string; opportunity_id:string; agency_id:string|null; assigned_user_id:string|null; assigned_user_name:string }
const leadSelect=`SELECT l.id lead_id,o.id opportunity_id,l.customer_id,l.first_name,l.last_name,l.company_name,l.email,l.phone,l.source,l.status lead_status,l.priority,l.assigned_user_id,l.created_by,o.title,o.stage,o.expected_value,o.probability,o.expected_close_date,o.lost_reason,o.notes,l.created_at,l.updated_at,CONCAT_WS(' ',u.first_name,u.last_name) assigned_user_name,CONCAT_WS(' ',creator.first_name,creator.last_name) created_by_name,COALESCE(u.agency_id,creator.agency_id) agency_id,a.name agency_name,EXISTS(SELECT 1 FROM follow_ups f JOIN activities act ON act.id=f.activity_id WHERE f.lead_id=l.id AND f.opportunity_id=o.id AND act.type='appointment' AND f.status IN('pending','completed')) has_valid_appointment,(SELECT td.status FROM showroom_test_drives td WHERE td.lead_id=l.id AND td.status<>'cancelled' ORDER BY td.id DESC LIMIT 1) test_drive_status,(SELECT td.returned_at FROM showroom_test_drives td WHERE td.lead_id=l.id AND td.status<>'cancelled' ORDER BY td.id DESC LIMIT 1) test_drive_returned_at FROM leads l JOIN opportunities o ON o.lead_id=l.id LEFT JOIN users u ON u.id=l.assigned_user_id LEFT JOIN users creator ON creator.id=l.created_by LEFT JOIN agencies a ON a.id=COALESCE(u.agency_id,creator.agency_id)`;
const mapLead=(row:LeadRow)=>({id:String(row.lead_id),opportunityId:String(row.opportunity_id),customerId:row.customer_id==null?null:String(row.customer_id),firstName:row.first_name??'',lastName:row.last_name??'',companyName:row.company_name??'',email:row.email??'',phone:row.phone??'',source:row.source??'',leadStatus:row.lead_status,priority:row.priority,assignedUserId:row.assigned_user_id==null?null:String(row.assigned_user_id),assignedUserName:row.assigned_user_name??'',createdById:row.created_by==null?null:String(row.created_by),createdByName:row.created_by_name??'',agencyId:row.agency_id==null?null:String(row.agency_id),agencyName:row.agency_name??'',title:row.title,stage:row.stage,expectedValue:row.expected_value,probability:row.probability,expectedCloseDate:row.expected_close_date,lostReason:row.lost_reason,notes:row.notes??'',canStartTestDrive:row.stage==='appointment'&&Boolean(row.has_valid_appointment),testDriveStatus:row.test_drive_status??null,testDriveReturnedAt:row.test_drive_returned_at??null,canCreateQuotation:row.stage==='test_drive'&&row.test_drive_status==='completed'&&Boolean(row.test_drive_returned_at),createdAt:row.created_at,updatedAt:row.updated_at});

const text=(value:unknown,name:string,max=255,required=false)=>{if(value==null||value===''){if(required)throw new HttpError(400,`${name} est requis`);return null;}if(typeof value!=='string')throw new HttpError(400,`${name} doit être une chaîne`);const result=value.trim();if(!result&&required)throw new HttpError(400,`${name} est requis`);if(result.length>max)throw new HttpError(400,`${name} est trop long`);return result||null;};
const numberValue=(value:unknown,name:string,min:number,max:number)=>{if(value==null||value==='')return null;const result=Number(value);if(!Number.isFinite(result)||result<min||result>max)throw new HttpError(400,`${name} est invalide`);return result;};
const validEmail=(value:string|null)=>{if(value&&!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(value))throw new HttpError(400,"L’adresse e-mail n’est pas valide.");return value;};
const validPhone=(value:string|null)=>{if(value){const digits=value.replace(/\D/g,'');if(!/^[+\d\s().-]+$/.test(value)||digits.length<6||digits.length>15)throw new HttpError(400,"Le numéro de téléphone n’est pas valide.");}return value;};
const leadStatusForStage=(stage:string)=>stage==='won'?'converted':stage==='lost'?'lost':['new','contacted','qualified'].includes(stage)?stage:'qualified';
const dateValue=(value:unknown,name:string)=>{if(value==null||value==='')return null;if(typeof value!=='string'||!/^\d{4}-\d{2}-\d{2}$/.test(value)||Number.isNaN(Date.parse(`${value}T00:00:00Z`)))throw new HttpError(400,`${name} doit être au format AAAA-MM-JJ`);return value;};
const routeId=(value:string|string[]|undefined)=>{const id=Array.isArray(value)?value[0]:value;if(!id||!/^\d+$/.test(id))throw new HttpError(400,'Identifiant invalide');return id;};
export function crmLeadScope(request:Request,permission:string,alias='COALESCE(u.agency_id,creator.agency_id)',applyFilters=false){
  const requestedAgency=typeof request.query.agencyId==='string'?request.query.agencyId:null;
  const requestedCommercial=typeof request.query.commercialId==='string'?request.query.commercialId:null;
  const permissionScope=request.rbac?.isSuperAdmin?'GLOBAL':request.rbac?.permissions.get(permission);
  if(permissionScope==='GLOBAL')return applyFilters?{sql:`(? IS NULL OR ${alias}=?) AND (? IS NULL OR l.assigned_user_id=?)`,params:[requestedAgency,requestedAgency,requestedCommercial,requestedCommercial]}:{sql:'1=1',params:[]};
  const agencyId=request.user?.agencyId;
  if(!agencyId)throw new HttpError(403,'Aucune agence associée à cet utilisateur');
  if(permissionScope==='OWN'){
    if(applyFilters&&requestedCommercial&&requestedCommercial!==request.user?.sub)throw new HttpError(403,'Cet utilisateur ne peut consulter que son portefeuille');
    return{sql:`${alias}=? AND l.assigned_user_id=?`,params:[agencyId,request.user?.sub]};
  }
  if(permissionScope==='CONCESSION')return applyFilters?{sql:`${alias} IN (SELECT id FROM agencies WHERE concession_id=(SELECT concession_id FROM agencies WHERE id=?)) AND (? IS NULL OR l.assigned_user_id=?)`,params:[agencyId,requestedCommercial,requestedCommercial]}:{sql:`${alias} IN (SELECT id FROM agencies WHERE concession_id=(SELECT concession_id FROM agencies WHERE id=?))`,params:[agencyId]};
  return applyFilters?{sql:`${alias}=? AND (? IS NULL OR l.assigned_user_id=?)`,params:[agencyId,requestedCommercial,requestedCommercial]}:{sql:`${alias}=?`,params:[agencyId]};
}

async function accessibleLead(id:string,request:Request,permission='crm.prospect.view'){const scoped=crmLeadScope(request,permission);const[row]=await query<LeadRow[]>(`${leadSelect} WHERE l.id=? AND ${scoped.sql}`,[id,...scoped.params]);if(!row)throw new HttpError(404,'Prospect introuvable');return row;}
async function leadById(id:string){const[row]=await query<LeadRow[]>(`${leadSelect} WHERE l.id=?`,[id]);if(!row)throw new HttpError(404,'Prospect introuvable');return row;}

crmRouter.get('/leads',requirePermission('crm.prospect.view'),asyncHandler(async(request,response)=>{
  const scoped=crmLeadScope(request,'crm.prospect.view','COALESCE(u.agency_id,creator.agency_id)',true);const search=typeof request.query.search==='string'?request.query.search.trim():'';const term=`%${search}%`;const normalizedPhone=search.replace(/[^\d+]/g,'');const phoneTerm=`%${normalizedPhone}%`;const stage=typeof request.query.stage==='string'?request.query.stage:null;if(stage&&!stages.includes(stage as typeof stages[number]))throw new HttpError(400,'Étape CRM invalide');const priority=typeof request.query.priority==='string'?request.query.priority:null;if(priority&&!priorities.includes(priority as typeof priorities[number]))throw new HttpError(400,'Priorité CRM invalide');
  const rows=await query<LeadRow[]>(`${leadSelect} WHERE ${scoped.sql} AND (?='' OR l.first_name LIKE ? OR l.last_name LIKE ? OR l.company_name LIKE ? OR l.email LIKE ? OR o.title LIKE ? OR (?<>'' AND REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(l.phone,' ',''),'-',''),'.',''),'(',''),')','') LIKE ?)) AND (? IS NULL OR o.stage=?) AND (? IS NULL OR l.priority=?) ORDER BY l.updated_at DESC LIMIT 200`,[...scoped.params,search,term,term,term,term,term,normalizedPhone,phoneTerm,stage,stage,priority,priority]);response.json(rows.map(mapLead));
}));

crmRouter.get('/leads/:id',requirePermission('crm.prospect.view'),asyncHandler(async(request,response)=>{response.json(mapLead(await accessibleLead(routeId(request.params.id),request)));}));

crmRouter.post('/leads',requirePermission('crm.prospect.create'),asyncHandler(async(request,response)=>{
  const body=request.body as Record<string,unknown>;const title=text(body.title,'title',200,true)!;const firstName=text(body.firstName,'firstName',100);const lastName=text(body.lastName,'lastName',100);const companyName=text(body.companyName,'companyName',200);const email=validEmail(text(body.email,'email',190));const phone=validPhone(text(body.phone,'phone',50));if(!lastName&&!companyName)throw new HttpError(400,'Un nom ou une société est requis');if(!phone&&!email)throw new HttpError(400,'Un téléphone ou un e-mail est requis');
  if(Object.hasOwn(body,'stage')){const requestedStage=text(body.stage,'stage',30);if(requestedStage&&!stages.includes(requestedStage as typeof stages[number]))throw new HttpError(400,'Étape CRM invalide');}
  const source=text(body.source,'source',100);if(source&&!leadSources.includes(source as typeof leadSources[number]))throw new HttpError(400,'Source du prospect invalide');const priority=text(body.priority,'priority',20)??'medium';if(!priorities.includes(priority as typeof priorities[number]))throw new HttpError(400,'Priorité CRM invalide');const stage=text(body.stage,'stage',30)??'new';if(stage!=='new')throw new HttpError(409,'Un prospect doit commencer à l’étape Nouveau');if(body.assignedUserId!=null&&body.assignedUserId!=='')await assertPermission(request,'crm.prospect.assign');const assigned=await resolveLeadAssignee(body.assignedUserId,request),assignedUserId=assigned.assignedUserId;const expectedValue=numberValue(body.expectedValue,'expectedValue',0,9999999999999999);const probability=numberValue(body.probability,'probability',0,100);const expectedCloseDate=dateValue(body.expectedCloseDate,'expectedCloseDate');const notes=text(body.notes,'notes',10000),leadStatus=leadStatusForStage(stage);
  const created=await transaction(async connection=>{const[lead]=await connection.execute<ResultSetHeader>(`INSERT INTO leads(assigned_user_id,created_by,source,status,priority,first_name,last_name,company_name,email,phone,notes) VALUES(?,?,?,?,?,?,?,?,?,?,?)`,[assignedUserId,request.user!.sub,source,leadStatus,priority,firstName,lastName,companyName,email,phone,notes]);const[opportunity]=await connection.execute<ResultSetHeader>(`INSERT INTO opportunities(lead_id,assigned_user_id,title,stage,expected_value,probability,expected_close_date,notes) VALUES(?,?,?,?,?,?,?,?)`,[lead.insertId,assignedUserId,title,stage,expectedValue,probability,expectedCloseDate,notes]);return{id:String(lead.insertId),opportunityId:String(opportunity.insertId)};});
  await notifyCrm({leadId:created.id,agencyId:assigned.agencyId,assignedUserId,actorUserId:request.user!.sub,subject:'Nouveau prospect',message:assignedUserId?`Le prospect ${[firstName,lastName].filter(Boolean).join(' ')||companyName} vous a été attribué.`:`Le prospect ${[firstName,lastName].filter(Boolean).join(' ')||companyName} est à affecter.`});response.status(201).json(mapLead(await leadById(created.id)));
}));

crmRouter.patch('/leads/:id',requireAnyPermission(['crm.prospect.update','crm.prospect.assign']),asyncHandler(async(request,response)=>{
  const leadId=routeId(request.params.id);const body=request.body as Record<string,unknown>;const assignmentOnly=Object.keys(body).length===1&&Object.hasOwn(body,'assignedUserId');if(assignmentOnly)await assertPermission(request,'crm.prospect.assign');else await assertPermission(request,'crm.prospect.update');if(Object.hasOwn(body,'assignedUserId'))await assertPermission(request,'crm.prospect.assign');const current=await accessibleLead(leadId,request,assignmentOnly?'crm.prospect.assign':'crm.prospect.update');const leadFields:Record<string,string>={firstName:'first_name',lastName:'last_name',companyName:'company_name',email:'email',phone:'phone',source:'source',priority:'priority',notes:'notes'};const opportunityFields:Record<string,string>={title:'title',expectedValue:'expected_value',probability:'probability',expectedCloseDate:'expected_close_date'};const leadSets:string[]=[],leadValues:any[]=[],oppSets:string[]=[],oppValues:any[]=[];
  for(const[key,column]of Object.entries(leadFields))if(Object.hasOwn(body,key)){let value=text(body[key],key,key==='notes'?10000:key==='companyName'?200:key==='email'?190:key==='phone'?50:100);if(key==='email')value=validEmail(value);if(key==='phone')value=validPhone(value);if(key==='source'&&value&&!leadSources.includes(value as typeof leadSources[number]))throw new HttpError(400,'Source du prospect invalide');if(key==='priority'&&!priorities.includes(value as typeof priorities[number]))throw new HttpError(400,'Priorité CRM invalide');leadSets.push(`${column}=?`);leadValues.push(value);}
  for(const[key,column]of Object.entries(opportunityFields))if(Object.hasOwn(body,key)){const value=key==='expectedValue'?numberValue(body[key],key,0,9999999999999999):key==='probability'?numberValue(body[key],key,0,100):key==='expectedCloseDate'?dateValue(body[key],key):text(body[key],key,200,key==='title');oppSets.push(`${column}=?`);oppValues.push(value);}
  let assignedUserId=current.assigned_user_id==null?null:String(current.assigned_user_id),agencyId=current.agency_id==null?null:String(current.agency_id);if(Object.hasOwn(body,'assignedUserId')){assignedUserId=text(body.assignedUserId,'assignedUserId',30,true)!;agencyId=(await validateLeadAssignee(assignedUserId,request)).agencyId;leadSets.push('assigned_user_id=?');leadValues.push(assignedUserId);oppSets.push('assigned_user_id=?');oppValues.push(assignedUserId);}
  if(!leadSets.length&&!oppSets.length)throw new HttpError(400,'Aucun champ modifiable fourni');await transaction(async connection=>{if(leadSets.length)await connection.execute(`UPDATE leads SET ${leadSets.join(',')} WHERE id=?`,[...leadValues,leadId]);if(oppSets.length)await connection.execute(`UPDATE opportunities SET ${oppSets.join(',')} WHERE lead_id=?`,[...oppValues,leadId]);const reassigned=assignedUserId!==String(current.assigned_user_id??'');await connection.execute(`INSERT INTO activities(customer_id,lead_id,opportunity_id,assigned_user_id,type,subject,description,status,completed_at) VALUES(?,?,?,?,?,?,?,'completed',NOW())`,[current.customer_id,leadId,current.opportunity_id,request.user!.sub,'note',reassigned?'Réaffectation commerciale':'Fiche prospect mise à jour',reassigned?`Commercial : ${current.assigned_user_id??'non affecté'} → ${assignedUserId}`:`Champs modifiés : ${[...Object.keys(body)].join(', ')}`]);});
  if(assignedUserId&&assignedUserId!==String(current.assigned_user_id??''))await notifyCrm({leadId,agencyId,assignedUserId,actorUserId:request.user!.sub,subject:'Prospect réattribué',message:`Le prospect #${leadId} vous a été attribué.`});response.json(mapLead(await leadById(leadId)));
}));

crmRouter.patch('/leads/:id/stage',requirePermission('crm.pipeline.advance'),asyncHandler(async(request,response)=>{
  const leadId=routeId(request.params.id);const current=await accessibleLead(leadId,request,'crm.pipeline.advance');const stage=text(request.body?.stage,'stage',30,true)!;if(!stages.includes(stage as typeof stages[number]))throw new HttpError(400,'Étape CRM invalide');const lostReason=text(request.body?.lostReason,'lostReason',255);if(stage==='lost'&&!lostReason)throw new HttpError(400,'Le motif de perte est obligatoire');
  if(['appointment','test_drive','offer','won'].includes(stage))throw new HttpError(409,'Cette étape doit être produite par son action métier');
  if(stage==='contacted'&&current.stage!=='new')throw new HttpError(409,'Seul un nouveau prospect peut être marqué contacté');
  if(stage==='qualified'){
    if(current.stage!=='contacted')throw new HttpError(409,'Le prospect doit d’abord être contacté');
    if(!current.assigned_user_id||!current.title||(!current.phone&&!current.email)||Number(current.expected_value??0)<=0)throw new HttpError(409,'Qualification impossible : commercial, besoin, coordonnées et budget sont requis');
  }
  if(stage==='negotiation'){
    if(current.stage!=='offer')throw new HttpError(409,'Une offre doit précéder la négociation');
    const[quotation]=await query<RowDataPacket[]>(`SELECT id FROM quotations WHERE opportunity_id=? AND status NOT IN('rejected','expired','cancelled') LIMIT 1`,[current.opportunity_id]);if(!quotation)throw new HttpError(409,'Un devis réel est requis pour négocier');
  }
  if(stage==='lost'){await assertPermission(request,'crm.prospect.lose');if(current.stage==='won')throw new HttpError(409,'Une opportunité gagnée ne peut pas être perdue');}
  await transaction(async connection=>{
    await connection.execute(`UPDATE opportunities SET stage=?,lost_reason=?,lost_at=IF(?='lost',NOW(),NULL) WHERE lead_id=?`,[stage,stage==='lost'?lostReason:null,stage,leadId]);
    await connection.execute(`UPDATE leads SET status=? WHERE id=?`,[leadStatusForStage(stage),leadId]);
    if(stage==='negotiation')await connection.execute("UPDATE quotations SET status='negotiation' WHERE opportunity_id=? AND status IN('draft','sent')",[current.opportunity_id]);
    await connection.execute(`INSERT INTO activities(customer_id,lead_id,opportunity_id,assigned_user_id,type,subject,description,status,completed_at) VALUES(?,?,?,?,?,'Étape CRM mise à jour',?,'completed',NOW())`,[current.customer_id,leadId,current.opportunity_id,request.user!.sub,'note',`Étape : ${current.stage} → ${stage}${lostReason?` — Motif : ${lostReason}`:''}`]);
  });
  await notifyCrm({leadId,agencyId:current.agency_id==null?null:String(current.agency_id),assignedUserId:current.assigned_user_id==null?null:String(current.assigned_user_id),actorUserId:request.user!.sub,subject:'Étape CRM mise à jour',message:`Le prospect #${leadId} est maintenant à l’étape ${stage}.`});response.json(mapLead(await accessibleLead(leadId,request,'crm.pipeline.advance')));
}));

crmRouter.post('/leads/:id/appointments',requirePermission('crm.appointment.create'),asyncHandler(async(request,response)=>{
  const leadId=routeId(request.params.id),current=await accessibleLead(leadId,request,'crm.appointment.create');if(!['qualified','appointment'].includes(current.stage))throw new HttpError(409,'Le prospect doit être qualifié avant de planifier un rendez-vous');if(!current.assigned_user_id)throw new HttpError(409,'Un commercial doit être affecté');
  const scheduledAt=text(request.body?.scheduledAt,'scheduledAt',30,true)!,parsed=new Date(scheduledAt);if(Number.isNaN(parsed.getTime())||parsed<=new Date())throw new HttpError(400,'La date du rendez-vous doit être future');const subject=text(request.body?.subject,'subject',255)??'Rendez-vous commercial',description=text(request.body?.description,'description',10000);
  const activityId=await transaction(async connection=>{const[result]=await connection.execute<ResultSetHeader>(`INSERT INTO activities(customer_id,lead_id,opportunity_id,assigned_user_id,type,subject,description,status,due_at) VALUES(?,?,?,?,?,?,?,'planned',?)`,[current.customer_id,leadId,current.opportunity_id,request.user!.sub,'appointment',subject,`${description??''}${description?' — ':''}Étape : ${current.stage} → appointment`,parsed]);await connection.execute(`INSERT INTO follow_ups(customer_id,lead_id,opportunity_id,assigned_user_id,activity_id,scheduled_at,status,notes) VALUES(?,?,?,?,?,?,'pending',?)`,[current.customer_id,leadId,current.opportunity_id,current.assigned_user_id,result.insertId,parsed,description]);await connection.execute("UPDATE opportunities SET stage='appointment' WHERE id=?",[current.opportunity_id]);return String(result.insertId)});
  await notifyCrm({leadId,agencyId:current.agency_id==null?null:String(current.agency_id),assignedUserId:current.assigned_user_id==null?null:String(current.assigned_user_id),actorUserId:request.user!.sub,subject:'Rendez-vous commercial planifié',message:`Un rendez-vous a été planifié pour le prospect #${leadId}.`});
  response.status(201).json({id:activityId,leadId,stage:'appointment',scheduledAt:parsed.toISOString()});
}));

crmRouter.get('/leads/:id/activities',requirePermission('crm.activity.view'),asyncHandler(async(request,response)=>{const leadId=routeId(request.params.id);await accessibleLead(leadId,request,'crm.activity.view');const rows=await query<RowDataPacket[]>(`SELECT a.id,a.customer_id,a.lead_id,a.opportunity_id,a.assigned_user_id,a.type,a.subject,a.description,a.status,a.due_at,a.completed_at,a.created_at,CONCAT_WS(' ',u.first_name,u.last_name) assigned_user_name FROM activities a LEFT JOIN users u ON u.id=a.assigned_user_id WHERE a.lead_id=? ORDER BY a.created_at DESC LIMIT 200`,[leadId]);response.json(rows.map(row=>({id:String(row.id),customerId:row.customer_id==null?null:String(row.customer_id),leadId:String(row.lead_id),opportunityId:row.opportunity_id==null?null:String(row.opportunity_id),assignedUserId:row.assigned_user_id==null?null:String(row.assigned_user_id),assignedUserName:row.assigned_user_name??'',type:row.type,subject:row.subject,description:row.description??'',status:row.status,dueAt:row.due_at,completedAt:row.completed_at,createdAt:row.created_at})));}));

crmRouter.post('/activities',requirePermission('crm.activity.create'),asyncHandler(async(request,response)=>{const body=request.body as Record<string,unknown>;const leadId=text(body.leadId,'leadId',30,true)!;const lead=await accessibleLead(leadId,request,'crm.activity.create');const type=text(body.type,'type',30,true)!;if(!activityTypes.includes(type as typeof activityTypes[number]))throw new HttpError(400,"Type d'activité invalide");const status=text(body.status,'status',30)??'completed';if(!activityStatuses.includes(status as typeof activityStatuses[number]))throw new HttpError(400,"Statut d'activité invalide");const subject=text(body.subject,'subject',255,true)!;const description=text(body.description,'description',10000);const dueAt=body.dueAt==null||body.dueAt===''?null:new Date(String(body.dueAt));if(dueAt&&Number.isNaN(dueAt.getTime()))throw new HttpError(400,'dueAt est invalide');const result=await execute(`INSERT INTO activities(customer_id,lead_id,opportunity_id,assigned_user_id,type,subject,description,status,due_at,completed_at) VALUES(?,?,?,?,?,?,?,?,?,?)`,[lead.customer_id??null,leadId,lead.opportunity_id,request.user!.sub,type,subject,description,status,dueAt,status==='completed'?new Date():null]);await notifyCrm({leadId,agencyId:lead.agency_id==null?null:String(lead.agency_id),assignedUserId:lead.assigned_user_id==null?null:String(lead.assigned_user_id),actorUserId:request.user!.sub,subject:'Nouvelle activité CRM',message:`${subject} a été ajouté au prospect #${leadId}.`});response.status(201).json({id:String(result.insertId)});}));
