import{useMutation,useQuery,useQueryClient}from'@tanstack/react-query';import{apiRequest}from'../services/apiClient';import{useAuthStore}from'../stores/authStore';import type{DocumentEntityResult,DocumentEntityType,DocumentFilters,DocumentListResponse,DocumentRecord}from'../types/documents';
const params=(values:object)=>{const p=new URLSearchParams();for(const[k,v]of Object.entries(values))if(v!==undefined&&v!==null&&v!=='')p.set(k,String(v));return p.toString()};
export const documentKeys={all:['documents']as const,list:(userId:string,agencyId:string,f:DocumentFilters)=>['documents',userId,agencyId,'list',f]as const,detail:(userId:string,agencyId:string,id:string)=>['documents',userId,agencyId,'detail',id]as const};
const context=()=>{const state=useAuthStore();return{userId:state.currentUser?.id??'',agencyId:state.currentAgency?.id??'',can:state.can}};
export function useDocumentsQuery(filters:DocumentFilters){const{userId,agencyId,can}=context();return useQuery({queryKey:documentKeys.list(userId,agencyId,filters),queryFn:()=>apiRequest<DocumentListResponse>(`/documents?${params(filters)}`),enabled:Boolean(userId&&agencyId&&can('ged.view'))})}
export function useDocumentQuery(id?:string){const{userId,agencyId,can}=context();return useQuery({queryKey:documentKeys.detail(userId,agencyId,id??''),queryFn:()=>apiRequest<DocumentRecord>(`/documents/${id}`),enabled:Boolean(id&&userId&&agencyId&&can('ged.view'))})}
export function useEntityDocuments(type:DocumentEntityType,id?:string,requestEnabled=true){const{userId,agencyId,can}=context();return useQuery({queryKey:['documents',userId,agencyId,'entity',type,id],queryFn:()=>apiRequest<DocumentRecord[]>(`/documents/entity/${type}/${id}`),enabled:Boolean(id&&userId&&agencyId&&requestEnabled&&can('ged.view'))})}
export function useDocumentEntitySearch(type:DocumentEntityType,q:string){const{userId,agencyId,can}=context();return useQuery({queryKey:['documents',userId,agencyId,'entities',type,q],queryFn:()=>apiRequest<DocumentEntityResult[]>(`/documents/entities/search?${params({entityType:type,q})}`),enabled:Boolean(userId&&agencyId&&can('ged.upload')&&q.trim().length>=2),staleTime:30_000})}
const invalidate=(qc:ReturnType<typeof useQueryClient>)=>()=>qc.invalidateQueries({queryKey:documentKeys.all});
export function useUploadDocument(){const qc=useQueryClient();return useMutation({mutationFn:(body:FormData)=>apiRequest<{id:string;duplicateWarning:boolean}>('/documents',{method:'POST',body}),onSuccess:invalidate(qc)})}
export function useArchiveDocument(){const qc=useQueryClient();return useMutation({mutationFn:({id,reason}:{id:string;reason?:string})=>apiRequest(`/documents/${id}`,{method:'DELETE',body:JSON.stringify({reason})}),onSuccess:invalidate(qc)})}
export function useRestoreDocument(){const qc=useQueryClient();return useMutation({mutationFn:(id:string)=>apiRequest(`/documents/${id}/restore`,{method:'POST',body:'{}'}),onSuccess:invalidate(qc)})}
export function useUploadDocumentVersion(){const qc=useQueryClient();return useMutation({mutationFn:({id,body}:{id:string;body:FormData})=>apiRequest(`/documents/${id}/version`,{method:'POST',body}),onSuccess:invalidate(qc)})}
