import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { apiRequest, assetUrl } from '../services/apiClient';
import { deliveryStatusFromDb, invoiceStatusFromDb, opportunityStageFromDb, repairOrderStatusFromDb, saleStatusFromDb, vehicleStatusFromDb } from '../services/mysqlStatusMap';
import type { Agency, Customer, Delivery, Invoice, Lead, RepairOrder, Sale, SparePart, User, Vehicle } from '../types';
import { notificationRoute } from '../navigation/routes';

export const erpKeys = { users:['users'],agencies:['agencies'],customers:['customers'],leads:['leads'],vehicles:['vehicles'],sales:['sales'],repairOrders:['repair-orders'],parts:['parts'],deliveries:['deliveries'],invoices:['invoices'] } as const;
const enabled = () => Boolean(localStorage.getItem('lca-access-token'));
const n=(v:unknown)=>Number(v??0); const s=(v:unknown)=>v==null?'':String(v);

const customerRating:Record<string,Customer['rating']>={occasional:'Occasionnel',regular:'Régulier',vip:'VIP',at_risk:'Contentieux'};
const mapCustomer=(r:any):Customer=>({id:s(r.id),code:r.customerCode??r.code??`CLI-${r.id}`,civility:r.civility??(r.customerType==='company'?'Société':'M.'),firstName:r.firstName??'',lastName:r.lastName??'',company:r.companyName??undefined,siret:r.taxIdentifier,email:r.email??'',phone:r.phone??'',mobile:r.secondaryPhone??r.phone??'',address:r.address??'',zipCode:r.postalCode??r.zipCode??'',city:r.city??'',country:r.country??'',type:r.customerType==='company'?'Professionnel':'Particulier',salesRepId:s(r.assignedUserId),salesRepName:r.assignedUserName??'',agencyId:s(r.agencyId),agencyName:r.agencyName??'',createdById:s(r.createdById),createdByName:r.createdByName??'',segment:r.segment??'',score:n(r.score),clientSince:r.createdAt??'',totalRevenue:n(r.totalRevenue),openBalance:n(r.openBalance),rating:customerRating[r.classification]??r.rating??'Occasionnel',notes:r.notes??''});
const vehicleType:Record<string,Vehicle['type']>={new:'Neuf',used:'Occasion',demo:'Démo',courtesy:'Véhicule de Courtoisie'};
const mapVehicle=(r:any):Vehicle=>({id:s(r.id),stockNumber:r.stockNumber??'',vin:r.vin,registrationNumber:r.registrationNumber??'',brand:r.brand??'',model:r.model??'',version:r.version??'',type:vehicleType[r.vehicleType]??r.type??'Neuf',bodyType:r.bodyType??'SUV',year:n(r.year),firstRegistrationDate:r.firstRegistrationDate??'',mileage:n(r.mileage),color:r.color??'',interiorColor:r.interiorColor??'',fuel:r.fuelType??'Essence',transmission:r.transmission??'Automatique',fiscalPower:n(r.fiscalPower),realPower:n(r.realPower),co2Emissions:n(r.co2Emissions),status:vehicleStatusFromDb[r.status as keyof typeof vehicleStatusFromDb]??'COMMANDE',location:r.locationName??'',agencyId:s(r.agencyId),agencyName:r.agencyName??'',stockDays:r.entryDate?Math.max(0,Math.floor((Date.now()-new Date(r.entryDate).getTime())/86400000)):0,purchasePriceHT:n(r.purchasePrice),refurbishCostHT:n(r.refurbishmentCost),otherCostsHT:n(r.additionalCosts)+n(r.transportCost)+n(r.administrativeCost),catalogPriceTTC:n(r.catalogPrice),sellingPriceTTC:n(r.salePrice),minimumPriceTTC:n(r.minimumPrice),targetMarginHT:n(r.salePrice)-n(r.purchasePrice)-n(r.refurbishmentCost)-n(r.additionalCosts)-n(r.transportCost)-n(r.administrativeCost),photos:(r.photos??(r.primaryImage?[r.primaryImage]:[])).map(assetUrl),features:r.features??[],supplier:r.supplierName??'',createdAt:r.createdAt??''});
const leadPriorityFromDb:Record<string,Lead['priority']>={low:'Basse',medium:'Moyenne',high:'Haute',urgent:'Urgente'};
const mapLead=(r:any):Lead=>({id:s(r.id),civility:r.companyName?'Société':'M.',firstName:r.firstName??'',lastName:r.lastName??'',company:r.companyName,email:r.email??'',phone:r.phone??'',source:r.source??'Web',stage:opportunityStageFromDb[r.stage as keyof typeof opportunityStageFromDb]??'NOUVEAU',targetVehicle:r.title??'',targetBudget:n(r.expectedValue),assignedToId:s(r.assignedUserId),assignedToName:r.assignedUserName??'',createdById:s(r.createdById),createdByName:r.createdByName??'',agencyId:s(r.agencyId),priority:leadPriorityFromDb[r.priority]??'Moyenne',estimatedCloseDate:r.expectedCloseDate,notes:r.notes??'',createdAt:r.createdAt??'',updatedAt:r.updatedAt??'',score:n(r.probability)});
const mapSale=(r:any):Sale=>({id:s(r.id),saleNumber:r.sale_number,customerId:s(r.customer_id),customerName:r.customer_name??'',vehicleId:s(r.vehicle_id),vehicleLabel:r.vehicle_label??'',salesRepId:s(r.salesperson_id),salesRepName:r.salesperson_name??'',agencyId:s(r.agency_id),status:saleStatusFromDb[r.status as keyof typeof saleStatusFromDb]??'DEVIS',vehiclePriceTTC:n(r.subtotal),optionsTotalTTC:0,discountTTC:n(r.discount_total),registrationFeesTTC:0,administrativeFeesTTC:0,totalSaleTTC:n(r.total),depositPaidTTC:n(r.deposit_amount),remainingBalanceTTC:n(r.balance_due),financingType:'Comptant',contractDate:r.created_at??'',expectedDeliveryDate:r.expected_delivery_date??'',actualDeliveryDate:r.sold_at??undefined,notes:r.notes??''});
const mapRepair=(r:any):RepairOrder=>({id:s(r.id),orNumber:r.order_number,customerId:s(r.customer_id),customerName:r.customer_name??'',customerPhone:r.customer_phone??'',vehicleId:s(r.vehicle_id),vehicleVin:r.vin??'',vehiclePlate:r.registration_number??'',vehicleModel:r.vehicle_label??'',mileage:n(r.mileage_in),advisorId:s(r.advisor_id),advisorName:r.advisor_name??'',agencyId:s(r.agency_id),status:repairOrderStatusFromDb[r.status as keyof typeof repairOrderStatusFromDb]??'PLANIFIE',appointmentDate:r.received_at??r.created_at,promisedCompletionDate:r.promised_completion_date??'',receptionChecklist:{fuelLevel:'',cleanliness:'',bodyworkDamage:'',itemsInVehicle:''},symptomsReported:r.complaint??'',diagnosticNotes:r.diagnosis_summary??'',operations:[],parts:[],estimatedTotalTTC:n(r.estimated_total),finalTotalTTC:n(r.actual_total),warrantyCovered:false,createdAt:r.created_at??''});
const mapPart=(r:any):SparePart=>({id:s(r.id),reference:r.reference,oemReference:r.oem_reference??'',name:r.name,category:r.category_name??'Moteur',supplier:r.supplier_name??'',locationBin:r.location_bin??'',stockQuantity:n(r.current_stock),minStockAlert:n(r.min_stock),maxStockLevel:n(r.max_stock),pendingOrderQuantity:0,purchasePriceHT:n(r.purchase_price),sellingPriceHT:n(r.sale_price),tvaRate:n(r.tax_rate),marginRate:n(r.sale_price)?((n(r.sale_price)-n(r.purchase_price))/n(r.sale_price))*100:0,status:r.obsolete?'DORMANT':n(r.current_stock)<=0?'RUPTURE':r.low_stock?'FAIBLE':'NORMAL',lastRestockedDate:r.updated_at??'',compatibilityList:[]});
const mapDelivery=(r:any):Delivery=>({id:s(r.id),deliveryNumber:r.delivery_number,saleId:s(r.sale_id),saleNumber:r.sale_number??'',customerId:s(r.customer_id),customerName:r.customer_name??'',customerPhone:r.phone??'',vehicleId:s(r.vehicle_id),vehicleLabel:r.vehicle_label??'',vehicleVin:r.vin??'',vehiclePlate:r.registration_number??'',salesRepName:r.salesperson_name??'',deliverySpecialistName:r.delivery_specialist_name??'',agencyId:s(r.agency_id),deliveryDate:r.scheduled_at??'',deliveryTimeSlot:r.scheduled_at?.slice?.(11,16)??'',status:deliveryStatusFromDb[r.status as keyof typeof deliveryStatusFromDb]??'RDV_CONFIRME',checklist:{cleaningInterior:false,cleaningExterior:false,aestheticCheck:false,mechanicalCheck:false,documentsComplete:false,accessoriesFitted:false,fuelOrBatteryCharged:false,finalQualitySignoff:false,customerHandoverBriefing:false,customerSignature:false},notes:r.customer_notes??''});
const mapInvoice=(r:any):Invoice=>({id:s(r.id),invoiceNumber:r.invoice_number,type:r.invoice_type==='vehicle'?'FACTURE_VENTE_VN_VO':r.invoice_type==='workshop'?'FACTURE_ATELIER_SAV':'FACTURE_PIECES',customerId:s(r.customer_id),customerName:r.customer_name??'',relatedDocNumber:r.sale_id?`Vente ${r.sale_id}`:r.repair_order_id?`OR ${r.repair_order_id}`:'',issueDate:r.issue_date,dueDate:r.due_date??'',amountHT:n(r.subtotal),amountTVA:n(r.tax_total),amountTTC:n(r.total),paidAmountTTC:n(r.amount_paid),remainingAmountTTC:n(r.balance_due),status:invoiceStatusFromDb[r.status as keyof typeof invoiceStatusFromDb]??'BROUILLON'});

function resource<T>(key:readonly string[],path:string,map:(r:any)=>T){return useQuery({queryKey:key,queryFn:async()=>((await apiRequest<any[]>(path)).map(map)),enabled:enabled()});}
export const useUsersQuery=()=>resource<User>(erpKeys.users,'/users',(r:any)=>({id:s(r.id),name:r.name,email:r.email,role:(r.roles?.[0]??'RECEPTIONIST'),roleTitle:r.jobTitle??'',avatar:'',agencyId:s(r.agencyId),agencyName:r.agencyName??'',department:'',phone:r.phone??'',status:r.isActive?'active':'inactive'} as User));
export const useAgenciesQuery=()=>resource<Agency>(erpKeys.agencies,'/agencies',(r:any)=>({id:s(r.id),name:r.name,code:r.code,address:r.address??'',city:r.city??'',phone:r.phone??'',email:r.email??'',isMain:false}));
export const useCustomersQuery=(search='',type='')=>useQuery({queryKey:[...erpKeys.customers,search,type],queryFn:async()=>{const params=new URLSearchParams();if(search)params.set('search',search);if(type)params.set('type',type);const suffix=params.size?`?${params}`:'';return(await apiRequest<any[]>(`/customers${suffix}`)).map(mapCustomer)},enabled:enabled()}); export const useLeadsQuery=(search='',priority='')=>useQuery({queryKey:[...erpKeys.leads,search,priority],queryFn:async()=>{const params=new URLSearchParams();if(search)params.set('search',search);if(priority)params.set('priority',priority);const suffix=params.size?`?${params}`:'';return(await apiRequest<any[]>(`/leads${suffix}`)).map(mapLead)},enabled:enabled()}); export interface VehicleFilters {search?:string;status?:string;type?:string;fuel?:string;dormant?:boolean;sort?:string;page?:number;pageSize?:number}
export const useVehiclesQuery=(filters:VehicleFilters={})=>useQuery({queryKey:[...erpKeys.vehicles,filters],queryFn:async()=>{const params=new URLSearchParams();Object.entries(filters).forEach(([key,value])=>{if(value!==undefined&&value!==''&&value!==false)params.set(key,String(value))});const data=await apiRequest<{items:any[];total:number;page:number;pageSize:number}>(`/vehicles?${params}`);return data.items.map(mapVehicle)},enabled:enabled()}); export const useSalesQuery=()=>resource(erpKeys.sales,'/sales',mapSale); export const useRepairOrdersQuery=()=>resource(erpKeys.repairOrders,'/repair-orders',mapRepair); export const usePartsQuery=()=>resource(erpKeys.parts,'/parts',mapPart); export const useDeliveriesQuery=()=>resource(erpKeys.deliveries,'/deliveries',mapDelivery); export const useInvoicesQuery=()=>resource(erpKeys.invoices,'/invoices',mapInvoice);
export const useCustomerDetailQuery=(id?:string)=>useQuery({queryKey:['customers',id],queryFn:async()=>mapCustomer(await apiRequest<any>(`/customers/${id}`)),enabled:enabled()&&Boolean(id)});
export const useCustomerTimelineQuery=(id?:string)=>useQuery({queryKey:['customers',id,'timeline'],queryFn:()=>apiRequest<any[]>(`/customers/${id}/timeline`),enabled:enabled()&&Boolean(id)});
export const useCustomer360Query=(id?:string)=>useQuery({queryKey:['customers',id,'360'],queryFn:async()=>{const data=await apiRequest<any>(`/customers/${id}/360`);return{...data,customer:mapCustomer(data.customer),vehicles:data.vehicles.map((v:any)=>({...v,status:vehicleStatusFromDb[v.status as keyof typeof vehicleStatusFromDb]??v.status})),sales:data.sales.map((sale:any)=>({...sale,status:saleStatusFromDb[sale.status as keyof typeof saleStatusFromDb]??sale.status})),repairOrders:data.repairOrders.map((order:any)=>({...order,status:repairOrderStatusFromDb[order.status as keyof typeof repairOrderStatusFromDb]??order.status})),invoices:data.invoices.map((invoice:any)=>({...invoice,status:invoiceStatusFromDb[invoice.status as keyof typeof invoiceStatusFromDb]??invoice.status}))}},enabled:enabled()&&Boolean(id)});
export function useCreateCustomerContact(customerId?:string){const qc=useQueryClient();return useMutation({mutationFn:(body:any)=>apiRequest(`/customers/${customerId}/contacts`,{method:'POST',body:JSON.stringify(body)}),onSuccess:()=>qc.invalidateQueries({queryKey:['customers',customerId,'360']})});}
export const useVehicleDetailQuery=(id?:string)=>useQuery({queryKey:['vehicles',id],queryFn:async()=>mapVehicle(await apiRequest<any>(`/vehicles/${id}`)),enabled:enabled()&&Boolean(id)});
export const useVehicle360Query=(id?:string)=>useQuery({queryKey:['vehicles',id,'360'],queryFn:async()=>{const data=await apiRequest<any>(`/vehicles/${id}/360`);return{...data,vehicle:mapVehicle({...data.vehicle,photos:data.images.map((image:any)=>image.file_path),features:data.features.map((feature:any)=>feature.name)}),images:data.images.map((image:any)=>({...image,file_path:assetUrl(image.file_path),thumbnail_path:assetUrl(image.thumbnail_path)})),documents:data.documents.map((document:any)=>({...document,file_url:assetUrl(document.file_url)}))}},enabled:enabled()&&Boolean(id)});
export const useVehicleReferencesQuery=()=>useQuery({queryKey:['vehicle-references'],queryFn:()=>apiRequest<any>('/vehicle-references'),enabled:enabled(),staleTime:300_000});
export const usePartDetailQuery=(id?:string)=>useQuery({queryKey:['parts',id],queryFn:async()=>mapPart(await apiRequest<any>(`/parts/${id}`)),enabled:enabled()&&Boolean(id)});
export const useSaleDetailQuery=(id?:string)=>useQuery({queryKey:['sales',id],queryFn:async()=>mapSale(await apiRequest<any>(`/sales/${id}`)),enabled:enabled()&&Boolean(id)});
function mutation<T>(path:(v:T)=>string,method='POST',invalidate:readonly string[]){const qc=useQueryClient();return useMutation({mutationFn:(v:T)=>apiRequest(path(v),{method,body:JSON.stringify(v)}),onSuccess:()=>qc.invalidateQueries({queryKey:invalidate})});}
export const useCreateCustomer=()=>mutation<any>(()=>'/customers','POST',erpKeys.customers);export const useCreateLead=()=>mutation<any>(()=>'/leads','POST',erpKeys.leads);export const useCreateSale=()=>mutation<any>(()=>'/sales','POST',erpKeys.sales);export const useCreateRepairOrder=()=>mutation<any>(()=>'/repair-orders','POST',erpKeys.repairOrders);export const useCreateInvoice=()=>mutation<any>(()=>'/invoices','POST',erpKeys.invoices);
export function useLeadStageMutation(){const qc=useQueryClient();return useMutation({mutationFn:({id,stage}:{id:string;stage:string})=>apiRequest(`/leads/${id}/stage`,{method:'PATCH',body:JSON.stringify({stage})}),onSuccess:()=>qc.invalidateQueries({queryKey:erpKeys.leads})});}
export function useVehicleStatusMutation(){const qc=useQueryClient();return useMutation({mutationFn:({id,status}:{id:string;status:string})=>apiRequest(`/vehicles/${id}/status`,{method:'PATCH',body:JSON.stringify({status})}),onSuccess:()=>qc.invalidateQueries({queryKey:erpKeys.vehicles})});}
export function useSaleStatusMutation(){const qc=useQueryClient();return useMutation({mutationFn:({id,status}:{id:string;status:string})=>apiRequest(`/sales/${id}/status`,{method:'PATCH',body:JSON.stringify({status})}),onSuccess:()=>qc.invalidateQueries({queryKey:erpKeys.sales})});}
export function useRepairStatusMutation(){const qc=useQueryClient();return useMutation({mutationFn:({id,status}:{id:string;status:string})=>apiRequest(`/repair-orders/${id}/status`,{method:'PATCH',body:JSON.stringify({status})}),onSuccess:(_,v)=>{qc.invalidateQueries({queryKey:erpKeys.repairOrders});qc.invalidateQueries({queryKey:['repair-orders',v.id]})}});}
export function usePartMovement(){const qc=useQueryClient();return useMutation({mutationFn:({id,...body}:any)=>apiRequest(`/parts/${id}/movements`,{method:'POST',body:JSON.stringify(body)}),onSuccess:()=>qc.invalidateQueries({queryKey:erpKeys.parts})});}
export const useCreatePart=()=>mutation<any>(()=>'/parts','POST',erpKeys.parts);
export const usePaymentMethodsQuery=()=>useQuery({queryKey:['payment-methods'],queryFn:()=>apiRequest<any[]>('/invoices/payment-methods'),enabled:enabled(),staleTime:300_000});
export function useInvoicePayment(){const qc=useQueryClient();return useMutation({mutationFn:({invoiceId,...body}:any)=>apiRequest(`/invoices/${invoiceId}/payments`,{method:'POST',body:JSON.stringify(body)}),onSuccess:()=>qc.invalidateQueries({queryKey:erpKeys.invoices})});}
export const useTechniciansQuery=()=>useQuery({queryKey:['technicians'],queryFn:()=>apiRequest<any[]>('/workshop/technicians'),enabled:enabled()});
export const useWorkshopPlanningQuery=(agencyId?:string,date?:string)=>useQuery({queryKey:['workshop-planning',agencyId,date],queryFn:()=>apiRequest<any[]>(`/workshop/planning?agencyId=${encodeURIComponent(agencyId!)}&date=${encodeURIComponent(date!)}`),enabled:enabled()&&Boolean(agencyId&&date)});
export const useShowroomQuery=()=>useQuery({queryKey:['showroom'],queryFn:async()=>{const rows=await apiRequest<any[]>('/showroom');return rows.map(r=>({id:s(r.id),visitorName:r.visitor_name??'',phone:r.phone??'',arrivalDateTime:r.arrival_at,interest:r.reason??'Achat Véhicule Neuf',preferredModel:r.preferred_model??'',assignedRepName:r.assigned_user_name,status:r.status==='waiting'?'En Attente':r.status==='in_progress'?'En Entretien':r.status==='completed'?'Terminé':'En Attente',waitTimeMinutes:n(r.wait_minutes)}))},enabled:enabled()});
export function useCreateShowroomVisit(){const qc=useQueryClient();return useMutation({mutationFn:(body:any)=>apiRequest('/showroom',{method:'POST',body:JSON.stringify(body)}),onSuccess:()=>qc.invalidateQueries({queryKey:['showroom']})});}
export function useShowroomStatus(){const qc=useQueryClient();return useMutation({mutationFn:({id,status}:any)=>apiRequest(`/showroom/${id}/status`,{method:'PATCH',body:JSON.stringify({status})}),onSuccess:()=>qc.invalidateQueries({queryKey:['showroom']})});}
export const useCreateVehicle=()=>mutation<any>(()=>'/vehicles','POST',erpKeys.vehicles);
export function useVehicleImages(){const qc=useQueryClient();return{add:useMutation({mutationFn:({id,images}:{id:string;images:any[]})=>apiRequest(`/vehicles/${id}/images`,{method:'POST',body:JSON.stringify({images})}),onSuccess:(_,v)=>qc.invalidateQueries({queryKey:['vehicles',v.id]})}),primary:useMutation({mutationFn:({id,imageId}:{id:string;imageId:string})=>apiRequest(`/vehicles/${id}/images/${imageId}/primary`,{method:'PATCH'}),onSuccess:(_,v)=>qc.invalidateQueries({queryKey:['vehicles',v.id]})}),remove:useMutation({mutationFn:({id,imageId}:{id:string;imageId:string})=>apiRequest(`/vehicles/${id}/images/${imageId}`,{method:'DELETE'}),onSuccess:(_,v)=>qc.invalidateQueries({queryKey:['vehicles',v.id]})})}}
export const useCreateUser=()=>mutation<any>(()=>'/users','POST',erpKeys.users);
export function useCreateActivity(){const qc=useQueryClient();return useMutation({mutationFn:(body:any)=>apiRequest('/activities',{method:'POST',body:JSON.stringify(body)}),onSuccess:()=>qc.invalidateQueries({queryKey:['activities']})});}
export const useNotificationsQuery=()=>useQuery({queryKey:['notifications'],queryFn:async()=>{const rows=await apiRequest<any[]>('/notifications');return rows.map(r=>({id:s(r.id),title:r.subject??'Notification',message:r.message,category:r.reference_type??'Système',timestamp:r.created_at,isRead:r.status==='read',priority:r.status==='failed'?'high':'medium',linkRoute:notificationRoute(r.reference_type,s(r.reference_id))}))},enabled:enabled()});
export function useNotificationActions(){const qc=useQueryClient();const done=()=>qc.invalidateQueries({queryKey:['notifications']});return{markAsRead:(id:string)=>apiRequest(`/notifications/${id}/read`,{method:'PATCH'}).then(done),markAllAsRead:()=>apiRequest('/notifications/read-all',{method:'PATCH'}).then(done),deleteNotification:(id:string)=>apiRequest(`/notifications/${id}`,{method:'DELETE'}).then(done)}}
export const useDeliveryDetailQuery=(id?:string)=>useQuery({queryKey:['deliveries',id],queryFn:()=>apiRequest<any>(`/deliveries/${id}`),enabled:enabled()&&Boolean(id)});
export const useCreateDelivery=()=>mutation<any>(()=>'/deliveries','POST',erpKeys.deliveries);
export function useDeliveryChecklist(){const qc=useQueryClient();return useMutation({mutationFn:({deliveryId,itemId,...body}:any)=>apiRequest(`/deliveries/${deliveryId}/checklist/${itemId}`,{method:'PATCH',body:JSON.stringify(body)}),onSuccess:(_,v:any)=>{qc.invalidateQueries({queryKey:erpKeys.deliveries});qc.invalidateQueries({queryKey:['deliveries',v.deliveryId]})}})}
export function useSignDelivery(){const qc=useQueryClient();return useMutation({mutationFn:({deliveryId,...body}:any)=>apiRequest(`/deliveries/${deliveryId}/sign`,{method:'POST',body:JSON.stringify(body)}),onSuccess:(_,v:any)=>{qc.invalidateQueries({queryKey:erpKeys.deliveries});qc.invalidateQueries({queryKey:['deliveries',v.deliveryId]})}})}
export const useRepairDetailQuery=(id?:string)=>useQuery({queryKey:['repair-orders',id],queryFn:()=>apiRequest<any>(`/repair-orders/${id}`),enabled:enabled()&&Boolean(id)});
export function useAddRepairItem(){const qc=useQueryClient();return useMutation({mutationFn:({repairOrderId,...body}:any)=>apiRequest(`/repair-orders/${repairOrderId}/items`,{method:'POST',body:JSON.stringify(body)}),onSuccess:(_,v:any)=>{qc.invalidateQueries({queryKey:erpKeys.repairOrders});qc.invalidateQueries({queryKey:['repair-orders',v.repairOrderId]});qc.invalidateQueries({queryKey:erpKeys.parts})}})}
export function useAssignRepairOrder(){const qc=useQueryClient();return useMutation({mutationFn:({repairOrderId,...body}:any)=>apiRequest(`/repair-orders/${repairOrderId}/assign`,{method:'POST',body:JSON.stringify(body)}),onSuccess:()=>qc.invalidateQueries({queryKey:erpKeys.repairOrders})})}
export const useSettingsQuery=()=>useQuery({queryKey:['settings'],queryFn:()=>apiRequest<any>('/settings'),enabled:enabled()});
export function useSaveSettings(){const qc=useQueryClient();return useMutation({mutationFn:(body:any)=>apiRequest('/settings',{method:'PUT',body:JSON.stringify(body)}),onSuccess:()=>qc.invalidateQueries({queryKey:['settings']})})}
export const useDocumentsQuery=()=>useQuery({queryKey:['documents'],queryFn:()=>apiRequest<any[]>('/documents'),enabled:enabled()});
export function useUploadDocument(){const qc=useQueryClient();return useMutation({mutationFn:(body:FormData)=>apiRequest('/documents',{method:'POST',body}),onSuccess:()=>qc.invalidateQueries({queryKey:['documents']})})}
