import {useMutation,useQuery,useQueryClient} from '@tanstack/react-query';
import {apiRequest} from '../services/apiClient';
export interface Supplier{id:string;name:string;code:string;contact_name:string|null;email:string|null;phone:string|null;address:string|null;city:string|null;country:string|null;tax_identifier:string|null;is_active:boolean}
export interface SupplierInput{name:string;code:string;contactName?:string;email?:string;phone?:string;address?:string;city?:string;country?:string;taxIdentifier?:string;isActive?:boolean}
export interface Bay{id:string;agency_id:string;name:string;bay_type:string|null;capacity:number;status:'available'|'occupied'|'maintenance'|'inactive';occupied_now:boolean}
const enabled=()=>Boolean(localStorage.getItem('lca-access-token'));
export const useSuppliersSettingsQuery=(search='')=>useQuery({queryKey:['suppliers',search],queryFn:()=>apiRequest<Supplier[]>(`/suppliers?search=${encodeURIComponent(search)}`),enabled:enabled()});
export function useSupplierSettingsActions(){const qc=useQueryClient(),done=()=>Promise.all([qc.invalidateQueries({queryKey:['suppliers']}),qc.invalidateQueries({queryKey:['part-references']})]);return{create:useMutation({mutationFn:(body:SupplierInput)=>apiRequest('/suppliers',{method:'POST',body:JSON.stringify(body)}),onSuccess:done}),update:useMutation({mutationFn:({id,...body}:SupplierInput&{id:string})=>apiRequest(`/suppliers/${id}`,{method:'PATCH',body:JSON.stringify(body)}),onSuccess:done}),status:useMutation({mutationFn:({id,isActive}:{id:string;isActive:boolean})=>apiRequest(`/suppliers/${id}/status`,{method:'PATCH',body:JSON.stringify({isActive})}),onSuccess:done})}}
export const useSettingsBaysQuery=(agencyId?:string)=>useQuery({queryKey:['workshop-bays',agencyId],queryFn:()=>apiRequest<Bay[]>(`/workshop/bays?agencyId=${encodeURIComponent(agencyId!)}`),enabled:enabled()&&Boolean(agencyId)});
export function useBaySettingsActions(){const qc=useQueryClient(),done=()=>Promise.all([qc.invalidateQueries({queryKey:['workshop-bays']}),qc.invalidateQueries({queryKey:['workshop-planning']}),qc.invalidateQueries({queryKey:['workshop-stats']})]);return{create:useMutation({mutationFn:(body:{agencyId?:string;name:string;bayType?:string;capacity:number;status:string})=>apiRequest('/workshop/bays',{method:'POST',body:JSON.stringify(body)}),onSuccess:done}),update:useMutation({mutationFn:({id,...body}:{id:string;agencyId?:string;name?:string;bayType?:string;capacity?:number;status:string})=>apiRequest(`/workshop/bays/${id}`,{method:'PATCH',body:JSON.stringify(body)}),onSuccess:done})}}
