import{useMutation,useQuery,useQueryClient}from'@tanstack/react-query';import{apiRequest}from'../services/apiClient';
export type TreasuryAccount={id:string;name:string;code:string;account_type:'CASH'|'BANK'|'OTHER';currency_code:string;agency_name:string|null;concession_name:string;is_active:boolean;balance:number};
export type TreasuryCategory={id:string;name:string;code:string;allowed_direction:'IN'|'OUT'|'BOTH';is_active:boolean;usage_count:number};
export type TreasuryMovement={id:string;value_date:string;account_name:string;direction:'IN'|'OUT';amount:number;currency_code:string;category_name:string|null;reference:string|null;source_type:string;source_id:string;author_name:string|null};
export type TreasurySummary={totalIn:number;totalOut:number;balance:number};
const keys={all:['treasury']as const,accounts:['treasury','accounts']as const,categories:['treasury','categories']as const,summary:['treasury','summary']as const,journal:(filters:string)=>['treasury','journal',filters]as const};
export const useTreasuryAccounts=(enabled=true)=>useQuery({queryKey:keys.accounts,queryFn:()=>apiRequest<TreasuryAccount[]>('/treasury/accounts'),enabled});
export const useTreasuryCategories=(enabled=true)=>useQuery({queryKey:keys.categories,queryFn:()=>apiRequest<TreasuryCategory[]>('/treasury/categories'),enabled});
export const useTreasurySummary=(enabled=true)=>useQuery({queryKey:keys.summary,queryFn:()=>apiRequest<TreasurySummary>('/treasury/summary'),enabled});
export function useTreasuryJournal(filters:{page:number;pageSize:number;accountId?:string;direction?:string;categoryId?:string;from?:string;to?:string}){const params=new URLSearchParams(Object.entries(filters).filter(([,v])=>v!==undefined&&v!=='').map(([k,v])=>[k,String(v)]));return useQuery({queryKey:keys.journal(params.toString()),queryFn:()=>apiRequest<{items:TreasuryMovement[];page:number;pageSize:number;total:number;totalPages:number}>(`/treasury/journal?${params}`)})}
export function useTreasuryActions(){const q=useQueryClient(),refresh=()=>q.invalidateQueries({queryKey:keys.all});return{createAccount:useMutation({mutationFn:(body:unknown)=>apiRequest('/treasury/accounts',{method:'POST',body:JSON.stringify(body)}),onSuccess:refresh}),accountStatus:useMutation({mutationFn:({id,isActive}:{id:string;isActive:boolean})=>apiRequest(`/treasury/accounts/${id}/status`,{method:'PATCH',body:JSON.stringify({isActive})}),onSuccess:refresh}),createCategory:useMutation({mutationFn:(body:unknown)=>apiRequest('/treasury/categories',{method:'POST',body:JSON.stringify(body)}),onSuccess:refresh}),categoryStatus:useMutation({mutationFn:({id,isActive}:{id:string;isActive:boolean})=>apiRequest(`/treasury/categories/${id}/status`,{method:'PATCH',body:JSON.stringify({isActive})}),onSuccess:refresh}),transfer:useMutation({mutationFn:(body:unknown)=>apiRequest('/treasury/transfers',{method:'POST',body:JSON.stringify(body)}),onSuccess:refresh}),reverse:useMutation({mutationFn:({id,...body}:{id:string;reason:string;valueDate:string})=>apiRequest(`/treasury/movements/${id}/reversal`,{method:'POST',body:JSON.stringify(body)}),onSuccess:refresh})}}
