import { Injectable, NotFoundException } from '@nestjs/common';
import { RowDataPacket } from 'mysql2';
import { DatabaseService } from '../../database/database.service';
import { CreateLeadDto, UpdateLeadStageDto } from './leads.dto';
@Injectable()
export class LeadsService {
  constructor(private readonly db: DatabaseService) {}
  async findAll() { const rows=await this.db.query<RowDataPacket[]>(`SELECT l.id lead_id,o.id opportunity_id,l.first_name,l.last_name,l.company_name,l.email,l.phone,l.source,l.assigned_user_id,o.title,o.stage,o.expected_value,o.probability,o.expected_close_date,o.lost_reason,o.notes,l.created_at,l.updated_at,CONCAT_WS(' ',u.first_name,u.last_name) assigned_user_name FROM leads l JOIN opportunities o ON o.lead_id=l.id LEFT JOIN users u ON u.id=l.assigned_user_id ORDER BY l.updated_at DESC`); return rows.map(r=>({id:r.lead_id,opportunityId:r.opportunity_id,firstName:r.first_name,lastName:r.last_name,companyName:r.company_name,email:r.email,phone:r.phone,source:r.source,assignedUserId:r.assigned_user_id,assignedUserName:r.assigned_user_name,title:r.title,stage:r.stage,expectedValue:r.expected_value,probability:r.probability,expectedCloseDate:r.expected_close_date,lostReason:r.lost_reason,notes:r.notes,createdAt:r.created_at,updatedAt:r.updated_at})); }
  async create(dto:CreateLeadDto){return this.db.transaction(async c=>{const [lead]=await c.execute<any>('INSERT INTO leads (assigned_user_id,source,status,first_name,last_name,company_name,email,phone,notes) VALUES (?,?,"new",?,?,?,?,?,?)',[dto.assignedUserId??null,dto.source??null,dto.firstName??null,dto.lastName??null,dto.companyName??null,dto.email??null,dto.phone??null,dto.notes??null]);const [opp]=await c.execute<any>('INSERT INTO opportunities (lead_id,assigned_user_id,title,stage,expected_value,probability,notes) VALUES (?,?,?,"new",?,?,?)',[String(lead.insertId),dto.assignedUserId??null,dto.title,dto.expectedValue??null,dto.probability??null,dto.notes??null]);return {id:String(lead.insertId),opportunityId:String(opp.insertId)};});}
  async updateStage(id:string,dto:UpdateLeadStageDto){const result=await this.db.execute(`UPDATE opportunities SET stage=?,lost_reason=?,won_at=IF(?='won',NOW(),won_at),lost_at=IF(?='lost',NOW(),lost_at) WHERE lead_id=?`,[dto.stage,dto.stage==='lost'?dto.lostReason??'Non précisé':null,dto.stage,dto.stage,id]);if(!result.affectedRows)throw new NotFoundException('Prospect introuvable');await this.db.execute('UPDATE leads SET status=? WHERE id=?',[dto.stage==='won'?'converted':dto.stage==='lost'?'lost':['new','contacted','qualified'].includes(dto.stage)?dto.stage:'qualified',id]);return {success:true};}
}
