import {unlink} from 'node:fs/promises';
import PDFDocument from 'pdfkit';
import {renderDeliveryDocument,renderInvoiceDocument,renderPaymentReceiptData,renderQuotationDocument,renderSaleOrderDocument} from './commercial-document.js';
import type {ResultSetHeader,RowDataPacket} from 'mysql2/promise';
import {execute,query} from '../../config/database.js';
import {emitToAgency} from '../../realtime/socket.js';
import {documentHash,storeDocument} from './document-storage.js';

type Field=[string,unknown];
type ArchiveInput={sourceKey:string;documentType:string;entityType:'customer'|'sale'|'invoice'|'delivery';entityId:string;fileName:string;agencyId:string;createdBy:string|null;buffer:Buffer};
const safe=(value:unknown)=>String(value??'—');
export async function renderBusinessPdf(title:string,fields:Field[],lines:string[]=[]){return new Promise<Buffer>((resolve,reject)=>{const doc=new PDFDocument({size:'A4',margin:45}),chunks:Buffer[]=[];doc.on('data',(x:Buffer)=>chunks.push(x));doc.on('end',()=>resolve(Buffer.concat(chunks)));doc.on('error',reject);doc.fontSize(20).fillColor('#8f1722').text(title).moveDown().fillColor('#111');for(const[label,value]of fields)doc.fontSize(10).text(`${label} : ${safe(value)}`);if(lines.length){doc.moveDown().fontSize(12).text('Détails');for(const line of lines)doc.fontSize(9).text(line)}doc.moveDown(2).fontSize(8).fillColor('#64748b').text(`Document généré le ${new Date().toLocaleString('fr-CG')}`,{align:'center'});doc.end()})}

export async function archiveBusinessDocument(input:ArchiveInput){
  const[existing]=await query<RowDataPacket[]>('SELECT id,file_url FROM documents WHERE source_key=? LIMIT 1',[input.sourceKey]);
  if(existing){console.info('[GED] document déjà existant',{sourceKey:input.sourceKey,documentId:String(existing.id)});return{id:String(existing.id),created:false}}
  const file={originalName:input.fileName,mimeType:'application/pdf',buffer:input.buffer},stored=await storeDocument(file,input.agencyId),hash=documentHash(input.buffer);
  try{const result=await execute(`INSERT INTO documents(uploaded_by,origin,source_key,document_type,file_name,file_url,mime_type,file_size,version,entity_type,entity_id,is_archived,file_hash) VALUES(?,'generated',?,?,?,?,?,?,1,?,?,FALSE,?)`,[input.createdBy,input.sourceKey,input.documentType,input.fileName,`ged:${stored.storageKey}`,'application/pdf',input.buffer.length,input.entityType,input.entityId,hash]) as ResultSetHeader;const id=String(result.insertId);console.info('[GED] document généré',{sourceKey:input.sourceKey,documentId:id,entityType:input.entityType,entityId:input.entityId});emitToAgency(input.agencyId,'documents:created',{id,entityType:input.entityType,entityId:input.entityId,origin:'generated'});return{id,created:true}}
  catch(error:any){await unlink(stored.absolute).catch(()=>undefined);if(error?.code==='ER_DUP_ENTRY'){const[row]=await query<RowDataPacket[]>('SELECT id FROM documents WHERE source_key=? LIMIT 1',[input.sourceKey]);if(row)return{id:String(row.id),created:false}}throw error}
}
export async function safelyArchive(label:string,job:()=>Promise<unknown>){try{return await job()}catch(error){console.error('[GED] archive échouée',{label,error:error instanceof Error?error.message:'Erreur inconnue'});return null}}

export async function archiveQuotation(id:string,createdBy:string|null){const[row]=await query<RowDataPacket[]>('SELECT id,customer_id,quotation_number,agency_id,status FROM quotations WHERE id=?',[id]);if(!row||row.status!=='sent')throw new Error('Devis émis introuvable');return archiveBusinessDocument({sourceKey:`quotation:${id}:issued:v2`,documentType:'Devis',entityType:'customer',entityId:String(row.customer_id),fileName:`devis-${row.quotation_number}.pdf`,agencyId:String(row.agency_id),createdBy,buffer:await renderQuotationDocument(id)})}
export async function archiveSaleOrder(id:string,createdBy:string|null){const[row]=await query<RowDataPacket[]>('SELECT id,sale_number,agency_id,status FROM sales WHERE id=?',[id]);if(!row||row.status!=='confirmed')throw new Error('Vente confirmée introuvable');return archiveBusinessDocument({sourceKey:`sale:${id}:confirmed:v2`,documentType:'Bon de commande',entityType:'sale',entityId:id,fileName:`bon-commande-${row.sale_number}.pdf`,agencyId:String(row.agency_id),createdBy,buffer:await renderSaleOrderDocument(id)})}
export async function archiveInvoice(id:string,createdBy:string|null){const[row]=await query<RowDataPacket[]>('SELECT id,invoice_number,agency_id,status FROM invoices WHERE id=?',[id]);if(!row||!['issued','partially_paid','paid'].includes(row.status))throw new Error('Facture émise introuvable');return archiveBusinessDocument({sourceKey:`invoice:${id}:issued:v2`,documentType:'Facture client',entityType:'invoice',entityId:id,fileName:`facture-${row.invoice_number}.pdf`,agencyId:String(row.agency_id),createdBy,buffer:await renderInvoiceDocument(id)})}
export async function archivePayment(id:string,createdBy:string|null){const[row]=await query<RowDataPacket[]>(`SELECT p.id,p.invoice_id,p.payment_number,p.status,p.amount,p.payment_date,p.reference,i.invoice_number,i.agency_id,i.currency_code,pm.name payment_method,CONCAT_WS(' ',u.first_name,u.last_name) received_by_name,COALESCE(c.company_name,CONCAT_WS(' ',c.first_name,c.last_name)) customer_name FROM payments p JOIN invoices i ON i.id=p.invoice_id JOIN customers c ON c.id=p.customer_id JOIN payment_methods pm ON pm.id=p.payment_method_id LEFT JOIN users u ON u.id=p.received_by WHERE p.id=?`,[id]);if(!row||row.status!=='confirmed')throw new Error('Paiement confirmé introuvable');return archiveBusinessDocument({sourceKey:`payment:${id}:confirmed:v1`,documentType:'Reçu de paiement',entityType:'invoice',entityId:String(row.invoice_id),fileName:`recu-${row.payment_number}.pdf`,agencyId:String(row.agency_id),createdBy,buffer:await renderPaymentReceiptData(row)})}
export async function archiveDelivery(id:string,createdBy:string|null){const[row]=await query<RowDataPacket[]>('SELECT id,delivery_number,agency_id,status FROM deliveries WHERE id=?',[id]);if(!row||row.status!=='delivered')throw new Error('Livraison finalisée introuvable');return archiveBusinessDocument({sourceKey:`delivery:${id}:finalized:v2`,documentType:'PV livraison',entityType:'delivery',entityId:id,fileName:`pv-${row.delivery_number}.pdf`,agencyId:String(row.agency_id),createdBy,buffer:await renderDeliveryDocument(id)})}
