import {unlink} from 'node:fs/promises';
import PDFDocument from 'pdfkit';
import {renderDeliveryDocument,renderInvoiceDocument,renderPaymentReceiptData,renderQuotationDocument,renderSaleOrderDocument} from './commercial-document.js';
import type {PoolConnection,ResultSetHeader,RowDataPacket} from 'mysql2/promise';
import {execute,query,transaction} from '../../config/database.js';
import {emitToAgency} from '../../realtime/socket.js';
import {documentHash,readDocumentFile,storeDocument} from './document-storage.js';
import {HttpError} from '../../shared/http-error.js';

type Field=[string,unknown];
type ArchiveInput={sourceKey:string;documentType:string;entityType:'customer'|'sale'|'invoice'|'delivery'|'vehicle_return';entityId:string;fileName:string;agencyId:string;createdBy:string|null;buffer:Buffer;afterInsert?:(connection:PoolConnection,documentId:string)=>Promise<void>};
export const businessArchiveTestHooks:{afterDeliveryFileStored?:(absolutePath:string)=>Promise<void>}={};
const safe=(value:unknown)=>String(value??'—');
export async function renderBusinessPdf(title:string,fields:Field[],lines:string[]=[]){return new Promise<Buffer>((resolve,reject)=>{const doc=new PDFDocument({size:'A4',margin:45}),chunks:Buffer[]=[];doc.on('data',(x:Buffer)=>chunks.push(x));doc.on('end',()=>resolve(Buffer.concat(chunks)));doc.on('error',reject);doc.fontSize(20).fillColor('#8f1722').text(title).moveDown().fillColor('#111');for(const[label,value]of fields)doc.fontSize(10).text(`${label} : ${safe(value)}`);if(lines.length){doc.moveDown().fontSize(12).text('Détails');for(const line of lines)doc.fontSize(9).text(line)}doc.moveDown(2).fontSize(8).fillColor('#64748b').text(`Document généré le ${new Date().toLocaleString('fr-CG')}`,{align:'center'});doc.end()})}

export async function archiveBusinessDocument(input:ArchiveInput){
  const[existing]=await query<RowDataPacket[]>('SELECT id,file_url FROM documents WHERE source_key=? LIMIT 1',[input.sourceKey]);
  if(existing){if(input.afterInsert)await transaction(c=>input.afterInsert!(c,String(existing.id)));console.info('[GED] document déjà existant',{sourceKey:input.sourceKey,documentId:String(existing.id)});return{id:String(existing.id),created:false}}
  const file={originalName:input.fileName,mimeType:'application/pdf',buffer:input.buffer},stored=await storeDocument(file,input.agencyId),hash=documentHash(input.buffer);
  try{const id=await transaction(async connection=>{const[result]=await connection.execute<ResultSetHeader>(`INSERT INTO documents(uploaded_by,origin,source_key,title,document_type,file_name,file_url,mime_type,file_size,version,entity_type,entity_id,agency_id,concession_id,is_archived,file_hash) SELECT ?,'generated',?,?,?,?,?,?,?,1,?,?,a.id,a.concession_id,FALSE,? FROM agencies a WHERE a.id=?`,[input.createdBy,input.sourceKey,input.fileName,input.documentType,input.fileName,`ged:${stored.storageKey}`,'application/pdf',input.buffer.length,input.entityType,input.entityId,hash,input.agencyId]);const documentId=String(result.insertId);if(input.afterInsert)await input.afterInsert(connection,documentId);return documentId});console.info('[GED] document généré',{sourceKey:input.sourceKey,documentId:id,entityType:input.entityType,entityId:input.entityId});emitToAgency(input.agencyId,'documents:created',{id,entityType:input.entityType,entityId:input.entityId,origin:'generated'});return{id,created:true}}
  catch(error:any){await unlink(stored.absolute).catch(()=>undefined);if(error?.code==='ER_DUP_ENTRY'){const[row]=await query<RowDataPacket[]>('SELECT id FROM documents WHERE source_key=? LIMIT 1',[input.sourceKey]);if(row){if(input.afterInsert)await transaction(c=>input.afterInsert!(c,String(row.id)));return{id:String(row.id),created:false}}}throw error}
}
export async function requireBusinessArchive(label:string,job:()=>Promise<unknown>){try{return await job()}catch(error){const reason=error instanceof Error?error.message:'Erreur inconnue';console.error('[GED] archive officielle requise échouée',{label,reason});if(error instanceof HttpError&&error.status<500)throw error;throw new HttpError(503,`Finalisation enregistrée, mais archive officielle temporairement indisponible (${label}). Réessayez l'action pour finaliser l'archivage.`)}}
export async function historicalBusinessPdf(sourcePrefix:string){const[row]=await query<RowDataPacket[]>("SELECT file_url,file_hash FROM documents WHERE origin='generated' AND source_key LIKE ? ORDER BY created_at ASC,id ASC LIMIT 1",[`${sourcePrefix}%`]);if(!row)return null;return readDocumentFile(String(row.file_url),row.file_hash)}
export async function requiredHistoricalBusinessPdf(sourcePrefix:string){const pdf=await historicalBusinessPdf(sourcePrefix);if(!pdf)throw new HttpError(409,'Archive officielle absente. Réessayez l’action de finalisation avant de consulter ce document.');return pdf}

export async function archiveQuotation(id:string,createdBy:string|null){const[row]=await query<RowDataPacket[]>('SELECT id,customer_id,quotation_number,agency_id,status,document_identity_snapshot FROM quotations WHERE id=?',[id]);if(!row||!row.document_identity_snapshot)throw new HttpError(409,'Devis émis introuvable');return archiveBusinessDocument({sourceKey:`quotation:${id}:issued:v2`,documentType:'Devis',entityType:'customer',entityId:String(row.customer_id),fileName:`devis-${row.quotation_number}.pdf`,agencyId:String(row.agency_id),createdBy,buffer:await renderQuotationDocument(id)})}
export async function archiveSaleOrder(id:string,createdBy:string|null){const[row]=await query<RowDataPacket[]>('SELECT id,sale_number,agency_id,status FROM sales WHERE id=?',[id]);if(!row||row.status!=='confirmed')throw new HttpError(409,'Vente confirmée introuvable');return archiveBusinessDocument({sourceKey:`sale:${id}:confirmed:v2`,documentType:'Bon de commande',entityType:'sale',entityId:id,fileName:`bon-commande-${row.sale_number}.pdf`,agencyId:String(row.agency_id),createdBy,buffer:await renderSaleOrderDocument(id)})}
export async function archiveInvoice(id:string,createdBy:string|null){const[row]=await query<RowDataPacket[]>('SELECT id,invoice_number,agency_id,status FROM invoices WHERE id=?',[id]);if(!row||!['issued','partially_paid','paid'].includes(row.status))throw new HttpError(409,'Facture émise introuvable');return archiveBusinessDocument({sourceKey:`invoice:${id}:issued:v2`,documentType:'Facture client',entityType:'invoice',entityId:id,fileName:`facture-${row.invoice_number}.pdf`,agencyId:String(row.agency_id),createdBy,buffer:await renderInvoiceDocument(id)})}
export async function archivePayment(id:string,createdBy:string|null){const[row]=await query<RowDataPacket[]>(`SELECT p.id,p.invoice_id,p.payment_number,p.status,p.amount,p.payment_date,p.reference,i.invoice_number,i.agency_id,i.currency_code,pm.name payment_method,CONCAT_WS(' ',u.first_name,u.last_name) received_by_name,COALESCE(c.company_name,CONCAT_WS(' ',c.first_name,c.last_name)) customer_name FROM payments p JOIN invoices i ON i.id=p.invoice_id JOIN customers c ON c.id=p.customer_id JOIN payment_methods pm ON pm.id=p.payment_method_id LEFT JOIN users u ON u.id=p.received_by WHERE p.id=?`,[id]);if(!row||row.status!=='confirmed')throw new HttpError(409,'Paiement confirmé introuvable');return archiveBusinessDocument({sourceKey:`payment:${id}:confirmed:v1`,documentType:'Reçu de paiement',entityType:'invoice',entityId:String(row.invoice_id),fileName:`recu-${row.payment_number}.pdf`,agencyId:String(row.agency_id),createdBy,buffer:await renderPaymentReceiptData(row)})}
export async function archiveDelivery(id:string,createdBy:string|null){const[row]=await query<RowDataPacket[]>('SELECT id,delivery_number,agency_id,status FROM deliveries WHERE id=?',[id]);if(!row||row.status!=='delivered')throw new HttpError(409,'Livraison finalisée introuvable');return archiveBusinessDocument({sourceKey:`delivery:${id}:finalized:v2`,documentType:'PV livraison',entityType:'delivery',entityId:id,fileName:`pv-${row.delivery_number}.pdf`,agencyId:String(row.agency_id),createdBy,buffer:await renderDeliveryDocument(id),afterInsert:async(connection,documentId)=>{await connection.execute(`INSERT IGNORE INTO document_mark_snapshots(document_id,document_context,signer_user_id,signature_version_id,signature_identity_snapshot,signature_hash,stamp_id,stamp_version_id,stamp_identity_snapshot,stamp_hash,applied_by) SELECT ?, 'DELIVERY_REPORT',ds.signed_by,ds.user_signature_version_id,CONCAT_WS(' ',u.first_name,u.last_name),us.file_hash,st.id,ds.service_stamp_version_id,st.name,sv.file_hash,ds.signed_by FROM delivery_signatures ds LEFT JOIN users u ON u.id=ds.signed_by LEFT JOIN user_signature_versions us ON us.id=ds.user_signature_version_id LEFT JOIN service_stamp_versions sv ON sv.id=ds.service_stamp_version_id LEFT JOIN service_stamps st ON st.id=sv.stamp_id WHERE ds.delivery_id=? AND (ds.user_signature_version_id IS NOT NULL OR ds.service_stamp_version_id IS NOT NULL)`,[documentId,id])}})}
export async function archiveDeliveryInTransaction(connection:PoolConnection,id:string,createdBy:string|null){const[rows]=await connection.execute<RowDataPacket[]>('SELECT id,delivery_number,agency_id,status FROM deliveries WHERE id=?',[id]),row=rows[0];if(!row||row.status!=='delivered')throw new HttpError(409,'Livraison finalisée introuvable');const buffer=await renderDeliveryDocument(id,connection),file={originalName:`pv-${row.delivery_number}.pdf`,mimeType:'application/pdf',buffer},stored=await storeDocument(file,String(row.agency_id)),hash=documentHash(buffer);try{if(process.env.NODE_ENV==='test')await businessArchiveTestHooks.afterDeliveryFileStored?.(stored.absolute);const[result]=await connection.execute<ResultSetHeader>(`INSERT INTO documents(uploaded_by,origin,source_key,title,document_type,file_name,file_url,mime_type,file_size,version,entity_type,entity_id,agency_id,concession_id,is_archived,file_hash) SELECT ?,'generated',?,?,?,?,?,?,?,1,'delivery',?,a.id,a.concession_id,FALSE,? FROM agencies a WHERE a.id=?`,[createdBy,`delivery:${id}:finalized:v2`,file.originalName,'PV livraison',file.originalName,`ged:${stored.storageKey}`,'application/pdf',buffer.length,id,hash,row.agency_id]);const documentId=String(result.insertId);await connection.execute(`INSERT INTO document_mark_snapshots(document_id,document_context,signer_user_id,signature_version_id,signature_identity_snapshot,signature_hash,stamp_id,stamp_version_id,stamp_identity_snapshot,stamp_hash,applied_by) SELECT ?, 'DELIVERY_REPORT',ds.signed_by,ds.user_signature_version_id,CONCAT_WS(' ',u.first_name,u.last_name),us.file_hash,st.id,ds.service_stamp_version_id,st.name,sv.file_hash,ds.signed_by FROM delivery_signatures ds LEFT JOIN users u ON u.id=ds.signed_by LEFT JOIN user_signature_versions us ON us.id=ds.user_signature_version_id LEFT JOIN service_stamp_versions sv ON sv.id=ds.service_stamp_version_id LEFT JOIN service_stamps st ON st.id=sv.stamp_id WHERE ds.delivery_id=? AND (ds.user_signature_version_id IS NOT NULL OR ds.service_stamp_version_id IS NOT NULL)`,[documentId,id]);return{documentId,absolute:stored.absolute,agencyId:String(row.agency_id)}}catch(error){await unlink(stored.absolute).catch(()=>undefined);throw error}}
export async function archiveCreditNote(id:string,createdBy:string|null){const[row]=await query<RowDataPacket[]>(`SELECT cn.*,i.invoice_number,i.agency_id,i.currency_code,COALESCE(c.company_name,CONCAT_WS(' ',c.first_name,c.last_name)) customer_name FROM credit_notes cn JOIN invoices i ON i.id=cn.invoice_id JOIN customers c ON c.id=cn.customer_id WHERE cn.id=?`,[id]);if(!row||!['issued','applied'].includes(String(row.status)))throw new HttpError(409,'Avoir émis introuvable');const buffer=await renderBusinessPdf('Avoir client',[["Numéro",row.credit_note_number],["Facture d’origine",row.invoice_number],["Client",row.customer_name],["Date",row.issue_date],["Montant",`${Number(row.amount).toFixed(2)} ${row.currency_code}`],["Motif",row.reason]]);return archiveBusinessDocument({sourceKey:`credit-note:${id}:issued:v1`,documentType:'Avoir client',entityType:'invoice',entityId:String(row.invoice_id),fileName:`avoir-${row.credit_note_number}.pdf`,agencyId:String(row.agency_id),createdBy,buffer})}
export async function archiveVehicleReturn(id:string,createdBy:string|null){const[row]=await query<RowDataPacket[]>('SELECT * FROM post_delivery_vehicle_returns WHERE id=?',[id]);if(!row||row.status!=='CLOSED')throw new HttpError(409,'Retour clôturé introuvable');const deductions=await query<RowDataPacket[]>('SELECT label,amount FROM post_delivery_vehicle_return_deductions WHERE return_id=? ORDER BY id',[id]),lines=[...deductions.map(x=>`Retenue — ${x.label}: ${Number(x.amount).toFixed(2)} ${row.currency_code}`),`Avoirs: ${Number(row.credited_amount).toFixed(2)} ${row.currency_code}`,`Remboursements: ${Number(row.refunded_amount).toFixed(2)} ${row.currency_code}`,`Décision stock: ${row.stock_decision}`];const buffer=await renderBusinessPdf('Procès-verbal de retour post-livraison',[["Dossier",row.return_number],["Livraison",row.delivery_number_snapshot],["Vente",row.sale_number_snapshot],["Client",row.customer_name_snapshot],["Véhicule",row.vehicle_label_snapshot],["VIN",row.vin_snapshot],["Kilométrage retour",row.return_mileage],["Décision",row.decision_comment]],lines);return archiveBusinessDocument({sourceKey:`vehicle-return:${id}:closed:v1`,documentType:'PV retour véhicule',entityType:'vehicle_return',entityId:id,fileName:`retour-${row.return_number}.pdf`,agencyId:String(row.agency_id),createdBy,buffer})}
