import PDFDocument from 'pdfkit';
import{readFile}from'node:fs/promises';
import type{RowDataPacket}from'mysql2/promise';
import{query}from'../../config/database.js';
import{HttpError}from'../../shared/http-error.js';
import{getBusinessIdentity}from'../settings/setting-resolver.js';
import{formatDocumentAmount}from'./document-money.js';

type Kind='DEVIS'|'FACTURE'|'BON DE COMMANDE';
const safe=(value:unknown)=>String(value??'').replace(/[\u0000-\u001f]/g,' ').trim();
const deliveryDate=(value:unknown)=>{if(value instanceof Date)return new Intl.DateTimeFormat('fr-CG',{dateStyle:'short',timeStyle:'short',timeZone:'Africa/Brazzaville'}).format(value);const raw=safe(value),match=/^(\d{4})-(\d{2})-(\d{2})(?:[ T](\d{2}):(\d{2}))?/.exec(raw);return match?`${match[3]}/${match[2]}/${match[1]}${match[4]?` ${match[4]}:${match[5]}`:''}`:raw};
const money=formatDocumentAmount;
let referenceLogo:Promise<string|null>|undefined;
export const getReferenceDocumentLogo=()=>referenceLogo??=readFile(new URL('../../../assets/logo-lca2.png',import.meta.url)).then(value=>value.toString('base64')).catch(()=>null);
export const documentLogoCandidates=(snapshotLogo:unknown,configuredLogo:unknown,reference:unknown)=>[snapshotLogo,configuredLogo,reference].filter(value=>typeof value==='string'&&value.length>0) as string[];
const parsedSnapshot=(value:unknown)=>{if(!value)return null;try{const saved=typeof value==='string'?JSON.parse(value):value;return saved&&typeof saved==='object'?saved as Record<string,unknown>:null}catch{return null}};
async function identityFor(agencyId:string,savedValue?:unknown){const live=await getBusinessIdentity(agencyId),saved=parsedSnapshot(savedValue),fallbackLogo=await getReferenceDocumentLogo();return{...live,...(saved??{}),logoCandidates:documentLogoCandidates(saved?.logoBase64,live.logoBase64,fallbackLogo)}}
function drawIdentityHeader(doc:PDFKit.PDFDocument,identity:any){
 let logoDrawn=false;
 for(const logo of identity.logoCandidates??[identity.logoBase64]){try{doc.image(Buffer.from(String(logo),'base64'),42,38,{fit:[95,55],valign:'center'});logoDrawn=true;break}catch{continue}}
 const x=logoDrawn?155:42,width=logoDrawn?398:511,align=logoDrawn?'right':'left';
 const name=safe(identity.legalName||identity.tradeName);
 // A visible logo already carries the concession name; without one, keep the textual identity.
 if(!logoDrawn&&name)doc.fillColor('#111827').font('Helvetica-Bold').fontSize(13).text(name,x,40,{width,align});
 const names=new Set([name.toLocaleLowerCase()]);
 const lines:unknown[]=[];
 if(!logoDrawn){const trade=safe(identity.tradeName);if(trade&&!names.has(trade.toLocaleLowerCase())){lines.push(trade);names.add(trade.toLocaleLowerCase())}}
 const agency=safe(identity.agencyName);if(agency&&!names.has(agency.toLocaleLowerCase()))lines.push(agency);
 lines.push([identity.agencyAddress,identity.agencyCity].filter(Boolean).join(', '),[identity.phone,identity.email].filter(Boolean).join(' · '),identity.taxIdentifier?`Identifiant fiscal : ${identity.taxIdentifier}`:'');
 doc.fillColor('#111827').font('Helvetica').fontSize(8).text(lines.filter(Boolean).map(safe).join('\n'),x,58,{width,align});
}
async function render(kind:Kind,header:RowDataPacket,items:RowDataPacket[]){
 const identity=await identityFor(String(header.agency_id),header.document_identity_snapshot);
 return renderCommercialDocument(kind,header,items,identity);
}
export async function renderCommercialDocument(kind:Kind,header:RowDataPacket,items:RowDataPacket[],identity:any){
 const currency=String(header.currency_code??identity.currencyCode??'XAF'),chunks:Buffer[]=[];
 return new Promise<Buffer>((resolve,reject)=>{const doc=new PDFDocument({size:'A4',margin:42,bufferPages:true,info:{Title:`${kind} ${header.number}`}});doc.on('data',(x:Buffer)=>chunks.push(x));doc.on('error',reject);doc.on('end',()=>resolve(Buffer.concat(chunks)));
const headerBlock=()=>{drawIdentityHeader(doc,identity);doc.moveTo(42,110).lineTo(553,110).strokeColor('#8f1722').lineWidth(1.2).stroke();doc.fillColor('#8f1722').font('Helvetica-Bold').fontSize(kind==='BON DE COMMANDE'?17:22).text(kind,42,126,{width:280}).fillColor('#111827').fontSize(12).text(safe(header.number),42,153);doc.font('Helvetica').fontSize(8).text(`${kind==='DEVIS'?'Date':'Émission'} : ${safe(header.document_date)}${header.due_date?`   ·   Échéance : ${safe(header.due_date)}`:''}`,330,135,{width:223,align:'right'});doc.roundedRect(42,180,511,100,4).fillAndStroke('#f8fafc','#cbd5e1');doc.fillColor('#64748b').font('Helvetica-Bold').fontSize(8).text('CLIENT',55,192).fillColor('#111827').fontSize(11).text(safe(header.customer_name),55,207,{width:235,height:28}).font('Helvetica').fontSize(8).text([header.customer_code,header.customer_phone,header.customer_email,header.customer_address].filter(Boolean).map(safe).join('\n'),55,238,{width:235,height:34});doc.fillColor('#64748b').font('Helvetica-Bold').text('RÉFÉRENCES',330,192).fillColor('#111827').font('Helvetica').text([header.related_number&&`Vente / devis : ${header.related_number}`,header.salesperson_name&&`Commercial : ${header.salesperson_name}`,header.valid_until&&`Valable jusqu’au : ${header.valid_until}`].filter(Boolean).join('\n'),330,207,{width:205});};
 const tableHeader=(y:number)=>{doc.rect(42,y,511,24).fill('#8f1722');doc.fillColor('#fff').font('Helvetica-Bold').fontSize(7);[['Désignation',48,195],['Qté',246,32],['PU HT',281,75],['Remise',359,65],['TVA',427,42],['Total TTC',472,76]].forEach(([t,x,w])=>doc.text(String(t),Number(x),y+8,{width:Number(w),align:Number(x)>280?'right':'left'}));return y+24};
headerBlock();let y=tableHeader(295);for(const item of items){const description=safe(item.description),height=Math.max(28,doc.heightOfString(description,{width:192})+12);if(y+height>690){doc.addPage();headerBlock();y=tableHeader(295)}doc.rect(42,y,511,height).strokeColor('#e2e8f0').stroke();doc.fillColor('#111827').font('Helvetica').fontSize(7.5).text(description,48,y+7,{width:232,height:height-10});doc.text(safe(item.quantity),246,y+7,{width:32,align:'right'}).text(money(item.unit_price,currency),281,y+7,{width:75,align:'right'}).text(money(item.discount,currency),359,y+7,{width:65,align:'right'}).text(header.tax_mode==='TAX_EXEMPT'?'—':`${safe(item.tax_rate)} %`,427,y+7,{width:42,align:'right'}).font('Helvetica-Bold').text(money(item.line_total,currency),472,y+7,{width:76,align:'right'});y+=height}
 if(y>500){doc.addPage();headerBlock();y=295}doc.roundedRect(330,y+18,223,118,4).fillAndStroke('#f8fafc','#cbd5e1');const rows=header.tax_mode==='TAX_EXEMPT'?[['Sous-total',header.subtotal],['Remise',header.discount_total],['TVA','Sans TVA'],['TOTAL',header.total]]:[['Sous-total HT',header.subtotal],['Remise',header.discount_total],[`TVA ${header.tax_rate_snapshot} %`,header.tax_total],['TOTAL TTC',header.total]];rows.forEach(([label,value],i)=>{doc.fillColor(i===rows.length-1?'#8f1722':'#334155').font(i===rows.length-1?'Helvetica-Bold':'Helvetica').fontSize(i===rows.length-1?11:8).text(String(label),342,y+31+i*22,{width:95}).text(value==='Sans TVA'?value:money(value,currency),435,y+31+i*22,{width:105,align:'right'})});doc.fillColor('#111827').font('Helvetica').fontSize(8).text(header.notes?safe(header.notes):'',42,y+25,{width:260,height:75});doc.font('Helvetica-Bold').text('Signature client',42,y+154,{width:180,align:'center'}).text('Pour l’entreprise · Signature / Cachet',350,y+154,{width:203,align:'center'});doc.moveTo(42,y+205).lineTo(222,y+205).moveTo(350,y+205).lineTo(553,y+205).strokeColor('#94a3b8').stroke();
 const range=doc.bufferedPageRange();for(let i=0;i<range.count;i++){doc.switchToPage(i);doc.fillColor('#64748b').font('Helvetica').fontSize(7).text([identity.legalName||identity.tradeName,identity.taxIdentifier,identity.phone,identity.email].filter(Boolean).map(safe).join(' • '),42,780,{width:430,align:'left',lineBreak:false}).text(`Page ${i+1} / ${range.count}`,480,780,{width:73,align:'right',lineBreak:false})}doc.end()})
}

const repairStatusLabel:Record<string,string>={planned:'Planifié',received:'Réceptionné',diagnosis:'Diagnostic',waiting_approval:'Attente validation client',in_progress:'En cours',quality_control:'Contrôle qualité',ready:'Prêt',invoiced:'Facturé',delivered:'Livré',closed:'Clôturé',cancelled:'Annulé'};
export async function renderRepairOrderDocument(order:any,identityOverride?:any){
 const identity=identityOverride??await identityFor(String(order.agency_id)),currency=String(order.financialSummary?.currencyCode??identity.currencyCode??'XAF'),chunks:Buffer[]=[];
 return new Promise<Buffer>((resolve,reject)=>{const doc=new PDFDocument({size:'A4',margin:42,bufferPages:true,info:{Title:`ORDRE DE RÉPARATION ${safe(order.order_number)}`}});doc.on('data',(chunk:Buffer)=>chunks.push(chunk));doc.on('error',reject);doc.on('end',()=>resolve(Buffer.concat(chunks)));
  const pageHeader=()=>{drawIdentityHeader(doc,identity);doc.moveTo(42,110).lineTo(553,110).strokeColor('#8f1722').lineWidth(1.2).stroke();doc.fillColor('#8f1722').font('Helvetica-Bold').fontSize(18).text('ORDRE DE RÉPARATION',42,126,{width:320}).fillColor('#111827').fontSize(11).text(safe(order.order_number),42,151);doc.font('Helvetica').fontSize(8).text(`Date : ${deliveryDate(order.created_at)||'—'}\nStatut : ${repairStatusLabel[order.status]??safe(order.status)}`,330,132,{width:223,align:'right'});};
  const newPage=()=>{doc.addPage();pageHeader();return 180};
  const band=(title:string,y:number)=>{if(y+34>735)y=newPage();doc.rect(42,y,511,23).fill('#8f1722');doc.fillColor('#fff').font('Helvetica-Bold').fontSize(8).text(title,52,y+8,{width:490});return y+23};
  const block=(title:string,text:unknown,y:number)=>{y=band(title,y);const value=safe(text)||'—';doc.font('Helvetica').fontSize(8.5);const height=Math.max(34,doc.heightOfString(value,{width:491})+14);if(y+height>735){y=newPage();y=band(title,y)}doc.rect(42,y,511,height).strokeColor('#e2e8f0').stroke();doc.fillColor('#111827').text(value,52,y+7,{width:491});return y+height+10};
  const lines=(title:string,items:any[],y:number)=>{y=band(title,y);const rows=items.length?items:[{description:'Aucune ligne facturable',quantity:'—',unit_price:0,discount:0,tax_rate:0,line_total:0}];for(const item of rows){const label=`${item.part_reference?`${safe(item.part_reference)} · `:''}${safe(item.description)}`;doc.font('Helvetica').fontSize(7.5);const height=Math.max(28,doc.heightOfString(label,{width:208})+12);if(y+height>720){y=newPage();y=band(`${title} (SUITE)`,y)}doc.rect(42,y,511,height).strokeColor('#e2e8f0').stroke();doc.fillColor('#111827').text(label,48,y+7,{width:208}).text(safe(item.quantity),260,y+7,{width:35,align:'right'}).text(money(item.unit_price,currency),300,y+7,{width:80,align:'right'}).text(money(item.discount,currency),385,y+7,{width:70,align:'right'}).text(`${safe(item.tax_rate)} %`,460,y+7,{width:38,align:'right'}).font('Helvetica-Bold').text(money(Number(item.line_total)*(1+Number(item.tax_rate)/100),currency),502,y+7,{width:47,align:'right'});y+=height}return y+10};
  pageHeader();let y=180;doc.roundedRect(42,y,511,104,4).fillAndStroke('#f8fafc','#cbd5e1');doc.fillColor('#64748b').font('Helvetica-Bold').fontSize(7).text('CLIENT',54,y+12).text('VÉHICULE',310,y+12);doc.fillColor('#111827').fontSize(10).text(safe(order.customer_name)||'—',54,y+27,{width:230}).text(safe(order.vehicle_label)||'—',310,y+27,{width:230});doc.font('Helvetica').fontSize(8).text([order.customer_phone,order.agency_name&&`Agence : ${order.agency_name}`].filter(Boolean).map(safe).join('\n'),54,y+49,{width:230}).text([`VIN : ${safe(order.vin)||'—'}`,`Immatriculation : ${safe(order.registration_number)||'—'}`,`Kilométrage : ${safe(order.mileage_in)||'—'}`].join('\n'),310,y+49,{width:230});y+=118;
  y=block('MOTIF / SYMPTÔMES',order.complaint,y);if(order.inspection)y=block('RÉCEPTION',[`Carburant : ${safe(order.inspection.fuel_level)||'—'}`,`Propreté : ${safe(order.inspection.cleanliness)||'—'}`,order.inspection.bodywork_damage&&`Carrosserie : ${safe(order.inspection.bodywork_damage)}`,order.inspection.observations&&`Observations : ${safe(order.inspection.observations)}`].filter(Boolean).join('\n'),y);
  y=block('DIAGNOSTIC',(order.diagnostics??[]).map((item:any)=>`${safe(item.diagnosis)}${item.recommendations?` — ${safe(item.recommendations)}`:''}`).join('\n'),y);y=block('INTERVENTIONS RÉALISÉES',(order.interventions??[]).filter((item:any)=>item.status!=='cancelled').map((item:any)=>`${safe(item.description)} — ${item.status==='completed'?'Terminée':safe(item.status)}`).join('\n'),y);
  const active=(order.items??[]).filter((item:any)=>item.status==='active');y=lines('PIÈCES FACTURABLES',active.filter((item:any)=>item.item_type==='part'),y);y=lines('MAIN-D’ŒUVRE FACTURABLE',active.filter((item:any)=>item.item_type==='labor'),y);
  if(y+154>720)y=newPage();const totals=order.financialSummary??{};doc.roundedRect(310,y,243,126,4).fillAndStroke('#f8fafc','#cbd5e1');[['Sous-total HT',totals.subtotal],['Remises',totals.discount],['TVA',totals.tax],['TOTAL TTC',totals.total]].forEach(([label,value],index)=>{doc.fillColor(index===3?'#8f1722':'#334155').font(index===3?'Helvetica-Bold':'Helvetica').fontSize(index===3?11:8).text(String(label),323,y+16+index*25,{width:95}).text(money(value,currency),420,y+16+index*25,{width:120,align:'right'})});
  const invoice=order.invoice;if(invoice)doc.fillColor('#111827').font('Helvetica').fontSize(8).text(`Facture : ${safe(invoice.invoice_number)}\nTotal facture : ${money(invoice.total,currency)}\nEncaissé : ${money(invoice.amount_paid,currency)}\nSolde : ${money(invoice.balance_due,currency)}`,42,y+8,{width:240});const qc=order.qualityControls?.[0];if(qc)doc.text(`Contrôle qualité : ${qc.result==='passed'?'Validé':'Refusé'}${qc.observations?`\n${safe(qc.observations)}`:''}`,42,y+74,{width:240});
  const range=doc.bufferedPageRange();for(let index=0;index<range.count;index++){doc.switchToPage(index);doc.fillColor('#64748b').font('Helvetica').fontSize(7).text([identity.legalName||identity.tradeName,identity.taxIdentifier,identity.phone,identity.email].filter(Boolean).map(safe).join(' • '),42,780,{width:430,lineBreak:false}).text(`Page ${index+1} / ${range.count}`,480,780,{width:73,align:'right',lineBreak:false})}doc.end();
 });
}
export async function renderQuotationDocument(id:string){const[header]=await query<RowDataPacket[]>(`SELECT q.*,q.quotation_number number,q.created_at document_date,COALESCE(c.company_name,CONCAT_WS(' ',c.first_name,c.last_name)) customer_name,c.customer_code,c.phone customer_phone,c.email customer_email,c.address customer_address,CONCAT_WS(' ',u.first_name,u.last_name) salesperson_name,NULL related_number FROM quotations q JOIN customers c ON c.id=q.customer_id LEFT JOIN opportunities o ON o.id=q.opportunity_id LEFT JOIN users u ON u.id=o.assigned_user_id WHERE q.id=?`,[id]);if(!header)throw new HttpError(404,'Devis introuvable');const items=await query<RowDataPacket[]>('SELECT * FROM quotation_items WHERE quotation_id=? ORDER BY id',[id]);return render('DEVIS',header,items)}
export async function renderInvoiceDocument(id:string){const[header]=await query<RowDataPacket[]>(`SELECT i.*,i.invoice_number number,i.issue_date document_date,COALESCE(c.company_name,CONCAT_WS(' ',c.first_name,c.last_name)) customer_name,c.customer_code,c.phone customer_phone,c.email customer_email,c.address customer_address,CONCAT_WS(' ',u.first_name,u.last_name) salesperson_name,CONCAT_WS(' / ',s.sale_number,q.quotation_number) related_number FROM invoices i JOIN customers c ON c.id=i.customer_id LEFT JOIN sales s ON s.id=i.sale_id LEFT JOIN quotations q ON q.id=s.quotation_id LEFT JOIN users u ON u.id=s.salesperson_id WHERE i.id=?`,[id]);if(!header)throw new HttpError(404,'Facture introuvable');const items=await query<RowDataPacket[]>('SELECT * FROM invoice_items WHERE invoice_id=? ORDER BY id',[id]);return render('FACTURE',header,items)}
export async function renderSaleOrderDocument(id:string){const[header]=await query<RowDataPacket[]>(`SELECT s.*,s.sale_number number,s.created_at document_date,q.quotation_number related_number,COALESCE(c.company_name,CONCAT_WS(' ',c.first_name,c.last_name)) customer_name,c.customer_code,c.phone customer_phone,c.email customer_email,c.address customer_address,CONCAT_WS(' ',u.first_name,u.last_name) salesperson_name FROM sales s JOIN customers c ON c.id=s.customer_id LEFT JOIN quotations q ON q.id=s.quotation_id LEFT JOIN users u ON u.id=s.salesperson_id WHERE s.id=?`,[id]);if(!header)throw new HttpError(404,'Vente introuvable');const items=await query<RowDataPacket[]>(`SELECT si.description,si.quantity,si.unit_price,si.discount,si.tax_rate,si.line_total FROM sale_items si WHERE si.sale_id=? ORDER BY si.id`,[id]);return render('BON DE COMMANDE',header,items)}

export async function renderPaymentReceiptData(payment:any,identityOverride?:any){
 const identity=identityOverride??await identityFor(String(payment.agency_id)),currency=String(payment.currency_code??identity.currencyCode??'XAF'),chunks:Buffer[]=[];
 return new Promise<Buffer>((resolve,reject)=>{const doc=new PDFDocument({size:'A4',margin:42,bufferPages:true,info:{Title:`REÇU DE PAIEMENT ${safe(payment.payment_number)}`}});doc.on('data',(x:Buffer)=>chunks.push(x));doc.on('error',reject);doc.on('end',()=>resolve(Buffer.concat(chunks)));
 drawIdentityHeader(doc,identity);
 doc.moveTo(42,110).lineTo(553,110).strokeColor('#8f1722').lineWidth(1.2).stroke();
 doc.fillColor('#8f1722').font('Helvetica-Bold').fontSize(20).text('REÇU DE PAIEMENT',42,126,{width:350});
 doc.fillColor('#111827').fontSize(11).text(safe(payment.payment_number),42,154);
 doc.font('Helvetica').fontSize(8).text(`Date d’encaissement : ${deliveryDate(payment.payment_date)||'—'}`,320,138,{width:233,align:'right'});
 doc.roundedRect(42,185,511,103,4).fillAndStroke('#f8fafc','#cbd5e1');
 doc.fillColor('#64748b').font('Helvetica-Bold').fontSize(8).text('CLIENT',55,198).text('FACTURE',330,198);
 doc.fillColor('#111827').fontSize(11).text(safe(payment.customer_name)||'—',55,216,{width:245}).text(safe(payment.invoice_number)||'—',330,216,{width:205});
 doc.rect(42,313,511,27).fill('#8f1722');doc.fillColor('#fff').font('Helvetica-Bold').fontSize(8).text('MONTANT ENCAISSÉ',52,322);
 doc.roundedRect(42,340,511,78,4).fillAndStroke('#f8fafc','#cbd5e1');
 doc.fillColor('#8f1722').font('Helvetica-Bold').fontSize(23).text(money(payment.amount,currency),52,359,{width:491,align:'right'});
 doc.fillColor('#64748b').font('Helvetica-Bold').fontSize(8).text('MODE DE PAIEMENT',52,451).text('RÉFÉRENCE DE TRANSACTION',315,451);
 doc.fillColor('#111827').font('Helvetica').fontSize(10).text(safe(payment.payment_method)||'—',52,467,{width:230}).text(safe(payment.reference)||'—',315,467,{width:230});
 doc.fillColor('#64748b').font('Helvetica-Bold').fontSize(8).text('ENCAISSÉ PAR',52,516);
 doc.fillColor('#111827').font('Helvetica').fontSize(10).text(safe(payment.received_by_name)||'—',52,532,{width:300});
 doc.fillColor('#64748b').font('Helvetica').fontSize(7).text([identity.legalName||identity.tradeName,identity.taxIdentifier,identity.phone,identity.email].filter(Boolean).map(safe).join(' • '),42,780,{width:430,align:'left',lineBreak:false}).text('Page 1 / 1',480,780,{width:73,align:'right',lineBreak:false});doc.end()})
}

export async function renderDeliveryDocumentData(delivery:any,identityOverride?:any){
 const identity=identityOverride??await identityFor(String(delivery.agency_id)),chunks:Buffer[]=[];
 return new Promise<Buffer>((resolve,reject)=>{
  const doc=new PDFDocument({size:'A4',margin:42,bufferPages:true,info:{Title:`PROCÈS-VERBAL DE LIVRAISON ${safe(delivery.delivery_number)}`}});
  doc.on('data',(x:Buffer)=>chunks.push(x));doc.on('error',reject);doc.on('end',()=>resolve(Buffer.concat(chunks)));
  const pageHeader=()=>{drawIdentityHeader(doc,identity);doc.moveTo(42,110).lineTo(553,110).strokeColor('#8f1722').lineWidth(1.2).stroke();doc.fillColor('#8f1722').font('Helvetica-Bold').fontSize(17).text('PROCÈS-VERBAL DE LIVRAISON',42,126,{width:350}).fillColor('#111827').fontSize(11).text(safe(delivery.delivery_number),42,151);doc.font('Helvetica').fontSize(8).text(`Date de remise : ${deliveryDate(delivery.delivered_at||delivery.scheduled_at)||'—'}`,330,137,{width:223,align:'right'});};
  const nextPage=()=>{doc.addPage();pageHeader();return 180};
  const band=(title:string,y:number)=>{doc.roundedRect(42,y,511,23,3).fill('#8f1722');doc.fillColor('#fff').font('Helvetica-Bold').fontSize(8).text(title,52,y+8,{width:490});return y+23};
  const detailField=(label:string,value:unknown,x:number,y:number,width=225)=>{doc.fillColor('#64748b').font('Helvetica-Bold').fontSize(7).text(label.toUpperCase(),x,y,{width});doc.fillColor('#111827').font('Helvetica').fontSize(9).text(safe(value)||'—',x,y+13,{width,height:27});};
  const card=(y:number,height:number)=>{doc.roundedRect(42,y,511,height,4).fillAndStroke('#f8fafc','#cbd5e1')};
  const list=(title:string,entries:{name:string;status:string}[],start:number)=>{let y=start;if(y+54>710)y=nextPage();y=band(title,y);const rows=entries.length?entries:[{name:'Aucun élément enregistré',status:'—'}];for(const entry of rows){doc.font('Helvetica').fontSize(8.5);const h=Math.max(27,doc.heightOfString(entry.name,{width:395})+12);if(y+h>710){y=nextPage();y=band(`${title} (SUITE)`,y)}doc.rect(42,y,511,h).strokeColor('#e2e8f0').stroke();doc.fillColor('#111827').font('Helvetica').fontSize(8.5).text(entry.name,52,y+7,{width:395});doc.fillColor(entry.status==='OK'?'#334155':'#8f1722').font('Helvetica-Bold').fontSize(8).text(entry.status,457,y+7,{width:84,align:'right'});y+=h}return y};
  const observations=[delivery.quality_notes&&`Contrôle qualité / réserves : ${safe(delivery.quality_notes)}`,delivery.customer_notes&&`Observations client : ${safe(delivery.customer_notes)}`,...(delivery.checklist??[]).filter((item:any)=>item.notes).map((item:any)=>`${safe(item.item_name)} : ${safe(item.notes)}`)].filter(Boolean) as string[];
  pageHeader();let y=180;
  card(y,101);doc.fillColor('#8f1722').font('Helvetica-Bold').fontSize(8).text('CLIENT ET LIVRAISON',52,y+12);detailField('Client',delivery.customer_name,52,y+34);detailField('Lieu de livraison',delivery.delivery_location,315,y+34);detailField('Responsable livraison',delivery.delivery_specialist_name,52,y+71);detailField('Date prévue',deliveryDate(delivery.scheduled_at),315,y+71);y+=115;
  card(y,106);doc.fillColor('#8f1722').font('Helvetica-Bold').fontSize(8).text('VÉHICULE REMIS',52,y+12);detailField('Véhicule',delivery.vehicle_label,52,y+34);detailField('VIN / châssis',delivery.vin,315,y+34);detailField('Immatriculation',delivery.registration_number,52,y+72);detailField('Kilométrage',delivery.mileage_at_delivery,315,y+72);y+=120;
  y=list('CONTRÔLE DE LIVRAISON',(delivery.checklist??[]).map((item:any)=>({name:safe(item.item_name),status:item.is_completed?'OK':'NON'})),y);
  y=list('DOCUMENTS ET ÉLÉMENTS REMIS',(delivery.documents??[]).map((item:any)=>({name:`${safe(item.document_name)}${item.is_required?' (obligatoire)':''}`,status:item.received?'OK':'NON'})),y+12);
  if(observations.length){if(y+65>710)y=nextPage();y=band('OBSERVATIONS ET RÉSERVES',y+12)+10;for(const [observationIndex,observation] of observations.entries()){const words=observation.split(/\s+/),parts:string[]=[];let part='';for(const word of words){if((part+' '+word).length>145&&part){parts.push(part);part=''}part+=(part?' ':'')+word}if(part)parts.push(part);if(parts.length>1&&(parts[parts.length-1]?.length??0)<45){const tail=parts.pop()!;parts[parts.length-1]=(parts[parts.length-1]??'')+' '+tail}for(const [pieceIndex,piece] of parts.entries()){if(observationIndex===observations.length-1&&parts.length-pieceIndex<=4&&y>555){y=nextPage();y=band('OBSERVATIONS ET RÉSERVES (SUITE)',y)+10}doc.font('Helvetica').fontSize(8.5);const h=Math.max(16,doc.heightOfString(piece,{width:490})+4);if(y+h>710){y=nextPage();y=band('OBSERVATIONS ET RÉSERVES (SUITE)',y)+10}doc.fillColor('#111827').font('Helvetica').fontSize(8.5).text(piece,52,y,{width:490});y+=h}y+=7}}
  if(y+158>735)y=nextPage();y=band('REMISE DU VÉHICULE / ACCEPTATION',y+12)+12;
  card(y,130);const signature=delivery.signatures?.[0];
  doc.fillColor('#111827').font('Helvetica-Bold').fontSize(9).text('LE CLIENT',52,y+12,{width:220}).text('POUR LA CONCESSION',315,y+12,{width:220});
  doc.font('Helvetica').fontSize(8).text(`Nom : ${safe(signature?.signer_name)||'—'}`,52,y+31,{width:220}).text(`Responsable : ${safe(delivery.delivery_specialist_name)||'—'}`,315,y+31,{width:220});
  const signatureData=String(signature?.signature_data??'');let imageDrawn=false;
  if(signatureData.startsWith('data:image/png;base64,'))try{doc.image(Buffer.from(signatureData.split(',')[1]??'','base64'),52,y+49,{fit:[180,55]});imageDrawn=true}catch{doc.fillColor('#64748b').font('Helvetica').fontSize(7).text('Signature enregistrée mais image illisible',52,y+54)};
  if(!imageDrawn)doc.moveTo(52,y+106).lineTo(242,y+106).strokeColor('#94a3b8').stroke();
  doc.moveTo(315,y+106).lineTo(535,y+106).strokeColor('#94a3b8').stroke();
  doc.fillColor('#64748b').font('Helvetica').fontSize(7).text(`Signature enregistrée le : ${deliveryDate(signature?.signed_at)||'—'}`,52,y+113,{width:220}).text('Signature / cachet',315,y+113,{width:220});
  if(signature?.document_hash)doc.text(`Empreinte : ${safe(signature.document_hash)}`,52,y+144,{width:483});
  const range=doc.bufferedPageRange();for(let i=0;i<range.count;i++){doc.switchToPage(i);doc.fillColor('#64748b').font('Helvetica').fontSize(7).text([identity.legalName||identity.tradeName,identity.taxIdentifier,identity.phone,identity.email].filter(Boolean).map(safe).join(' • '),42,780,{width:430,align:'left',lineBreak:false}).text(`Page ${i+1} / ${range.count}`,480,780,{width:73,align:'right',lineBreak:false})}doc.end()
 })
}

export async function renderDeliveryDocument(id:string){const[delivery]=await query<RowDataPacket[]>(`SELECT d.*,COALESCE(c.company_name,CONCAT_WS(' ',c.first_name,c.last_name)) customer_name,v.vin,v.registration_number,CONCAT_WS(' ',b.name,m.name,ve.name) vehicle_label,CONCAT_WS(' ',u.first_name,u.last_name) delivery_specialist_name FROM deliveries d JOIN customers c ON c.id=d.customer_id JOIN vehicles v ON v.id=d.vehicle_id JOIN versions ve ON ve.id=v.version_id JOIN models m ON m.id=ve.model_id JOIN brands b ON b.id=m.brand_id LEFT JOIN users u ON u.id=d.delivery_specialist_id WHERE d.id=?`,[id]);if(!delivery)throw new HttpError(404,'Livraison introuvable');const[checklist,documents,signatures]=await Promise.all([query<RowDataPacket[]>('SELECT item_name,is_completed,notes FROM delivery_checklists WHERE delivery_id=? ORDER BY sort_order,id',[id]),query<RowDataPacket[]>('SELECT document_name,is_required,received FROM delivery_documents WHERE delivery_id=? ORDER BY id',[id]),query<RowDataPacket[]>('SELECT signer_name,signature_data,document_hash,signed_at FROM delivery_signatures WHERE delivery_id=? ORDER BY signed_at DESC LIMIT 1',[id])]);return renderDeliveryDocumentData({...delivery,checklist,documents,signatures})}
