import type{Request}from'express';
import type{ResultSetHeader,RowDataPacket}from'mysql2/promise';
import{execute,query}from'../../config/database.js';
import{HttpError}from'../../shared/http-error.js';

const text=(value:unknown,label:string,max:number)=>{const result=typeof value==='string'?value.trim():'';if(!result)throw new HttpError(400,`${label} obligatoire`);return result.slice(0,max)};
const id=(value:unknown,label='Identifiant')=>{const result=String(value??'');if(!/^[1-9]\d*$/.test(result))throw new HttpError(400,`${label} invalide`);return result};
const code=(value:unknown)=>text(value,'Code',100).toUpperCase().replace(/[^A-Z0-9]+/g,'_').replace(/^_|_$/g,'');
const order=(value:unknown)=>Math.max(0,Math.min(65535,Number(value)||0));

export async function list(includeInactive=false){
 const active=includeInactive?'':' WHERE c.is_active=TRUE',typeActive=includeInactive?'':' AND t.is_active=TRUE';
 const categories=await query<RowDataPacket[]>(`SELECT c.* FROM document_categories c${active} ORDER BY c.display_order,c.name`);
 const types=await query<RowDataPacket[]>(`SELECT t.*,c.name category_name,c.is_active category_is_active FROM document_types t JOIN document_categories c ON c.id=t.category_id WHERE 1=1${typeActive}${includeInactive?'':' AND c.is_active=TRUE'} ORDER BY c.display_order,t.display_order,t.name`);
 return{categories:categories.map(x=>({...x,id:String(x.id),isActive:Boolean(x.is_active),displayOrder:Number(x.display_order)})),types:types.map(x=>({...x,id:String(x.id),categoryId:String(x.category_id),isActive:Boolean(x.is_active),categoryIsActive:Boolean(x.category_is_active),displayOrder:Number(x.display_order)}))};
}
export async function activeType(categoryId:string,typeId:string){const[row]=await query<RowDataPacket[]>('SELECT t.id,t.name,t.category_id,c.name category_name FROM document_types t JOIN document_categories c ON c.id=t.category_id WHERE t.id=? AND t.category_id=? AND t.is_active=TRUE AND c.is_active=TRUE',[id(typeId,'Type'),id(categoryId,'Catégorie')]);if(!row)throw new HttpError(400,'Catégorie ou type documentaire inactif, introuvable ou incohérent');return row}
export async function createCategory(body:any,request:Request){try{const result=await execute('INSERT INTO document_categories(code,name,display_order,is_active,created_by,updated_by) VALUES(?,?,?,?,?,?)',[code(body.code),text(body.name,'Nom',120),order(body.displayOrder),body.isActive!==false,request.user!.sub,request.user!.sub])as ResultSetHeader;return{id:String(result.insertId)}}catch(error:any){if(error?.code==='ER_DUP_ENTRY')throw new HttpError(409,'Cette catégorie existe déjà');throw error}}
export async function updateCategory(value:string,body:any,request:Request){const categoryId=id(value);const sets:string[]=[],params:unknown[]=[];if(body.code!=null){sets.push('code=?');params.push(code(body.code))}if(body.name!=null){sets.push('name=?');params.push(text(body.name,'Nom',120))}if(body.displayOrder!=null){sets.push('display_order=?');params.push(order(body.displayOrder))}if(body.isActive!=null){sets.push('is_active=?');params.push(Boolean(body.isActive))}if(!sets.length)throw new HttpError(400,'Aucune modification');try{const result=await execute(`UPDATE document_categories SET ${sets.join(',')},updated_by=? WHERE id=?`,[...params,request.user!.sub,categoryId]);if(!result.affectedRows)throw new HttpError(404,'Catégorie introuvable');return{success:true}}catch(error:any){if(error?.code==='ER_DUP_ENTRY')throw new HttpError(409,'Cette catégorie existe déjà');throw error}}
export async function createType(body:any,request:Request){const categoryId=id(body.categoryId,'Catégorie');try{const result=await execute('INSERT INTO document_types(category_id,code,name,display_order,is_active,created_by,updated_by) SELECT ?,?,?,?,?,?,? FROM document_categories WHERE id=?',[categoryId,code(body.code),text(body.name,'Nom',120),order(body.displayOrder),body.isActive!==false,request.user!.sub,request.user!.sub,categoryId])as ResultSetHeader;if(!result.affectedRows)throw new HttpError(404,'Catégorie introuvable');return{id:String(result.insertId)}}catch(error:any){if(error?.code==='ER_DUP_ENTRY')throw new HttpError(409,'Ce type documentaire existe déjà');throw error}}
export async function updateType(value:string,body:any,request:Request){const typeId=id(value);const sets:string[]=[],params:unknown[]=[];if(body.categoryId!=null){sets.push('category_id=?');params.push(id(body.categoryId,'Catégorie'))}if(body.code!=null){sets.push('code=?');params.push(code(body.code))}if(body.name!=null){sets.push('name=?');params.push(text(body.name,'Nom',120))}if(body.displayOrder!=null){sets.push('display_order=?');params.push(order(body.displayOrder))}if(body.isActive!=null){sets.push('is_active=?');params.push(Boolean(body.isActive))}if(!sets.length)throw new HttpError(400,'Aucune modification');try{const result=await execute(`UPDATE document_types SET ${sets.join(',')},updated_by=? WHERE id=?`,[...params,request.user!.sub,typeId]);if(!result.affectedRows)throw new HttpError(404,'Type documentaire introuvable');return{success:true}}catch(error:any){if(error?.code==='ER_DUP_ENTRY')throw new HttpError(409,'Ce type documentaire existe déjà');throw error}}
