import type{Request}from'express';import type{RowDataPacket}from'mysql2/promise';import{query}from'../../config/database.js';import{HttpError}from'../../shared/http-error.js';
export const ENTITY_TYPES=['customer','vehicle','sale','invoice','repair_order','delivery','supplier','expense','budget','employee']as const;export type DocumentEntityType=typeof ENTITY_TYPES[number];
type Entity={entityType:DocumentEntityType;entityId:string;agencyId:string|null;concessionId:string|null;agencyName:string|null;label:string;businessId:string};export type GedPermission='ged.view'|'ged.upload'|'ged.archive';type Scope='OWN'|'AGENCY'|'CONCESSION'|'GLOBAL';
const POLICIES:Record<DocumentEntityType,string[]>={customer:['customers.view'],vehicle:['vehicles.view'],sale:['sales.view'],invoice:['billing.view'],repair_order:['service.order.view','workshop.view'],delivery:['delivery.view'],supplier:['parts.suppliers.view'],expense:['hr.expense.view','hr.expense.create'],budget:['hr.budget.view'],employee:['hr.employees.view']};
const simple=(table:string,num:string,prefix:string)=>({sql:`SELECT x.id,x.agency_id,a.concession_id,a.name agency_name,CONCAT('${prefix} ',x.${num}) label,x.${num} business_id FROM ${table} x JOIN agencies a ON a.id=x.agency_id WHERE x.id=?`,search:`SELECT x.id,x.agency_id,a.concession_id,a.name agency_name,CONCAT('${prefix} ',x.${num}) label,x.${num} business_id FROM ${table} x JOIN agencies a ON a.id=x.agency_id WHERE x.${num} LIKE ?`});
const configs:Record<DocumentEntityType,{sql:string;search:string}>={
 customer:{sql:`SELECT c.id,c.agency_id,a.concession_id,a.name agency_name,COALESCE(NULLIF(c.company_name,''),CONCAT_WS(' ',c.first_name,c.last_name)) label,c.customer_code business_id FROM customers c JOIN agencies a ON a.id=c.agency_id WHERE c.id=?`,search:`SELECT c.id,c.agency_id,a.concession_id,a.name agency_name,CONCAT(COALESCE(NULLIF(c.company_name,''),CONCAT_WS(' ',c.first_name,c.last_name)),' — ',c.customer_code) label,c.customer_code business_id FROM customers c JOIN agencies a ON a.id=c.agency_id WHERE CONCAT_WS(' ',c.customer_code,c.first_name,c.last_name,c.company_name,c.phone) LIKE ?`},
 vehicle:{sql:`SELECT v.id,v.agency_id,a.concession_id,a.name agency_name,CONCAT_WS(' · ',v.registration_number,v.vin,CONCAT(b.name,' ',m.name)) label,COALESCE(v.stock_number,v.vin) business_id FROM vehicles v JOIN versions ve ON ve.id=v.version_id JOIN models m ON m.id=ve.model_id JOIN brands b ON b.id=m.brand_id JOIN agencies a ON a.id=v.agency_id WHERE v.id=?`,search:`SELECT v.id,v.agency_id,a.concession_id,a.name agency_name,CONCAT_WS(' · ',v.stock_number,v.registration_number,v.vin,CONCAT(b.name,' ',m.name)) label,COALESCE(v.stock_number,v.vin) business_id FROM vehicles v JOIN versions ve ON ve.id=v.version_id JOIN models m ON m.id=ve.model_id JOIN brands b ON b.id=m.brand_id JOIN agencies a ON a.id=v.agency_id WHERE CONCAT_WS(' ',v.stock_number,v.registration_number,v.vin,b.name,m.name) LIKE ?`},
 sale:simple('sales','sale_number','Vente'),invoice:simple('invoices','invoice_number','Facture'),repair_order:simple('repair_orders','order_number','OR'),delivery:simple('deliveries','delivery_number','Livraison'),
 supplier:{sql:`SELECT s.id,NULL agency_id,NULL concession_id,NULL agency_name,CONCAT(s.name,' — ',s.code) label,s.code business_id FROM suppliers s WHERE s.id=?`,search:`SELECT s.id,NULL agency_id,NULL concession_id,NULL agency_name,CONCAT(s.name,' — ',s.code) label,s.code business_id FROM suppliers s WHERE CONCAT_WS(' ',s.name,s.code,s.contact_name) LIKE ?`},
 expense:{sql:`SELECT e.id,b.agency_id,COALESCE(b.concession_id,a.concession_id) concession_id,a.name agency_name,CONCAT(e.label,' — ',COALESCE(e.reference,CONCAT('DEP-',LPAD(e.id,6,'0')))) label,COALESCE(e.reference,CONCAT('DEP-',LPAD(e.id,6,'0'))) business_id FROM budget_expenses e JOIN budgets b ON b.id=e.budget_id LEFT JOIN agencies a ON a.id=b.agency_id WHERE e.id=?`,search:`SELECT e.id,b.agency_id,COALESCE(b.concession_id,a.concession_id) concession_id,a.name agency_name,CONCAT(e.label,' — ',COALESCE(e.reference,CONCAT('DEP-',LPAD(e.id,6,'0')))) label,COALESCE(e.reference,CONCAT('DEP-',LPAD(e.id,6,'0'))) business_id FROM budget_expenses e JOIN budgets b ON b.id=e.budget_id LEFT JOIN agencies a ON a.id=b.agency_id WHERE CONCAT_WS(' ',e.label,e.reference,e.id) LIKE ?`},
 budget:{sql:`SELECT b.id,b.agency_id,COALESCE(b.concession_id,a.concession_id) concession_id,a.name agency_name,CONCAT(b.label,' — BUD-',LPAD(b.id,6,'0')) label,CONCAT('BUD-',LPAD(b.id,6,'0')) business_id FROM budgets b LEFT JOIN agencies a ON a.id=b.agency_id WHERE b.id=?`,search:`SELECT b.id,b.agency_id,COALESCE(b.concession_id,a.concession_id) concession_id,a.name agency_name,CONCAT(b.label,' — BUD-',LPAD(b.id,6,'0')) label,CONCAT('BUD-',LPAD(b.id,6,'0')) business_id FROM budgets b LEFT JOIN agencies a ON a.id=b.agency_id WHERE CONCAT_WS(' ',b.label,b.id) LIKE ?`},
 employee:{sql:`SELECT ep.id,u.agency_id,a.concession_id,a.name agency_name,CONCAT_WS(' · ',ep.employee_number,u.first_name,u.last_name) label,ep.employee_number business_id FROM employee_profiles ep JOIN users u ON u.id=ep.user_id JOIN agencies a ON a.id=u.agency_id WHERE ep.id=?`,search:`SELECT ep.id,u.agency_id,a.concession_id,a.name agency_name,CONCAT_WS(' · ',ep.employee_number,u.first_name,u.last_name) label,ep.employee_number business_id FROM employee_profiles ep JOIN users u ON u.id=ep.user_id JOIN agencies a ON a.id=u.agency_id WHERE CONCAT_WS(' ',ep.employee_number,u.first_name,u.last_name,u.email) LIKE ?`}};
export function entityType(v:unknown):DocumentEntityType{if(typeof v!=='string'||!ENTITY_TYPES.includes(v as DocumentEntityType))throw new HttpError(400,'Type d’entité invalide');return v as DocumentEntityType}
const has=(r:Request,p:string)=>Boolean(r.rbac?.isSuperAdmin||r.rbac?.permissions.has(p)),rank:Record<Scope,number>={OWN:0,AGENCY:1,CONCESSION:2,GLOBAL:3};export function assertEntityRole(r:Request,t:DocumentEntityType){if(!POLICIES[t].some(p=>has(r,p)))throw new HttpError(403,'Accès interdit à ce type de dossier')}export function allowedEntityTypes(r:Request){return ENTITY_TYPES.filter(t=>POLICIES[t].some(p=>has(r,p)))}
const permissionScope=(r:Request,p:string):Scope|undefined=>r.rbac?.isSuperAdmin?'GLOBAL':r.rbac?.permissions.get(p)as Scope|undefined,businessScope=(r:Request,t:DocumentEntityType)=>POLICIES[t].map(p=>permissionScope(r,p)).filter((x):x is Scope=>Boolean(x)).sort((a,b)=>rank[b]-rank[a])[0];
async function actorConcession(r:Request){const[x]=await query<RowDataPacket[]>('SELECT concession_id FROM agencies WHERE id=?',[r.user?.agencyId]);return x?String(x.concession_id):null}async function allows(r:Request,s:Scope|undefined,a:string|null,c:string|null,o?:string|null){if(!s)return false;if(s==='OWN')return o!=null&&o===String(r.user?.sub);if(s==='GLOBAL')return true;if(s==='AGENCY')return a!=null&&a===String(r.user?.agencyId);return c!=null&&c===await actorConcession(r)}
async function scoped(r:Request,row:RowDataPacket,p:GedPermission,owner?:string|null){const t=entityType(row.entity_type),a=row.agency_id==null?null:String(row.agency_id),c=row.concession_id==null?null:String(row.concession_id);if(!await allows(r,permissionScope(r,p),a,c,owner)||!await allows(r,businessScope(r,t),a,c))throw new HttpError(403,'Ressource documentaire hors périmètre')}
const mapped=(t:DocumentEntityType,x:RowDataPacket):Entity=>({entityType:t,entityId:String(x.id),agencyId:x.agency_id==null?null:String(x.agency_id),concessionId:x.concession_id==null?null:String(x.concession_id),agencyName:x.agency_name??null,label:x.label,businessId:x.business_id});
export async function resolveDocumentEntity(r:Request,t:DocumentEntityType,value:string,p:GedPermission='ged.view',owner?:string|null){if(!/^\d+$/.test(value))throw new HttpError(400,'Identifiant d’entité invalide');assertEntityRole(r,t);const[x]=await query<RowDataPacket[]>(configs[t].sql,[value]);if(!x)throw new HttpError(404,'Entité introuvable');x.entity_type=t;await scoped(r,x,p,owner??(p==='ged.upload'?r.user?.sub:null));return mapped(t,x)}
export async function searchEntities(r:Request,t:DocumentEntityType,q:string,p:GedPermission='ged.upload'){assertEntityRole(r,t);const rows=await query<RowDataPacket[]>(`SELECT * FROM (${configs[t].search}) e ORDER BY e.label LIMIT 50`,[`%${q}%`]),out=[];for(const x of rows){x.entity_type=t;try{await scoped(r,x,p,p==='ged.upload'?r.user?.sub:null);out.push(mapped(t,x))}catch(e){if(!(e instanceof HttpError)||e.status!==403)throw e}if(out.length===15)break}return out}
export async function standaloneContext(r:Request,p:GedPermission){const a=String(r.user?.agencyId??''),[x]=await query<RowDataPacket[]>('SELECT id,concession_id,name FROM agencies WHERE id=?',[a]);if(!x)throw new HttpError(400,'Agence utilisateur introuvable');if(!await allows(r,permissionScope(r,p),a,String(x.concession_id),r.user?.sub))throw new HttpError(403,'Périmètre GED insuffisant');return{agencyId:a,concessionId:String(x.concession_id),agencyName:x.name}}
function sqlScope(s:Scope|undefined,r:Request,params:unknown[],own:boolean){if(s==='GLOBAL')return'1=1';if(s==='CONCESSION'){params.push(r.user?.agencyId);return'd.concession_id=(SELECT concession_id FROM agencies WHERE id=?)'}if(s==='AGENCY'){params.push(r.user?.agencyId);return'd.agency_id=?'}if(s==='OWN'&&own){params.push(r.user?.sub);return'd.uploaded_by=?'}return'1=0'}
export function documentAccessPredicate(r:Request,p:GedPermission){const params:unknown[]=[],ged=permissionScope(r,p),parts:string[]=[];for(const t of ENTITY_TYPES){const business=businessScope(r,t);if(!business)continue;params.push(t);parts.push(`(d.entity_type=? AND ${sqlScope(ged,r,params,true)} AND ${sqlScope(business,r,params,false)})`)}parts.push(`(d.entity_type IS NULL AND d.entity_id IS NULL AND ${sqlScope(ged,r,params,true)})`);return{clause:`(${parts.join(' OR ')})`,params}}
export async function getAccessibleDocument(r:Request,value:string,p:GedPermission='ged.view',archived=false){if(!/^\d+$/.test(value))throw new HttpError(400,'Identifiant documentaire invalide');const[d]=await query<RowDataPacket[]>(`SELECT d.*,CONCAT_WS(' ',u.first_name,u.last_name) uploaded_by_name FROM documents d LEFT JOIN users u ON u.id=d.uploaded_by WHERE d.id=?`,[value]);if(!d)throw new HttpError(404,'Document introuvable');const owner=d.uploaded_by==null?null:String(d.uploaded_by),a=d.agency_id==null?null:String(d.agency_id),c=d.concession_id==null?null:String(d.concession_id);if(d.entity_type&&d.entity_id)await resolveDocumentEntity(r,entityType(d.entity_type),String(d.entity_id),p,owner);else if(!await allows(r,permissionScope(r,p),a,c,owner))throw new HttpError(403,'Ressource documentaire hors périmètre');if(d.is_archived&&!archived)throw new HttpError(404,'Document introuvable');if(d.is_archived&&p==='ged.view'&&!await allows(r,permissionScope(r,'ged.archive'),a,c,owner))throw new HttpError(403,'Accès aux archives interdit');return{doc:d,entity:d.entity_type&&d.entity_id?await resolveDocumentEntity(r,entityType(d.entity_type),String(d.entity_id),p,owner):null}}
