import type{NextFunction,Request,Response}from'express';
import{HttpError}from'../../shared/http-error.js';
import{MAX_DOCUMENT_SIZE,type UploadedDocument}from'./document-storage.js';

export type MultipartRequest=Request&{documentFile?:UploadedDocument};
const disposition=(value:string)=>Object.fromEntries([...value.matchAll(/(?:^|;)\s*([\w-]+)="([^"]*)"/g)].map(x=>[x[1],x[2]]));
export async function documentMultipart(request:MultipartRequest,_response:Response,next:NextFunction){try{const contentType=request.headers['content-type']??'',boundary=contentType.match(/boundary=(?:"([^"]+)"|([^;]+))/i)?.slice(1).find(Boolean);if(!contentType.startsWith('multipart/form-data')||!boundary)throw new HttpError(400,'Requête multipart/form-data obligatoire');const chunks:Buffer[]=[];let size=0;for await(const chunk of request){const value=Buffer.isBuffer(chunk)?chunk:Buffer.from(chunk);size+=value.length;if(size>MAX_DOCUMENT_SIZE+128*1024)throw new HttpError(413,'Fichier trop volumineux (15 Mo maximum)');chunks.push(value)}const body=Buffer.concat(chunks),marker=Buffer.from(`--${boundary}`),fields:Record<string,string>={};let cursor=body.indexOf(marker);while(cursor>=0){const start=cursor+marker.length;if(body.subarray(start,start+2).toString()==='--')break;const headersEnd=body.indexOf(Buffer.from('\r\n\r\n'),start);if(headersEnd<0)break;const nextBoundary=body.indexOf(marker,headersEnd+4);if(nextBoundary<0)break;const rawHeaders=body.subarray(start+2,headersEnd).toString('utf8'),content=body.subarray(headersEnd+4,nextBoundary-2),disp=rawHeaders.split('\r\n').find(x=>x.toLowerCase().startsWith('content-disposition:'));if(disp){const params=disposition(disp),name=params.name;if(name&&params.filename!=null){const mimeType=rawHeaders.match(/content-type:\s*([^\r\n]+)/i)?.[1]?.trim()??'application/octet-stream';request.documentFile={originalName:pathBase(params.filename),mimeType,buffer:content}}else if(name)fields[name]=content.toString('utf8')}cursor=nextBoundary}request.body=fields;next()}catch(error){next(error)}}
function pathBase(value:string){return value.replaceAll('\\','/').split('/').pop()?.slice(0,255)??''}

