import React,{useState}from'react';
import{useVehicleLocationActions,useVehicleLocationsQuery}from'../../api/erpHooks';
import{useSettingsAgenciesQuery}from'../../api/settingHooks';
import{useUiStore}from'../../stores/uiStore';
import{Button}from'../../components/ui/Button';
import{Badge}from'../../components/ui/Badge';
import{Card}from'../../components/ui/Card';

export function VehicleLocationsSettings({canManage}:{canManage:boolean}){
 const agencies=useSettingsAgenciesQuery(true),[agencyId,setAgencyId]=useState(''),[type,setType]=useState<''|'PARC'|'SHOWROOM'>(''),[name,setName]=useState(''),locations=useVehicleLocationsQuery({agencyId:agencyId||undefined,type:type||undefined}),actions=useVehicleLocationActions(),toast=useUiStore(s=>s.addToast);
 const notify=(title:string)=>toast({type:'success',title}),fail=(error:unknown)=>toast({type:'error',title:'Opération impossible',description:error instanceof Error?error.message:'Erreur API'});
 const create=async(e:React.FormEvent)=>{e.preventDefault();const target=agencyId||agencies.data?.[0]?.id;if(!target)return;try{await actions.create.mutateAsync({agencyId:target,name:name.trim(),type:type||'PARC'});setName('');notify('Affectation véhicule créée')}catch(error){fail(error)}};
 return <div className="space-y-4">{canManage&&<Card><form onSubmit={create} className="grid gap-3 md:grid-cols-4"><label className="text-xs font-semibold">Agence<select required value={agencyId} onChange={e=>setAgencyId(e.target.value)} className="mt-1 w-full rounded border p-2"><option value="">Sélectionner</option>{agencies.data?.filter(a=>a.isActive).map(a=><option key={a.id} value={a.id}>{a.name}</option>)}</select></label><label className="text-xs font-semibold">Type<select value={type||'PARC'} onChange={e=>setType(e.target.value as 'PARC'|'SHOWROOM')} className="mt-1 w-full rounded border p-2"><option value="PARC">Parc automobile</option><option value="SHOWROOM">Showroom</option></select></label><label className="text-xs font-semibold">Nom<input required maxLength={120} value={name} onChange={e=>setName(e.target.value)} className="mt-1 w-full rounded border p-2" placeholder="Parc dépôt Nord"/></label><div className="flex items-end"><Button type="submit" loading={actions.create.isPending}>Créer</Button></div></form></Card>}<div className="flex gap-2"><select value={agencyId} onChange={e=>setAgencyId(e.target.value)} className="rounded border p-2 text-xs"><option value="">Toutes les agences accessibles</option>{agencies.data?.map(a=><option key={a.id} value={a.id}>{a.name}</option>)}</select><select value={type} onChange={e=>setType(e.target.value as typeof type)} className="rounded border p-2 text-xs"><option value="">Parc et Showroom</option><option value="PARC">Parc</option><option value="SHOWROOM">Showroom</option></select></div><div className="grid gap-3 md:grid-cols-2">{locations.data?.map(location=><Card key={location.id}><div className="flex items-start justify-between"><div><b>{location.name}</b><p className="text-xs text-slate-500">{location.agencyName} · {location.type==='PARC'?'Parc automobile':'Showroom'}</p></div><Badge variant={location.isActive?'success':'default'}>{location.isActive?'Active':'Inactive'}</Badge></div>{canManage&&<div className="mt-3 flex gap-2 border-t pt-3"><Button size="xs" variant="outline" onClick={()=>{const next=window.prompt('Nouveau nom',location.name)?.trim();if(next&&next!==location.name)void actions.update.mutateAsync({id:location.id,name:next}).then(()=>notify('Affectation renommée')).catch(fail)}}>Renommer</Button><Button size="xs" variant={location.isActive?'danger':'success'} onClick={()=>void actions.update.mutateAsync({id:location.id,isActive:!location.isActive}).then(()=>notify(location.isActive?'Affectation désactivée':'Affectation réactivée')).catch(fail)}>{location.isActive?'Désactiver':'Réactiver'}</Button></div>}</Card>)}{!locations.isLoading&&!locations.data?.length&&<p className="text-sm text-slate-500">Aucune affectation véhicule.</p>}</div></div>
}
