import type{ReactNode}from'react';
import{useActivityConsolidatedQuery,useBudgetConsolidatedQuery,useCommercialConsolidatedQuery,useHrConsolidatedQuery,useReturnConsolidatedQuery,useTreasuryConsolidatedQuery}from'../../api/reportHooks';
import{Card,CardDescription,CardHeader,CardTitle}from'../../components/ui/Card';
import{useAuthStore}from'../../stores/authStore';
import type{ReportFilters}from'../../types/reports';
const money=(v?:number)=>v==null?'—':`${new Intl.NumberFormat('fr-FR',{maximumFractionDigits:0}).format(v).replace(/[\u00a0\u202f]/g,'.')} XAF`,pct=(v?:number)=>v==null?'—':`${v.toLocaleString('fr-FR',{maximumFractionDigits:1})} %`;
const Item=({label,value}:{label:string;value:ReactNode})=><div className="rounded bg-slate-50 p-2"><p className="text-[11px] text-slate-500">{label}</p><p className="font-bold">{value??'—'}</p></div>;
const Failure=({error}:{error:unknown})=>error?<p className="mt-3 rounded bg-red-50 p-3 text-sm text-red-700">{error instanceof Error?error.message:'Section indisponible'}</p>:null;
const allowed=(can:(code:string)=>boolean,codes:string[])=>can('reporting.view')&&codes.every(can);
export function ConsolidatedReportSections({filters}:{filters:ReportFilters}){const auth=useAuthStore(),commercialOk=allowed(auth.can,['crm.prospect.view','showroom.view','sales.view']),treasuryOk=allowed(auth.can,['treasury.view']),budgetOk=allowed(auth.can,['hr.budget.view','hr.expense.view']),hrOk=allowed(auth.can,['hr.reporting.view','hr.employees.view','hr.salary.view','hr.contract.view','hr.leave.view','hr.bonus.view']),activityOk=allowed(auth.can,['activity.view']),returnsOk=allowed(auth.can,['vehicle.return.view']),commercial=useCommercialConsolidatedQuery(filters,commercialOk),treasury=useTreasuryConsolidatedQuery(filters,treasuryOk),budgets=useBudgetConsolidatedQuery(filters,budgetOk),hr=useHrConsolidatedQuery(filters,hrOk),activity=useActivityConsolidatedQuery(filters,activityOk),returns=useReturnConsolidatedQuery(filters,returnsOk);return <div className="space-y-6"><p className="text-xs text-slate-500">Indicateurs consolidés sur tout le périmètre autorisé par vos permissions.</p>
{commercialOk&&<Card><CardHeader><CardTitle>Commercial consolidé</CardTitle><CardDescription>Cohorte de prospects créés sur la période, essais et ventes issus de leurs sources métier.</CardDescription></CardHeader><div className="grid gap-3 sm:grid-cols-3 lg:grid-cols-6"><Item label="Prospects créés" value={commercial.data?.prospects_created}/><Item label="Convertis (statut courant)" value={commercial.data?.prospects_currently_converted}/><Item label="Conversion de cohorte" value={pct(commercial.data?.conversionRate)}/><Item label="Essais" value={commercial.data?.trials}/><Item label="Ventes enregistrées" value={commercial.data?.sales}/><Item label="Ventes non annulées" value={money(commercial.data?.confirmed_sales_amount)}/></div><Failure error={commercial.error}/></Card>}
{returnsOk&&<Card><CardHeader><CardTitle>Retours post-livraison</CardTitle><CardDescription>Ventes historiques, retours, avoirs, remboursements et retour stock restent distincts.</CardDescription></CardHeader><div className="grid gap-3 sm:grid-cols-3 lg:grid-cols-5"><Item label="Retours demandés" value={returns.data?.returns}/><Item label="Retours clôturés" value={returns.data?.closed_returns}/><Item label="Avoirs liés" value={money(returns.data?.credited_amount)}/><Item label="Remboursements liés" value={money(returns.data?.refunded_amount)}/><Item label="Retours au stock VO" value={returns.data?.returned_to_stock}/></div><Failure error={returns.error}/></Card>}
{(treasuryOk||budgetOk)&&<div className="grid gap-6 lg:grid-cols-2">{treasuryOk&&<Card><CardHeader><CardTitle>Trésorerie</CardTitle><CardDescription>Les transferts internes sont exclus des flux économiques.</CardDescription></CardHeader><div className="grid gap-3 sm:grid-cols-2"><Item label="Entrées économiques" value={money(treasury.data?.economic_entries)}/><Item label="Sorties économiques" value={money(treasury.data?.economic_exits)}/><Item label="Variation de trésorerie" value={money(treasury.data?.period_balance)}/><Item label="Transferts internes (débits)" value={money(treasury.data?.transfers)}/></div><Failure error={treasury.error}/></Card>}{budgetOk&&<Card><CardHeader><CardTitle>Budgets et décaissements</CardTitle><CardDescription>Allocation, consommation budgétaire et décaissement réel sont séparés.</CardDescription></CardHeader><div className="grid gap-3 sm:grid-cols-2"><Item label="Alloué" value={money(budgets.data?.allocated)}/><Item label="Consommé sur période" value={money(budgets.data?.consumed)}/><Item label="Solde budgétaire" value={money(budgets.data?.remaining)}/><Item label="Réellement décaissé" value={money(budgets.data?.disbursed)}/></div><Failure error={budgets.error}/></Card>}</div>}
{hrOk&&<Card><CardHeader><CardTitle>Ressources humaines</CardTitle><CardDescription>Source employés ; salaire courant au terme de période ; primes approuvées, non assimilées à un paiement.</CardDescription></CardHeader><div className="grid gap-3 sm:grid-cols-3 lg:grid-cols-6"><Item label="Effectif actif" value={hr.data?.active_employees}/><Item label="Avec / sans compte ERP" value={`${hr.data?.with_erp_account??0} / ${hr.data?.without_erp_account??0}`}/><Item label="Masse salariale courante" value={money(hr.data?.current_salary_mass)}/><Item label="Contrats applicables" value={hr.data?.current_contracts}/><Item label="Congés approuvés chevauchants" value={hr.data?.approved_leaves_in_period}/><Item label="Primes approuvées" value={`${hr.data?.approved_bonuses??0} · ${money(hr.data?.approved_bonus_amount)}`}/></div><Failure error={hr.error}/></Card>}
{activityOk&&<Card><CardHeader><CardTitle>Activité ERP</CardTitle><CardDescription>Volumes d’événements audités, sans classement ni score individuel.</CardDescription></CardHeader><div className="grid gap-3 sm:grid-cols-3"><Item label="Événements" value={activity.data?.events}/><Item label="Utilisateurs actifs" value={activity.data?.active_users}/><Item label="Modules actifs" value={activity.data?.active_modules}/></div><div className="mt-3 flex flex-wrap gap-2">{activity.data?.byModule.map(x=><span key={x.module} className="rounded-full bg-slate-100 px-3 py-1 text-xs">{x.module} · {x.events}</span>)}</div><Failure error={activity.error}/></Card>}
</div>}
