import { BadRequestException,ConflictException,Injectable,NotFoundException } from '@nestjs/common';
import { PoolConnection,ResultSetHeader,RowDataPacket } from 'mysql2/promise';
import { DatabaseService } from '../../database/database.service';
import { RealtimeGateway } from '../../realtime/realtime.gateway';
import { CreatePartDto,PartMovementDto } from './parts.dto';
@Injectable() export class PartsService{
constructor(private readonly db:DatabaseService,private readonly rt:RealtimeGateway){}
async list(agencyId:string){if(!agencyId)throw new BadRequestException('Agence requise');return this.db.query<RowDataPacket[]>(`SELECT p.*,pc.name category_name,s.name supplier_name,COALESCE(SUM(ps.current_stock),0) current_stock,COALESCE(SUM(ps.reserved_stock),0) reserved_stock,COALESCE(SUM(ps.current_stock-ps.reserved_stock),0) available_stock,COALESCE(SUM(ps.min_stock),0) min_stock,COALESCE(SUM(ps.max_stock),0) max_stock,(COALESCE(SUM(ps.current_stock-ps.reserved_stock),0)<=COALESCE(SUM(ps.min_stock),0)) low_stock FROM parts p LEFT JOIN part_categories pc ON pc.id=p.category_id LEFT JOIN suppliers s ON s.id=p.supplier_id LEFT JOIN part_stocks ps ON ps.part_id=p.id AND ps.agency_id=? WHERE p.is_active=TRUE GROUP BY p.id ORDER BY p.name`,[agencyId])}
async detail(id:string,agencyId:string){if(!agencyId)throw new BadRequestException('Agence requise');const rows=await this.db.query<RowDataPacket[]>('SELECT p.*,COALESCE(SUM(ps.current_stock),0) current_stock,COALESCE(SUM(ps.reserved_stock),0) reserved_stock,COALESCE(SUM(ps.current_stock-ps.reserved_stock),0) available_stock FROM parts p LEFT JOIN part_stocks ps ON ps.part_id=p.id AND ps.agency_id=? WHERE p.id=? AND p.is_active=TRUE GROUP BY p.id',[agencyId,id]);if(!rows[0])throw new NotFoundException('Pièce introuvable');const stocks=await this.db.query<RowDataPacket[]>('SELECT ps.*,l.name location_name,(ps.current_stock-ps.reserved_stock) available_stock FROM part_stocks ps LEFT JOIN locations l ON l.id=ps.location_id WHERE ps.part_id=? AND ps.agency_id=?',[id,agencyId]);return{...rows[0],stocks}}
private async lock(c:PoolConnection,partId:string,agencyId:string,locationId?:string,create=false){if(locationId){const[locations]=await c.execute<RowDataPacket[]>('SELECT id FROM locations WHERE id=? AND agency_id=? AND is_active=TRUE',[locationId,agencyId]);if(!locations[0])throw new BadRequestException("Emplacement étranger à l'agence");let[rows]=await c.execute<RowDataPacket[]>('SELECT * FROM part_stocks WHERE part_id=? AND agency_id=? AND location_id=? FOR UPDATE',[partId,agencyId,locationId]);if(!rows[0]&&create){await c.execute('INSERT INTO part_stocks(part_id,agency_id,location_id)VALUES(?,?,?)',[partId,agencyId,locationId]);[rows]=await c.execute<RowDataPacket[]>('SELECT * FROM part_stocks WHERE part_id=? AND agency_id=? AND location_id=? FOR UPDATE',[partId,agencyId,locationId]);}if(!rows[0])throw new NotFoundException('Stock introuvable');return rows[0]}let[rows]=await c.execute<RowDataPacket[]>('SELECT * FROM part_stocks WHERE part_id=? AND agency_id=? FOR UPDATE',[partId,agencyId]);if(rows.length>1)throw new BadRequestException('Emplacement requis');if(!rows[0]&&create){await c.execute('INSERT INTO part_stocks(part_id,agency_id,location_id)VALUES(?,?,NULL)',[partId,agencyId]);[rows]=await c.execute<RowDataPacket[]>('SELECT * FROM part_stocks WHERE part_id=? AND agency_id=? AND location_id IS NULL FOR UPDATE',[partId,agencyId]);}if(!rows[0])throw new NotFoundException('Stock agence introuvable');return rows[0]}
async create(d:CreatePartDto,userId:string){return this.db.transaction(async c=>{const[result]=await c.execute<ResultSetHeader>('INSERT INTO parts(category_id,supplier_id,reference,name,brand,description,purchase_price,sale_price)VALUES(?,?,?,?,?,?,?,?)',[d.categoryId??null,d.supplierId??null,d.reference.trim(),d.name.trim(),d.brand??null,d.description??null,d.purchasePrice,d.salePrice]);if((d.currentStock??0)>0){if(!d.agencyId)throw new BadRequestException('Agence requise pour le stock initial');const stock=await this.lock(c,String(result.insertId),d.agencyId,d.locationId,true);await c.execute('UPDATE part_stocks SET current_stock=?,min_stock=?,max_stock=? WHERE id=?',[d.currentStock,d.minStock??0,d.maxStock??0,stock.id]);await c.execute("INSERT INTO part_movements(part_id,agency_id,location_id,movement_type,quantity,reference_type,reference_id,reason,performed_by)VALUES(?,?,?,'inventory',?,'part',?,'Stock initial',?)",[result.insertId,d.agencyId,stock.location_id,d.currentStock,result.insertId,userId]);}return{id:String(result.insertId)}})}
async movements(partId:string,agencyId:string){if(!agencyId)throw new BadRequestException('Agence requise');return this.db.query<RowDataPacket[]>('SELECT pm.*,l.name location_name FROM part_movements pm LEFT JOIN locations l ON l.id=pm.location_id WHERE pm.part_id=? AND pm.agency_id=? ORDER BY pm.moved_at DESC',[partId,agencyId])}
async move(partId:string,d:PartMovementDto,userId:string){if(!d.quantity)throw new BadRequestException('Quantité non nulle requise');if(['reservation','release','repair_order'].includes(d.movementType))throw new BadRequestException('Utilisez le workflow OR');const incoming=['purchase','transfer_in','return'].includes(d.movementType),outgoing=['sale','transfer_out'].includes(d.movementType),signed=incoming?Math.abs(d.quantity):outgoing?-Math.abs(d.quantity):d.quantity;const stock=await this.db.transaction(async c=>{const row=await this.lock(c,partId,d.agencyId,d.locationId,incoming);const next=Number(row.current_stock)+signed;if(next<Number(row.reserved_stock))throw new ConflictException('Stock disponible insuffisant');await c.execute('UPDATE part_stocks SET current_stock=? WHERE id=?',[next,row.id]);await c.execute('INSERT INTO part_movements(part_id,agency_id,location_id,movement_type,quantity,unit_cost,reference_type,reference_id,reason,performed_by)VALUES(?,?,?,?,?,?,?,?,?,?)',[partId,d.agencyId,row.location_id,d.movementType,signed,d.unitCost??null,d.referenceType??null,d.referenceId??null,d.reason??null,userId]);return{locationId:row.location_id,currentStock:next,reservedStock:Number(row.reserved_stock),availableStock:next-Number(row.reserved_stock),lowStock:next-Number(row.reserved_stock)<=Number(row.min_stock)};});this.rt.emitAgency(d.agencyId,'parts:stock-changed',{partId,agencyId:d.agencyId,...stock,movementType:d.movementType,quantity:signed});return stock}}
