import React,{useEffect,useState}from'react';
import{Plus,Save}from'lucide-react';
import{useSettingsAgenciesQuery,useWorkshopLaborRateActions,useWorkshopLaborRatesQuery,type WorkshopLaborRate}from'../../api/settingHooks';
import{useAuthStore}from'../../stores/authStore';
import{useUiStore}from'../../stores/uiStore';
import{Badge}from'../../components/ui/Badge';
import{Button}from'../../components/ui/Button';

const field='w-full rounded-md border border-slate-300 bg-white px-3 py-2 text-sm';
const empty={code:'',label:'',hourlyRate:0,displayOrder:0};

export const WorkshopLaborRatesSettings:React.FC<{currencyCode:string}>=({currencyCode})=>{
 const can=useAuthStore(s=>s.can),permissionScope=useAuthStore(s=>s.permissionScope('settings.update')),currentAgency=useAuthStore(s=>s.currentAgency),canUpdate=can('settings.update')&&permissionScope!=='OWN',canEditConcession=canUpdate&&(permissionScope==='CONCESSION'||permissionScope==='GLOBAL'),agencies=useSettingsAgenciesQuery(can('settings.view'));
 const[agencyId,setAgencyId]=useState(currentAgency?.id??''),[draft,setDraft]=useState(empty),[editing,setEditing]=useState<WorkshopLaborRate|null>(null),[overrideDraft,setOverrideDraft]=useState<Record<string,string>>({});
 const query=useWorkshopLaborRatesQuery(agencyId,can('settings.view')),actions=useWorkshopLaborRateActions(),toast=useUiStore(s=>s.addToast);
 useEffect(()=>{if(!agencyId&&currentAgency?.id)setAgencyId(currentAgency.id)},[agencyId,currentAgency?.id]);
 const success=(title:string)=>toast({type:'success',title}),fail=(error:unknown)=>toast({type:'error',title:'Opération impossible',description:error instanceof Error?error.message:'Erreur API'});
 const run=async(work:()=>Promise<unknown>,title:string)=>{try{await work();success(title)}catch(error){fail(error)}};
 const create=async(e:React.FormEvent)=>{e.preventDefault();await run(()=>actions.create.mutateAsync({...draft,hourlyRate:Number(draft.hourlyRate),displayOrder:Number(draft.displayOrder)}),'Barème créé');setDraft(empty)};
 const save=async(e:React.FormEvent)=>{e.preventDefault();if(!editing)return;await run(()=>actions.update.mutateAsync({id:editing.id,code:editing.code,label:editing.label,hourlyRate:Number(editing.concessionHourlyRate),displayOrder:Number(editing.displayOrder)}),'Barème modifié');setEditing(null)};
 const override=async(rate:WorkshopLaborRate)=>run(()=>actions.override.mutateAsync({id:rate.id,agencyId,hourlyRate:Number(overrideDraft[rate.id]??rate.agencyOverride?.hourlyRate??rate.concessionHourlyRate),isActive:rate.agencyOverride?.isActive??true}),'Surcharge agence enregistrée');
 const mayChooseAgency=permissionScope==='CONCESSION'||permissionScope==='GLOBAL';
 return <div className="space-y-4">
  <div className="flex flex-wrap items-end gap-3 rounded-md bg-slate-50 p-3"><label className="min-w-64 text-xs font-semibold text-slate-700">Agence de simulation / surcharge<select className={`${field} mt-1`} value={agencyId} disabled={!mayChooseAgency} onChange={e=>setAgencyId(e.target.value)}>{agencies.data?.map(agency=><option key={agency.id} value={agency.id}>{agency.name}</option>)}</select></label><p className="pb-2 text-xs text-slate-500">La valeur effective est celle proposée aux nouveaux chiffrages de cette agence.</p></div>
  {query.isError&&<p className="rounded border border-red-200 p-3 text-sm text-red-700">{query.error instanceof Error?query.error.message:'Chargement impossible'}</p>}
  <div className="overflow-x-auto"><table className="w-full min-w-[850px] text-left text-sm"><thead><tr className="border-b text-xs text-slate-500"><th className="py-2">Code / libellé</th><th>Concession</th><th>Agence</th><th>Effectif</th><th>État</th><th className="text-right">Actions</th></tr></thead><tbody>{query.data?.rates.map(rate=><tr key={rate.id} className="border-b"><td className="py-3"><b>{rate.code}</b> · {rate.label}</td><td>{rate.concessionHourlyRate.toLocaleString('fr-FR')} {currencyCode}/h</td><td>{rate.agencyOverride?<><span>{rate.agencyOverride.hourlyRate.toLocaleString('fr-FR')} {currencyCode}/h</span><br/><span className="text-xs text-slate-500">{rate.agencyOverride.isActive?'Surcharge active':'Désactivé pour cette agence'}</span></>:<span className="text-slate-500">Hérité</span>}</td><td><b>{rate.effectiveHourlyRate.toLocaleString('fr-FR')} {currencyCode}/h</b><br/><span className="text-xs text-slate-500">source {rate.source==='agency'?'agence':'concession'}</span></td><td><Badge variant={rate.effectiveIsActive?'success':'default'}>{rate.effectiveIsActive?'Actif':'Inactif'}</Badge></td><td><div className="flex justify-end gap-2">{canEditConcession&&<><Button size="xs" variant="outline" onClick={()=>setEditing(rate)}>Modifier</Button><Button size="xs" variant={rate.isActive?'danger':'success'} loading={actions.update.isPending} onClick={()=>void run(()=>actions.update.mutateAsync({id:rate.id,isActive:!rate.isActive}),rate.isActive?'Barème désactivé':'Barème réactivé')}>{rate.isActive?'Désactiver':'Réactiver'}</Button></>}{canUpdate&&<><input aria-label={`Tarif agence ${rate.code}`} className="w-28 rounded border px-2 text-xs" type="number" min="0" step="0.01" value={overrideDraft[rate.id]??String(rate.agencyOverride?.hourlyRate??rate.concessionHourlyRate)} onChange={e=>setOverrideDraft(current=>({...current,[rate.id]:e.target.value}))}/><Button size="xs" variant="outline" onClick={()=>void override(rate)} loading={actions.override.isPending}>Surcharger</Button>{rate.agencyOverride&&<Button size="xs" variant="outline" onClick={()=>void run(()=>actions.clearOverride.mutateAsync({id:rate.id,agencyId}),'Héritage concession restauré')} loading={actions.clearOverride.isPending}>Hériter</Button>}</>}</div></td></tr>)}</tbody></table></div>
  {!query.isLoading&&!query.data?.rates.length&&<p className="text-sm text-slate-500">Aucun barème configuré.</p>}
  {canEditConcession&&<form onSubmit={create} className="grid gap-3 rounded-md border p-4 md:grid-cols-5"><input required className={field} placeholder="Code (ex. T5)" value={draft.code} onChange={e=>setDraft({...draft,code:e.target.value})}/><input required className={`${field} md:col-span-2`} placeholder="Libellé" value={draft.label} onChange={e=>setDraft({...draft,label:e.target.value})}/><input required className={field} type="number" min="0" step="0.01" placeholder="Tarif HT/h" value={draft.hourlyRate} onChange={e=>setDraft({...draft,hourlyRate:Number(e.target.value)})}/><Button type="submit" icon={<Plus className="h-4 w-4"/>} loading={actions.create.isPending}>Ajouter</Button></form>}
  {editing&&<form onSubmit={save} className="grid gap-3 rounded-md border border-amber-200 bg-amber-50 p-4 md:grid-cols-5"><input required className={field} value={editing.code} onChange={e=>setEditing({...editing,code:e.target.value})}/><input required className={`${field} md:col-span-2`} value={editing.label} onChange={e=>setEditing({...editing,label:e.target.value})}/><input required className={field} type="number" min="0" step="0.01" value={editing.concessionHourlyRate} onChange={e=>setEditing({...editing,concessionHourlyRate:Number(e.target.value)})}/><div className="flex gap-2"><Button type="submit" icon={<Save className="h-4 w-4"/>} loading={actions.update.isPending}>Enregistrer</Button><Button type="button" variant="outline" onClick={()=>setEditing(null)}>Annuler</Button></div></form>}
  <p className="text-xs text-slate-500">Une surcharge agence inactive désactive explicitement le barème pour cette agence. « Hériter » retire la configuration effective de l’agence et restaure la valeur concession, sans effacer l’historique.</p>
 </div>;
};
