import React,{useState}from'react';
import{ArrowDownLeft,ArrowRightLeft,ArrowUpRight,Landmark,Plus}from'lucide-react';
import{PageHeader}from'../../components/common/PageHeader';
import{Button}from'../../components/ui/Button';
import{Card}from'../../components/ui/Card';
import{Modal}from'../../components/ui/Modal';
import{useAuthStore}from'../../stores/authStore';
import{useTreasuryAccounts,useTreasuryActions,useTreasuryCategories,useTreasuryFlowConfiguration,useTreasuryJournal,useTreasuryManualOptions,useTreasurySummary}from'../../api/treasuryHooks';
import{formatCurrency,formatDate}from'../../lib/utils';
import{TreasuryManualDocuments}from'./TreasuryManualDocuments';
type Tab='overview'|'accounts'|'journal'|'categories'|'flows';type Direction='IN'|'OUT';
const input='rounded-md border border-slate-300 px-3 py-2 text-xs';
const sourceLabel=(s:string)=>({PAYMENT:'Paiement client',PAYMENT_REFUND:'Remboursement client',WARRANTY_CLAIM_PAYMENT:'Règlement garantie constructeur',MANUAL_RECEIPT:'Entrée manuelle',MANUAL_DISBURSEMENT:'Sortie manuelle',BUDGET_EXPENSE_DISBURSEMENT:'Décaissement budgétaire'}[s]??s);
const initial=(today:string)=>({accountId:'',amount:'',categoryId:'',description:'',valueDate:today,paymentMethodId:'',reference:'',counterparty:'',handedTo:'',clientRequestId:crypto.randomUUID()});
export const TreasuryPage:React.FC=()=>{
 const can=useAuthStore(s=>s.can),permissionScope=useAuthStore(s=>s.permissionScope),today=new Date().toISOString().slice(0,10);
 const[tab,setTab]=useState<Tab>('overview'),[page,setPage]=useState(1),[filters,setFilters]=useState({accountId:'',direction:'',categoryId:'',from:'',to:''}),[manual,setManual]=useState<Direction|null>(null),[documents,setDocuments]=useState<{id:string;direction:Direction}|null>(null),[form,setForm]=useState(initial(today)),[flowForm,setFlowForm]=useState({agencyId:'',paymentMethodId:'',treasuryAccountId:''});
 const accounts=useTreasuryAccounts(),categories=useTreasuryCategories(),summary=useTreasurySummary(),journal=useTreasuryJournal({page,pageSize:20,...filters}),actions=useTreasuryActions();
 const canAccounts=can('treasury.account.manage'),canCategories=can('treasury.category.manage'),canTransfer=can('treasury.transfer.create'),canReverse=can('treasury.reverse'),canReceipt=can('treasury.receipt.create'),canDisbursement=can('treasury.disbursement.create'),options=useTreasuryManualOptions(Boolean(manual)),flows=useTreasuryFlowConfiguration(canAccounts),manageScope=permissionScope('treasury.account.manage'),canActivateFlows=manageScope==='CONCESSION'||manageScope==='GLOBAL';
 const run=(p:Promise<unknown>)=>void p.catch(e=>window.alert(e instanceof Error?e.message:'Opération impossible'));
 const openManual=(d:Direction)=>{setForm(initial(today));setManual(d)};
 const submitManual=async(e:React.FormEvent)=>{e.preventDefault();if(manual==='OUT'&&!window.confirm(`Confirmer le décaissement de ${form.amount} depuis le compte sélectionné ?`))return;const direction=manual!,mutation=direction==='IN'?actions.manualReceipt:actions.manualDisbursement;try{const result=await mutation.mutateAsync(form)as{id:string};setManual(null);setTab('journal');setDocuments({id:result.id,direction})}catch(error){window.alert(error instanceof Error?error.message:'Opération impossible')}};
 const createAccount=()=>{const code=window.prompt('Code du compte'),name=code&&window.prompt('Nom du compte'),accountType=name&&window.prompt('Type : CASH, BANK ou OTHER','BANK');if(code&&name&&accountType)run(actions.createAccount.mutateAsync({code,name,accountType:accountType.toUpperCase(),currencyCode:'XAF'}))};
 const createCategory=()=>{const code=window.prompt('Code de catégorie'),name=code&&window.prompt('Nom de catégorie'),allowedDirection=name&&window.prompt('Sens : IN, OUT ou BOTH','BOTH');if(code&&name&&allowedDirection)run(actions.createCategory.mutateAsync({code,name,allowedDirection:allowedDirection.toUpperCase()}))};
 const transfer=()=>{const sourceAccountId=window.prompt('Compte source'),destinationAccountId=sourceAccountId&&window.prompt('Compte destination'),amount=destinationAccountId&&window.prompt('Montant'),description=amount&&window.prompt('Motif');if(sourceAccountId&&destinationAccountId&&amount&&description)run(actions.transfer.mutateAsync({sourceAccountId,destinationAccountId,amount,valueDate:today,description}))};
 return <div className="space-y-5"><PageHeader title="Comptabilité & Trésorerie" subtitle="Comptes, soldes dérivés et journal financier central." actions={<div className="flex gap-2">{canReceipt&&<Button size="xs" variant="success" onClick={()=>openManual('IN')} icon={<ArrowDownLeft className="h-3 w-3"/>}>Nouvelle entrée</Button>}{canDisbursement&&<Button size="xs" variant="danger" onClick={()=>openManual('OUT')} icon={<ArrowUpRight className="h-3 w-3"/>}>Nouvelle sortie</Button>}</div>}/>
 <div className="flex gap-2 border-b">{(['overview','accounts','journal','categories','flows']as Tab[]).filter(x=>x!=='categories'||canCategories).filter(x=>x!=='flows'||canAccounts).map(x=><button key={x} onClick={()=>setTab(x)} className={`px-3 py-2 text-xs font-bold ${tab===x?'border-b-2 border-[#8f1722] text-[#8f1722]':'text-slate-500'}`}>{({overview:'Vue d’ensemble',accounts:'Comptes',journal:'Journal',categories:'Catégories',flows:'Configuration des flux'})[x]}</button>)}</div>
 {tab==='overview'&&<><div className="grid gap-4 md:grid-cols-3"><Card><p className="text-xs text-slate-500">Solde dérivé</p><p className="text-2xl font-bold">{formatCurrency(summary.data?.balance??0)}</p></Card><Card><p className="text-xs text-slate-500">Entrées comptabilisées</p><p className="text-xl font-bold text-emerald-700">{formatCurrency(summary.data?.totalIn??0)}</p></Card><Card><p className="text-xs text-slate-500">Sorties comptabilisées</p><p className="text-xl font-bold text-red-700">{formatCurrency(summary.data?.totalOut??0)}</p></Card></div><Card><h2 className="mb-3 font-bold">Comptes accessibles</h2>{accounts.data?.map(a=><div key={a.id} className="flex justify-between border-t py-3 text-xs"><span><b>{a.name}</b> · {a.agency_name??'Compte central'} · {a.is_active?'Actif':'Inactif'}</span><b>{formatCurrency(Number(a.balance),a.currency_code)}</b></div>)}</Card></>}
 {tab==='accounts'&&<Card><div className="mb-3 flex justify-between"><h2 className="font-bold">Comptes de trésorerie</h2><div className="flex gap-2">{canTransfer&&<Button size="xs" variant="outline" onClick={transfer} icon={<ArrowRightLeft className="h-3 w-3"/>}>Transférer</Button>}{canAccounts&&<Button size="xs" onClick={createAccount} icon={<Plus className="h-3 w-3"/>}>Configurer</Button>}</div></div>{accounts.data?.map(a=><div key={a.id} className="flex items-center justify-between border-t py-2 text-xs"><span><b>{a.code}</b> — {a.name} · {a.account_type} · {a.agency_name??a.concession_name}</span><span>{formatCurrency(Number(a.balance),a.currency_code)} {canAccounts&&<Button size="xs" variant="outline" onClick={()=>run(actions.accountStatus.mutateAsync({id:a.id,isActive:!a.is_active}))}>{a.is_active?'Désactiver':'Activer'}</Button>}</span></div>)}</Card>}
 {tab==='journal'&&<Card><div className="mb-4 grid gap-2 md:grid-cols-5"><select className={input} value={filters.accountId} onChange={e=>{setPage(1);setFilters({...filters,accountId:e.target.value})}}><option value="">Tous comptes</option>{accounts.data?.map(a=><option key={a.id} value={a.id}>{a.name}</option>)}</select><select className={input} value={filters.direction} onChange={e=>setFilters({...filters,direction:e.target.value})}><option value="">Tous sens</option><option value="IN">Entrées</option><option value="OUT">Sorties</option></select><select className={input} value={filters.categoryId} onChange={e=>setFilters({...filters,categoryId:e.target.value})}><option value="">Toutes catégories</option>{categories.data?.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select><input aria-label="Du" type="date" className={input} value={filters.from} onChange={e=>setFilters({...filters,from:e.target.value})}/><input aria-label="Au" type="date" className={input} value={filters.to} onChange={e=>setFilters({...filters,to:e.target.value})}/></div>{journal.data?.items.map(m=><div key={m.id} className="grid grid-cols-7 items-center border-t py-2 text-xs"><span>{formatDate(m.value_date)}</span><span>{m.account_name}</span><span>{m.direction}</span><b>{formatCurrency(Number(m.amount),m.currency_code)}</b><span>{m.category_name??'—'}</span><span>{sourceLabel(m.source_type)} #{m.source_id}{m.budget_expense_id?` · dépense #${m.budget_expense_id}`:''}{m.reference?` · ${m.reference}`:''}{(m.source_type==='MANUAL_RECEIPT'||m.source_type==='MANUAL_DISBURSEMENT')&&<Button size="xs" variant="outline" className="ml-2" onClick={()=>setDocuments({id:m.source_id,direction:m.direction})}>Justificatifs</Button>}</span>{m.is_reversed?<span className="font-bold text-slate-500">Contrepassée</span>:canReverse?<Button size="xs" variant="outline" onClick={()=>{const reason=window.prompt('Motif de contrepassation');if(reason)run(actions.reverse.mutateAsync({id:m.id,reason,valueDate:today}))}}>Contrepasser</Button>:<span/>}</div>)}<div className="mt-3 flex justify-between text-xs"><span>{journal.data?.total??0} mouvements</span><div><Button size="xs" variant="outline" disabled={page<=1} onClick={()=>setPage(x=>x-1)}>Précédent</Button><span className="px-2">{page}/{Math.max(1,journal.data?.totalPages??1)}</span><Button size="xs" variant="outline" disabled={page>=(journal.data?.totalPages??1)} onClick={()=>setPage(x=>x+1)}>Suivant</Button></div></div></Card>}
 {tab==='categories'&&<Card><div className="mb-3 flex justify-between"><h2 className="font-bold">Catégories</h2><Button size="xs" onClick={createCategory}>Ajouter</Button></div>{categories.data?.map(c=><div key={c.id} className="flex justify-between border-t py-2 text-xs"><span><b>{c.code}</b> — {c.name}</span><span>{c.allowed_direction} · {c.is_active?'Active':'Inactive'} <Button size="xs" variant="outline" onClick={()=>run(actions.categoryStatus.mutateAsync({id:c.id,isActive:!c.is_active}))}>{c.is_active?'Désactiver':'Activer'}</Button></span></div>)}</Card>}
 {tab==='flows'&&canAccounts&&<Card><div className="mb-4 flex justify-between"><div><h2 className="font-bold">Configuration des flux automatiques</h2><p className="text-xs text-slate-500">Paiements, remboursements et règlements constructeur.</p></div><b className="text-xs">{flows.data?.isReady?'Intégration active':'Intégration inactive'}</b></div><div className="grid gap-2 md:grid-cols-4"><select className={input} value={flowForm.agencyId} onChange={e=>setFlowForm({...flowForm,agencyId:e.target.value})}><option value="">Agence</option>{flows.data?.agencies.map(a=><option key={a.id} value={a.id}>{a.name}</option>)}</select><select className={input} value={flowForm.paymentMethodId} onChange={e=>setFlowForm({...flowForm,paymentMethodId:e.target.value})}><option value="">Moyen de paiement</option>{flows.data?.paymentMethods.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select><select className={input} value={flowForm.treasuryAccountId} onChange={e=>setFlowForm({...flowForm,treasuryAccountId:e.target.value})}><option value="">Compte</option>{flows.data?.accounts.filter(a=>a.is_active&&(a.agency_id===null||a.agency_id===flowForm.agencyId)).map(a=><option key={a.id} value={a.id}>{a.code} · {a.name}</option>)}</select><Button size="xs" disabled={!flowForm.agencyId||!flowForm.paymentMethodId||!flowForm.treasuryAccountId} onClick={()=>run(actions.saveFlowMapping.mutateAsync(flowForm))}>Enregistrer</Button></div>{canActivateFlows&&<div className="mt-4 text-right"><Button size="xs" onClick={()=>run(actions.flowReadiness.mutateAsync(!flows.data?.isReady))}>{flows.data?.isReady?'Désactiver':'Activer explicitement'}</Button></div>}</Card>}
 <p className="text-xs text-slate-500"><Landmark className="mr-1 inline h-3 w-3"/>Le solde est calculé exclusivement depuis les mouvements comptabilisés.</p>
 <Modal isOpen={manual!==null} onClose={()=>setManual(null)} title={manual==='IN'?'Nouvelle entrée manuelle':'Nouvelle sortie manuelle'} description="L’opération sera définitive et pourra uniquement être contrepassée."><form className="grid gap-3" onSubmit={submitManual}><select required className={input} value={form.accountId} onChange={e=>setForm({...form,accountId:e.target.value})}><option value="">Compte actif</option>{accounts.data?.filter(a=>a.is_active).map(a=><option key={a.id} value={a.id}>{a.name} · {a.currency_code} · solde {formatCurrency(Number(a.balance),a.currency_code)}</option>)}</select><input required className={input} type="number" min="0.01" step="0.01" placeholder="Montant" value={form.amount} onChange={e=>setForm({...form,amount:e.target.value})}/><select required className={input} value={form.categoryId} onChange={e=>setForm({...form,categoryId:e.target.value})}><option value="">Catégorie compatible</option>{categories.data?.filter(c=>c.is_active&&(c.allowed_direction==='BOTH'||c.allowed_direction===manual)).map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select><textarea required className={input} placeholder="Motif / description" value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/><input required className={input} type="date" max={today} value={form.valueDate} onChange={e=>setForm({...form,valueDate:e.target.value})}/><select className={input} value={form.paymentMethodId} onChange={e=>setForm({...form,paymentMethodId:e.target.value})}><option value="">Moyen de paiement (facultatif)</option>{options.data?.paymentMethods.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select><input className={input} placeholder="Référence (facultative)" value={form.reference} onChange={e=>setForm({...form,reference:e.target.value})}/><input required className={input} placeholder={manual==='IN'?'Provenance / payeur':'Bénéficiaire / destination'} value={form.counterparty} onChange={e=>setForm({...form,counterparty:e.target.value})}/>{manual==='OUT'&&<input className={input} placeholder="Fonds remis à (facultatif)" value={form.handedTo} onChange={e=>setForm({...form,handedTo:e.target.value})}/>}<div className="flex justify-end gap-2"><Button type="button" variant="outline" onClick={()=>setManual(null)}>Annuler</Button><Button type="submit" variant={manual==='OUT'?'danger':'success'} loading={actions.manualReceipt.isPending||actions.manualDisbursement.isPending}>{manual==='IN'?'Comptabiliser l’entrée':'Confirmer la sortie'}</Button></div></form></Modal>
 <TreasuryManualDocuments operationId={documents?.id??null} direction={documents?.direction??'IN'} onClose={()=>setDocuments(null)}/></div>;
};
