CREATE TABLE supplier_invoices (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  supplier_id BIGINT UNSIGNED NOT NULL,
  agency_id BIGINT UNSIGNED NOT NULL,
  concession_id BIGINT UNSIGNED NOT NULL,
  purchase_order_id BIGINT UNSIGNED NULL,
  purchase_receipt_id BIGINT UNSIGNED NULL,
  budget_expense_id BIGINT UNSIGNED NULL,
  supplier_reference VARCHAR(150) NOT NULL,
  invoice_date DATE NOT NULL,
  received_date DATE NOT NULL,
  due_date DATE NOT NULL,
  currency_code CHAR(3) NOT NULL,
  invoice_kind ENUM('GOODS','SERVICE') NOT NULL DEFAULT 'GOODS',
  subtotal DECIMAL(18,2) NOT NULL,
  tax_total DECIMAL(18,2) NOT NULL,
  total DECIMAL(18,2) NOT NULL,
  exception_reason VARCHAR(1000) NULL,
  notes TEXT NULL,
  status ENUM('DRAFT','SUBMITTED','VALIDATED','REJECTED','CANCELLED') NOT NULL DEFAULT 'DRAFT',
  created_by BIGINT UNSIGNED NOT NULL,
  submitted_by BIGINT UNSIGNED NULL,
  submitted_at DATETIME NULL,
  validated_by BIGINT UNSIGNED NULL,
  validated_at DATETIME NULL,
  rejected_by BIGINT UNSIGNED NULL,
  rejected_at DATETIME NULL,
  rejection_reason VARCHAR(500) NULL,
  cancelled_by BIGINT UNSIGNED NULL,
  cancelled_at DATETIME NULL,
  cancellation_reason VARCHAR(500) NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uq_supplier_invoice_reference (concession_id,supplier_id,supplier_reference),
  UNIQUE KEY uq_supplier_invoice_budget_expense (budget_expense_id),
  KEY idx_supplier_invoice_scope_status_due (concession_id,agency_id,status,due_date),
  KEY idx_supplier_invoice_order (purchase_order_id),
  KEY idx_supplier_invoice_receipt (purchase_receipt_id),
  CONSTRAINT chk_supplier_invoice_dates CHECK (invoice_date<=received_date AND invoice_date<=due_date),
  CONSTRAINT chk_supplier_invoice_amounts CHECK (subtotal>=0 AND tax_total>=0 AND total=subtotal+tax_total AND total>0),
  CONSTRAINT fk_supplier_invoice_supplier FOREIGN KEY (supplier_id) REFERENCES suppliers(id) ON DELETE RESTRICT,
  CONSTRAINT fk_supplier_invoice_agency FOREIGN KEY (agency_id) REFERENCES agencies(id) ON DELETE RESTRICT,
  CONSTRAINT fk_supplier_invoice_concession FOREIGN KEY (concession_id) REFERENCES concessions(id) ON DELETE RESTRICT,
  CONSTRAINT fk_supplier_invoice_order FOREIGN KEY (purchase_order_id) REFERENCES purchase_orders(id) ON DELETE RESTRICT,
  CONSTRAINT fk_supplier_invoice_receipt FOREIGN KEY (purchase_receipt_id) REFERENCES purchase_order_receipts(id) ON DELETE RESTRICT,
  CONSTRAINT fk_supplier_invoice_expense FOREIGN KEY (budget_expense_id) REFERENCES budget_expenses(id) ON DELETE RESTRICT,
  CONSTRAINT fk_supplier_invoice_creator FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE RESTRICT,
  CONSTRAINT fk_supplier_invoice_submitter FOREIGN KEY (submitted_by) REFERENCES users(id) ON DELETE RESTRICT,
  CONSTRAINT fk_supplier_invoice_validator FOREIGN KEY (validated_by) REFERENCES users(id) ON DELETE RESTRICT,
  CONSTRAINT fk_supplier_invoice_rejector FOREIGN KEY (rejected_by) REFERENCES users(id) ON DELETE RESTRICT,
  CONSTRAINT fk_supplier_invoice_canceller FOREIGN KEY (cancelled_by) REFERENCES users(id) ON DELETE RESTRICT
) ENGINE=InnoDB;

CREATE TABLE supplier_invoice_lines (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  supplier_invoice_id BIGINT UNSIGNED NOT NULL,
  purchase_order_item_id BIGINT UNSIGNED NULL,
  purchase_receipt_item_id BIGINT UNSIGNED NULL,
  part_id BIGINT UNSIGNED NULL,
  description VARCHAR(255) NOT NULL,
  quantity DECIMAL(12,3) NOT NULL,
  unit_price DECIMAL(18,2) NOT NULL,
  tax_amount DECIMAL(18,2) NOT NULL DEFAULT 0,
  line_subtotal DECIMAL(18,2) NOT NULL,
  line_total DECIMAL(18,2) NOT NULL,
  KEY idx_supplier_invoice_line_invoice (supplier_invoice_id),
  KEY idx_supplier_invoice_line_order (purchase_order_item_id),
  CONSTRAINT chk_supplier_invoice_line_values CHECK (quantity>0 AND unit_price>=0 AND tax_amount>=0 AND line_subtotal=quantity*unit_price AND line_total=line_subtotal+tax_amount),
  CONSTRAINT fk_supplier_invoice_line_invoice FOREIGN KEY (supplier_invoice_id) REFERENCES supplier_invoices(id) ON DELETE CASCADE,
  CONSTRAINT fk_supplier_invoice_line_order FOREIGN KEY (purchase_order_item_id) REFERENCES purchase_order_items(id) ON DELETE RESTRICT,
  CONSTRAINT fk_supplier_invoice_line_receipt FOREIGN KEY (purchase_receipt_item_id) REFERENCES purchase_order_receipt_items(id) ON DELETE RESTRICT,
  CONSTRAINT fk_supplier_invoice_line_part FOREIGN KEY (part_id) REFERENCES parts(id) ON DELETE RESTRICT
) ENGINE=InnoDB;

CREATE TABLE supplier_invoice_history (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  supplier_invoice_id BIGINT UNSIGNED NOT NULL,
  action ENUM('CREATED','UPDATED','SUBMITTED','VALIDATED','REJECTED','CANCELLED','BUDGET_LINKED','PAYMENT_POSTED') NOT NULL,
  old_status VARCHAR(30) NULL,
  new_status VARCHAR(30) NOT NULL,
  reason VARCHAR(1000) NULL,
  actor_id BIGINT UNSIGNED NOT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  KEY idx_supplier_invoice_history (supplier_invoice_id,created_at,id),
  CONSTRAINT fk_supplier_invoice_history_invoice FOREIGN KEY (supplier_invoice_id) REFERENCES supplier_invoices(id) ON DELETE RESTRICT,
  CONSTRAINT fk_supplier_invoice_history_actor FOREIGN KEY (actor_id) REFERENCES users(id) ON DELETE RESTRICT
) ENGINE=InnoDB;

CREATE TABLE supplier_credit_notes (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  supplier_invoice_id BIGINT UNSIGNED NOT NULL,
  supplier_id BIGINT UNSIGNED NOT NULL,
  agency_id BIGINT UNSIGNED NOT NULL,
  concession_id BIGINT UNSIGNED NOT NULL,
  reference VARCHAR(150) NOT NULL,
  credit_date DATE NOT NULL,
  amount DECIMAL(18,2) NOT NULL,
  reason VARCHAR(1000) NOT NULL,
  status ENUM('DRAFT','SUBMITTED','VALIDATED','REJECTED','CANCELLED') NOT NULL DEFAULT 'DRAFT',
  created_by BIGINT UNSIGNED NOT NULL,
  submitted_by BIGINT UNSIGNED NULL,
  submitted_at DATETIME NULL,
  validated_by BIGINT UNSIGNED NULL,
  validated_at DATETIME NULL,
  rejected_by BIGINT UNSIGNED NULL,
  rejected_at DATETIME NULL,
  decision_reason VARCHAR(500) NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uq_supplier_credit_reference (concession_id,supplier_id,reference),
  KEY idx_supplier_credit_invoice_status (supplier_invoice_id,status),
  CONSTRAINT chk_supplier_credit_amount CHECK (amount>0),
  CONSTRAINT fk_supplier_credit_invoice FOREIGN KEY (supplier_invoice_id) REFERENCES supplier_invoices(id) ON DELETE RESTRICT,
  CONSTRAINT fk_supplier_credit_supplier FOREIGN KEY (supplier_id) REFERENCES suppliers(id) ON DELETE RESTRICT,
  CONSTRAINT fk_supplier_credit_agency FOREIGN KEY (agency_id) REFERENCES agencies(id) ON DELETE RESTRICT,
  CONSTRAINT fk_supplier_credit_concession FOREIGN KEY (concession_id) REFERENCES concessions(id) ON DELETE RESTRICT,
  CONSTRAINT fk_supplier_credit_creator FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE RESTRICT,
  CONSTRAINT fk_supplier_credit_submitter FOREIGN KEY (submitted_by) REFERENCES users(id) ON DELETE RESTRICT,
  CONSTRAINT fk_supplier_credit_validator FOREIGN KEY (validated_by) REFERENCES users(id) ON DELETE RESTRICT,
  CONSTRAINT fk_supplier_credit_rejector FOREIGN KEY (rejected_by) REFERENCES users(id) ON DELETE RESTRICT
) ENGINE=InnoDB;

CREATE TABLE supplier_credit_history (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  supplier_credit_note_id BIGINT UNSIGNED NOT NULL,
  action ENUM('CREATED','SUBMITTED','VALIDATED','REJECTED','CANCELLED') NOT NULL,
  old_status VARCHAR(30) NULL,
  new_status VARCHAR(30) NOT NULL,
  reason VARCHAR(1000) NULL,
  actor_id BIGINT UNSIGNED NOT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  KEY idx_supplier_credit_history (supplier_credit_note_id,created_at,id),
  CONSTRAINT fk_supplier_credit_history_note FOREIGN KEY (supplier_credit_note_id) REFERENCES supplier_credit_notes(id) ON DELETE RESTRICT,
  CONSTRAINT fk_supplier_credit_history_actor FOREIGN KEY (actor_id) REFERENCES users(id) ON DELETE RESTRICT
) ENGINE=InnoDB;

INSERT INTO permissions(module,action,code,name,group_name,description,is_active) VALUES
('supplier_finance','view','supplier.invoice.view','Voir les factures fournisseurs','Achats & Fournisseurs','Consulter les factures fournisseurs du périmètre',TRUE),
('supplier_finance','create','supplier.invoice.create','Créer une facture fournisseur','Achats & Fournisseurs','Créer une facture fournisseur en brouillon',TRUE),
('supplier_finance','update','supplier.invoice.update','Modifier une facture fournisseur','Achats & Fournisseurs','Modifier ou annuler une facture fournisseur autorisée',TRUE),
('supplier_finance','submit','supplier.invoice.submit','Soumettre une facture fournisseur','Achats & Fournisseurs','Soumettre une facture fournisseur au contrôle',TRUE),
('supplier_finance','approve','supplier.invoice.validate','Valider une facture fournisseur','Achats & Fournisseurs','Reconnaître la dette fournisseur après contrôle',TRUE),
('supplier_finance','approve','supplier.invoice.reject','Rejeter une facture fournisseur','Achats & Fournisseurs','Rejeter une facture fournisseur soumise',TRUE),
('supplier_finance','view','supplier.debt.view','Voir les dettes fournisseurs','Achats & Fournisseurs','Consulter soldes, échéances et indicateurs fournisseurs',TRUE),
('supplier_finance','create','supplier.credit.create','Enregistrer un avoir fournisseur','Achats & Fournisseurs','Créer et soumettre un avoir imputé à une facture',TRUE),
('supplier_finance','approve','supplier.credit.validate','Valider un avoir fournisseur','Achats & Fournisseurs','Valider ou rejeter un avoir imputé',TRUE),
('supplier_finance','pay','supplier.payment.create','Régler une facture fournisseur','Achats & Fournisseurs','Créer un décaissement Treasury pour une dette validée',TRUE),
('supplier_finance','view','supplier.invoice.history.view','Voir l’historique fournisseur','Achats & Fournisseurs','Consulter les décisions, avoirs et paiements',TRUE)
ON DUPLICATE KEY UPDATE name=VALUES(name),group_name=VALUES(group_name),description=VALUES(description),is_active=VALUES(is_active);

INSERT IGNORE INTO role_permissions(role_id,permission_id,scope)
SELECT r.id,p.id,'GLOBAL' FROM roles r JOIN permissions p ON p.code IN(
 'supplier.invoice.view','supplier.invoice.create','supplier.invoice.update','supplier.invoice.submit',
 'supplier.invoice.validate','supplier.invoice.reject','supplier.debt.view','supplier.credit.create',
 'supplier.credit.validate','supplier.payment.create','supplier.invoice.history.view'
) WHERE r.code='SUPER_ADMIN' AND r.is_system=TRUE;
