CREATE TABLE bank_statements (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  account_id BIGINT UNSIGNED NOT NULL,
  agency_id BIGINT UNSIGNED NULL,
  concession_id BIGINT UNSIGNED NOT NULL,
  currency_code CHAR(3) NOT NULL,
  bank_name VARCHAR(150) NULL,
  external_reference VARCHAR(190) NULL,
  period_start DATE NOT NULL,
  period_end DATE NOT NULL,
  opening_balance DECIMAL(18,2) NULL,
  closing_balance DECIMAL(18,2) NULL,
  total_credits DECIMAL(18,2) NOT NULL DEFAULT 0,
  total_debits DECIMAL(18,2) NOT NULL DEFAULT 0,
  line_count INT UNSIGNED NOT NULL DEFAULT 0,
  file_name VARCHAR(255) NOT NULL,
  file_hash CHAR(64) NOT NULL,
  source_content LONGBLOB NOT NULL,
  mapping_json JSON NOT NULL,
  decimal_separator ENUM('DOT','COMMA') NOT NULL,
  thousands_separator ENUM('NONE','SPACE','DOT','COMMA') NOT NULL DEFAULT 'NONE',
  delimiter ENUM('SEMICOLON','COMMA') NOT NULL,
  status ENUM('DRAFT','VALIDATED','REJECTED','CANCELLED') NOT NULL DEFAULT 'DRAFT',
  duplicate_guard CHAR(64) GENERATED ALWAYS AS (CASE WHEN status IN('DRAFT','VALIDATED') THEN file_hash ELSE NULL END) STORED,
  imported_by BIGINT UNSIGNED NOT NULL,
  imported_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  validated_by BIGINT UNSIGNED NULL,
  validated_at DATETIME NULL,
  rejected_by BIGINT UNSIGNED NULL,
  rejected_at DATETIME NULL,
  rejection_reason VARCHAR(1000) NULL,
  cancelled_by BIGINT UNSIGNED NULL,
  cancelled_at DATETIME NULL,
  cancellation_reason VARCHAR(1000) NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uq_bank_statement_active_file(account_id,duplicate_guard),
  KEY idx_bank_statement_scope(account_id,status,period_start,period_end),
  CONSTRAINT chk_bank_statement_period CHECK(period_start<=period_end),
  CONSTRAINT fk_bank_statement_account FOREIGN KEY(account_id) REFERENCES treasury_accounts(id) ON DELETE RESTRICT,
  CONSTRAINT fk_bank_statement_agency FOREIGN KEY(agency_id) REFERENCES agencies(id) ON DELETE RESTRICT,
  CONSTRAINT fk_bank_statement_concession FOREIGN KEY(concession_id) REFERENCES concessions(id) ON DELETE RESTRICT,
  CONSTRAINT fk_bank_statement_importer FOREIGN KEY(imported_by) REFERENCES users(id) ON DELETE RESTRICT,
  CONSTRAINT fk_bank_statement_validator FOREIGN KEY(validated_by) REFERENCES users(id) ON DELETE RESTRICT,
  CONSTRAINT fk_bank_statement_rejecter FOREIGN KEY(rejected_by) REFERENCES users(id) ON DELETE RESTRICT,
  CONSTRAINT fk_bank_statement_canceller FOREIGN KEY(cancelled_by) REFERENCES users(id) ON DELETE RESTRICT
) ENGINE=InnoDB;

CREATE TABLE bank_statement_lines (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  statement_id BIGINT UNSIGNED NOT NULL,
  line_number INT UNSIGNED NOT NULL,
  operation_date DATE NOT NULL,
  value_date DATE NULL,
  description VARCHAR(1000) NOT NULL,
  bank_reference VARCHAR(255) NULL,
  signed_amount DECIMAL(18,2) NOT NULL,
  balance_after DECIMAL(18,2) NULL,
  raw_data JSON NOT NULL,
  duplicate_class ENUM('NONE','POTENTIAL','CERTAIN') NOT NULL DEFAULT 'NONE',
  duplicate_of_line_id BIGINT UNSIGNED NULL,
  observation VARCHAR(1000) NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE KEY uq_bank_statement_line_order(statement_id,line_number),
  KEY idx_bank_line_match(statement_id,operation_date,signed_amount),
  KEY idx_bank_line_reference(bank_reference),
  CONSTRAINT chk_bank_line_nonzero CHECK(signed_amount<>0),
  CONSTRAINT fk_bank_line_statement FOREIGN KEY(statement_id) REFERENCES bank_statements(id) ON DELETE RESTRICT,
  CONSTRAINT fk_bank_line_duplicate FOREIGN KEY(duplicate_of_line_id) REFERENCES bank_statement_lines(id) ON DELETE RESTRICT
) ENGINE=InnoDB;

CREATE TABLE bank_reconciliations (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  statement_line_id BIGINT UNSIGNED NOT NULL,
  treasury_movement_id BIGINT UNSIGNED NOT NULL,
  status ENUM('VALIDATED','CANCELLED') NOT NULL DEFAULT 'VALIDATED',
  active_statement_line_id BIGINT UNSIGNED GENERATED ALWAYS AS (CASE WHEN status='VALIDATED' THEN statement_line_id ELSE NULL END) STORED,
  active_treasury_movement_id BIGINT UNSIGNED GENERATED ALWAYS AS (CASE WHEN status='VALIDATED' THEN treasury_movement_id ELSE NULL END) STORED,
  bank_amount DECIMAL(18,2) NOT NULL,
  treasury_amount DECIMAL(18,2) NOT NULL,
  amount_difference DECIMAL(18,2) NOT NULL,
  date_difference_days INT NOT NULL,
  match_kind ENUM('EXACT','AMOUNT_DIFFERENCE','DATE_DIFFERENCE','AMOUNT_AND_DATE_DIFFERENCE') NOT NULL,
  observation VARCHAR(1000) NULL,
  client_request_id CHAR(36) NOT NULL,
  payload_hash CHAR(64) NOT NULL,
  validated_by BIGINT UNSIGNED NOT NULL,
  validated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  cancelled_by BIGINT UNSIGNED NULL,
  cancelled_at DATETIME NULL,
  cancellation_reason VARCHAR(1000) NULL,
  UNIQUE KEY uq_bank_reconciliation_active_line(active_statement_line_id),
  UNIQUE KEY uq_bank_reconciliation_active_movement(active_treasury_movement_id),
  UNIQUE KEY uq_bank_reconciliation_request(validated_by,client_request_id),
  KEY idx_bank_reconciliation_status(status,validated_at),
  CONSTRAINT fk_bank_reconciliation_line FOREIGN KEY(statement_line_id) REFERENCES bank_statement_lines(id) ON DELETE RESTRICT,
  CONSTRAINT fk_bank_reconciliation_movement FOREIGN KEY(treasury_movement_id) REFERENCES treasury_movements(id) ON DELETE RESTRICT,
  CONSTRAINT fk_bank_reconciliation_validator FOREIGN KEY(validated_by) REFERENCES users(id) ON DELETE RESTRICT,
  CONSTRAINT fk_bank_reconciliation_canceller FOREIGN KEY(cancelled_by) REFERENCES users(id) ON DELETE RESTRICT
) ENGINE=InnoDB;

CREATE TABLE bank_reconciliation_history (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  statement_id BIGINT UNSIGNED NOT NULL,
  statement_line_id BIGINT UNSIGNED NULL,
  reconciliation_id BIGINT UNSIGNED NULL,
  action ENUM('IMPORTED','VALIDATED','REJECTED','RECONCILED','RECONCILIATION_CANCELLED','IMPORT_CANCELLED','OBSERVATION_UPDATED') NOT NULL,
  reason VARCHAR(1000) NULL,
  actor_id BIGINT UNSIGNED NOT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  KEY idx_bank_reconciliation_history(statement_id,created_at,id),
  CONSTRAINT fk_bank_history_statement FOREIGN KEY(statement_id) REFERENCES bank_statements(id) ON DELETE RESTRICT,
  CONSTRAINT fk_bank_history_line FOREIGN KEY(statement_line_id) REFERENCES bank_statement_lines(id) ON DELETE RESTRICT,
  CONSTRAINT fk_bank_history_reconciliation FOREIGN KEY(reconciliation_id) REFERENCES bank_reconciliations(id) ON DELETE RESTRICT,
  CONSTRAINT fk_bank_history_actor FOREIGN KEY(actor_id) REFERENCES users(id) ON DELETE RESTRICT
) ENGINE=InnoDB;

INSERT INTO permissions(module,action,code,name,group_name,description,is_active) VALUES
('bank_reconciliation','view','treasury.reconciliation.view','Voir les relevés bancaires','Comptabilité & Trésorerie','Consulter les relevés, rapprochements et écarts du périmètre',TRUE),
('bank_reconciliation','import','treasury.reconciliation.import','Importer un relevé bancaire','Comptabilité & Trésorerie','Analyser et importer un relevé bancaire CSV',TRUE),
('bank_reconciliation','approve','treasury.reconciliation.validate_import','Valider un relevé bancaire','Comptabilité & Trésorerie','Valider ou rejeter un import analysé',TRUE),
('bank_reconciliation','approve','treasury.reconciliation.reconcile','Valider un rapprochement bancaire','Comptabilité & Trésorerie','Rapprocher explicitement une ligne et un mouvement Treasury',TRUE),
('bank_reconciliation','reverse','treasury.reconciliation.cancel','Annuler un rapprochement bancaire','Comptabilité & Trésorerie','Annuler un rapprochement avec motif sans modifier Treasury',TRUE),
('bank_reconciliation','export','treasury.reconciliation.export','Exporter les rapprochements','Comptabilité & Trésorerie','Exporter les relevés, écarts et synthèses autorisés',TRUE)
ON DUPLICATE KEY UPDATE name=VALUES(name),group_name=VALUES(group_name),description=VALUES(description),is_active=VALUES(is_active);

INSERT IGNORE INTO role_permissions(role_id,permission_id,scope)
SELECT r.id,p.id,'GLOBAL' FROM roles r JOIN permissions p ON p.code LIKE 'treasury.reconciliation.%'
WHERE r.code='SUPER_ADMIN' AND r.is_system=TRUE;
