import React from'react';
import{Bar,BarChart,CartesianGrid,Cell,Line,LineChart,Pie,PieChart,ResponsiveContainer,Tooltip,XAxis,YAxis}from'recharts';
import type{HrOverview,HrReport}from'../../api/hrHooks';
import{Card,CardDescription,CardHeader,CardTitle}from'../../components/ui/Card';

const COLORS=['#8f1722','#2563eb','#0891b2','#059669','#d97706','#7c3aed'];
const money=(value:number)=>`${new Intl.NumberFormat('fr-FR',{maximumFractionDigits:0}).format(Number.isFinite(value)?value:0).replace(/[\u00a0\u202f]/g,'.')} XAF`;
const tickMoney=(value:number)=>new Intl.NumberFormat('fr-FR',{notation:'compact',maximumFractionDigits:1}).format(value);
const periodLabel=(value:string)=>/^\d{4}-\d{2}$/.test(value)?new Intl.DateTimeFormat('fr-FR',{month:'short',year:'2-digit'}).format(new Date(`${value}-01T12:00:00`)):value;
const ChartEmpty=()=> <p className="flex h-full items-center justify-center p-6 text-center text-xs text-slate-500">Aucune donnée disponible pour cette période.</p>;
const State=({loading,error}:{loading:boolean;error:Error|null})=>loading?<Card><p className="animate-pulse p-8 text-center text-xs text-slate-500">Chargement des indicateurs…</p></Card>:error?<Card className="border-red-200 bg-red-50 text-xs text-red-700">Erreur de chargement : {error.message}</Card>:null;
const ChartCard=({title,description,children,className=''}:{title:string;description:string;children:React.ReactNode;className?:string})=><Card className={className}><CardHeader><div><CardTitle>{title}</CardTitle><CardDescription>{description}</CardDescription></div></CardHeader><div className="h-64">{children}</div></Card>;

export function HrOverviewDashboard({data,loading,error}:{data?:HrOverview;loading:boolean;error:Error|null}){
 if(loading||error)return <State loading={loading} error={error}/>;
 if(!data||!Object.keys(data).length)return <Card><ChartEmpty/></Card>;
 return <div className="space-y-4"><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4">
  {data.activeEmployees!==undefined&&<Kpi label="Effectif actif" value={String(data.activeEmployees)}/>} 
  {data.payroll!==undefined&&<Kpi label="Masse salariale courante" value={money(data.payroll)}/>} 
  {data.activeBudget!==undefined&&<Kpi label="Budget total actif" value={money(data.activeBudget)} detail={`${money(data.expenses??0)} consommé · ${money(data.remainingBudget??0)} restant`}/>} 
  {data.periodExpenses!==undefined&&<Kpi label="Dépenses · 6 derniers mois" value={money(data.periodExpenses)}/>} 
  {data.stockItems!==undefined&&<Kpi label="Articles de stock actifs" value={String(data.stockItems)} detail={`${data.lowStockItems??0} sous seuil`}/>} 
 </div><div className="grid gap-4 lg:grid-cols-2">
  {data.headcountByAgency&&<ChartCard title="Effectifs par agence" description="Employés actifs dans votre périmètre">{data.headcountByAgency.length?<ResponsiveContainer><BarChart data={data.headcountByAgency}><CartesianGrid strokeDasharray="3 3" vertical={false}/><XAxis dataKey="agencyName"/><YAxis allowDecimals={false}/><Tooltip/><Bar isAnimationActive={false} dataKey="employees" name="Employés" fill="#8f1722" radius={[4,4,0,0]}/></BarChart></ResponsiveContainer>:<ChartEmpty/>}</ChartCard>}
  {data.budgetSummary&&<ChartCard title="Situation budgétaire" description="Budgets actifs, montants réels">{data.budgetSummary.some(x=>x.value!==0)?<ResponsiveContainer><BarChart data={data.budgetSummary}><CartesianGrid strokeDasharray="3 3" vertical={false}/><XAxis dataKey="label"/><YAxis tickFormatter={tickMoney} width={55}/><Tooltip formatter={(v:any)=>money(Number(v))}/><Bar isAnimationActive={false} dataKey="value" name="Montant" fill="#2563eb" radius={[4,4,0,0]}/></BarChart></ResponsiveContainer>:<ChartEmpty/>}</ChartCard>}
  {data.expenseTrend&&<ChartCard title="Évolution des dépenses" description="Six derniers mois, selon la date de dépense">{data.expenseTrend.length?<ResponsiveContainer><LineChart data={data.expenseTrend}><CartesianGrid strokeDasharray="3 3" vertical={false}/><XAxis dataKey="period" tickFormatter={periodLabel}/><YAxis tickFormatter={tickMoney} width={55}/><Tooltip labelFormatter={v=>periodLabel(String(v))} formatter={(v:any)=>money(Number(v))}/><Line isAnimationActive={false} type="monotone" dataKey="spent" name="Dépenses" stroke="#8f1722" strokeWidth={3}/></LineChart></ResponsiveContainer>:<ChartEmpty/>}</ChartCard>}
  {data.stockStatus&&<ChartCard title="Stock interne" description="Articles actifs à leur niveau actuel">{data.stockStatus.some(x=>x.value!==0)?<ResponsiveContainer><PieChart><Pie isAnimationActive={false} data={data.stockStatus} dataKey="value" nameKey="label" innerRadius={48} outerRadius={78}>{data.stockStatus.map((_,i)=><Cell key={i} fill={COLORS[(i+2)%COLORS.length]}/>)}</Pie><Tooltip/></PieChart></ResponsiveContainer>:<ChartEmpty/>}</ChartCard>}
 </div></div>
}

export function HrReportingDashboard({data,loading,error}:{data?:HrReport;loading:boolean;error:Error|null}){
 if(loading||error)return <State loading={loading} error={error}/>;
 if(!data)return <Card><ChartEmpty/></Card>;
 const budgetTotals=(data.budgets??[]).reduce((a,x)=>({initial:a.initial+x.initial_amount,added:a.added+x.additional_funds,total:a.total+x.total_allocated,spent:a.spent+x.spent,remaining:a.remaining+x.remaining}),{initial:0,added:0,total:0,spent:0,remaining:0}),headcount=(data.headcount??[]).reduce((a,x)=>a+x.employees,0),payroll=(data.payroll??[]).reduce((a,x)=>a+x.payroll,0),stock=(data.stock??[]).reduce((a,x)=>({items:a.items+x.items,low:a.low+x.low_items}),{items:0,low:0}),expenses=(data.expenseCategories??[]).reduce((a,x)=>a+x.spent,0);
 return <div className="space-y-6">
  {data.headcount&&<Section title="Effectifs" summary={`${headcount} employé(s) actif(s)`}><ChartCard title="Effectifs par agence" description="État actuel, hors filtre de période">{data.headcount.length?<ResponsiveContainer><BarChart data={data.headcount}><CartesianGrid strokeDasharray="3 3" vertical={false}/><XAxis dataKey="agency_name"/><YAxis allowDecimals={false}/><Tooltip/><Bar isAnimationActive={false} dataKey="employees" name="Employés" fill="#8f1722"/></BarChart></ResponsiveContainer>:<ChartEmpty/>}</ChartCard></Section>}
  {data.payroll&&<Section title="Masse salariale" summary={money(payroll)}><ChartCard title="Masse salariale par agence" description="Salaires courants, avec scope salarial propre">{data.payroll.length?<ResponsiveContainer><BarChart data={data.payroll}><CartesianGrid strokeDasharray="3 3" vertical={false}/><XAxis dataKey="agency_name"/><YAxis tickFormatter={tickMoney} width={55}/><Tooltip formatter={(v:any)=>money(Number(v))}/><Bar isAnimationActive={false} dataKey="payroll" name="Masse salariale" fill="#7c3aed"/></BarChart></ResponsiveContainer>:<ChartEmpty/>}</ChartCard></Section>}
  {data.budgets&&<Section title="Budgets" summary={`${money(budgetTotals.initial)} initial · ${money(budgetTotals.added)} ajouté · ${money(budgetTotals.total)} total · ${money(budgetTotals.remaining)} restant`}><ChartCard title="Budget par catégorie" description="Dotation initiale, rallonges et consommation réelles">{data.budgets.length?<ResponsiveContainer><BarChart data={data.budgets}><CartesianGrid strokeDasharray="3 3" vertical={false}/><XAxis dataKey="category_name"/><YAxis tickFormatter={tickMoney} width={55}/><Tooltip formatter={(v:any)=>money(Number(v))}/><Bar isAnimationActive={false} dataKey="initial_amount" name="Initial" fill="#2563eb"/><Bar isAnimationActive={false} dataKey="additional_funds" name="Fonds ajoutés" fill="#7c3aed"/><Bar isAnimationActive={false} dataKey="spent" name="Consommé" fill="#d97706"/><Bar isAnimationActive={false} dataKey="remaining" name="Restant" fill="#059669"/></BarChart></ResponsiveContainer>:<ChartEmpty/>}</ChartCard></Section>}
  {data.expenseCategories&&<Section title="Dépenses" summary={`${money(expenses)} sur la période`}><div className="grid gap-4 lg:grid-cols-2"><ChartCard title="Dépenses par catégorie opérationnelle" description="Catégorie propre à chaque dépense">{data.expenseCategories.length?<ResponsiveContainer><BarChart data={data.expenseCategories}><CartesianGrid strokeDasharray="3 3" vertical={false}/><XAxis dataKey="category_name"/><YAxis tickFormatter={tickMoney} width={55}/><Tooltip formatter={(v:any)=>money(Number(v))}/><Bar isAnimationActive={false} dataKey="spent" name="Dépenses" fill="#0891b2"/></BarChart></ResponsiveContainer>:<ChartEmpty/>}</ChartCard><ChartCard title="Évolution des dépenses" description="Agrégation mensuelle par expense_date">{data.expenseTrend?.length?<ResponsiveContainer><LineChart data={data.expenseTrend}><CartesianGrid strokeDasharray="3 3" vertical={false}/><XAxis dataKey="period" tickFormatter={periodLabel}/><YAxis tickFormatter={tickMoney} width={55}/><Tooltip labelFormatter={v=>periodLabel(String(v))} formatter={(v:any)=>money(Number(v))}/><Line isAnimationActive={false} type="monotone" dataKey="spent" name="Dépenses" stroke="#8f1722" strokeWidth={3}/></LineChart></ResponsiveContainer>:<ChartEmpty/>}</ChartCard></div></Section>}
  {data.stock&&<Section title="Stock interne" summary={`${stock.items} article(s) actif(s) · ${stock.low} sous seuil`}><ChartCard title="État du stock par agence" description="Articles actifs et alertes actuelles">{data.stock.length?<ResponsiveContainer><BarChart data={data.stock}><CartesianGrid strokeDasharray="3 3" vertical={false}/><XAxis dataKey="agency_name"/><YAxis allowDecimals={false}/><Tooltip/><Bar isAnimationActive={false} dataKey="items" name="Articles" fill="#2563eb"/><Bar isAnimationActive={false} dataKey="low_items" name="Sous seuil" fill="#dc2626"/></BarChart></ResponsiveContainer>:<ChartEmpty/>}</ChartCard></Section>}
 </div>
}

const Section=({title,summary,children}:{title:string;summary:string;children:React.ReactNode})=><section className="space-y-3"><div><h2 className="text-base font-bold text-slate-900">{title}</h2><p className="text-xs text-slate-500">{summary}</p></div>{children}</section>;
const Kpi=({label,value,detail}:{label:string;value:string;detail?:string})=><Card className="border-t-4 border-t-[#8f1722]"><p className="text-xs font-semibold text-slate-500">{label}</p><p className="mt-1 text-xl font-bold">{value}</p>{detail&&<p className="mt-1 text-[11px] text-slate-500">{detail}</p>}</Card>;
