import { Router } from 'express';
import { asyncHandler } from '../../middleware/error-handler.js';
import { requirePermission } from '../../middleware/require-permission.js';
import { documentMultipart, type MultipartRequest } from '../documents/document-multipart.js';
import { removeAvatar, saveAvatar } from './user-avatar.js';
import * as service from './user.service.js';
import { assertCanManage } from './user-access.js';

export const userRouter=Router();
const routeId=(value:string|string[]|undefined)=>String(Array.isArray(value)?value[0]:value??'');
userRouter.get('/users/directory',asyncHandler(async(req,res)=>res.json(await service.directory(req.query,req))));
userRouter.get('/users/me',asyncHandler(async(req,res)=>res.json(await service.one(req.user!.sub))));
userRouter.patch('/users/me',asyncHandler(async(req,res)=>res.json(await service.updateOwnProfile(req.body,req))));
userRouter.patch('/users/me/password',asyncHandler(async(req,res)=>res.json(await service.changeOwnPassword(req.body,req))));
userRouter.post('/users/me/avatar',documentMultipart,asyncHandler(async(req,res)=>{const current=await service.one(req.user!.sub),avatar=await saveAvatar((req as MultipartRequest).documentFile),updated=await service.avatarChanged(req.user!.sub,avatar,req);await removeAvatar(current.avatar);res.status(201).json(updated)}));
userRouter.delete('/users/me/avatar',asyncHandler(async(req,res)=>{const current=await service.one(req.user!.sub),updated=await service.avatarChanged(req.user!.sub,null,req);await removeAvatar(current.avatar);res.json(updated)}));
userRouter.get('/users',requirePermission('users.view'),asyncHandler(async(req,res)=>res.json(await service.list(req.query,req))));
userRouter.get('/users/:id',requirePermission('users.view'),asyncHandler(async(req,res)=>res.json(await service.one(routeId(req.params.id),req))));
userRouter.post('/users',requirePermission('users.create'),asyncHandler(async(req,res)=>res.status(201).json(await service.create(req.body,req))));
userRouter.patch('/users/:id',requirePermission('users.update'),asyncHandler(async(req,res)=>res.json(await service.update(routeId(req.params.id),req.body,req))));
userRouter.patch('/users/:id/status',requirePermission('users.disable'),asyncHandler(async(req,res)=>res.json(await service.status(routeId(req.params.id),req.body.isActive,req))));
userRouter.patch('/users/:id/password',requirePermission('users.reset_password'),asyncHandler(async(req,res)=>res.json(await service.resetPassword(routeId(req.params.id),req.body,req))));
userRouter.post('/users/:id/avatar',requirePermission('users.update'),documentMultipart,asyncHandler(async(req,res)=>{const id=routeId(req.params.id);await assertCanManage(req,id);const current=await service.one(id),avatar=await saveAvatar((req as MultipartRequest).documentFile),updated=await service.avatarChanged(id,avatar,req);await removeAvatar(current.avatar);res.status(201).json(updated)}));
userRouter.delete('/users/:id/avatar',requirePermission('users.update'),asyncHandler(async(req,res)=>{const id=routeId(req.params.id);await assertCanManage(req,id);const current=await service.one(id),updated=await service.avatarChanged(id,null,req);await removeAvatar(current.avatar);res.json(updated)}));
userRouter.get('/permissions',requirePermission('roles.view'),asyncHandler(async(_req,res)=>res.json(await service.permissionsCatalog())));
userRouter.get('/roles',requirePermission('roles.view'),asyncHandler(async(_req,res)=>res.json(await service.rolesList())));
userRouter.get('/roles/:id/permissions',requirePermission('roles.view'),asyncHandler(async(req,res)=>res.json(await service.rolePermissions(routeId(req.params.id)))));
userRouter.post('/roles',requirePermission('roles.create'),asyncHandler(async(req,res)=>res.status(201).json(await service.createRole(req.body,req))));
userRouter.patch('/roles/:id',requirePermission('roles.update'),asyncHandler(async(req,res)=>res.json(await service.updateRole(routeId(req.params.id),req.body,req))));
userRouter.patch('/roles/:id/status',requirePermission('roles.disable'),asyncHandler(async(req,res)=>res.json(await service.roleStatus(routeId(req.params.id),req.body.isActive,req))));
userRouter.delete('/roles/:id',requirePermission('roles.delete'),asyncHandler(async(req,res)=>res.json(await service.deleteRole(routeId(req.params.id),req.body?.replacementRoleId,req))));
