import {Router,type Request} from 'express';
import type {PoolConnection,ResultSetHeader,RowDataPacket} from 'mysql2/promise';
import {query as rawQuery,transaction} from '../../config/database.js';
import {asyncHandler} from '../../middleware/error-handler.js';
import {requirePermission} from '../../middleware/require-permission.js';
import {emitToAgenciesAndGlobals,emitToAgencyAndGlobals} from '../../realtime/socket.js';
import {HttpError} from '../../shared/http-error.js';
import {assertPermission,can,rbac,type PermissionScope} from '../rbac/rbac.service.js';
import{writeAudit}from'../activity/audit-writer.js';

export const hrContractRouter=Router();
const query=<T extends RowDataPacket[]>(sql:string,values?:unknown[])=>rawQuery<T>(sql,values as any);
type Input=Record<string,any>;
const id=(v:unknown)=>{const x=String(v??'');if(!/^[1-9]\d*$/.test(x))throw new HttpError(400,'Identifiant invalide.');return x};
const optionalId=(v:unknown)=>v==null||v===''?null:id(v);
const text=(v:unknown,label:string,required=false,max=190)=>{const x=typeof v==='string'?v.trim():'';if(required&&!x)throw new HttpError(400,`${label} obligatoire.`);if(x.length>max)throw new HttpError(400,`${label} trop long.`);return x||null};
const date=(v:unknown,label:string)=>{const x=String(v??'');if(!/^\d{4}-\d{2}-\d{2}$/.test(x)||Number.isNaN(Date.parse(`${x}T00:00:00Z`)))throw new HttpError(400,`${label} invalide.`);return x};
const optionalDate=(v:unknown,label:string)=>v==null||v===''?null:date(v,label);
const code=(v:unknown)=>{const x=String(v??'').trim().toUpperCase().replace(/[\s-]+/g,'_');if(!/^[A-Z0-9_]{1,50}$/.test(x))throw new HttpError(400,'Code type invalide.');return x};
const reference=(v:unknown)=>{const x=String(v??'').trim().toUpperCase().replace(/\s+/g,' ');if(!/^[A-Z0-9][A-Z0-9 ./_-]{0,99}$/.test(x))throw new HttpError(400,'Référence contrat invalide.');return x};
const predicate=(r:Request,scope:PermissionScope|null,alias='ep')=>scope==='GLOBAL'?{sql:'1=1',params:[]as any[]}:scope==='CONCESSION'?{sql:`${alias}.concession_id=(SELECT concession_id FROM agencies WHERE id=?)`,params:[r.user!.agencyId]}:scope==='AGENCY'?{sql:`${alias}.agency_id=?`,params:[r.user!.agencyId]}:scope==='OWN'?{sql:`${alias}.user_id=?`,params:[r.user!.sub]}:(()=>{throw new HttpError(403,'Périmètre employé invalide.')})();
async function audit(c:PoolConnection,r:Request,type:string,entityId:string,action:string,value:unknown){await writeAudit(c,r,{module:'hr',entityType:type,entityId,action,newValues:value})}
function event(employeeId:string,agencyId:string|null,action:string){const payload={employeeId,agencyId,action};if(agencyId)emitToAgencyAndGlobals(agencyId,'hr:contract-updated',payload);else emitToAgenciesAndGlobals([],'hr:contract-updated',payload)}
async function actorConcession(r:Request){const[x]=await query<RowDataPacket[]>('SELECT concession_id FROM agencies WHERE id=?',[r.user!.agencyId]);if(!x)throw new HttpError(403,'Agence de rattachement invalide.');return String(x.concession_id)}
async function typeConcession(r:Request,requested?:unknown){const scope=await assertPermission(r,'hr.contract.type.manage');if(scope==='OWN'||scope==='AGENCY')throw new HttpError(403,'La gestion des types de contrat exige un scope CONCESSION ou GLOBAL.');if(scope==='CONCESSION'){const concessionId=await actorConcession(r);if(requested!=null&&requested!==''&&id(requested)!==concessionId)throw new HttpError(403,'Concession hors périmètre.');return concessionId}return id(requested)}
async function lockEmployee(c:PoolConnection,r:Request,permission:string,employeeId:string){const scope=await assertPermission(r,permission),p=predicate(r,scope);const[rows]=await c.execute<RowDataPacket[]>(`SELECT ep.* FROM employee_profiles ep WHERE ep.id=? AND ${p.sql} FOR UPDATE`,[employeeId,...p.params]);if(!rows[0])throw new HttpError(404,'Employé introuvable dans votre périmètre.');return rows[0]}
const contractSelect=`SELECT ec.*,ep.agency_id,ep.user_id,ep.first_name,ep.last_name,ep.employee_number,ct.code current_type_code,ct.name current_type_name,ct.is_active type_is_active,CASE WHEN ec.status='ACTIVE' AND ec.start_date>CURDATE() THEN 'SCHEDULED' WHEN ec.status='ACTIVE' AND COALESCE(ec.effective_end_date,ec.contractual_end_date) IS NOT NULL AND COALESCE(ec.effective_end_date,ec.contractual_end_date)<CURDATE() THEN 'EXPIRED' ELSE ec.status END effective_status FROM employee_contracts ec JOIN employee_profiles ep ON ep.id=ec.employee_profile_id JOIN employee_contract_types ct ON ct.id=ec.contract_type_id`;
const json=(x:RowDataPacket)=>({...x,id:String(x.id),employee_profile_id:String(x.employee_profile_id),concession_id:String(x.concession_id),contract_type_id:String(x.contract_type_id),previous_contract_id:x.previous_contract_id==null?null:String(x.previous_contract_id),agency_id:x.agency_id==null?null:String(x.agency_id),user_id:x.user_id==null?null:String(x.user_id),type_is_active:Boolean(x.type_is_active)});
async function getContract(r:Request,permission:string,contractId:string,c?:PoolConnection,lock=false){const scope=await assertPermission(r,permission),p=predicate(r,scope),sql=`${contractSelect} WHERE ec.id=? AND ${p.sql}${lock?' FOR UPDATE':''}`;const rows=c?(await c.execute<RowDataPacket[]>(sql,[contractId,...p.params]))[0]:await query<RowDataPacket[]>(sql,[contractId,...p.params]);if(!rows[0])throw new HttpError(404,'Contrat introuvable dans votre périmètre.');return rows[0]}
async function assertNoOverlap(c:PoolConnection,employeeId:string,start:string,end:string|null,exclude?:string){const[rows]=await c.execute<RowDataPacket[]>(`SELECT id FROM employee_contracts WHERE employee_profile_id=? AND status='ACTIVE' AND id<>COALESCE(?,0) AND start_date<=COALESCE(?, '9999-12-31') AND COALESCE(effective_end_date,contractual_end_date,'9999-12-31')>=? FOR UPDATE`,[employeeId,exclude??null,end,start]);if(rows[0])throw new HttpError(409,'La période chevauche un autre contrat applicable.')}

hrContractRouter.get('/hr/contract-types',asyncHandler(async(r,res)=>{const context=await rbac(r),permission=can(context,'hr.contract.type.manage')?'hr.contract.type.manage':can(context,'hr.contract.manage')?'hr.contract.manage':'hr.contract.view',scope=await assertPermission(r,permission);if(scope==='OWN'||scope==='AGENCY')throw new HttpError(403,'Le catalogue des types exige un scope CONCESSION ou GLOBAL.');const params:unknown[]=[];let where='1=1';if(scope==='CONCESSION'){where='ct.concession_id=(SELECT concession_id FROM agencies WHERE id=?)';params.push(r.user!.agencyId)}if(r.query.concessionId){const concessionId=id(r.query.concessionId);if(scope==='CONCESSION'&&concessionId!==await actorConcession(r))throw new HttpError(403,'Concession hors périmètre.');where+=' AND ct.concession_id=?';params.push(concessionId)}if(r.query.active==='true')where+=' AND ct.is_active=TRUE';const rows=await query<RowDataPacket[]>(`SELECT ct.*,c.name concession_name,EXISTS(SELECT 1 FROM employee_contracts ec WHERE ec.contract_type_id=ct.id) is_used FROM employee_contract_types ct JOIN concessions c ON c.id=ct.concession_id WHERE ${where} ORDER BY ct.name,ct.id`,params);res.json(rows.map(x=>({...x,id:String(x.id),concession_id:String(x.concession_id),is_active:Boolean(x.is_active),is_used:Boolean(x.is_used)})))}));
hrContractRouter.post('/hr/contract-types',requirePermission('hr.contract.type.manage'),asyncHandler(async(r,res)=>{const b=r.body as Input,concessionId=await typeConcession(r,b.concessionId),typeCode=code(b.code),name=text(b.name,'Nom',true,120)!;const typeId=await transaction(async c=>{try{const[result]=await c.execute<ResultSetHeader>('INSERT INTO employee_contract_types(concession_id,code,name,description,created_by,updated_by) SELECT ?,?,?,?,?,? FROM concessions WHERE id=? AND is_active=TRUE',[concessionId,typeCode,name,text(b.description,'Description',false,500),r.user!.sub,r.user!.sub,concessionId]);if(!result.affectedRows)throw new HttpError(400,'Concession inexistante ou inactive.');await audit(c,r,'employee_contract_type',String(result.insertId),'contract.type.created',{concessionId,code:typeCode,name});return String(result.insertId)}catch(error:any){if(error?.code==='ER_DUP_ENTRY')throw new HttpError(409,'Ce code ou ce nom existe déjà dans cette concession.');throw error}});res.status(201).json({id:typeId})}));
hrContractRouter.patch('/hr/contract-types/:id',requirePermission('hr.contract.type.manage'),asyncHandler(async(r,res)=>{const typeId=id(r.params.id),b=r.body as Input,scope=await assertPermission(r,'hr.contract.type.manage');if(scope==='OWN'||scope==='AGENCY')throw new HttpError(403,'La gestion des types exige un scope CONCESSION ou GLOBAL.');if(typeof b.isActive!=='boolean')throw new HttpError(400,'Statut type invalide.');await transaction(async c=>{const[rows]=await c.execute<RowDataPacket[]>(`SELECT ct.*,EXISTS(SELECT 1 FROM employee_contracts ec WHERE ec.contract_type_id=ct.id) is_used FROM employee_contract_types ct WHERE ct.id=?${scope==='CONCESSION'?' AND ct.concession_id=(SELECT concession_id FROM agencies WHERE id=?)':''} FOR UPDATE`,[typeId,...(scope==='CONCESSION'?[r.user!.agencyId]:[])]),current=rows[0];if(!current)throw new HttpError(404,'Type de contrat introuvable.');const nextCode=code(b.code),name=text(b.name,'Nom',true,120)!;if(current.is_used&&nextCode!==current.code)throw new HttpError(409,'Le code d’un type utilisé est immuable.');try{await c.execute('UPDATE employee_contract_types SET code=?,name=?,description=?,is_active=?,updated_by=? WHERE id=?',[nextCode,name,text(b.description,'Description',false,500),b.isActive,r.user!.sub,typeId])}catch(error:any){if(error?.code==='ER_DUP_ENTRY')throw new HttpError(409,'Ce code ou ce nom existe déjà dans cette concession.');throw error}await audit(c,r,'employee_contract_type',typeId,b.isActive?'contract.type.updated':'contract.type.deactivated',{before:{code:current.code,name:current.name,isActive:Boolean(current.is_active)},after:{code:nextCode,name,isActive:b.isActive}})});res.json({success:true})}));

hrContractRouter.get('/hr/employees/:employeeId/contracts',requirePermission('hr.contract.view'),asyncHandler(async(r,res)=>{const employeeId=id(r.params.employeeId),scope=await assertPermission(r,'hr.contract.view'),p=predicate(r,scope);const rows=await query<RowDataPacket[]>(`${contractSelect} WHERE ec.employee_profile_id=? AND ${p.sql} ORDER BY ec.start_date DESC,ec.id DESC`,[employeeId,...p.params]);if(!rows.length){const[e]=await query<RowDataPacket[]>(`SELECT ep.id FROM employee_profiles ep WHERE ep.id=? AND ${p.sql}`,[employeeId,...p.params]);if(!e)throw new HttpError(404,'Employé introuvable dans votre périmètre.')}res.json(rows.map(json))}));
hrContractRouter.get('/hr/contracts/:id',requirePermission('hr.contract.view'),asyncHandler(async(r,res)=>res.json(json(await getContract(r,'hr.contract.view',id(r.params.id))))));
hrContractRouter.post('/hr/employees/:employeeId/contracts',requirePermission('hr.contract.manage'),asyncHandler(async(r,res)=>{const employeeId=id(r.params.employeeId),b=r.body as Input,typeId=id(b.contractTypeId),start=date(b.startDate,'Date de début'),end=optionalDate(b.endDate,'Date de fin');if(end&&end<start)throw new HttpError(400,'La date de fin doit suivre la date de début.');const result=await transaction(async c=>{const employee=await lockEmployee(c,r,'hr.contract.manage',employeeId);const[types]=await c.execute<RowDataPacket[]>('SELECT * FROM employee_contract_types WHERE id=? AND concession_id=? AND is_active=TRUE FOR UPDATE',[typeId,employee.concession_id]),type=types[0];if(!type)throw new HttpError(409,'Type de contrat actif introuvable dans la concession de l’employé.');try{const[created]=await c.execute<ResultSetHeader>('INSERT INTO employee_contracts(employee_profile_id,concession_id,contract_type_id,type_code_snapshot,type_name_snapshot,reference,start_date,contractual_end_date,status,created_by,updated_by) VALUES(?,?,?,?,?,?,?,?,\'DRAFT\',?,?)',[employeeId,employee.concession_id,typeId,type.code,type.name,reference(b.reference),start,end,r.user!.sub,r.user!.sub]);await audit(c,r,'employee_contract',String(created.insertId),'contract.created',{employeeId,typeId,startDate:start,endDate:end});return{id:String(created.insertId),agencyId:employee.agency_id==null?null:String(employee.agency_id)}}catch(error:any){if(error?.code==='ER_DUP_ENTRY')throw new HttpError(409,'Référence contrat déjà utilisée dans cette concession.');throw error}});event(employeeId,result.agencyId,'created');res.status(201).json({id:result.id})}));
hrContractRouter.patch('/hr/contracts/:id',requirePermission('hr.contract.manage'),asyncHandler(async(r,res)=>{const contractId=id(r.params.id),b=r.body as Input;const agencyId=await transaction(async c=>{const current=await getContract(r,'hr.contract.manage',contractId,c,true);await lockEmployee(c,r,'hr.contract.manage',String(current.employee_profile_id));if(current.status!=='DRAFT')throw new HttpError(409,'Seul un brouillon peut être modifié.');const typeId=Object.hasOwn(b,'contractTypeId')?id(b.contractTypeId):String(current.contract_type_id),start=Object.hasOwn(b,'startDate')?date(b.startDate,'Date de début'):String(current.start_date),end=Object.hasOwn(b,'endDate')?optionalDate(b.endDate,'Date de fin'):current.contractual_end_date==null?null:String(current.contractual_end_date);if(end&&end<start)throw new HttpError(400,'La date de fin doit suivre la date de début.');const[types]=await c.execute<RowDataPacket[]>('SELECT * FROM employee_contract_types WHERE id=? AND concession_id=? AND is_active=TRUE FOR UPDATE',[typeId,current.concession_id]),type=types[0];if(!type)throw new HttpError(409,'Type de contrat actif introuvable.');try{await c.execute('UPDATE employee_contracts SET contract_type_id=?,type_code_snapshot=?,type_name_snapshot=?,reference=?,start_date=?,contractual_end_date=?,updated_by=? WHERE id=?',[typeId,type.code,type.name,reference(Object.hasOwn(b,'reference')?b.reference:current.reference),start,end,r.user!.sub,contractId])}catch(error:any){if(error?.code==='ER_DUP_ENTRY')throw new HttpError(409,'Référence contrat déjà utilisée.');throw error}await audit(c,r,'employee_contract',contractId,'contract.draft.updated',{typeId,startDate:start,endDate:end});return current.agency_id==null?null:String(current.agency_id)});event(String((await getContract(r,'hr.contract.manage',contractId)).employee_profile_id),agencyId,'updated');res.json({success:true})}));
hrContractRouter.post('/hr/contracts/:id/activate',requirePermission('hr.contract.manage'),asyncHandler(async(r,res)=>{const contractId=id(r.params.id);const out=await transaction(async c=>{const current=await getContract(r,'hr.contract.manage',contractId,c,true),employee=await lockEmployee(c,r,'hr.contract.manage',String(current.employee_profile_id));if(current.status!=='DRAFT')throw new HttpError(409,'Seul un brouillon peut être activé.');if(employee.employment_status!=='active')throw new HttpError(409,'Un contrat ne peut être activé que pour un employé actif.');const[types]=await c.execute<RowDataPacket[]>('SELECT is_active FROM employee_contract_types WHERE id=? FOR UPDATE',[current.contract_type_id]);if(!types[0]?.is_active)throw new HttpError(409,'Le type de contrat est désactivé.');await assertNoOverlap(c,String(current.employee_profile_id),String(current.start_date),current.contractual_end_date==null?null:String(current.contractual_end_date),contractId);await c.execute("UPDATE employee_contracts SET status='ACTIVE',activated_at=NOW(),updated_by=? WHERE id=?",[r.user!.sub,contractId]);await audit(c,r,'employee_contract',contractId,'contract.activated',{employeeId:String(current.employee_profile_id)});return{employeeId:String(current.employee_profile_id),agencyId:current.agency_id==null?null:String(current.agency_id)}});event(out.employeeId,out.agencyId,'activated');res.json({success:true})}));
hrContractRouter.post('/hr/contracts/:id/end',requirePermission('hr.contract.manage'),asyncHandler(async(r,res)=>{const contractId=id(r.params.id),endDate=date(r.body.effectiveEndDate,'Date de fin effective'),reason=text(r.body.reason,'Motif',true,1000)!;const out=await transaction(async c=>{const current=await getContract(r,'hr.contract.manage',contractId,c,true);await lockEmployee(c,r,'hr.contract.manage',String(current.employee_profile_id));if(current.status!=='ACTIVE')throw new HttpError(409,'Seul un contrat actif peut être terminé.');if(endDate<String(current.start_date)||current.contractual_end_date&&endDate>String(current.contractual_end_date))throw new HttpError(400,'Date de fin effective hors période contractuelle.');await c.execute("UPDATE employee_contracts SET status='ENDED',effective_end_date=?,end_reason=?,ended_at=NOW(),updated_by=? WHERE id=?",[endDate,reason,r.user!.sub,contractId]);await audit(c,r,'employee_contract',contractId,'contract.ended',{effectiveEndDate:endDate,reason});return{employeeId:String(current.employee_profile_id),agencyId:current.agency_id==null?null:String(current.agency_id)}});event(out.employeeId,out.agencyId,'ended');res.json({success:true})}));
hrContractRouter.post('/hr/contracts/:id/cancel',requirePermission('hr.contract.manage'),asyncHandler(async(r,res)=>{const contractId=id(r.params.id),reason=text(r.body.reason,'Motif',true,1000)!;const out=await transaction(async c=>{const current=await getContract(r,'hr.contract.manage',contractId,c,true);await lockEmployee(c,r,'hr.contract.manage',String(current.employee_profile_id));if(current.status!=='DRAFT')throw new HttpError(409,'Seul un brouillon peut être annulé.');await c.execute("UPDATE employee_contracts SET status='CANCELLED',cancellation_reason=?,cancelled_at=NOW(),updated_by=? WHERE id=?",[reason,r.user!.sub,contractId]);await audit(c,r,'employee_contract',contractId,'contract.cancelled',{reason});return{employeeId:String(current.employee_profile_id),agencyId:current.agency_id==null?null:String(current.agency_id)}});event(out.employeeId,out.agencyId,'cancelled');res.json({success:true})}));
hrContractRouter.post('/hr/contracts/:id/renew',requirePermission('hr.contract.manage'),asyncHandler(async(r,res)=>{const previousId=id(r.params.id),b=r.body as Input,start=date(b.startDate,'Date de début'),end=optionalDate(b.endDate,'Date de fin');if(end&&end<start)throw new HttpError(400,'La date de fin doit suivre la date de début.');const out=await transaction(async c=>{const previous=await getContract(r,'hr.contract.manage',previousId,c,true);await lockEmployee(c,r,'hr.contract.manage',String(previous.employee_profile_id));if(!['ACTIVE','ENDED'].includes(String(previous.status)))throw new HttpError(409,'Ce contrat ne peut pas être renouvelé.');const typeId=optionalId(b.contractTypeId)??String(previous.contract_type_id),[types]=await c.execute<RowDataPacket[]>('SELECT * FROM employee_contract_types WHERE id=? AND concession_id=? AND is_active=TRUE FOR UPDATE',[typeId,previous.concession_id]),type=types[0];if(!type)throw new HttpError(409,'Type de contrat actif introuvable.');try{const[result]=await c.execute<ResultSetHeader>("INSERT INTO employee_contracts(employee_profile_id,concession_id,contract_type_id,type_code_snapshot,type_name_snapshot,reference,start_date,contractual_end_date,status,previous_contract_id,created_by,updated_by) VALUES(?,?,?,?,?,?,?,?, 'DRAFT',?,?,?)",[previous.employee_profile_id,previous.concession_id,typeId,type.code,type.name,reference(b.reference),start,end,previousId,r.user!.sub,r.user!.sub]);await audit(c,r,'employee_contract',String(result.insertId),'contract.renewed',{previousContractId:previousId});return{id:String(result.insertId),employeeId:String(previous.employee_profile_id),agencyId:previous.agency_id==null?null:String(previous.agency_id)}}catch(error:any){if(error?.code==='ER_DUP_ENTRY')throw new HttpError(409,'Ce contrat a déjà été renouvelé ou la référence existe déjà.');throw error}});event(out.employeeId,out.agencyId,'renewed');res.status(201).json({id:out.id})}));
