import React, { useEffect, useMemo, useState } from 'react';
import { Car, Check, ChevronLeft, ChevronRight, FileCheck2, User } from 'lucide-react';
import { useCreateSale, useCustomersQuery, useUsersQuery, useVehiclesQuery } from '../../api/erpHooks';
import { useAuthStore } from '../../stores/authStore';
import { useUiStore } from '../../stores/uiStore';
import { Modal } from '../../components/ui/Modal';
import { Button } from '../../components/ui/Button';
import { formatCurrency } from '../../lib/utils';
import { Badge } from '../../components/ui/Badge';

interface Props { isOpen:boolean;onClose:()=>void;initialCustomerId?:string;initialVehicleId?:string }
const input='w-full rounded-md border border-slate-300 bg-white p-2.5 text-xs';
export const SaleWizardModal:React.FC<Props>=({isOpen,onClose,initialCustomerId,initialVehicleId})=>{
 const auth=useAuthStore(),toast=useUiStore(s=>s.addToast),createSale=useCreateSale();
 const customersQuery=useCustomersQuery(),vehiclesQuery=useVehiclesQuery(),usersQuery=useUsersQuery(),agencyId=auth.currentAgency?.id??'';
 const customers=useMemo(()=>customersQuery.data?.filter(c=>c.agencyId===agencyId)??[],[customersQuery.data,agencyId]);
 const vehicles=useMemo(()=>vehiclesQuery.data?.filter(v=>v.agencyId===agencyId&&v.status==='DISPONIBLE')??[],[vehiclesQuery.data,agencyId]);
 const salespeople=useMemo(()=>usersQuery.data?.filter(u=>u.agencyId===agencyId&&u.status==='active'&&u.roles.some(r=>['SALES_REP','SALES_MANAGER','DIRECTION','SUPER_ADMIN'].includes(r)))??[],[usersQuery.data,agencyId]);
 const[step,setStep]=useState(1),[customerId,setCustomerId]=useState(''),[vehicleId,setVehicleId]=useState(''),[salespersonId,setSalespersonId]=useState(''),[discount,setDiscount]=useState(0),[depositAmount,setDepositAmount]=useState(0),[notes,setNotes]=useState(''),[idempotencyKey,setIdempotencyKey]=useState('');
 useEffect(()=>{if(!isOpen)return;setStep(1);setCustomerId(initialCustomerId&&customers.some(c=>c.id===initialCustomerId)?initialCustomerId:'');setVehicleId(initialVehicleId&&vehicles.some(v=>v.id===initialVehicleId)?initialVehicleId:'');setSalespersonId(salespeople.some(u=>u.id===auth.currentUser?.id)?auth.currentUser!.id:(salespeople[0]?.id??''));setDiscount(0);setDepositAmount(0);setNotes('');setIdempotencyKey(crypto.randomUUID())},[isOpen,initialCustomerId,initialVehicleId,customers,salespeople,vehicles,auth.currentUser]);
 const customer=customers.find(c=>c.id===customerId),vehicle=vehicles.find(v=>v.id===vehicleId),vehiclePrice=vehicle?.sellingPriceTTC??0,total=Math.max(0,vehiclePrice-discount),balance=Math.max(0,total-depositAmount);
 const validAmounts=Number.isFinite(discount)&&Number.isFinite(depositAmount)&&discount>=0&&discount<=vehiclePrice&&depositAmount>=0&&depositAmount<=total;
 const canContinue=step===1?Boolean(customerId):step===2?Boolean(vehicleId):step===3?Boolean(salespersonId)&&validAmounts:true;
 const finish=async()=>{if(!customer||!vehicle||!agencyId||!salespersonId||!validAmounts)return;try{await createSale.mutateAsync({customerId:customer.id,vehicleId:vehicle.id,agencyId,salespersonId,discount,depositAmount,notes:notes.trim(),idempotencyKey});toast({type:'success',title:'Vente enregistrée',description:`Le véhicule ${vehicle.stockNumber} est maintenant réservé.`});onClose()}catch(error){toast({type:'error',title:'Vente non enregistrée',description:error instanceof Error?error.message:'Erreur API'})}};
 const loading=customersQuery.isLoading||vehiclesQuery.isLoading||usersQuery.isLoading,error=customersQuery.error||vehiclesQuery.error||usersQuery.error;
 return <Modal isOpen={isOpen} onClose={onClose} title="Créer une vente automobile" description="Les prix sont revalidés par le backend avant réservation du véhicule." maxWidth="2xl"><div className="space-y-5">
  <div className="flex justify-between border-b pb-3">{['Client','Véhicule','Conditions','Validation'].map((label,index)=><div key={label} className={`flex items-center gap-1 text-xs ${step===index+1?'font-bold text-[#8f1722]':'text-slate-500'}`}><span className={`flex h-6 w-6 items-center justify-center rounded-full ${step>index+1?'bg-emerald-600 text-white':step===index+1?'bg-[#8f1722] text-white':'bg-slate-100'}`}>{step>index+1?<Check className="h-3 w-3"/>:index+1}</span><span className="hidden sm:inline">{label}</span></div>)}</div>
  {loading&&<p className="py-8 text-center text-sm text-slate-500">Chargement des données métier…</p>}{error&&<p className="rounded-md border border-red-200 bg-red-50 p-3 text-sm text-red-700">{error.message}</p>}
  {!loading&&!error&&step===1&&<section className="space-y-3"><h3 className="flex items-center gap-2 text-sm font-bold"><User className="h-4 w-4"/>Client de l’agence</h3>{!customers.length?<p className="rounded-md border border-dashed p-6 text-center text-sm text-slate-500">Aucun client disponible pour cette agence.</p>:<div className="max-h-64 space-y-2 overflow-y-auto">{customers.map(c=><button type="button" key={c.id} onClick={()=>setCustomerId(c.id)} className={`flex w-full justify-between rounded-md border p-3 text-left text-xs ${customerId===c.id?'border-[#8f1722] bg-red-50':'border-slate-200'}`}><span><b>{c.company||`${c.firstName} ${c.lastName}`}</b><br/><span className="text-slate-500">{c.phone||c.email||c.code}</span></span>{customerId===c.id&&<Badge variant="primary">Sélectionné</Badge>}</button>)}</div>}</section>}
  {!loading&&!error&&step===2&&<section className="space-y-3"><h3 className="flex items-center gap-2 text-sm font-bold"><Car className="h-4 w-4"/>Véhicule disponible</h3>{!vehicles.length?<p className="rounded-md border border-amber-200 bg-amber-50 p-6 text-center text-sm text-amber-800">Aucun véhicule disponible dans cette agence. Le bouton Suivant reste désactivé.</p>:<div className="max-h-64 space-y-2 overflow-y-auto">{vehicles.map(v=><button type="button" key={v.id} onClick={()=>setVehicleId(v.id)} className={`flex w-full items-center justify-between rounded-md border p-3 text-left text-xs ${vehicleId===v.id?'border-[#8f1722] bg-red-50':'border-slate-200'}`}><span><b>{v.brand} {v.model} {v.version}</b><br/><span className="text-slate-500">{v.stockNumber} · VIN {v.vin}</span></span><b>{formatCurrency(v.sellingPriceTTC)}</b></button>)}</div>}</section>}
  {!loading&&!error&&step===3&&<section className="grid gap-4 sm:grid-cols-2"><label className="text-xs font-semibold sm:col-span-2">Commercial actif<select required className={`${input} mt-1`} value={salespersonId} onChange={e=>setSalespersonId(e.target.value)}><option value="">Choisir un commercial</option>{salespeople.map(u=><option key={u.id} value={u.id}>{u.name}</option>)}</select></label><label className="text-xs font-semibold">Remise commerciale XAF<input className={`${input} mt-1`} type="number" min="0" max={vehiclePrice} step="1" value={discount} onChange={e=>setDiscount(Number(e.target.value))}/></label><label className="text-xs font-semibold">Acompte commercial XAF<input className={`${input} mt-1`} type="number" min="0" max={total} step="1" value={depositAmount} onChange={e=>setDepositAmount(Number(e.target.value))}/></label><label className="text-xs font-semibold sm:col-span-2">Notes<textarea className={`${input} mt-1 min-h-20`} maxLength={10000} value={notes} onChange={e=>setNotes(e.target.value)} placeholder="Conditions particulières éventuelles"/></label>{!validAmounts&&<p className="text-xs text-red-700 sm:col-span-2">La remise ou l’acompte dépasse le montant autorisé.</p>}</section>}
  {!loading&&!error&&step===4&&<section className="space-y-4"><h3 className="flex items-center gap-2 text-sm font-bold"><FileCheck2 className="h-4 w-4"/>Vérification finale</h3><div className="grid gap-3 rounded-md border bg-slate-50 p-4 text-xs sm:grid-cols-2"><p>Client<br/><b>{customer?.company||`${customer?.firstName??''} ${customer?.lastName??''}`}</b></p><p>Véhicule<br/><b>{vehicle?.brand} {vehicle?.model}</b></p><p>Commercial<br/><b>{salespeople.find(u=>u.id===salespersonId)?.name}</b></p><p>Agence<br/><b>{auth.currentAgency?.name}</b></p><p>Prix véhicule<br/><b>{formatCurrency(vehiclePrice)}</b></p><p>Remise<br/><b>-{formatCurrency(discount)}</b></p><p>Total commercial<br/><b>{formatCurrency(total)}</b></p><p>Solde commercial<br/><b>{formatCurrency(balance)}</b></p></div><p className="text-xs text-slate-500">L’acompte est une donnée commerciale. Son encaissement comptable reste géré dans Facturation.</p></section>}
  <div className="flex justify-between border-t pt-4"><Button type="button" variant="outline" icon={<ChevronLeft className="h-4 w-4"/>} disabled={step===1||createSale.isPending} onClick={()=>setStep(x=>x-1)}>Retour</Button>{step<4?<Button type="button" icon={<ChevronRight className="h-4 w-4"/>} iconPosition="right" disabled={!canContinue||loading} onClick={()=>setStep(x=>x+1)}>Suivant</Button>:<Button type="button" loading={createSale.isPending} disabled={!customer||!vehicle||!salespersonId||!validAmounts} onClick={()=>void finish()}>Enregistrer la vente</Button>}</div>
 </div></Modal>
};
