import type {PoolConnection,RowDataPacket} from 'mysql2/promise';
import {query} from '../../config/database.js';
import {HttpError} from '../../shared/http-error.js';
import type {WarrantySelection} from './sale.domain.js';

export async function proposal(vehicleId:string){const[vehicle]=await query<RowDataPacket[]>(`SELECT wp.id provider_id,wp.code provider_code,wp.name provider_name,wp.default_warranty_months duration_months,wp.default_mileage_limit mileage_limit FROM vehicles v JOIN versions ve ON ve.id=v.version_id JOIN models m ON m.id=ve.model_id JOIN brands b ON b.id=m.brand_id LEFT JOIN warranty_providers wp ON wp.id=b.warranty_provider_id AND wp.is_active=TRUE AND wp.warranty_available=TRUE WHERE v.id=?`,[vehicleId]);if(!vehicle)throw new HttpError(404,'Véhicule introuvable');return vehicle.provider_id?{applicable:true,providerId:String(vehicle.provider_id),providerCode:vehicle.provider_code,providerName:vehicle.provider_name,durationMonths:Number(vehicle.duration_months),mileageLimit:vehicle.mileage_limit==null?null:Number(vehicle.mileage_limit)}:{applicable:false,providerId:null,providerCode:null,providerName:null,durationMonths:null,mileageLimit:null}}

export async function createSnapshot(connection:PoolConnection,input:{saleId:string;vehicleId:string;customerId:string;selection:WarrantySelection;userId:string}){const{saleId,vehicleId,customerId,selection,userId}=input;if(selection.decision==='APPLICABLE'){const[rows]=await connection.execute<RowDataPacket[]>(`SELECT wp.id,wp.code,wp.name FROM vehicles v JOIN versions ve ON ve.id=v.version_id JOIN models m ON m.id=ve.model_id JOIN brands b ON b.id=m.brand_id JOIN warranty_providers wp ON wp.id=b.warranty_provider_id WHERE v.id=? AND wp.is_active=TRUE AND wp.warranty_available=TRUE FOR UPDATE`,[vehicleId]),provider=rows[0];if(!provider)throw new HttpError(409,"Aucun constructeur actif n’est paramétré pour la garantie de ce véhicule");await connection.execute(`INSERT INTO vehicle_warranty_contracts(sale_id,vehicle_id,customer_id,provider_id,decision,status,provider_code_snapshot,provider_name_snapshot,duration_months,mileage_limit,decision_at,decided_by,created_by) VALUES(?,?,?,?,'APPLICABLE','PENDING_ACTIVATION',?,?,?,?,NOW(),?,?)`,[saleId,vehicleId,customerId,provider.id,provider.code,provider.name,selection.durationMonths,selection.mileageLimit??null,userId,userId]);return}const status=selection.decision==='NOT_APPLICABLE'?'NOT_APPLICABLE':'PENDING_DECISION';await connection.execute(`INSERT INTO vehicle_warranty_contracts(sale_id,vehicle_id,customer_id,decision,status,decision_at,decided_by,created_by) VALUES(?,?,?,?,?,IF(?='UNDETERMINED',NULL,NOW()),IF(?='UNDETERMINED',NULL,?),?)`,[saleId,vehicleId,customerId,selection.decision,status,selection.decision,selection.decision,userId,userId])}

export async function activateAtDelivery(connection:PoolConnection,input:{saleId:string;vehicleId:string;mileage:number;signedAt:string;userId:string}){const[rows]=await connection.execute<RowDataPacket[]>('SELECT * FROM vehicle_warranty_contracts WHERE sale_id=? AND vehicle_id=? FOR UPDATE',[input.saleId,input.vehicleId]),contract=rows[0];if(!contract||contract.decision==='UNDETERMINED')throw new HttpError(409,'La décision de garantie doit être renseignée avant la livraison');if(contract.decision==='NOT_APPLICABLE')return;if(contract.status==='ACTIVE')return;if(contract.status!=='PENDING_ACTIVATION')throw new HttpError(409,'Le contrat de garantie ne peut pas être activé');await connection.execute(`UPDATE vehicle_warranty_contracts SET status='ACTIVE',start_date=?,expiry_date=DATE_ADD(?,INTERVAL duration_months MONTH),initial_mileage=?,activated_at=?,activated_by=?,updated_by=? WHERE id=? AND status='PENDING_ACTIVATION'`,[input.signedAt,input.signedAt,input.mileage,input.signedAt,input.userId,input.userId,contract.id])}

export async function updateSnapshot(connection:PoolConnection,input:{saleId:string;vehicleId:string;selection:WarrantySelection;userId:string}){const[rows]=await connection.execute<RowDataPacket[]>('SELECT id,status FROM vehicle_warranty_contracts WHERE sale_id=? FOR UPDATE',[input.saleId]),contract=rows[0];if(!contract)throw new HttpError(404,'Contrat de garantie introuvable');if(contract.status==='ACTIVE')throw new HttpError(409,'Une garantie activée est immuable');if(input.selection.decision==='APPLICABLE'){const[providers]=await connection.execute<RowDataPacket[]>(`SELECT wp.id,wp.code,wp.name FROM vehicles v JOIN versions ve ON ve.id=v.version_id JOIN models m ON m.id=ve.model_id JOIN brands b ON b.id=m.brand_id JOIN warranty_providers wp ON wp.id=b.warranty_provider_id WHERE v.id=? AND wp.is_active=TRUE AND wp.warranty_available=TRUE FOR UPDATE`,[input.vehicleId]),provider=providers[0];if(!provider)throw new HttpError(409,"Aucun constructeur actif n’est paramétré pour la garantie de ce véhicule");await connection.execute(`UPDATE vehicle_warranty_contracts SET provider_id=?,decision='APPLICABLE',status='PENDING_ACTIVATION',provider_code_snapshot=?,provider_name_snapshot=?,duration_months=?,mileage_limit=?,decision_at=NOW(),decided_by=?,updated_by=? WHERE id=?`,[provider.id,provider.code,provider.name,input.selection.durationMonths,input.selection.mileageLimit??null,input.userId,input.userId,contract.id]);return}const status=input.selection.decision==='NOT_APPLICABLE'?'NOT_APPLICABLE':'PENDING_DECISION';await connection.execute(`UPDATE vehicle_warranty_contracts SET provider_id=NULL,decision=?,status=?,provider_code_snapshot=NULL,provider_name_snapshot=NULL,duration_months=NULL,mileage_limit=NULL,decision_at=IF(?='UNDETERMINED',NULL,NOW()),decided_by=IF(?='UNDETERMINED',NULL,?),updated_by=? WHERE id=?`,[input.selection.decision,status,input.selection.decision,input.selection.decision,input.userId,input.userId,contract.id])}
