import { Router, type Request } from 'express';
import type { ResultSetHeader, RowDataPacket } from 'mysql2/promise';
import { execute, query, transaction } from '../../config/database.js';
import { authorize, unrestricted } from '../../middleware/authorize.js';
import { asyncHandler } from '../../middleware/error-handler.js';
import { emitToAgency } from '../../realtime/socket.js';
import { HttpError } from '../../shared/http-error.js';
import { createUserNotification } from '../notifications/notification.service.js';

export const showroomRouter=Router();
const READ=['SUPER_ADMIN','DIRECTOR','SALES_MANAGER','SALES_AGENT','RECEPTIONIST','DELIVERY_MANAGER'];
const RECEPTION=['SUPER_ADMIN','DIRECTOR','SALES_MANAGER','RECEPTIONIST'];
const COMMERCIAL=['SUPER_ADMIN','DIRECTOR','SALES_MANAGER','SALES_AGENT'];
const statuses=['waiting','assigned','in_progress','completed','cancelled'];
const outcomes=['pending','lead_created','quotation','sale','no_interest','follow_up'];
const idOf=(value:string|string[]|undefined)=>{const id=Array.isArray(value)?value[0]:value;if(!id||!/^[1-9]\d*$/.test(id))throw new HttpError(400,'Identifiant invalide');return id};
const text=(value:unknown,name:string,max=255,required=false)=>{const result=String(value??'').trim();if(required&&!result)throw new HttpError(400,`${name} est requis`);if(result.length>max)throw new HttpError(400,`${name} est trop long`);return result||null};
const normalizedPhone=(value:unknown)=>String(value??'').replace(/\D/g,'');
const has=(request:Request,roles:string[])=>request.user!.roles.some(role=>roles.includes(role));
const agencyId=(request:Request,requested?:unknown)=>{if(unrestricted(request)&&requested)return String(requested);if(!request.user?.agencyId)throw new HttpError(403,'Aucune agence associée');return request.user.agencyId};
const scope=(request:Request,alias='sv')=>unrestricted(request)?{sql:'1=1',params:[] as unknown[]}:{sql:`${alias}.agency_id=?`,params:[request.user!.agencyId]};
const visitSelect=`SELECT sv.*,CONCAT_WS(' ',assignee.first_name,assignee.last_name) assigned_user_name,CONCAT_WS(' ',greeter.first_name,greeter.last_name) greeted_by_name,c.customer_code,l.first_name lead_first_name,l.last_name lead_last_name,CONCAT(b.name,' ',m.name,' ',ve.name) vehicle_label,v.vin,v.registration_number,TIMESTAMPDIFF(MINUTE,sv.arrival_at,COALESCE(sv.assigned_at,NOW())) wait_minutes,(SELECT td.id FROM showroom_test_drives td WHERE td.visit_id=sv.id AND td.status='in_progress' ORDER BY td.started_at DESC LIMIT 1) active_test_drive_id,(SELECT td.mileage_out FROM showroom_test_drives td WHERE td.visit_id=sv.id AND td.status='in_progress' ORDER BY td.started_at DESC LIMIT 1) active_test_drive_mileage FROM showroom_visits sv LEFT JOIN users assignee ON assignee.id=sv.assigned_user_id LEFT JOIN users greeter ON greeter.id=sv.greeted_by LEFT JOIN customers c ON c.id=sv.customer_id LEFT JOIN leads l ON l.id=sv.lead_id LEFT JOIN vehicles v ON v.id=sv.vehicle_id LEFT JOIN versions ve ON ve.id=v.version_id LEFT JOIN models m ON m.id=ve.model_id LEFT JOIN brands b ON b.id=m.brand_id`;
const mapVisit=(r:RowDataPacket)=>({id:String(r.id),customerId:r.customer_id==null?null:String(r.customer_id),leadId:r.lead_id==null?null:String(r.lead_id),visitorName:r.visitor_name,phone:r.phone,reason:r.reason,preferredModel:r.preferred_model,vehicleId:r.vehicle_id==null?null:String(r.vehicle_id),vehicleLabel:r.vehicle_label,assignedUserId:r.assigned_user_id==null?null:String(r.assigned_user_id),assignedUserName:r.assigned_user_name,greetedById:r.greeted_by==null?null:String(r.greeted_by),greetedByName:r.greeted_by_name,agencyId:String(r.agency_id),queueNumber:r.queue_number,status:r.status,outcome:r.outcome,arrivalAt:r.arrival_at,assignedAt:r.assigned_at,completedAt:r.completed_at,cancellationReason:r.cancellation_reason,notes:r.notes,waitMinutes:Number(r.wait_minutes??0),activeTestDriveId:r.active_test_drive_id==null?null:String(r.active_test_drive_id),activeTestDriveMileage:r.active_test_drive_mileage==null?null:Number(r.active_test_drive_mileage)});
async function accessible(id:string,request:Request){const scoped=scope(request);const[row]=await query<RowDataPacket[]>(`${visitSelect} WHERE sv.id=? AND ${scoped.sql}`,[id,...scoped.params]);if(!row)throw new HttpError(404,'Visite showroom introuvable');return row}
async function validAssignee(id:string,agency:string){const[row]=await query<RowDataPacket[]>(`SELECT u.id FROM users u JOIN user_roles ur ON ur.user_id=u.id JOIN roles r ON r.id=ur.role_id WHERE u.id=? AND u.agency_id=? AND u.is_active=TRUE AND r.code IN ('SALES_AGENT','SALES_MANAGER') LIMIT 1`,[id,agency]);if(!row)throw new HttpError(400,'Conseiller commercial invalide ou rattaché à une autre agence')}
async function notify(agency:string,event:string,visitId:string,subject:string,message:string,userId?:string|null){emitToAgency(agency,event,{visitId});if(userId)try{await createUserNotification({userId,subject,message,eventType:event==='showroom:assigned'?'showroom.visitor_assigned':event.replace(':','.'),referenceType:'showroom',referenceId:visitId,priority:'normal'})}catch(error){console.error('Notification showroom non créée',error)}}

showroomRouter.patch('/showroom/test-drives/:id/cancel',authorize(...COMMERCIAL),asyncHandler(async(request,response)=>{const id=idOf(request.params.id);const[row]=await query<RowDataPacket[]>(`SELECT td.*,sv.visitor_name FROM showroom_test_drives td JOIN showroom_visits sv ON sv.id=td.visit_id WHERE td.id=? AND ${unrestricted(request)?'1=1':'td.agency_id=?'}`,[id,...(unrestricted(request)?[]:[request.user!.agencyId])]);if(!row)throw new HttpError(404,'Essai introuvable');if(row.status!=='in_progress')throw new HttpError(409,'Essai non actif');if(String(row.advisor_id)!==request.user!.sub&&!has(request,['SALES_MANAGER','DIRECTOR','SUPER_ADMIN']))throw new HttpError(403,'Cet essai appartient à un autre conseiller');const reason=text(request.body.reason,'Motif',255,true)!;await execute(`UPDATE showroom_test_drives SET status='cancelled',returned_at=NOW(),internal_notes=? WHERE id=?`,[reason,id]);await notify(String(row.agency_id),'showroom:test-drive-cancelled',String(row.visit_id),'Essai routier annulé',`${row.visitor_name}: ${reason}`);response.json({success:true});}));

showroomRouter.get('/showroom/detect',authorize(...READ),asyncHandler(async(request,response)=>{const phone=normalizedPhone(request.query.phone);if(phone.length<6)throw new HttpError(400,'Saisissez au moins 6 chiffres');const agency=agencyId(request,request.query.agencyId);const term=`%${phone}%`;const [customers,leads,recentVisits]=await Promise.all([query<RowDataPacket[]>(`SELECT id,customer_code,first_name,last_name,company_name,phone FROM customers WHERE agency_id=? AND REPLACE(REPLACE(REPLACE(REPLACE(phone,' ',''),'-',''),'.',''),'+','') LIKE ? LIMIT 10`,[agency,term]),query<RowDataPacket[]>(`SELECT l.id,l.first_name,l.last_name,l.company_name,l.phone,l.assigned_user_id FROM leads l LEFT JOIN users u ON u.id=l.assigned_user_id WHERE u.agency_id=? AND REPLACE(REPLACE(REPLACE(REPLACE(l.phone,' ',''),'-',''),'.',''),'+','') LIKE ? LIMIT 10`,[agency,term]),query<RowDataPacket[]>(`SELECT id,visitor_name,phone,status,arrival_at FROM showroom_visits WHERE agency_id=? AND REPLACE(REPLACE(REPLACE(REPLACE(phone,' ',''),'-',''),'.',''),'+','') LIKE ? AND arrival_at>DATE_SUB(NOW(),INTERVAL 90 DAY) ORDER BY arrival_at DESC LIMIT 10`,[agency,term])]);response.json({customers,leads,recentVisits});}));

showroomRouter.get('/showroom',authorize(...READ),asyncHandler(async(request,response)=>{const scoped=scope(request);const date=typeof request.query.date==='string'?request.query.date:new Date().toISOString().slice(0,10);if(!/^\d{4}-\d{2}-\d{2}$/.test(date))throw new HttpError(400,'Date invalide');const rows=await query<RowDataPacket[]>(`${visitSelect} WHERE ${scoped.sql} AND DATE(sv.arrival_at)=? ORDER BY FIELD(sv.status,'waiting','assigned','in_progress','completed','cancelled'),sv.arrival_at`,[...scoped.params,date]);const visits=rows.map(mapVisit);const completed=visits.filter(v=>v.status==='completed');const transformed=completed.filter(v=>['lead_created','quotation','sale'].includes(v.outcome)).length;response.json({visits,metrics:{total:visits.length,waiting:visits.filter(v=>v.status==='waiting').length,inProgress:visits.filter(v=>['assigned','in_progress'].includes(v.status)).length,completed:completed.length,averageWaitMinutes:visits.filter(v=>v.assignedAt).length?Math.round(visits.filter(v=>v.assignedAt).reduce((sum,v)=>sum+v.waitMinutes,0)/visits.filter(v=>v.assignedAt).length):0,activeAdvisors:new Set(visits.filter(v=>['assigned','in_progress'].includes(v.status)).map(v=>v.assignedUserId).filter(Boolean)).size,conversionRate:completed.length?Math.round(transformed/completed.length*100):0,quotations:completed.filter(v=>v.outcome==='quotation').length}});}));

showroomRouter.get('/showroom/:id',authorize(...READ),asyncHandler(async(request,response)=>{const row=await accessible(idOf(request.params.id),request);const drives=await query<RowDataPacket[]>(`SELECT td.*,CONCAT(b.name,' ',m.name,' ',ve.name) vehicle_label,v.vin,v.registration_number,CONCAT_WS(' ',u.first_name,u.last_name) advisor_name FROM showroom_test_drives td JOIN vehicles v ON v.id=td.vehicle_id JOIN versions ve ON ve.id=v.version_id JOIN models m ON m.id=ve.model_id JOIN brands b ON b.id=m.brand_id JOIN users u ON u.id=td.advisor_id WHERE td.visit_id=? ORDER BY td.created_at DESC`,[row.id]);response.json({visit:mapVisit(row),testDrives:drives});}));

showroomRouter.post('/showroom',authorize(...RECEPTION),asyncHandler(async(request,response)=>{const body=request.body as Record<string,unknown>,name=text(body.visitorName,'Nom du visiteur',200,true)!,phone=text(body.phone,'Téléphone',50),reason=text(body.reason,'Motif',255,true)!,preferred=text(body.preferredModel,'Modèle recherché',200),agency=agencyId(request,body.agencyId);const customerId=body.customerId?idOf(String(body.customerId)):null,leadId=body.leadId?idOf(String(body.leadId)):null,vehicleId=body.vehicleId?idOf(String(body.vehicleId)):null;if(customerId){const[c]=await query<RowDataPacket[]>('SELECT id FROM customers WHERE id=? AND agency_id=?',[customerId,agency]);if(!c)throw new HttpError(400,'Client invalide pour cette agence')}if(leadId){const[l]=await query<RowDataPacket[]>('SELECT l.id FROM leads l LEFT JOIN users u ON u.id=l.assigned_user_id WHERE l.id=? AND u.agency_id=?',[leadId,agency]);if(!l)throw new HttpError(400,'Prospect invalide pour cette agence')}const created=await transaction(async connection=>{const[number]=await connection.execute<RowDataPacket[]>('SELECT COALESCE(MAX(queue_number),0)+1 next_number FROM showroom_visits WHERE agency_id=? AND DATE(arrival_at)=CURDATE() FOR UPDATE',[agency]);const[result]=await connection.execute<ResultSetHeader>(`INSERT INTO showroom_visits(customer_id,lead_id,visitor_name,phone,reason,preferred_model,vehicle_id,greeted_by,agency_id,queue_number,status) VALUES(?,?,?,?,?,?,?,?,?,?,'waiting')`,[customerId,leadId,name,phone,reason,preferred,vehicleId,request.user!.sub,agency,number[0]?.next_number??1]);return String(result.insertId)});await notify(agency,'showroom:visitor-created',created,'Nouveau visiteur showroom',`${name} attend une prise en charge`);response.status(201).json(mapVisit(await accessible(created,request)));}));

showroomRouter.patch('/showroom/:id/assign',authorize(...RECEPTION),asyncHandler(async(request,response)=>{const id=idOf(request.params.id),visit=await accessible(id,request),assignee=idOf(String(request.body.assignedUserId));if(!['waiting','assigned'].includes(visit.status))throw new HttpError(409,'Cette visite ne peut plus être affectée');await validAssignee(assignee,String(visit.agency_id));await execute(`UPDATE showroom_visits SET assigned_user_id=?,status='assigned',assigned_at=NOW() WHERE id=?`,[assignee,id]);await notify(String(visit.agency_id),'showroom:assigned',id,'Visiteur affecté',`${visit.visitor_name} vous a été affecté`,assignee);response.json(mapVisit(await accessible(id,request)));}));

showroomRouter.patch('/showroom/:id/take-over',authorize(...COMMERCIAL),asyncHandler(async(request,response)=>{const id=idOf(request.params.id),visit=await accessible(id,request);if(!['waiting','assigned'].includes(visit.status))throw new HttpError(409,'Visite déjà prise en charge ou terminée');await validAssignee(request.user!.sub,String(visit.agency_id));if(visit.assigned_user_id&&String(visit.assigned_user_id)!==request.user!.sub&&!has(request,['SALES_MANAGER','DIRECTOR','SUPER_ADMIN']))throw new HttpError(403,'Cette visite est affectée à un autre conseiller');await execute(`UPDATE showroom_visits SET assigned_user_id=?,status='in_progress',assigned_at=COALESCE(assigned_at,NOW()) WHERE id=?`,[request.user!.sub,id]);await notify(String(visit.agency_id),'showroom:takeover',id,'Visiteur pris en charge',`${visit.visitor_name} est maintenant en entretien`,request.user!.sub);response.json(mapVisit(await accessible(id,request)));}));

showroomRouter.patch('/showroom/:id/complete',authorize(...COMMERCIAL),asyncHandler(async(request,response)=>{const id=idOf(request.params.id),visit=await accessible(id,request),outcome=text(request.body.outcome,'Résultat',30,true)!;if(!outcomes.includes(outcome))throw new HttpError(400,'Résultat invalide');if(visit.status!=='in_progress')throw new HttpError(409,'Seule une visite en cours peut être clôturée');if(String(visit.assigned_user_id)!==request.user!.sub&&!has(request,['SALES_MANAGER','DIRECTOR','SUPER_ADMIN']))throw new HttpError(403,'Cette visite appartient à un autre conseiller');await execute(`UPDATE showroom_visits SET status='completed',outcome=?,completed_at=NOW(),notes=COALESCE(?,notes) WHERE id=?`,[outcome,text(request.body.notes,'Notes',5000),id]);await notify(String(visit.agency_id),'showroom:completed',id,'Visite clôturée',`${visit.visitor_name}: ${outcome}`);response.json(mapVisit(await accessible(id,request)));}));

showroomRouter.patch('/showroom/:id/cancel',authorize(...RECEPTION),asyncHandler(async(request,response)=>{const id=idOf(request.params.id),visit=await accessible(id,request),reason=text(request.body.reason,'Motif',255,true)!;if(['completed','cancelled'].includes(visit.status))throw new HttpError(409,'Visite déjà terminée');await execute(`UPDATE showroom_visits SET status='cancelled',cancellation_reason=?,completed_at=NOW() WHERE id=?`,[reason,id]);await notify(String(visit.agency_id),'showroom:cancelled',id,'Visite annulée',`${visit.visitor_name}: ${reason}`);response.json(mapVisit(await accessible(id,request)));}));

showroomRouter.post('/showroom/:id/test-drives',authorize(...COMMERCIAL),asyncHandler(async(request,response)=>{const visitId=idOf(request.params.id),visit=await accessible(visitId,request);if(visit.status!=='in_progress')throw new HttpError(409,'La visite doit être en cours');if(String(visit.assigned_user_id)!==request.user!.sub&&!has(request,['SALES_MANAGER','DIRECTOR','SUPER_ADMIN']))throw new HttpError(403,'Visite affectée à un autre conseiller');const vehicleId=idOf(String(request.body.vehicleId));const[vehicle]=await query<RowDataPacket[]>(`SELECT id,mileage,status,agency_id FROM vehicles WHERE id=? AND agency_id=? AND archived_at IS NULL`,[vehicleId,visit.agency_id]);if(!vehicle||!['available','reserved'].includes(vehicle.status))throw new HttpError(409,'Véhicule indisponible pour un essai');const mileage=Number(request.body.mileageOut??vehicle.mileage);if(!Number.isInteger(mileage)||mileage<Number(vehicle.mileage))throw new HttpError(400,'Kilométrage de départ invalide');const result=await execute(`INSERT INTO showroom_test_drives(visit_id,customer_id,lead_id,vehicle_id,agency_id,advisor_id,driver_name,driver_phone,license_number,mileage_out,status,started_at,created_by) VALUES(?,?,?,?,?,?,?,?,?,?,'in_progress',NOW(),?)`,[visitId,visit.customer_id,visit.lead_id,vehicleId,visit.agency_id,request.user!.sub,visit.visitor_name,visit.phone,text(request.body.licenseNumber,'Permis',100,true),mileage,request.user!.sub]);await execute('UPDATE showroom_visits SET vehicle_id=? WHERE id=?',[vehicleId,visitId]);await notify(String(visit.agency_id),'showroom:test-drive-started',visitId,'Essai routier démarré',`${visit.visitor_name} essaie le véhicule #${vehicleId}`);response.status(201).json({id:String(result.insertId)});}));

showroomRouter.patch('/showroom/test-drives/:id/complete',authorize(...COMMERCIAL),asyncHandler(async(request,response)=>{const id=idOf(request.params.id);const[row]=await query<RowDataPacket[]>(`SELECT td.*,sv.visitor_name FROM showroom_test_drives td JOIN showroom_visits sv ON sv.id=td.visit_id WHERE td.id=? AND ${unrestricted(request)?'1=1':'td.agency_id=?'}`,[id,...(unrestricted(request)?[]:[request.user!.agencyId])]);if(!row)throw new HttpError(404,'Essai introuvable');if(row.status!=='in_progress')throw new HttpError(409,'Essai non actif');const mileage=Number(request.body.mileageIn);if(!Number.isInteger(mileage)||mileage<Number(row.mileage_out))throw new HttpError(400,'Kilométrage de retour invalide');await transaction(async connection=>{await connection.execute(`UPDATE showroom_test_drives SET status='completed',mileage_in=?,returned_at=NOW(),customer_feedback=?,internal_notes=? WHERE id=?`,[mileage,text(request.body.customerFeedback,'Avis',5000),text(request.body.internalNotes,'Notes',5000),id]);await connection.execute('UPDATE vehicles SET mileage=GREATEST(mileage,?) WHERE id=?',[mileage,row.vehicle_id]);await connection.execute(`INSERT INTO activities(customer_id,lead_id,assigned_user_id,type,subject,description,status,completed_at) VALUES(?,?,?,'test_drive','Essai routier showroom',?,'completed',NOW())`,[row.customer_id,row.lead_id,row.advisor_id,text(request.body.customerFeedback,'Avis',5000)])});await notify(String(row.agency_id),'showroom:test-drive-completed',String(row.visit_id),'Essai routier terminé',`${row.visitor_name} a rendu le véhicule`);response.json({success:true});}));

showroomRouter.post('/showroom/:id/convert-to-lead',authorize(...COMMERCIAL),asyncHandler(async(request,response)=>{const visitId=idOf(request.params.id),visit=await accessible(visitId,request);if(visit.lead_id)return response.json({leadId:String(visit.lead_id),existing:true});const names=String(visit.visitor_name).trim().split(/\s+/),lastName=names.pop()!,firstName=names.join(' '),title=text(request.body.title,'Projet automobile',200)??visit.preferred_model??visit.reason;const created=await transaction(async connection=>{const[lead]=await connection.execute<ResultSetHeader>(`INSERT INTO leads(customer_id,assigned_user_id,created_by,source,status,priority,first_name,last_name,phone,notes) VALUES(?,?,?,'Passage Showroom','new','medium',?,?,?,?)`,[visit.customer_id,visit.assigned_user_id??request.user!.sub,request.user!.sub,firstName,lastName,visit.phone,`Visite showroom #${visitId}`]);await connection.execute<ResultSetHeader>(`INSERT INTO opportunities(lead_id,customer_id,assigned_user_id,title,stage,probability,notes) VALUES(?,?,?,?,'qualified',30,?)`,[lead.insertId,visit.customer_id,visit.assigned_user_id??request.user!.sub,title,`Créée depuis la visite showroom #${visitId}`]);await connection.execute(`UPDATE showroom_visits SET lead_id=?,outcome='lead_created' WHERE id=?`,[lead.insertId,visitId]);return String(lead.insertId)});await notify(String(visit.agency_id),'showroom:converted',visitId,'Prospect créé depuis le showroom',`${visit.visitor_name} est maintenant un prospect`,String(visit.assigned_user_id??request.user!.sub));response.status(201).json({leadId:created});}));
