import assert from'node:assert/strict';
import{after,before,test}from'node:test';
import type{PoolConnection,ResultSetHeader,RowDataPacket}from'mysql2/promise';
import{pool}from'../src/config/database.js';
import{bootstrapDatabase}from'../src/scripts/database-bootstrap.js';
import{createDeliveryChecklistSnapshot,lockAndAssertDeliveryChecklistComplete}from'../src/modules/deliveries/delivery-checklist.service.js';

const enabled=process.env.DELIVERY_CHECKLIST_CONCURRENCY_MYSQL_TEST==='1';
let sequence=0;
const wait=(ms=100)=>new Promise(resolve=>setTimeout(resolve,ms));
const insert=async(connection:PoolConnection,sql:string,args:unknown[]=[])=>String((await connection.execute<ResultSetHeader>(sql,args))[0].insertId);
async function tx<T>(work:(connection:PoolConnection)=>Promise<T>){const connection=await pool.getConnection();try{await connection.beginTransaction();const value=await work(connection);await connection.commit();return value}catch(error){await connection.rollback();throw error}finally{connection.release()}}
type Fixture={delivery:string;categoryA:string;categoryB:string;itemA:string;itemB:string;user:string};
async function fixture():Promise<Fixture>{return tx(async connection=>{const n=`${Date.now()}${sequence++}`,concession=await insert(connection,'INSERT INTO concessions(name,code,currency_code) VALUES(?,?,?)',[`Checklist ${n}`,`CC${n}`,'XAF']),agency=await insert(connection,'INSERT INTO agencies(concession_id,name,code) VALUES(?,?,?)',[concession,`Agence ${n}`,`CA${n}`]),user=await insert(connection,'INSERT INTO users(agency_id,first_name,last_name,email,password_hash) VALUES(?,?,?,?,?)',[agency,'Agent','Checklist',`checklist-${n}@test.local`,'x']),customer=await insert(connection,'INSERT INTO customers(customer_code,agency_id,first_name,last_name) VALUES(?,?,?,?)',[`CL${n}`,agency,'Client',n]),brand=await insert(connection,'INSERT INTO brands(name,code) VALUES(?,?)',[`Brand ${n}`,`CB${n}`]),model=await insert(connection,'INSERT INTO models(brand_id,name,code) VALUES(?,?,?)',[brand,`Model ${n}`,`CM${n}`]),version=await insert(connection,'INSERT INTO versions(model_id,name,code) VALUES(?,?,?)',[model,`Version ${n}`,`CV${n}`]),vehicle=await insert(connection,"INSERT INTO vehicles(version_id,agency_id,vin,status) VALUES(?,?,?,'sold')",[version,agency,`CHK${n}`]),sale=await insert(connection,"INSERT INTO sales(sale_number,customer_id,agency_id,status,total,deposit_amount,balance_due,currency_code,created_by) VALUES(?,?,?,'ready_for_delivery',100,100,0,'XAF',?)",[`CS${n}`,customer,agency,user]);await connection.execute('INSERT INTO sale_items(sale_id,vehicle_id,description,quantity,unit_price,line_total) VALUES(?,?,?,1,100,100)',[sale,vehicle,'Véhicule']);const delivery=await insert(connection,"INSERT INTO deliveries(delivery_number,sale_id,customer_id,vehicle_id,agency_id,status,created_by) VALUES(?,?,?,?,?,'planned',?)",[`CD${n}`,sale,customer,vehicle,agency,user]),categoryA=await insert(connection,'INSERT INTO delivery_checklist_categories(concession_id,code,name,sort_order,created_by) VALUES(?,?,?,?,?)',[concession,`PREP${n}`,'Préparation ancienne',10,user]),categoryB=await insert(connection,'INSERT INTO delivery_checklist_categories(concession_id,code,name,sort_order,created_by) VALUES(?,?,?,?,?)',[concession,`QUAL${n}`,'Qualité',20,user]),itemA=await insert(connection,'INSERT INTO delivery_checklist_items(category_id,code,name,is_mandatory,sort_order,created_by) VALUES(?,?,?,TRUE,10,?)',[categoryA,`A${n}`,'Item A ancien',user]),itemB=await insert(connection,'INSERT INTO delivery_checklist_items(category_id,code,name,is_mandatory,sort_order,created_by) VALUES(?,?,?,TRUE,10,?)',[categoryB,`B${n}`,'Item B',user]);return{delivery,categoryA,categoryB,itemA,itemB,user}})}
async function start(connection:PoolConnection,f:Fixture,hold?:()=>Promise<void>){const[rows]=await connection.execute<RowDataPacket[]>('SELECT status FROM deliveries WHERE id=? FOR UPDATE',[f.delivery]);if(rows[0]?.status==='preparing')return false;assert.equal(rows[0]?.status,'planned');const created=await createDeliveryChecklistSnapshot(connection,f.delivery,f.user);if(hold)await hold();await connection.execute("UPDATE deliveries SET status='preparing',prepared_at=NOW() WHERE id=?",[f.delivery]);return created}
async function instanceItems(f:Fixture){const[rows]=await pool.execute<RowDataPacket[]>('SELECT ii.id,ii.name_snapshot,ii.is_completed,ii.completed_by,ii.completed_at,ci.name_snapshot category_name FROM delivery_checklist_item_instances ii JOIN delivery_checklist_category_instances ci ON ci.id=ii.category_instance_id WHERE ci.delivery_id=? ORDER BY ci.sort_order_snapshot,ii.sort_order_snapshot',[f.delivery]);return rows}
async function setItem(connection:PoolConnection,f:Fixture,itemId:string,completed:boolean,hold?:()=>Promise<void>){const[delivery]=await connection.execute<RowDataPacket[]>('SELECT status FROM deliveries WHERE id=? FOR UPDATE',[f.delivery]);if(delivery[0]?.status==='delivered')throw new Error('DELIVERED');const[items]=await connection.execute<RowDataPacket[]>('SELECT ii.id FROM delivery_checklist_item_instances ii JOIN delivery_checklist_category_instances ci ON ci.id=ii.category_instance_id WHERE ii.id=? AND ci.delivery_id=? FOR UPDATE',[itemId,f.delivery]);if(!items[0])throw new Error('ITEM_NOT_FOUND');if(hold)await hold();await connection.execute('UPDATE delivery_checklist_item_instances SET is_completed=?,completed_by=?,completed_at=IF(?,NOW(),NULL) WHERE id=?',[completed,completed?f.user:null,completed,itemId])}
async function finalize(connection:PoolConnection,f:Fixture,hold?:()=>Promise<void>){const[delivery]=await connection.execute<RowDataPacket[]>('SELECT status FROM deliveries WHERE id=? FOR UPDATE',[f.delivery]);if(delivery[0]?.status==='delivered')return false;await lockAndAssertDeliveryChecklistComplete(connection,f.delivery);if(hold)await hold();await connection.execute("UPDATE deliveries SET status='delivered',delivered_at=NOW() WHERE id=?",[f.delivery]);return true}

before(async()=>{if(enabled)await bootstrapDatabase()});after(async()=>{if(enabled)await pool.end()});
test('CONC-CHK-01..08 transactions MySQL 8.4 réelles',{skip:!enabled,timeout:300000},async t=>{
  await t.test('CONC-CHK-01 double démarrage crée un seul snapshot',async()=>{const f=await fixture(),results=await Promise.all([tx(c=>start(c,f)),tx(c=>start(c,f))]);assert.deepEqual(results.sort(),[false,true]);const[rows]=await pool.execute<RowDataPacket[]>('SELECT COUNT(*) categories,COUNT(DISTINCT ii.id) items FROM delivery_checklist_category_instances ci LEFT JOIN delivery_checklist_item_instances ii ON ii.category_instance_id=ci.id WHERE ci.delivery_id=?',[f.delivery]);assert.equal(Number(rows[0].categories),2);assert.equal(Number(rows[0].items),2)});
  await t.test('CONC-CHK-02 snapshot vs catégorie produit un snapshot cohérent',async()=>{const f=await fixture();let release!:()=>void;const gate=new Promise<void>(resolve=>release=resolve),snapshot=tx(c=>start(c,f,()=>gate));await wait();let changed=false;const update=tx(async c=>{await c.execute("SELECT id FROM delivery_checklist_categories WHERE id=? FOR UPDATE",[f.categoryA]);await c.execute("UPDATE delivery_checklist_categories SET name='Préparation nouvelle' WHERE id=?",[f.categoryA]);changed=true});await wait();assert.equal(changed,false);release();await Promise.all([snapshot,update]);const items=await instanceItems(f);assert.equal(items[0]!.category_name,'Préparation ancienne')});
  await t.test('CONC-CHK-03 snapshot vs item ne crée aucun hybride',async()=>{const f=await fixture();let release!:()=>void;const gate=new Promise<void>(resolve=>release=resolve),snapshot=tx(c=>start(c,f,()=>gate));await wait();let changed=false;const update=tx(async c=>{await c.execute('SELECT i.id FROM delivery_checklist_items i JOIN delivery_checklist_categories cat ON cat.id=i.category_id WHERE i.id=? FOR UPDATE',[f.itemA]);await c.execute("UPDATE delivery_checklist_items SET name='Item A nouveau',is_mandatory=FALSE WHERE id=?",[f.itemA]);changed=true});await wait();assert.equal(changed,false);release();await Promise.all([snapshot,update]);const items=await instanceItems(f);assert.equal(items[0]!.name_snapshot,'Item A ancien');assert.equal(Number(items[0]!.is_completed),0)});
  await t.test('CONC-CHK-04 deux mutations du même item sont sérialisées',async()=>{const f=await fixture();await tx(c=>start(c,f));const item=String((await instanceItems(f))[0]!.id);let release!:()=>void;const gate=new Promise<void>(resolve=>release=resolve),first=tx(c=>setItem(c,f,item,true,()=>gate));await wait();let secondDone=false;const second=tx(c=>setItem(c,f,item,false)).finally(()=>secondDone=true);await wait();assert.equal(secondDone,false);release();await Promise.all([first,second]);const row=(await instanceItems(f))[0]!;assert.equal(Number(row.is_completed),0);assert.equal(row.completed_by,null);assert.equal(row.completed_at,null)});
  await t.test('CONC-CHK-05 réordonnements concurrents gardent des positions uniques',async()=>{const f=await fixture(),reorder=(ids:string[])=>tx(async c=>{const[rows]=await c.execute<RowDataPacket[]>('SELECT id FROM delivery_checklist_categories WHERE id IN (?,?) ORDER BY id FOR UPDATE',[f.categoryA,f.categoryB]);assert.equal(rows.length,2);for(const[index,id]of ids.entries())await c.execute('UPDATE delivery_checklist_categories SET sort_order=? WHERE id=?',[1_000_000+index,id]);for(const[index,id]of ids.entries())await c.execute('UPDATE delivery_checklist_categories SET sort_order=? WHERE id=?',[(index+1)*10,id])});await Promise.all([reorder([f.categoryA,f.categoryB]),reorder([f.categoryB,f.categoryA])]);const[rows]=await pool.execute<RowDataPacket[]>('SELECT sort_order FROM delivery_checklist_categories WHERE id IN (?,?) ORDER BY sort_order',[f.categoryA,f.categoryB]);assert.deepEqual(rows.map(row=>Number(row.sort_order)),[10,20])});
  await t.test('CONC-CHK-06 décomplétion vs finalisation préserve l invariant',async()=>{const f=await fixture();await tx(c=>start(c,f));const items=await instanceItems(f);for(const item of items)await tx(c=>setItem(c,f,String(item.id),true));const target=String(items[0]!.id);await tx(c=>setItem(c,f,target,false));await assert.rejects(tx(c=>finalize(c,f)),/obligatoires/);await tx(c=>setItem(c,f,target,true));let release!:()=>void;const gate=new Promise<void>(resolve=>release=resolve),done=tx(c=>finalize(c,f,()=>gate));await wait();const reopen=tx(c=>setItem(c,f,target,false));await wait();release();await done;await assert.rejects(reopen,/DELIVERED/);assert.equal((await pool.execute<RowDataPacket[]>('SELECT status FROM deliveries WHERE id=?',[f.delivery]))[0][0]!.status,'delivered');assert.equal(Number((await instanceItems(f))[0]!.is_completed),1)});
  await t.test('CONC-CHK-07 dernier obligatoire vs finalisation est cohérent',async()=>{const f=await fixture();await tx(c=>start(c,f));const items=await instanceItems(f);await tx(c=>setItem(c,f,String(items[0]!.id),true));await assert.rejects(tx(c=>finalize(c,f)),/obligatoires/);await tx(c=>setItem(c,f,String(items[1]!.id),true));assert.equal(await tx(c=>finalize(c,f)),true);assert.equal((await pool.execute<RowDataPacket[]>('SELECT status FROM deliveries WHERE id=?',[f.delivery]))[0][0]!.status,'delivered')});
  await t.test('CONC-CHK-08 finalisation ignore une modification ultérieure du catalogue',async()=>{const f=await fixture();await tx(c=>start(c,f));const items=await instanceItems(f);for(const item of items)await tx(c=>setItem(c,f,String(item.id),true));await Promise.all([tx(c=>finalize(c,f)),tx(async c=>{await c.execute('SELECT id FROM delivery_checklist_items WHERE id=? FOR UPDATE',[f.itemA]);await c.execute("UPDATE delivery_checklist_items SET name='Catalogue après snapshot' WHERE id=?",[f.itemA])})]);assert.equal((await instanceItems(f))[0]!.name_snapshot,'Item A ancien');assert.equal((await pool.execute<RowDataPacket[]>('SELECT status FROM deliveries WHERE id=?',[f.delivery]))[0][0]!.status,'delivered')});
});
