import assert from'node:assert/strict';
import{readFileSync}from'node:fs';
import{test}from'node:test';
import{assertHandoverMileage,deliverySignatureHash}from'../src/modules/deliveries/delivery.domain.js';
const read=(path:string)=>readFileSync(new URL(path,import.meta.url),'utf8');

test('DEL-MILE-01..04 refuse inférieur et accepte égal ou supérieur avec message métier',()=>{assert.throws(()=>assertHandoverMileage(25,20),error=>Boolean(error&&typeof error==='object'&&'status'in error&&error.status===409&&'message'in error&&String(error.message).includes('25 km')));assert.equal(assertHandoverMileage(25,25),25);assert.equal(assertHandoverMileage(25,31),31)});
test('DEL-SIGN empreinte reproductible depuis un timestamp canonique',()=>{const input={deliveryId:'1',saleId:'2',vehicleId:'3',signer:'Client',mileage:31,signedAt:'2026-09-10T10:00:00.000Z',signature:'data:image/png;base64,abc'};assert.equal(deliverySignatureHash(input),deliverySignatureHash(input));assert.notEqual(deliverySignatureHash(input),deliverySignatureHash({...input,signedAt:'2026-09-10T10:00:01.000Z'}))});
test('DEL-CHK-01..06 catégories, phases, persistance et verrou post-livraison',()=>{const route=read('../src/modules/deliveries/delivery.routes.ts'),service=read('../src/modules/deliveries/delivery-checklist.service.ts');assert.match(route,/createDeliveryChecklistSnapshot/);assert.match(route,/delivery_checklist_item_instances SET is_completed/);assert.match(route,/completed_by=\?,completed_at=IF\(\?,NOW\(\),NULL\)/);assert.match(route,/lockAndAssertDeliveryChecklistComplete/);assert.match(route,/\["delivered", "cancelled"\]\.includes\(row\.status\)/);assert.match(service,/is_mandatory_snapshot/)});
test('DEL-DOC-01..04 documents GED restent distincts des items snapshotés et immuables',()=>{const route=read('../src/modules/deliveries/delivery.routes.ts');assert.match(route,/received=Boolean\(request\.body\.received\)/);assert.match(route,/documents d’une livraison finalisée ne peuvent plus être modifiés/);assert.match(route,/documents obligatoires ne sont pas tous remis/);assert.doesNotMatch(route.slice(route.indexOf('deliveryRouter.post(\n  "\/deliveries",'),route.indexOf('deliveryRouter.patch(\n  "\/deliveries\/:id\/status"')),/INSERT INTO delivery_documents/)});
test('DEL-SIGN-01..06 et DEL-FINAL-01..06 transaction unique et autoritaire',()=>{const route=read('../src/modules/deliveries/delivery.routes.ts'),financialGate=read('../src/modules/billing/sale-financial-gate.ts'),schema=read('../database/baseline/001_initial_schema.sql');const sign=route.slice(route.indexOf('"/deliveries/:id/sign"'),route.indexOf('"/deliveries/:id/pdf"'));assert.match(sign,/requirePermission\('delivery\.signature\.capture'\)/);assert.match(sign,/requirePermission\('delivery\.complete'\)/);assert.match(sign,/SELECT d\.\*,s\.status sale_status.*FOR UPDATE/);assert.match(sign,/useDeliveryFinancialAuthorization/);assert.match(financialGate,/SELECT id,status,total,amount_paid,balance_due,currency_code,invoice_type FROM invoices.*FOR UPDATE/);assert.match(sign,/SELECT id,status,mileage FROM vehicles WHERE id=\? FOR UPDATE/);assert.match(sign,/delivery\.status==='delivered'.*duplicate:true/s);assert.match(sign,/INSERT INTO delivery_signatures/);assert.match(sign,/UPDATE deliveries SET status='delivered'/);assert.match(sign,/UPDATE sales SET status='delivered'/);assert.match(sign,/UPDATE vehicles SET status='delivered',mileage=\?/);assert.match(sign,/vehicle\.status.*'delivered'/);assert.match(schema,/UNIQUE KEY uk_delivery_signature_final \(delivery_id\)/)});
test('DEL-PDF utilise le renderer documentaire partagé avec opérateur, kilométrage, empreinte et signature',()=>{const route=read('../src/modules/deliveries/delivery.routes.ts'),renderer=read('../src/modules/documents/commercial-document.ts');const pdf=route.slice(route.indexOf('"/deliveries/:id/pdf"'),route.indexOf('"/deliveries-planning/pdf"'));assert.match(pdf,/renderDeliveryDocument/);assert.match(renderer,/Responsable livraison/);assert.match(renderer,/Kilométrage/);assert.match(renderer,/Empreinte/);assert.match(renderer,/signature_data/);assert.match(renderer,/logoCandidates/)});
test('DEL-PLAN responsable obligatoire de même agence et détenteur de permission',()=>{const route=read('../src/modules/deliveries/delivery.routes.ts');assert.match(route,/requirePermission\('delivery\.schedule'\)/);assert.match(route,/specialist = idOf/);assert.match(route,/p\.code='delivery\.prepare'/);assert.match(route,/u\.agency_id=\?/)});
