import assert from'node:assert/strict';
import{readFileSync}from'node:fs';
import test from'node:test';
import{validateConcession}from'../src/modules/settings/setting.service.js';
import{documentFooterLines}from'../src/modules/documents/document-layout.js';
import{renderCommercialDocument,renderDeliveryPlanningDocumentData}from'../src/modules/documents/commercial-document.js';

const source=(path:string)=>readFileSync(new URL(`../${path}`,import.meta.url),'utf8');
const migration=source('database/migrations/053_concession_document_identity.sql'),baseline=source('database/baseline/001_initial_schema.sql'),service=source('src/modules/settings/setting.service.ts'),resolver=source('src/modules/settings/setting-resolver.ts'),routes=source('src/modules/settings/setting.routes.ts'),layout=source('src/modules/documents/document-layout.ts'),business=source('src/modules/documents/business-document.service.ts');
const identity={legalName:'LCA SA',tradeName:'LCA',taxIdentifier:'NIU-001',rccm:'CG-BZV-01-2026-B12-00001',rib:'30001 00001 12345678901 99',website:'https://www.lca.cg/',agencyName:'Agence Centre',agencyAddress:'12 avenue de la République',agencyCity:'Brazzaville',concessionAddress:'Adresse concession',concessionCity:'Pointe-Noire',phone:'+242 06 000 00 00',email:'contact@lca.cg',currencyCode:'XAF',logoCandidates:[]};
const payload={name:'  LCA  ',legalName:' LCA SA ',taxIdentifier:' NIU-001 ',rccm:' CG-BZV ',rib:' 30001 00001 12345678901 99 ',website:' https://www.lca.cg ',address:' Rue 1 ',city:' Brazzaville ',country:' Congo ',currencyCode:'XAF',timezone:'Africa/Brazzaville'};

test('ID-DOC-01/02 le NIU reste tax_identifier sans nouveau NIU ou NIF',()=>{assert.match(baseline,/tax_identifier VARCHAR\(100\)/);assert.doesNotMatch(migration,/\b(?:niu|nif)\b/i);assert.match(service,/taxIdentifier: text\(b\.taxIdentifier, "NIU"/)});
test('ID-DOC-03/04/05 RCCM, RIB et site sont persistés et relus par le modèle canonique',()=>{for(const token of['rccm VARCHAR(190)','rib VARCHAR(500)','website VARCHAR(500)']){assert.match(migration,new RegExp(token.replace(/[()]/g,'\\$&')));assert.match(baseline,new RegExp(token.replace(/[()]/g,'\\$&')))}assert.match(service,/UPDATE concessions SET name=\?,legal_name=\?,tax_identifier=\?,rccm=\?,rib=\?,website=\?/);for(const field of['c.rccm','c.rib','c.website'])assert.match(resolver,new RegExp(field.replace('.','\\.')))});
test('ID-DOC-06 validation normalise les valeurs et rejette longueurs et sites invalides',()=>{const value=validateConcession(payload);assert.equal(value.rccm,'CG-BZV');assert.equal(value.rib,'30001 00001 12345678901 99');assert.equal(value.website,'https://www.lca.cg');assert.throws(()=>validateConcession({...payload,rccm:'x'.repeat(191)}),/RCCM trop long/);assert.throws(()=>validateConcession({...payload,rib:'x'.repeat(501)}),/RIB trop long/);assert.throws(()=>validateConcession({...payload,website:'pas-un-site'}),/Site web invalide/)});
test('ID-DOC-07/08 identité commune expose le légal concession et les coordonnées agence',()=>{for(const field of['taxIdentifier:row.tax_identifier','rccm:row.rccm','rib:row.rib','website:row.website','agencyAddress:row.agency_address','phone:row.phone'])assert.match(resolver,new RegExp(field.replaceAll('.','\\.')));assert.deepEqual(documentFooterLines(identity),{legal:'RCCM : CG-BZV-01-2026-B12-00001 • NIU : NIU-001 • RIB : 30001 00001 12345678901 99 • Site web : www.lca.cg',contact:'Adresse : 12 avenue de la République, Brazzaville • Tél. : +242 06 000 00 00'})});
test('ID-DOC-09/10 écriture protégée par permission persistée sans rôle codé',()=>{assert.match(routes,/patch\('\/concessions\/current',requirePermission\('settings\.update'\)/);assert.match(service,/assertConcessionWrite/);assert.doesNotMatch(service,/SUPER_ADMIN|DIRECTOR|MANAGER/)});
test('PDF-FOOTER-01..05 valeurs absentes sans séparateurs orphelins',()=>{assert.deepEqual(documentFooterLines({...identity,rccm:null,rib:null,website:null}),{legal:'NIU : NIU-001',contact:'Adresse : 12 avenue de la République, Brazzaville • Tél. : +242 06 000 00 00'});assert.deepEqual(documentFooterLines({...identity,rccm:null,taxIdentifier:null,rib:null,website:null,agencyAddress:null,agencyCity:null,concessionAddress:null,concessionCity:null,phone:null}),{legal:'',contact:''});assert.doesNotMatch(layout,/Identifiant fiscal/)});
test('PDF-FOOTER-06..08 valeurs longues restent prises en charge par une taille adaptative',()=>{assert.match(layout,/footerFontSize/);assert.match(layout,/while\(size>5\.2\)/);const lines=documentFooterLines({...identity,rccm:'R'.repeat(190),rib:'1'.repeat(500),website:`https://${'a'.repeat(470)}.cg`,agencyAddress:'A'.repeat(400)});assert.ok(lines.legal.includes('RIB :'));assert.ok(lines.contact.startsWith('Adresse :'))});
test('PDF-FOOTER-09..12 rendu multipage, logo/header et réserve footer',async()=>{const rows=Array.from({length:60},(_,i)=>({scheduled_at:`2026-10-06 10:00:00`,delivery_number:`LIV-${i}`,customer_name:`Client ${i}`,vehicle_label:`Véhicule ${i} ${'long '.repeat(12)}`,delivery_location:'Agence',status:'planned'})),pdf=await renderDeliveryPlanningDocumentData(rows,'2026-10-06',identity),count=Number(/\/Count\s+(\d+)/.exec(pdf.toString('latin1'))?.[1]??0);assert.equal(pdf.subarray(0,4).toString(),'%PDF');assert.ok(count>1);assert.equal((layout.match(/identity\.taxIdentifier/g)??[]).length,1);assert.match(layout,/footerY:746/)});
test('ID-DOC-11 nouveaux documents consomment l’identité légale étendue',async()=>{const header={number:'DEV-1',document_date:'2026-10-06',agency_id:1,currency_code:'XAF',customer_name:'Client',customer_code:'C1',subtotal:100,discount_total:0,tax_total:0,total:100,tax_mode:'TAX_EXEMPT',tax_rate_snapshot:0},items=[{description:'Véhicule',quantity:1,unit_price:100,discount_amount:0,tax_amount:0,line_total:100}],pdf=await renderCommercialDocument('DEVIS',header as any,items as any,identity);assert.equal(pdf.subarray(0,4).toString(),'%PDF');assert.match(pdf.subarray(-32).toString('latin1'),/%%EOF/)});
test('ID-DOC-12..17 archives historiques restent autoritaires pour preview et download',()=>{assert.match(business,/requiredHistoricalBusinessPdf/);assert.match(business,/readDocumentFile\(String\(row\.file_url\),row\.file_hash\)/);for(const file of['src/modules/quotations/quotation.routes.ts','src/modules/core/core.routes.ts','src/modules/billing/billing.routes.ts','src/modules/deliveries/delivery.routes.ts'])assert.match(source(file),/requiredHistoricalBusinessPdf/)});
