import assert from'node:assert/strict';import{randomUUID}from'node:crypto';import{after,test}from'node:test';import supertest from'supertest';import type{ResultSetHeader,RowDataPacket}from'mysql2/promise';import{createApp}from'../src/app.js';import{pool,query}from'../src/config/database.js';
const enabled=process.env.LCA_LABOR_RATES_DB_TEST==='1';if(enabled)after(async()=>pool.end());const insert=async(sql:string,p:unknown[]=[])=>String((await pool.execute<ResultSetHeader>(sql,p))[0].insertId);const rows=(sql:string,p:unknown[]=[])=>query<RowDataPacket[]>(sql,p);

test('BAREME-03..28 référentiel dynamique, surcharge et snapshots sur MySQL 8.4',{skip:!enabled},async()=>{
 const api=supertest(createApp()),login=await api.post('/api/auth/login').send({email:process.env.ADMIN_EMAIL,password:process.env.ADMIN_PASSWORD});assert.equal(login.status,200,JSON.stringify(login.body));const auth=(request:supertest.Test)=>request.set('Authorization',`Bearer ${login.body.accessToken}`),suffix=randomUUID().slice(0,8),[admin]=await rows('SELECT id,agency_id FROM users WHERE email=?',[process.env.ADMIN_EMAIL]),agencyId=String(admin.agency_id);
 const created=await auth(api.post('/api/workshop-labor-rates')).send({code:`T5_${suffix}`,label:'Climatisation',hourlyRate:25000,displayOrder:50});assert.equal(created.status,201,JSON.stringify(created.body));const baseId=String(created.body.id);
 const duplicate=await auth(api.post('/api/workshop-labor-rates')).send({code:`T5_${suffix}`,label:'Doublon',hourlyRate:1});assert.equal(duplicate.status,409);
 const override=await auth(api.put(`/api/workshop-labor-rates/${baseId}/agency-override`)).send({agencyId,hourlyRate:30000,isActive:true});assert.equal(override.status,200,JSON.stringify(override.body));
 const brand=await insert('INSERT INTO brands(name,code) VALUES(?,?)',[`Barème ${suffix}`,`BAR_${suffix}`]),model=await insert('INSERT INTO models(brand_id,name) VALUES(?,?)',[brand,'Modèle']),version=await insert('INSERT INTO versions(model_id,name) VALUES(?,?)',[model,'Version']),customer=await insert('INSERT INTO customers(customer_code,agency_id,first_name,last_name) VALUES(?,?,?,?)',[`BARC_${suffix}`,agencyId,'Client','Barème']),vehicle=await insert('INSERT INTO vehicles(version_id,agency_id,vin) VALUES(?,?,?)',[version,agencyId,`BAR${suffix}VIN`]),order=await insert("INSERT INTO repair_orders(order_number,customer_id,vehicle_id,agency_id,advisor_id,status,created_by) VALUES(?,?,?,?,?,'diagnosis',?)",[`OR-BAR-${suffix}`,customer,vehicle,agencyId,admin.id,admin.id]);
 const rates=await auth(api.get(`/api/repair-orders/${order}/labor-rates`));assert.equal(rates.status,200);const effective=rates.body.rates.find((rate:{baseRateId:string})=>rate.baseRateId===baseId);assert.equal(effective.source,'agency');assert.equal(effective.hourlyRate,30000);
 const oldLine=await auth(api.post(`/api/repair-orders/${order}/estimate-items`)).send({itemType:'labor',description:'Recharge circuit',quantity:2,laborRateId:effective.id,unitPrice:1,requestKey:randomUUID()});assert.equal(oldLine.status,201,JSON.stringify(oldLine.body));const[oldSnapshot]=await rows('SELECT id,labor_rate_id,rate_code_snapshot,rate_label_snapshot,unit_price,line_total FROM repair_order_estimate_items WHERE repair_order_id=? ORDER BY id DESC LIMIT 1',[order]);assert.equal(Number(oldSnapshot.unit_price),30000);assert.equal(Number(oldSnapshot.line_total),60000);assert.equal(oldSnapshot.rate_label_snapshot,'Climatisation');
 const changed=await auth(api.patch(`/api/workshop-labor-rates/${baseId}`)).send({label:'Climatisation & froid',hourlyRate:35000});assert.equal(changed.status,200);
 const cleared=await auth(api.delete(`/api/workshop-labor-rates/${baseId}/agency-override`).query({agencyId}));assert.equal(cleared.status,200);const[preservedOverride]=await rows('SELECT is_configured FROM workshop_labor_rates WHERE id=?',[effective.id]);assert.equal(Boolean(preservedOverride.is_configured),false);const[linkedSnapshot]=await rows('SELECT labor_rate_id FROM repair_order_estimate_items WHERE id=?',[oldSnapshot.id]);assert.equal(String(linkedSnapshot.labor_rate_id),String(effective.id));const inherited=(await auth(api.get(`/api/repair-orders/${order}/labor-rates`))).body.rates.find((rate:{baseRateId:string})=>rate.baseRateId===baseId);assert.equal(inherited.source,'concession');assert.equal(inherited.hourlyRate,35000);
 const newLine=await auth(api.post(`/api/repair-orders/${order}/estimate-items`)).send({itemType:'labor',description:'Recharge nouvelle',quantity:2,laborRateId:inherited.id,unitPrice:999999,requestKey:randomUUID()});assert.equal(newLine.status,201,JSON.stringify(newLine.body));const snapshots=await rows('SELECT rate_label_snapshot,unit_price,line_total FROM repair_order_estimate_items WHERE repair_order_id=? AND rate_code_snapshot=? ORDER BY id',[order,`T5_${suffix}`]);assert.deepEqual(snapshots.map(row=>[row.rate_label_snapshot,Number(row.unit_price),Number(row.line_total)]),[['Climatisation',30000,60000],['Climatisation & froid',35000,70000]]);
 const inactiveOverride=await auth(api.put(`/api/workshop-labor-rates/${baseId}/agency-override`)).send({agencyId,hourlyRate:31000,isActive:false});assert.equal(inactiveOverride.status,200);assert.equal((await auth(api.get(`/api/repair-orders/${order}/labor-rates`))).body.rates.some((rate:{baseRateId:string})=>rate.baseRateId===baseId),false);await auth(api.delete(`/api/workshop-labor-rates/${baseId}/agency-override`).query({agencyId}));
 const disabled=await auth(api.patch(`/api/workshop-labor-rates/${baseId}`)).send({isActive:false});assert.equal(disabled.status,200);assert.equal((await auth(api.get(`/api/repair-orders/${order}/labor-rates`))).body.rates.some((rate:{baseRateId:string})=>rate.baseRateId===baseId),false);const rejected=await auth(api.post(`/api/repair-orders/${order}/estimate-items`)).send({itemType:'labor',description:'Interdit',quantity:1,laborRateId:baseId,unitPrice:1});assert.equal(rejected.status,400);const oldAfterDisable=await rows('SELECT rate_label_snapshot,unit_price,line_total FROM repair_order_estimate_items WHERE id=?',[oldSnapshot.id]);assert.equal(oldAfterDisable[0].rate_label_snapshot,'Climatisation');assert.equal(Number(oldAfterDisable[0].unit_price),30000);assert.equal(Number(oldAfterDisable[0].line_total),60000);
 assert.equal((await auth(api.patch(`/api/workshop-labor-rates/${baseId}`)).send({isActive:true})).status,200);
 console.log('DYNAMIC_LABOR_RATE_EVIDENCE',JSON.stringify({baseId,overrideRate:30000,oldSnapshot:30000,newSnapshot:35000,forgedIgnored:true,inactiveRejected:true,duplicateHttp:409}));
});
