import test from'node:test';import assert from'node:assert/strict';import{readFileSync}from'node:fs';
const read=(path:string)=>readFileSync(new URL(`../${path}`,import.meta.url),'utf8');
const migration=read('database/migrations/040_dynamic_workshop_labor_rates.sql'),service=read('src/modules/settings/labor-rate.service.ts'),routes=read('src/modules/settings/setting.routes.ts'),workshop=read('src/modules/workshop/workshop.routes.ts'),frontend=read('../frontend/src/modules/service/RepairOrderDetailPage.tsx'),settings=read('../frontend/src/modules/settings/WorkshopLaborRatesSettings.tsx');

test('BAREMES-01 migration 040 crée le référentiel et migre T1-T4 sans écraser',()=>{assert.match(migration,/CREATE TABLE workshop_labor_rates/);assert.match(migration,/UNIQUE KEY uk_workshop_labor_rate_base_code/);assert.match(migration,/UNIQUE KEY uk_workshop_labor_rate_agency_override/);assert.match(migration,/workshop\.rate_t1/);assert.match(migration,/JSON_UNQUOTE\(s\.setting_value\) REGEXP/);assert.match(migration,/ON DUPLICATE KEY UPDATE id=workshop_labor_rates\.id/)});
test('BAREMES-02 snapshots historiques sont additifs et non destructifs',()=>{for(const column of['labor_rate_id','rate_code_snapshot','rate_label_snapshot'])assert.match(migration,new RegExp(column));assert.match(migration,/fk_repair_estimate_labor_rate[\s\S]*ON DELETE SET NULL/);assert.doesNotMatch(migration,/UPDATE repair_order_estimate_items/)});
test('BAREMES-03 résolution explicite concession puis agence sans suppression historique',()=>{assert.match(service,/LEFT JOIN workshop_labor_rates override_rate/);assert.match(service,/override_rate\.parent_rate_id=base\.id/);assert.match(service,/override_rate\.is_configured=TRUE/);assert.match(service,/source:row\.override_id\?'agency':'concession'/);assert.match(service,/override_rate\.id IS NULL OR override_rate\.is_active=TRUE/);assert.match(service,/SET is_configured=FALSE/);assert.doesNotMatch(service,/DELETE FROM workshop_labor_rates/)});
test('BAREMES-04 administration reste RBAC dynamique et refuse OWN collectif',()=>{assert.match(routes,/requirePermission\('settings\.view'\)/);assert.match(routes,/requirePermission\('settings\.update'\)/);assert.match(service,/scope OWN ne permet pas/);assert.doesNotMatch(service,/role\s*===|DIRECTOR|SUPER_ADMIN/)});
test('BAREMES-05 SAV résout le tarif serveur et snapshotte identité code libellé',()=>{assert.match(workshop,/resolveEffectiveLaborRateSelection/);assert.match(workshop,/labor_rate_id,rate_code_snapshot,rate_label_snapshot/);assert.match(workshop,/price=rate\.hourlyRate/);assert.match(workshop,/tarif de main-d’œuvre snapshoté ne peut pas être remplacé/);assert.doesNotMatch(workshop,/\['T1','T2','T3','T4'\]\.includes/)});
test('BAREMES-06 interfaces Paramètres et SAV consomment une collection dynamique',()=>{assert.match(settings,/Hérité/);assert.match(settings,/Surcharger/);assert.match(settings,/Hériter/);assert.match(frontend,/workshopConfig\?\.rates\.map/);assert.match(frontend,/laborRateId/);assert.doesNotMatch(frontend,/\["T1","T2","T3","T4"\]/)});
