import assert from'node:assert/strict';import{readFileSync}from'node:fs';import test from'node:test';
const eligibility=readFileSync(new URL('../src/modules/workshop/vehicle-warranty-eligibility.service.ts',import.meta.url),'utf8'),workshop=readFileSync(new URL('../src/modules/workshop/workshop.routes.ts',import.meta.url),'utf8'),warranty=readFileSync(new URL('../src/modules/workshop/warranty.routes.ts',import.meta.url),'utf8'),service=readFileSync(new URL('../src/modules/workshop/warranty.service.ts',import.meta.url),'utf8'),v1=readFileSync(new URL('./sav-warranty-v1.test.ts',import.meta.url),'utf8');
test('WL03-02 NOT_APPLICABLE conserve le SAV normal',()=>assert.match(eligibility,/NOT_APPLICABLE.*NOT_COVERED/s));
test('WL03-03 ACTIVE valide est détecté automatiquement',()=>assert.match(eligibility,/ELIGIBLE_CONTRACTUALLY/));
test('WL03-04 constructeur provient du snapshot',()=>assert.match(eligibility,/provider_name_snapshot/));
test('WL03-05 conditions proviennent du snapshot',()=>{assert.match(eligibility,/duration_months/);assert.match(eligibility,/mileage_limit/)});
test('WL03-06 ACTIVE initialise Warranty V1',()=>assert.match(workshop,/contractWarranty\.status==='ELIGIBLE_CONTRACTUALLY'[\s\S]*INSERT INTO repair_order_warranties/));
test('WL03-07 demande automatique reste PENDING',()=>{assert.match(workshop,/decision_status,allocation_status[\s\S]*'PENDING','UNALLOCATED'/);assert.doesNotMatch(workshop,/contractWarranty[\s\S]{0,300}'APPROVED'/)});
test('WL03-08 PENDING bloque réception',()=>assert.match(service,/décision de prise en charge constructeur doit être enregistrée avant la réception/));
test('WL03-09 API directe conserve le verrou PENDING',()=>assert.match(workshop,/if\(next==='received'\)await assertWarrantyDecisionMade/));
test('WL03-10 APPROVED autorise la suite',()=>assert.match(service,/if\(rows\[0\]\?\.decision_status==='PENDING'\)throw/));
test('WL03-11 REJECTED autorise le SAV hors prise en charge',()=>assert.match(warranty,/decision==='APPROVED'\?'DRAFT':'CONFIRMED'/));
test('WL03-12 REJECTED ne modifie pas le contrat véhicule',()=>assert.doesNotMatch(warranty,/UPDATE vehicle_warranty_contracts/));
test('WL03-13 un nouvel OR réévalue le contrat persistant',()=>assert.match(workshop,/evaluateVehicleWarranty\(vehicle,mileage,c\)/));
test('WL03-14 expiration par date',()=>{assert.match(eligibility,/expiry_date<NOW\(\)/);assert.match(eligibility,/EXPIRED_BY_DATE/)});
test('WL03-15 dépassement kilométrique',()=>assert.match(eligibility,/currentMileage!>Number\(contract\.mileage_limit\).*EXPIRED_BY_MILEAGE/s));
test('WL03-16 limite NULL sans comparaison à zéro',()=>assert.match(eligibility,/contract\.mileage_limit!=null/));
test('WL03-17 kilométrage réception autoritaire',()=>{assert.match(workshop,/evaluateVehicleWarranty\(vehicle,mileage,c\)/);assert.match(workshop,/inspection\[0\]\?\.mileage/)});
test('WL03-18 APPLICABLE non ACTIVE reste non éligible',()=>assert.match(eligibility,/status!=='ACTIVE'.*PENDING_ACTIVATION/s));
test('WL03-19 UNDETERMINED distinct de NOT_COVERED',()=>{assert.match(eligibility,/UNDETERMINED' as const/);assert.match(eligibility,/NOT_COVERED' as const/)});
test('WL03-20 détail reconstruit contrat et demande',()=>{assert.match(workshop,/vehicleWarranty/);assert.match(workshop,/warrantyDetail/)});
test('WL03-21 anciens OR restent lisibles',()=>assert.match(warranty,/if\(before\)/));
test('WL03-22 ancien PENDING conservé',()=>assert.match(warranty,/SELECT \* FROM repair_order_warranties/));
test('WL03-23 ancien APPROVED conservé',()=>assert.doesNotMatch(workshop,/UPDATE repair_order_warranties SET decision_status/));
test('WL03-24 ancien REJECTED conservé',()=>assert.doesNotMatch(workshop,/DELETE FROM repair_order_warranties/));
test('WL03-25 paramètres constructeur non relus',()=>assert.doesNotMatch(eligibility,/default_warranty/));
test('WL03-26 constructeur désactivé sans effet historique',()=>assert.doesNotMatch(eligibility,/is_active|warranty_available/));
test('WL03-27 véhicules isolés par vehicle_id',()=>assert.match(eligibility,/WHERE vwc\.vehicle_id=\?/));
test('WL03-28 décisions isolées par repair_order_id',()=>assert.match(warranty,/WHERE repair_order_id=\? FOR UPDATE/));
test('WL03-29 RBAC et scope préservés',()=>{assert.match(workshop,/serviceAccess\('service\.order\.create'\)/);assert.match(workshop,/permissionCoversAgency/)});
test('WL03-30 à 33 verrous SAV restent présents',()=>{for(const value of['assertWarrantyReadyForQuality','assertWorkNotStarted','assertCustomerDidNotReject','customerApproval'])assert.match(workshop,new RegExp(value))});
test('WL03-34 FULL reste fonctionnel',()=>assert.match(v1,/GAR-06 garantie totale/));
test('WL03-35 PARTIAL reste fonctionnel',()=>assert.match(v1,/GAR-07 garantie partielle/));
test('WL03-36 créance constructeur reste fonctionnelle',()=>assert.match(workshop,/INSERT INTO warranty_claims/));
test('WL03-37 encaissement constructeur reste fonctionnel',()=>assert.match(warranty,/warranty_claim_payments/));
test('WL03-38 reporting Warranty reste fonctionnel',()=>assert.match(v1,/REP-WAR KPI/));
