import assert from'node:assert/strict';import{readFileSync}from'node:fs';import test from'node:test';
const migration=readFileSync(new URL('../database/migrations/048_vehicle_warranty_contract_lifecycle.sql',import.meta.url),'utf8'),service=readFileSync(new URL('../src/modules/sales/vehicle-warranty.service.ts',import.meta.url),'utf8'),sales=readFileSync(new URL('../src/modules/sales/sale.service.ts',import.meta.url),'utf8'),routes=readFileSync(new URL('../src/modules/sales/sale.routes.ts',import.meta.url),'utf8'),delivery=readFileSync(new URL('../src/modules/deliveries/delivery.routes.ts',import.meta.url),'utf8'),domain=readFileSync(new URL('../src/modules/sales/sale.domain.ts',import.meta.url),'utf8'),baseline=readFileSync(new URL('../database/baseline/001_initial_schema.sql',import.meta.url),'utf8');
test('WL02-01 migration additive 048',()=>assert.match(migration,/CREATE TABLE vehicle_warranty_contracts/));
test('WL02-02 états métier distincts',()=>{for(const value of['UNDETERMINED','APPLICABLE','NOT_APPLICABLE'])assert.match(migration,new RegExp(value))});
test('WL02-03 snapshot lié à la vente',()=>assert.match(migration,/UNIQUE KEY uk_vwc_sale\(sale_id\)/));
test('WL02-04 snapshot lié au véhicule',()=>assert.match(migration,/INDEX idx_vwc_vehicle\(vehicle_id\)/));
test('WL02-05 client historisé',()=>assert.match(migration,/customer_id BIGINT UNSIGNED NOT NULL/));
test('WL02-06 identité constructeur snapshotée',()=>{assert.match(migration,/provider_code_snapshot/);assert.match(migration,/provider_name_snapshot/)});
test('WL02-07 durée contractuelle bornée',()=>assert.match(migration,/BETWEEN 1 AND 240/));
test('WL02-08 plafond kilométrique optionnel positif',()=>assert.match(migration,/mileage_limit IS NULL OR mileage_limit>0/));
test('WL02-09 dates et kilométrage activation persistés',()=>{for(const value of['start_date','expiry_date','initial_mileage','activated_at'])assert.match(migration,new RegExp(value))});
test('WL02-10 acteurs décision et activation persistés',()=>{assert.match(migration,/decided_by/);assert.match(migration,/activated_by/)});
test('WL02-11 ventes historiques rétroalimentées indéterminées',()=>assert.match(migration,/INSERT INTO vehicle_warranty_contracts[\s\S]*FROM sales/));
test('WL02-12 baseline synchronisée',()=>assert.match(baseline,/CREATE TABLE vehicle_warranty_contracts/));
test('WL02-13 proposition issue de marque constructeur',()=>assert.match(service,/brands b ON b\.id=m\.brand_id[\s\S]*warranty_providers wp ON wp\.id=b\.warranty_provider_id/));
test('WL02-14 constructeur inactif exclu des nouvelles décisions',()=>assert.match(service,/wp\.is_active=TRUE AND wp\.warranty_available=TRUE/));
test('WL02-15 création vente crée le snapshot dans sa transaction',()=>assert.match(sales,/createSnapshot\(connection/));
test('WL02-16 valeurs applicables validées côté serveur',()=>{assert.match(domain,/Durée de garantie invalide/);assert.match(domain,/Plafond kilométrique invalide/)});
test('WL02-17 modification protégée par sales.update',()=>assert.match(routes,/sales\/:id\/warranty'.*requirePermission\('sales\.update'\)/));
test('WL02-18 garantie active immuable',()=>assert.match(service,/Une garantie activée est immuable/));
test('WL02-19 livraison refuse la décision indéterminée',()=>assert.match(service,/décision de garantie doit être renseignée avant la livraison/));
test('WL02-20 activation dans la transaction de signature',()=>{const transactionAt=delivery.indexOf('const result=await transaction'),activationAt=delivery.indexOf('await activateAtDelivery');assert.ok(transactionAt>=0&&activationAt>transactionAt)});
test('WL02-21 activation calcule échéance depuis le snapshot',()=>assert.match(service,/DATE_ADD\(\?,INTERVAL duration_months MONTH\)/));
test('WL02-22 activation est idempotente',()=>{assert.match(service,/status==='ACTIVE'\)return/);assert.match(service,/WHERE id=\? AND status='PENDING_ACTIVATION'/)});
test('WL02-23 non applicable ne crée pas de contrat actif',()=>assert.match(service,/decision==='NOT_APPLICABLE'\)return/));
