import assert from'node:assert/strict';
import{randomUUID}from'node:crypto';
import{after,test}from'node:test';
import jwt from'jsonwebtoken';
import supertest from'supertest';
import type{RowDataPacket}from'mysql2/promise';
import{createApp}from'../src/app.js';
import{execute,pool,query}from'../src/config/database.js';

const enabled=process.env.LCA_HR_BUDGET_CATEGORIES_DB_TEST==='1';
if(enabled)after(async()=>pool.end());

test('RH-BUDGET-CATEGORIES-02 MySQL 8.4 : référentiel, RBAC, usages et concurrence',{skip:!enabled},async()=>{
 const suffix=randomUUID().slice(0,8),api=supertest(createApp()),insert=async(sql:string,params:unknown[]=[])=>String((await execute(sql,params)).insertId);
 const concessionA=await insert('INSERT INTO concessions(name,code) VALUES(?,?)',[`Catégories A ${suffix}`,`BCA-${suffix}`]),concessionB=await insert('INSERT INTO concessions(name,code) VALUES(?,?)',[`Catégories B ${suffix}`,`BCB-${suffix}`]),agencyA1=await insert('INSERT INTO agencies(concession_id,name,code) VALUES(?,?,?)',[concessionA,'Agence CAT A1',`BCA1-${suffix}`]),agencyA2=await insert('INSERT INTO agencies(concession_id,name,code) VALUES(?,?,?)',[concessionA,'Agence CAT A2',`BCA2-${suffix}`]),agencyB1=await insert('INSERT INTO agencies(concession_id,name,code) VALUES(?,?,?)',[concessionB,'Agence CAT B1',`BCB1-${suffix}`]);
 const actor=await insert('INSERT INTO users(agency_id,first_name,last_name,email,password_hash) VALUES(?,?,?,?,?)',[agencyA1,'RH','Catégories',`budget-cat-${suffix}@test.local`,'test']),role=await insert('INSERT INTO roles(name,code,is_system,is_active) VALUES(?,?,FALSE,TRUE)',[`Budget catégories ${suffix}`,`BUDGET_CAT_${suffix}`]);await execute('INSERT INTO user_roles(user_id,role_id) VALUES(?,?)',[actor,role]);
 const codes=['hr.budget.view','hr.budget.manage','hr.expense.view','hr.expense.create','hr.expense.manage','hr.budget.category.view','hr.budget.category.manage'],permissionRows=await query<RowDataPacket[]>(`SELECT id,code FROM permissions WHERE code IN(${codes.map(()=>'?').join(',')})`,codes),permissionId=(code:string)=>String(permissionRows.find(row=>row.code===code)!.id),configure=async(scope:'OWN'|'AGENCY'|'CONCESSION'|'GLOBAL')=>{await execute('DELETE FROM role_permissions WHERE role_id=?',[role]);for(const code of codes)await execute('INSERT INTO role_permissions(role_id,permission_id,scope) VALUES(?,?,?)',[role,permissionId(code),scope])};
 const token=jwt.sign({sub:actor,email:`budget-cat-${suffix}@test.local`,roles:[],agencyId:agencyA1},process.env.JWT_ACCESS_SECRET!,{expiresIn:'10m'}),auth=(request:supertest.Test)=>request.set('Authorization',`Bearer ${token}`),category=async(concessionId:string,code:string,name:string)=>auth(api.post('/api/hr/budget-categories')).send({concessionId,code,name}),budgetPayload=(agencyId:string,categoryId?:string)=>({scopeType:'agency',agencyId,label:`Budget ${randomUUID().slice(0,6)}`,initialAmount:1000,startDate:'2026-01-01',endDate:'2026-12-31',categoryId}),expensePayload=(categoryId?:string)=>({label:`Dépense ${randomUUID().slice(0,6)}`,amount:10,expenseDate:'2026-03-01',categoryId});
 await configure('CONCESSION');let response=await category(concessionA,' marketing ','Marketing & communication');assert.equal(response.status,201,JSON.stringify(response.body));const marketingA=String(response.body.id);response=await category(concessionB,'OTHER','Interdite');assert.equal(response.status,403);response=await category(concessionA,'MARKETING','Autre nom');assert.equal(response.status,409);response=await category(concessionA,'OTHER_NAME','marketing & communication');assert.equal(response.status,409);response=await category(concessionA,'IT','Informatique');assert.equal(response.status,201);const itA=String(response.body.id);
 await configure('GLOBAL');response=await category(concessionB,'MARKETING','Marketing local B');assert.equal(response.status,201);const marketingB=String(response.body.id);response=await category(concessionA,'GLOBAL_A','Global A');assert.equal(response.status,201);response=await category(concessionB,'GLOBAL_B','Global B');assert.equal(response.status,201);
 await configure('AGENCY');response=await auth(api.get(`/api/hr/budget-categories?useFor=budget&concessionId=${concessionA}`));assert.equal(response.status,200);assert.ok(response.body.some((x:{id:string})=>x.id===marketingA));assert.equal((await category(concessionA,'AGENCY_FORBIDDEN','Interdite')).status,403);assert.equal((await auth(api.get('/api/hr/budget-categories?useFor=budget&concessionId='+concessionB))).status,403);
 await configure('OWN');assert.equal((await auth(api.get(`/api/hr/budget-categories?useFor=budget&concessionId=${concessionA}`))).status,403);assert.equal((await category(concessionA,'OWN_FORBIDDEN','Interdite')).status,403);
 await configure('CONCESSION');response=await auth(api.post('/api/hr/budgets')).send(budgetPayload(agencyA1,marketingA));assert.equal(response.status,201,JSON.stringify(response.body));const budgetA=String(response.body.id);assert.equal((await auth(api.post('/api/hr/budgets')).send(budgetPayload(agencyA1,marketingB))).status,400);response=await auth(api.post(`/api/hr/budgets/${budgetA}/expenses`)).send(expensePayload(marketingA));assert.equal(response.status,201);const inheritedExpense=String(response.body.id);response=await auth(api.post(`/api/hr/budgets/${budgetA}/expenses`)).send(expensePayload(itA));assert.equal(response.status,201);assert.equal((await auth(api.post(`/api/hr/budgets/${budgetA}/expenses`)).send(expensePayload(marketingB))).status,400);response=await auth(api.post(`/api/hr/budgets/${budgetA}/expenses`)).send(expensePayload());assert.equal(response.status,201);const nullExpense=String(response.body.id);let[rows]=await query<RowDataPacket[]>('SELECT b.category_id,b.category,e.category_id,e.category FROM budgets b JOIN budget_expenses e ON e.id=? WHERE b.id=?',[inheritedExpense,budgetA]);assert.equal(String(rows.category_id),marketingA);assert.equal(rows.category,'Marketing & communication');[rows]=await query<RowDataPacket[]>('SELECT category_id,category FROM budget_expenses WHERE id=?',[nullExpense]);assert.equal(rows.category_id,null);assert.equal(rows.category,null);
 assert.equal((await auth(api.patch(`/api/hr/budget-categories/${marketingA}`)).send({code:'MARKETING_NEW',name:'Marketing renommé'})).status,409);response=await auth(api.patch(`/api/hr/budget-categories/${marketingA}`)).send({code:'MARKETING',name:'Marketing renommé'});assert.equal(response.status,200);[rows]=await query<RowDataPacket[]>('SELECT category_id,category FROM budgets WHERE id=?',[budgetA]);assert.equal(String(rows.category_id),marketingA);assert.equal(rows.category,'Marketing & communication');
 assert.equal((await auth(api.patch(`/api/hr/budget-categories/${marketingA}/status`)).send({isActive:false})).status,200);assert.equal((await auth(api.post('/api/hr/budgets')).send(budgetPayload(agencyA1,marketingA))).status,400);assert.equal((await auth(api.post(`/api/hr/budgets/${budgetA}/expenses`)).send(expensePayload(marketingA))).status,400);response=await auth(api.get(`/api/hr/budget-categories?useFor=budget&concessionId=${concessionA}`));assert.ok(!response.body.some((x:{id:string})=>x.id===marketingA));response=await auth(api.get('/api/hr/budget-categories?useFor=administration&includeInactive=true'));assert.ok(response.body.some((x:{id:string;is_active:boolean})=>x.id===marketingA&&!x.is_active));assert.equal((await auth(api.patch(`/api/hr/budget-categories/${marketingA}/status`)).send({isActive:true})).status,200);assert.equal((await auth(api.post('/api/hr/budgets')).send(budgetPayload(agencyA2,marketingA))).status,201);
 const concurrentCode=`CONCURRENT_${suffix.toUpperCase()}`,duplicates=await Promise.all([category(concessionA,concurrentCode,'Concurrent 1'),category(concessionA,concurrentCode,'Concurrent 2')]);assert.deepEqual(duplicates.map(x=>x.status).sort(),[201,409]);
 response=await category(concessionA,`LOCK_B_${suffix}`,'Verrou budget');const lockBudgetCategory=String(response.body.id);const budgetRace=await Promise.all([auth(api.post('/api/hr/budgets')).send(budgetPayload(agencyA1,lockBudgetCategory)),auth(api.patch(`/api/hr/budget-categories/${lockBudgetCategory}/status`)).send({isActive:false})]);assert.equal(budgetRace.find(x=>x.status===200)?.status,200);assert.ok(budgetRace.some(x=>x.status===201||x.status===400));
 response=await category(concessionA,`LOCK_E_${suffix}`,'Verrou dépense');const lockExpenseCategory=String(response.body.id);const expenseRace=await Promise.all([auth(api.post(`/api/hr/budgets/${budgetA}/expenses`)).send(expensePayload(lockExpenseCategory)),auth(api.patch(`/api/hr/budget-categories/${lockExpenseCategory}/status`)).send({isActive:false})]);assert.equal(expenseRace.find(x=>x.status===200)?.status,200);assert.ok(expenseRace.some(x=>x.status===201||x.status===400));
 const fakeUser=await insert('INSERT INTO users(agency_id,first_name,last_name,email,password_hash) VALUES(?,?,?,?,?)',[agencyA1,'Faux','Super Admin',`fake-super-${suffix}@test.local`,'test']),fakeRole=await insert('INSERT INTO roles(name,code,is_system,is_active) VALUES(?,?,FALSE,TRUE)',[`Super Admin ${suffix}`,`FAKE_SUPER_${suffix}`]);await execute('INSERT INTO user_roles(user_id,role_id) VALUES(?,?)',[fakeUser,fakeRole]);for(const code of['hr.budget.category.view','hr.budget.category.manage'])await execute('INSERT INTO role_permissions(role_id,permission_id,scope) VALUES(?,?,?)',[fakeRole,permissionId(code),'AGENCY']);const fakeToken=jwt.sign({sub:fakeUser,email:`fake-super-${suffix}@test.local`,roles:['SUPER_ADMIN'],agencyId:agencyA1},process.env.JWT_ACCESS_SECRET!,{expiresIn:'10m'}),fakeAuth=(request:supertest.Test)=>request.set('Authorization',`Bearer ${fakeToken}`);assert.equal((await fakeAuth(api.post('/api/hr/budget-categories')).send({concessionId:concessionB,code:'FAKE',name:'Fausse'})).status,403);
 const systemUser=await insert('INSERT INTO users(agency_id,first_name,last_name,email,password_hash) VALUES(?,?,?,?,?)',[agencyA1,'Vrai','Super Admin',`true-super-${suffix}@test.local`,'test']),[systemRole]=await query<RowDataPacket[]>("SELECT id FROM roles WHERE code='SUPER_ADMIN' AND is_system=TRUE AND is_active=TRUE");assert.ok(systemRole);await execute('INSERT INTO user_roles(user_id,role_id) VALUES(?,?)',[systemUser,systemRole.id]);const systemToken=jwt.sign({sub:systemUser,email:`true-super-${suffix}@test.local`,roles:[],agencyId:agencyA1},process.env.JWT_ACCESS_SECRET!,{expiresIn:'10m'}),systemAuth=(request:supertest.Test)=>request.set('Authorization',`Bearer ${systemToken}`);assert.equal((await systemAuth(api.post('/api/hr/budget-categories')).send({concessionId:concessionB,code:`SYSTEM_${suffix}`,name:'Système'})).status,201);
 const auditRows=await query<RowDataPacket[]>("SELECT action FROM audit_logs WHERE entity_type='budget_category' AND entity_id=?",[marketingA]);for(const action of['budget.category.created','budget.category.updated','budget.category.deactivated','budget.category.activated'])assert.ok(auditRows.some(row=>row.action===action));
});
