import assert from'node:assert/strict';
import{readFileSync}from'node:fs';
import test from'node:test';
const read=(path:string)=>readFileSync(new URL(path,import.meta.url),'utf8');
const migration=read('../database/migrations/064_employee_profiles_independent_identity.sql'),baseline=read('../database/baseline/001_initial_schema.sql'),routes=read('../src/modules/hr/hr.routes.ts'),users=read('../src/modules/users/user.service.ts'),ged=read('../src/modules/documents/document-access.ts'),seed=read('../database/seeds/001_system_seed.sql');

test('HR10-01..12 employé autonome, identité, salaire et GED sans user',()=>{for(const sql of[migration,baseline]){assert.match(sql,/user_id BIGINT UNSIGNED NULL/);assert.match(sql,/first_name VARCHAR\(100\)/);assert.match(sql,/concession_id BIGINT UNSIGNED NOT NULL/)}assert.match(routes,/INSERT INTO employee_profiles\(user_id[\s\S]*VALUES\(NULL/);assert.match(routes,/FROM employee_profiles ep JOIN concessions c[\s\S]*LEFT JOIN users u ON u.id=ep.user_id/);assert.match(routes,/salary_history\(employee_profile_id/);assert.match(ged,/FROM employee_profiles ep LEFT JOIN agencies/);assert.doesNotMatch(users,/INSERT INTO employee_profiles|UPDATE employee_profiles/)});
test('HR10-LINK-01..14 liaison explicite conserve les ressources employé',()=>{assert.match(routes,/\/hr\/employees\/:id\/link-user/);assert.match(routes,/\/hr\/employees\/:id\/unlink-user/);assert.match(routes,/SELECT ep\.\* FROM employee_profiles ep[\s\S]*FOR UPDATE/);assert.match(routes,/SELECT u\.id,u\.is_active[\s\S]*FOR UPDATE/);assert.match(routes,/ER_DUP_ENTRY/);assert.match(routes,/Compte ERP hors concession RH/);assert.match(routes,/employee\.user_linked/);assert.match(routes,/employee\.user_unlinked/);assert.doesNotMatch(routes,/DELETE FROM employee_profiles|UPDATE salary_history|DELETE FROM documents/)});
test('HR10-RBAC-01..12 scopes dynamiques et permission sensible persistée',()=>{assert.match(seed,/hr\.employee\.account\.manage/);assert.match(routes,/requirePermission\('hr.employee.account.manage'\)/);assert.match(routes,/if\(scope==='OWN'\)return\{sql:`\$\{alias\}\.user_id=\?`/);assert.match(routes,/if\(scope==='AGENCY'\)return\{sql:`\$\{alias\}\.agency_id=\?`/);assert.match(routes,/if\(scope==='CONCESSION'\)return\{sql:`\$\{alias\}\.concession_id=/);assert.doesNotMatch(routes,/SUPER_ADMIN.*(?:bypass|return true)/i)});
test('HR10-MIG-01 historique conservé, backfill déterministe, unicité et FK sûre',()=>{assert.match(migration,/UPDATE employee_profiles ep\s+JOIN users u ON u.id=ep.user_id\s+JOIN agencies a/);assert.match(migration,/MODIFY user_id BIGINT UNSIGNED NULL/);assert.match(migration,/FOREIGN KEY \(user_id\).*ON DELETE SET NULL/);assert.doesNotMatch(migration,/DELETE FROM employee_profiles|INSERT INTO employee_profiles|UPDATE salary_history|UPDATE documents/);assert.match(baseline,/user_id BIGINT UNSIGNED NULL UNIQUE/)});
test('HR10-AUDIT-RT acteurs users et événements après transaction',()=>{for(const action of['employee.created','employee.updated','employee.user_linked','employee.user_unlinked'])assert.match(routes,new RegExp(action.replaceAll('.','\\.')));assert.match(routes,/audit_logs\(user_id/);assert.match(routes,/emitToAgencyAndGlobals/);assert.match(baseline,/created_by BIGINT UNSIGNED NULL/)});
