import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import test from 'node:test';
import {consumeReservation,partsScopeAllows,reserveStock,stockAfterDelta} from '../src/modules/parts/parts-policy.js';
const source=(path:string)=>readFileSync(new URL(`../${path}`,import.meta.url),'utf8');
const route=source('src/modules/parts/part.routes.ts'),stock=source('src/modules/parts/part-stock.ts'),workshop=source('src/modules/workshop/workshop.routes.ts'),migration=source('database/legacy-migrations/032_parts_reservation_permissions.sql');

test('PARTS-01 AGENCY accepte son agence',()=>assert.equal(partsScopeAllows('AGENCY','1','1'),true));
test('PARTS-02 AGENCY refuse une autre agence',()=>assert.equal(partsScopeAllows('AGENCY','1','2'),false));
test('PARTS-03 CONCESSION accepte une agence sœur validée',()=>assert.equal(partsScopeAllows('CONCESSION','1','2',true),true));
test('PARTS-04 CONCESSION refuse une autre concession',()=>assert.equal(partsScopeAllows('CONCESSION','1','3',false),false));
test('PARTS-05 GLOBAL accepte toute agence',()=>assert.equal(partsScopeAllows('GLOBAL','1','99'),true));
test('PARTS-06 OWN refuse le stock collectif',()=>assert.equal(partsScopeAllows('OWN','1','1'),false));
test('PARTS-07 agencyId passe par le garde backend',()=>assert.match(route,/assertAgencyScope\(request,permission,agencyId\)/));
test('PARTS-08 destination de transfert est aussi contrôlée',()=>assert.match(route,/assertAgencyScope\(r,permission,da\)/));
test('PARTS-09 catalogue utilise catalog.view',()=>assert.match(route,/path\.startsWith\('\/parts'\).*parts\.catalog\.view/));
test('PARTS-10 gestion catalogue est séparée',()=>assert.match(route,/parts\.catalog\.manage/));
test('PARTS-11 stock view est spécialisé',()=>assert.match(route,/parts\.stock\.view/));
test('PARTS-12 reporting protège les prix',()=>assert.match(route,/mayViewReporting\?row\.purchase_price:null/));
test('PARTS-13 fournisseurs sont filtrés',()=>assert.match(route,/mayViewSuppliers\?row\.supplier_name:null/));
test('PARTS-14 commandes sont filtrées',()=>assert.match(route,/mayViewOrders\?query/));
test('PARTS-15 références ne divulguent pas fournisseurs et emplacements',()=>assert.match(route,/mayViewSuppliers.*mayViewStock.*Promise\.resolve\(\[\]\)/));
test('PARTS-16 delta valide conserve les réservations',()=>assert.deepEqual(stockAfterDelta(10,3,-2),{currentStock:8,reservedStock:3,availableStock:5}));
test('PARTS-17 delta sous le réservé est refusé',()=>assert.throws(()=>stockAfterDelta(10,3,-8),/insuffisant/));
test('PARTS-18 état négatif est refusé',()=>assert.throws(()=>stockAfterDelta(-1,0,1),/incohérent/));
test('PARTS-19 réservation de 3 sur 10',()=>assert.deepEqual(reserveStock(10,0,3),{currentStock:10,reservedStock:3,availableStock:7}));
test('PARTS-20 sur-réservation est refusée',()=>assert.throws(()=>reserveStock(10,3,8),/insuffisant/));
test('PARTS-21 réservation exacte du disponible',()=>assert.deepEqual(reserveStock(10,3,7),{currentStock:10,reservedStock:10,availableStock:0}));
test('PARTS-22 quantité réservation zéro refusée',()=>assert.throws(()=>reserveStock(10,0,0),/Quantité/));
test('PARTS-23 quantité réservation négative refusée',()=>assert.throws(()=>reserveStock(10,0,-1),/Quantité/));
test('PARTS-24 consommation décrémente physique et réservé',()=>assert.deepEqual(consumeReservation(10,3,3),{currentStock:7,reservedStock:0,availableStock:7}));
test('PARTS-25 double consommation est refusée',()=>assert.throws(()=>consumeReservation(7,0,3),/Cohérence/));
test('PARTS-26 ajustement exige permission dédiée',()=>assert.match(route,/adjustments.*parts\.stock\.adjust/s));
test('PARTS-27 inventaire respecte le réservé',()=>assert.match(route,/stock compté ne peut pas être inférieur au stock réservé/));
test('PARTS-28 transfert est transactionnel et produit deux mouvements',()=>{assert.match(route,/transfers.*transaction/s);assert.match(route,/transfer_out/);assert.match(route,/transfer_in/)});
test('PARTS-29 verrou stock utilise FOR UPDATE',()=>assert.match(stock,/FOR UPDATE/));
test('PARTS-30 réception est idempotente',()=>assert.match(route,/purchase_order_receipts.*idempotency_key/));
test('PARTS-31 réception seule incrémente le stock fournisseur',()=>assert.match(route,/receipts.*current_stock=\?/s));
test('PARTS-32 permissions réservation dédiées existent',()=>{for(const code of ['parts.reservation.view','parts.reservation.create','parts.reservation.release','parts.reservation.consume'])assert.match(migration,new RegExp(code.replaceAll('.','\\.')))});
test('PARTS-33 réservation Atelier ne dépend plus de stock.adjust',()=>{const block=workshop.slice(workshop.indexOf('"/repair-orders/:id/parts/reserve"'),workshop.indexOf('"/repair-orders/:id/parts/reservations/:reservationId"'));assert.match(block,/parts\.reservation\.create/);assert.doesNotMatch(block,/parts\.stock\.adjust/)});
test('PARTS-34 consommation et libération ont des permissions distinctes',()=>assert.match(workshop,/status==='consumed'\?'parts\.reservation\.consume':'parts\.reservation\.release'/));
test('PARTS-35 aucun rôle historique ne pilote Parts',()=>assert.doesNotMatch(route,/PARTS_MANAGER|MAGASINIER|STOREKEEPER|DIRECTOR|DIRECTION|SUPER_ADMIN/));
