import assert from 'node:assert/strict';
import {randomUUID} from 'node:crypto';
import {after,test} from 'node:test';
import supertest from 'supertest';
import type {ResultSetHeader,RowDataPacket} from 'mysql2/promise';
import {createApp} from '../src/app.js';
import {pool,query} from '../src/config/database.js';

const enabled=process.env.LCA_PR02_SAV03_DB_TEST==='1';
if(enabled)after(async()=>{await pool.end()});
const rows=(sql:string,params:unknown[]=[])=>query<RowDataPacket[]>(sql,params);
const insert=async(sql:string,params:unknown[]=[])=>String((await pool.execute<ResultSetHeader>(sql,params))[0].insertId);

test('PR-02 et SAV-OR-03 sur MySQL 8.4 isolé', {skip:!enabled},async()=>{
  const api=supertest(createApp());
  const suffix=randomUUID().slice(0,8);
  const adminLogin=await api.post('/api/auth/login').send({email:process.env.ADMIN_EMAIL,password:process.env.ADMIN_PASSWORD});
  assert.equal(adminLogin.status,200,JSON.stringify(adminLogin.body));
  const adminToken=adminLogin.body.accessToken as string;
  const auth=(request:supertest.Test,token=adminToken)=>request.set('Authorization',`Bearer ${token}`);
  const [admin]=await rows('SELECT password_hash FROM users WHERE email=?',[process.env.ADMIN_EMAIL]);
  const [mainAgency]=await rows('SELECT id,concession_id FROM agencies WHERE code=?',['LCA-BZV']);
  const agencyA=String(mainAgency.id);
  const agencyB=await insert('INSERT INTO agencies(concession_id,name,code) VALUES(?,?,?)',[mainAgency.concession_id,`Agence B ${suffix}`,`PR02_B_${suffix}`]);
  const [group]=await rows('SELECT id FROM groups_company LIMIT 1');
  const concessionC=await insert('INSERT INTO concessions(group_id,name,code) VALUES(?,?,?)',[group.id,`Concession C ${suffix}`,`PR02_C_${suffix}`]);
  const agencyC=await insert('INSERT INTO agencies(concession_id,name,code) VALUES(?,?,?)',[concessionC,`Agence C ${suffix}`,`PR02_AC_${suffix}`]);
  const makeRole=async(name:string,permissions:string[],scope:'OWN'|'AGENCY'|'CONCESSION'|'GLOBAL')=>{
    const role=await insert('INSERT INTO roles(code,name,is_active,is_system) VALUES(?,?,TRUE,FALSE)',[`QA_${name}_${suffix}`,`${name} ${suffix}`]);
    for(const code of permissions){const [permission]=await rows('SELECT id FROM permissions WHERE code=?',[code]);assert.ok(permission,code);await pool.execute('INSERT INTO role_permissions(role_id,permission_id,scope) VALUES(?,?,?)',[role,permission.id,scope]);}
    return role;
  };
  const makeUser=async(role:string,agency:string,name:string)=>{
    const email=`${name.toLowerCase()}-${suffix}@example.test`;
    const id=await insert('INSERT INTO users(agency_id,first_name,last_name,email,password_hash,is_active) VALUES(?,?,?,?,?,TRUE)',[agency,'Recette',name,email,admin.password_hash]);
    await pool.execute('INSERT INTO user_roles(user_id,role_id) VALUES(?,?)',[id,role]);
    const login=await api.post('/api/auth/login').send({email,password:process.env.ADMIN_PASSWORD});
    assert.equal(login.status,200,JSON.stringify(login.body));
    return{id,token:login.body.accessToken as string};
  };

  const category=await auth(api.post('/api/part-categories')).send({name:`Freinage ${suffix}`,code:`PR02_${suffix}`});
  assert.equal(category.status,201,JSON.stringify(category.body));
  const locA=await insert('INSERT INTO locations(agency_id,name,type,is_active) VALUES(?,?,?,TRUE)',[agencyA,`A-01 ${suffix}`,'warehouse']);
  const locB=await insert('INSERT INTO locations(agency_id,name,type,is_active) VALUES(?,?,?,TRUE)',[agencyB,`B-01 ${suffix}`,'warehouse']);
  const locInactive=await insert('INSERT INTO locations(agency_id,name,type,is_active) VALUES(?,?,?,FALSE)',[agencyA,`A-02 ${suffix}`,'warehouse']);
  const partsRole=await makeRole('CataloguePolyvalent',['parts.catalog.view','parts.catalog.manage','parts.inventory.manage'],'AGENCY');
  const partsUser=await makeUser(partsRole,agencyA,'Pieces');
  const references=await auth(api.get('/api/part-references').query({agencyId:agencyA}),partsUser.token);
  assert.equal(references.status,200,JSON.stringify(references.body));
  assert.ok(references.body.categories.some((item:RowDataPacket)=>String(item.id)===category.body.id));
  const offeredLocations=references.body.locations.map((item:RowDataPacket)=>String(item.id));
  assert.ok(offeredLocations.includes(locA));
  assert.ok(!offeredLocations.includes(locB));
  assert.ok(!offeredLocations.includes(locInactive));
  const partBody={agencyId:agencyA,reference:`PR02-P-${suffix}`,name:'Plaquette recette',categoryId:category.body.id,locationId:locA,initialQuantity:3};
  const part=await auth(api.post('/api/parts'),partsUser.token).send(partBody);
  assert.equal(part.status,201,JSON.stringify(part.body));
  const reloadedPart=await auth(api.get(`/api/parts/${part.body.id}`).query({agencyId:agencyA}));
  assert.equal(reloadedPart.status,200,JSON.stringify(reloadedPart.body));
  assert.equal(String(reloadedPart.body.category_id),category.body.id);
  assert.equal(String(reloadedPart.body.stocks[0].location_id),locA);
  assert.equal(Number(reloadedPart.body.stocks[0].current_stock),3);
  const forgedPart=await auth(api.post('/api/parts'),partsUser.token).send({...partBody,reference:`PR02-BAD-${suffix}`,locationId:locB});
  assert.equal(forgedPart.status,400,JSON.stringify(forgedPart.body));
  const inactivePart=await auth(api.post('/api/parts'),partsUser.token).send({...partBody,reference:`PR02-INACTIVE-${suffix}`,locationId:locInactive});
  assert.equal(inactivePart.status,400);
  const wrongAgency=await auth(api.get('/api/part-references').query({agencyId:agencyB}),partsUser.token);
  assert.equal(wrongAgency.status,403);

  const brand=await insert('INSERT INTO brands(name,code) VALUES(?,?)',[`Marque ${suffix}`,`PR02_BR_${suffix}`]);
  const model=await insert('INSERT INTO models(brand_id,name) VALUES(?,?)',[brand,`Modèle ${suffix}`]);
  const version=await insert('INSERT INTO versions(model_id,name) VALUES(?,?)',[model,'Standard']);
  const customer=async(code:string,agency:string,assignee?:string)=>insert('INSERT INTO customers(customer_code,agency_id,first_name,last_name,assigned_user_id) VALUES(?,?,?,?,?)',[`CLI_${code}_${suffix}`,agency,'Client',code,assignee??null]);
  const customerA=await customer('A',agencyA),customerMulti=await customer('MULTI',agencyA),customerB=await customer('B',agencyB),customerC=await customer('C',agencyC);
  const linkVehicle=async(customerId:string,agency:string,n:number)=>{
    const vehicle=await insert('INSERT INTO vehicles(version_id,agency_id,vin) VALUES(?,?,?)',[version,agency,`PR02${suffix}${n}`]);
    const sale=await insert('INSERT INTO sales(sale_number,customer_id,agency_id) VALUES(?,?,?)',[`PR02-S-${suffix}-${n}`,customerId,agency]);
    await pool.execute('INSERT INTO sale_items(sale_id,vehicle_id,description) VALUES(?,?,?)',[sale,vehicle,'Véhicule recette']);
    return vehicle;
  };
  const vehicleA=await linkVehicle(customerA,agencyA,1);
  const vehicleM1=await linkVehicle(customerMulti,agencyA,2);
  const vehicleM2=await linkVehicle(customerMulti,agencyA,3);
  const vehicleB=await linkVehicle(customerB,agencyB,4);
  const vehicleC=await linkVehicle(customerC,agencyC,5);
  const servicePermissions=['service.order.create','service.order.receive'];
  const agencyRole=await makeRole('AgentAtelier',servicePermissions,'AGENCY');
  const agencyUser=await makeUser(agencyRole,agencyA,'Atelier');
  const deniedPartReferences=await auth(api.get('/api/part-references').query({agencyId:agencyA}),agencyUser.token);
  assert.equal(deniedPartReferences.status,403);
  const deniedCustomers=await auth(api.get('/api/customers'),agencyUser.token);
  assert.equal(deniedCustomers.status,403);
  const agencyCustomers=await auth(api.get('/api/repair-orders/customer-candidates'),agencyUser.token);
  assert.equal(agencyCustomers.status,200,JSON.stringify(agencyCustomers.body));
  assert.ok(agencyCustomers.body.some((item:{id:string})=>item.id===customerA));
  assert.ok(!agencyCustomers.body.some((item:{id:string})=>item.id===customerB));
  const oneVehicle=await auth(api.get('/api/repair-orders/customer-vehicles').query({customerId:customerA}),agencyUser.token);
  assert.deepEqual(oneVehicle.body.map((item:{id:string})=>item.id),[vehicleA]);
  const several=await auth(api.get('/api/repair-orders/customer-vehicles').query({customerId:customerMulti}),agencyUser.token);
  assert.deepEqual(several.body.map((item:{id:string})=>item.id).sort(),[vehicleM1,vehicleM2].sort());
  const forgedClient=await auth(api.post('/api/repair-orders'),agencyUser.token).send({customerId:customerB,vehicleId:vehicleB,advisorId:agencyUser.id,agencyId:agencyB,complaint:'Interdit'});
  assert.equal(forgedClient.status,403,JSON.stringify(forgedClient.body));
  const order=await auth(api.post('/api/repair-orders'),agencyUser.token).send({customerId:customerA,vehicleId:vehicleA,advisorId:agencyUser.id,complaint:'Contrôle atelier'});
  assert.equal(order.status,201,JSON.stringify(order.body));
  const reloaded=await auth(api.get(`/api/repair-orders/${order.body.id}`));
  assert.equal(reloaded.status,200,JSON.stringify(reloaded.body));
  assert.equal(String(reloaded.body.customer_id),customerA);
  assert.equal(String(reloaded.body.vehicle_id),vehicleA);
  assert.equal(String(reloaded.body.advisor_id),agencyUser.id);
  const concessionRole=await makeRole('PolyvalentConcession',servicePermissions,'CONCESSION');
  const concessionUser=await makeUser(concessionRole,agencyA,'Concession');
  const concessionCustomers=await auth(api.get('/api/repair-orders/customer-candidates'),concessionUser.token);
  assert.ok(concessionCustomers.body.some((item:{id:string})=>item.id===customerB));
  assert.ok(!concessionCustomers.body.some((item:{id:string})=>item.id===customerC));
  const concessionAdvisors=await auth(api.get('/api/repair-orders/advisor-candidates').query({targetAgency:agencyB}),concessionUser.token);
  assert.ok(concessionAdvisors.body.some((item:{id:string})=>item.id===concessionUser.id));
  const concessionOrder=await auth(api.post('/api/repair-orders'),concessionUser.token).send({customerId:customerB,vehicleId:vehicleB,advisorId:concessionUser.id,complaint:'Agence sœur'});
  assert.equal(concessionOrder.status,201,JSON.stringify(concessionOrder.body));
  const [savedConcessionOrder]=await rows('SELECT agency_id FROM repair_orders WHERE id=?',[concessionOrder.body.id]);
  assert.equal(String(savedConcessionOrder.agency_id),agencyB);
  const globalRole=await makeRole('PolyvalentGlobal',servicePermissions,'GLOBAL');
  const globalUser=await makeUser(globalRole,agencyA,'Global');
  const globalCustomers=await auth(api.get('/api/repair-orders/customer-candidates'),globalUser.token);
  assert.ok(globalCustomers.body.some((item:{id:string})=>item.id===customerC));
  const globalAdvisors=await auth(api.get('/api/repair-orders/advisor-candidates').query({targetAgency:agencyC}),globalUser.token);
  assert.ok(globalAdvisors.body.some((item:{id:string})=>item.id===globalUser.id));
  const globalOrder=await auth(api.post('/api/repair-orders'),globalUser.token).send({customerId:customerC,vehicleId:vehicleC,advisorId:globalUser.id,complaint:'Autre concession'});
  assert.equal(globalOrder.status,201,JSON.stringify(globalOrder.body));
  const [savedGlobalOrder]=await rows('SELECT agency_id FROM repair_orders WHERE id=?',[globalOrder.body.id]);
  assert.equal(String(savedGlobalOrder.agency_id),agencyC);
  const emptyRole=await makeRole('ConseillerSAVSansPermission',[],'AGENCY');
  const emptyUser=await makeUser(emptyRole,agencyA,'SansPermission');
  const noPrivilege=await auth(api.get('/api/repair-orders/customer-candidates'),emptyUser.token);
  assert.equal(noPrivilege.status,403);
  const ownRole=await makeRole('AgentOwn',servicePermissions,'OWN');
  const ownUser=await makeUser(ownRole,agencyA,'Own');
  const ownCustomer=await customer('OWN',agencyA,ownUser.id);
  const ownList=await auth(api.get('/api/repair-orders/customer-candidates'),ownUser.token);
  assert.deepEqual(ownList.body.map((item:{id:string})=>item.id),[ownCustomer]);
});
