import assert from 'node:assert/strict';
import {randomUUID} from 'node:crypto';
import {after,test} from 'node:test';
import supertest from 'supertest';
import type {ResultSetHeader,RowDataPacket} from 'mysql2/promise';
import {createApp} from '../src/app.js';
import {pool,query} from '../src/config/database.js';

const enabled=process.env.LCA_PR03_DB_TEST==='1';
if(enabled)after(async()=>{await pool.end()});
const rows=(sql:string,params:unknown[]=[])=>query<RowDataPacket[]>(sql,params);
const insert=async(sql:string,params:unknown[]=[])=>String((await pool.execute<ResultSetHeader>(sql,params))[0].insertId);

test('PR-03 administration des emplacements sur MySQL 8.4 isolé',{skip:!enabled},async()=>{
  const api=supertest(createApp());
  const suffix=randomUUID().slice(0,8);
  const adminLogin=await api.post('/api/auth/login').send({email:process.env.ADMIN_EMAIL,password:process.env.ADMIN_PASSWORD});
  assert.equal(adminLogin.status,200,JSON.stringify(adminLogin.body));
  const adminToken=adminLogin.body.accessToken as string;
  const auth=(request:supertest.Test,token=adminToken)=>request.set('Authorization',`Bearer ${token}`);
  const [admin]=await rows('SELECT password_hash FROM users WHERE email=?',[process.env.ADMIN_EMAIL]);
  const [home]=await rows('SELECT id,concession_id FROM agencies WHERE code=?',['LCA-BZV']);
  const agencyA=String(home.id);
  const agencyB=await insert('INSERT INTO agencies(concession_id,name,code) VALUES(?,?,?)',[home.concession_id,`Agence B ${suffix}`,`PR03_B_${suffix}`]);
  const [group]=await rows('SELECT id FROM groups_company LIMIT 1');
  const externalConcession=await insert('INSERT INTO concessions(group_id,name,code) VALUES(?,?,?)',[group.id,`Concession C ${suffix}`,`PR03_C_${suffix}`]);
  const agencyC=await insert('INSERT INTO agencies(concession_id,name,code) VALUES(?,?,?)',[externalConcession,`Agence C ${suffix}`,`PR03_AC_${suffix}`]);
  const permissions=['parts.catalog.view','parts.catalog.manage','parts.inventory.manage','parts.stock.view'];
  const makeRole=async(name:string,codes:string[],scope:'AGENCY'|'CONCESSION'|'GLOBAL')=>{
    const role=await insert('INSERT INTO roles(code,name,is_active,is_system) VALUES(?,?,TRUE,FALSE)',[`PR03_${name}_${suffix}`,`${name} ${suffix}`]);
    for(const code of codes){const [permission]=await rows('SELECT id FROM permissions WHERE code=?',[code]);assert.ok(permission,code);await pool.execute('INSERT INTO role_permissions(role_id,permission_id,scope) VALUES(?,?,?)',[role,permission.id,scope]);}
    return role;
  };
  const makeUser=async(role:string,agency:string,name:string)=>{
    const email=`pr03-${name.toLowerCase()}-${suffix}@example.test`;
    const id=await insert('INSERT INTO users(agency_id,first_name,last_name,email,password_hash,is_active) VALUES(?,?,?,?,?,TRUE)',[agency,'Recette',name,email,admin.password_hash]);
    await pool.execute('INSERT INTO user_roles(user_id,role_id) VALUES(?,?)',[id,role]);
    const login=await api.post('/api/auth/login').send({email,password:process.env.ADMIN_PASSWORD});
    assert.equal(login.status,200,JSON.stringify(login.body));
    return{id,token:login.body.accessToken as string};
  };
  const agencyRole=await makeRole('Polyvalent',permissions,'AGENCY');
  const actorA=await makeUser(agencyRole,agencyA,'A');
  const actorB=await makeUser(agencyRole,agencyB,'B');
  const noRole=await makeRole('Magasinier',[],'AGENCY');
  const noAccess=await makeUser(noRole,agencyA,'SansPermission');
  const category=await auth(api.post('/api/part-categories')).send({name:`Freinage ${suffix}`,code:`FREIN_${suffix}`});
  assert.equal(category.status,201);

  const agenciesA=await auth(api.get('/api/part-locations/agencies'),actorA.token);
  assert.deepEqual(agenciesA.body.map((item:{id:string})=>item.id),[agencyA]);
  const invalidName=await auth(api.post('/api/part-locations').query({targetAgency:agencyA}),actorA.token).send({name:'   '});
  assert.equal(invalidName.status,400);
  const invalidType=await auth(api.post('/api/part-locations').query({targetAgency:agencyA}),actorA.token).send({name:'Interdit',type:'showroom'});
  assert.equal(invalidType.status,400);
  const createLocation=async(targetAgency:string,name:string,token:string)=>auth(api.post('/api/part-locations').query({targetAgency}),token).send({name,address:`Repère ${name}`,isActive:true});
  const createdA1=await createLocation(agencyA,`A-01 ${suffix}`,actorA.token);
  const createdA2=await createLocation(agencyA,`A-02 ${suffix}`,actorA.token);
  const createdB=await createLocation(agencyB,`B-01 ${suffix}`,actorB.token);
  for(const response of [createdA1,createdA2,createdB])assert.equal(response.status,201,JSON.stringify(response.body));
  const locA1=createdA1.body.id as string,locA2=createdA2.body.id as string,locB=createdB.body.id as string;
  const listA=await auth(api.get('/api/part-locations').query({targetAgency:agencyA}),actorA.token);
  assert.equal(listA.status,200);
  assert.ok(listA.body.some((item:{id:string})=>item.id===locA1));
  assert.ok(listA.body.some((item:{id:string})=>item.id===locA2));
  assert.ok(!listA.body.some((item:{id:string})=>item.id===locB));
  const listB=await auth(api.get('/api/part-locations').query({targetAgency:agencyB}),actorB.token);
  assert.ok(listB.body.some((item:{id:string})=>item.id===locB));
  const deniedList=await auth(api.get('/api/part-locations').query({targetAgency:agencyB}),actorA.token);
  assert.equal(deniedList.status,403);
  const deniedCreate=await createLocation(agencyB,'Interdit',actorA.token);
  assert.equal(deniedCreate.status,403);
  const deniedNoPermission=await createLocation(agencyA,'Interdit',noAccess.token);
  assert.equal(deniedNoPermission.status,403);
  const deniedForeignEdit=await auth(api.patch(`/api/part-locations/${locB}`),actorA.token).send({name:'Hors scope'});
  assert.equal(deniedForeignEdit.status,403);
  const forgedMove=await auth(api.patch(`/api/part-locations/${locA1}`),actorA.token).send({agencyId:agencyB,name:'Déplacement interdit'});
  assert.ok([400,403].includes(forgedMove.status));
  const forgedStock=await auth(api.post('/api/parts'),actorA.token).send({agencyId:agencyA,reference:`PR03-BAD-${suffix}`,name:'Pièce invalide',categoryId:category.body.id,locationId:locB,initialQuantity:2});
  assert.equal(forgedStock.status,400);

  const references=await auth(api.get('/api/part-references').query({agencyId:agencyA}),actorA.token);
  assert.ok(references.body.categories.some((item:{id:string})=>String(item.id)===category.body.id));
  assert.ok(references.body.locations.some((item:{id:string})=>String(item.id)===locA1));
  assert.ok(!references.body.locations.some((item:{id:string})=>String(item.id)===locB));
  const part=await auth(api.post('/api/parts'),actorA.token).send({agencyId:agencyA,reference:`PR03-P-${suffix}`,name:'Plaquette recette',categoryId:category.body.id,locationId:locA1,initialQuantity:5});
  assert.equal(part.status,201,JSON.stringify(part.body));
  const reloaded=await auth(api.get(`/api/parts/${part.body.id}`).query({agencyId:agencyA}),actorA.token);
  assert.equal(reloaded.status,200,JSON.stringify(reloaded.body));
  assert.equal(String(reloaded.body.category_id),category.body.id);
  assert.equal(String(reloaded.body.stocks[0].agency_id),agencyA);
  assert.equal(String(reloaded.body.stocks[0].location_id),locA1);
  assert.equal(Number(reloaded.body.stocks[0].current_stock),5);
  const deactivate=await auth(api.patch(`/api/part-locations/${locA1}`),actorA.token).send({isActive:false,name:`A-01 ${suffix} modifié`});
  assert.equal(deactivate.status,200,JSON.stringify(deactivate.body));
  const afterDeactivate=await auth(api.get('/api/part-references').query({agencyId:agencyA}),actorA.token);
  assert.ok(!afterDeactivate.body.locations.some((item:{id:string})=>String(item.id)===locA1));
  const [historical]=await rows('SELECT location_id,current_stock FROM part_stocks WHERE part_id=?',[part.body.id]);
  assert.equal(String(historical.location_id),locA1);
  assert.equal(Number(historical.current_stock),5);
  const inactiveStock=await auth(api.post('/api/parts'),actorA.token).send({agencyId:agencyA,reference:`PR03-INACTIVE-${suffix}`,name:'Pièce invalide',categoryId:category.body.id,locationId:locA1,initialQuantity:1});
  assert.equal(inactiveStock.status,400);
  const listInactive=await auth(api.get('/api/part-locations').query({targetAgency:agencyA}),actorA.token);
  assert.ok(listInactive.body.some((item:{id:string;isActive:boolean})=>item.id===locA1&&!item.isActive));

  const concessionRole=await makeRole('Concession',permissions,'CONCESSION');
  const concessionUser=await makeUser(concessionRole,agencyA,'Concession');
  const concessionAgencies=await auth(api.get('/api/part-locations/agencies'),concessionUser.token);
  assert.ok(concessionAgencies.body.some((item:{id:string})=>item.id===agencyB));
  assert.ok(!concessionAgencies.body.some((item:{id:string})=>item.id===agencyC));
  const concessionCreate=await createLocation(agencyB,`B-02 ${suffix}`,concessionUser.token);
  assert.equal(concessionCreate.status,201,JSON.stringify(concessionCreate.body));
  const concessionDenied=await createLocation(agencyC,'Interdit',concessionUser.token);
  assert.equal(concessionDenied.status,403);
  const globalRole=await makeRole('Global',permissions,'GLOBAL');
  const globalUser=await makeUser(globalRole,agencyA,'Global');
  const globalAgencies=await auth(api.get('/api/part-locations/agencies'),globalUser.token);
  assert.ok(globalAgencies.body.some((item:{id:string})=>item.id===agencyC));
  const globalCreate=await createLocation(agencyC,`C-01 ${suffix}`,globalUser.token);
  assert.equal(globalCreate.status,201,JSON.stringify(globalCreate.body));
});
