import assert from 'node:assert/strict';
import {randomUUID} from 'node:crypto';
import {after,test} from 'node:test';
import supertest from 'supertest';
import type {ResultSetHeader,RowDataPacket} from 'mysql2/promise';
import {createApp} from '../src/app.js';
import {pool,query} from '../src/config/database.js';

const enabled=process.env.LCA_SAV1618_DB_TEST==='1';
if(enabled)after(async()=>pool.end());
const rows=(sql:string,params:unknown[]=[])=>query<RowDataPacket[]>(sql,params);
const insert=async(sql:string,params:unknown[]=[])=>String((await pool.execute<ResultSetHeader>(sql,params))[0].insertId);

test('SAV-OR-16 à 18 sur MySQL 8.4 : étapes, annulation et finance séparée',{skip:!enabled},async()=>{
  const api=supertest(createApp()),suffix=randomUUID().slice(0,8);
  const login=await api.post('/api/auth/login').send({email:process.env.ADMIN_EMAIL,password:process.env.ADMIN_PASSWORD});assert.equal(login.status,200,JSON.stringify(login.body));
  const token=login.body.accessToken as string,auth=(request:supertest.Test)=>request.set('Authorization',`Bearer ${token}`);
  const[admin]=await rows('SELECT id,password_hash,agency_id FROM users WHERE email=?',[process.env.ADMIN_EMAIL]),agency=String(admin.agency_id);
  const brand=await insert('INSERT INTO brands(name,code) VALUES(?,?)',[`SAV1618 ${suffix}`,`S1618_${suffix}`]),model=await insert('INSERT INTO models(brand_id,name) VALUES(?,?)',[brand,'Modèle']),version=await insert('INSERT INTO versions(model_id,name) VALUES(?,?)',[model,'Version']);
  const customer=await insert('INSERT INTO customers(customer_code,agency_id,first_name,last_name) VALUES(?,?,?,?)',[`C1618_${suffix}`,agency,'Client','SAV']),vehicle=await insert('INSERT INTO vehicles(version_id,agency_id,vin) VALUES(?,?,?)',[version,agency,`S1618${suffix}VIN`]);
  const role=await insert('INSERT INTO roles(code,name,is_active,is_system) VALUES(?,?,TRUE,FALSE)',[`TECH1618_${suffix}`,'Technicien recette']);const[track]=await rows("SELECT id FROM permissions WHERE code='workshop.session.track'");await pool.execute("INSERT INTO role_permissions(role_id,permission_id,scope) VALUES(?,?,'AGENCY')",[role,track.id]);
  const techUser=await insert('INSERT INTO users(agency_id,first_name,last_name,email,password_hash,is_active) VALUES(?,?,?,?,?,TRUE)',[agency,'Tech','Recette',`tech-${suffix}@test.local`,admin.password_hash]);await pool.execute('INSERT INTO user_roles(user_id,role_id) VALUES(?,?)',[techUser,role]);
  const makeOrder=async(status:string)=>insert('INSERT INTO repair_orders(order_number,customer_id,vehicle_id,agency_id,advisor_id,mileage_in,complaint,status,created_by) VALUES(?,?,?,?,?,100,?,?,?)',[`OR-${status}-${suffix}-${randomUUID().slice(0,4)}`,customer,vehicle,agency,admin.id,'Test SAV',status,admin.id]);
  const cancelAllowed=['planned','received','diagnosis','waiting_approval','in_progress','quality_control'];
  for(const status of cancelAllowed){const id=await makeOrder(status),response=await auth(api.patch(`/api/repair-orders/${id}/status`)).send({status:'cancelled',reason:`Annulation ${status}`});assert.equal(response.status,200,`${status}: ${JSON.stringify(response.body)}`);const[current]=await rows('SELECT status FROM repair_orders WHERE id=?',[id]);assert.equal(current.status,'cancelled')}
  for(const status of ['ready','invoiced','delivered','closed']){const id=await makeOrder(status);await pool.execute("INSERT INTO repair_order_items(repair_order_id,item_type,description,quantity,unit_price,discount,tax_rate,line_total) VALUES(?,'labor','Conservée',1,1000,0,0,1000)",[id]);const[beforeHistory]=await rows("SELECT COUNT(*) total FROM repair_order_status_history WHERE repair_order_id=? AND new_status='cancelled'",[id]),response=await auth(api.patch(`/api/repair-orders/${id}/status`)).send({status:'cancelled',reason:'Tentative interdite'});assert.equal(response.status,409,status);const[current]=await rows('SELECT status FROM repair_orders WHERE id=?',[id]);assert.equal(current.status,status);const[afterHistory]=await rows("SELECT COUNT(*) total FROM repair_order_status_history WHERE repair_order_id=? AND new_status='cancelled'",[id]),[items]=await rows('SELECT COUNT(*) total FROM repair_order_items WHERE repair_order_id=?',[id]);assert.equal(Number(afterHistory.total),Number(beforeHistory.total));assert.equal(Number(items.total),1)}

  const id=await makeOrder('planned'),route=(path:string)=>`/api/repair-orders/${id}${path}`;
  assert.equal((await auth(api.post(route('/diagnostics'))).send({diagnosis:'Trop tôt',estimatedHours:1})).status,409);
  assert.equal((await auth(api.post(route('/interventions'))).send({description:'Trop tôt',plannedHours:1})).status,409);
  assert.equal((await auth(api.post(route('/items'))).send({itemType:'labor',description:'Trop tôt',quantity:1,unitPrice:1000})).status,409);
  const inspection=await auth(api.post(route('/inspection'))).send({fuelLevel:'Moitié',cleanliness:'Propre'});assert.equal(inspection.status,200,JSON.stringify(inspection.body));await pool.execute("UPDATE repair_orders SET status='received' WHERE id=?",[id]);assert.equal((await auth(api.post(route('/inspection'))).send({fuelLevel:'Plein',cleanliness:'Propre'})).status,409);
  assert.equal((await auth(api.post(route('/diagnostics'))).send({diagnosis:'Diagnostic réel',estimatedHours:2.5})).status,201);assert.equal((await auth(api.post(route('/interventions'))).send({description:'Toujours trop tôt',plannedHours:1})).status,409);
  await pool.execute("INSERT INTO repair_order_estimate_items(repair_order_id,item_type,description,quantity,unit_price,tax_rate,line_total,created_by) VALUES(?,'labor','Chiffrage SAV',2,35000,0,70000,?)",[id,admin.id]);await pool.execute("UPDATE repair_orders SET status='waiting_approval',estimated_total=70000 WHERE id=?",[id]);const approval=await auth(api.post(route('/approval'))).send({approved:true,approvedAmount:70000,customerName:'Client SAV'});assert.equal(approval.status,201,JSON.stringify(approval.body));assert.equal((await auth(api.post(route('/approval'))).send({approved:true,customerName:'Client SAV'})).status,409);assert.equal((await auth(api.post(route('/interventions'))).send({description:'Encore trop tôt',plannedHours:1})).status,409);
  await pool.execute("UPDATE repair_orders SET status='in_progress' WHERE id=?",[id]);const interventionResponse=await auth(api.post(route('/interventions'))).send({technicianId:`u:${techUser}`,description:'Remplacement embrayage',plannedHours:2.5,rateCode:'T4',requestKey:randomUUID()});assert.equal(interventionResponse.status,201,JSON.stringify(interventionResponse.body));const intervention=String(interventionResponse.body.interventions.find((x:{description:string})=>x.description==='Remplacement embrayage').id),technician=String(interventionResponse.body.interventions.find((x:{id:string})=>String(x.id)===intervention).technician_id);const[operational]=await rows('SELECT planned_hours,unit_price,line_total FROM interventions WHERE id=?',[intervention]);assert.equal(Number(operational.planned_hours),2.5);assert.equal(Number(operational.unit_price),0);assert.equal(Number(operational.line_total),0);
  const started=await auth(api.post(route('/sessions/start'))).send({technicianId:technician,interventionId:intervention});assert.equal(started.status,201,JSON.stringify(started.body));await pool.execute('UPDATE work_sessions SET started_at=DATE_SUB(NOW(),INTERVAL 150 MINUTE) WHERE id=?',[started.body.id]);assert.equal((await auth(api.patch(route(`/sessions/${started.body.id}/stop`))).send({})).status,200);assert.equal((await auth(api.patch(route(`/sessions/${started.body.id}/stop`))).send({})).status,200);assert.equal((await auth(api.patch(route(`/interventions/${intervention}/status`))).send({status:'completed'})).status,200);
  const laborKey=randomUUID(),laborPayload={itemType:'labor',interventionId:intervention,description:'Main-d’œuvre embrayage',quantity:2,unitPrice:30000,requestKey:laborKey};assert.equal((await auth(api.post(route('/items'))).send(laborPayload)).status,201);assert.equal((await auth(api.post(route('/items'))).send(laborPayload)).status,201);
  await pool.execute("INSERT INTO repair_order_items(repair_order_id,item_type,description,quantity,unit_price,discount,tax_rate,line_total) VALUES(?,'part','Kit embrayage',1,10000,0,0,10000)",[id]);
  const[itemCounts]=await rows("SELECT COUNT(*) total,SUM(item_type='labor') labor_count,SUM(item_type='part') part_count FROM repair_order_items WHERE repair_order_id=? AND status='active'",[id]);assert.equal(Number(itemCounts.total),2);assert.equal(Number(itemCounts.labor_count),1);assert.equal(Number(itemCounts.part_count),1);const[labor]=await rows("SELECT quantity,unit_price,line_total FROM repair_order_items WHERE repair_order_id=? AND item_type='labor'",[id]);assert.equal(Number(labor.quantity),2);assert.equal(Number(labor.unit_price),30000);assert.equal(Number(labor.line_total),60000);const[time]=await rows('SELECT COUNT(*) total,SUM(hours) hours FROM time_entries WHERE repair_order_id=?',[id]);assert.equal(Number(time.total),1);assert.ok(Number(time.hours)>=2.49&&Number(time.hours)<=2.51,Number(time.hours));
  await pool.execute("INSERT INTO repair_quality_controls(repair_order_id,planned_work_completed,defect_corrected,no_leaks,levels_checked,cleanliness_checked,result,controlled_by) VALUES(?,TRUE,TRUE,TRUE,TRUE,TRUE,'passed',?)",[id,admin.id]);await pool.execute("UPDATE repair_orders SET status='quality_control',estimated_total=(SELECT SUM(line_total*(1+tax_rate/100)) FROM repair_order_items WHERE repair_order_id=? AND status='active') WHERE id=?",[id,id]);assert.equal((await auth(api.patch(route('/status'))).send({status:'ready'})).status,200);const invoice=await auth(api.post(route('/invoice'))).send({});assert.equal(invoice.status,201,JSON.stringify(invoice.body));const[totals]=await rows('SELECT ro.estimated_total,i.subtotal,i.total FROM repair_orders ro JOIN invoices i ON i.repair_order_id=ro.id WHERE ro.id=?',[id]);assert.equal(Number(totals.estimated_total),Number(totals.total));assert.equal(Number(totals.subtotal),70000);
  for(const status of ['quality_control','ready','invoiced','delivered','closed']){await pool.execute('UPDATE repair_orders SET status=? WHERE id=?',[status,id]);assert.equal((await auth(api.post(route('/interventions'))).send({description:'Interdite',plannedHours:1})).status,409);assert.equal((await auth(api.post(route('/sessions/start'))).send({technicianId:technician,interventionId:intervention})).status,409)}
});
