import assert from 'node:assert/strict';
import {randomUUID} from 'node:crypto';
import {after,test} from 'node:test';
import supertest from 'supertest';
import type{ResultSetHeader,RowDataPacket}from'mysql2/promise';
import{createApp}from'../src/app.js';
import{pool,query}from'../src/config/database.js';
const enabled=process.env.LCA_SAV21_DB_TEST==='1';if(enabled)after(async()=>pool.end());
const rows=(sql:string,p:unknown[]=[])=>query<RowDataPacket[]>(sql,p);const insert=async(sql:string,p:unknown[]=[])=>String((await pool.execute<ResultSetHeader>(sql,p))[0].insertId);

test('SAV-OR-21 relie baseline acceptée et réel sans doublon',{skip:!enabled},async()=>{
 const api=supertest(createApp()),suffix=randomUUID().slice(0,8),login=await api.post('/api/auth/login').send({email:process.env.ADMIN_EMAIL,password:process.env.ADMIN_PASSWORD});assert.equal(login.status,200);const auth=(r:supertest.Test)=>r.set('Authorization',`Bearer ${login.body.accessToken}`);const[admin]=await rows('SELECT id,agency_id FROM users WHERE email=?',[process.env.ADMIN_EMAIL]),agency=String(admin.agency_id);
 const brand=await insert('INSERT INTO brands(name,code)VALUES(?,?)',[`S21 ${suffix}`,`S21B_${suffix}`]),model=await insert('INSERT INTO models(brand_id,name)VALUES(?,?)',[brand,'M']),version=await insert('INSERT INTO versions(model_id,name)VALUES(?,?)',[model,'V']),customer=await insert('INSERT INTO customers(customer_code,agency_id,first_name,last_name)VALUES(?,?,?,?)',[`S21C_${suffix}`,agency,'Client','S21']),vehicle=await insert('INSERT INTO vehicles(version_id,agency_id,vin)VALUES(?,?,?)',[version,agency,`S21${suffix}VIN`]);
 const makeOrder=(label:string,status='in_progress')=>insert('INSERT INTO repair_orders(order_number,customer_id,vehicle_id,agency_id,advisor_id,status,created_by)VALUES(?,?,?,?,?,?,?)',[`OR-S21-${label}-${suffix}`,customer,vehicle,agency,admin.id,status,admin.id]);const order=await makeOrder('MAIN'),other=await makeOrder('OTHER'),historical=await makeOrder('HIST');
 await pool.execute('INSERT INTO repair_approvals(repair_order_id,approved,approved_amount,customer_name,recorded_by)VALUES(?,TRUE,195000,?,?)',[order,'Client S21',admin.id]);
 const labor=await insert("INSERT INTO repair_order_estimate_items(repair_order_id,item_type,description,quantity,unit_price,tax_rate,line_total,created_by)VALUES(?,'labor','Diagnostic moteur',3,25000,0,75000,?)",[order,admin.id]),part=await insert('INSERT INTO parts(reference,name,sale_price)VALUES(?,?,120000)',[`S21P-${suffix}`,'Bougies']),partEstimate=await insert("INSERT INTO repair_order_estimate_items(repair_order_id,part_id,item_type,description,quantity,unit_price,tax_rate,line_total,created_by)VALUES(?,?,'part','Bougies',4,30000,0,120000,?)",[order,part,admin.id]),location=await insert("INSERT INTO locations(agency_id,name,type,is_active)VALUES(?,?,'warehouse',TRUE)",[agency,`Magasin ${suffix}`]),stock=await insert('INSERT INTO part_stocks(part_id,agency_id,location_id,current_stock,reserved_stock)VALUES(?,?,?,10,0)',[part,agency,location]);
 const route=(tail:string)=>`/api/repair-orders/${order}${tail}`;const interventionRace=await Promise.all([auth(api.post(route(`/estimate-items/${labor}/intervention`))).send({plannedHours:10}),auth(api.post(route(`/estimate-items/${labor}/intervention`))).send({plannedHours:10})]);assert.ok(interventionRace.every(r=>r.status===201),JSON.stringify(interventionRace.map(r=>r.body)));const[interventions]=await rows('SELECT COUNT(*) total,MAX(planned_hours) hours,MAX(unit_price) price FROM interventions WHERE estimate_item_id=?',[labor]);assert.equal(Number(interventions.total),1);assert.equal(Number(interventions.hours),3);assert.equal(Number(interventions.price),25000);
 assert.equal((await auth(api.post(`/api/repair-orders/${other}/estimate-items/${labor}/intervention`)).send({})).status,404);
 const reserveRace=await Promise.all([auth(api.post(route(`/estimate-items/${partEstimate}/reserve`))).send({partStockId:stock,quantity:8}),auth(api.post(route(`/estimate-items/${partEstimate}/reserve`))).send({partStockId:stock,quantity:8})]);assert.ok(reserveRace.every(r=>r.status===201));const[reservation]=await rows('SELECT id,quantity,consumed_quantity FROM part_reservations WHERE estimate_item_id=?',[partEstimate]);assert.equal(Number(reservation.quantity),4);const[reservedStock]=await rows('SELECT current_stock,reserved_stock FROM part_stocks WHERE id=?',[stock]);assert.equal(Number(reservedStock.current_stock),10);assert.equal(Number(reservedStock.reserved_stock),4);
 const consume=await auth(api.patch(route(`/parts/reservations/${reservation.id}`))).send({status:'consumed',quantity:3});assert.equal(consume.status,200,JSON.stringify(consume.body));const[after]=await rows('SELECT current_stock,reserved_stock FROM part_stocks WHERE id=?',[stock]);assert.equal(Number(after.current_stock),7);assert.equal(Number(after.reserved_stock),1);const[reservedAfter]=await rows('SELECT quantity,consumed_quantity,status FROM part_reservations WHERE id=?',[reservation.id]);assert.equal(Number(reservedAfter.quantity),4);assert.equal(Number(reservedAfter.consumed_quantity),3);assert.equal(reservedAfter.status,'reserved');
 const[int]=await rows('SELECT id FROM interventions WHERE estimate_item_id=?',[labor]);const bill=await auth(api.post(route('/items'))).send({itemType:'labor',estimateItemId:labor,interventionId:int.id,description:'Forgée',quantity:2.5,rateCode:'T1',requestKey:randomUUID()});assert.equal(bill.status,201,JSON.stringify(bill.body));const[billable]=await rows('SELECT quantity,unit_price FROM repair_order_items WHERE estimate_item_id=?',[labor]);assert.equal(Number(billable.quantity),2.5);assert.equal(Number(billable.unit_price),25000);assert.equal((await auth(api.post(route('/items'))).send({itemType:'labor',estimateItemId:labor,interventionId:int.id,quantity:4,requestKey:randomUUID()})).status,409);
 const old=await auth(api.get(`/api/repair-orders/${historical}`));assert.equal(old.status,200);assert.deepEqual(old.body.estimateItems,[]);
 const[approval]=await rows('SELECT approved_amount FROM repair_approvals WHERE repair_order_id=?',[order]);assert.equal(Number(approval.approved_amount),195000);console.log('SAV_OR21_EVIDENCE',JSON.stringify({authorizedHours:3,plannedHours:Number(interventions.hours),billableHours:Number(billable.quantity),authorizedParts:4,reserved:4,consumed:3,stock:Number(after.current_stock),snapshot:Number(approval.approved_amount)}));
});
