import assert from 'node:assert/strict';
import {randomUUID} from 'node:crypto';
import {after,test} from 'node:test';
import supertest from 'supertest';
import type {ResultSetHeader,RowDataPacket} from 'mysql2/promise';
import {createApp} from '../src/app.js';
import {pool,query} from '../src/config/database.js';

const enabled=process.env.LCA_SAV0409_DB_TEST==='1';
if(enabled)after(async()=>pool.end());
const rows=(sql:string,params:unknown[]=[])=>query<RowDataPacket[]>(sql,params);
const insert=async(sql:string,params:unknown[]=[])=>String((await pool.execute<ResultSetHeader>(sql,params))[0].insertId);

test('SAV-OR-04 à 09 : techniciens, stock et main-d’œuvre sur MySQL 8.4',{skip:!enabled},async()=>{
  const api=supertest(createApp()),suffix=randomUUID().slice(0,8);
  const login=await api.post('/api/auth/login').send({email:process.env.ADMIN_EMAIL,password:process.env.ADMIN_PASSWORD});
  assert.equal(login.status,200,JSON.stringify(login.body));
  const token=login.body.accessToken as string,auth=(request:supertest.Test)=>request.set('Authorization',`Bearer ${token}`);
  const [admin]=await rows('SELECT id,password_hash,agency_id FROM users WHERE email=?',[process.env.ADMIN_EMAIL]);
  const agencyA=String(admin.agency_id),[home]=await rows('SELECT concession_id FROM agencies WHERE id=?',[agencyA]);
  const agencyB=await insert('INSERT INTO agencies(concession_id,name,code) VALUES(?,?,?)',[home.concession_id,`Agence B ${suffix}`,`SAV_B_${suffix}`]);
  const [group]=await rows('SELECT id FROM groups_company LIMIT 1');
  const otherConcession=await insert('INSERT INTO concessions(group_id,name,code) VALUES(?,?,?)',[group.id,`Concession X ${suffix}`,`SAV_C_${suffix}`]);
  const agencyC=await insert('INSERT INTO agencies(concession_id,name,code) VALUES(?,?,?)',[otherConcession,`Agence C ${suffix}`,`SAV_AC_${suffix}`]);
  const makeRole=async(name:string,codes:string[],scope:string)=>{const role=await insert('INSERT INTO roles(code,name,is_active,is_system) VALUES(?,?,TRUE,FALSE)',[`SAV_${name}_${suffix}`,`${name} ${suffix}`]);for(const code of codes){const [permission]=await rows('SELECT id FROM permissions WHERE code=?',[code]);assert.ok(permission,code);await pool.execute('INSERT INTO role_permissions(role_id,permission_id,scope) VALUES(?,?,?)',[role,permission.id,scope])}return role};
  const makeUser=async(name:string,role:string,agency=agencyA,active=true)=>{const user=await insert('INSERT INTO users(agency_id,first_name,last_name,email,password_hash,is_active) VALUES(?,?,?,?,?,?)',[agency,'Recette',name,`sav-${name}-${suffix}@example.test`,admin.password_hash,active]);await pool.execute('INSERT INTO user_roles(user_id,role_id) VALUES(?,?)',[user,role]);return user};
  const capability='workshop.session.track';
  const roleAgency=await makeRole('Polyvalent',[capability],'AGENCY'),roleNamed=await makeRole('Technicien',[],'AGENCY'),roleConcession=await makeRole('Concession',[capability],'CONCESSION'),roleGlobal=await makeRole('Global',[capability],'GLOBAL'),roleInactive=await makeRole('Inactif',[capability],'AGENCY'),roleAdvisor=await makeRole('Conseiller',['service.order.receive'],'AGENCY');
  const techA=await makeUser('A',roleAgency),techNoPermission=await makeUser('NomTechnicien',roleNamed),techInactive=await makeUser('Inactif',roleAgency,agencyA,false),techRoleInactive=await makeUser('RoleInactif',roleInactive),techB=await makeUser('B',roleAgency,agencyB),techConcession=await makeUser('C',roleConcession),techGlobal=await makeUser('G',roleGlobal),techOther=await makeUser('X',roleGlobal,agencyC);
  const advisor=await makeUser('Conseiller',roleAdvisor);
  await pool.execute('UPDATE roles SET is_active=FALSE WHERE id=?',[roleInactive]);
  const brand=await insert('INSERT INTO brands(name,code) VALUES(?,?)',[`Marque ${suffix}`,`SAV_BR_${suffix}`]);
  const model=await insert('INSERT INTO models(brand_id,name) VALUES(?,?)',[brand,`Modèle ${suffix}`]);
  const version=await insert('INSERT INTO versions(model_id,name) VALUES(?,?)',[model,'Standard']);
  const customer=await insert('INSERT INTO customers(customer_code,agency_id,first_name,last_name) VALUES(?,?,?,?)',[`SAV_CLI_${suffix}`,agencyA,'Client','Atelier']);
  const vehicle=await insert('INSERT INTO vehicles(version_id,agency_id,vin) VALUES(?,?,?)',[version,agencyA,`SAV${suffix}123`]);
  const sale=await insert('INSERT INTO sales(sale_number,customer_id,agency_id) VALUES(?,?,?)',[`SAV-S-${suffix}`,customer,agencyA]);
  await pool.execute('INSERT INTO sale_items(sale_id,vehicle_id,description) VALUES(?,?,?)',[sale,vehicle,'Véhicule client']);
  const order=await auth(api.post('/api/repair-orders')).send({customerId:customer,vehicleId:vehicle,advisorId:advisor,complaint:'Contrôle atelier'});
  assert.equal(order.status,201,JSON.stringify(order.body));const orId=order.body.id as string,route=(suffixPath:string)=>`/api/repair-orders/${orId}${suffixPath}`;
  const candidates=await auth(api.get(route('/technician-candidates')));assert.equal(candidates.status,200,JSON.stringify(candidates.body));
  const users=new Set(candidates.body.map((x:{userId:string})=>x.userId));
  for(const allowed of [techA,techConcession,techGlobal])assert.ok(users.has(allowed),allowed);
  for(const denied of [String(admin.id),techNoPermission,techInactive,techRoleInactive,techB,techOther])assert.ok(!users.has(denied),denied);
  const virtual=(user:string)=>String(candidates.body.find((x:{userId:string})=>x.userId===user).id);
  const badDiagnostic=async(technicianId:string)=>auth(api.post(route('/diagnostics'))).send({technicianId,diagnosis:'Tentative',estimatedHours:1});
  assert.equal((await auth(api.post(route('/inspection'))).send({})).status,400);
  const inspection=await auth(api.post(route('/inspection'))).send({fuelLevel:'Moitié',cleanliness:'Propre',mileage:100});assert.equal(inspection.status,200,JSON.stringify(inspection.body));
  const [minimalInspection]=await rows('SELECT fuel_level,cleanliness,bodywork_damage,items_in_vehicle,observations,customer_signature FROM vehicle_reception_inspections WHERE repair_order_id=?',[orId]);
  assert.equal(minimalInspection.fuel_level,'Moitié');assert.equal(minimalInspection.cleanliness,'Propre');for(const nullable of ['bodywork_damage','items_in_vehicle','observations','customer_signature'])assert.equal(minimalInspection[nullable],null);
  assert.equal((await auth(api.post(route('/inspection'))).send({observations:'Mise à jour partielle'})).status,200);
  const [updatedInspection]=await rows('SELECT fuel_level,cleanliness,observations FROM vehicle_reception_inspections WHERE repair_order_id=?',[orId]);assert.equal(updatedInspection.fuel_level,'Moitié');assert.equal(updatedInspection.cleanliness,'Propre');assert.equal(updatedInspection.observations,'Mise à jour partielle');
  const fullInspection={fuelLevel:'Plein',cleanliness:'Correcte',bodyworkDamage:'Rayure',itemsInVehicle:'Gilet',mileage:101,observations:'Complet',customerSignature:'signature'};
  assert.equal((await auth(api.post(route('/inspection'))).send(fullInspection)).status,200);
  for(const optional of ['bodyworkDamage','itemsInVehicle','mileage','observations','customerSignature']){const payload={...fullInspection} as Record<string,unknown>;delete payload[optional];assert.equal((await auth(api.post(route('/inspection'))).send(payload)).status,200,optional)}
  assert.equal((await auth(api.post(route('/inspection'))).send({observations:null,customerSignature:null})).status,200);
  assert.equal((await auth(api.post(route('/inspection'))).send({bodyworkDamage:{invalid:true}})).status,400);
  let status=await auth(api.patch(route('/status'))).send({status:'received'});assert.equal(status.status,200,JSON.stringify(status.body));
  for(const forged of [`u:${techNoPermission}`,`u:${techInactive}`,`u:${techRoleInactive}`,`u:${techB}`,`u:${admin.id}`])assert.equal((await badDiagnostic(forged)).status,400,forged);
  const diagnostic=await badDiagnostic(virtual(techA));assert.equal(diagnostic.status,201,JSON.stringify(diagnostic.body));
  const savedTech=String(diagnostic.body.diagnostics[0].technician_id);
  const [materialized]=await rows('SELECT user_id,agency_id FROM technicians WHERE id=?',[savedTech]);assert.equal(String(materialized.user_id),techA);assert.equal(String(materialized.agency_id),agencyA);
  const nextCandidates=await auth(api.get(route('/technician-candidates')));assert.ok(nextCandidates.body.some((x:{id:string})=>x.id===savedTech));
  status=await auth(api.patch(route('/status'))).send({status:'diagnosis'});assert.equal(status.status,200,JSON.stringify(status.body));
  const workBody={technicianId:savedTech,description:'Remplacement filtre',plannedHours:1.5,rateCode:'T1',requestKey:randomUUID()};
  assert.equal((await auth(api.post(route('/interventions'))).send(workBody)).status,409);
  const locationA=await insert("INSERT INTO locations(agency_id,name,type,is_active) VALUES(?,'A-01','warehouse',TRUE)",[agencyA]);
  const locationB=await insert("INSERT INTO locations(agency_id,name,type,is_active) VALUES(?,'B-01','warehouse',TRUE)",[agencyB]);
  const locationInactive=await insert("INSERT INTO locations(agency_id,name,type,is_active) VALUES(?,'A-inactif','warehouse',FALSE)",[agencyA]);
  const locationShowroom=await insert("INSERT INTO locations(agency_id,name,type,is_active) VALUES(?,'Showroom','showroom',TRUE)",[agencyA]);
  const part=await insert('INSERT INTO parts(reference,name,sale_price) VALUES(?,?,?)',[`SAV-P-${suffix}`,'Filtre atelier',12000]);
  const stockA=await insert('INSERT INTO part_stocks(part_id,agency_id,location_id,current_stock) VALUES(?,?,?,5)',[part,agencyA,locationA]);
  const stockB=await insert('INSERT INTO part_stocks(part_id,agency_id,location_id,current_stock) VALUES(?,?,?,10)',[part,agencyB,locationB]);
  const stockInactive=await insert('INSERT INTO part_stocks(part_id,agency_id,location_id,current_stock) VALUES(?,?,?,2)',[part,agencyA,locationInactive]);
  const stockShowroom=await insert('INSERT INTO part_stocks(part_id,agency_id,location_id,current_stock) VALUES(?,?,?,3)',[part,agencyA,locationShowroom]);
  const available=await auth(api.get(route('/available-parts')));assert.equal(available.status,200,JSON.stringify(available.body));assert.equal(available.body.find((x:{id:string})=>x.id===part).availableStock,5);
  const stocks=await auth(api.get(route(`/available-parts/${part}/stocks`)));assert.deepEqual(stocks.body.map((x:{id:string})=>x.id),[stockA]);
  const reserve=(partStockId:string,quantity:number,requestKey?:string)=>auth(api.post(route('/parts/reserve'))).send({partId:part,partStockId,quantity,requestKey});
  for(const bad of [stockB,stockInactive,stockShowroom]){const denied=await reserve(bad,1);assert.ok([400,403,404,409].includes(denied.status),`${bad}: ${JSON.stringify(denied.body)}`)}
  assert.equal((await reserve(stockA,6)).status,409);
  const reservationKey=randomUUID(),reserved=await reserve(stockA,2,reservationKey);assert.equal(reserved.status,201,JSON.stringify(reserved.body));
  const repeatedReservation=await reserve(stockA,2,reservationKey);assert.equal(repeatedReservation.status,201);assert.equal(repeatedReservation.body.id,reserved.body.id);
  assert.equal((await reserve(stockA,1,reservationKey)).status,409);
  const afterReserve=await auth(api.get(route(`/available-parts/${part}/stocks`)));assert.equal(afterReserve.body[0].availableStock,3);
  const estimate=await auth(api.post(route('/estimate-items'))).send({itemType:'labor',description:'Chiffrage initial',quantity:1,rateCode:'T1',requestKey:randomUUID()});assert.equal(estimate.status,201,JSON.stringify(estimate.body));
  status=await auth(api.patch(route('/status'))).send({status:'waiting_approval'});assert.equal(status.status,200,JSON.stringify(status.body));
  const approval=await auth(api.post(route('/approval'))).send({approved:true,approvedAmount:18000,customerName:'Client Atelier'});assert.equal(approval.status,201,JSON.stringify(approval.body));
  status=await auth(api.patch(route('/status'))).send({status:'in_progress'});assert.equal(status.status,200,JSON.stringify(status.body));
  const forgedWork=await auth(api.post(route('/interventions'))).send({technicianId:`u:${techB}`,description:'Interdit',plannedHours:1,rateCode:'T1'});assert.equal(forgedWork.status,400);
  const work=await auth(api.post(route('/interventions'))).send(workBody);assert.equal(work.status,201,JSON.stringify(work.body));const intervention=String(work.body.interventions[0].id);
  const repeatedWork=await auth(api.post(route('/interventions'))).send(workBody);assert.equal(repeatedWork.status,201);assert.equal(repeatedWork.body.interventions.length,1);
  assert.equal((await auth(api.post(route('/interventions'))).send({...workBody,description:'Autre travail'})).status,409);
  const assign=await auth(api.post(route('/assign'))).send({technicianId:savedTech,interventionId:intervention,startsAt:'2026-09-19 09:00:00',endsAt:'2026-09-19 10:30:00'});assert.equal(assign.status,201,JSON.stringify(assign.body));
  const secondWork=await auth(api.post(route('/interventions'))).send({technicianId:virtual(techConcession),description:'Contrôle parallèle',plannedHours:1,rateCode:'T1'});assert.equal(secondWork.status,201,JSON.stringify(secondWork.body));const secondIntervention=String(secondWork.body.interventions.find((x:{description:string})=>x.description==='Contrôle parallèle').id);
  const secondTech=String(secondWork.body.interventions.find((x:{id:string})=>String(x.id)===secondIntervention).technician_id);
  const secondAssign=await auth(api.post(route('/assign'))).send({technicianId:secondTech,interventionId:secondIntervention,startsAt:'2026-09-19 09:00:00',endsAt:'2026-09-19 10:30:00'});assert.equal(secondAssign.status,201,JSON.stringify(secondAssign.body));
  const forgedAssign=await auth(api.post(route('/assign'))).send({technicianId:`u:${techB}`,interventionId:intervention,startsAt:'2026-09-20 09:00:00',endsAt:'2026-09-20 10:00:00'});assert.equal(forgedAssign.status,400);
  const start=await auth(api.post(route('/sessions/start'))).send({technicianId:savedTech,interventionId:intervention});assert.equal(start.status,201,JSON.stringify(start.body));
  assert.equal((await auth(api.post(route('/sessions/start'))).send({technicianId:savedTech,interventionId:intervention})).status,409);
  const session=String(start.body.id);const stop=await auth(api.patch(route(`/sessions/${session}/stop`))).send({});assert.equal(stop.status,200,JSON.stringify(stop.body));
  assert.equal((await auth(api.patch(route(`/sessions/${session}/stop`))).send({})).status,200);
  let [firstSchedule]=await rows('SELECT status FROM schedules WHERE id=?',[assign.body.id]);assert.equal(firstSchedule.status,'confirmed');
  const secondSessionStart=await auth(api.post(route('/sessions/start'))).send({technicianId:savedTech,interventionId:intervention});assert.equal(secondSessionStart.status,201,JSON.stringify(secondSessionStart.body));
  const secondSession=String(secondSessionStart.body.id);assert.equal((await auth(api.patch(route(`/sessions/${secondSession}/stop`))).send({})).status,200);
  [firstSchedule]=await rows('SELECT status FROM schedules WHERE id=?',[assign.body.id]);assert.equal(firstSchedule.status,'confirmed');
  const complete=await auth(api.patch(route(`/interventions/${intervention}/status`))).send({status:'completed'});assert.equal(complete.status,200,JSON.stringify(complete.body));
  assert.equal((await auth(api.patch(route(`/interventions/${intervention}/status`))).send({status:'completed'})).status,200);
  [firstSchedule]=await rows('SELECT status FROM schedules WHERE id=?',[assign.body.id]);assert.equal(firstSchedule.status,'completed');
  assert.equal(complete.body.schedules.find((x:{id:string})=>String(x.id)===String(assign.body.id)).status,'completed');
  assert.equal((await auth(api.patch(`/api/workshop/schedules/${assign.body.id}`)).send({technicianId:savedTech,startsAt:'2026-09-19 11:00:00',endsAt:'2026-09-19 12:00:00'})).status,409);
  assert.equal((await auth(api.delete(`/api/workshop/schedules/${assign.body.id}`))).status,409);
  const [parallelSchedule]=await rows('SELECT status FROM schedules WHERE id=?',[secondAssign.body.id]);assert.equal(parallelSchedule.status,'confirmed');
  const [completionHistory]=await rows("SELECT COUNT(*) total FROM workshop_schedule_history WHERE schedule_id=? AND JSON_UNQUOTE(JSON_EXTRACT(new_values,'$.status'))='completed'",[assign.body.id]);assert.equal(Number(completionHistory.total),1);
  const thirdWork=await auth(api.post(route('/interventions'))).send({technicianId:savedTech,description:'Réutilisation ressource',plannedHours:1,rateCode:'T1'});assert.equal(thirdWork.status,201,JSON.stringify(thirdWork.body));const thirdIntervention=String(thirdWork.body.interventions.find((x:{description:string})=>x.description==='Réutilisation ressource').id);
  const reusedSlot=await auth(api.post(route('/assign'))).send({technicianId:savedTech,interventionId:thirdIntervention,startsAt:'2026-09-19 09:00:00',endsAt:'2026-09-19 10:30:00'});assert.equal(reusedSlot.status,201,JSON.stringify(reusedSlot.body));
  await pool.execute('UPDATE locations SET is_active=FALSE WHERE id=?',[locationA]);
  const inactiveChoices=await auth(api.get(route(`/available-parts/${part}/stocks`)));assert.deepEqual(inactiveChoices.body,[]);
  assert.equal((await auth(api.patch(route(`/parts/reservations/${reserved.body.id}`))).send({status:'consumed'})).status,400);
  await pool.execute('UPDATE locations SET is_active=TRUE WHERE id=?',[locationA]);
  const consume=await auth(api.patch(route(`/parts/reservations/${reserved.body.id}`))).send({status:'consumed'});assert.equal(consume.status,200,JSON.stringify(consume.body));
  assert.ok([404,409].includes((await auth(api.patch(route(`/parts/reservations/${reserved.body.id}`))).send({status:'consumed'})).status));
  const directBody={itemType:'part',partId:part,partStockId:stockA,description:'Filtre atelier',quantity:1,unitPrice:12000,requestKey:randomUUID()};
  const direct=await auth(api.post(route('/items'))).send(directBody);assert.equal(direct.status,201,JSON.stringify(direct.body));
  const repeatedDirect=await auth(api.post(route('/items'))).send(directBody);assert.equal(repeatedDirect.status,201);assert.equal(repeatedDirect.body.items.filter((x:{item_type:string})=>x.item_type==='part').length,2);
  const laborBody={itemType:'labor',interventionId:intervention,description:'Main-d’œuvre filtre',quantity:1.5,rateCode:'T1',requestKey:randomUUID()};
  const labor=await auth(api.post(route('/items'))).send(laborBody);assert.equal(labor.status,201,JSON.stringify(labor.body));
  const repeatedLabor=await auth(api.post(route('/items'))).send(laborBody);assert.equal(repeatedLabor.status,201);assert.equal(repeatedLabor.body.items.filter((x:{item_type:string})=>x.item_type==='labor').length,1);
  assert.equal((await auth(api.post(route('/items'))).send({...laborBody,quantity:2})).status,409);
  const manual=await auth(api.post(route('/items'))).send({itemType:'labor',description:'Contrôle manuel',quantity:0.5,rateCode:'T1'});assert.equal(manual.status,201,JSON.stringify(manual.body));
  const reloaded=await auth(api.get(route('')));assert.equal(reloaded.status,200,JSON.stringify(reloaded.body));
  const config=await auth(api.get('/api/workshop/config').query({agencyId:agencyA}));assert.equal(config.status,200,JSON.stringify(config.body));
  assert.equal(String(reloaded.body.diagnostics[0].technician_id),savedTech);
  assert.equal(String(reloaded.body.interventions[0].technician_id),savedTech);
  assert.ok(reloaded.body.schedules.some((x:{technician_id:string})=>String(x.technician_id)===savedTech));
  assert.equal(reloaded.body.sessions.filter((x:{id:string})=>String(x.id)===session).length,1);
  assert.equal(reloaded.body.items.filter((x:{item_type:string})=>x.item_type==='labor').length,2);
  const linkedLabor=reloaded.body.items.find((x:{item_type:string;intervention_id:unknown})=>x.item_type==='labor'&&String(x.intervention_id)===intervention);
  assert.equal(Number(linkedLabor.quantity),1.5);assert.equal(Number(linkedLabor.unit_price),Number(config.body.rates.T1));assert.equal(Number(linkedLabor.line_total),1.5*Number(config.body.rates.T1));
  assert.ok(reloaded.body.items.some((x:{item_type:string;intervention_id:unknown})=>x.item_type==='labor'&&x.intervention_id==null));
  const [balance]=await rows('SELECT current_stock,reserved_stock FROM part_stocks WHERE id=?',[stockA]);assert.equal(Number(balance.current_stock),2);assert.equal(Number(balance.reserved_stock),0);
  const [entry]=await rows('SELECT COUNT(*) total FROM time_entries WHERE work_session_id=?',[session]);assert.equal(Number(entry.total),1);
  await pool.execute('UPDATE users SET is_active=FALSE WHERE id=?',[techA]);
  const afterRevocation=await auth(api.get(route('/technician-candidates')));assert.ok(!afterRevocation.body.some((x:{userId:string})=>x.userId===techA));
  const revokedAssign=await auth(api.post(route('/assign'))).send({technicianId:savedTech,interventionId:intervention,startsAt:'2026-09-21 09:00:00',endsAt:'2026-09-21 10:00:00'});assert.equal(revokedAssign.status,400);
});
