import assert from'node:assert/strict';import{after,test}from'node:test';import type{Request}from'express';import type{ResultSetHeader,RowDataPacket}from'mysql2/promise';import{pool,query}from'../src/config/database.js';import{resolveDocumentEntity}from'../src/modules/documents/document-access.js';import{bootstrapDatabase}from'../src/scripts/database-bootstrap.js';import{createAccount,createCategory,createManualDisbursement,createManualReceipt,reverse}from'../src/modules/treasury/treasury.service.js';
const enabled=process.env.TREASURY_MANUAL_MYSQL_TEST==='1';if(enabled)after(()=>pool.end());
test('TREAS-MAN MySQL 8.4 opérations manuelles, idempotence et concurrence',{skip:!enabled,timeout:300000},async()=>{
 assert.equal((await bootstrapDatabase()).version,60);assert.equal((await bootstrapDatabase()).version,60);
 const suffix=Date.now().toString(),insert=async(sql:string,p:unknown[]=[])=>String((await pool.execute<ResultSetHeader>(sql,p))[0].insertId),concession=await insert('INSERT INTO concessions(name,code,currency_code) VALUES(?,?,?)',[`Manual ${suffix}`,`MAN${suffix}`,'XAF']),agency=await insert('INSERT INTO agencies(concession_id,name,code) VALUES(?,?,?)',[concession,`Agence ${suffix}`,`MA${suffix}`]),user=await insert('INSERT INTO users(agency_id,first_name,last_name,email,password_hash) VALUES(?,?,?,?,?)',[agency,'Test','Manuel',`manual-${suffix}@example.test`,'not-used']);
 const permissions=new Map(['treasury.view','treasury.account.manage','treasury.category.manage','treasury.receipt.create','treasury.disbursement.create','treasury.reverse','ged.view','ged.upload'].map(p=>[p,'CONCESSION'])),request={user:{sub:user,agencyId:agency},rbac:{isSuperAdmin:false,permissions},ip:'127.0.0.1',get:()=>undefined}as unknown as Request,account=String((await createAccount(request,{agencyId:agency,code:`CASH_${suffix}`,name:'Caisse manuelle',accountType:'CASH',currencyCode:'XAF',openingBalance:1000,openingDate:'2026-10-06',openingJustification:'Solde initial test'})).id),category=String((await createCategory(request,{concessionId:concession,code:`CAT_${suffix}`,name:'Opérations manuelles',allowedDirection:'BOTH'})).id),method=String((await query<RowDataPacket[]>('SELECT id FROM payment_methods WHERE is_active=TRUE ORDER BY id LIMIT 1'))[0]!.id),base={accountId:account,categoryId:category,valueDate:'2026-10-06',paymentMethodId:method,reference:'MAN-REF',description:'Opération manuelle audit',counterparty:'Partenaire test'};
 const receipt=await createManualReceipt(request,{...base,amount:'500.25',clientRequestId:'10000000-0000-4000-8000-000000000001'}),auditBefore=Number((await query<RowDataPacket[]>("SELECT COUNT(*) total FROM audit_logs WHERE entity_type='treasury_manual_operation' AND entity_id=?",[receipt.id]))[0]!.total),retry=await createManualReceipt(request,{...base,amount:'500.25',clientRequestId:'10000000-0000-4000-8000-000000000001'});assert.equal(retry.id,receipt.id);assert.equal(retry.movementId,receipt.movementId);assert.equal(retry.duplicate,true);assert.equal(Number((await query<RowDataPacket[]>("SELECT COUNT(*) total FROM audit_logs WHERE entity_type='treasury_manual_operation' AND entity_id=?",[receipt.id]))[0]!.total),auditBefore);
 await assert.rejects(createManualReceipt(request,{...base,amount:'501.25',clientRequestId:'10000000-0000-4000-8000-000000000001'}),error=>(error as any).status===409);
 const concurrent=await Promise.allSettled([createManualDisbursement(request,{...base,amount:'1000',handedTo:'Responsable A',clientRequestId:'20000000-0000-4000-8000-000000000001'}),createManualDisbursement(request,{...base,amount:'1000',handedTo:'Responsable B',clientRequestId:'20000000-0000-4000-8000-000000000002'})]);assert.equal(concurrent.filter(x=>x.status==='fulfilled').length,1);assert.equal(concurrent.filter(x=>x.status==='rejected').length,1);
 const rows=await query<RowDataPacket[]>("SELECT o.id,o.direction,o.amount,m.id movement_id,m.source_type,m.event_type FROM treasury_manual_operations o JOIN treasury_movements m ON CAST(m.source_id AS UNSIGNED)=o.id AND m.source_type IN('MANUAL_RECEIPT','MANUAL_DISBURSEMENT') WHERE o.account_id=? ORDER BY o.id",[account]);assert.equal(rows.length,2);assert.deepEqual(rows.map(x=>[x.direction,x.source_type,x.event_type]),[['IN','MANUAL_RECEIPT','POSTED'],['OUT','MANUAL_DISBURSEMENT','POSTED']]);
 await assert.rejects(createManualReceipt(request,{...base,categoryId:'999999999',amount:'10',clientRequestId:'30000000-0000-4000-8000-000000000001'}));assert.equal(Number((await query<RowDataPacket[]>("SELECT COUNT(*) total FROM treasury_manual_operations WHERE client_request_id='30000000-0000-4000-8000-000000000001'"))[0]!.total),0);
 const reversed=await reverse(request,receipt.movementId,{reason:'Correction manuelle test',valueDate:'2026-10-06'});assert.ok(reversed.id);assert.equal(Number((await query<RowDataPacket[]>("SELECT COALESCE(SUM(CASE WHEN status='POSTED' AND direction='IN' THEN amount WHEN status='POSTED' THEN -amount ELSE 0 END),0) balance FROM treasury_movements WHERE account_id=?",[account]))[0]!.balance),0);
 assert.equal(Number((await query<RowDataPacket[]>("SELECT COUNT(*) total FROM audit_logs WHERE entity_type='treasury_manual_operation' AND entity_id IN (?,?)",[receipt.id,(concurrent.find(x=>x.status==='fulfilled')as PromiseFulfilledResult<any>).value.id]))[0]!.total),2);
 const entity=await resolveDocumentEntity(request,'treasury_manual_operation',receipt.id,'ged.upload');assert.equal(entity.entityId,receipt.id);assert.equal(entity.agencyId,agency);
 const distinctA=await createManualReceipt(request,{...base,amount:'10',reference:'DISTINCT',clientRequestId:'40000000-0000-4000-8000-000000000001'}),distinctB=await createManualReceipt(request,{...base,amount:'10',reference:'DISTINCT',clientRequestId:'40000000-0000-4000-8000-000000000002'});assert.notEqual(distinctA.id,distinctB.id);
 const secondUser=await insert('INSERT INTO users(agency_id,first_name,last_name,email,password_hash) VALUES(?,?,?,?,?)',[agency,'Autre','Auteur',`manual-other-${suffix}@example.test`,'not-used']),secondRequest={...request,user:{sub:secondUser,agencyId:agency}}as unknown as Request,sameUuid=await createManualReceipt(secondRequest,{...base,amount:'5',reference:'SECOND-USER',clientRequestId:'10000000-0000-4000-8000-000000000001'});assert.notEqual(sameUuid.id,receipt.id);
 const protectedAccount=String((await createAccount(request,{agencyId:agency,code:`SAFE_${suffix}`,name:'Caisse reversal',accountType:'CASH',currencyCode:'XAF'})).id),protectedBase={...base,accountId:protectedAccount,reference:'REVERSAL-SAFE'},protectedIn=await createManualReceipt(request,{...protectedBase,amount:'500',clientRequestId:'50000000-0000-4000-8000-000000000001'}),protectedOut=await createManualDisbursement(request,{...protectedBase,amount:'400',handedTo:'Bénéficiaire',clientRequestId:'50000000-0000-4000-8000-000000000002'});await assert.rejects(reverse(request,protectedIn.movementId,{reason:'Reversal entrée impossible',valueDate:'2026-10-06'}),error=>(error as any).status===409);await pool.execute('UPDATE treasury_categories SET is_active=FALSE WHERE id=?',[category]);await pool.execute('UPDATE treasury_accounts SET is_active=FALSE WHERE id=?',[protectedAccount]);await reverse(request,protectedOut.movementId,{reason:'Restauration sortie historique',valueDate:'2026-10-06'});assert.equal(Number((await query<RowDataPacket[]>("SELECT COALESCE(SUM(CASE WHEN status='POSTED' AND direction='IN' THEN amount WHEN status='POSTED' THEN -amount ELSE 0 END),0) balance FROM treasury_movements WHERE account_id=?",[protectedAccount]))[0]!.balance),500);
});
