import React,{useState}from'react';
import{ArrowLeft,Download}from'lucide-react';
import{useNavigate,useParams}from'react-router-dom';
import{useBillingAction,useInvoiceQuery}from'../../api/erpHooks';
import{PageHeader}from'../../components/common/PageHeader';
import{Button as BaseButton}from'../../components/ui/Button';
import{Card}from'../../components/ui/Card';
import{Modal}from'../../components/ui/Modal';
import{StatusBadge}from'../../components/common/StatusBadge';
import{formatCurrency,formatDateTime}from'../../lib/utils';
import{generateUuid}from'../../lib/uuid';
import{apiDownload}from'../../services/apiClient';
import{useAuthStore}from'../../stores/authStore';
import{useUiStore}from'../../stores/uiStore';
import{InvoicePaymentForm,InvoicePaymentHistory}from'./InvoicePaymentComponents';
import type{InvoicePayment}from'../../types';

export const InvoiceDetailPage:React.FC=()=>{
 const{id}=useParams(),navigate=useNavigate(),agencyId=useAuthStore(s=>s.currentAgency?.id),can=useAuthStore(s=>s.can);
 const canView=can('billing.invoice.view'),canViewPayments=can('billing.payment.view'),canPay=can('billing.payment.collect'),canUpdate=can('billing.invoice.update'),canIssue=can('billing.invoice.issue'),canCancel=can('billing.invoice.cancel'),canRefund=can('billing.payment.refund');
 const query=useInvoiceQuery(id,agencyId,canView),action=useBillingAction(),toast=useUiStore(s=>s.addToast);
 const[modal,setModal]=useState<'credit'|'cancel'|''>(''),[operationKey,setOperationKey]=useState(generateUuid()),[form,setForm]=useState({amount:'',reason:''}),[refundPayment,setRefundPayment]=useState<InvoicePayment|null>(null),[refundKey,setRefundKey]=useState(generateUuid()),[refundForm,setRefundForm]=useState({creditNoteId:'',amount:'',reason:''});
 const invoice=query.data,pending=action.isPending;
 const Button=(props:React.ComponentProps<typeof BaseButton>)=><BaseButton {...props} disabled={props.disabled||(props.type==='submit'&&pending)} loading={props.loading||(props.type==='submit'&&pending)}/>;
 if(query.isLoading)return <p className="p-8">Chargement…</p>;
 if(query.isError||!invoice)return <p className="p-8 text-red-700">{query.error instanceof Error?query.error.message:'Facture introuvable'}</p>;
 const download=async(path:string,name:string)=>{try{const blob=await apiDownload(`${path}?agencyId=${encodeURIComponent(agencyId!)}`),url=URL.createObjectURL(blob),anchor=document.createElement('a');anchor.href=url;anchor.download=name;anchor.click();URL.revokeObjectURL(url)}catch(error){toast({type:'error',title:'Document indisponible',description:error instanceof Error?error.message:'Erreur API'})}};
 const issue=async()=>{try{await action.mutateAsync({path:`/invoices/${id}/status`,method:'PATCH',status:'issued',agencyId});toast({type:'success',title:'Facture émise'})}catch(error){toast({type:'error',title:'Émission impossible',description:error instanceof Error?error.message:'Erreur API'})}};
 const updateDraft=async()=>{const notes=window.prompt('Notes de la facture',invoice.notes??'');if(notes===null)return;try{await action.mutateAsync({path:`/invoices/${id}`,method:'PATCH',agencyId,issueDate:String(invoice.issueDate).slice(0,10),dueDate:invoice.dueDate?String(invoice.dueDate).slice(0,10):null,notes,items:(invoice.items??[]).map(item=>({description:item.description,quantity:item.quantity,unitPrice:item.unitPrice,discount:item.discount,taxRate:item.taxRate}))});toast({type:'success',title:'Brouillon modifié'})}catch(error){toast({type:'error',title:'Modification impossible',description:error instanceof Error?error.message:'Erreur API'})}};
 async function submit(event:React.FormEvent){event.preventDefault();if(pending)return;try{if(modal==='credit')await action.mutateAsync({path:`/invoices/${id}/credit-notes`,agencyId,amount:Number(form.amount),reason:form.reason,issueDate:new Date().toISOString().slice(0,10),idempotencyKey:operationKey});else if(modal==='cancel')await action.mutateAsync({path:`/invoices/${id}/cancel`,agencyId,reason:form.reason});toast({type:'success',title:'Opération enregistrée'});setOperationKey(generateUuid());setModal('')}catch(error){toast({type:'error',title:'Opération impossible',description:error instanceof Error?error.message:'Erreur API'})}}
 const availableCredits=(invoice.creditNotes??[]).filter(item=>['issued','applied'].includes(item.status)&&item.refundableRemaining>0);
 function openRefund(payment:InvoicePayment){const credit=availableCredits[0];setRefundPayment(payment);setRefundForm({creditNoteId:credit?.id??'',amount:String(Math.min(payment.refundableRemaining,credit?.refundableRemaining??0)),reason:''})}
 async function refund(event:React.FormEvent){event.preventDefault();if(!refundPayment||pending)return;const credit=availableCredits.find(item=>item.id===refundForm.creditNoteId),maximum=Math.min(refundPayment.refundableRemaining,credit?.refundableRemaining??0),amount=Number(refundForm.amount);if(!credit||refundForm.amount===''||!Number.isFinite(amount)||Number(refundForm.amount)<=0||amount>maximum){toast({type:'error',title:'Montant de remboursement invalide'});return}try{await action.mutateAsync({path:`/payments/${refundPayment.id}/refund`,agencyId,creditNoteId:credit.id,amount,reason:refundForm.reason,idempotencyKey:refundKey});toast({type:'success',title:'Remboursement enregistré'});setRefundKey(generateUuid());setRefundPayment(null)}catch(error){toast({type:'error',title:'Remboursement impossible',description:error instanceof Error?error.message:'Erreur API'})}}
 return <div className="space-y-6">
  <PageHeader title={invoice.invoiceNumber} subtitle={`${invoice.customerName} · ${invoice.agencyName??''}`} breadcrumbs={[{label:'Accueil',href:'/dashboard'},{label:'Facturation',href:'/billing'},{label:invoice.invoiceNumber}]} actions={<div className="flex gap-2"><Button variant="outline" size="sm" icon={<ArrowLeft className="w-4 h-4"/>} onClick={()=>navigate('/billing')}>Retour</Button><Button size="sm" icon={<Download className="w-4 h-4"/>} onClick={()=>download(`/invoices/${id}/pdf`,`facture-${invoice.invoiceNumber}.pdf`)}>PDF</Button></div>}/>
  <div className="grid gap-4 lg:grid-cols-3">
   <Card><div className="flex justify-between"><h2 className="font-bold">Facture</h2><StatusBadge status={invoice.status} type="invoice"/></div><Info l="Client" v={invoice.customerName}/><Info l="Type" v={invoice.type}/><Info l="Source" v={invoice.relatedDocNumber||'Manuelle'}/><Info l="Émission" v={invoice.issueDate}/><Info l="Échéance" v={invoice.dueDate||'—'}/></Card>
   <Card><h2 className="font-bold">Résumé</h2><Info l="HT net" v={formatCurrency(invoice.amountHT)}/><Info l="Taxes" v={formatCurrency(invoice.amountTVA)}/><Info l="Total" v={formatCurrency(invoice.amountTTC)}/>{canViewPayments?<><Info l="Encaissé" v={formatCurrency(invoice.paidAmountTTC)}/><Info l="Reste dû" v={formatCurrency(invoice.remainingAmountTTC)}/></>:<p className="mt-2 text-xs text-slate-500">Détails des règlements masqués.</p>}</Card>
   {(canUpdate||canIssue||canPay||canCancel)&&<Card><h2 className="mb-3 font-bold">Actions</h2><div className="flex flex-wrap gap-2">{canUpdate&&invoice.status==='BROUILLON'&&<Button size="sm" variant="outline" onClick={()=>void updateDraft()}>Modifier</Button>}{canIssue&&invoice.status==='BROUILLON'&&<Button size="sm" onClick={()=>void issue()}>Émettre</Button>}<InvoicePaymentForm invoice={invoice} canCollect={canPay}/>{canCancel&&invoice.status!=='ANNULEE'&&<Button size="sm" variant="outline" onClick={()=>setModal('credit')}>Créer avoir</Button>}{canCancel&&invoice.paidAmountTTC===0&&invoice.status!=='ANNULEE'&&<Button size="sm" variant="outline" onClick={()=>setModal('cancel')}>Annuler</Button>}</div></Card>}
  </div>
  <Card><h2 className="mb-3 font-bold">Lignes</h2><table className="w-full text-xs"><thead><tr className="text-left"><th>Description</th><th>Quantité</th><th>Prix</th><th>Remise</th><th>Taxe</th><th>Total</th></tr></thead><tbody>{invoice.items?.map(item=><tr key={item.id} className="border-t"><td className="py-2">{item.description}</td><td>{item.quantity}</td><td>{formatCurrency(item.unitPrice)}</td><td>{formatCurrency(item.discount)}</td><td>{item.taxRate}%</td><td className="font-bold">{formatCurrency(item.lineTotal)}</td></tr>)}</tbody></table></Card>
  {canViewPayments&&<Card><h2 className="mb-3 font-bold">Historique des règlements</h2><InvoicePaymentHistory payments={invoice.payments} canRefund={canRefund&&availableCredits.length>0} onRefund={openRefund}/></Card>}
  {(canViewPayments||canCancel||canRefund)&&<Card><h2 className="mb-3 font-bold">Avoirs</h2>{invoice.creditNotes?.length?<div className="space-y-2">{invoice.creditNotes.map(item=><div key={item.id} className="rounded border p-3 text-sm"><div className="flex justify-between"><b>{item.creditNoteNumber}</b><span>{item.status}</span></div><p>{item.issueDate} · {item.reason}</p><p>Montant {formatCurrency(item.amount)} · utilisé {formatCurrency(item.refundedAmount)} · disponible {formatCurrency(item.refundableRemaining)}</p></div>)}</div>:<p className="text-sm text-slate-500">Aucun avoir.</p>}</Card>}
  <Modal isOpen={Boolean(modal)&&canCancel} onClose={()=>setModal('')} title={modal==='credit'?'Créer un avoir':'Annuler la facture'}><form onSubmit={submit} className="space-y-3">{modal==='credit'&&<label className="text-xs font-semibold">Montant<input required type="number" min="0.01" max={invoice.amountTTC} step="0.01" placeholder="Saisir le montant de l’avoir" className="mt-1 w-full rounded border p-2" value={form.amount} onChange={event=>setForm({...form,amount:event.target.value})}/></label>}<label className="text-xs font-semibold">Motif<textarea required className="mt-1 w-full rounded border p-2" value={form.reason} onChange={event=>setForm({...form,reason:event.target.value})}/></label><div className="flex justify-end"><Button type="submit">Valider</Button></div></form></Modal>
  <Modal isOpen={Boolean(refundPayment)&&canRefund} onClose={()=>!pending&&setRefundPayment(null)} title="Rembourser un règlement"><form onSubmit={refund} className="space-y-3"><div className="rounded bg-slate-50 p-3 text-sm"><p>Paiement : <b>{refundPayment?.paymentNumber}</b></p><p>Montant reçu : {formatCurrency(refundPayment?.amount??0)}</p><p>Déjà remboursé : {formatCurrency(refundPayment?.refundedAmount??0)}</p><p>Reliquat remboursable : {formatCurrency(refundPayment?.refundableRemaining??0)}</p></div><label className="text-xs font-semibold">Avoir justificatif<select required className="mt-1 w-full rounded border p-2" value={refundForm.creditNoteId} onChange={event=>{const credit=availableCredits.find(item=>item.id===event.target.value);setRefundForm({...refundForm,creditNoteId:event.target.value,amount:String(Math.min(refundPayment?.refundableRemaining??0,credit?.refundableRemaining??0))})}}><option value="">Sélectionner</option>{availableCredits.map(item=><option key={item.id} value={item.id}>{item.creditNoteNumber} · disponible {formatCurrency(item.refundableRemaining)}</option>)}</select></label><label className="text-xs font-semibold">Montant à rembourser<input required type="number" min="0.01" max={Math.min(refundPayment?.refundableRemaining??0,availableCredits.find(item=>item.id===refundForm.creditNoteId)?.refundableRemaining??0)} step="0.01" className="mt-1 w-full rounded border p-2" value={refundForm.amount} placeholder="Saisir le montant à rembourser" onChange={event=>setRefundForm({...refundForm,amount:event.target.value})}/></label><label className="text-xs font-semibold">Motif<textarea required className="mt-1 w-full rounded border p-2" value={refundForm.reason} onChange={event=>setRefundForm({...refundForm,reason:event.target.value})}/></label><p className="text-xs text-amber-700">Cette opération enregistre une sortie de trésorerie irréversible.</p><div className="flex justify-end"><Button type="submit" loading={pending} disabled={pending}>Confirmer le remboursement</Button></div></form></Modal>
 </div>;
};
const Info=({l,v}:any)=><div className="flex justify-between py-1 text-sm"><span className="text-slate-500">{l}</span><b>{v}</b></div>;
