import React, { useEffect, useState } from 'react';
import { Plus, Trash2 } from 'lucide-react';
import { useBillingConfigQuery, useCreateInvoice, useCustomersQuery, useSalesQuery } from '../../api/erpHooks';
import { useAuthStore } from '../../stores/authStore';
import { useUiStore } from '../../stores/uiStore';
import { Modal } from '../../components/ui/Modal';
import { Button } from '../../components/ui/Button';
import { formatCurrency } from '../../lib/utils';

const emptyLine = (taxRate = 0) => ({ description: '', quantity: 1, unitPrice: 0, discount: 0, taxRate });

export const NewInvoiceModal: React.FC<{ isOpen: boolean; onClose: () => void }> = ({ isOpen, onClose }) => {
  const customers = useCustomersQuery().data ?? [], sales = useSalesQuery().data ?? [], create = useCreateInvoice();
  const agency = useAuthStore((state) => state.currentAgency), config = useBillingConfigQuery(agency?.id), toast = useUiStore((state) => state.addToast);
  const today = new Date().toISOString().slice(0, 10);
  const [form, setForm] = useState({ customerId: '', invoiceType: 'manual', saleId: '', issueDate: today, dueDate: today, notes: '', items: [emptyLine()] });
  useEffect(() => { if (!form.customerId && customers[0]) setForm((value) => ({ ...value, customerId: customers[0].id })); }, [customers, form.customerId]);
  useEffect(() => { if (config.data) setForm((value) => ({ ...value, items: value.items.map((item) => ({ ...item, taxRate: config.data.defaultVatRate })) })); }, [config.data]);
  const update = (index: number, key: string, value: unknown) => setForm((current) => ({ ...current, items: current.items.map((line, position) => position === index ? { ...line, [key]: value } : line) }));
  const net = form.items.reduce((sum, item) => sum + item.quantity * item.unitPrice - item.discount, 0), tax = form.items.reduce((sum, item) => sum + (item.quantity * item.unitPrice - item.discount) * item.taxRate / 100, 0);
  const currency = config.data?.currencyCode, money = (amount: number) => currency ? formatCurrency(amount, currency) : '—';
  async function submit(event: React.FormEvent) { event.preventDefault(); if (!config.data) return; try { await create.mutateAsync({ ...form, agencyId: agency?.id, saleId: form.invoiceType === 'vehicle' ? form.saleId || null : null, idempotencyKey: crypto.randomUUID() }); toast({ type: 'success', title: 'Facture créée', description: `Total ${money(net + tax)}` }); onClose(); } catch (error) { toast({ type: 'error', title: 'Facture non créée', description: error instanceof Error ? error.message : 'Erreur API' }); } }
  return <Modal isOpen={isOpen} onClose={onClose} title="Émettre une facture" description="Les montants affichés sont un aperçu ; le backend recalcule toutes les lignes." maxWidth="xl"><form onSubmit={submit} className="space-y-4">
    {config.isLoading && <p className="rounded border bg-slate-50 p-3 text-xs text-slate-600">Chargement de la configuration de facturation...</p>}
    {config.isError && <p className="rounded border border-red-200 bg-red-50 p-3 text-xs text-red-700">Configuration TVA et devise indisponible. La facture ne peut pas être émise.</p>}
    <div className="grid sm:grid-cols-2 gap-3"><label className="text-xs font-semibold">Client<select required className="mt-1 w-full p-2 border rounded" value={form.customerId} onChange={(e) => setForm({ ...form, customerId: e.target.value })}><option value="">Sélectionner</option>{customers.map((customer) => <option key={customer.id} value={customer.id}>{customer.company || `${customer.firstName} ${customer.lastName}`}</option>)}</select></label><label className="text-xs font-semibold">Type<select className="mt-1 w-full p-2 border rounded" value={form.invoiceType} onChange={(e) => setForm({ ...form, invoiceType: e.target.value, saleId: '' })}><option value="manual">Manuelle</option><option value="vehicle">Vente véhicule</option><option value="parts">Pièces</option></select></label>{form.invoiceType === 'vehicle' && <label className="text-xs font-semibold">Vente<select required className="mt-1 w-full p-2 border rounded" value={form.saleId} onChange={(e) => setForm({ ...form, saleId: e.target.value })}><option value="">Sélectionner</option>{sales.filter((sale) => sale.customerId === form.customerId).map((sale) => <option key={sale.id} value={sale.id}>{sale.saleNumber} — {money(sale.totalSaleTTC)}</option>)}</select></label>}<label className="text-xs font-semibold">Date émission<input required type="date" className="mt-1 w-full p-2 border rounded" value={form.issueDate} onChange={(e) => setForm({ ...form, issueDate: e.target.value })} /></label><label className="text-xs font-semibold">Échéance<input type="date" className="mt-1 w-full p-2 border rounded" value={form.dueDate} onChange={(e) => setForm({ ...form, dueDate: e.target.value })} /></label></div>
    <div className="overflow-x-auto"><table className="w-full text-xs"><thead><tr><th>Description</th><th>Quantité</th><th>Prix unitaire</th><th>Remise</th><th>Taxe %</th><th></th></tr></thead><tbody>{form.items.map((item, index) => <tr key={index}><td><input required className="w-full p-2 border rounded" value={item.description} onChange={(e) => update(index, 'description', e.target.value)} /></td>{(['quantity', 'unitPrice', 'discount', 'taxRate'] as const).map((key) => <td key={key}><input required type="number" min="0" step="0.01" className="w-28 p-2 border rounded" value={item[key]} onChange={(e) => update(index, key, Number(e.target.value))} /></td>)}<td><Button type="button" size="xs" variant="outline" disabled={form.items.length === 1} icon={<Trash2 className="w-3 h-3" />} onClick={() => setForm({ ...form, items: form.items.filter((_, position) => position !== index) })}>Retirer</Button></td></tr>)}</tbody></table></div>
    <Button type="button" variant="outline" size="sm" icon={<Plus className="w-4 h-4" />} disabled={!config.data} onClick={() => setForm({ ...form, items: [...form.items, emptyLine(config.data!.defaultVatRate)] })}>Ajouter une ligne</Button><textarea className="w-full p-2 border rounded text-xs" placeholder="Notes" value={form.notes} onChange={(e) => setForm({ ...form, notes: e.target.value })} /><div className="bg-slate-50 p-3 rounded text-sm text-right">HT net : <b>{money(net)}</b> · Taxes : <b>{money(tax)}</b> · Total : <b>{money(net + tax)}</b></div><div className="flex justify-end gap-2"><Button type="button" variant="outline" onClick={onClose}>Annuler</Button><Button type="submit" loading={create.isPending} disabled={!form.customerId || !agency?.id || !config.data}>Émettre</Button></div>
  </form></Modal>;
};
