import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import test from 'node:test';
import {showroomViewMode} from '../src/modules/showroom/showroomPolicy.js';

const read=(path:string)=>readFileSync(new URL(path,import.meta.url),'utf8'),page=read('../src/modules/showroom/ShowroomPage.tsx'),hooks=read('../src/api/erpHooks.ts'),routes=read('../../backend-node/src/modules/showroom/showroom.routes.ts'),bootstrap=read('../src/components/AppBootstrap.tsx');

test('LIST-VIEW-01..04 absence, board et valeur invalide utilisent Board; list utilise Liste',()=>{assert.equal(showroomViewMode(null),'board');assert.equal(showroomViewMode('board'),'board');assert.equal(showroomViewMode('list'),'list');assert.equal(showroomViewMode('grille'),'board')});
test('LIST-VIEW-05/06 persiste le choix dans view et partage exactement visits',()=>{assert.match(page,/useSearchParams\(\)/);assert.match(page,/next\.set\('view','list'\)/);assert.match(page,/viewMode==='board'\?/);assert.match(page,/<ShowroomList visits=\{visits\}/);assert.equal((page.match(/useShowroomBoardQuery\(/g)??[]).length,1)});
test('LIST-TABLE-01..10 expose les dix colonnes et toutes les visites dont Annulé',()=>{for(const column of['Visiteur','Contact','Arrivée','Motif','Conseiller','Véhicule','Statut','Origine','Attente','Actions'])assert.match(page,new RegExp(`>${column}<`),column);assert.match(page,/visits\.map\(visit=>/);assert.match(page,/status==='Annulé'/);assert.match(page,/Non affecté/);assert.match(page,/visit\.origin==='crm'\?'CRM':'Showroom'/)});
test('LIST-ACTION-01..08 Board et Liste appellent un seul builder métier',()=>{assert.match(page,/const renderVisitActions=/);assert.match(page,/renderActions=\{renderVisitActions\}/);assert.match(page,/renderVisitActions\(visit\)/);for(const token of['canAssign','canTakeOver','canManageTestDrive','canReturnTestDrive','canComplete','canConvertShowroomVisitToLead','visit.origin===\'showroom\''])assert.match(page,new RegExp(token));assert.match(page,/useShowroomSalesCandidatesQuery\(visit\.agencyId,true\)/)});
test('LIST-SEARCH-01..13 transmet search au même endpoint et réinitialise la page',()=>{assert.match(hooks,/filters:\{from\?:string;to\?:string;all\?:boolean;search\?:string\}/);assert.match(hooks,/`\/showroom\?\$\{pageParams\(\{\.\.\.filters,page,pageSize\}\)\}`/);assert.match(page,/deferredSearch=useDeferredValue\(search\.trim\(\)\)/);assert.match(page,/\[dateMode,dateFrom,dateTo,deferredSearch\]/);assert.match(routes,/search=text\(request\.query\.search,'Recherche',100\)/);assert.match(routes,/sv\.visitor_name LIKE \?/);assert.match(routes,/showroomPhoneSql/)});
test('LIST-PAG-01..06 partage page six, contrôle et resynchronisation serveur',()=>{assert.match(page,/pageSize=6/);assert.match(hooks,/page=1,pageSize=6/);assert.match(page,/board\.data&&page!==board\.data\.page/);assert.doesNotMatch(page,/listPage|listPageSize/)});
test('LIST-DETAIL/REALTIME réutilise le détail et le préfixe cache Showroom',()=>{assert.match(page,/setDetailVisitId\(visit\.id\)/);assert.match(hooks,/useShowroomVisitQuery/);assert.match(bootstrap,/'showroom:visitor-created': \['showroom'\]/);assert.match(bootstrap,/invalidateQueries\(\{ queryKey: key \}\)/)});
test('LIST-EMPTY distingue recherche vide et absence de résultat',()=>{assert.match(page,/Aucune visite ne correspond à votre recherche/);assert.match(page,/Aucune visite à afficher/)});
