import React,{useEffect,useMemo,useState}from'react';
import{useAdvisorCandidatesQuery,useCreateCustomer,useCreateRepairOrder,useCreateWorkshopExternalVehicle,useCreateWorkshopVehicleAssociation,useCustomerServiceVehiclesQuery,useCustomersQuery,useVehicleWarrantyEligibilityQuery,useWorkshopVehicleSearchQuery,type VehicleRelationType,type WorkshopVehicleMatch}from'../../api/erpHooks';
import{ApiError}from'../../services/apiClient';
import{useAuthStore}from'../../stores/authStore';
import{useUiStore}from'../../stores/uiStore';
import{Modal}from'../../components/ui/Modal';
import{Button}from'../../components/ui/Button';
import{selectCustomerVehicle}from'./repairOrderVehicleSelection';

interface Props{isOpen:boolean;onClose:()=>void;initialCustomerId?:string;initialVehicleId?:string}
type Mode='internal'|'external';
type CustomerForm={type:'Particulier'|'Professionnel';civility:'M.'|'Mme'|'Société';firstName:string;lastName:string;company:string;email:string;phone:string;city:string};
type ExternalForm={brand:string;model:string;version:string;registrationNumber:string;vin:string;relationType:VehicleRelationType};
const relationLabels:Record<VehicleRelationType,string>={OWNER:'Propriétaire',DRIVER:'Conducteur',RESPONSIBLE:'Responsable',FLEET:'Flotte'};
const originLabels={CONCESSION:'Concession',EXTERNAL:'Extérieur',UNKNOWN:'Origine non renseignée'}as const;
const warrantyLabels={NO_CONTRACT:'Aucun contrat historique',UNDETERMINED:'Situation de garantie à régulariser',NOT_COVERED:'Garantie non applicable',PENDING_ACTIVATION:'Garantie prévue — en attente d’activation',EXPIRED_BY_DATE:'Garantie expirée par date',MILEAGE_REQUIRED:'Vérification kilométrique requise',EXPIRED_BY_MILEAGE:'Limite kilométrique dépassée',ELIGIBLE_CONTRACTUALLY:'Garantie active'}as const;
const inputClass='w-full text-xs p-2.5 rounded-lg border border-slate-300 bg-white focus:outline-none focus:ring-2 focus:ring-blue-500';
const details=(error:unknown)=>error instanceof ApiError&&error.details&&typeof error.details==='object'?error.details as{code?:string;matches?:WorkshopVehicleMatch[]}:undefined;

export const NewRepairOrderModal:React.FC<Props>=({isOpen,onClose,initialCustomerId,initialVehicleId})=>{
 const{currentUser,currentAgency,can}=useAuthStore(),{addToast}=useUiStore();
 const fresh=()=>({customerId:'',customerName:'',vehicleId:'',mileage:'',promisedCompletionDate:new Date(Date.now()+86400000).toISOString().slice(0,16).replace('T',' '),symptomsReported:'',diagnosticNotes:''});
 const emptyCustomer=():CustomerForm=>({type:'Particulier',civility:'M.',firstName:'',lastName:'',company:'',email:'',phone:'',city:currentAgency?.city||'Brazzaville'});
 const emptyExternal=():ExternalForm=>({brand:'',model:'',version:'',registrationNumber:'',vin:'',relationType:'OWNER'});
 const[mode,setMode]=useState<Mode>('internal'),[form,setForm]=useState(fresh),[advisorId,setAdvisorId]=useState(''),[preferredVehicleId,setPreferredVehicleId]=useState<string|undefined>(initialVehicleId);
 const[customerSearch,setCustomerSearch]=useState(''),[debouncedCustomerSearch,setDebouncedCustomerSearch]=useState(''),[showNewCustomer,setShowNewCustomer]=useState(false),[customerForm,setCustomerForm]=useState(emptyCustomer),[customerError,setCustomerError]=useState('');
 const[vehicleSearch,setVehicleSearch]=useState({vin:'',registration:'',brand:'',model:''}),[debouncedVehicleSearch,setDebouncedVehicleSearch]=useState(vehicleSearch),[relationType,setRelationType]=useState<VehicleRelationType>('OWNER');
 const[showExternal,setShowExternal]=useState(false),[externalForm,setExternalForm]=useState<ExternalForm>(emptyExternal),[conflict,setConflict]=useState<{code:string;message:string;matches:WorkshopVehicleMatch[]}|null>(null);
 const canCreateCustomer=can('customers.create'),canViewVehicles=can('workshop.vehicles.view'),canCreateExternal=can('workshop.external_vehicle.create'),canAssociate=can('workshop.vehicle.associations.create'),canAssignAdvisor=can('service.order.assign_advisor');
 const customersQuery=useCustomersQuery(debouncedCustomerSearch,'',isOpen&&can('customers.view')),customers=customersQuery.data??[],selectedCustomer=customers.find(c=>c.id===form.customerId);
 const vehiclesQuery=useCustomerServiceVehiclesQuery(form.customerId,isOpen),vehicles=useMemo(()=>Array.from(new Map((vehiclesQuery.data??[]).map(v=>[v.id,v])).values()),[vehiclesQuery.data]);
 const advisorsQuery=useAdvisorCandidatesQuery(selectedCustomer?.agencyId??currentAgency?.id,isOpen),advisors=advisorsQuery.data??[];
 const searchQuery=useWorkshopVehicleSearchQuery(debouncedVehicleSearch,isOpen&&mode==='external'&&canViewVehicles),createCustomer=useCreateCustomer(),createExternal=useCreateWorkshopExternalVehicle(),createAssociation=useCreateWorkshopVehicleAssociation(),createOrder=useCreateRepairOrder();
 const mileage=form.mileage!==''&&Number.isInteger(Number(form.mileage))&&Number(form.mileage)>=0?Number(form.mileage):null,warrantyQuery=useVehicleWarrantyEligibilityQuery(form.vehicleId,mileage,isOpen);
 useEffect(()=>{const timer=window.setTimeout(()=>setDebouncedCustomerSearch(customerSearch.trim()),350);return()=>clearTimeout(timer)},[customerSearch]);
 useEffect(()=>{const timer=window.setTimeout(()=>setDebouncedVehicleSearch(vehicleSearch),350);return()=>clearTimeout(timer)},[vehicleSearch]);
 useEffect(()=>{if(!isOpen){setForm(fresh());setPreferredVehicleId(initialVehicleId);setMode('internal');setShowNewCustomer(false);setShowExternal(false);setConflict(null);return}if(customersQuery.isSuccess&&!form.customerId){const c=customers.find(x=>x.id===initialCustomerId);if(c)setForm(current=>({...current,customerId:c.id,customerName:`${c.civility} ${c.firstName} ${c.lastName}`.trim()}))}},[isOpen,customersQuery.isSuccess,initialCustomerId,initialVehicleId]);
 useEffect(()=>{if (!isOpen) return;setAdvisorId(advisors.some(a=>a.id===currentUser?.id)?currentUser!.id:advisors[0]?.id??'')},[isOpen,advisorsQuery.data,currentUser?.id]);
 useEffect(()=>{if(!isOpen||!vehiclesQuery.isSuccess)return;const ids=vehicles.map(v=>v.id);if(preferredVehicleId&&!ids.includes(preferredVehicleId))return;setForm(current=>{const vehicleId=selectCustomerVehicle(ids,preferredVehicleId);if(current.vehicleId===vehicleId)return current;return{...current,vehicleId}})},[isOpen,form.customerId,vehiclesQuery.data,preferredVehicleId]);
 const selectCustomer=(id:string,created?:typeof customers[number])=>{const c=created??customers.find(x=>x.id===id);setPreferredVehicleId(undefined);setConflict(null);setForm(current=>({...current,customerId:id,customerName:c?`${c.civility} ${c.firstName} ${c.lastName}`.trim():'',vehicleId:'',mileage:''}))};
 const saveCustomer=async()=>{setCustomerError('');if(customerForm.type==='Particulier'&&!customerForm.lastName.trim())return setCustomerError('Le nom est obligatoire.');if(customerForm.type==='Professionnel'&&!customerForm.company.trim())return setCustomerError('La raison sociale est obligatoire.');if(!customerForm.phone.trim()&&!customerForm.email.trim())return setCustomerError('Un téléphone ou une adresse e-mail est requis.');try{const c=await createCustomer.mutateAsync({customerType:customerForm.type==='Particulier'?'individual':'company',civility:customerForm.civility,firstName:customerForm.firstName,lastName:customerForm.lastName,companyName:customerForm.company||undefined,email:customerForm.email,phone:customerForm.phone,city:customerForm.city,country:'Congo',agencyId:currentAgency?.id});selectCustomer(c.id,c);setShowNewCustomer(false);setCustomerForm(emptyCustomer());addToast({type:'success',title:'Client enregistré',description:'Le nouveau client est sélectionné pour cet OR.'})}catch(error){setCustomerError(error instanceof Error?error.message:'Erreur API')}};
 const selectOrAssociate=async(vehicle:WorkshopVehicleMatch)=>{if(vehicles.some(v=>v.id===vehicle.id)){setForm(current=>({...current,vehicleId:vehicle.id}));return}if(!canAssociate||!currentAgency?.id)return;try{await createAssociation.mutateAsync({customerId:form.customerId,vehicleId:vehicle.id,agencyId:currentAgency.id,relationType});setPreferredVehicleId(vehicle.id);await vehiclesQuery.refetch();addToast({type:'success',title:'Véhicule associé',description:'Le véhicule est sélectionné.'})}catch(error){addToast({type:'error',title:'Association impossible',description:error instanceof Error?error.message:'Erreur API'})}};
 const saveExternal=async(confirmRegistrationAmbiguity=false)=>{setConflict(null);if(!externalForm.brand.trim()||!externalForm.model.trim())return setConflict({code:'VALIDATION',message:'La marque et le modèle sont obligatoires.',matches:[]});try{const result=await createExternal.mutateAsync({customerId:form.customerId,agencyId:currentAgency!.id,...externalForm,confirmRegistrationAmbiguity:confirmRegistrationAmbiguity||undefined});setPreferredVehicleId(result.vehicleId);await vehiclesQuery.refetch();setShowExternal(false);setExternalForm(emptyExternal());addToast({type:'success',title:'Véhicule extérieur ajouté',description:'Le véhicule a été associé et sélectionné.'})}catch(error){const d=details(error);setConflict({code:d?.code??'API_ERROR',message:error instanceof Error?error.message:'Erreur API',matches:d?.matches??[]});if(d?.code==='VIN_ALREADY_EXISTS')setVehicleSearch(current=>({...current,vin:externalForm.vin}))}};
 const submit=async(e:React.FormEvent)=>{e.preventDefault();if(mileage==null){addToast({type:'error',title:'Kilométrage invalide',description:'Le kilométrage doit être un nombre entier positif ou nul.'});return}const vehicle=vehicles.find(v=>v.id===form.vehicleId);if(!vehicle){addToast({type:'error',title:'Véhicule requis',description:'Sélectionnez explicitement un véhicule existant.'});return}if(!advisors.some(a=>a.id===advisorId)){addToast({type:'error',title:'Conseiller SAV requis',description:'Aucun conseiller opérationnel éligible n’est disponible dans cette agence.'});return}try{await createOrder.mutateAsync({customerId:form.customerId,vehicleId:vehicle.id,mileage,advisorId,complaint:form.symptomsReported,diagnosisSummary:form.diagnosticNotes,promisedCompletionAt:form.promisedCompletionDate});addToast({type:'success',title:'Ordre de Réparation créé (OR)',description:`L’OR a été ouvert pour ${form.customerName} (${vehicle.registrationNumber||vehicle.vin}).`});onClose()}catch(error){addToast({type:'error',title:'Création impossible',description:error instanceof Error?error.message:'Erreur API'})}};
 const busy=createCustomer.isPending||createExternal.isPending||createAssociation.isPending||createOrder.isPending;
 return <Modal isOpen={isOpen} onClose={onClose} title="Créer un Ordre de Réparation Atelier (OR)" description="Ouverture de dossier SAV et planification d'intervention atelier." maxWidth="xl"><form onSubmit={submit} className="space-y-4">
  <div className="grid grid-cols-2 gap-2 rounded-lg bg-slate-100 p-1">{([['internal','Véhicule interne'],['external','Véhicule extérieur']]as const).map(([value,label])=><button key={value} type="button" onClick={()=>setMode(value)} className={`rounded-md px-3 py-2 text-xs font-semibold ${mode===value?'bg-white text-blue-700 shadow-sm':'text-slate-600'}`}>{label}</button>)}</div>
  {canAssignAdvisor?<label className="block text-xs font-semibold text-slate-700">Conseiller SAV affecté<select required value={advisorId} onChange={e=>setAdvisorId(e.target.value)} className={`mt-1 ${inputClass}`}><option value="">Sélectionner…</option>{advisors.map(a=><option key={a.id} value={a.id}>{a.name}</option>)}</select></label>:<p className="text-xs text-slate-600">Conseiller SAV : {advisors.find(a=>a.id===advisorId)?.name??'Aucun conseiller éligible'}</p>}
  <section className="rounded-lg border border-slate-200 p-3 space-y-2"><div className="flex items-center justify-between"><label className="text-xs font-semibold">Client *</label>{canCreateCustomer&&<Button type="button" size="xs" variant="outline" onClick={()=>setShowNewCustomer(v=>!v)}>Nouveau client</Button>}</div><input value={customerSearch} onChange={e=>setCustomerSearch(e.target.value)} placeholder="Nom, prénom, raison sociale ou téléphone…" className={inputClass}/><select value={form.customerId} onChange={e=>selectCustomer(e.target.value)} className={inputClass}><option value="">Sélectionner un client…</option>{customers.map(c=><option key={c.id} value={c.id}>{c.company||`${c.civility} ${c.firstName} ${c.lastName}`} — {c.code} — {c.phone||c.email}</option>)}</select>{customersQuery.isFetching&&<p className="text-[11px] text-slate-500">Recherche des clients…</p>}{customersQuery.isSuccess&&!customers.length&&<p className="text-[11px] text-amber-700">Aucun client ne correspond à la recherche.</p>}{customersQuery.isError&&<p className="text-[11px] text-red-700">Chargement impossible : {customersQuery.error.message}</p>}
  {showNewCustomer&&<div className="grid grid-cols-1 sm:grid-cols-3 gap-2 border-t pt-3"><select value={customerForm.type} onChange={e=>setCustomerForm(current=>({...current,type:e.target.value as CustomerForm['type'],civility:e.target.value==='Professionnel'?'Société':'M.'}))} className={inputClass}><option>Particulier</option><option>Professionnel</option></select>{customerForm.type==='Particulier'?<><input placeholder="Prénom" value={customerForm.firstName} onChange={e=>setCustomerForm({...customerForm,firstName:e.target.value})} className={inputClass}/><input placeholder="Nom *" value={customerForm.lastName} onChange={e=>setCustomerForm({...customerForm,lastName:e.target.value})} className={inputClass}/></>:<input placeholder="Raison sociale *" value={customerForm.company} onChange={e=>setCustomerForm({...customerForm,company:e.target.value})} className={`${inputClass} sm:col-span-2`}/>}<input placeholder="Téléphone" value={customerForm.phone} onChange={e=>setCustomerForm({...customerForm,phone:e.target.value})} className={inputClass}/><input type="email" placeholder="E-mail" value={customerForm.email} onChange={e=>setCustomerForm({...customerForm,email:e.target.value})} className={inputClass}/><input placeholder="Ville" value={customerForm.city} onChange={e=>setCustomerForm({...customerForm,city:e.target.value})} className={inputClass}/>{customerError&&<p className="sm:col-span-3 text-xs text-red-700">{customerError}</p>}<div className="sm:col-span-3 flex justify-end"><Button type="button" size="sm" disabled={createCustomer.isPending} onClick={saveCustomer}>{createCustomer.isPending?'Enregistrement…':'Enregistrer et sélectionner'}</Button></div></div>}</section>
  <div className="grid grid-cols-1 sm:grid-cols-3 gap-3"><div className="sm:col-span-2"><label className="block text-xs font-semibold mb-1">Véhicule existant *</label><select required value={form.vehicleId} onChange={e=>setForm({...form,vehicleId:e.target.value})} className={inputClass}><option value="">Sélectionner…</option>{vehicles.map(v=><option key={v.id} value={v.id}>{v.label} — {v.registrationNumber||v.vin||'Sans immatriculation ni VIN'} — {originLabels[v.commercialOrigin]}</option>)}</select>{vehiclesQuery.isFetching&&<p className="text-[11px] text-slate-500">Chargement des véhicules…</p>}{form.customerId&&vehiclesQuery.isSuccess&&!vehicles.length&&<p className="text-[11px] text-amber-700">Aucun véhicule enregistré pour ce client</p>}</div><label className="block text-xs font-semibold">Kilométrage actuel<input type="number" min="0" step="1" value={form.mileage} onChange={e=>setForm({...form,mileage:e.target.value})} className={`mt-1 ${inputClass}`}/></label></div>
  {mode==='external'&&form.customerId&&canViewVehicles&&<section className="rounded-lg border border-blue-200 bg-blue-50/30 p-3 space-y-3"><div className="flex justify-between"><b className="text-xs">Rechercher un véhicule existant</b>{canCreateExternal&&canAssociate&&<Button type="button" size="xs" variant="outline" onClick={()=>setShowExternal(v=>!v)}>Ajouter un véhicule extérieur</Button>}</div><div className="grid grid-cols-2 sm:grid-cols-4 gap-2">{(['vin','registration','brand','model']as const).map(key=><input key={key} value={vehicleSearch[key]} onChange={e=>setVehicleSearch(current=>({...current,[key]:e.target.value}))} placeholder={({vin:'VIN',registration:'Immatriculation',brand:'Marque',model:'Modèle'})[key]} className={inputClass}/>)}</div>{searchQuery.isFetching&&<p className="text-xs text-slate-500">Recherche des véhicules…</p>}{searchQuery.isError&&<p className="text-xs text-red-700">Recherche impossible : {searchQuery.error.message}</p>}{searchQuery.isSuccess&&!searchQuery.data.items.length&&<p className="text-xs text-amber-700">Aucun véhicule ne correspond aux critères.</p>}{searchQuery.data?.items.map(vehicle=><div key={vehicle.id} className="flex flex-col sm:flex-row sm:items-center justify-between gap-2 rounded border bg-white p-2 text-xs"><span><b>{vehicle.brand} {vehicle.model} {vehicle.version}</b> — {vehicle.registrationNumber||'Sans immatriculation'} — {vehicle.vin||'Sans VIN'} — {originLabels[vehicle.commercialOrigin]}</span><div className="flex gap-2"><select aria-label="Type de relation" value={relationType} onChange={e=>setRelationType(e.target.value as VehicleRelationType)} className="rounded border p-1">{Object.entries(relationLabels).map(([v,l])=><option key={v} value={v}>{l}</option>)}</select><Button type="button" size="xs" disabled={!vehicles.some(v=>v.id===vehicle.id)&&!canAssociate||createAssociation.isPending} onClick={()=>selectOrAssociate(vehicle)}>{vehicles.some(v=>v.id===vehicle.id)?'Sélectionner':'Associer et sélectionner'}</Button></div></div>)}
  {showExternal&&<div className="grid grid-cols-2 sm:grid-cols-3 gap-2 border-t pt-3">{(['brand','model','version','registrationNumber','vin']as const).map(key=><input key={key} value={externalForm[key]} onChange={e=>setExternalForm({...externalForm,[key]:e.target.value})} placeholder={({brand:'Marque *',model:'Modèle *',version:'Version (facultative)',registrationNumber:'Immatriculation (facultative)',vin:'VIN (facultatif)'})[key]} className={inputClass}/>)}<select value={externalForm.relationType} onChange={e=>setExternalForm({...externalForm,relationType:e.target.value as VehicleRelationType})} className={inputClass}>{Object.entries(relationLabels).map(([v,l])=><option key={v} value={v}>{l}</option>)}</select>{conflict&&<div className="col-span-full rounded border border-red-200 bg-red-50 p-2 text-xs text-red-800"><p>{conflict.message}</p>{conflict.code==='VIN_ALREADY_EXISTS'&&<p>Recherchez puis sélectionnez le véhicule existant ci-dessus.</p>}{conflict.matches.map(match=><button key={match.id} type="button" className="block underline" onClick={()=>selectOrAssociate(match)}>Sélectionner {match.brand} {match.model} — {match.registrationNumber||match.vin}</button>)}{conflict.code==='REGISTRATION_AMBIGUOUS'&&<Button type="button" size="xs" variant="outline" className="mt-2" onClick={()=>saveExternal(true)}>Confirmer qu’il s’agit d’un autre véhicule</Button>}</div>}<div className="col-span-full flex justify-end"><Button type="button" size="sm" disabled={createExternal.isPending} onClick={()=>saveExternal(false)}>{createExternal.isPending?'Création…':'Créer, associer et sélectionner'}</Button></div></div>}</section>}
  <label className="block text-xs font-semibold">Fin promise<input type="datetime-local" value={form.promisedCompletionDate.replace(' ','T')} onChange={e=>setForm({...form,promisedCompletionDate:e.target.value.replace('T',' ')})} className={`mt-1 ${inputClass}`}/></label><label className="block text-xs font-semibold">Motif de visite & Symptômes signalés par le client *<textarea rows={2} required value={form.symptomsReported} onChange={e=>setForm({...form,symptomsReported:e.target.value})} className={`mt-1 ${inputClass}`}/></label>
  {form.vehicleId&&<div className="rounded-lg border bg-slate-50 p-3 text-xs space-y-1"><b>Garantie constructeur</b>{warrantyQuery.isFetching?<p>Vérification du contrat…</p>:warrantyQuery.isError?<p className="text-red-700">Impossible de récupérer le contexte Garantie.</p>:warrantyQuery.data?<><p>Éligibilité : <b>{warrantyLabels[warrantyQuery.data.status]}</b></p>{warrantyQuery.data.contract&&<div className="grid sm:grid-cols-2 gap-1"><p>Constructeur : <b>{warrantyQuery.data.contract.providerName??'Non renseigné'}</b></p><p>Limite kilométrique : <b>{warrantyQuery.data.contract.mileageLimit==null?'Non renseignée':`${warrantyQuery.data.contract.mileageLimit.toLocaleString('fr-FR')} km`}</b></p><p>Kilométrage de réception : <b>{warrantyQuery.data.currentMileage==null?'À déterminer':`${warrantyQuery.data.currentMileage.toLocaleString('fr-FR')} km`}</b></p></div>}</>:<p>Contexte Garantie indisponible.</p>}</div>}
  <div className="flex justify-end gap-2.5 pt-3 border-t"><Button variant="outline" type="button" onClick={onClose}>Annuler</Button><Button type="submit" disabled={busy||vehiclesQuery.isFetching||advisorsQuery.isFetching||!form.vehicleId||!form.customerId||!advisors.some(a=>a.id===advisorId)}>{createOrder.isPending?'Ouverture…':"Ouvrir l'Ordre de Réparation"}</Button></div>
 </form></Modal>
};
