import { Injectable, NotFoundException } from '@nestjs/common';
import { RowDataPacket } from 'mysql2';
import { DatabaseService } from '../../database/database.service';
import { CreateVehicleDto } from './vehicles.dto';
@Injectable()
export class VehiclesService {
  constructor(private readonly db:DatabaseService){}
  private readonly select=`SELECT v.id,v.vin,v.stock_number,v.registration_number,v.year,v.color,v.fuel_type,v.engine,v.transmission,v.mileage,v.purchase_price,v.additional_costs,v.catalog_price,v.sale_price,v.discount,v.status,v.entry_date,v.created_at,ve.name version,m.name model,b.name brand,a.id agency_id,a.name agency_name,l.id location_id,l.name location_name,s.id supplier_id,s.name supplier_name FROM vehicles v JOIN versions ve ON ve.id=v.version_id JOIN models m ON m.id=ve.model_id JOIN brands b ON b.id=m.brand_id JOIN agencies a ON a.id=v.agency_id LEFT JOIN locations l ON l.id=v.location_id LEFT JOIN suppliers s ON s.id=v.supplier_id`;
  private map(r:RowDataPacket){return{id:r.id,vin:r.vin,stockNumber:r.stock_number,registrationNumber:r.registration_number,year:r.year,color:r.color,fuelType:r.fuel_type,engine:r.engine,transmission:r.transmission,mileage:r.mileage,purchasePrice:r.purchase_price,additionalCosts:r.additional_costs,catalogPrice:r.catalog_price,salePrice:r.sale_price,discount:r.discount,status:r.status,entryDate:r.entry_date,createdAt:r.created_at,version:r.version,model:r.model,brand:r.brand,agencyId:r.agency_id,agencyName:r.agency_name,locationId:r.location_id,locationName:r.location_name,supplierId:r.supplier_id,supplierName:r.supplier_name};}
  async findAll(status?:string,agencyId?:string){const where:string[]=[];const params:unknown[]=[];if(status){where.push('v.status=?');params.push(status);}if(agencyId){where.push('v.agency_id=?');params.push(agencyId);}const rows=await this.db.query<RowDataPacket[]>(`${this.select}${where.length?' WHERE '+where.join(' AND '):''} ORDER BY v.created_at DESC`,params);return rows.map(r=>this.map(r));}
  async findOne(id:string){const [row]=await this.db.query<RowDataPacket[]>(`${this.select} WHERE v.id=?`,[id]);if(!row)throw new NotFoundException('Véhicule introuvable');return this.map(row);}
  async create(d:CreateVehicleDto){const id=await this.db.transaction(async c=>{await c.execute(`INSERT INTO brands(name,code)VALUES(?,?) ON DUPLICATE KEY UPDATE id=LAST_INSERT_ID(id)`,[d.brand,d.brand.toUpperCase().replace(/\W+/g,'-')]);const [brands]=await c.execute<RowDataPacket[]>('SELECT id FROM brands WHERE name=?',[d.brand]);await c.execute(`INSERT INTO models(brand_id,name,code)VALUES(?,?,?) ON DUPLICATE KEY UPDATE id=LAST_INSERT_ID(id)`,[brands[0].id,d.model,d.model.toUpperCase().replace(/\W+/g,'-')]);const [models]=await c.execute<RowDataPacket[]>('SELECT id FROM models WHERE brand_id=? AND name=?',[brands[0].id,d.model]);const [versions]=await c.execute<RowDataPacket[]>('SELECT id FROM versions WHERE model_id=? AND name=? LIMIT 1',[models[0].id,d.version]);let versionId=versions[0]?.id;if(!versionId){const[v]:any=await c.execute('INSERT INTO versions(model_id,name,fuel_type,transmission)VALUES(?,?,?,?)',[models[0].id,d.version,d.fuelType??null,d.transmission??null]);versionId=v.insertId}const[r]:any=await c.execute(`INSERT INTO vehicles(version_id,agency_id,vin,stock_number,registration_number,year,color,fuel_type,transmission,mileage,purchase_price,additional_costs,catalog_price,sale_price,status,entry_date)VALUES(?,?,?,CONCAT('STK-',YEAR(CURDATE()),'-',LPAD(FLOOR(RAND()*99999),5,'0')),?,?,?,?,?,?,?,?,?,?,'available',CURDATE())`,[versionId,d.agencyId,d.vin,d.registrationNumber??null,d.year??null,d.color??null,d.fuelType??null,d.transmission??null,d.mileage??0,d.purchasePrice??0,d.additionalCosts??0,d.catalogPrice??0,d.salePrice??0]);return String(r.insertId)});return this.findOne(id)}
  async updateStatus(id:string,status:string,userId:string){await this.db.transaction(async c=>{const [rows]=await c.execute<RowDataPacket[]>('SELECT status FROM vehicles WHERE id=? FOR UPDATE',[id]);if(!rows[0])throw new NotFoundException('Véhicule introuvable');await c.execute('UPDATE vehicles SET status=? WHERE id=?',[status,id]);await c.execute('INSERT INTO vehicle_status_history(vehicle_id,old_status,new_status,changed_by) VALUES(?,?,?,?)',[id,rows[0].status,status,userId]);});return this.findOne(id);}
}
