ALTER TABLE showroom_visits
  ADD COLUMN lead_id BIGINT UNSIGNED NULL AFTER customer_id,
  ADD COLUMN greeted_by BIGINT UNSIGNED NULL AFTER assigned_user_id,
  ADD COLUMN preferred_model VARCHAR(200) NULL AFTER reason,
  ADD COLUMN outcome ENUM('pending','lead_created','quotation','sale','no_interest','follow_up') NOT NULL DEFAULT 'pending' AFTER status,
  ADD COLUMN cancellation_reason VARCHAR(255) NULL AFTER completed_at,
  ADD COLUMN updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP AFTER notes,
  ADD INDEX idx_showroom_agency_status_arrival (agency_id,status,arrival_at),
  ADD INDEX idx_showroom_phone (phone),
  ADD INDEX idx_showroom_lead (lead_id),
  ADD CONSTRAINT fk_showroom_lead FOREIGN KEY (lead_id) REFERENCES leads(id) ON DELETE SET NULL,
  ADD CONSTRAINT fk_showroom_greeter FOREIGN KEY (greeted_by) REFERENCES users(id) ON DELETE SET NULL;

CREATE TABLE showroom_test_drives (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  visit_id BIGINT UNSIGNED NOT NULL,
  customer_id BIGINT UNSIGNED NULL,
  lead_id BIGINT UNSIGNED NULL,
  vehicle_id BIGINT UNSIGNED NOT NULL,
  agency_id BIGINT UNSIGNED NOT NULL,
  advisor_id BIGINT UNSIGNED NOT NULL,
  created_by BIGINT UNSIGNED NULL,
  driver_name VARCHAR(200) NOT NULL,
  driver_phone VARCHAR(50) NULL,
  license_number VARCHAR(100) NULL,
  mileage_out INT UNSIGNED NOT NULL,
  mileage_in INT UNSIGNED NULL,
  status ENUM('planned','in_progress','completed','cancelled') NOT NULL DEFAULT 'planned',
  started_at DATETIME NULL,
  returned_at DATETIME NULL,
  customer_feedback TEXT NULL,
  internal_notes TEXT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX idx_test_drive_visit (visit_id),
  INDEX idx_test_drive_vehicle_status (vehicle_id,status),
  INDEX idx_test_drive_agency_date (agency_id,created_at),
  CONSTRAINT fk_td_visit FOREIGN KEY (visit_id) REFERENCES showroom_visits(id) ON DELETE CASCADE,
  CONSTRAINT fk_td_customer FOREIGN KEY (customer_id) REFERENCES customers(id) ON DELETE SET NULL,
  CONSTRAINT fk_td_lead FOREIGN KEY (lead_id) REFERENCES leads(id) ON DELETE SET NULL,
  CONSTRAINT fk_td_vehicle FOREIGN KEY (vehicle_id) REFERENCES vehicles(id) ON DELETE RESTRICT,
  CONSTRAINT fk_td_agency FOREIGN KEY (agency_id) REFERENCES agencies(id) ON DELETE RESTRICT,
  CONSTRAINT fk_td_advisor FOREIGN KEY (advisor_id) REFERENCES users(id) ON DELETE RESTRICT,
  CONSTRAINT fk_td_creator FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB;
