import { BadRequestException,ConflictException,Injectable,NotFoundException } from '@nestjs/common';
import { RowDataPacket } from 'mysql2/promise';
import { DatabaseService } from '../../database/database.service';
import { RealtimeGateway } from '../../realtime/realtime.gateway';
import { AddRepairOrderItemDto,AssignRepairOrderDto,CreateRepairOrderDto } from './workshop.dto';
@Injectable()export class WorkshopService{constructor(private readonly db:DatabaseService,private readonly rt:RealtimeGateway){}
async list(agencyId?:string|null){return this.db.query<RowDataPacket[]>(`SELECT ro.*,CONCAT_WS(' ',c.first_name,c.last_name) customer_name,c.phone customer_phone,v.vin,v.registration_number,CONCAT(b.name,' ',m.name,' ',ve.name) vehicle_label,CONCAT_WS(' ',u.first_name,u.last_name) advisor_name FROM repair_orders ro JOIN customers c ON c.id=ro.customer_id JOIN vehicles v ON v.id=ro.vehicle_id JOIN versions ve ON ve.id=v.version_id JOIN models m ON m.id=ve.model_id JOIN brands b ON b.id=m.brand_id LEFT JOIN users u ON u.id=ro.advisor_id WHERE (? IS NULL OR ro.agency_id=?) ORDER BY ro.created_at DESC`,[agencyId??null,agencyId??null])}
async detail(id:string){const rows=await this.db.query<RowDataPacket[]>(`SELECT ro.*,CONCAT_WS(' ',c.first_name,c.last_name) customer_name,c.phone customer_phone,v.vin,v.registration_number,CONCAT(b.name,' ',m.name,' ',ve.name) vehicle_label,CONCAT_WS(' ',u.first_name,u.last_name) advisor_name FROM repair_orders ro JOIN customers c ON c.id=ro.customer_id JOIN vehicles v ON v.id=ro.vehicle_id JOIN versions ve ON ve.id=v.version_id JOIN models m ON m.id=ve.model_id JOIN brands b ON b.id=m.brand_id LEFT JOIN users u ON u.id=ro.advisor_id WHERE ro.id=?`,[id]);if(!rows[0])throw new NotFoundException('Ordre de réparation introuvable');const items=await this.db.query<RowDataPacket[]>('SELECT roi.*,p.reference part_reference FROM repair_order_items roi LEFT JOIN parts p ON p.id=roi.part_id WHERE roi.repair_order_id=? ORDER BY roi.id',[id]);const schedules=await this.db.query<RowDataPacket[]>(`SELECT s.*,CONCAT_WS(' ',u.first_name,u.last_name) technician_name,wb.name bay_name FROM schedules s LEFT JOIN technicians t ON t.id=s.technician_id LEFT JOIN users u ON u.id=t.user_id LEFT JOIN workshop_bays wb ON wb.id=s.bay_id WHERE s.repair_order_id=? ORDER BY s.starts_at DESC`,[id]);return{...rows[0],items,schedules}}
async create(d:CreateRepairOrderDto,userId:string){const no=`OR-${Date.now()}`;const r=await this.db.execute(`INSERT INTO repair_orders(order_number,appointment_id,customer_id,vehicle_id,agency_id,advisor_id,mileage_in,complaint,diagnosis_summary,status,received_at) VALUES(?,?,?,?,?,?,?,?,?,'planned',NULL)`,[no,d.appointmentId??null,d.customerId,d.vehicleId,d.agencyId,d.advisorId??userId,d.mileage??null,d.complaint,d.diagnosisSummary??null]);this.rt.emitAgency(d.agencyId,'workshop:repair-order-created',{id:String(r.insertId),orderNumber:no});return this.detail(String(r.insertId))}
async status(id:string,status:string){const flow=['planned','received','diagnosis','waiting_approval','in_progress','quality_control','ready','invoiced','delivered','closed'];const rows=await this.db.query<RowDataPacket[]>('SELECT agency_id,status FROM repair_orders WHERE id=?',[id]);const ro=rows[0];if(!ro)throw new NotFoundException('Ordre de réparation introuvable');const valid=status==='cancelled'||flow.indexOf(status)===flow.indexOf(String(ro.status))+1;if(!valid)throw new BadRequestException(`Transition ${ro.status} → ${status} interdite`);await this.db.execute(`UPDATE repair_orders SET status=?,received_at=IF(?='received',NOW(),received_at),closed_at=IF(?='closed',NOW(),closed_at) WHERE id=?`,[status,status,status,id]);this.rt.emitAgency(String(ro.agency_id),'workshop:status',{id,status});return this.detail(id)}
async assign(id:string,d:AssignRepairOrderDto){const rows=await this.db.query<RowDataPacket[]>('SELECT agency_id FROM repair_orders WHERE id=?',[id]);const ro=rows[0];if(!ro)throw new NotFoundException('Ordre de réparation introuvable');const r=await this.db.execute(`INSERT INTO schedules(agency_id,technician_id,bay_id,repair_order_id,starts_at,ends_at,status) VALUES(?,?,?,?,?,?,'confirmed')`,[ro.agency_id,d.technicianId,d.bayId??null,id,d.startsAt,d.endsAt]);this.rt.emitAgency(String(ro.agency_id),'workshop:assigned',{repairOrderId:id,technicianId:d.technicianId,bayId:d.bayId});return{id:String(r.insertId)}}
async addItem(id:string,d:AddRepairOrderItemDto,userId:string){await this.db.transaction(async c=>{const[orders]=await c.execute<RowDataPacket[]>('SELECT agency_id FROM repair_orders WHERE id=? FOR UPDATE',[id]);if(!orders[0])throw new NotFoundException('Ordre de réparation introuvable');if(d.itemType==='part'){if(!d.partId)throw new BadRequestException('La pièce est obligatoire');let sql='SELECT * FROM part_stocks WHERE part_id=? AND agency_id=?',params:any[]=[d.partId,orders[0].agency_id];if(d.locationId){sql+=' AND location_id=?';params.push(d.locationId)}sql+=' FOR UPDATE';const[stocks]=await c.execute<RowDataPacket[]>(sql,params);if(!stocks[0])throw new NotFoundException("Stock de la pièce introuvable dans l'agence");if(!d.locationId&&stocks.length>1)throw new BadRequestException('Emplacement requis');const stock=stocks[0];if(Number(stock.current_stock)-Number(stock.reserved_stock)<d.quantity)throw new ConflictException('Stock disponible insuffisant');await c.execute('UPDATE part_stocks SET current_stock=current_stock-? WHERE id=?',[d.quantity,stock.id]);await c.execute(`INSERT INTO part_movements(part_id,agency_id,location_id,movement_type,quantity,reference_type,reference_id,reason,performed_by) VALUES(?,?,?,'repair_order',?,'repair_order',?,'Consommation atelier',?)`,[d.partId,orders[0].agency_id,stock.location_id,-d.quantity,id,userId])}const line=d.quantity*d.unitPrice-(d.discount??0);await c.execute(`INSERT INTO repair_order_items(repair_order_id,part_id,item_type,description,quantity,unit_price,discount,tax_rate,line_total) VALUES(?,?,?,?,?,?,?,?,?)`,[id,d.partId??null,d.itemType,d.description,d.quantity,d.unitPrice,d.discount??0,d.taxRate??0,line]);await c.execute('UPDATE repair_orders SET estimated_total=(SELECT COALESCE(SUM(line_total*(1+tax_rate/100)),0) FROM repair_order_items WHERE repair_order_id=?) WHERE id=?',[id,id])});return this.detail(id)}
async planning(agencyId:string,date:string){return this.db.query<RowDataPacket[]>(`SELECT s.*,ro.order_number,t.employee_code,CONCAT_WS(' ',u.first_name,u.last_name) technician_name,b.name bay_name FROM schedules s LEFT JOIN repair_orders ro ON ro.id=s.repair_order_id LEFT JOIN technicians t ON t.id=s.technician_id LEFT JOIN users u ON u.id=t.user_id LEFT JOIN workshop_bays b ON b.id=s.bay_id WHERE s.agency_id=? AND DATE(s.starts_at)=? ORDER BY s.starts_at`,[agencyId,date])}
async technicians(){return this.db.query<RowDataPacket[]>(`SELECT t.*,CONCAT_WS(' ',u.first_name,u.last_name) name FROM technicians t JOIN users u ON u.id=t.user_id WHERE t.is_active=TRUE ORDER BY name`)}}
