import React from'react';
import{useNavigate}from'react-router-dom';
import{useDeliveryFinancialAuthorizationActions,useDeliveryFinancialAuthorizations}from'../../api/erpHooks';
import{Button}from'../../components/ui/Button';
import{Card,CardHeader,CardTitle}from'../../components/ui/Card';
import{Badge}from'../../components/ui/Badge';
import{formatCurrency,formatDate,formatDateTime}from'../../lib/utils';
import{useAuthStore}from'../../stores/authStore';
import{useUiStore}from'../../stores/uiStore';

export const DeliveryFinancialAuthorizationPanel:React.FC<{saleId:string;total:number;paid:number;balance:number;currency?:string;compact?:boolean}>=({saleId,total,paid,balance,currency='XAF',compact=false})=>{
 const can=useAuthStore(s=>s.can),canAuthorize=can('delivery.financial_override.authorize'),canView=can('delivery.view')||canAuthorize,query=useDeliveryFinancialAuthorizations(saleId,canView),actions=useDeliveryFinancialAuthorizationActions(),toast=useUiStore(s=>s.addToast),navigate=useNavigate(),rows=query.data??[],active=rows.find((x:any)=>x.status==='AUTHORIZED'),valid=active&&balance>0&&balance<=Number(active.balance_due_snapshot)+.001;
 const authorize=async()=>{const reason=window.prompt('Motif obligatoire de la dérogation financière');if(!reason?.trim())return;const guaranteeType=window.prompt('Type de garantie ou sûreté (facultatif)')||null,guaranteeDetails=window.prompt('Détails de la garantie (facultatif)')||null,guaranteeReference=window.prompt('Référence de garantie (facultatif)')||null,balanceDueDate=window.prompt('Échéance prévue AAAA-MM-JJ (facultatif)')||null,paymentTerms=window.prompt('Modalités de règlement du solde (facultatif)')||null;if(!window.confirm(`Vous autorisez la livraison de ce véhicule alors qu’un solde de ${formatCurrency(balance)} reste dû. Cette action ne constitue pas un paiement.`))return;try{await actions.authorize.mutateAsync({saleId,reason:reason.trim(),guaranteeType,guaranteeDetails,guaranteeReference,balanceDueDate,paymentTerms,clientRequestId:crypto.randomUUID()});toast({type:'success',title:'Livraison avec solde autorisée',description:'La facture reste non soldée et encaissable.'})}catch(error){toast({type:'error',title:'Autorisation impossible',description:error instanceof Error?error.message:'Erreur API'})}};
 const revoke=async()=>{if(!active)return;const reason=window.prompt('Motif obligatoire de révocation');if(!reason?.trim())return;try{await actions.revoke.mutateAsync({authorizationId:String(active.id),saleId,reason:reason.trim()});toast({type:'success',title:'Autorisation révoquée'})}catch(error){toast({type:'error',title:'Révocation impossible',description:error instanceof Error?error.message:'Erreur API'})}};
 if(!canView)return null;
 return <Card><CardHeader><CardTitle>Autorisation financière de livraison</CardTitle>{balance<=.001?<Badge variant="success">Facture soldée</Badge>:valid?<Badge variant="warning">Livraison autorisée avec solde</Badge>:active?<Badge variant="danger">Autorisation insuffisante</Badge>:<Badge variant="default">Aucune dérogation</Badge>}</CardHeader><div className="space-y-3 text-xs"><div className="grid grid-cols-3 gap-2"><div>Total<br/><b>{formatCurrency(total)}</b></div><div>Payé<br/><b>{formatCurrency(paid)}</b></div><div>Solde actuel<br/><b>{formatCurrency(balance)}</b></div></div>{active&&<div className={`rounded-lg border p-3 ${valid?'border-amber-200 bg-amber-50':'border-red-200 bg-red-50'}`}><p className="font-bold">{valid?'Livraison autorisée avec solde':'Autorisation financière insuffisante — nouvelle autorisation requise.'}</p><p>Solde autorisé : {formatCurrency(Number(active.balance_due_snapshot))} {active.currency_code||currency}</p><p>Solde actuel : {formatCurrency(balance)}</p><p>Échéance : {active.balance_due_date?formatDate(active.balance_due_date):'Non renseignée'}</p><p>Autorisé par {active.authorized_by_name||'—'} le {formatDateTime(active.authorized_at)}</p><p>Motif : {active.reason}</p></div>}{!compact&&rows.length>0&&<details><summary className="cursor-pointer font-semibold">Historique ({rows.length})</summary>{rows.map((row:any)=><p key={row.id} className="mt-1">#{row.id} · {row.status} · {formatCurrency(Number(row.balance_due_snapshot))}</p>)}</details>}<div className="flex flex-wrap gap-2">{canAuthorize&&balance>.001&&!valid&&<Button size="xs" loading={actions.authorize.isPending} onClick={()=>void authorize()}>Autoriser la livraison avec solde</Button>}{canAuthorize&&active?.status==='AUTHORIZED'&&<Button size="xs" variant="danger" loading={actions.revoke.isPending} onClick={()=>void revoke()}>Révoquer l’autorisation</Button>}{active&&<Button size="xs" variant="outline" onClick={()=>navigate(`/documents?entityType=delivery_financial_authorization&entityId=${active.id}`)}>Justificatifs GED</Button>}</div></div></Card>;
};
