import React,{useState}from'react';
import{ArrowDown,ArrowUp,Plus}from'lucide-react';
import{useDeliveryChecklistConfig,useDeliveryChecklistConfigActions}from'../../api/erpHooks';
import{Button}from'../../components/ui/Button';
import{Card,CardHeader,CardTitle}from'../../components/ui/Card';
import{useAuthStore}from'../../stores/authStore';
import{useUiStore}from'../../stores/uiStore';

export const DeliveryChecklistTemplates:React.FC=()=>{
 const can=useAuthStore(s=>s.can),mayView=can('delivery.checklist.config.view')||can('delivery.checklist.config.manage'),mayManage=can('delivery.checklist.config.manage'),query=useDeliveryChecklistConfig(mayView),actions=useDeliveryChecklistConfigActions(),toast=useUiStore(s=>s.addToast),[categoryForm,setCategoryForm]=useState({code:'',name:'',description:''}),[itemCategory,setItemCategory]=useState(''),[itemForm,setItemForm]=useState({code:'',name:'',description:'',isMandatory:true});
 if(!mayView)return null;
 const fail=(error:unknown)=>toast({type:'error',title:'Configuration impossible',description:error instanceof Error?error.message:'Erreur API'}),ok=(title:string)=>toast({type:'success',title});
 const reorder=async(type:'category'|'item',ownerId:string,ids:string[],index:number,direction:-1|1)=>{const target=index+direction;if(target<0||target>=ids.length)return;[ids[index],ids[target]]=[ids[target]!,ids[index]!];try{if(type==='category')await actions.reorderCategories.mutateAsync(ids);else await actions.reorderItems.mutateAsync({categoryId:ownerId,ids});ok('Ordre enregistré')}catch(error){fail(error)}};
 const createCategory=async(e:React.FormEvent)=>{e.preventDefault();try{await actions.createCategory.mutateAsync(categoryForm);setCategoryForm({code:'',name:'',description:''});ok('Catégorie créée')}catch(error){fail(error)}};
 const createItem=async(e:React.FormEvent)=>{e.preventDefault();if(!itemCategory)return;try{await actions.createItem.mutateAsync({categoryId:itemCategory,...itemForm});setItemForm({code:'',name:'',description:'',isMandatory:true});ok('Élément créé')}catch(error){fail(error)}};
 const categories=query.data??[];
 return <div className="space-y-4">
  <Card><CardHeader><div><CardTitle>Checklist de livraison configurable</CardTitle><p className="text-xs text-slate-500">Modèle concession appliqué une seule fois au démarrage réel de chaque préparation. Les livraisons déjà démarrées conservent leur snapshot.</p></div></CardHeader>
   {mayManage&&<form onSubmit={createCategory} className="grid gap-2 md:grid-cols-4"><input required placeholder="Code stable" value={categoryForm.code} onChange={e=>setCategoryForm({...categoryForm,code:e.target.value})} className="rounded border p-2 text-sm"/><input required placeholder="Nom de l’étape" value={categoryForm.name} onChange={e=>setCategoryForm({...categoryForm,name:e.target.value})} className="rounded border p-2 text-sm"/><input placeholder="Description" value={categoryForm.description} onChange={e=>setCategoryForm({...categoryForm,description:e.target.value})} className="rounded border p-2 text-sm"/><Button type="submit" size="sm" icon={<Plus className="h-3 w-3"/>}>Ajouter une étape</Button></form>}
  </Card>
  {categories.map((category:any,index:number)=><Card key={category.id} className={!category.is_active?'opacity-60':''}><div className="flex flex-wrap items-start justify-between gap-3"><div><div className="text-xs font-bold text-[#8f1722]">ÉTAPE {index+1} · {category.code}</div><h3 className="font-bold">{category.name}</h3><p className="text-xs text-slate-500">{category.description||'Sans description'} · {category.is_active?'Active':'Inactive'}</p></div>{mayManage&&<div className="flex gap-1"><Button size="xs" variant="outline" aria-label="Monter la catégorie" onClick={()=>void reorder('category','',categories.map((x:any)=>String(x.id)),index,-1)}><ArrowUp className="h-3 w-3"/></Button><Button size="xs" variant="outline" aria-label="Descendre la catégorie" onClick={()=>void reorder('category','',categories.map((x:any)=>String(x.id)),index,1)}><ArrowDown className="h-3 w-3"/></Button><Button size="xs" variant="outline" onClick={()=>{const name=window.prompt('Nom de l’étape',category.name);if(name!=null)void actions.updateCategory.mutateAsync({id:category.id,name,description:category.description??''}).catch(fail)}}>Modifier</Button><Button size="xs" variant={category.is_active?'danger':'success'} onClick={()=>void actions.categoryStatus.mutateAsync({id:category.id,isActive:!category.is_active}).catch(fail)}>{category.is_active?'Désactiver':'Activer'}</Button></div>}</div>
   <div className="mt-3 divide-y rounded border">{category.items.map((item:any,itemIndex:number)=><div key={item.id} className="flex items-center justify-between gap-3 p-3 text-xs"><div><b>{item.name}</b> <span className="text-slate-500">{item.is_mandatory?'Obligatoire':'Facultatif'} · {item.is_active?'Actif':'Inactif'}</span></div>{mayManage&&<div className="flex gap-1"><Button size="xs" variant="ghost" aria-label="Monter l’élément" onClick={()=>void reorder('item',String(category.id),category.items.map((x:any)=>String(x.id)),itemIndex,-1)}><ArrowUp className="h-3 w-3"/></Button><Button size="xs" variant="ghost" aria-label="Descendre l’élément" onClick={()=>void reorder('item',String(category.id),category.items.map((x:any)=>String(x.id)),itemIndex,1)}><ArrowDown className="h-3 w-3"/></Button><Button size="xs" variant="outline" onClick={()=>{const name=window.prompt('Libellé',item.name);if(name!=null)void actions.updateItem.mutateAsync({id:item.id,name,description:item.description??'',isMandatory:item.is_mandatory}).catch(fail)}}>Modifier</Button><Button size="xs" variant={item.is_active?'danger':'success'} onClick={()=>void actions.itemStatus.mutateAsync({id:item.id,isActive:!item.is_active}).catch(fail)}>{item.is_active?'Désactiver':'Activer'}</Button></div>}</div>)}</div>
   {mayManage&&<Button className="mt-3" size="xs" variant="outline" onClick={()=>setItemCategory(String(category.id))}>Ajouter un élément</Button>}
  </Card>)}
  {mayManage&&itemCategory&&<Card><form onSubmit={createItem} className="grid gap-2 md:grid-cols-4"><input required placeholder="Code stable" value={itemForm.code} onChange={e=>setItemForm({...itemForm,code:e.target.value})} className="rounded border p-2 text-sm"/><input required placeholder="Libellé" value={itemForm.name} onChange={e=>setItemForm({...itemForm,name:e.target.value})} className="rounded border p-2 text-sm"/><label className="flex items-center gap-2 text-xs"><input type="checkbox" checked={itemForm.isMandatory} onChange={e=>setItemForm({...itemForm,isMandatory:e.target.checked})}/> Obligatoire</label><div className="flex gap-2"><Button type="submit" size="sm">Créer</Button><Button type="button" size="sm" variant="outline" onClick={()=>setItemCategory('')}>Annuler</Button></div></form></Card>}
 </div>;
};
