import React, { useDeferredValue, useEffect, useState } from 'react';
import { CalendarDays, CheckCircle2, Clock, Grid2X2, List, Printer, Search, Truck } from 'lucide-react';
import { useNavigate, useSearchParams } from 'react-router-dom';
import { useDeliveriesPageQuery, useDeliveryCandidatesQuery, useDeliveryStatsQuery } from '../../api/erpHooks';
import { PageHeader } from '../../components/common/PageHeader';
import { Badge } from '../../components/ui/Badge';
import { Button } from '../../components/ui/Button';
import { Card } from '../../components/ui/Card';
import { formatDate } from '../../lib/utils';
import { openBusinessPdf, openDeliveryPlanningPdf } from '../../services/businessPdf';
import { useUiStore } from '../../stores/uiStore';
import { NewDeliveryModal } from './NewDeliveryModal';
import { useAuthStore } from '../../stores/authStore';

export const DeliveriesPage:React.FC=()=>{
  const navigate=useNavigate(),[params]=useSearchParams(),requestedSaleId=params.get('saleId')??'',addToast=useUiStore(s=>s.addToast),can=useAuthStore(s=>s.can),canView=can('delivery.view'),canCreate=can('delivery.schedule'),canViewDocuments=can('delivery.documents.view');
  const [newOpen,setNewOpen]=useState(Boolean(requestedSaleId)&&canCreate),[search,setSearch]=useState(''),[status,setStatus]=useState(''),[date,setDate]=useState(new Date().toISOString().slice(0,10)),[page,setPage]=useState(1),[view,setView]=useState<'cards'|'list'>('cards');
  const deferredSearch=useDeferredValue(search),list=useDeliveriesPageQuery({search:deferredSearch,status,page,pageSize:7},canView),stats=useDeliveryStatsQuery(canView),deliveries=list.data?.items??[];
  useEffect(()=>setPage(1),[deferredSearch,status]);
  useEffect(()=>{if(list.data&&page>Math.max(1,list.data.totalPages))setPage(Math.max(1,list.data.totalPages))},[list.data,page]);
  const candidatesQuery=useDeliveryCandidatesQuery(canCreate),candidates=candidatesQuery.data??[];
  const error=(title:string,value:unknown)=>addToast({type:'error',title,description:value instanceof Error?value.message:'Erreur API'});
  return <div className="space-y-6">
    <PageHeader title="Livraisons véhicules" subtitle="Planification, préparation qualité, remise client et traçabilité." breadcrumbs={[{label:'Accueil',href:'/dashboard'},{label:'Livraisons'}]} actions={<div className="flex gap-2">{canCreate&&<Button size="sm" onClick={()=>setNewOpen(true)}>Planifier</Button>}<Button size="sm" variant="outline" icon={<Printer className="w-4 h-4"/>} onClick={()=>openDeliveryPlanningPdf(date).catch(value=>error('Planning indisponible',value))}>Planning PDF</Button></div>}/>
    {stats.isError&&<ErrorBox error={stats.error} retry={()=>stats.refetch()}/>}
    <div className="grid grid-cols-2 lg:grid-cols-5 gap-3">{[['Total',stats.data?.total??0,Truck],['Planifiées',stats.data?.planned??0,CalendarDays],['En préparation',stats.data?.preparing??0,Clock],['Prêtes',stats.data?.ready??0,CheckCircle2],['Livrées',stats.data?.delivered??0,CheckCircle2]].map(([label,value,Icon]:any)=><Card key={label}><Icon className="w-4 h-4 text-[#8f1722]"/><div className="text-2xl font-bold mt-2">{value}</div><div className="text-xs text-slate-500">{label}</div></Card>)}</div>
    <Card className="flex flex-col md:flex-row gap-3"><label className="relative flex-1"><Search className="absolute left-3 top-3 w-4 h-4 text-slate-400"/><input aria-label="Rechercher une livraison" value={search} onChange={e=>setSearch(e.target.value)} placeholder="Client, téléphone, VIN, immatriculation…" className="w-full border rounded-lg py-2.5 pl-9 pr-3 text-sm"/></label><select aria-label="Filtrer par statut" value={status} onChange={e=>setStatus(e.target.value)} className="border rounded-lg px-3 text-sm"><option value="">Tous les statuts</option><option value="planned">Planifiées</option><option value="preparing">Préparation</option><option value="quality_control">Contrôle qualité</option><option value="ready">Prêtes</option><option value="delivered">Livrées</option><option value="cancelled">Annulées</option></select><input aria-label="Date du planning PDF" type="date" value={date} onChange={e=>setDate(e.target.value)} className="border rounded-lg px-3 text-sm"/><div className="flex rounded-lg border p-1"><Button size="xs" variant={view==='cards'?'primary':'ghost'} icon={<Grid2X2 className="h-3.5 w-3.5"/>} onClick={()=>setView('cards')}>Cartes</Button><Button size="xs" variant={view==='list'?'primary':'ghost'} icon={<List className="h-3.5 w-3.5"/>} onClick={()=>setView('list')}>Liste</Button></div></Card>
    {candidates.length>0&&<Card><div className="flex items-center justify-between gap-3"><div><h2 className="font-bold">Ventes à planifier</h2><p className="text-xs text-slate-500">{candidates.length} dossier(s) prêt(s) pour le planning de livraison.</p></div>{canCreate&&<Button size="sm" onClick={()=>setNewOpen(true)}>Planifier maintenant</Button>}</div></Card>}
    {list.isLoading&&<div className="p-10 text-center text-sm text-slate-500">Chargement des livraisons…</div>}
    {list.isError&&<ErrorBox error={list.error} retry={()=>list.refetch()}/>}
    {!list.isLoading&&!list.isError&&<>{view==='cards'?<div className="grid md:grid-cols-2 xl:grid-cols-3 gap-5">{deliveries.map((item:any)=><DeliveryCard key={item.id} item={item} actions={<DeliveryActions item={item} canViewDocuments={canViewDocuments} open={()=>navigate(`/deliveries/${item.id}`)} error={error}/>}/>)}{!deliveries.length&&<EmptyDeliveries/>}</div>:<Card padding="none"><div className="overflow-x-auto"><table className="w-full text-left text-xs"><thead className="border-b bg-slate-50 text-slate-500 uppercase"><tr><th className="p-3">Livraison</th><th className="p-3">Client</th><th className="p-3">Véhicule / VIN</th><th className="p-3">Date prévue</th><th className="p-3">Statut</th><th className="p-3 text-right">Actions</th></tr></thead><tbody className="divide-y">{deliveries.map((item:any)=><tr key={item.id}><td className="p-3 font-bold">{item.deliveryNumber}</td><td className="p-3"><b>{item.customerName}</b><div className="text-slate-500">{item.customerPhone}</div></td><td className="p-3"><b>{item.vehicleLabel}</b><div className="font-mono text-[10px]">{item.vehicleVin}</div></td><td className="p-3">{formatDate(item.deliveryDate)} {item.deliveryTimeSlot}</td><td className="p-3"><DeliveryStatus item={item}/></td><td className="p-3"><DeliveryActions item={item} canViewDocuments={canViewDocuments} open={()=>navigate(`/deliveries/${item.id}`)} error={error}/></td></tr>)}</tbody></table>{!deliveries.length&&<div className="p-10 text-center text-sm text-slate-500">Aucune livraison ne correspond aux filtres.</div>}</div></Card>}<Pager page={list.data?.page??page} totalPages={list.data?.totalPages??0} total={list.data?.total??0} onPage={setPage}/></>}
    <NewDeliveryModal isOpen={newOpen} initialSaleId={requestedSaleId} onClose={()=>setNewOpen(false)}/>
  </div>;
};

const DeliveryStatus=({item}:{item:any})=><Badge variant={item.status==='LIVRE_SIGNE'?'success':item.status==='REPORTE'?'danger':'primary'}>{item.status.replaceAll('_',' ')}</Badge>;
const DeliveryActions=({item,canViewDocuments,open,error}:{item:any;canViewDocuments:boolean;open:()=>void;error:(title:string,value:unknown)=>void})=><div className="flex justify-end gap-2">{canViewDocuments&&<Button size="xs" variant="outline" onClick={()=>openBusinessPdf('delivery',item.id).catch(value=>error('PV indisponible',value))}>PV</Button>}<Button size="xs" onClick={open}>Ouvrir</Button></div>;
const DeliveryCard=({item,actions}:{item:any;actions:React.ReactNode})=><Card className="space-y-4"><div className="flex justify-between"><div><div className="font-bold">{item.deliveryNumber}</div><div className="text-xs text-slate-500">{formatDate(item.deliveryDate)} {item.deliveryTimeSlot}</div></div><DeliveryStatus item={item}/></div><div className="bg-slate-50 rounded-lg p-3 text-sm"><strong>{item.customerName}</strong><div className="text-xs text-slate-500">{item.customerPhone}</div><div className="mt-2 text-xs font-semibold">{item.vehicleLabel}</div><div className="font-mono text-[11px]">{item.vehicleVin}</div></div><div className="text-xs"><div className="flex justify-between"><span>Checklist</span><strong>{item.checklistProgress?.completed??0}/{item.checklistProgress?.total??0}</strong></div><div className="h-1.5 bg-slate-100 rounded mt-1"><div className="h-full bg-[#8f1722] rounded" style={{width:`${item.checklistProgress?.total?item.checklistProgress.completed/item.checklistProgress.total*100:0}%`}}/></div></div>{actions}</Card>;
const EmptyDeliveries=()=> <div className="col-span-full border border-dashed rounded-xl p-12 text-center text-sm text-slate-500">Aucune livraison ne correspond aux filtres.</div>;
const Pager=({page,totalPages,total,onPage}:{page:number;totalPages:number;total:number;onPage:(page:number)=>void})=><div className="flex items-center justify-between rounded-xl border bg-white p-3 text-xs"><span>{total} livraison(s)</span><div className="flex items-center gap-2"><Button size="xs" variant="outline" disabled={page<=1} onClick={()=>onPage(page-1)}>Précédent</Button><span>Page {page} / {Math.max(1,totalPages)}</span><Button size="xs" variant="outline" disabled={page>=totalPages} onClick={()=>onPage(page+1)}>Suivant</Button></div></div>;

const ErrorBox:React.FC<{error:unknown;retry:()=>unknown}>=({error,retry})=><div className="p-4 border border-red-200 bg-red-50 rounded-xl text-sm text-red-800"><strong>Impossible de charger les livraisons.</strong> {error instanceof Error?error.message:'Erreur API'} <Button className="ml-2" size="xs" variant="outline" onClick={retry}>Réessayer</Button></div>;
