import React,{useEffect,useRef,useState}from'react';
import{ArrowLeft,CheckCircle2,Circle,Download,FileCheck,Printer,Upload}from'lucide-react';
import{useNavigate,useParams}from'react-router-dom';
import{useDeliveryActions,useDeliveryApplicableCategories,useDeliveryChecklist,useDeliveryDetailQuery,useSignDelivery,useVehicleReturnActions}from'../../api/erpHooks';
import{PageHeader}from'../../components/common/PageHeader';
import{Badge}from'../../components/ui/Badge';
import{Button}from'../../components/ui/Button';
import{Card,CardHeader,CardTitle}from'../../components/ui/Card';
import{formatDate}from'../../lib/utils';
import{openBusinessPdf}from'../../services/businessPdf';
import{useAuthStore}from'../../stores/authStore';
import{useUiStore}from'../../stores/uiStore';
import{apiDownload}from'../../services/apiClient';
import{DeliveryFinancialAuthorizationPanel}from'./DeliveryFinancialAuthorizationPanel';
import{DeliveryServicesPanel}from'./DeliveryServicesPanel';

export const DeliveryDetailPage:React.FC=()=>{
  const{id}=useParams(),navigate=useNavigate(),can=useAuthStore(s=>s.can);
  const canView=can('delivery.view'),canUpdate=can('delivery.prepare'),canSchedule=can('delivery.schedule'),canCancel=can('delivery.cancel'),canChecklistView=can('delivery.checklist.view')||can('delivery.checklist.manage'),canChecklist=can('delivery.checklist.manage'),canDocumentsView=can('delivery.documents.view')||can('delivery.checklist.manage'),canDocuments=can('delivery.checklist.manage'),canSign=can('delivery.signature.capture'),canComplete=can('delivery.complete'),canViewPayments=can('billing.payment.view'),canCreateReturn=can('vehicle.return.create'),addToast=useUiStore(s=>s.addToast),deliveryQuery=useDeliveryDetailQuery(id,canView),check=useDeliveryChecklist(),signMutation=useSignDelivery(),actions=useDeliveryActions(),returnActions=useVehicleReturnActions();
  const applicable=useDeliveryApplicableCategories(id,canUpdate&&deliveryQuery.data?.status==='planned');
  const[signer,setSigner]=useState(''),[mileage,setMileage]=useState(''),[signature,setSignature]=useState(''),[accepted,setAccepted]=useState(false),[documentName,setDocumentName]=useState(''),[file,setFile]=useState<File|null>(null),[selectedCategories,setSelectedCategories]=useState<string[]>([]),signLock=useRef(false);
  useEffect(()=>{if(applicable.data&&!selectedCategories.length)setSelectedCategories(applicable.data.map((category:any)=>String(category.id)))},[applicable.data,selectedCategories.length]);
  const delivery=deliveryQuery.data,fail=(title:string,error:unknown)=>addToast({type:'error',title,description:error instanceof Error?error.message:'Erreur API'});
  if(deliveryQuery.isLoading)return <div className="p-8 text-sm text-slate-500">Chargement de la livraison…</div>;
  if(deliveryQuery.isError||!delivery)return <div className="p-8"><p className="text-sm text-red-700">{deliveryQuery.error instanceof Error?deliveryQuery.error.message:'Livraison introuvable.'}</p><Button className="mt-4" variant="outline" onClick={()=>navigate('/deliveries')}>Retour</Button></div>;
  const checklistCategories=delivery.checklist_categories??[],documents=delivery.documents??[],delivered=delivery.status==='delivered',cancelled=delivery.status==='cancelled',readOnly=delivered||cancelled,mandatoryComplete=checklistCategories.length>0&&Number(delivery.checklist_progress?.mandatoryCompleted??0)===Number(delivery.checklist_progress?.mandatoryTotal??-1),documentsComplete=documents.filter((doc:any)=>doc.is_required).every((doc:any)=>doc.received);
  const warrantyUndetermined=!delivery.warranty_decision||delivery.warranty_decision==='UNDETERMINED',remaining=delivery.balance_due==null?null:Number(delivery.balance_due),financiallySettled=Boolean(delivery.financially_cleared),signDisabled=warrantyUndetermined||!financiallySettled||delivery.status!=='ready'||!mandatoryComplete||!documentsComplete||!accepted||!signature||!signer||!mileage;
  const updateItem=async(item:any)=>{if(!canChecklist||readOnly)return;try{await check.mutateAsync({deliveryId:id,itemId:String(item.id),completed:!item.is_completed})}catch(error){fail('Contrôle impossible',error)}};
  const changeStatus=async(status:string,reason?:string)=>{if(!canUpdate)return;try{await actions.status.mutateAsync({deliveryId:id,status,reason,...(status==='preparing'?{categoryIds:selectedCategories}: {})});addToast({type:'success',title:'Workflow actualisé',description:`Nouveau statut : ${status}`})}catch(error){fail('Transition impossible',error)}};
  const cancel=()=>{const reason=window.prompt("Motif obligatoire d’annulation");if(reason?.trim())void actions.cancel.mutateAsync({deliveryId:id,reason:reason.trim()}).catch(error=>fail('Annulation impossible',error))};
  const reschedule=async()=>{const date=window.prompt('Nouvelle date et heure (AAAA-MM-JJ HH:mm)');if(!date)return;const reason=window.prompt('Motif du report');if(!reason?.trim())return;try{await actions.reschedule.mutateAsync({deliveryId:id,scheduledAt:new Date(date.replace(' ','T')).toISOString(),reason:reason.trim()})}catch(error){fail('Report impossible',error)}};
  const createReturn=async()=>{const description=window.prompt('Décrivez précisément le motif du retour post-livraison');if(!description?.trim()||!id)return;try{const result:any=await returnActions.create.mutateAsync({deliveryId:id,reasonCode:'OTHER',description:description.trim(),requestId:crypto.randomUUID()});navigate(`/vehicle-returns/${result.id}`)}catch(error){fail('Création du retour impossible',error)}};
  const upload=async()=>{if(!canDocuments||readOnly)return;try{let dataBase64:string|undefined;if(file)dataBase64=await new Promise(resolve=>{const reader=new FileReader();reader.onload=()=>resolve(String(reader.result));reader.readAsDataURL(file)});await actions.addDocument.mutateAsync({deliveryId:id,documentName,fileName:file?.name,mimeType:file?.type,dataBase64,isRequired:true,received:false});setDocumentName('');setFile(null)}catch(error){fail('Document impossible',error)}};
  const downloadDocument=async(document:any)=>{try{const blob=await apiDownload(`/deliveries/${id}/documents/${document.id}/download`),url=URL.createObjectURL(blob),link=window.document.createElement('a');link.href=url;link.download=document.file_name||document.document_name||'document-livraison';link.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}catch(error){fail('Téléchargement impossible',error)}};
  const sign=async(event:React.FormEvent)=>{event.preventDefault();if(!canSign||!canComplete||signDisabled||signLock.current)return;signLock.current=true;try{await signMutation.mutateAsync({deliveryId:id,signerName:signer,signatureData:signature,consentText:'Le client confirme la réception du véhicule, de ses clés et des documents.',mileageAtDelivery:Number(mileage)});addToast({type:'success',title:'Véhicule livré',description:'La vente, le véhicule et le PV ont été actualisés.'})}catch(error){fail('Signature impossible',error)}finally{signLock.current=false}};
  return <div className="space-y-6">
    <PageHeader title={`Livraison ${delivery.delivery_number}`} subtitle={`${delivery.customer_name} · ${delivery.vehicle_label}`} breadcrumbs={[{label:'Livraisons',href:'/deliveries'},{label:delivery.delivery_number}]} actions={<div className="flex gap-2"><Button variant="outline" size="sm" icon={<ArrowLeft className="w-4 h-4"/>} onClick={()=>navigate('/deliveries')}>Retour</Button>{canDocumentsView&&<Button size="sm" icon={<Printer className="w-4 h-4"/>} onClick={()=>openBusinessPdf('delivery',String(id)).catch(error=>fail('PV indisponible',error))}>PV PDF</Button>}</div>}/>
    <Card><div className="flex gap-2 flex-wrap items-center"><Badge variant={delivered?'success':cancelled?'danger':'primary'}>{delivery.status}</Badge>{canSchedule&&!readOnly&&<Button size="xs" variant="outline" onClick={reschedule}>Reporter</Button>}{canCancel&&!readOnly&&<Button size="xs" variant="danger" onClick={cancel}>Annuler</Button>}{canUpdate&&delivery.status==='planned'&&<Button size="xs" disabled={!selectedCategories.length} onClick={()=>changeStatus('preparing')}>Démarrer la préparation</Button>}{canUpdate&&delivery.status==='preparing'&&<Button size="xs" onClick={()=>changeStatus('quality_control')}>Contrôle opérationnel</Button>}{canUpdate&&delivery.status==='quality_control'&&<span title={!mandatoryComplete?'Les éléments obligatoires de la checklist doivent être terminés avant la remise du véhicule.':undefined}><Button size="xs" disabled={!mandatoryComplete} onClick={()=>changeStatus('ready')}>Valider pour livraison</Button></span>}<span className={`text-xs ml-auto ${financiallySettled?'text-emerald-700':'font-bold text-red-700'}`}>{canViewPayments&&remaining!=null?`Solde vente : ${remaining.toLocaleString('fr-FR')} XAF`:financiallySettled?'Règlement validé':'Règlement incomplet'}</span></div>{delivery.status==='planned'&&canUpdate&&<div className="mt-3 rounded-lg border bg-slate-50 p-3"><p className="text-xs font-bold">Étapes applicables à figer au démarrage</p><div className="mt-2 flex flex-wrap gap-3">{applicable.data?.map((category:any)=><label key={category.id} className="flex items-center gap-2 text-xs"><input type="checkbox" checked={selectedCategories.includes(String(category.id))} onChange={e=>setSelectedCategories(current=>e.target.checked?[...current,String(category.id)]:current.filter(id=>id!==String(category.id)))}/>{category.name} ({category.item_count})</label>)}</div><p className="mt-2 text-[11px] text-slate-500">Après démarrage, les libellés, ordres et obligations sont figés pour cette livraison.</p></div>}{!financiallySettled&&<p className="mt-3 rounded-lg border border-red-200 bg-red-50 p-3 text-xs text-red-800">Livraison impossible : le règlement intégral n’est pas confirmé.</p>}</Card>
    {delivered&&canCreateReturn&&<Card><CardHeader><CardTitle>Retour post-livraison</CardTitle></CardHeader><p className="mb-3 text-sm text-slate-600">Ouvre un dossier séparé sans réécrire la vente, la facture ni le PV de livraison.</p><Button loading={returnActions.create.isPending} onClick={createReturn}>Initier un retour post-livraison</Button></Card>}
    <DeliveryFinancialAuthorizationPanel saleId={String(delivery.sale_id)} total={Number(delivery.sale_total??0)+Number(delivery.delivery_services_total??0)} paid={Math.max(0,Number(delivery.sale_total??0)+Number(delivery.delivery_services_total??0)-Number(delivery.balance_due??0))} balance={Number(delivery.balance_due??0)} compact/>
    <DeliveryServicesPanel deliveryId={id!} readOnly={readOnly} currencyCode="XAF"/>
    <Card><CardHeader><CardTitle>Garantie contractuelle</CardTitle></CardHeader><div className="text-sm space-y-1">{warrantyUndetermined?<p className="font-semibold text-red-700">Décision à renseigner dans le dossier de vente avant la remise client.</p>:delivery.warranty_decision==='NOT_APPLICABLE'?<p>Garantie non applicable.</p>:<><p><b>Garantie applicable</b> — {delivery.warranty_provider_name}</p><p>{delivery.warranty_duration_months} mois · {delivery.warranty_mileage_limit==null?'sans plafond kilométrique':`${Number(delivery.warranty_mileage_limit).toLocaleString('fr-FR')} km`}</p><p>{delivery.warranty_status==='ACTIVE'?`Active du ${formatDate(delivery.warranty_start_date)} au ${formatDate(delivery.warranty_expiry_date)}`:'Activation automatique à la signature de livraison'}</p></>}</div></Card>
    <div className="grid lg:grid-cols-3 gap-5">{canChecklistView&&<Card className="lg:col-span-2"><CardHeader><div><CardTitle>Checklist par étapes</CardTitle><p className="text-xs text-slate-500">Obligatoires : {delivery.checklist_progress?.mandatoryCompleted??0}/{delivery.checklist_progress?.mandatoryTotal??0} · {delivery.checklist_progress?.percent??0}%</p></div></CardHeader>{checklistCategories.map((category:any,index:number)=><section key={category.id} className="mb-4"><div className="mb-1 flex justify-between text-xs font-bold uppercase text-slate-500"><span>{index+1}. {category.name_snapshot}</span><span>{category.mandatory_completed}/{category.mandatory_total} obligatoires · {category.status}</span></div><div className="divide-y rounded-lg border">{category.items.map((item:any)=><button key={item.id} disabled={!canChecklist||readOnly||delivery.status==='planned'||check.isPending} onClick={()=>updateItem(item)} className="w-full p-3 flex justify-between text-left disabled:cursor-default disabled:opacity-70"><span className="flex gap-3 text-sm">{item.is_completed?<CheckCircle2 className="w-5 h-5 text-emerald-600"/>:<Circle className="w-5 h-5 text-slate-300"/>}{item.name_snapshot}<span className="text-[10px] text-slate-500">{item.is_mandatory_snapshot?'OBLIGATOIRE':'FACULTATIF'}</span></span><span className="text-xs text-slate-500">{item.completed_by_name?`${item.completed_by_name} · ${formatDate(item.completed_at)}`:'À contrôler'}</span></button>)}</div></section>)}</Card>}<Card><CardHeader><CardTitle>Rendez-vous</CardTitle></CardHeader><dl className="text-sm space-y-3"><div><dt className="text-slate-500">Date</dt><dd className="font-semibold">{formatDate(delivery.scheduled_at)}</dd></div><div><dt className="text-slate-500">Responsable livraison</dt><dd>{delivery.delivery_specialist_name||'Non affecté'}</dd></div><div><dt className="text-slate-500">Lieu</dt><dd>{delivery.delivery_location||'Concession'}</dd></div><div><dt className="text-slate-500">Client</dt><dd>{delivery.customer_name}<br/>{delivery.phone}</dd></div><div><dt className="text-slate-500">Véhicule</dt><dd>{delivery.vehicle_label}<br/><span className="font-mono text-xs">{delivery.vin}</span></dd></div></dl></Card></div>
    <div className="grid lg:grid-cols-2 gap-5">{canDocumentsView&&<Card><CardHeader><div><CardTitle>Documents remis</CardTitle><p className="text-xs text-slate-500">La pièce jointe numérique et la remise physique sont suivies séparément.</p></div><Badge variant={documentsComplete?'success':'warning'}>{documentsComplete?'Complets':'Incomplets'}</Badge></CardHeader><div className="space-y-2">{documents.map((doc:any)=><div key={doc.id} className="flex items-center justify-between gap-2 text-sm"><label className="flex items-center gap-2"><input type="checkbox" disabled={!canDocuments||readOnly||actions.markDocument.isPending} checked={Boolean(doc.received)} onChange={e=>actions.markDocument.mutate({deliveryId:id,documentId:String(doc.id),received:e.target.checked})}/><span>{doc.document_name}{doc.is_required&&' *'}</span></label>{doc.document_url&&<Button size="xs" variant="outline" icon={<Download className="h-3 w-3"/>} onClick={()=>void downloadDocument(doc)}>Télécharger</Button>}</div>)}{canDocuments&&!readOnly&&<><input value={documentName} onChange={e=>setDocumentName(e.target.value)} placeholder="Nom du document physique" className="w-full border rounded p-2 text-sm"/><input type="file" accept="application/pdf,image/png,image/jpeg" onChange={e=>setFile(e.target.files?.[0]??null)} className="text-xs"/><Button size="xs" icon={<Upload className="w-3 h-3"/>} loading={actions.addDocument.isPending} disabled={!documentName} onClick={upload}>Ajouter au dossier</Button></>}</div></Card>}
    <Card><CardHeader><CardTitle>Signature réelle du client</CardTitle></CardHeader>{delivered?<p className="text-sm text-emerald-700">Remise client finalisée.</p>:canSign&&canComplete?<form onSubmit={sign} className="space-y-3"><input required value={signer} onChange={e=>setSigner(e.target.value)} placeholder="Nom du signataire" className="w-full border rounded p-2 text-sm"/><input required type="number" min={delivery.vehicle_mileage} value={mileage} onChange={e=>setMileage(e.target.value)} placeholder="Kilométrage à la remise" className="w-full border rounded p-2 text-sm"/><SignaturePad onChange={setSignature}/><label className="flex gap-2 text-xs"><input type="checkbox" checked={accepted} onChange={e=>setAccepted(e.target.checked)}/>Le client confirme la réception du véhicule, des clés et des documents.</label><Button type="submit" className="w-full" icon={<FileCheck className="w-4 h-4"/>} loading={signMutation.isPending} disabled={signDisabled||signMutation.isPending}>{signMutation.isPending?'Finalisation...':'Signer et livrer'}</Button>{warrantyUndetermined&&<p className="text-xs font-semibold text-red-700">La décision de garantie est obligatoire avant la livraison.</p>}{!mandatoryComplete&&<p className="text-xs text-amber-700">Les éléments obligatoires de la checklist doivent être terminés avant la remise du véhicule.</p>}{!documentsComplete&&<p className="text-xs text-amber-700">Les documents obligatoires ne sont pas tous remis.</p>}</form>:<p className="text-sm text-slate-500">Les permissions de signature et de finalisation sont requises.</p>}</Card></div>
  </div>;
};

const SignaturePad:React.FC<{onChange:(value:string)=>void}>=({onChange})=>{const ref=useRef<HTMLCanvasElement>(null),drawing=useRef(false);useEffect(()=>{const canvas=ref.current;if(!canvas)return;canvas.width=canvas.clientWidth*2;canvas.height=160;const context=canvas.getContext('2d');if(context){context.scale(2,2);context.lineWidth=2;context.lineCap='round'}},[]);const point=(event:React.PointerEvent<HTMLCanvasElement>)=>{const rect=event.currentTarget.getBoundingClientRect();return{x:event.clientX-rect.left,y:event.clientY-rect.top}};return <div><canvas ref={ref} aria-label="Zone de signature" className="w-full h-20 border rounded bg-white touch-none" onPointerDown={e=>{drawing.current=true;const p=point(e);ref.current?.getContext('2d')?.beginPath();ref.current?.getContext('2d')?.moveTo(p.x,p.y)}} onPointerMove={e=>{if(!drawing.current)return;const p=point(e),context=ref.current?.getContext('2d');context?.lineTo(p.x,p.y);context?.stroke()}} onPointerUp={()=>{drawing.current=false;if(ref.current)onChange(ref.current.toDataURL('image/png'))}}/><button type="button" className="text-xs underline" onClick={()=>{const canvas=ref.current;canvas?.getContext('2d')?.clearRect(0,0,canvas.width,canvas.height);onChange('')}}>Effacer la signature</button></div>};
